export type LitLevel = 'A1' | 'A1.1' | 'A2' | 'B1' | 'B2' | 'C1'
export type LitKind = 'graded' | 'original'

export interface Localized {
  ru: string
  kz: string
  en: string
}

export interface LiteratureBook {
  id: string
  level: LitLevel
  kind: LitKind
  title: string
  author: string
  year: number
  series: string | null
  headwords: number | null
  genre: Localized
  about: Localized
}

export const LIT_LEVELS: LitLevel[] = ['A1', 'A1.1', 'A2', 'B1', 'B2', 'C1']

export const LITERATURE: LiteratureBook[] = [
  {
    id: 'red-roses',
    level: 'A1',
    kind: 'graded',
    title: 'Red Roses',
    author: 'Christine Lindop',
    year: 2000,
    series: 'Oxford Bookworms Starter',
    headwords: 250,
    genre: { ru: 'любовная история', kz: 'махаббат хикаясы', en: 'romance' },
    about: {
      ru: 'Короткая история о подарке и недоразумении. Почти весь текст — диалоги, словарь очень маленький.',
      kz: 'Сыйлық пен түсінбеушілік туралы қысқа әңгіме. Мәтіннің көбі диалог, сөздігі өте шағын.',
      en: 'A short story about a gift and a misunderstanding. Mostly dialogue, with a very small vocabulary.',
    },
  },
  {
    id: 'love-or-money',
    level: 'A1',
    kind: 'graded',
    title: 'Love or Money?',
    author: 'Rowena Akinyemi',
    year: 2000,
    series: 'Oxford Bookworms Starter',
    headwords: 250,
    genre: { ru: 'детектив', kz: 'детектив', en: 'mystery' },
    about: {
      ru: 'В семье умирает женщина, и каждый из близких что-то скрывает. Удобный первый детектив на английском.',
      kz: 'Отбасында әйел қайтыс болады, жақындарының әрқайсысы бірдеңені жасырады. Ағылшын тіліндегі алғашқы детективке ыңғайлы.',
      en: 'A woman dies, and everyone close to her is hiding something. A gentle first mystery in English.',
    },
  },
  {
    id: 'elephant-man',
    level: 'A1',
    kind: 'graded',
    title: 'The Elephant Man',
    author: 'Tim Vicary',
    year: 2000,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'биография', kz: 'өмірбаян', en: 'biography' },
    about: {
      ru: 'История Джозефа Меррика в викторианском Лондоне. Короткие главы и понятный сюжет про достоинство человека.',
      kz: 'Виктория дәуіріндегі Лондондағы Джозеф Мерриктің тарихы. Қысқа тараулар және адам қадірі туралы түсінікті сюжет.',
      en: 'Joseph Merrick’s life in Victorian London. Short chapters and a clear story about human dignity.',
    },
  },
  {
    id: 'little-princess',
    level: 'A1',
    kind: 'graded',
    title: 'A Little Princess',
    author: 'Frances Hodgson Burnett',
    year: 1905,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'повесть', kz: 'повесть', en: 'story' },
    about: {
      ru: 'Сара Кру живёт в школе-пансионе и теряет всё за одну ночь. Адаптация держит сюжет, но убирает сложный язык оригинала 1905 года.',
      kz: 'Сара Кру мектеп-пансионатта тұрады және бір түнде бәрінен айырылады. Бейімдеу сюжетті сақтайды, бірақ 1905 жылғы түпнұсқаның күрделі тілін алып тастайды.',
      en: 'Sara Crewe lives at a boarding school and loses everything overnight. The adaptation keeps the plot and drops the 1905 original’s difficult language.',
    },
  },
  {
    id: 'wizard-of-oz',
    level: 'A1',
    kind: 'graded',
    title: 'The Wizard of Oz',
    author: 'L. Frank Baum',
    year: 1900,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'сказка', kz: 'ертегі', en: 'fantasy' },
    about: {
      ru: 'Дороти ищет дорогу домой. Знакомый сюжет помогает не терять нить, даже если часть слов новая.',
      kz: 'Дороти үйге қайтар жолды іздейді. Таныс сюжет кей сөздер жаңа болса да, оқиғадан адаспауға көмектеседі.',
      en: 'Dorothy looks for the way home. A familiar plot keeps the story clear even when some words are new.',
    },
  },
  {
    id: 'tom-sawyer',
    level: 'A1',
    kind: 'graded',
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    year: 1876,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'приключения', kz: 'шытырман оқиға', en: 'adventure' },
    about: {
      ru: 'Том, побелка забора и пещера. Хороший переход от диалогов к небольшому повествованию.',
      kz: 'Том, қоршауды әктеу және үңгір. Диалогтан шағын баяндауға жақсы көшу.',
      en: 'Tom, the fence, and the cave. A good step from dialogue into a short narrative.',
    },
  },

  {
    id: 'phantom',
    level: 'A1.1',
    kind: 'graded',
    title: 'The Phantom of the Opera',
    author: 'Gaston Leroux',
    year: 1910,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'готика', kz: 'готика', en: 'gothic' },
    about: {
      ru: 'Под Парижской оперой живёт человек в маске. Напряжение есть, предложения остаются короткими.',
      kz: 'Париж операсының астында бетперделі адам тұрады. Шиеленіс бар, сөйлемдер қысқа болып қалады.',
      en: 'A masked man lives under the Paris Opera. There is suspense, and the sentences stay short.',
    },
  },
  {
    id: 'white-death',
    level: 'A1.1',
    kind: 'graded',
    title: 'White Death',
    author: 'Tim Vicary',
    year: 2000,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'триллер', kz: 'триллер', en: 'thriller' },
    about: {
      ru: 'Сара ищет брата и выходит на торговлю героином. Современный сюжет, без архаичной лексики.',
      kz: 'Сара ағасын іздеп, героин саудасына тап болады. Қазіргі сюжет, ескі сөздерсіз.',
      en: 'Sarah looks for her brother and finds a heroin trade. A modern plot, without old-fashioned vocabulary.',
    },
  },
  {
    id: 'dukes-son',
    level: 'A1.1',
    kind: 'graded',
    title: "Sherlock Holmes and the Duke's Son",
    author: 'Arthur Conan Doyle',
    year: 1903,
    series: 'Oxford Bookworms Stage 1',
    headwords: 400,
    genre: { ru: 'детектив', kz: 'детектив', en: 'detective' },
    about: {
      ru: 'Две короткие истории Холмса. Удобно читать по одной за вечер и пересказывать улики своими словами.',
      kz: 'Холмстың екі қысқа хикаясы. Кешке біреуін оқып, дәлелдерді өз сөзіңізбен айтып беруге ыңғайлы.',
      en: 'Two short Holmes stories. Easy to read one in an evening and retell the clues in your own words.',
    },
  },
  {
    id: 'alice',
    level: 'A1.1',
    kind: 'graded',
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    year: 1865,
    series: 'Oxford Bookworms Stage 2',
    headwords: 700,
    genre: { ru: 'сказка', kz: 'ертегі', en: 'fantasy' },
    about: {
      ru: 'Алиса падает в нору и попадает в мир, где правила не работают. Словарь шире, чем на Stage 1, сюжет всё ещё держит внимание.',
      kz: 'Алиса інге құлап, ережелер жұмыс істемейтін әлемге түседі. Сөздік Stage 1-ден кеңірек, сюжет назарды әлі ұстайды.',
      en: 'Alice falls down a hole into a world where the rules do not work. A wider vocabulary than Stage 1, and the plot still carries you.',
    },
  },
  {
    id: 'anne',
    level: 'A1.1',
    kind: 'graded',
    title: 'Anne of Green Gables',
    author: 'L. M. Montgomery',
    year: 1908,
    series: 'Oxford Bookworms Stage 2',
    headwords: 700,
    genre: { ru: 'роман взросления', kz: 'ержету романы', en: 'coming of age' },
    about: {
      ru: 'Рыжую Энн по ошибке привозят на ферму вместо мальчика. Много бытовых сцен: школа, подруги, характер.',
      kz: 'Жирен Эннді қателесіп ұлдың орнына фермаға әкеледі. Тұрмыстық көрініс көп: мектеп, достар, мінез.',
      en: 'Red-haired Anne is sent to a farm by mistake, instead of a boy. Lots of everyday scenes: school, friends, character.',
    },
  },
  {
    id: 'huckleberry',
    level: 'A1.1',
    kind: 'graded',
    title: 'The Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    year: 1884,
    series: 'Oxford Bookworms Stage 2',
    headwords: 700,
    genre: { ru: 'приключения', kz: 'шытырман оқиға', en: 'adventure' },
    about: {
      ru: 'Гек и Джим плывут по Миссисипи. Адаптация убирает диалект оригинала, из-за которого книгу трудно читать даже сильным студентам.',
      kz: 'Гек пен Джим Миссисипимен жүзеді. Бейімдеу түпнұсқаның диалектісін алып тастайды — сол диалект кітапты мықты студенттерге де қиындатады.',
      en: 'Huck and Jim travel down the Mississippi. The adaptation removes the original dialect, which makes the book hard even for strong students.',
    },
  },

  {
    id: 'dracula',
    level: 'A2',
    kind: 'graded',
    title: 'Dracula',
    author: 'Bram Stoker',
    year: 1897,
    series: 'Oxford Bookworms Stage 2',
    headwords: 700,
    genre: { ru: 'ужас', kz: 'қорқынышты', en: 'horror' },
    about: {
      ru: 'Джонатан Харкер едет в замок в Трансильвании. Классика в объёме, который реально дочитать за неделю.',
      kz: 'Джонатан Харкер Трансильваниядағы сарайға барады. Бір аптада шынымен аяқтауға болатын көлемдегі классика.',
      en: 'Jonathan Harker travels to a castle in Transylvania. A classic short enough to finish in a week.',
    },
  },
  {
    id: 'crusoe',
    level: 'A2',
    kind: 'graded',
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    year: 1719,
    series: 'Oxford Bookworms Stage 2',
    headwords: 700,
    genre: { ru: 'приключения', kz: 'шытырман оқиға', en: 'adventure' },
    about: {
      ru: 'Человек один на острове учится выживать. Полезный текст про последовательность действий: сначала, потом, наконец.',
      kz: 'Аралда жалғыз қалған адам аман қалуды үйренеді. Әрекет реті туралы пайдалы мәтін: алдымен, содан кейін, ақыры.',
      en: 'A man alone on an island learns to survive. Useful language for sequences: first, then, finally.',
    },
  },
  {
    id: 'secret-garden',
    level: 'A2',
    kind: 'graded',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    year: 1911,
    series: 'Oxford Bookworms Stage 3',
    headwords: 1000,
    genre: { ru: 'повесть', kz: 'повесть', en: 'story' },
    about: {
      ru: 'Мэри находит запертый сад в Йоркшире. На Stage 3 уже появляются описания природы и более длинные абзацы.',
      kz: 'Мэри Йоркширде құлыпталған бақ табады. Stage 3-те табиғат сипаттамасы мен ұзындау абзацтар пайда болады.',
      en: 'Mary finds a locked garden in Yorkshire. Stage 3 brings nature description and longer paragraphs.',
    },
  },
  {
    id: 'frankenstein',
    level: 'A2',
    kind: 'graded',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    year: 1818,
    series: 'Oxford Bookworms Stage 3',
    headwords: 1000,
    genre: { ru: 'готика', kz: 'готика', en: 'gothic' },
    about: {
      ru: 'Учёный создаёт существо и отказывается от него. Удобный мост к разговору об ответственности, без языка оригинала XIX века.',
      kz: 'Ғалым тіршілік иесін жасайды да, одан бас тартады. XIX ғасыр түпнұсқасының тілінсіз жауапкершілік туралы әңгімеге ыңғайлы көпір.',
      en: 'A scientist creates a being and abandons it. A bridge into a talk about responsibility, without 19th-century prose.',
    },
  },
  {
    id: 'railway-children',
    level: 'A2',
    kind: 'graded',
    title: 'The Railway Children',
    author: 'Edith Nesbit',
    year: 1906,
    series: 'Oxford Bookworms Stage 3',
    headwords: 1000,
    genre: { ru: 'семейная история', kz: 'отбасы хикаясы', en: 'family story' },
    about: {
      ru: 'Трое детей переезжают к железной дороге, пока отца нет дома. Много разговорной речи и бытовых деталей.',
      kz: 'Әкесі үйде жоқта үш бала теміржол маңына көшеді. Ауызекі сөз бен тұрмыстық деталь көп.',
      en: 'Three children move beside a railway while their father is away. Plenty of spoken English and everyday detail.',
    },
  },
  {
    id: 'call-of-the-wild',
    level: 'A2',
    kind: 'graded',
    title: 'The Call of the Wild',
    author: 'Jack London',
    year: 1903,
    series: 'Oxford Bookworms Stage 3',
    headwords: 1000,
    genre: { ru: 'приключения', kz: 'шытырман оқиға', en: 'adventure' },
    about: {
      ru: 'Пёс Бак попадает на Аляску во время золотой лихорадки. Короткий, жёсткий сюжет — хороший тренировочный объём перед B1.',
      kz: 'Бак иті алтын безгегі кезінде Аляскаға түседі. Қысқа, қатал сюжет — B1 алдындағы жақсы жаттығу көлемі.',
      en: 'The dog Buck is taken to Alaska in the gold rush. A short, hard story — good training length before B1.',
    },
  },

  {
    id: 'hound',
    level: 'B1',
    kind: 'graded',
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    year: 1902,
    series: 'Oxford Bookworms Stage 4',
    headwords: 1400,
    genre: { ru: 'детектив', kz: 'детектив', en: 'detective' },
    about: {
      ru: 'Холмс расследует смерть на торфяниках Девона. На этом уровне уже нужно держать в голове несколько линий сразу.',
      kz: 'Холмс Девон батпағындағы өлімді тергейді. Бұл деңгейде бірнеше желіні бірден есте сақтау керек.',
      en: 'Holmes investigates a death on the Devon moor. At this level you need to hold several threads at once.',
    },
  },
  {
    id: 'three-men',
    level: 'B1',
    kind: 'graded',
    title: 'Three Men in a Boat',
    author: 'Jerome K. Jerome',
    year: 1889,
    series: 'Oxford Bookworms Stage 4',
    headwords: 1400,
    genre: { ru: 'юмор', kz: 'әзіл', en: 'humour' },
    about: {
      ru: 'Трое друзей плывут по Темзе и всё время попадают в нелепые ситуации. Редкая адаптированная книга, где главное — тон, а не интрига.',
      kz: 'Үш дос Темзамен жүзіп, үнемі күлкілі жағдайға түседі. Бастысы интрига емес, үн болатын сирек бейімделген кітап.',
      en: 'Three friends travel up the Thames and fall into absurd situations. A rare graded book where tone matters more than plot.',
    },
  },
  {
    id: 'thirty-nine-steps',
    level: 'B1',
    kind: 'graded',
    title: 'The Thirty-Nine Steps',
    author: 'John Buchan',
    year: 1915,
    series: 'Oxford Bookworms Stage 4',
    headwords: 1400,
    genre: { ru: 'шпионский роман', kz: 'тыңшылық роман', en: 'spy novel' },
    about: {
      ru: 'Ричард Хэнней бежит через Шотландию с тайной, которую некому отдать. Быстрый сюжет тренирует чтение без остановки на каждом слове.',
      kz: 'Ричард Хэнней құпиямен Шотландияны аралап қашады, оны беретін адам жоқ. Жылдам сюжет әр сөзде тоқтамай оқуды жаттықтырады.',
      en: 'Richard Hannay runs across Scotland with a secret and nobody to give it to. A fast plot trains you to read without stopping at every word.',
    },
  },
  {
    id: 'lord-of-the-flies',
    level: 'B1',
    kind: 'graded',
    title: 'Lord of the Flies',
    author: 'William Golding',
    year: 1954,
    series: 'Oxford Bookworms Stage 4',
    headwords: 1400,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Мальчики остаются одни на острове, и порядок быстро распадается. После адаптации легче браться за оригинал на B2.',
      kz: 'Ұлдар аралда жалғыз қалады, тәртіп тез ыдырап кетеді. Бейімдеуден кейін B2-де түпнұсқаға кірісу оңайырақ.',
      en: 'Boys are left alone on an island, and order falls apart. The adaptation makes the original easier at B2.',
    },
  },
  {
    id: 'of-mice-and-men',
    level: 'B1',
    kind: 'original',
    title: 'Of Mice and Men',
    author: 'John Steinbeck',
    year: 1937,
    series: null,
    headwords: null,
    genre: { ru: 'повесть', kz: 'повесть', en: 'novella' },
    about: {
      ru: 'Джордж и Ленни ищут работу на ранчо в Калифорнии. Короткий оригинал: простые предложения, разговорная речь, сильный финал.',
      kz: 'Джордж пен Ленни Калифорниядағы ранчодан жұмыс іздейді. Қысқа түпнұсқа: қарапайым сөйлем, ауызекі сөз, күшті финал.',
      en: 'George and Lennie look for ranch work in California. A short original: plain sentences, spoken English, a hard ending.',
    },
  },
  {
    id: 'animal-farm',
    level: 'B1',
    kind: 'original',
    title: 'Animal Farm',
    author: 'George Orwell',
    year: 1945,
    series: null,
    headwords: null,
    genre: { ru: 'повесть-притча', kz: 'мысал-повесть', en: 'fable' },
    about: {
      ru: 'Животные прогоняют хозяина фермы, а новые правила постепенно меняются. Один из самых доступных оригиналов перед B2.',
      kz: 'Жануарлар ферма иесін қуып шығады, жаңа ережелер біртіндеп өзгереді. B2 алдындағы ең қолжетімді түпнұсқалардың бірі.',
      en: 'The animals drive out the farmer, and the new rules slowly change. One of the most approachable originals before B2.',
    },
  },

  {
    id: 'gatsby',
    level: 'B2',
    kind: 'original',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Ник Каррауэй рассказывает о соседе, который устраивает вечеринки ради одной женщины. Короткий роман, но метафоры уже нужно читать медленно.',
      kz: 'Ник Каррауэй бір әйел үшін кеш беретін көршісі туралы баяндайды. Роман қысқа, бірақ метафораларды баяу оқу керек.',
      en: 'Nick Carraway tells the story of a neighbour who gives parties for one woman. A short novel, but the metaphors need slow reading.',
    },
  },
  {
    id: 'nineteen-eighty-four',
    level: 'B2',
    kind: 'original',
    title: 'Nineteen Eighty-Four',
    author: 'George Orwell',
    year: 1949,
    series: null,
    headwords: null,
    genre: { ru: 'антиутопия', kz: 'антиутопия', en: 'dystopia' },
    about: {
      ru: 'Уинстон работает в Министерстве правды и начинает сомневаться в партии. Плотная лексика власти, слежки и языка.',
      kz: 'Уинстон Ақиқат министрлігінде жұмыс істейді де, партияға күмәндана бастайды. Билік, бақылау және тіл туралы тығыз лексика.',
      en: 'Winston works at the Ministry of Truth and begins to doubt the Party. Dense vocabulary of power, surveillance, and language.',
    },
  },
  {
    id: 'mockingbird',
    level: 'B2',
    kind: 'original',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    year: 1960,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Скаут наблюдает, как её отец защищает человека в суде маленького южного города. Длиннее Гэтсби, но синтаксис прозрачный.',
      kz: 'Скаут әкесінің кішкентай оңтүстік қаладағы сотта адамды қорғағанын бақылайды. Гэтсбиден ұзын, бірақ синтаксисі ашық.',
      en: 'Scout watches her father defend a man in a small Southern town. Longer than Gatsby, with clear syntax.',
    },
  },
  {
    id: 'old-man',
    level: 'B2',
    kind: 'original',
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    year: 1952,
    series: null,
    headwords: null,
    genre: { ru: 'повесть', kz: 'повесть', en: 'novella' },
    about: {
      ru: 'Старый рыбак три дня держит на леске большую рыбу. Короткие фразы Хемингуэя — хороший мост от адаптации к авторскому стилю.',
      kz: 'Кәрі балықшы үш күн бойы үлкен балықты қармақта ұстайды. Хемингуэйдің қысқа фразалары бейімдеуден автор стиліне жақсы көпір.',
      en: 'An old fisherman holds a great fish on the line for three days. Hemingway’s short sentences bridge graded text and an author’s style.',
    },
  },
  {
    id: 'brave-new-world',
    level: 'B2',
    kind: 'original',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    year: 1932,
    series: null,
    headwords: null,
    genre: { ru: 'антиутопия', kz: 'антиутопия', en: 'dystopia' },
    about: {
      ru: 'Общество, где людей выращивают по кастам и успокаивают развлечением. Рядом с «1984» даёт второй язык разговора об устройстве мира.',
      kz: 'Адамдарды каста бойынша өсіріп, ойын-сауықпен тыныштандыратын қоғам. «1984» қасында әлем құрылысы туралы екінші тіл береді.',
      en: 'A society that breeds people by caste and keeps them quiet with entertainment. Next to 1984, it gives a second vocabulary for how a world is built.',
    },
  },
  {
    id: 'dorian-gray',
    level: 'B2',
    kind: 'original',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    year: 1890,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Портрет стареет вместо Дориана. Диалоги Уайльда полны афоризмов — их полезно выписывать, а не только понимать сюжет.',
      kz: 'Портрет Дорианның орнына қартаяды. Уайльд диалогтары афоризмге толы — оларды сюжетті түсінумен шектелмей, жазып алған дұрыс.',
      en: 'The portrait ages instead of Dorian. Wilde’s dialogue is full of aphorisms worth copying out, not only following for plot.',
    },
  },

  {
    id: 'pride',
    level: 'C1',
    kind: 'original',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Элизабет Беннет и мистер Дарси судят друг друга слишком быстро. Ирония Остин спрятана в вежливых фразах — это уже уровень внимательного чтения.',
      kz: 'Элизабет Беннет пен мистер Дарси бір-бірін тым тез бағалайды. Остиннің ирониясы сыпайы фразалардың ішінде — бұл енді мұқият оқу деңгейі.',
      en: 'Elizabeth Bennet and Mr Darcy judge each other too quickly. Austen’s irony sits inside polite sentences — this is close reading.',
    },
  },
  {
    id: 'jane-eyre',
    level: 'C1',
    kind: 'original',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    year: 1847,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Джейн проходит пансион, гувернантство и дом с тайной. Длинный оригинал с устойчивой повествовательной манерой XIX века.',
      kz: 'Джейн пансионат, гувернанттық және құпиясы бар үйден өтеді. XIX ғасырдың тұрақты баяндау мәнері бар ұзын түпнұсқа.',
      en: 'Jane moves through school, governess work, and a house with a secret. A long original in a steady 19th-century narrative voice.',
    },
  },
  {
    id: 'heart-of-darkness',
    level: 'C1',
    kind: 'original',
    title: 'Heart of Darkness',
    author: 'Joseph Conrad',
    year: 1899,
    series: null,
    headwords: null,
    genre: { ru: 'повесть', kz: 'повесть', en: 'novella' },
    about: {
      ru: 'Марлоу плывёт по реке в Конго в поисках Куртца. Короткий текст, но плотность образов выше, чем в романах B2.',
      kz: 'Марлоу Куртцты іздеп Конго өзенімен жүзеді. Мәтін қысқа, бірақ образдардың тығыздығы B2 романдарынан жоғары.',
      en: 'Marlow travels up a Congo river looking for Kurtz. A short text, denser in image than the B2 novels.',
    },
  },
  {
    id: 'things-fall-apart',
    level: 'C1',
    kind: 'original',
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    year: 1958,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Оконкво живёт в деревне игбо в момент прихода колониальной власти. Ясный английский и другая культурная рамка, не британский канон.',
      kz: 'Оконкво отаршыл билік келген кезде игбо ауылында тұрады. Анық ағылшын және британ каноны емес, басқа мәдени шеңбер.',
      en: 'Okonkwo lives in an Igbo village as colonial rule arrives. Clear English, and a cultural frame outside the British canon.',
    },
  },
  {
    id: 'never-let-me-go',
    level: 'C1',
    kind: 'original',
    title: 'Never Let Me Go',
    author: 'Kazuo Ishiguro',
    year: 2005,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Кэти вспоминает школу-интернат, в которой дети растут с заранее назначенной судьбой. Спокойный современный стиль, смысл собирается из недосказанности.',
      kz: 'Кэти тағдыры алдын ала белгіленген балалар өскен интернатты еске алады. Сабырлы қазіргі стиль, мән айтылмай қалған жерден жиналады.',
      en: 'Kathy remembers a boarding school where children grow up with a fate already assigned. Calm contemporary prose; the meaning sits in what is left unsaid.',
    },
  },
  {
    id: 'aitmatov-day',
    level: 'C1',
    kind: 'original',
    title: 'The Day Lasts More Than a Hundred Years',
    author: 'Chingiz Aitmatov',
    year: 1980,
    series: null,
    headwords: null,
    genre: { ru: 'роман', kz: 'роман', en: 'novel' },
    about: {
      ru: 'Едигей везёт хоронить друга через сарозекскую степь, а память тянет в прошлое рода. Английский перевод романа, близкого студентам ЗКУ по географии и памяти.',
      kz: 'Едігей досын жерлеуге Сарыөзек даласымен барады, естелік рудың өткеніне тартады. Географиясы мен жадысы ЗКУ студенттеріне жақын романның ағылшынша аудармасы.',
      en: 'Yedigei takes a friend to be buried across the Sary-Ozek steppe, and memory pulls him into the past of his people. An English translation close to WKU students in place and memory.',
    },
  },
]
