'use client'

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

export type ZkuLang = 'ru' | 'kz' | 'en'

export const ZKU_T = {
  ru: {
    nav: {
      home: 'Главная', course: 'Мой курс', vocab: 'Словарь',
      progress: 'Прогресс', placement: 'Placement test',
      writing: 'Writing Coach', certs: 'Сертификаты',
      leaderboard: 'Рейтинг', achievements: 'Достижения',
    },
    user: {
      profile: 'Мой профиль', certs: 'Сертификаты',
      achievements: 'Достижения', settings: 'Настройки', logout: 'Выйти из аккаунта',
    },
    dash: {
      cabinet: 'КАБИНЕТ СТУДЕНТА', subtitle: 'Сегодня отличный день, чтобы выучить что-то новое',
      greeting: 'Привет', streak: 'дней подряд', xp: 'XP всего',
      rank: 'Место в группе', lessons: 'Уроков пройдено',
      continue_tag: '▶ ПРОДОЛЖИТЬ', start_lesson: '▶ Продолжить урок',
      block: 'Блок', of: 'из', to_level: 'До следующего уровня',
      xp_left: 'XP до следующего уровня', streak_label: 'Стрик', record: 'Рекорд', days: 'дней',
      skills: 'Прогресс по навыкам', details: 'подробнее →',
      activity: 'Последняя активность', see_all: 'смотреть всё →',
      reading: 'Reading', listening: 'Listening', grammar: 'Grammar',
      writing: 'Writing', writing_sub: 'Тренажёр письма',
      vocab_btn: 'Словарь', texts: 'текстов', audio: 'аудио',
      themes: 'тем по уровню', words_wait: 'слов ждут',
      all_courses: 'Все курсы', test_level: 'Пройти тест',
      start_first: 'Начни первый урок', start_first_sub: 'Пройди первый урок, чтобы начать отслеживать прогресс',
      go_to_courses: 'К курсам',
      no_skills_title: 'Пока нет данных о навыках', no_skills_sub: 'Пройди уроки, чтобы увидеть прогресс',
      no_activity_title: 'Нет активности', no_activity_sub: 'Начни учиться — здесь появится история',
    },
    course: {
      title: 'Программа курса', subtitle: 'Полный путь от A1 до C1 · 600+ уроков',
      overall: 'Общий прогресс', modules_done: 'модулей пройдено',
      lessons_done: 'уроков пройдено', modules: 'модулей', lessons: 'уроков',
      hours: 'часов', words: 'слов', continue_btn: 'Продолжить →', start_btn: 'Начать →',
      locked: 'Заблокировано', in_progress: 'В процессе', passed: 'Пройден',
      platform: 'ЗКУ им. М. Утемісова · English Platform',
      coming_soon_title: 'Контент скоро появится', coming_soon_sub: 'раздел в разработке',
      level_locked_title: 'Уровень заблокирован',
      level_locked_sub: 'Завершите предыдущий уровень, чтобы открыть этот',
      back_to_course: '← Вернуться к курсу', module_word: 'Модуль',
      beginner_sub: 'Начинающий', elementary_sub: 'Элементарный',
      pre_int_sub: 'Предсредний', intermediate_sub: 'Средний',
      upper_int_sub: 'Выше среднего', advanced_sub: 'Продвинутый',
      desc_a1:  'Базовые фразы, приветствия и простые предложения. Идеально для тех, кто начинает с нуля.',
      desc_a11: 'Повседневные ситуации: покупки, знакомства, описание людей и предметов.',
      desc_a2:  'Общение на базовые темы, простые диалоги, описание событий и планов.',
      desc_b1:  'Уверенное общение на знакомые темы, путешествия, рабочая переписка.',
      desc_b2:  'Сложные тексты, дискуссии, профессиональная речь и деловая переписка.',
      desc_c1:  'Беглая речь, академические тексты, бизнес-уровень и международные экзамены.',
      title_a1:  'С нуля до базы',
      title_a11: 'Повседневный английский',
      title_a2:  'Базовое общение',
      title_b1:  'Уверенное общение',
      title_b2:  'Готов к IELTS 6.0',
      title_c1:  'Готов к IELTS 7.0+',
    },
    vocab: {
      title: 'Мой словарь', subtitle: 'Карточки для повторения · интервальное обучение',
      total: 'слов', review: 'Повторение', learned: 'Выучено', reps: 'Повторений',
      due_banner: 'слов ждут повторения', due_sub: 'По методу интервального повторения',
      all_done: 'Словарь изучен!', come_later: 'Следующие слова появятся позже',
      tap_hint: 'Показать перевод',
      forgot: 'Ещё раз', hard: 'Трудно', good: 'Знаю', easy: 'Легко',
      back_lesson: 'К уроку',
    },
    placement: {
      title: 'Placement Test', subtitle: 'Определи свой уровень английского от A1 до C1',
      duration: '15–20 минут', questions: 'До 30 вопросов',
      result: 'Твой CEFR уровень', adaptive: 'Подстраивается под тебя',
      tip: 'Совет: отвечай честно — тест поможет найти правильный уровень',
      start: 'Начать тест →', question_of: 'из', level_badge: 'УРОВЕНЬ',
      q_of_6: 'Вопрос', answer: 'Ответить →', reset: 'Сбросить',
      your_level: 'ТВОЙ УРОВЕНЬ', correct: 'Правильных ответов',
      by_level: 'Результаты по уровням', mistakes: 'Разбор ошибок',
      your_ans: 'Твой ответ', correct_ans: 'Правильно',
      go_course: 'Перейти к курсу', retry: 'Пройти заново',
      passed_lv: 'Пройден', failed_lv: 'Остановлено',
      word_hint: 'Нажимай на слова снизу чтобы составить предложение',
    },
    certs: {
      title: 'Мои сертификаты',
      subtitle: 'Официальные сертификаты CEFR выдаются после прохождения каждого уровня',
      earned: 'Получено', in_progress: 'В процессе', locked: 'Заблокировано',
      how_title: 'Как получить сертификат?',
      how_body: 'Пройди все модули уровня и набери минимум 80% в каждом финальном тесте.',
      to_courses: 'К курсам →', issued_to: 'ВЫДАН СТУДЕНТУ',
      skills_conf: 'Навыки подтверждены', issued_at: 'Дата выдачи', org: 'Организация',
      flip_hint: 'Нажми чтобы перевернуть · скачать сертификат',
      download: 'Скачать PDF', continue: 'Продолжить обучение →',
      locked_msg: 'Завершите предыдущий уровень чтобы открыть', left_to: '% до сертификата',
      completion_cert: 'Сертификат об окончании',
      download_coming: 'Сертификат будет доступен после завершения уровня',
      footer_note: 'Сертификаты признаются работодателями Казахстана и международными организациями · Соответствует CEFR стандарту',
    },
    profile: {
      tab_profile: 'Профиль', tab_security: 'Безопасность',
      tab_notifs: 'Уведомления', tab_stats: 'Статистика',
      title_info: 'Личная информация', title_study: 'Учебная информация',
      title_pass: 'Смена пароля', title_notifs: 'Настройка уведомлений',
      title_stats: 'Прогресс по навыкам', title_act: 'Последняя активность',
      save: 'Сохранить изменения', saved: 'Сохранено',
      full_name: 'Полное имя', email: 'Email', phone: 'Телефон',
      city: 'Город', bio: 'О себе', group: 'Группа', level: 'Текущий уровень',
      reg_date: 'Дата регистрации', last_active: 'Последняя активность',
      old_pass: 'Текущий пароль', new_pass: 'Новый пароль', conf_pass: 'Подтвердите пароль',
      sessions: 'Активные сессии', current: 'Текущая', end_session: 'Завершить', today: 'Сегодня',
      pass_changed: 'Пароль успешно изменён',
      pass_fill_all: 'Заполните все поля', pass_mismatch: 'Пароли не совпадают', pass_too_short: 'Минимум 8 символов',
      pass_placeholder: 'Минимум 8 символов', pass_confirm_placeholder: 'Повторите новый пароль',
      level_auto_hint: 'Уровень определяется автоматически на основе Placement Test и прогресса курса',
      stat_xp: 'Всего XP', stat_streak: 'Стрик дней', stat_best: 'Лучший стрик', stat_lessons: 'Уроков пройдено',
      achievements_title: 'Достижения', achievements_empty: 'Пока нет достижений', achievements_empty_sub: 'Проходи уроки и тесты, чтобы получить первые достижения',
      no_activity: 'Нет активности', no_activity_sub: 'История появится после первых уроков',
      no_skills: 'Нет данных', no_skills_sub: 'Данные появятся после прохождения уроков',
      notif_hw_label: 'Домашние задания',    notif_hw_desc: 'Новые задания от учителя и напоминания о дедлайнах',
      notif_streak_label: 'Ежедневный стрик', notif_streak_desc: 'Напоминание о ежедневных занятиях',
      notif_lesson_label: 'Новые уроки',      notif_lesson_desc: 'Уведомления о новых уроках в курсе',
      notif_ach_label: 'Достижения',          notif_ach_desc: 'Когда разблокируется новое достижение',
      notif_email_label: 'Email уведомления', notif_email_desc: 'Дублировать уведомления на почту',
    },
    hw: {
      title: 'Домашние задания', subtitle: 'Задания от учителя · дедлайны · история сдач',
      active: 'Активные', done_section: 'Выполненные', no_hw: 'Все задания выполнены',
      no_hw_sub: 'Новые задания появятся когда учитель назначит',
      urgent: 'Срочно', days_left: 'дн.', min_score: 'Мин. балл',
      do_btn: 'Выполнить →', group: 'Группа',
      done_empty: 'Ещё нет выполненных заданий',
      group_info: 'Домашние задания назначает преподаватель через группу. Обратитесь к администратору.',
    },
    writing: {
      title: 'Writing Coach', subtitle: 'Тренажёр письменного английского · улучшай навыки письма',
      types_title: 'Тренировки по типам письма', my_works: 'Мои работы',
      skills_title: 'Прогресс по навыкам письма', tasks: 'заданий',
      start: 'Начать', open: 'Открыть', no_works: 'Ещё нет работ',
      no_works_sub: 'Начни первую тренировку выше',
      no_skills_title: 'Нет данных', no_skills_sub: 'Выполняй задания — здесь появится прогресс',
      status_reviewed: 'Проверено', status_sent: 'Отправлено', status_draft: 'Черновик',
      task_label: 'Задание', structure_label: 'Структура', phrase_label: 'Банк фраз',
      your_text: 'Твой текст', check: 'Проверить', save: 'Черновик',
      saved: 'Сохранено', submit: 'Учителю', submitted: 'Отправлено',
      sent_msg: 'Работа отправлена преподавателю на проверку!',
      words: 'слов',
      desc_email: 'Деловые и личные письма',
      desc_essay: 'Эссе для IELTS/TOEFL',
      desc_letter: 'Формальные и неформальные письма',
      desc_story: 'Творческое письмо и истории',
      desc_review: 'Отзывы и обзоры',
      desc_description: 'Описания людей, мест, событий',
      skill_grammar: 'Грамматика', skill_vocabulary: 'Словарный запас',
      skill_structure: 'Структура текста', skill_coherence: 'Связность (linking words)',
      skill_style: 'Стиль и тон',
      phrase_hint: '— нажми чтобы вставить',
      result_good: 'Хорошая работа!', result_almost: 'Почти готово!',
      check_volume: 'Объём текста', check_greeting: 'Приветствие',
      check_closing: 'Прощание', check_phrases: 'Фразы из банка',
      tips_label: 'Советы:',
    },
    progress: {
      title: 'Мой прогресс', subtitle: 'Детальная статистика обучения',
      overall: 'Общий прогресс', level_progress: 'Прогресс уровня',
      xp_total: 'Всего XP', streak_days: 'Дней подряд', best_streak: 'Лучший стрик',
      lessons_done: 'Уроков пройдено', time_spent: 'Часов обучения',
      skills_title: 'Навыки', no_data: 'Нет данных',
      no_data_sub: 'Пройди первые уроки чтобы увидеть прогресс',
      level_path: 'Путь к уровню', current_level: 'Текущий уровень',
      next_level: 'Следующий уровень', xp_needed: 'XP до следующего',
      activity_title: 'Активность', weeks: 'нед', today: 'Сегодня',
    },
    leaderboard: {
      title: 'Рейтинг группы', subtitle: 'Соревнуйся с одногруппниками',
      rank: 'Место', student: 'Студент', xp: 'XP', streak: 'Стрик', level: 'Уровень',
      you: 'Вы', top: 'Топ', your_rank: 'Ваше место',
      empty_title: 'Рейтинг пока пуст', empty_sub: 'Набирай XP чтобы появиться в рейтинге',
      week: 'За неделю', month: 'За месяц', all_time: 'За всё время',
    },
    achievements: {
      title: 'Достижения', subtitle: 'Разблокируй награды за обучение',
      earned: 'Получено', locked: 'Заблокировано', progress: 'Прогресс',
      all: 'Все', unlocked_only: 'Полученные',
      empty: 'Нет достижений', empty_sub: 'Начни учиться чтобы получить первые достижения',
    },
    lesson: {
      back: '← К модулю', complete: 'Завершить урок',
      next: 'Следующий вопрос →', check: 'Проверить',
      correct: 'Верно!', wrong: 'Неверно',
      score: 'Результат', xp_earned: 'XP получено',
      continue: 'Продолжить →', retry: 'Пройти заново',
      question_of: 'из', loading: 'Загрузка урока...',
      read_text: 'Прочитайте текст', answer_q: 'Ответьте на вопросы',
      type_answer: 'Введите ответ', your_answer: 'Ваш ответ',
      coming_soon: 'Урок скоро будет доступен', coming_soon_sub: 'Контент этого урока находится в разработке',
      // Steps
      step_prep: 'Подготовка', step_text: 'Текст', step_task1: 'Задание 1', step_task2: 'Задание 2',
      step_listen: 'Аудирование', step_model: 'Образец', step_write: 'Написать',
      step_theory: 'Теория', step_practice: 'Практика',
      // Prep phase
      prep_title: 'Соедините слова с их значениями',
      prep_write_title: 'Соедините фразы с их значениями',
      prep_remaining: 'осталось',
      check_btn: 'Проверить ответы',
      perfect: 'Отлично!', good_try: 'Хорошая попытка!',
      now_read: 'Теперь прочитайте текст.', continue_reading: 'Перейти к тексту →',
      continue_listen: 'Перейти к аудированию →',
      // Task 1 / 2
      task1_label: 'Задание 1 · Заполните пропуски', task1_title: 'Используйте слова из рамки',
      task2_label: 'Задание 2 · Верно или неверно', task2_title: 'Верно или неверно?',
      true_btn: 'Верно', false_btn: 'Неверно',
      correct_ans: 'Правильный ответ:', finish_btn: 'Завершить',
      excellent: 'Отлично!', good_job: 'Молодец!', good_score: 'Хороший результат!',
      // Listening
      listen_t1_label: 'Задание 1 · После прослушивания',
      listen_t2_label: 'Задание 2 · Кто это сказал?',
      listen_instr: 'Сначала выполните подготовительное задание. Затем слушайте.',
      playing: 'Воспроизведение...', played: 'Прослушано ✓ — можно слушать снова',
      press_play: 'Нажмите play, чтобы слушать',
      transcript_btn: 'Текст диалога',
      lesson_complete: 'Урок завершён!', well_done: 'Молодец!',
      back_to_module: '← К модулю',
      read_carefully_label: 'Читайте внимательно', dialogue_label: 'Диалог',
      // Writing
      prep_writing_title: 'Соедините фразы с их значениями',
      read_model: 'Прочитайте образец текста.',
      read_model_sub: 'Обратите внимание на структуру, фразы и словарный запас.',
      model_example: 'Образец', my_writing_label: 'Моя работа',
      key_phrases_label: 'Ключевые фразы из текста',
      write_task_label: 'Напишите свой текст',
      word_count_label: 'Слов:', target_words: 'Цель: 50+ слов',
      useful_phrases_label: 'Полезные фразы', click_copy: 'Нажмите, чтобы вставить',
      writing_done: 'Письмо завершено!', profile_ready: 'Ваш текст готов!',
      words_written: 'Написано слов', sentences_label: 'Предложений',
      // Grammar
      wrong_with_answer: 'Неверно. Правильный ответ:',
      // Test
      outstanding: 'Превосходно!', great_job: 'Отличная работа!',
      good_effort: 'Хорошая попытка!', keep_studying: 'Продолжайте учиться!',
      results_by_cat: 'Результаты по категориям',
      incorrect_answers: 'Разбор ошибок',
      perfect_score: 'Идеально! Ни одной ошибки!',
      mc_type: 'Выбор ответа', tf_type: 'Верно / Неверно', fill_type: 'Заполните пропуск',
      type_answer_ph: 'Введите ответ...', correct_answer_show: 'Правильный ответ:',
      next_q: 'Следующий вопрос →', see_results: 'Результаты →', retry_test: 'Пройти ещё раз',
      tap_flip: 'Нажмите, чтобы перевернуть',
      grammar_point: 'Грамматика',
      grammar_theory: 'Теория',
      grammar_tip: 'Ключевое правило',
      grammar_practice: 'Практика',
      exercises_label: 'заданий',
      finish_lesson: 'Завершить урок',
    },
    module: {
      after_module:    'После этого модуля ты сможешь:',
      plan_title:      'План модуля',
      plan_sub:        'Что ты изучишь в каждом уроке',
      start_module:    'Начать модуль',
      continue_module: 'Продолжить',
      lesson_word:     'урок',
      of_word:         'из',
      no_done:         'Пока нет пройденных уроков',
      to_complete:     'К прохождению',
      left:            'осталось',
      all_done:        'Все уроки пройдены!',
      unlock_test:     'Пройди все уроки чтобы открыть финальный тест',
      test_passed:     'Тест пройден!',
      final_test:      'Финальный тест',
      module_done:     'Модуль завершён',
      unlocks_after:   'Откроется после всех уроков',
      min_word:        'мин',
      lessons_word:    'уроков',
      total_word:      'всего',
      earn_word:       'заработать',
      lesson_structure:'Структура уроков',
      lessons_done:    'уроков пройдено',
      not_found:       'Модуль не найден',
      words_word:      'слов',
      completed_label: 'Пройдено',
      back_label:      '← Вернуться',
      back_course:     '← Курс',
      module_label:    'Модуль',
      exam_complete:   'Экзамен пройден',
      get_cert_a1:     'Получить сертификат A1',
      get_cert_a11:    'Получить сертификат A1.1',
      get_cert_a2:     'Получить сертификат A2',
      get_cert_b1:     'Получить сертификат B1',
      save_pdf:        'Распечатать или сохранить как PDF',
      re_read:         'Перечитать',
      vocab_study:     'Повторить словарь',
      type_reading:    'Чтение', type_listening: 'Аудирование',
      type_grammar:    'Грамматика', type_writing: 'Письмо',
      type_vocabulary: 'Словарь', type_test: 'Финальный тест',
    },
    common: {
      back: '← Назад', all_levels: '← Все уровни', loading: 'Загрузка...', xp: 'XP', days: 'дней',
      done_badge: 'Пройдено', locked_badge: 'Заблокировано',
      not_found: 'Не найдено', words: 'слов',
      level_a1: 'Начинающий', level_a11: 'Элементарный',
      level_a2: 'Предсредний', level_b1: 'Средний',
      level_b2: 'Выше среднего', level_c1: 'Продвинутый',
      level_not_found: 'Уровень не найден',
      skill_reading: 'Чтение', skill_listening: 'Аудирование',
      skill_writing: 'Письмо', skill_speaking: 'Говорение',
      skill_grammar: 'Грамматика',
      label_correct: 'Правильных', label_read: 'Прочитано',
      done_badge_f: 'Пройдено', locked_badge_f: 'Заблокировано',
    },
    layout: {
      logo: 'ЗКУ', title: 'ЗКУ им. М. Утемісова · English', subtitle: 'Powered by KHAMADI English',
    },
    path: {
      course_progress: 'Прогресс курса',
      modules_of: 'модулей',
      completed_section: 'Пройдено',
      current_section: 'В процессе',
      upcoming_section: 'Предстоит',
      next_module: 'Следующий',
      lessons_left: 'уроков осталось',
      lessons_of: 'уроков',
    },
    vocab_page: {
      title_lessons: 'Vocab уроков',
      avg_score: 'Средний балл',
      empty_title: 'Словарь пока пуст',
      empty_sub: 'Слова добавляются после прохождения словарных уроков',
      go_courses: 'К курсам →',
      completed_lessons: 'Пройденные словарные уроки',
      repeat_btn: 'Повторить →',
    },
    panel: {
      // Shared teacher + admin panel strings
      logout: 'Выйти', logout_full: 'Выйти из аккаунта',
      teacher_label: 'Преподаватель', admin_label: 'Администратор',
      teacher_cabinet: 'Кабинет преподавателя', admin_cabinet: 'Панель администратора',
      // Nav
      nav_dashboard: 'Дашборд', nav_groups: 'Группы', nav_students: 'Студенты',
      nav_teachers: 'Преподаватели', nav_other: 'Другие кабинеты', nav_manage: 'Управление',
      // Dashboard
      welcome: 'Добро пожаловать',
      dash_subtitle: 'Вот что происходит в ваших группах сегодня',
      admin_subtitle: 'Платформа ЗКУ English',
      my_groups: 'Мои группы', create_group: '+ Создать',
      recent_active: 'Последние активные', all_arrow: 'Все →',
      no_groups: 'Групп нет', no_groups_sub: 'Создайте первую группу',
      no_students: 'Студентов нет',
      stat_groups: 'Моих групп', stat_students: 'Студентов', stat_today: 'Активны сегодня', stat_progress: 'Ср. прогресс',
      // Students table
      student_col: 'Студент', level_col: 'Уровень', xp_col: 'XP', lessons_col: 'Уроки',
      streak_col: 'Стрик', activity_col: 'Активность', group_col: 'Группа', actions_col: 'Действия',
      today: 'Сегодня', yesterday: 'Вчера', never: 'Никогда', days_ago: 'дн.',
      no_group_badge: 'Без группы', risk_badge: 'Риск',
      search_placeholder: '🔍 Имя или email...',
      all_levels: 'Все уровни', all_activity: 'Любая активность', last_7: '7 дней', inactive_30: '30+ дней',
      reset_filter: '✕ Сбросить',
      shown_of: 'Показано', of_word: 'из',
      // Groups
      create_btn: '+ Создать группу', cancel_btn: '✕ Отмена',
      group_name_label: 'Название группы', level_label: 'Уровень', code_label: 'Код доступа',
      students_count: 'студентов', progress_label: 'прогресс',
      copy_code: 'Копировать', copied: 'Скопировано!',
      open_group: 'Открыть группу',
      // Password
      change_pass: 'Сменить пароль', new_pass_ph: 'Новый пароль (мин. 6 символов)',
      save_pass: '✓ Сохранить пароль', saving: 'Сохраняем...',
      pass_changed: '✓ Пароль изменён', min_chars: 'Минимум 6 символов',
      // Teachers
      all_teachers: 'Преподаватели', create_teacher: '+ Создать преподавателя',
      teacher_name: 'Полное имя', teacher_email: 'Email', teacher_pass: 'Пароль',
      to_admin: '→ Admin', remove_teacher: '✕',
      // Admin stats
      stat_total_students: 'Студентов', stat_total_teachers: 'Преподавателей',
      stat_total_groups: 'Групп', stat_active_today: 'Активны сегодня',
      quick_actions: '⚡ Быстрые действия', platform_health: '📈 Состояние платформы',
      total_xp: 'Всего XP на платформе', earned_by_all: 'Заработано всеми студентами',
      active_pct: 'Активны сегодня', students_per_group: 'Студентов на группу',
      avg_xp_student: 'Ср. XP на студента', avg_suffix: ' ср.',
    },
  },

  kz: {
    nav: {
      home: 'Басты бет', course: 'Менің курсым', vocab: 'Сөздік',
      progress: 'Прогресс', placement: 'Placement test',
      writing: 'Writing Coach', certs: 'Сертификаттар',
      leaderboard: 'Рейтинг', achievements: 'Жетістіктер',
    },
    user: {
      profile: 'Менің профилім', certs: 'Сертификаттар',
      achievements: 'Жетістіктер', settings: 'Параметрлер', logout: 'Шығу',
    },
    dash: {
      cabinet: 'СТУДЕНТ КАБИНЕТІ', subtitle: 'Бүгін жаңа нәрсе үйренуге тамаша күн',
      greeting: 'Сәлем', streak: 'күн қатарынан', xp: 'Барлық XP',
      rank: 'Топтағы орын', lessons: 'Өтілген сабақтар',
      continue_tag: '▶ ЖАЛҒАСТЫРУ', start_lesson: '▶ Сабақты жалғастыру',
      block: 'Блок', of: '/', to_level: 'Келесі деңгейге дейін',
      xp_left: 'Келесі деңгейге XP', streak_label: 'Стрик', record: 'Рекорд', days: 'күн',
      skills: 'Дағдылар бойынша прогресс', details: 'толығырақ →',
      activity: 'Соңғы белсенділік', see_all: 'барлығын көру →',
      reading: 'Reading', listening: 'Listening', grammar: 'Grammar',
      writing: 'Writing', writing_sub: 'Жазу тренажері',
      vocab_btn: 'Сөздік', texts: 'мәтін', audio: 'аудио',
      themes: 'деңгей тақырыптары', words_wait: 'сөз күтуде',
      all_courses: 'Барлық курстар', test_level: 'Тест тапсыру',
      start_first: 'Бірінші сабақты бастаңыз', start_first_sub: 'Прогресіңізді қадағалау үшін бірінші сабақты аяқтаңыз',
      go_to_courses: 'Курстарға',
      no_skills_title: 'Дағды деректері жоқ', no_skills_sub: 'Прогресіңізді көру үшін сабақтарды өтіңіз',
      no_activity_title: 'Белсенділік жоқ', no_activity_sub: 'Оқуды бастаңыз — тарих осында пайда болады',
    },
    course: {
      title: 'Курс бағдарламасы', subtitle: 'A1-ден C1-ге дейін · 600+ сабақ',
      overall: 'Жалпы прогресс', modules_done: 'модуль өтілді',
      lessons_done: 'сабақ өтілді', modules: 'модуль', lessons: 'сабақ',
      hours: 'сағат', words: 'сөз', continue_btn: 'Жалғастыру →', start_btn: 'Бастау →',
      locked: 'Бұғатталған', in_progress: 'Үдерісте', passed: 'Аяқталды',
      platform: 'МӨ атындағы БҚУ · English Platform',
      coming_soon_title: 'Мазмұн жақында қосылады', coming_soon_sub: 'дайындалуда',
      level_locked_title: 'Деңгей бұғатталған',
      level_locked_sub: 'Ашу үшін алдыңғы деңгейді аяқтаңыз',
      back_to_course: '← Курсқа оралу', module_word: 'Модуль',
      beginner_sub: 'Бастаушы', elementary_sub: 'Элементарлы',
      pre_int_sub: 'Орташа алды', intermediate_sub: 'Орташа',
      upper_int_sub: 'Ортадан жоғары', advanced_sub: 'Жоғары деңгей',
      desc_a1:  'Негізгі сөздер, сәлемдесулер, қарапайым сөйлемдер. Нөлден бастайтындар үшін.',
      desc_a11: 'Күнделікті жағдайлар, дүкенде сөйлесу, танысу, адамдар мен заттарды сипаттау.',
      desc_a2:  'Таныс тақырыптарда еркін сөйлесу, қарапайым диалогтар, оқиғаларды сипаттау.',
      desc_b1:  'Таныс тақырыптарда сенімді сөйлесу, саяхат, жұмыс хат жазысу.',
      desc_b2:  'Күрделі мәтіндер, пікірталастар, кәсіби сөйлеу, іскер хат жазысу.',
      desc_c1:  'Шешен сөйлеу, академиялық мәтіндер, бизнес деңгейі, халықаралық емтихандар.',
      title_a1:  'Нөлден базаға дейін',
      title_a11: 'Күнделікті ағылшын тілі',
      title_a2:  'Негізгі қарым-қатынас',
      title_b1:  'Еркін қарым-қатынас',
      title_b2:  'IELTS 6.0-ге дайын',
      title_c1:  'IELTS 7.0+-ке дайын',
    },
    vocab: {
      title: 'Менің сөздігім', subtitle: 'Қайталауға арналған карточкалар · интервалдық оқу',
      total: 'сөз', review: 'Қайталау', learned: 'Үйренілді', reps: 'Қайталау саны',
      due_banner: 'сөз қайталауды күтуде', due_sub: 'Аралық қайталау əдісімен',
      all_done: 'Сөздік үйренілді!', come_later: 'Келесі сөздер кейінірек пайда болады',
      tap_hint: 'Аударманы көрсету',
      forgot: 'Тағы', hard: 'Қиын', good: 'Білемін', easy: 'Оңай',
      back_lesson: 'Сабаққа',
    },
    placement: {
      title: 'Placement Test', subtitle: 'A1-ден C1-ге дейін деңгейіңізді анықтаңыз',
      duration: '15–20 минут', questions: '30 сұраққа дейін',
      result: 'Сіздің CEFR деңгейіңіз', adaptive: 'Жауаптарыңызға бейімделеді',
      tip: 'Кеңес: шынайы жауап беріңіз',
      start: 'Тестті бастау →', question_of: '/', level_badge: 'ДЕҢГЕЙ',
      q_of_6: 'Сұрақ', answer: 'Жауап беру →', reset: 'Тазалау',
      your_level: 'СІЗДІҢ ДЕҢГЕЙІҢІЗ', correct: 'Дұрыс жауап',
      by_level: 'Деңгейлер бойынша нәтиже', mistakes: 'Қателерді талдау',
      your_ans: 'Сіздің жауабыңыз', correct_ans: 'Дұрыс',
      go_course: 'Курсқа өту', retry: 'Қайта тапсыру',
      passed_lv: 'Өтілді', failed_lv: 'Тоқтатылды',
      word_hint: 'Сөйлем құрастыру үшін төмендегі сөздерді басыңыз',
    },
    certs: {
      title: 'Менің сертификаттарым',
      subtitle: 'CEFR ресми сертификаттары әр деңгейді аяқтағаннан кейін беріледі',
      earned: 'Алынды', in_progress: 'Үдерісте', locked: 'Бұғатталған',
      how_title: 'Сертификатты қалай алуға болады?',
      how_body: 'Деңгейдің барлық модульдерін өтіп, кем дегенде 80% жинаңыз.',
      to_courses: 'Курстарға →', issued_to: 'СТУДЕНТКЕ БЕРІЛГЕН',
      skills_conf: 'Расталған дағдылар', issued_at: 'Берілген күн', org: 'Ұйым',
      flip_hint: 'Аудару үшін басыңыз · PDF жүктеу',
      download: 'PDF жүктеу', continue: 'Оқуды жалғастыру →',
      locked_msg: 'Ашу үшін алдыңғы деңгейді аяқтаңыз', left_to: '% сертификатқа дейін',
      completion_cert: 'Бітіру сертификаты',
      download_coming: 'Сертификат деңгейді аяқтағаннан кейін қол жетімді болады',
      footer_note: 'Сертификаттар Қазақстан жұмыс берушілері мен халықаралық ұйымдар тарапынан мойындалады · CEFR стандартына сәйкес',
    },
    profile: {
      tab_profile: 'Профиль', tab_security: 'Қауіпсіздік',
      tab_notifs: 'Хабарландырулар', tab_stats: 'Статистика',
      title_info: 'Жеке ақпарат', title_study: 'Оқу ақпараты',
      title_pass: 'Құпия сөзді өзгерту', title_notifs: 'Хабарландыруларды баптау',
      title_stats: 'Дағдылар бойынша прогресс', title_act: 'Соңғы белсенділік',
      save: 'Өзгерістерді сақтау', saved: 'Сақталды',
      full_name: 'Толық аты', email: 'Email', phone: 'Телефон',
      city: 'Қала', bio: 'Өзім туралы', group: 'Топ', level: 'Ағымдағы деңгей',
      reg_date: 'Тіркелу күні', last_active: 'Соңғы белсенділік',
      old_pass: 'Ағымдағы құпия сөз', new_pass: 'Жаңа құпия сөз', conf_pass: 'Растаңыз',
      sessions: 'Белсенді сеанстар', current: 'Ағымдағы', end_session: 'Аяқтау', today: 'Бүгін',
      pass_changed: 'Құпия сөз сәтті өзгертілді',
      pass_fill_all: 'Барлық өрістерді толтырыңыз', pass_mismatch: 'Құпия сөздер сәйкес келмейді', pass_too_short: 'Кемінде 8 таңба',
      pass_placeholder: 'Кемінде 8 таңба', pass_confirm_placeholder: 'Жаңа құпия сөзді қайталаңыз',
      level_auto_hint: 'Деңгей Placement Test және курс прогресі негізінде автоматты анықталады',
      stat_xp: 'Барлық XP', stat_streak: 'Стрик күні', stat_best: 'Үздік стрик', stat_lessons: 'Өтілген сабақ',
      achievements_title: 'Жетістіктер', achievements_empty: 'Әлі жетістіктер жоқ', achievements_empty_sub: 'Бірінші жетістіктерді алу үшін сабақтар мен тесттерді өтіңіз',
      no_activity: 'Белсенділік жоқ', no_activity_sub: 'Тарих бірінші сабақтардан кейін пайда болады',
      no_skills: 'Деректер жоқ', no_skills_sub: 'Деректер сабақтарды өткеннен кейін пайда болады',
      notif_hw_label: 'Үй тапсырмалары',    notif_hw_desc: 'Мұғалімнен жаңа тапсырмалар және мерзімдер туралы еске салу',
      notif_streak_label: 'Күнделікті стрик', notif_streak_desc: 'Күнделікті сабақтар туралы еске салу',
      notif_lesson_label: 'Жаңа сабақтар',   notif_lesson_desc: 'Курстағы жаңа сабақтар туралы хабарландырулар',
      notif_ach_label: 'Жетістіктер',         notif_ach_desc: 'Жаңа жетістік ашылғанда',
      notif_email_label: 'Email хабарландырулар', notif_email_desc: 'Хабарландыруларды электрондық поштаға жіберу',
    },
    hw: {
      title: 'Үй тапсырмалары', subtitle: 'Мұғалімнен тапсырмалар · мерзімдер · тарих',
      active: 'Белсенді', done_section: 'Орындалған', no_hw: 'Барлық тапсырмалар орындалды',
      no_hw_sub: 'Мұғалім тағайындағанда жаңа тапсырмалар пайда болады',
      urgent: 'Шұғыл', days_left: 'күн', min_score: 'Мин. балл',
      do_btn: 'Орындау →', group: 'Топ',
      done_empty: 'Әлі орындалған тапсырмалар жоқ',
      group_info: 'Үй тапсырмасын оқытушы топ арқылы тағайындайды. Әкімшіге хабарласыңыз.',
    },
    writing: {
      title: 'Writing Coach', subtitle: 'Ағылшын жазу тренажері · жазу дағдыларыңды жетілдір',
      types_title: 'Жазу түрлері бойынша тренировкалар', my_works: 'Менің жұмыстарым',
      skills_title: 'Жазу дағдылары бойынша прогресс', tasks: 'тапсырма',
      start: 'Бастау', open: 'Ашу', no_works: 'Әлі жұмыстар жоқ',
      no_works_sub: 'Жоғарыдан бірінші тренировканы бастаңыз',
      no_skills_title: 'Деректер жоқ', no_skills_sub: 'Тапсырмаларды орындаңыз — прогресс осында пайда болады',
      status_reviewed: 'Тексерілді', status_sent: 'Жіберілді', status_draft: 'Жоба',
      task_label: 'Тапсырма', structure_label: 'Құрылым', phrase_label: 'Фраза банкі',
      your_text: 'Сіздің мәтіңіз', check: 'Тексеру', save: 'Жоба',
      saved: 'Сақталды', submit: 'Мұғалімге', submitted: 'Жіберілді',
      sent_msg: 'Жұмыс мұғалімге тексеруге жіберілді!',
      words: 'сөз',
      desc_email: 'Іскери және жеке хаттар',
      desc_essay: 'IELTS/TOEFL үшін эссе',
      desc_letter: 'Ресми және бейресми хаттар',
      desc_story: 'Шығармашылық жазу және оқиғалар',
      desc_review: 'Пікірлер мен шолулар',
      desc_description: 'Адамдар, орындар, оқиғалар сипаттамасы',
      skill_grammar: 'Грамматика', skill_vocabulary: 'Сөздік қор',
      skill_structure: 'Мәтін құрылымы', skill_coherence: 'Байланыстылық (linking words)',
      skill_style: 'Стиль және сарын',
      phrase_hint: '— кірістіру үшін басыңыз',
      result_good: 'Керемет жұмыс!', result_almost: 'Дерлік дайын!',
      check_volume: 'Мәтін көлемі', check_greeting: 'Сәлемдесу',
      check_closing: 'Қоштасу', check_phrases: 'Банктен фразалар',
      tips_label: 'Кеңестер:',
    },
    progress: {
      title: 'Менің прогресім', subtitle: 'Оқу статистикасы',
      overall: 'Жалпы прогресс', level_progress: 'Деңгей прогресі',
      xp_total: 'Барлық XP', streak_days: 'Қатарынан күн', best_streak: 'Үздік стрик',
      lessons_done: 'Өтілген сабақ', time_spent: 'Оқу сағаты',
      skills_title: 'Дағдылар', no_data: 'Деректер жоқ',
      no_data_sub: 'Прогресті көру үшін алғашқы сабақтарды өтіңіз',
      level_path: 'Деңгейге жол', current_level: 'Ағымдағы деңгей',
      next_level: 'Келесі деңгей', xp_needed: 'Келесіге дейінгі XP',
      activity_title: 'Белсенділік', weeks: 'апта', today: 'Бүгін',
    },
    leaderboard: {
      title: 'Топ рейтингі', subtitle: 'Топтастарыңызбен бәсекелесіңіз',
      rank: 'Орын', student: 'Студент', xp: 'XP', streak: 'Стрик', level: 'Деңгей',
      you: 'Сіз', top: 'Топ', your_rank: 'Сіздің орныңыз',
      empty_title: 'Рейтинг әлі бос', empty_sub: 'Рейтингте пайда болу үшін XP жинаңыз',
      week: 'Апта бойынша', month: 'Ай бойынша', all_time: 'Барлық уақыт',
    },
    achievements: {
      title: 'Жетістіктер', subtitle: 'Оқу үшін марапаттар алыңыз',
      earned: 'Алынды', locked: 'Бұғатталған', progress: 'Прогресс',
      all: 'Барлығы', unlocked_only: 'Алынғандар',
      empty: 'Жетістіктер жоқ', empty_sub: 'Алғашқы жетістіктерді алу үшін оқуды бастаңыз',
    },
    lesson: {
      back: '← Модульге', complete: 'Сабақты аяқтау',
      next: 'Келесі сұрақ →', check: 'Тексеру',
      correct: 'Дұрыс!', wrong: 'Қате',
      score: 'Нәтиже', xp_earned: 'XP жиналды',
      continue: 'Жалғастыру →', retry: 'Қайта өту',
      question_of: '/', loading: 'Сабақ жүктелуде...',
      read_text: 'Мәтінді оқыңыз', answer_q: 'Сұрақтарға жауап беріңіз',
      type_answer: 'Жауапты теріңіз', your_answer: 'Сіздің жауабыңыз',
      coming_soon: 'Сабақ жақында қол жетімді болады', coming_soon_sub: 'Бұл сабақтың мазмұны дайындалуда',
      // Steps
      step_prep: 'Дайындық', step_text: 'Мәтін', step_task1: '1-тапсырма', step_task2: '2-тапсырма',
      step_listen: 'Тыңдау', step_model: 'Үлгі', step_write: 'Жазу',
      step_theory: 'Теория', step_practice: 'Жаттығу',
      // Prep phase
      prep_title: 'Сөздерді мағынасымен сәйкестендіріңіз',
      prep_write_title: 'Сөйлем басталуларын мағынасымен сәйкестендіріңіз',
      prep_remaining: 'қалды',
      check_btn: 'Жауаптарды тексеру',
      perfect: 'Тамаша!', good_try: 'Жақсы әрекет!',
      now_read: 'Енді мәтінді оқыңыз.', continue_reading: 'Мәтінге өту →',
      continue_listen: 'Тыңдауға өту →',
      // Task 1 / 2
      task1_label: '1-тапсырма · Бос орындарды толтырыңыз', task1_title: 'Берілген сөздерді пайдаланыңыз',
      task2_label: '2-тапсырма · Рас па, жалған ба', task2_title: 'Рас па, жалған ба?',
      true_btn: 'Рас', false_btn: 'Жалған',
      correct_ans: 'Дұрыс жауап:', finish_btn: 'Аяқтау',
      excellent: 'Керемет!', good_job: 'Жарайсың!', good_score: 'Жақсы нәтиже!',
      // Listening
      listen_t1_label: '1-тапсырма · Тыңдаудан кейін',
      listen_t2_label: '2-тапсырма · Кім айтты?',
      listen_instr: 'Алдымен дайындық тапсырмасын орындаңыз, содан кейін тыңдаңыз.',
      playing: 'Ойнауда...', played: 'Тыңдалды ✓ — қайта тыңдауға болады',
      press_play: 'Тыңдау үшін Play басыңыз',
      transcript_btn: 'Диалог мәтіні',
      lesson_complete: 'Сабақ аяқталды!', well_done: 'Жарайсың!',
      back_to_module: '← Модульге оралу',
      read_carefully_label: 'Мұқият оқыңыз', dialogue_label: 'Диалог',
      // Writing
      prep_writing_title: 'Сөйлем басталуларын мағынасымен сәйкестендіріңіз',
      read_model: 'Үлгі мәтінді оқыңыз.',
      read_model_sub: 'Мәтіннің құрылымына, сөз тіркестері мен лексикасына назар аударыңыз.',
      model_example: 'Үлгі', my_writing_label: 'Менің жазуым',
      key_phrases_label: 'Мәтіндегі негізгі сөз тіркестері',
      write_task_label: 'Өз мәтіңізді жазыңыз',
      word_count_label: 'Сөздер:', target_words: 'Мақсат: 50+ сөз',
      useful_phrases_label: 'Пайдалы сөз тіркестері', click_copy: 'Кірістіру үшін басыңыз',
      writing_done: 'Жазу аяқталды!', profile_ready: 'Мәтіңіз дайын!',
      words_written: 'Жазылған сөздер', sentences_label: 'Сөйлемдер',
      // Grammar
      wrong_with_answer: 'Қате. Дұрыс жауап:',
      // Test
      outstanding: 'Тамаша нәтиже!', great_job: 'Өте жақсы!',
      good_effort: 'Жақсы тырысыс!', keep_studying: 'Оқуды жалғастырыңыз!',
      results_by_cat: 'Санаттар бойынша нәтижелер',
      incorrect_answers: 'Қателерді талдау',
      perfect_score: 'Мінсіз нәтиже! Қате жоқ!',
      mc_type: 'Бір жауапты таңдау', tf_type: 'Рас / Жалған', fill_type: 'Бос орынды толтыру',
      type_answer_ph: 'Жауапты теріңіз...', correct_answer_show: 'Дұрыс жауап:',
      next_q: 'Келесі сұрақ →', see_results: 'Нәтижелерді көру →', retry_test: 'Қайтадан өту',
      tap_flip: 'Аудару үшін басыңыз',
      grammar_point: 'Грамматика',
      grammar_theory: 'Теория',
      grammar_tip: 'Негізгі ереже',
      grammar_practice: 'Жаттығу',
      exercises_label: 'тапсырма',
      finish_lesson: 'Сабақты аяқтау',
    },
    module: {
      after_module:    'Осы модульді аяқтағаннан кейін сіз:',
      plan_title:      'Модуль жоспары',
      plan_sub:        'Әр сабақта не үйренесіз',
      start_module:    'Модульді бастау',
      continue_module: 'Жалғастыру',
      lesson_word:     'сабақ',
      of_word:         '/',
      no_done:         'Аяқталған сабақтар жоқ',
      to_complete:     'Аяқтау керек',
      left:            'қалды',
      all_done:        'Барлық сабақтар аяқталды!',
      unlock_test:     'Финалдық тестті ашу үшін барлық сабақтарды өтіңіз',
      test_passed:     'Тест өтілді!',
      final_test:      'Финалдық тест',
      module_done:     'Модуль аяқталды',
      unlocks_after:   'Барлық сабақтарды өткеннен кейін ашылады',
      min_word:        'мин',
      lessons_word:    'сабақ',
      total_word:      'барлығы',
      earn_word:       'жинау',
      lesson_structure:'Сабақтар құрылымы',
      lessons_done:    'сабақ өтілді',
      not_found:       'Модуль табылмады',
      words_word:      'сөз',
      completed_label: 'Аяқталды',
      back_label:      '← Қайту',
      back_course:     '← Курс',
      module_label:    'Модуль',
      exam_complete:   'Емтихан аяқталды',
      get_cert_a1:     'A1 сертификатын алу',
      get_cert_a11:    'A1.1 сертификатын алу',
      get_cert_a2:     'A2 сертификатын алу',
      get_cert_b1:     'B1 сертификатын алу',
      save_pdf:        'Басып шығару немесе PDF ретінде сақтау',
      re_read:         'Қайта оқу',
      vocab_study:     'Сөздікті қайталау',
      type_reading:    'Оқу', type_listening: 'Тыңдау',
      type_grammar:    'Грамматика', type_writing: 'Жазу',
      type_vocabulary: 'Сөздік', type_test: 'Финалдық тест',
    },
    common: {
      back: '← Артқа', all_levels: '← Барлық деңгейлер', loading: 'Жүктелуде...', xp: 'XP', days: 'күн',
      done_badge: 'Аяқталды', locked_badge: 'Бұғатталған',
      not_found: 'Табылмады', words: 'сөз',
      level_a1: 'Бастаушы', level_a11: 'Элементарлы',
      level_a2: 'Орта алды', level_b1: 'Орташа',
      level_b2: 'Ортадан жоғары', level_c1: 'Жоғары деңгей',
      level_not_found: 'Деңгей табылмады',
      skill_reading: 'Оқу', skill_listening: 'Тыңдау',
      skill_writing: 'Жазу', skill_speaking: 'Сөйлеу',
      skill_grammar: 'Грамматика',
      label_correct: 'Дұрыс', label_read: 'Оқылды',
    },
    layout: {
      logo: 'БҚУ', title: 'МӨ атындағы БҚУ · English', subtitle: 'KHAMADI English платформасы',
    },
    path: {
      course_progress: 'Курс прогресі',
      modules_of: 'модуль',
      completed_section: 'Аяқталды',
      current_section: 'Үдерісте',
      upcoming_section: 'Алдағы',
      next_module: 'Келесі',
      lessons_left: 'сабақ қалды',
      lessons_of: 'сабақ',
    },
    vocab_page: {
      title_lessons: 'Сөздік сабақтары',
      avg_score: 'Орта балл',
      empty_title: 'Сөздік әлі бос',
      empty_sub: 'Сөздер сөздік сабақтарын өткеннен кейін қосылады',
      go_courses: 'Курстарға →',
      completed_lessons: 'Өтілген сөздік сабақтары',
      repeat_btn: 'Қайталау →',
    },
    panel: {
      logout: 'Шығу', logout_full: 'Аккаунттан шығу',
      teacher_label: 'Оқытушы', admin_label: 'Әкімші',
      teacher_cabinet: 'Оқытушы кабинеті', admin_cabinet: 'Әкімші панелі',
      nav_dashboard: 'Басқару тақтасы', nav_groups: 'Топтар', nav_students: 'Студенттер',
      nav_teachers: 'Оқытушылар', nav_other: 'Басқа кабинеттер', nav_manage: 'Басқару',
      welcome: 'Қош келдіңіз',
      dash_subtitle: 'Топтарыңызда бүгін не болып жатыр',
      admin_subtitle: 'ЗКУ English платформасы',
      my_groups: 'Менің топтарым', create_group: '+ Жасау',
      recent_active: 'Соңғы белсенді', all_arrow: 'Барлығы →',
      no_groups: 'Топ жоқ', no_groups_sub: 'Бірінші топты жасаңыз',
      no_students: 'Студент жоқ',
      stat_groups: 'Топтарым', stat_students: 'Студенттер', stat_today: 'Бүгін белсенді', stat_progress: 'Орт. прогресс',
      student_col: 'Студент', level_col: 'Деңгей', xp_col: 'XP', lessons_col: 'Сабақтар',
      streak_col: 'Стрик', activity_col: 'Белсенділік', group_col: 'Топ', actions_col: 'Әрекеттер',
      today: 'Бүгін', yesterday: 'Кеше', never: 'Ешқашан', days_ago: 'күн',
      no_group_badge: 'Топсыз', risk_badge: 'Қауіп',
      search_placeholder: '🔍 Аты немесе email...',
      all_levels: 'Барлық деңгейлер', all_activity: 'Кез келген белсенділік', last_7: '7 күн', inactive_30: '30+ күн',
      reset_filter: '✕ Тазалау',
      shown_of: 'Көрсетілген', of_word: '/',
      create_btn: '+ Топ жасау', cancel_btn: '✕ Бас тарту',
      group_name_label: 'Топ атауы', level_label: 'Деңгей', code_label: 'Кіру коды',
      students_count: 'студент', progress_label: 'прогресс',
      copy_code: 'Көшіру', copied: 'Көшірілді!',
      open_group: 'Топты ашу',
      change_pass: 'Құпиясөзді өзгерту', new_pass_ph: 'Жаңа құпиясөз (мин. 6 таңба)',
      save_pass: '✓ Сақтау', saving: 'Сақталуда...',
      pass_changed: '✓ Құпиясөз өзгертілді', min_chars: 'Кемінде 6 таңба',
      all_teachers: 'Оқытушылар', create_teacher: '+ Оқытушы жасау',
      teacher_name: 'Толық аты', teacher_email: 'Email', teacher_pass: 'Құпиясөз',
      to_admin: '→ Admin', remove_teacher: '✕',
      stat_total_students: 'Студенттер', stat_total_teachers: 'Оқытушылар',
      stat_total_groups: 'Топтар', stat_active_today: 'Бүгін белсенді',
      quick_actions: '⚡ Жылдам әрекеттер', platform_health: '📈 Платформа жағдайы',
      total_xp: 'Платформадағы барлық XP', earned_by_all: 'Барлық студенттер тапқан',
      active_pct: 'Бүгін белсенді', students_per_group: 'Топтағы студент',
      avg_xp_student: 'Орт. XP/студент', avg_suffix: ' орт.',
    },
  },

  en: {
    nav: {
      home: 'Home', course: 'My Course', vocab: 'Vocabulary',
      progress: 'Progress', placement: 'Placement test',
      writing: 'Writing Coach', certs: 'Certificates',
      leaderboard: 'Leaderboard', achievements: 'Achievements',
    },
    user: {
      profile: 'My Profile', certs: 'Certificates',
      achievements: 'Achievements', settings: 'Settings', logout: 'Sign out',
    },
    dash: {
      cabinet: 'STUDENT DASHBOARD', subtitle: 'Today is a great day to learn something new',
      greeting: 'Hello', streak: 'day streak', xp: 'Total XP',
      rank: 'Group rank', lessons: 'Lessons done',
      continue_tag: '▶ CONTINUE', start_lesson: '▶ Continue lesson',
      block: 'Block', of: 'of', to_level: 'To next level',
      xp_left: 'XP to next level', streak_label: 'Streak', record: 'Best streak', days: 'days',
      skills: 'Skills progress', details: 'see more →',
      activity: 'Recent activity', see_all: 'see all →',
      reading: 'Reading', listening: 'Listening', grammar: 'Grammar',
      writing: 'Writing', writing_sub: 'Writing trainer',
      vocab_btn: 'Vocabulary', texts: 'texts', audio: 'audio',
      themes: 'level themes', words_wait: 'words due',
      all_courses: 'All courses', test_level: 'Take level test',
      start_first: 'Start your first lesson', start_first_sub: 'Complete a lesson to begin tracking progress',
      go_to_courses: 'Go to courses',
      no_skills_title: 'No skill data yet', no_skills_sub: 'Complete lessons to see your progress',
      no_activity_title: 'No activity yet', no_activity_sub: 'Start learning — your history will appear here',
    },
    course: {
      title: 'Course program', subtitle: 'Full path from A1 to C1 · 600+ lessons',
      overall: 'Overall progress', modules_done: 'modules done',
      lessons_done: 'lessons done', modules: 'modules', lessons: 'lessons',
      hours: 'hours', words: 'words', continue_btn: 'Continue →', start_btn: 'Start →',
      locked: 'Locked', in_progress: 'In progress', passed: 'Completed',
      platform: 'WKU · English Platform',
      coming_soon_title: 'Content coming soon', coming_soon_sub: 'is in development',
      level_locked_title: 'Level locked',
      level_locked_sub: 'Complete the previous level to unlock',
      back_to_course: '← Back to course', module_word: 'Module',
      beginner_sub: 'Beginner', elementary_sub: 'Elementary',
      pre_int_sub: 'Pre-Intermediate', intermediate_sub: 'Intermediate',
      upper_int_sub: 'Upper-Intermediate', advanced_sub: 'Advanced',
      desc_a1:  'Basic phrases, greetings, simple sentences. Perfect for those starting from zero.',
      desc_a11: 'Everyday situations, shopping, introductions, describing people and things.',
      desc_a2:  'Free communication on basic topics, simple dialogues, describing events.',
      desc_b1:  'Fluent communication on familiar topics, travel, work correspondence.',
      desc_b2:  'Complex texts, discussions, professional speech, business writing.',
      desc_c1:  'Fluent speech, academic texts, business level, international exams.',
      title_a1:  'From Zero to Base',
      title_a11: 'Everyday English',
      title_a2:  'Basic Communication',
      title_b1:  'Confident Communication',
      title_b2:  'Ready for IELTS 6.0',
      title_c1:  'Ready for IELTS 7.0+',
    },
    vocab: {
      title: 'My Vocabulary', subtitle: 'Flashcards · spaced repetition',
      total: 'words', review: 'Review', learned: 'Learned', reps: 'Reviews',
      due_banner: 'words due for review', due_sub: 'Spaced repetition method',
      all_done: 'Vocabulary complete!', come_later: 'Next words will appear later',
      tap_hint: 'Show translation',
      forgot: 'Again', hard: 'Hard', good: 'Got it', easy: 'Easy',
      back_lesson: 'Back to lesson',
    },
    placement: {
      title: 'Placement Test', subtitle: 'Find your English level from A1 to C1',
      duration: '15–20 minutes', questions: 'Up to 30 questions',
      result: 'Your CEFR level', adaptive: 'Adapts to your answers',
      tip: 'Tip: answer honestly — the test will find your true level',
      start: 'Start test →', question_of: 'of', level_badge: 'LEVEL',
      q_of_6: 'Question', answer: 'Answer →', reset: 'Reset',
      your_level: 'YOUR LEVEL', correct: 'Correct answers',
      by_level: 'Results by level', mistakes: 'Mistakes review',
      your_ans: 'Your answer', correct_ans: 'Correct',
      go_course: 'Go to course', retry: 'Retake test',
      passed_lv: 'Passed', failed_lv: 'Stopped',
      word_hint: 'Click words below to build your sentence',
    },
    certs: {
      title: 'My Certificates',
      subtitle: 'Official CEFR certificates issued after completing each level',
      earned: 'Earned', in_progress: 'In progress', locked: 'Locked',
      how_title: 'How to earn a certificate?',
      how_body: 'Complete all modules in a level and score at least 80% on each final test.',
      to_courses: 'To courses →', issued_to: 'ISSUED TO',
      skills_conf: 'Verified skills', issued_at: 'Date issued', org: 'Organization',
      flip_hint: 'Click to flip · download certificate',
      download: 'Download PDF', continue: 'Continue learning →',
      locked_msg: 'Complete the previous level to unlock', left_to: '% to certificate',
      completion_cert: 'Certificate of Completion',
      download_coming: 'Certificate will be available after completing the level',
      footer_note: 'Certificates are recognised by Kazakh employers and international organisations · CEFR standard compliant',
    },
    profile: {
      tab_profile: 'Profile', tab_security: 'Security',
      tab_notifs: 'Notifications', tab_stats: 'Statistics',
      title_info: 'Personal information', title_study: 'Academic information',
      title_pass: 'Change password', title_notifs: 'Notification settings',
      title_stats: 'Skills progress', title_act: 'Recent activity',
      save: 'Save changes', saved: 'Saved',
      full_name: 'Full name', email: 'Email', phone: 'Phone',
      city: 'City', bio: 'About me', group: 'Group', level: 'Current level',
      reg_date: 'Registration date', last_active: 'Last active',
      old_pass: 'Current password', new_pass: 'New password', conf_pass: 'Confirm password',
      sessions: 'Active sessions', current: 'Current', end_session: 'End session', today: 'Today',
      pass_changed: 'Password changed successfully',
      pass_fill_all: 'Please fill in all fields', pass_mismatch: 'Passwords do not match', pass_too_short: 'Minimum 8 characters',
      pass_placeholder: 'Minimum 8 characters', pass_confirm_placeholder: 'Repeat new password',
      level_auto_hint: 'Your level is determined automatically based on Placement Test and course progress',
      stat_xp: 'Total XP', stat_streak: 'Day streak', stat_best: 'Best streak', stat_lessons: 'Lessons done',
      achievements_title: 'Achievements', achievements_empty: 'No achievements yet', achievements_empty_sub: 'Complete lessons and tests to earn your first achievements',
      no_activity: 'No activity yet', no_activity_sub: 'History will appear after your first lessons',
      no_skills: 'No data yet', no_skills_sub: 'Data will appear after completing lessons',
      notif_hw_label: 'Homework',             notif_hw_desc: 'New assignments from teacher and deadline reminders',
      notif_streak_label: 'Daily streak',     notif_streak_desc: 'Reminder to study every day',
      notif_lesson_label: 'New lessons',      notif_lesson_desc: 'Notifications about new lessons in the course',
      notif_ach_label: 'Achievements',         notif_ach_desc: 'When a new achievement is unlocked',
      notif_email_label: 'Email notifications', notif_email_desc: 'Duplicate notifications to email',
    },
    hw: {
      title: 'Homework', subtitle: 'Teacher assignments · deadlines · history',
      active: 'Active', done_section: 'Completed', no_hw: 'All assignments done',
      no_hw_sub: 'New assignments will appear when your teacher assigns them',
      urgent: 'Urgent', days_left: 'days', min_score: 'Min score',
      do_btn: 'Complete →', group: 'Group',
      done_empty: 'No completed assignments yet',
      group_info: 'Homework is assigned by the teacher through a group. Contact your administrator.',
    },
    writing: {
      title: 'Writing Coach', subtitle: 'English writing trainer · improve your writing skills',
      types_title: 'Writing type practice', my_works: 'My works',
      skills_title: 'Writing skills progress', tasks: 'tasks',
      start: 'Start', open: 'Open', no_works: 'No works yet',
      no_works_sub: 'Start your first practice above',
      no_skills_title: 'No data yet', no_skills_sub: 'Complete tasks — progress will appear here',
      status_reviewed: 'Reviewed', status_sent: 'Sent', status_draft: 'Draft',
      task_label: 'Task', structure_label: 'Structure', phrase_label: 'Phrase bank',
      your_text: 'Your text', check: 'Check', save: 'Draft',
      saved: 'Saved', submit: 'Send to teacher', submitted: 'Sent',
      sent_msg: 'Work sent to teacher for review!',
      words: 'words',
      desc_email: 'Business and personal letters',
      desc_essay: 'Essays for IELTS/TOEFL',
      desc_letter: 'Formal and informal letters',
      desc_story: 'Creative writing and stories',
      desc_review: 'Reviews and summaries',
      desc_description: 'Describing people, places, events',
      skill_grammar: 'Grammar', skill_vocabulary: 'Vocabulary',
      skill_structure: 'Text structure', skill_coherence: 'Cohesion (linking words)',
      skill_style: 'Style and tone',
      phrase_hint: '— click to insert',
      result_good: 'Great work!', result_almost: 'Almost there!',
      check_volume: 'Word count', check_greeting: 'Greeting',
      check_closing: 'Closing', check_phrases: 'Phrase bank used',
      tips_label: 'Tips:',
    },
    progress: {
      title: 'My Progress', subtitle: 'Detailed learning statistics',
      overall: 'Overall progress', level_progress: 'Level progress',
      xp_total: 'Total XP', streak_days: 'Day streak', best_streak: 'Best streak',
      lessons_done: 'Lessons done', time_spent: 'Study hours',
      skills_title: 'Skills', no_data: 'No data yet',
      no_data_sub: 'Complete your first lessons to see progress',
      level_path: 'Path to level', current_level: 'Current level',
      next_level: 'Next level', xp_needed: 'XP to next level',
      activity_title: 'Activity', weeks: 'wk', today: 'Today',
    },
    leaderboard: {
      title: 'Group Leaderboard', subtitle: 'Compete with your classmates',
      rank: 'Rank', student: 'Student', xp: 'XP', streak: 'Streak', level: 'Level',
      you: 'You', top: 'Top', your_rank: 'Your rank',
      empty_title: 'Leaderboard is empty', empty_sub: 'Earn XP to appear on the leaderboard',
      week: 'This week', month: 'This month', all_time: 'All time',
    },
    achievements: {
      title: 'Achievements', subtitle: 'Unlock rewards for learning',
      earned: 'Earned', locked: 'Locked', progress: 'Progress',
      all: 'All', unlocked_only: 'Unlocked',
      empty: 'No achievements', empty_sub: 'Start learning to earn your first achievements',
    },
    lesson: {
      back: '← To module', complete: 'Complete lesson',
      next: 'Next question →', check: 'Check',
      correct: 'Correct!', wrong: 'Wrong',
      score: 'Score', xp_earned: 'XP earned',
      continue: 'Continue →', retry: 'Try again',
      question_of: 'of', loading: 'Loading lesson...',
      read_text: 'Read the text', answer_q: 'Answer the questions',
      type_answer: 'Type your answer', your_answer: 'Your answer',
      coming_soon: 'Lesson coming soon', coming_soon_sub: 'Content for this lesson is in development',
      // Steps
      step_prep: 'Preparation', step_text: 'Reading text', step_task1: 'Task 1', step_task2: 'Task 2',
      step_listen: 'Listen', step_model: 'Model text', step_write: 'Write',
      step_theory: 'Theory', step_practice: 'Practice',
      // Prep phase
      prep_title: 'Match the words to their meanings',
      prep_write_title: 'Match the sentence starters to their meanings',
      prep_remaining: 'remaining',
      check_btn: 'Check answers',
      perfect: 'Perfect!', good_try: 'Good try!',
      now_read: 'Now read the text.', continue_reading: 'Continue to Reading →',
      continue_listen: 'Continue to Listening →',
      // Task 1 / 2
      task1_label: 'Task 1 · Fill in the gaps', task1_title: 'Use the words from the box',
      task2_label: 'Task 2 · True or False', task2_title: 'True or False?',
      true_btn: 'True', false_btn: 'False',
      correct_ans: 'Correct answer:', finish_btn: 'Finish',
      excellent: 'Excellent!', good_job: 'Good job!', good_score: 'Good score!',
      // Listening
      listen_t1_label: 'Task 1 · After listening',
      listen_t2_label: 'Task 2 · Who said it?',
      listen_instr: 'Do the preparation task first. Then listen and do the exercises.',
      playing: 'Playing...', played: 'Played ✓ — listen again',
      press_play: 'Press play to listen',
      transcript_btn: 'Transcript',
      lesson_complete: 'Lesson complete!', well_done: 'Well done!',
      back_to_module: '← Back to module',
      read_carefully_label: 'Read carefully', dialogue_label: 'Dialogue',
      // Writing
      prep_writing_title: 'Match the sentence starters to their meanings',
      read_model: 'Read the model text first.',
      read_model_sub: 'Pay attention to the structure, phrases and vocabulary.',
      model_example: 'Example', my_writing_label: 'My writing',
      key_phrases_label: 'Key phrases used in this text',
      write_task_label: 'Write your own text',
      word_count_label: 'Words:', target_words: 'Target: 50+ words',
      useful_phrases_label: 'Useful phrases', click_copy: 'Click to insert',
      writing_done: 'Writing complete!', profile_ready: 'Your text is ready!',
      words_written: 'Words written', sentences_label: 'Sentences',
      // Grammar
      wrong_with_answer: 'Incorrect. Correct answer:',
      // Test
      outstanding: 'Outstanding!', great_job: 'Great job!',
      good_effort: 'Good effort!', keep_studying: 'Keep studying!',
      results_by_cat: 'Results by category',
      incorrect_answers: 'Incorrect answers',
      perfect_score: 'Perfect score! No mistakes!',
      mc_type: 'Multiple choice', tf_type: 'True / False', fill_type: 'Fill in the blank',
      type_answer_ph: 'Type your answer...', correct_answer_show: 'Correct answer:',
      next_q: 'Next question →', see_results: 'See results →', retry_test: 'Try again',
      tap_flip: 'Tap card to flip',
      grammar_point: 'Grammar',
      grammar_theory: 'Theory',
      grammar_tip: 'Key rule',
      grammar_practice: 'Practice',
      exercises_label: 'exercises',
      finish_lesson: 'Finish lesson',
    },
    module: {
      after_module:    'After this module you will be able to:',
      plan_title:      'Module plan',
      plan_sub:        'What you\'ll study in each lesson',
      start_module:    'Start module',
      continue_module: 'Continue',
      lesson_word:     'lesson',
      of_word:         'of',
      no_done:         'No lessons completed yet',
      to_complete:     'To complete',
      left:            'remaining',
      all_done:        'All lessons completed!',
      unlock_test:     'Complete all lessons to unlock the final test',
      test_passed:     'Test passed!',
      final_test:      'Final test',
      module_done:     'Module completed',
      unlocks_after:   'Unlocks after all lessons',
      min_word:        'min',
      lessons_word:    'lessons',
      total_word:      'total',
      earn_word:       'earn',
      lesson_structure:'Lesson structure',
      lessons_done:    'lessons done',
      not_found:       'Module not found',
      words_word:      'words',
      completed_label: 'Completed',
      back_label:      '← Back',
      back_course:     '← Course',
      module_label:    'Module',
      exam_complete:   'Exam Complete',
      get_cert_a1:     'Get Your A1 Certificate',
      get_cert_a11:    'Get Your A1.1 Certificate',
      get_cert_a2:     'Get Your A2 Certificate',
      get_cert_b1:     'Get Your B1 Certificate',
      save_pdf:        'Print or save as PDF',
      re_read:         'Re-read',
      vocab_study:     'Study vocabulary',
      type_reading:    'Reading', type_listening: 'Listening',
      type_grammar:    'Grammar', type_writing: 'Writing',
      type_vocabulary: 'Vocabulary', type_test: 'Final Test',
    },
    common: {
      back: '← Back', all_levels: '← All levels', loading: 'Loading...', xp: 'XP', days: 'days',
      done_badge: 'Done', locked_badge: 'Locked',
      not_found: 'Not found', words: 'words',
      level_a1: 'Beginner', level_a11: 'Elementary',
      level_a2: 'Pre-Intermediate', level_b1: 'Intermediate',
      level_b2: 'Upper-Intermediate', level_c1: 'Advanced',
      level_not_found: 'Level not found',
      skill_reading: 'Reading', skill_listening: 'Listening',
      skill_writing: 'Writing', skill_speaking: 'Speaking',
      skill_grammar: 'Grammar',
      label_correct: 'Correct', label_read: 'Read',
    },
    layout: {
      logo: 'WKU', title: 'WKU · English', subtitle: 'Powered by KHAMADI English',
    },
    path: {
      course_progress: 'Course progress',
      modules_of: 'modules',
      completed_section: 'Completed',
      current_section: 'In progress',
      upcoming_section: 'Upcoming',
      next_module: 'Next',
      lessons_left: 'lessons left',
      lessons_of: 'lessons',
    },
    vocab_page: {
      title_lessons: 'Vocab lessons',
      avg_score: 'Avg score',
      empty_title: 'Vocabulary is empty',
      empty_sub: 'Words are added after completing vocabulary lessons',
      go_courses: 'Go to courses →',
      completed_lessons: 'Completed vocabulary lessons',
      repeat_btn: 'Repeat →',
    },
    panel: {
      logout: 'Sign out', logout_full: 'Sign out of account',
      teacher_label: 'Teacher', admin_label: 'Administrator',
      teacher_cabinet: 'Teacher panel', admin_cabinet: 'Admin panel',
      nav_dashboard: 'Dashboard', nav_groups: 'Groups', nav_students: 'Students',
      nav_teachers: 'Teachers', nav_other: 'Other panels', nav_manage: 'Management',
      welcome: 'Welcome',
      dash_subtitle: "Here's what's happening in your groups today",
      admin_subtitle: 'WKU English Platform',
      my_groups: 'My groups', create_group: '+ Create',
      recent_active: 'Recent activity', all_arrow: 'All →',
      no_groups: 'No groups', no_groups_sub: 'Create your first group',
      no_students: 'No students',
      stat_groups: 'My groups', stat_students: 'Students', stat_today: 'Active today', stat_progress: 'Avg progress',
      student_col: 'Student', level_col: 'Level', xp_col: 'XP', lessons_col: 'Lessons',
      streak_col: 'Streak', activity_col: 'Activity', group_col: 'Group', actions_col: 'Actions',
      today: 'Today', yesterday: 'Yesterday', never: 'Never', days_ago: 'd.',
      no_group_badge: 'No group', risk_badge: 'At risk',
      search_placeholder: '🔍 Name or email...',
      all_levels: 'All levels', all_activity: 'Any activity', last_7: '7 days', inactive_30: '30+ days',
      reset_filter: '✕ Reset',
      shown_of: 'Showing', of_word: 'of',
      create_btn: '+ Create group', cancel_btn: '✕ Cancel',
      group_name_label: 'Group name', level_label: 'Level', code_label: 'Access code',
      students_count: 'students', progress_label: 'progress',
      copy_code: 'Copy', copied: 'Copied!',
      open_group: 'Open group',
      change_pass: 'Change password', new_pass_ph: 'New password (min. 6 chars)',
      save_pass: '✓ Save password', saving: 'Saving...',
      pass_changed: '✓ Password changed', min_chars: 'At least 6 characters',
      all_teachers: 'Teachers', create_teacher: '+ Create teacher',
      teacher_name: 'Full name', teacher_email: 'Email', teacher_pass: 'Password',
      to_admin: '→ Admin', remove_teacher: '✕',
      stat_total_students: 'Students', stat_total_teachers: 'Teachers',
      stat_total_groups: 'Groups', stat_active_today: 'Active today',
      quick_actions: '⚡ Quick actions', platform_health: '📈 Platform health',
      total_xp: 'Total XP on platform', earned_by_all: 'Earned by all students',
      active_pct: 'Active today', students_per_group: 'Students per group',
      avg_xp_student: 'Avg XP/student', avg_suffix: ' avg',
    },
  },
}

export type ZkuT = typeof ZKU_T.ru

type Ctx = { lang: ZkuLang; setLang: (l: ZkuLang) => void; t: ZkuT }

const ZkuLangCtx = createContext<Ctx>({ lang: 'ru', setLang: () => {}, t: ZKU_T.ru })

export function ZkuLangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<ZkuLang>('ru')

  useEffect(() => {
    const saved = localStorage.getItem('zku-lang') as ZkuLang | null
    if (saved === 'ru' || saved === 'kz' || saved === 'en') setLangState(saved)
  }, [])

  function setLang(l: ZkuLang) {
    setLangState(l)
    localStorage.setItem('zku-lang', l)
  }

  return (
    <ZkuLangCtx.Provider value={{ lang, setLang, t: ZKU_T[lang] as typeof ZKU_T.ru }}>
      {children}
    </ZkuLangCtx.Provider>
  )
}

export function useZkuLang() { return useContext(ZkuLangCtx) }

export function ZkuLangSwitcher() {
  const { lang, setLang } = useZkuLang()
  return (
    <div style={{
      display: 'flex', gap: 2,
      background: 'rgba(255,255,255,0.08)',
      border: '1px solid rgba(255,255,255,0.12)',
      borderRadius: 10, padding: 3,
    }}>
      {(['ru', 'kz', 'en'] as ZkuLang[]).map(l => (
        <button key={l} onClick={() => setLang(l)} style={{
          padding: '5px 11px', borderRadius: 7, border: 'none',
          cursor: 'pointer', fontFamily: 'inherit',
          fontSize: 11, fontWeight: 800, letterSpacing: '0.04em',
          background: lang === l ? '#fff' : 'transparent',
          color: lang === l ? '#003876' : 'rgba(255,255,255,0.5)',
          transition: 'all 0.15s',
        }}>
          {l === 'ru' ? 'РУС' : l === 'kz' ? 'ҚАЗ' : 'ENG'}
        </button>
      ))}
    </div>
  )
}