-- ================================================================
-- SOCIAL SCIENCES B1  (45800af0-cc5a-4787-bf49-a58bcfda9f1a)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $ss_b1$ DECLARE
  c UUID := '45800af0-cc5a-4787-bf49-a58bcfda9f1a';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Introduction to Social Sciences',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Research Basics',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Sociology',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Academic Writing Basics',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Disciplines Overview',1,1,'vocabulary',true,true,'[{"en":"social sciences","ru":"социальные науки"},{"en":"sociology","ru":"социология"},{"en":"psychology","ru":"психология"},{"en":"economics","ru":"экономика"},{"en":"political science","ru":"политология"},{"en":"anthropology","ru":"антропология"},{"en":"geography","ru":"география"},{"en":"history","ru":"история"},{"en":"criminology","ru":"криминология"},{"en":"social policy","ru":"социальная политика"},{"en":"interdisciplinary","ru":"межотраслевой"},{"en":"theory","ru":"теория"},{"en":"methodology","ru":"методология"},{"en":"empirical","ru":"эмпирический"},{"en":"normative","ru":"нормативный"},{"en":"positivism","ru":"позитивизм"},{"en":"interpretivism","ru":"интерпретивизм"},{"en":"objective","ru":"объективный"},{"en":"subjective","ru":"субъективный"},{"en":"academic","ru":"академический"}]'::jsonb),
  (c,m1,'Society & Culture',2,2,'vocabulary',true,true,'[{"en":"society","ru":"общество"},{"en":"culture","ru":"культура"},{"en":"norms","ru":"нормы"},{"en":"values","ru":"ценности"},{"en":"beliefs","ru":"убеждения"},{"en":"customs","ru":"обычаи"},{"en":"tradition","ru":"традиция"},{"en":"language","ru":"язык"},{"en":"identity","ru":"идентичность"},{"en":"diversity","ru":"разнообразие"},{"en":"multiculturalism","ru":"мультикультурализм"},{"en":"subculture","ru":"субкультура"},{"en":"socialisation","ru":"социализация"},{"en":"symbols","ru":"символы"},{"en":"rituals","ru":"ритуалы"},{"en":"institution","ru":"институт"},{"en":"community","ru":"сообщество"},{"en":"social structure","ru":"социальная структура"},{"en":"change","ru":"изменение"},{"en":"globalisation","ru":"глобализация"}]'::jsonb),
  (c,m1,'Norms & Values',3,3,'vocabulary',true,true,'[{"en":"norm","ru":"норма"},{"en":"value","ru":"ценность"},{"en":"social norm","ru":"социальная норма"},{"en":"moral norm","ru":"моральная норма"},{"en":"formal norm","ru":"формальная норма"},{"en":"informal norm","ru":"неформальная норма"},{"en":"sanction","ru":"санкция"},{"en":"positive sanction","ru":"положительная санкция"},{"en":"negative sanction","ru":"отрицательная санкция"},{"en":"conformity","ru":"конформизм"},{"en":"deviance","ru":"девиация"},{"en":"law","ru":"закон"},{"en":"rule","ru":"правило"},{"en":"expectation","ru":"ожидание"},{"en":"reward","ru":"вознаграждение"},{"en":"punishment","ru":"наказание"},{"en":"internalise","ru":"интернализировать"},{"en":"transmit","ru":"передавать"},{"en":"generation","ru":"поколение"},{"en":"enforce","ru":"применять"}]'::jsonb),
  (c,m1,'Social Institutions',4,4,'vocabulary',true,true,'[{"en":"institution","ru":"институт"},{"en":"family","ru":"семья"},{"en":"education","ru":"образование"},{"en":"religion","ru":"религия"},{"en":"government","ru":"правительство"},{"en":"economy","ru":"экономика"},{"en":"healthcare","ru":"здравоохранение"},{"en":"media","ru":"СМИ"},{"en":"law enforcement","ru":"правоохранительные органы"},{"en":"military","ru":"вооружённые силы"},{"en":"social control","ru":"социальный контроль"},{"en":"function","ru":"функция"},{"en":"structure","ru":"структура"},{"en":"reproduce","ru":"воспроизводить"},{"en":"challenge","ru":"оспаривать"},{"en":"reform","ru":"реформа"},{"en":"dysfunctional","ru":"дисфункциональный"},{"en":"latent","ru":"скрытый"},{"en":"manifest","ru":"явный"},{"en":"role","ru":"роль"}]'::jsonb),
  (c,m1,'Socialisation',5,5,'vocabulary',true,true,'[{"en":"socialisation","ru":"социализация"},{"en":"primary socialisation","ru":"первичная социализация"},{"en":"secondary socialisation","ru":"вторичная социализация"},{"en":"family","ru":"семья"},{"en":"peer group","ru":"группа сверстников"},{"en":"school","ru":"школа"},{"en":"media","ru":"СМИ"},{"en":"religion","ru":"религия"},{"en":"agent","ru":"агент социализации"},{"en":"identity","ru":"идентичность"},{"en":"role model","ru":"образец для подражания"},{"en":"internalise","ru":"интернализировать"},{"en":"gender","ru":"гендер"},{"en":"class","ru":"класс"},{"en":"norms","ru":"нормы"},{"en":"values","ru":"ценности"},{"en":"interaction","ru":"взаимодействие"},{"en":"influence","ru":"влияние"},{"en":"development","ru":"развитие"},{"en":"culture","ru":"культура"}]'::jsonb),
  (c,m1,'Key Thinkers',6,6,'vocabulary',true,true,'[{"en":"Marx","ru":"Маркс"},{"en":"Durkheim","ru":"Дюркгейм"},{"en":"Weber","ru":"Вебер"},{"en":"Parsons","ru":"Парсонс"},{"en":"Goffman","ru":"Гофман"},{"en":"Bourdieu","ru":"Бурдьё"},{"en":"Foucault","ru":"Фуко"},{"en":"Mead","ru":"Мид"},{"en":"Comte","ru":"Конт"},{"en":"theory","ru":"теория"},{"en":"contribution","ru":"вклад"},{"en":"critique","ru":"критика"},{"en":"paradigm","ru":"парадигма"},{"en":"functionalism","ru":"функционализм"},{"en":"conflict theory","ru":"теория конфликта"},{"en":"symbolic interactionism","ru":"символический интеракционизм"},{"en":"structuralism","ru":"структурализм"},{"en":"postmodernism","ru":"постмодернизм"},{"en":"feminism","ru":"феминизм"},{"en":"Spencer","ru":"Спенсер"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Research Questions',1,7,'vocabulary',true,true,'[{"en":"research question","ru":"исследовательский вопрос"},{"en":"hypothesis","ru":"гипотеза"},{"en":"aim","ru":"цель"},{"en":"objective","ru":"задача"},{"en":"scope","ru":"область охвата"},{"en":"focus","ru":"фокус"},{"en":"formulate","ru":"формулировать"},{"en":"refine","ru":"уточнять"},{"en":"broad","ru":"широкий"},{"en":"narrow","ru":"узкий"},{"en":"feasible","ru":"осуществимый"},{"en":"answerable","ru":"поддающийся исследованию"},{"en":"original","ru":"оригинальный"},{"en":"gap","ru":"пробел"},{"en":"literature","ru":"литература"},{"en":"define","ru":"определять"},{"en":"operationalise","ru":"операционализировать"},{"en":"concept","ru":"концепция"},{"en":"variable","ru":"переменная"},{"en":"indicator","ru":"индикатор"}]'::jsonb),
  (c,m2,'Qualitative vs Quantitative',2,8,'vocabulary',true,true,'[{"en":"qualitative","ru":"качественный"},{"en":"quantitative","ru":"количественный"},{"en":"mixed methods","ru":"смешанные методы"},{"en":"data","ru":"данные"},{"en":"numbers","ru":"числа"},{"en":"words","ru":"слова"},{"en":"depth","ru":"глубина"},{"en":"breadth","ru":"широта"},{"en":"meaning","ru":"смысл"},{"en":"measurement","ru":"измерение"},{"en":"interview","ru":"интервью"},{"en":"survey","ru":"опрос"},{"en":"observation","ru":"наблюдение"},{"en":"statistical","ru":"статистический"},{"en":"thematic","ru":"тематический"},{"en":"inductive","ru":"индуктивный"},{"en":"deductive","ru":"дедуктивный"},{"en":"flexible","ru":"гибкий"},{"en":"structured","ru":"структурированный"},{"en":"epistemology","ru":"эпистемология"}]'::jsonb),
  (c,m2,'Data Collection',3,9,'vocabulary',true,true,'[{"en":"data","ru":"данные"},{"en":"primary data","ru":"первичные данные"},{"en":"secondary data","ru":"вторичные данные"},{"en":"observation","ru":"наблюдение"},{"en":"interview","ru":"интервью"},{"en":"questionnaire","ru":"анкета"},{"en":"focus group","ru":"фокус-группа"},{"en":"experiment","ru":"эксперимент"},{"en":"document analysis","ru":"анализ документов"},{"en":"fieldwork","ru":"полевая работа"},{"en":"sample","ru":"выборка"},{"en":"access","ru":"доступ"},{"en":"permission","ru":"разрешение"},{"en":"ethics","ru":"этика"},{"en":"validity","ru":"валидность"},{"en":"reliability","ru":"надёжность"},{"en":"generalisability","ru":"обобщаемость"},{"en":"triangulation","ru":"триангуляция"},{"en":"statistical data","ru":"статистические данные"},{"en":"entry","ru":"вход в поле исследования"}]'::jsonb),
  (c,m2,'Surveys',4,10,'vocabulary',true,true,'[{"en":"survey","ru":"опрос"},{"en":"questionnaire","ru":"анкета"},{"en":"respondent","ru":"респондент"},{"en":"sample","ru":"выборка"},{"en":"population","ru":"генеральная совокупность"},{"en":"random sampling","ru":"случайная выборка"},{"en":"stratified","ru":"стратифицированный"},{"en":"convenience","ru":"удобная выборка"},{"en":"snowball","ru":"снежный ком"},{"en":"response rate","ru":"уровень ответов"},{"en":"closed question","ru":"закрытый вопрос"},{"en":"open question","ru":"открытый вопрос"},{"en":"Likert scale","ru":"шкала Лайкерта"},{"en":"bias","ru":"предвзятость"},{"en":"pilot","ru":"пилотный"},{"en":"distribution","ru":"распространение"},{"en":"analyse","ru":"анализировать"},{"en":"code","ru":"кодировать"},{"en":"data entry","ru":"ввод данных"},{"en":"report","ru":"отчёт"}]'::jsonb),
  (c,m2,'Ethics',5,11,'vocabulary',true,true,'[{"en":"ethics","ru":"этика"},{"en":"informed consent","ru":"информированное согласие"},{"en":"anonymity","ru":"анонимность"},{"en":"confidentiality","ru":"конфиденциальность"},{"en":"harm","ru":"вред"},{"en":"vulnerability","ru":"уязвимость"},{"en":"deception","ru":"обман"},{"en":"debrief","ru":"разъяснение после исследования"},{"en":"data protection","ru":"защита данных"},{"en":"right to withdraw","ru":"право на выход из исследования"},{"en":"risk","ru":"риск"},{"en":"benefit","ru":"польза"},{"en":"approval","ru":"одобрение"},{"en":"ethics committee","ru":"этический комитет"},{"en":"plagiarism","ru":"плагиат"},{"en":"attribution","ru":"атрибуция"},{"en":"participant","ru":"участник"},{"en":"power","ru":"власть"},{"en":"trust","ru":"доверие"},{"en":"code of conduct","ru":"кодекс поведения"}]'::jsonb),
  (c,m2,'Citation',6,12,'vocabulary',true,true,'[{"en":"citation","ru":"цитирование"},{"en":"reference","ru":"ссылка"},{"en":"bibliography","ru":"библиография"},{"en":"Harvard referencing","ru":"гарвардский стиль"},{"en":"APA","ru":"стиль APA"},{"en":"MLA","ru":"стиль MLA"},{"en":"footnote","ru":"сноска"},{"en":"endnote","ru":"концевая сноска"},{"en":"in-text","ru":"внутритекстовый"},{"en":"author","ru":"автор"},{"en":"date","ru":"дата"},{"en":"title","ru":"название"},{"en":"page","ru":"страница"},{"en":"paraphrase","ru":"перефразировать"},{"en":"quote","ru":"цитата"},{"en":"plagiarism","ru":"плагиат"},{"en":"cite","ru":"цитировать"},{"en":"acknowledge","ru":"признавать"},{"en":"source","ru":"источник"},{"en":"secondary source","ru":"вторичный источник"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Social Class',1,13,'vocabulary',true,true,'[{"en":"social class","ru":"социальный класс"},{"en":"working class","ru":"рабочий класс"},{"en":"middle class","ru":"средний класс"},{"en":"upper class","ru":"высший класс"},{"en":"stratification","ru":"стратификация"},{"en":"mobility","ru":"мобильность"},{"en":"income","ru":"доход"},{"en":"wealth","ru":"богатство"},{"en":"occupation","ru":"профессия"},{"en":"education","ru":"образование"},{"en":"status","ru":"статус"},{"en":"prestige","ru":"престиж"},{"en":"Marxism","ru":"марксизм"},{"en":"Weber","ru":"Вебер"},{"en":"bourgeoisie","ru":"буржуазия"},{"en":"proletariat","ru":"пролетариат"},{"en":"inequality","ru":"неравенство"},{"en":"life chances","ru":"жизненные шансы"},{"en":"closure","ru":"социальное закрытие"},{"en":"meritocracy","ru":"меритократия"}]'::jsonb),
  (c,m3,'Gender',2,14,'vocabulary',true,true,'[{"en":"gender","ru":"гендер"},{"en":"sex","ru":"пол"},{"en":"gender role","ru":"гендерная роль"},{"en":"patriarchy","ru":"патриархат"},{"en":"feminism","ru":"феминизм"},{"en":"equality","ru":"равенство"},{"en":"stereotype","ru":"стереотип"},{"en":"socialisation","ru":"социализация"},{"en":"identity","ru":"идентичность"},{"en":"masculinity","ru":"мужественность"},{"en":"femininity","ru":"женственность"},{"en":"discrimination","ru":"дискриминация"},{"en":"glass ceiling","ru":"стеклянный потолок"},{"en":"pay gap","ru":"разрыв в оплате труда"},{"en":"domestic labour","ru":"домашний труд"},{"en":"representation","ru":"представительство"},{"en":"non-binary","ru":"небинарный"},{"en":"intersectionality","ru":"интерсекциональность"},{"en":"gendered","ru":"гендерно обусловленный"},{"en":"construct","ru":"конструкт"}]'::jsonb),
  (c,m3,'Race & Ethnicity',3,15,'vocabulary',true,true,'[{"en":"race","ru":"раса"},{"en":"ethnicity","ru":"этническая принадлежность"},{"en":"racism","ru":"расизм"},{"en":"discrimination","ru":"дискриминация"},{"en":"prejudice","ru":"предрассудок"},{"en":"stereotype","ru":"стереотип"},{"en":"institutional racism","ru":"институциональный расизм"},{"en":"diversity","ru":"разнообразие"},{"en":"inclusion","ru":"включённость"},{"en":"minority","ru":"меньшинство"},{"en":"majority","ru":"большинство"},{"en":"identity","ru":"идентичность"},{"en":"culture","ru":"культура"},{"en":"heritage","ru":"наследие"},{"en":"migration","ru":"миграция"},{"en":"integration","ru":"интеграция"},{"en":"assimilation","ru":"ассимиляция"},{"en":"multiculturalism","ru":"мультикультурализм"},{"en":"privilege","ru":"привилегия"},{"en":"intersectionality","ru":"интерсекциональность"}]'::jsonb),
  (c,m3,'Family',4,16,'vocabulary',true,true,'[{"en":"family","ru":"семья"},{"en":"nuclear family","ru":"нуклеарная семья"},{"en":"extended family","ru":"расширенная семья"},{"en":"single parent","ru":"одинокий родитель"},{"en":"reconstituted","ru":"воссозданная семья"},{"en":"cohabitation","ru":"сожительство"},{"en":"marriage","ru":"брак"},{"en":"divorce","ru":"развод"},{"en":"function","ru":"функция"},{"en":"socialisation","ru":"социализация"},{"en":"support","ru":"поддержка"},{"en":"change","ru":"изменение"},{"en":"diversity","ru":"разнообразие"},{"en":"structure","ru":"структура"},{"en":"role","ru":"роль"},{"en":"obligation","ru":"обязанность"},{"en":"relationship","ru":"отношения"},{"en":"decline","ru":"упадок"},{"en":"ideology","ru":"идеология"},{"en":"statistics","ru":"статистика"}]'::jsonb),
  (c,m3,'Education',5,17,'vocabulary',true,true,'[{"en":"education","ru":"образование"},{"en":"school","ru":"школа"},{"en":"curriculum","ru":"учебная программа"},{"en":"attainment","ru":"успеваемость"},{"en":"achievement gap","ru":"разрыв в успеваемости"},{"en":"meritocracy","ru":"меритократия"},{"en":"reproduce","ru":"воспроизводить"},{"en":"cultural capital","ru":"культурный капитал"},{"en":"hidden curriculum","ru":"скрытый учебный план"},{"en":"labelling","ru":"навешивание ярлыков"},{"en":"self-fulfilling prophecy","ru":"самосбывающееся пророчество"},{"en":"setting","ru":"потоковое деление"},{"en":"streaming","ru":"разделение по потокам"},{"en":"inequality","ru":"неравенство"},{"en":"policy","ru":"политика"},{"en":"gender gap","ru":"гендерный разрыв"},{"en":"ethnicity","ru":"этническая принадлежность"},{"en":"class","ru":"класс"},{"en":"privatisation","ru":"приватизация"},{"en":"outcomes","ru":"результаты"}]'::jsonb),
  (c,m3,'Deviance',6,18,'vocabulary',true,true,'[{"en":"deviance","ru":"девиация"},{"en":"crime","ru":"преступность"},{"en":"social control","ru":"социальный контроль"},{"en":"labelling","ru":"навешивание ярлыков"},{"en":"stigma","ru":"стигма"},{"en":"moral panic","ru":"моральная паника"},{"en":"strain theory","ru":"теория напряжения"},{"en":"anomie","ru":"аномия"},{"en":"subculture","ru":"субкультура"},{"en":"Marxist criminology","ru":"марксистская криминология"},{"en":"social learning","ru":"социальное обучение"},{"en":"differential association","ru":"дифференциальная ассоциация"},{"en":"official statistics","ru":"официальная статистика"},{"en":"dark figure","ru":"скрытая преступность"},{"en":"victim","ru":"жертва"},{"en":"rational choice","ru":"рациональный выбор"},{"en":"opportunity","ru":"возможность"},{"en":"deterrence","ru":"сдерживание"},{"en":"rehabilitation","ru":"реабилитация"},{"en":"recidivism","ru":"рецидив"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Essay Structure',1,19,'vocabulary',true,true,'[{"en":"essay","ru":"эссе"},{"en":"introduction","ru":"введение"},{"en":"body paragraph","ru":"основной абзац"},{"en":"conclusion","ru":"заключение"},{"en":"argument","ru":"аргумент"},{"en":"thesis statement","ru":"тезисное утверждение"},{"en":"topic sentence","ru":"тематическое предложение"},{"en":"evidence","ru":"доказательство"},{"en":"analysis","ru":"анализ"},{"en":"evaluation","ru":"оценка"},{"en":"link","ru":"связующее предложение"},{"en":"transition","ru":"переход"},{"en":"structure","ru":"структура"},{"en":"plan","ru":"план"},{"en":"draft","ru":"черновик"},{"en":"revise","ru":"пересматривать"},{"en":"proof","ru":"вычитывать"},{"en":"coherence","ru":"связность"},{"en":"flow","ru":"плавность"},{"en":"word count","ru":"количество слов"}]'::jsonb),
  (c,m4,'Paragraphing',2,20,'vocabulary',true,true,'[{"en":"paragraph","ru":"абзац"},{"en":"topic sentence","ru":"тематическое предложение"},{"en":"evidence","ru":"доказательство"},{"en":"explanation","ru":"объяснение"},{"en":"analysis","ru":"анализ"},{"en":"link","ru":"связка"},{"en":"PEE","ru":"структура PEE"},{"en":"PEEL","ru":"структура PEEL"},{"en":"structure","ru":"структура"},{"en":"unity","ru":"единство"},{"en":"coherence","ru":"связность"},{"en":"length","ru":"длина"},{"en":"indent","ru":"отступ"},{"en":"point","ru":"мысль"},{"en":"support","ru":"подкреплять"},{"en":"develop","ru":"развивать"},{"en":"evaluate","ru":"оценивать"},{"en":"conclude","ru":"заключать"},{"en":"transition","ru":"переход"},{"en":"flow","ru":"плавность"}]'::jsonb),
  (c,m4,'Thesis Statements',3,21,'vocabulary',true,true,'[{"en":"thesis","ru":"тезис"},{"en":"argument","ru":"аргумент"},{"en":"position","ru":"позиция"},{"en":"claim","ru":"утверждение"},{"en":"main point","ru":"главная мысль"},{"en":"debatable","ru":"дискуссионный"},{"en":"specific","ru":"конкретный"},{"en":"focused","ru":"целенаправленный"},{"en":"clear","ru":"чёткий"},{"en":"essay map","ru":"карта эссе"},{"en":"introduce","ru":"вводить"},{"en":"signal","ru":"сигнализировать"},{"en":"direction","ru":"направление"},{"en":"complex","ru":"сложный"},{"en":"narrow","ru":"узкий"},{"en":"broad","ru":"широкий"},{"en":"refine","ru":"уточнять"},{"en":"develop","ru":"развивать"},{"en":"academic","ru":"академический"},{"en":"purpose","ru":"цель"}]'::jsonb),
  (c,m4,'Referencing',4,22,'vocabulary',true,true,'[{"en":"reference","ru":"ссылка"},{"en":"bibliography","ru":"библиография"},{"en":"in-text citation","ru":"внутритекстовое цитирование"},{"en":"Harvard referencing","ru":"гарвардский стиль"},{"en":"author","ru":"автор"},{"en":"date","ru":"дата"},{"en":"title","ru":"название"},{"en":"publisher","ru":"издатель"},{"en":"page","ru":"страница"},{"en":"URL","ru":"URL"},{"en":"accessed date","ru":"дата обращения"},{"en":"paraphrase","ru":"перефразирование"},{"en":"quotation","ru":"цитата"},{"en":"cite","ru":"цитировать"},{"en":"academic integrity","ru":"академическая честность"},{"en":"plagiarism","ru":"плагиат"},{"en":"ibid","ru":"там же"},{"en":"secondary source","ru":"вторичный источник"},{"en":"reference list","ru":"список источников"},{"en":"op cit","ru":"из уже цитированного"}]'::jsonb),
  (c,m4,'Paraphrasing',5,23,'vocabulary',true,true,'[{"en":"paraphrase","ru":"перефразирование"},{"en":"rephrase","ru":"переформулировать"},{"en":"own words","ru":"своими словами"},{"en":"meaning","ru":"смысл"},{"en":"cite","ru":"цитировать"},{"en":"source","ru":"источник"},{"en":"avoid plagiarism","ru":"избегать плагиата"},{"en":"synonyms","ru":"синонимы"},{"en":"restructure","ru":"переструктурировать"},{"en":"academic voice","ru":"академический стиль"},{"en":"close paraphrase","ru":"близкое перефразирование"},{"en":"summary","ru":"краткое изложение"},{"en":"quotation","ru":"прямая цитата"},{"en":"signal phrase","ru":"вводная фраза"},{"en":"author","ru":"автор"},{"en":"interpretation","ru":"интерпретация"},{"en":"change","ru":"изменять"},{"en":"retain meaning","ru":"сохранять смысл"},{"en":"citation","ru":"цитирование"},{"en":"acknowledge","ru":"признавать"}]'::jsonb),
  (c,m4,'Vocabulary',6,24,'vocabulary',true,true,'[{"en":"academic vocabulary","ru":"академическая лексика"},{"en":"formal","ru":"формальный"},{"en":"hedging","ru":"хеджирование"},{"en":"signpost","ru":"сигнальное слово"},{"en":"stance","ru":"позиция"},{"en":"evaluate","ru":"оценивать"},{"en":"analyse","ru":"анализировать"},{"en":"argue","ru":"утверждать"},{"en":"suggest","ru":"предполагать"},{"en":"indicate","ru":"указывать"},{"en":"demonstrate","ru":"демонстрировать"},{"en":"examine","ru":"исследовать"},{"en":"critically","ru":"критически"},{"en":"review","ru":"рассматривать"},{"en":"consider","ru":"рассматривать"},{"en":"contrast","ru":"противопоставлять"},{"en":"support","ru":"поддерживать"},{"en":"challenge","ru":"оспаривать"},{"en":"nuance","ru":"нюанс"},{"en":"discipline-specific","ru":"отраслевой"}]'::jsonb);

  RAISE NOTICE 'Social Sciences B1: 4 modules, 24 lessons inserted';
END $ss_b1$;
