-- ================================================================
-- MANAGEMENT B1  (41f65a3f-2d1e-4281-a249-7d7b5f255352)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $mgmt_b1$ DECLARE
  c UUID := '41f65a3f-2d1e-4281-a249-7d7b5f255352';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Management Fundamentals',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Communication',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Team Management',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Business Documents',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Roles of Managers',1,1,'vocabulary',true,true,'[{"en":"manager","ru":"менеджер"},{"en":"managing director","ru":"генеральный директор"},{"en":"CEO","ru":"генеральный директор"},{"en":"supervisor","ru":"руководитель"},{"en":"team leader","ru":"лидер команды"},{"en":"department head","ru":"руководитель отдела"},{"en":"line manager","ru":"непосредственный руководитель"},{"en":"middle manager","ru":"менеджер среднего звена"},{"en":"senior manager","ru":"старший менеджер"},{"en":"board","ru":"совет директоров"},{"en":"responsibility","ru":"ответственность"},{"en":"authority","ru":"полномочия"},{"en":"accountability","ru":"подотчётность"},{"en":"span of control","ru":"норма управляемости"},{"en":"hierarchy","ru":"иерархия"},{"en":"reporting","ru":"подотчётность"},{"en":"role","ru":"роль"},{"en":"function","ru":"функция"},{"en":"task","ru":"задача"},{"en":"delegation","ru":"делегирование"}]'::jsonb),
  (c,m1,'Planning',2,2,'vocabulary',true,true,'[{"en":"plan","ru":"план"},{"en":"objective","ru":"цель"},{"en":"goal","ru":"задача"},{"en":"target","ru":"ориентир"},{"en":"strategy","ru":"стратегия"},{"en":"tactic","ru":"тактика"},{"en":"timeline","ru":"сроки"},{"en":"milestone","ru":"веха"},{"en":"action plan","ru":"план действий"},{"en":"resource","ru":"ресурс"},{"en":"budget","ru":"бюджет"},{"en":"forecast","ru":"прогноз"},{"en":"scenario","ru":"сценарий"},{"en":"contingency","ru":"запасной план"},{"en":"review","ru":"обзор"},{"en":"monitor","ru":"контролировать"},{"en":"adjust","ru":"корректировать"},{"en":"prioritise","ru":"расставлять приоритеты"},{"en":"SMART","ru":"SMART-цели"},{"en":"alignment","ru":"согласованность"}]'::jsonb),
  (c,m1,'Organising',3,3,'vocabulary',true,true,'[{"en":"organise","ru":"организовывать"},{"en":"structure","ru":"структура"},{"en":"hierarchy","ru":"иерархия"},{"en":"department","ru":"отдел"},{"en":"team","ru":"команда"},{"en":"role","ru":"роль"},{"en":"job description","ru":"должностная инструкция"},{"en":"responsibility","ru":"ответственность"},{"en":"authority","ru":"полномочия"},{"en":"coordination","ru":"координация"},{"en":"communication","ru":"коммуникация"},{"en":"span of control","ru":"норма управляемости"},{"en":"matrix","ru":"матричная структура"},{"en":"flat structure","ru":"плоская структура"},{"en":"line authority","ru":"линейные полномочия"},{"en":"functional","ru":"функциональный"},{"en":"divisional","ru":"дивизиональный"},{"en":"geographic","ru":"географический"},{"en":"integration","ru":"интеграция"},{"en":"staff authority","ru":"штабные полномочия"}]'::jsonb),
  (c,m1,'Leading',4,4,'vocabulary',true,true,'[{"en":"leadership","ru":"лидерство"},{"en":"vision","ru":"видение"},{"en":"inspire","ru":"вдохновлять"},{"en":"motivate","ru":"мотивировать"},{"en":"guide","ru":"направлять"},{"en":"delegate","ru":"делегировать"},{"en":"communicate","ru":"общаться"},{"en":"empower","ru":"наделять полномочиями"},{"en":"coach","ru":"коучинг"},{"en":"mentor","ru":"наставничество"},{"en":"support","ru":"поддерживать"},{"en":"direction","ru":"направление"},{"en":"example","ru":"пример"},{"en":"relationship","ru":"отношения"},{"en":"trust","ru":"доверие"},{"en":"team","ru":"команда"},{"en":"individual","ru":"индивидуум"},{"en":"style","ru":"стиль"},{"en":"transformational","ru":"трансформационный"},{"en":"transactional","ru":"транзакционный"}]'::jsonb),
  (c,m1,'Controlling',5,5,'vocabulary',true,true,'[{"en":"control","ru":"контроль"},{"en":"monitor","ru":"отслеживать"},{"en":"measure","ru":"измерять"},{"en":"KPI","ru":"КПЭ"},{"en":"target","ru":"целевой показатель"},{"en":"actual","ru":"фактический"},{"en":"variance","ru":"отклонение"},{"en":"report","ru":"отчёт"},{"en":"feedback","ru":"обратная связь"},{"en":"corrective action","ru":"корректирующее действие"},{"en":"standard","ru":"стандарт"},{"en":"benchmark","ru":"эталон"},{"en":"performance review","ru":"оценка эффективности"},{"en":"audit","ru":"аудит"},{"en":"quality control","ru":"контроль качества"},{"en":"financial control","ru":"финансовый контроль"},{"en":"risk control","ru":"контроль рисков"},{"en":"process","ru":"процесс"},{"en":"review cycle","ru":"цикл проверки"},{"en":"dashboard","ru":"панель мониторинга"}]'::jsonb),
  (c,m1,'Management Styles',6,6,'vocabulary',true,true,'[{"en":"autocratic","ru":"авторитарный"},{"en":"democratic","ru":"демократический"},{"en":"laissez-faire","ru":"попустительский"},{"en":"coaching","ru":"наставнический"},{"en":"visionary","ru":"визионерский"},{"en":"affiliative","ru":"партнёрский"},{"en":"pace-setting","ru":"задающий темп"},{"en":"servant leadership","ru":"слуга-лидер"},{"en":"situational","ru":"ситуационный"},{"en":"contingency","ru":"ситуативный"},{"en":"style","ru":"стиль"},{"en":"subordinate","ru":"подчинённый"},{"en":"task","ru":"задача"},{"en":"relationship","ru":"отношения"},{"en":"effectiveness","ru":"эффективность"},{"en":"context","ru":"контекст"},{"en":"adapt","ru":"адаптировать"},{"en":"preference","ru":"предпочтение"},{"en":"culture","ru":"культура"},{"en":"development level","ru":"уровень развития"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Workplace Communication',1,7,'vocabulary',true,true,'[{"en":"communication","ru":"коммуникация"},{"en":"message","ru":"сообщение"},{"en":"sender","ru":"отправитель"},{"en":"receiver","ru":"получатель"},{"en":"channel","ru":"канал"},{"en":"feedback","ru":"обратная связь"},{"en":"barrier","ru":"барьер"},{"en":"noise","ru":"помехи"},{"en":"verbal","ru":"вербальный"},{"en":"non-verbal","ru":"невербальный"},{"en":"formal","ru":"официальный"},{"en":"informal","ru":"неформальный"},{"en":"upward","ru":"восходящий"},{"en":"downward","ru":"нисходящий"},{"en":"lateral","ru":"горизонтальный"},{"en":"written","ru":"письменный"},{"en":"oral","ru":"устный"},{"en":"digital","ru":"цифровой"},{"en":"face-to-face","ru":"личный"},{"en":"clarity","ru":"ясность"}]'::jsonb),
  (c,m2,'Meetings',2,8,'vocabulary',true,true,'[{"en":"agenda","ru":"повестка дня"},{"en":"minutes","ru":"протокол"},{"en":"chairperson","ru":"председатель"},{"en":"action point","ru":"задача"},{"en":"attendee","ru":"участник"},{"en":"quorum","ru":"кворум"},{"en":"item","ru":"пункт повестки"},{"en":"time-keeping","ru":"соблюдение времени"},{"en":"objective","ru":"цель"},{"en":"outcome","ru":"результат"},{"en":"decision","ru":"решение"},{"en":"follow-up","ru":"дальнейшие шаги"},{"en":"AOB","ru":"разное"},{"en":"virtual","ru":"виртуальный"},{"en":"in-person","ru":"очный"},{"en":"facilitate","ru":"вести"},{"en":"defer","ru":"откладывать"},{"en":"summary","ru":"резюме"},{"en":"schedule","ru":"расписание"},{"en":"interrupt","ru":"перебивать"}]'::jsonb),
  (c,m2,'Emails',3,9,'vocabulary',true,true,'[{"en":"subject line","ru":"тема письма"},{"en":"greeting","ru":"обращение"},{"en":"body","ru":"основная часть"},{"en":"closing","ru":"заключительная фраза"},{"en":"CC","ru":"копия"},{"en":"BCC","ru":"скрытая копия"},{"en":"reply all","ru":"ответить всем"},{"en":"attachment","ru":"вложение"},{"en":"professional tone","ru":"деловой тон"},{"en":"brief","ru":"краткий"},{"en":"purpose","ru":"цель"},{"en":"urgent","ru":"срочный"},{"en":"flag","ru":"отметить"},{"en":"thread","ru":"ветка"},{"en":"response time","ru":"время ответа"},{"en":"archive","ru":"архивировать"},{"en":"folder","ru":"папка"},{"en":"etiquette","ru":"этикет"},{"en":"clear","ru":"понятный"},{"en":"concise","ru":"лаконичный"}]'::jsonb),
  (c,m2,'Reports',4,10,'vocabulary',true,true,'[{"en":"report","ru":"отчёт"},{"en":"executive summary","ru":"резюме"},{"en":"introduction","ru":"введение"},{"en":"findings","ru":"выводы"},{"en":"analysis","ru":"анализ"},{"en":"recommendation","ru":"рекомендация"},{"en":"conclusion","ru":"заключение"},{"en":"appendix","ru":"приложение"},{"en":"chart","ru":"диаграмма"},{"en":"table","ru":"таблица"},{"en":"evidence","ru":"доказательства"},{"en":"data","ru":"данные"},{"en":"visual","ru":"визуализация"},{"en":"audience","ru":"аудитория"},{"en":"format","ru":"формат"},{"en":"heading","ru":"заголовок"},{"en":"length","ru":"объём"},{"en":"reference","ru":"ссылка"},{"en":"distribution","ru":"рассылка"},{"en":"approval","ru":"согласование"}]'::jsonb),
  (c,m2,'Presentations',5,11,'vocabulary',true,true,'[{"en":"presentation","ru":"презентация"},{"en":"slide","ru":"слайд"},{"en":"audience","ru":"аудитория"},{"en":"objective","ru":"цель"},{"en":"message","ru":"ключевое сообщение"},{"en":"structure","ru":"структура"},{"en":"delivery","ru":"подача"},{"en":"eye contact","ru":"зрительный контакт"},{"en":"voice","ru":"голос"},{"en":"pace","ru":"темп"},{"en":"question","ru":"вопрос"},{"en":"visual","ru":"визуальный"},{"en":"data","ru":"данные"},{"en":"rehearse","ru":"репетировать"},{"en":"time","ru":"хронометраж"},{"en":"confidence","ru":"уверенность"},{"en":"body language","ru":"язык тела"},{"en":"transition","ru":"переход"},{"en":"key point","ru":"ключевой момент"},{"en":"summary","ru":"резюме"}]'::jsonb),
  (c,m2,'Active Listening',6,12,'vocabulary',true,true,'[{"en":"active listening","ru":"активное слушание"},{"en":"attention","ru":"внимание"},{"en":"eye contact","ru":"зрительный контакт"},{"en":"nod","ru":"кивок"},{"en":"body language","ru":"язык тела"},{"en":"paraphrase","ru":"перефразировать"},{"en":"summarise","ru":"подводить итог"},{"en":"clarify","ru":"уточнять"},{"en":"empathy","ru":"эмпатия"},{"en":"open question","ru":"открытый вопрос"},{"en":"closed question","ru":"закрытый вопрос"},{"en":"interrupt","ru":"перебивать"},{"en":"reflect","ru":"отражать"},{"en":"follow-up","ru":"уточняющий вопрос"},{"en":"understand","ru":"понимать"},{"en":"feedback","ru":"обратная связь"},{"en":"distraction","ru":"отвлечение"},{"en":"focus","ru":"концентрация"},{"en":"genuinely","ru":"искренне"},{"en":"two-way","ru":"двусторонний"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Team Roles',1,13,'vocabulary',true,true,'[{"en":"team","ru":"команда"},{"en":"role","ru":"роль"},{"en":"Belbin","ru":"Белбин"},{"en":"plant","ru":"генератор идей"},{"en":"resource investigator","ru":"исследователь ресурсов"},{"en":"coordinator","ru":"координатор"},{"en":"shaper","ru":"движущая сила"},{"en":"monitor evaluator","ru":"оценщик"},{"en":"teamworker","ru":"командный игрок"},{"en":"implementer","ru":"исполнитель"},{"en":"completer finisher","ru":"доводчик"},{"en":"specialist","ru":"специалист"},{"en":"strength","ru":"сильная сторона"},{"en":"weakness","ru":"слабая сторона"},{"en":"diversity","ru":"разнообразие"},{"en":"complement","ru":"дополнять"},{"en":"effectiveness","ru":"эффективность"},{"en":"balance","ru":"баланс"},{"en":"assign","ru":"назначать"},{"en":"clarify","ru":"уточнять"}]'::jsonb),
  (c,m3,'Motivation',2,14,'vocabulary',true,true,'[{"en":"motivation","ru":"мотивация"},{"en":"Maslow","ru":"Маслоу"},{"en":"Herzberg","ru":"Герцберг"},{"en":"Theory X","ru":"Теория X"},{"en":"Theory Y","ru":"Теория Y"},{"en":"intrinsic","ru":"внутренняя"},{"en":"extrinsic","ru":"внешняя"},{"en":"reward","ru":"вознаграждение"},{"en":"recognition","ru":"признание"},{"en":"autonomy","ru":"автономия"},{"en":"challenge","ru":"вызов"},{"en":"growth","ru":"рост"},{"en":"responsibility","ru":"ответственность"},{"en":"feedback","ru":"обратная связь"},{"en":"goal setting","ru":"постановка целей"},{"en":"appraisal","ru":"оценка"},{"en":"engagement","ru":"вовлечённость"},{"en":"morale","ru":"моральный дух"},{"en":"job satisfaction","ru":"удовлетворённость работой"},{"en":"hygiene factor","ru":"гигиенический фактор"}]'::jsonb),
  (c,m3,'Delegation',3,15,'vocabulary',true,true,'[{"en":"delegate","ru":"делегировать"},{"en":"task","ru":"задача"},{"en":"authority","ru":"полномочия"},{"en":"responsibility","ru":"ответственность"},{"en":"accountability","ru":"подотчётность"},{"en":"brief","ru":"инструктировать"},{"en":"clear","ru":"чёткий"},{"en":"deadline","ru":"срок"},{"en":"check","ru":"проверять"},{"en":"support","ru":"поддерживать"},{"en":"trust","ru":"доверие"},{"en":"develop","ru":"развивать"},{"en":"capability","ru":"способность"},{"en":"appropriate","ru":"подходящий"},{"en":"micromanage","ru":"микроменеджмент"},{"en":"empower","ru":"наделять полномочиями"},{"en":"feedback","ru":"обратная связь"},{"en":"outcome","ru":"результат"},{"en":"follow-up","ru":"контроль"},{"en":"workload","ru":"рабочая нагрузка"}]'::jsonb),
  (c,m3,'Conflict Resolution',4,16,'vocabulary',true,true,'[{"en":"conflict","ru":"конфликт"},{"en":"disagreement","ru":"разногласие"},{"en":"cause","ru":"причина"},{"en":"interests","ru":"интересы"},{"en":"position","ru":"позиция"},{"en":"negotiation","ru":"переговоры"},{"en":"mediation","ru":"медиация"},{"en":"facilitate","ru":"способствовать"},{"en":"listen","ru":"слушать"},{"en":"understand","ru":"понять"},{"en":"solution","ru":"решение"},{"en":"compromise","ru":"компромисс"},{"en":"win-win","ru":"взаимовыгодный"},{"en":"assert","ru":"отстаивать"},{"en":"aggressive","ru":"агрессивный"},{"en":"passive","ru":"пассивный"},{"en":"assertive","ru":"настойчивый"},{"en":"escalate","ru":"эскалировать"},{"en":"policy","ru":"политика"},{"en":"resolution","ru":"урегулирование"}]'::jsonb),
  (c,m3,'Feedback',5,17,'vocabulary',true,true,'[{"en":"feedback","ru":"обратная связь"},{"en":"positive","ru":"позитивный"},{"en":"constructive","ru":"конструктивный"},{"en":"specific","ru":"конкретный"},{"en":"timely","ru":"своевременный"},{"en":"behaviour","ru":"поведение"},{"en":"impact","ru":"воздействие"},{"en":"observation","ru":"наблюдение"},{"en":"suggestion","ru":"предложение"},{"en":"improvement","ru":"улучшение"},{"en":"two-way","ru":"двусторонний"},{"en":"receive","ru":"принимать"},{"en":"react","ru":"реагировать"},{"en":"action","ru":"действие"},{"en":"development","ru":"развитие"},{"en":"annual","ru":"ежегодный"},{"en":"informal","ru":"неформальный"},{"en":"360-degree","ru":"360-градусная обратная связь"},{"en":"peer","ru":"коллега"},{"en":"manager","ru":"менеджер"}]'::jsonb),
  (c,m3,'Performance',6,18,'vocabulary',true,true,'[{"en":"performance","ru":"эффективность"},{"en":"objective","ru":"цель"},{"en":"KPI","ru":"КПЭ"},{"en":"target","ru":"целевой показатель"},{"en":"measure","ru":"измерять"},{"en":"appraisal","ru":"аттестация"},{"en":"review","ru":"обзор"},{"en":"rating","ru":"рейтинг"},{"en":"underperformance","ru":"недостаточная эффективность"},{"en":"support","ru":"поддержка"},{"en":"improvement plan","ru":"план по улучшению"},{"en":"PIP","ru":"план повышения эффективности"},{"en":"progress","ru":"прогресс"},{"en":"recognition","ru":"признание"},{"en":"reward","ru":"вознаграждение"},{"en":"development","ru":"развитие"},{"en":"succession","ru":"преемственность"},{"en":"talent","ru":"талант"},{"en":"high performer","ru":"высокоэффективный сотрудник"},{"en":"manage out","ru":"мягкое увольнение"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Business Reports',1,19,'vocabulary',true,true,'[{"en":"executive summary","ru":"резюме для руководства"},{"en":"findings","ru":"выводы"},{"en":"recommendation","ru":"рекомендация"},{"en":"conclusion","ru":"заключение"},{"en":"methodology","ru":"методология"},{"en":"evidence","ru":"доказательства"},{"en":"chart","ru":"диаграмма"},{"en":"table","ru":"таблица"},{"en":"heading","ru":"заголовок"},{"en":"format","ru":"формат"},{"en":"distribution","ru":"рассылка"},{"en":"approval","ru":"согласование"},{"en":"length","ru":"объём"},{"en":"audience","ru":"аудитория"},{"en":"purpose","ru":"цель"},{"en":"reference","ru":"ссылка"},{"en":"appendix","ru":"приложение"},{"en":"objective","ru":"цель"},{"en":"scope","ru":"область охвата"},{"en":"sign-off","ru":"согласование"}]'::jsonb),
  (c,m4,'Memos',2,20,'vocabulary',true,true,'[{"en":"memo","ru":"служебная записка"},{"en":"internal","ru":"внутренний"},{"en":"brief","ru":"краткий"},{"en":"to","ru":"кому"},{"en":"from","ru":"от кого"},{"en":"date","ru":"дата"},{"en":"subject","ru":"тема"},{"en":"body","ru":"основная часть"},{"en":"action","ru":"действие"},{"en":"informal","ru":"неформальный"},{"en":"note","ru":"заметка"},{"en":"circulation","ru":"рассылка"},{"en":"file","ru":"хранить"},{"en":"reference","ru":"ссылка"},{"en":"follow-up","ru":"дальнейшие шаги"},{"en":"record","ru":"запись"},{"en":"instruction","ru":"инструкция"},{"en":"update","ru":"обновление"},{"en":"query","ru":"запрос"},{"en":"response","ru":"ответ"}]'::jsonb),
  (c,m4,'Meeting Minutes',3,21,'vocabulary',true,true,'[{"en":"minutes","ru":"протокол"},{"en":"attendees","ru":"участники"},{"en":"apologies","ru":"извинения за отсутствие"},{"en":"actions","ru":"задачи"},{"en":"discussion","ru":"обсуждение"},{"en":"decision","ru":"решение"},{"en":"next steps","ru":"следующие шаги"},{"en":"responsible","ru":"ответственный"},{"en":"deadline","ru":"срок"},{"en":"agenda item","ru":"пункт повестки"},{"en":"AOB","ru":"разное"},{"en":"sign off","ru":"утвердить"},{"en":"distribution","ru":"рассылка"},{"en":"accurate","ru":"точный"},{"en":"timely","ru":"своевременный"},{"en":"reference","ru":"ссылка"},{"en":"format","ru":"формат"},{"en":"previous minutes","ru":"предыдущий протокол"},{"en":"matters arising","ru":"вопросы по предыдущему протоколу"},{"en":"chairperson","ru":"председатель"}]'::jsonb),
  (c,m4,'Proposals',4,22,'vocabulary',true,true,'[{"en":"proposal","ru":"предложение"},{"en":"business case","ru":"бизнес-обоснование"},{"en":"objective","ru":"цель"},{"en":"solution","ru":"решение"},{"en":"benefit","ru":"выгода"},{"en":"cost","ru":"затраты"},{"en":"ROI","ru":"рентабельность инвестиций"},{"en":"timeline","ru":"сроки"},{"en":"resource","ru":"ресурс"},{"en":"risk","ru":"риск"},{"en":"recommendation","ru":"рекомендация"},{"en":"approval","ru":"согласование"},{"en":"scope","ru":"область охвата"},{"en":"alternative","ru":"альтернатива"},{"en":"feasibility","ru":"осуществимость"},{"en":"sponsor","ru":"спонсор"},{"en":"audience","ru":"аудитория"},{"en":"format","ru":"формат"},{"en":"presentation","ru":"презентация"},{"en":"decision","ru":"решение"}]'::jsonb),
  (c,m4,'KPI Dashboards',5,23,'vocabulary',true,true,'[{"en":"dashboard","ru":"панель мониторинга"},{"en":"KPI","ru":"КПЭ"},{"en":"metric","ru":"показатель"},{"en":"target","ru":"целевой показатель"},{"en":"actual","ru":"фактический"},{"en":"variance","ru":"отклонение"},{"en":"trend","ru":"тенденция"},{"en":"chart","ru":"диаграмма"},{"en":"table","ru":"таблица"},{"en":"RAG","ru":"RAG-статус"},{"en":"red amber green","ru":"красный янтарный зелёный"},{"en":"period","ru":"период"},{"en":"cumulative","ru":"нарастающий итог"},{"en":"forecast","ru":"прогноз"},{"en":"drill down","ru":"детализация"},{"en":"filter","ru":"фильтр"},{"en":"update","ru":"обновлять"},{"en":"distribute","ru":"распространять"},{"en":"review","ru":"обзор"},{"en":"colour code","ru":"цветовая кодировка"}]'::jsonb),
  (c,m4,'Correspondence',6,24,'vocabulary',true,true,'[{"en":"business letter","ru":"деловое письмо"},{"en":"formal","ru":"официальный"},{"en":"heading","ru":"заголовок"},{"en":"date","ru":"дата"},{"en":"address","ru":"адрес"},{"en":"salutation","ru":"обращение"},{"en":"purpose","ru":"цель"},{"en":"body","ru":"основная часть"},{"en":"action","ru":"действие"},{"en":"closing","ru":"заключительная фраза"},{"en":"signature","ru":"подпись"},{"en":"attachment","ru":"вложение"},{"en":"professional","ru":"профессиональный"},{"en":"tone","ru":"тон"},{"en":"grammar","ru":"грамматика"},{"en":"proofread","ru":"вычитывать"},{"en":"response time","ru":"время ответа"},{"en":"filing","ru":"хранение"},{"en":"copy","ru":"копия"},{"en":"distribute","ru":"распространять"}]'::jsonb);

  RAISE NOTICE 'Management B1: 4 modules, 24 lessons inserted';
END $mgmt_b1$;
