-- ================================================================
-- FINANCE INDUSTRY B1  (13f80caf-c0ea-4cae-bb68-225c418d6b7b)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $fin_b1$ DECLARE
  c UUID := '13f80caf-c0ea-4cae-bb68-225c418d6b7b';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Financial System',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Banking Basics',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Investment Basics',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Financial Documents',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Banks & Institutions',1,1,'vocabulary',true,true,'[{"en":"bank","ru":"банк"},{"en":"central bank","ru":"центральный банк"},{"en":"commercial bank","ru":"коммерческий банк"},{"en":"investment bank","ru":"инвестиционный банк"},{"en":"retail bank","ru":"розничный банк"},{"en":"credit union","ru":"кредитный союз"},{"en":"financial institution","ru":"финансовое учреждение"},{"en":"regulator","ru":"регулятор"},{"en":"monetary policy","ru":"денежно-кредитная политика"},{"en":"deposit","ru":"депозит"},{"en":"lending","ru":"кредитование"},{"en":"reserve","ru":"резерв"},{"en":"supervision","ru":"надзор"},{"en":"prudential","ru":"пруденциальный"},{"en":"Basel","ru":"Базельские соглашения"},{"en":"systemic risk","ru":"системный риск"},{"en":"financial stability","ru":"финансовая стабильность"},{"en":"liquidity","ru":"ликвидность"},{"en":"capital","ru":"капитал"},{"en":"building society","ru":"строительное общество"}]'::jsonb),
  (c,m1,'Central Banks',2,2,'vocabulary',true,true,'[{"en":"central bank","ru":"центральный банк"},{"en":"monetary policy","ru":"денежно-кредитная политика"},{"en":"interest rate","ru":"процентная ставка"},{"en":"base rate","ru":"базовая ставка"},{"en":"inflation target","ru":"целевой уровень инфляции"},{"en":"quantitative easing","ru":"количественное смягчение"},{"en":"open market operations","ru":"операции на открытом рынке"},{"en":"reserve requirement","ru":"норма обязательных резервов"},{"en":"lender of last resort","ru":"кредитор последней инстанции"},{"en":"bank supervision","ru":"банковский надзор"},{"en":"currency","ru":"валюта"},{"en":"foreign exchange reserve","ru":"валютный резерв"},{"en":"payment system","ru":"платёжная система"},{"en":"financial stability","ru":"финансовая стабильность"},{"en":"mandate","ru":"мандат"},{"en":"governor","ru":"глава центробанка"},{"en":"committee","ru":"комитет"},{"en":"minutes","ru":"протокол заседания"},{"en":"independence","ru":"независимость"},{"en":"inflation","ru":"инфляция"}]'::jsonb),
  (c,m1,'Financial Markets',3,3,'vocabulary',true,true,'[{"en":"financial market","ru":"финансовый рынок"},{"en":"capital market","ru":"рынок капитала"},{"en":"money market","ru":"денежный рынок"},{"en":"primary market","ru":"первичный рынок"},{"en":"secondary market","ru":"вторичный рынок"},{"en":"equities","ru":"акции"},{"en":"bonds","ru":"облигации"},{"en":"derivatives","ru":"деривативы"},{"en":"forex","ru":"валютный рынок"},{"en":"commodities","ru":"товарные ресурсы"},{"en":"liquidity","ru":"ликвидность"},{"en":"price discovery","ru":"ценообразование"},{"en":"efficiency","ru":"эффективность"},{"en":"transparency","ru":"прозрачность"},{"en":"regulation","ru":"регулирование"},{"en":"participants","ru":"участники"},{"en":"intermediary","ru":"посредник"},{"en":"exchange","ru":"биржа"},{"en":"OTC","ru":"внебиржевой рынок"},{"en":"settlement","ru":"расчёт"}]'::jsonb),
  (c,m1,'Money & Currency',4,4,'vocabulary',true,true,'[{"en":"currency","ru":"валюта"},{"en":"exchange rate","ru":"обменный курс"},{"en":"fixed rate","ru":"фиксированный курс"},{"en":"floating rate","ru":"плавающий курс"},{"en":"appreciation","ru":"укрепление валюты"},{"en":"depreciation","ru":"ослабление валюты"},{"en":"devaluation","ru":"девальвация"},{"en":"revaluation","ru":"ревальвация"},{"en":"forex","ru":"валютный рынок"},{"en":"spot rate","ru":"спот-курс"},{"en":"forward rate","ru":"форвардный курс"},{"en":"cross rate","ru":"кросс-курс"},{"en":"reserve currency","ru":"резервная валюта"},{"en":"monetary union","ru":"валютный союз"},{"en":"purchasing power","ru":"покупательная способность"},{"en":"inflation","ru":"инфляция"},{"en":"hyperinflation","ru":"гиперинфляция"},{"en":"USD","ru":"доллар США"},{"en":"EUR","ru":"евро"},{"en":"GBP","ru":"фунт стерлингов"}]'::jsonb),
  (c,m1,'Interest Rates',5,5,'vocabulary',true,true,'[{"en":"interest rate","ru":"процентная ставка"},{"en":"base rate","ru":"базовая ставка"},{"en":"yield","ru":"доходность"},{"en":"coupon","ru":"купон"},{"en":"fixed rate","ru":"фиксированная ставка"},{"en":"floating rate","ru":"плавающая ставка"},{"en":"LIBOR","ru":"LIBOR"},{"en":"SOFR","ru":"SOFR"},{"en":"spread","ru":"спред"},{"en":"margin","ru":"маржа"},{"en":"risk premium","ru":"премия за риск"},{"en":"term","ru":"срок"},{"en":"maturity","ru":"погашение"},{"en":"yield curve","ru":"кривая доходности"},{"en":"inverted yield","ru":"инвертированная кривая"},{"en":"risk-free rate","ru":"безрисковая ставка"},{"en":"overnight rate","ru":"однодневная ставка"},{"en":"bank rate","ru":"банковская ставка"},{"en":"discount rate","ru":"учётная ставка"},{"en":"central bank rate","ru":"ставка центробанка"}]'::jsonb),
  (c,m1,'Economic Indicators',6,6,'vocabulary',true,true,'[{"en":"GDP","ru":"ВВП"},{"en":"inflation","ru":"инфляция"},{"en":"CPI","ru":"индекс потребительских цен"},{"en":"unemployment rate","ru":"уровень безработицы"},{"en":"trade balance","ru":"торговый баланс"},{"en":"current account","ru":"текущий счёт"},{"en":"fiscal deficit","ru":"бюджетный дефицит"},{"en":"government debt","ru":"государственный долг"},{"en":"consumer confidence","ru":"потребительское доверие"},{"en":"PMI","ru":"индекс деловой активности"},{"en":"industrial output","ru":"промышленное производство"},{"en":"retail sales","ru":"розничные продажи"},{"en":"housing starts","ru":"строительство жилья"},{"en":"leading indicator","ru":"опережающий индикатор"},{"en":"lagging indicator","ru":"запаздывающий индикатор"},{"en":"forecast","ru":"прогноз"},{"en":"revision","ru":"пересмотр"},{"en":"interpretation","ru":"интерпретация"},{"en":"RPI","ru":"индекс розничных цен"},{"en":"coincident","ru":"совпадающий индикатор"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Account Types',1,7,'vocabulary',true,true,'[{"en":"current account","ru":"расчётный счёт"},{"en":"savings account","ru":"сберегательный счёт"},{"en":"fixed deposit","ru":"срочный вклад"},{"en":"notice account","ru":"счёт с уведомлением"},{"en":"business account","ru":"бизнес-счёт"},{"en":"joint account","ru":"совместный счёт"},{"en":"interest","ru":"проценты"},{"en":"terms","ru":"условия"},{"en":"charges","ru":"комиссии"},{"en":"minimum balance","ru":"минимальный остаток"},{"en":"overdraft","ru":"овердрафт"},{"en":"online banking","ru":"интернет-банкинг"},{"en":"mobile app","ru":"мобильное приложение"},{"en":"customer","ru":"клиент"},{"en":"KYC","ru":"знай своего клиента"},{"en":"opening","ru":"открытие счёта"},{"en":"premium account","ru":"премиальный счёт"},{"en":"features","ru":"функции"},{"en":"conditions","ru":"условия"},{"en":"ISA","ru":"ИСА (счёт сбережений)"}]'::jsonb),
  (c,m2,'Loans & Deposits',2,8,'vocabulary',true,true,'[{"en":"loan","ru":"кредит / заём"},{"en":"mortgage","ru":"ипотека"},{"en":"personal loan","ru":"потребительский кредит"},{"en":"car loan","ru":"автокредит"},{"en":"overdraft","ru":"овердрафт"},{"en":"deposit","ru":"депозит"},{"en":"savings","ru":"сбережения"},{"en":"interest rate","ru":"процентная ставка"},{"en":"APR","ru":"годовая процентная ставка"},{"en":"term","ru":"срок"},{"en":"repayment","ru":"погашение"},{"en":"principal","ru":"основная сумма долга"},{"en":"amortisation","ru":"амортизация кредита"},{"en":"secured","ru":"обеспеченный"},{"en":"unsecured","ru":"необеспеченный"},{"en":"collateral","ru":"залог"},{"en":"guarantor","ru":"поручитель"},{"en":"credit check","ru":"проверка кредитной истории"},{"en":"default","ru":"дефолт"},{"en":"arrears","ru":"задолженность"}]'::jsonb),
  (c,m2,'Credit',3,9,'vocabulary',true,true,'[{"en":"credit","ru":"кредит"},{"en":"credit score","ru":"кредитный рейтинг"},{"en":"credit history","ru":"кредитная история"},{"en":"credit limit","ru":"кредитный лимит"},{"en":"credit card","ru":"кредитная карта"},{"en":"revolving credit","ru":"возобновляемый кредит"},{"en":"utilisation","ru":"использование лимита"},{"en":"repayment","ru":"погашение"},{"en":"minimum payment","ru":"минимальный платёж"},{"en":"interest","ru":"проценты"},{"en":"annual fee","ru":"годовая комиссия"},{"en":"credit bureau","ru":"кредитное бюро"},{"en":"credit rating","ru":"кредитный рейтинг"},{"en":"delinquency","ru":"просрочка"},{"en":"default","ru":"дефолт"},{"en":"charge-off","ru":"списание долга"},{"en":"recovery","ru":"взыскание долга"},{"en":"credit risk","ru":"кредитный риск"},{"en":"underwriting","ru":"андеррайтинг"},{"en":"facility","ru":"кредитная линия"}]'::jsonb),
  (c,m2,'Payments',4,10,'vocabulary',true,true,'[{"en":"payment","ru":"платёж"},{"en":"bank transfer","ru":"банковский перевод"},{"en":"BACS","ru":"BACS"},{"en":"CHAPS","ru":"CHAPS"},{"en":"SWIFT","ru":"SWIFT"},{"en":"SEPA","ru":"SEPA"},{"en":"direct debit","ru":"прямой дебет"},{"en":"standing order","ru":"постоянное поручение"},{"en":"cheque","ru":"чек"},{"en":"card payment","ru":"оплата картой"},{"en":"contactless","ru":"бесконтактный платёж"},{"en":"mobile payment","ru":"мобильный платёж"},{"en":"instant payment","ru":"мгновенный платёж"},{"en":"Faster Payments","ru":"быстрые платежи"},{"en":"settlement","ru":"расчёт"},{"en":"clearing","ru":"клиринг"},{"en":"correspondent bank","ru":"банк-корреспондент"},{"en":"intermediary","ru":"посредник"},{"en":"remittance","ru":"денежный перевод"},{"en":"FX payment","ru":"валютный платёж"}]'::jsonb),
  (c,m2,'SWIFT',5,11,'vocabulary',true,true,'[{"en":"SWIFT","ru":"SWIFT"},{"en":"BIC code","ru":"BIC-код"},{"en":"IBAN","ru":"IBAN"},{"en":"correspondent bank","ru":"банк-корреспондент"},{"en":"nostro account","ru":"ностро-счёт"},{"en":"vostro account","ru":"востро-счёт"},{"en":"MT103","ru":"MT103"},{"en":"MT202","ru":"MT202"},{"en":"message","ru":"сообщение"},{"en":"instruction","ru":"инструкция"},{"en":"confirmation","ru":"подтверждение"},{"en":"intermediary","ru":"посредник"},{"en":"charge option","ru":"вариант комиссии"},{"en":"OUR","ru":"OUR"},{"en":"SHA","ru":"SHA"},{"en":"BEN","ru":"BEN"},{"en":"value date","ru":"дата валютирования"},{"en":"reference","ru":"ссылка"},{"en":"currency","ru":"валюта"},{"en":"amount","ru":"сумма"}]'::jsonb),
  (c,m2,'Retail Banking',6,12,'vocabulary',true,true,'[{"en":"branch","ru":"отделение банка"},{"en":"ATM","ru":"банкомат"},{"en":"online banking","ru":"интернет-банкинг"},{"en":"mobile banking","ru":"мобильный банкинг"},{"en":"teller","ru":"кассир"},{"en":"customer service","ru":"обслуживание клиентов"},{"en":"deposit","ru":"вклад"},{"en":"withdrawal","ru":"снятие наличных"},{"en":"transfer","ru":"перевод"},{"en":"balance","ru":"остаток"},{"en":"statement","ru":"выписка"},{"en":"standing order","ru":"постоянное поручение"},{"en":"direct debit","ru":"прямой дебет"},{"en":"card","ru":"банковская карта"},{"en":"PIN","ru":"PIN-код"},{"en":"security","ru":"безопасность"},{"en":"KYC","ru":"знай своего клиента"},{"en":"complaint","ru":"жалоба"},{"en":"product","ru":"банковский продукт"},{"en":"cheque","ru":"чек"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Stocks',1,13,'vocabulary',true,true,'[{"en":"stock","ru":"акция"},{"en":"share","ru":"доля / акция"},{"en":"equity","ru":"акционерный капитал"},{"en":"listed company","ru":"публичная компания"},{"en":"stock exchange","ru":"фондовая биржа"},{"en":"market price","ru":"рыночная цена"},{"en":"dividend","ru":"дивиденд"},{"en":"earnings","ru":"прибыль"},{"en":"P/E ratio","ru":"коэффициент P/E"},{"en":"market capitalisation","ru":"рыночная капитализация"},{"en":"IPO","ru":"IPO"},{"en":"secondary offering","ru":"вторичное размещение"},{"en":"buyback","ru":"обратный выкуп"},{"en":"ordinary share","ru":"обыкновенная акция"},{"en":"preference share","ru":"привилегированная акция"},{"en":"rights issue","ru":"выпуск прав"},{"en":"blue chip","ru":"голубая фишка"},{"en":"growth stock","ru":"акция роста"},{"en":"value stock","ru":"стоимостная акция"},{"en":"portfolio","ru":"портфель"}]'::jsonb),
  (c,m3,'Bonds',2,14,'vocabulary',true,true,'[{"en":"bond","ru":"облигация"},{"en":"fixed income","ru":"фиксированный доход"},{"en":"coupon","ru":"купон"},{"en":"maturity","ru":"срок погашения"},{"en":"face value","ru":"номинальная стоимость"},{"en":"yield","ru":"доходность"},{"en":"yield to maturity","ru":"доходность к погашению"},{"en":"credit rating","ru":"кредитный рейтинг"},{"en":"investment grade","ru":"инвестиционный рейтинг"},{"en":"high yield","ru":"высокодоходный"},{"en":"government bond","ru":"государственная облигация"},{"en":"corporate bond","ru":"корпоративная облигация"},{"en":"duration","ru":"дюрация"},{"en":"convexity","ru":"выпуклость"},{"en":"discount","ru":"дисконт"},{"en":"premium","ru":"премия"},{"en":"zero coupon","ru":"бескупонная облигация"},{"en":"callable","ru":"отзывная облигация"},{"en":"floating rate note","ru":"облигация с плавающей ставкой"},{"en":"price","ru":"цена"}]'::jsonb),
  (c,m3,'Funds',3,15,'vocabulary',true,true,'[{"en":"mutual fund","ru":"паевой инвестиционный фонд"},{"en":"unit trust","ru":"паевой траст"},{"en":"ETF","ru":"ETF"},{"en":"index fund","ru":"индексный фонд"},{"en":"active fund","ru":"активно управляемый фонд"},{"en":"passive fund","ru":"пассивный фонд"},{"en":"NAV","ru":"стоимость чистых активов"},{"en":"total expense ratio","ru":"общий коэффициент расходов"},{"en":"manager","ru":"управляющий"},{"en":"strategy","ru":"стратегия"},{"en":"benchmark","ru":"эталон"},{"en":"diversification","ru":"диверсификация"},{"en":"liquidity","ru":"ликвидность"},{"en":"redemption","ru":"погашение паёв"},{"en":"subscription","ru":"подписка на паи"},{"en":"accumulation","ru":"накопление"},{"en":"income","ru":"доходный"},{"en":"distributor","ru":"дистрибьютор"},{"en":"OEIC","ru":"OEIC"},{"en":"class","ru":"класс акций"}]'::jsonb),
  (c,m3,'Risk & Return',4,16,'vocabulary',true,true,'[{"en":"risk","ru":"риск"},{"en":"return","ru":"доходность"},{"en":"volatility","ru":"волатильность"},{"en":"standard deviation","ru":"стандартное отклонение"},{"en":"beta","ru":"бета"},{"en":"alpha","ru":"альфа"},{"en":"Sharpe ratio","ru":"коэффициент Шарпа"},{"en":"risk-adjusted return","ru":"доходность с поправкой на риск"},{"en":"diversification","ru":"диверсификация"},{"en":"correlation","ru":"корреляция"},{"en":"systematic risk","ru":"систематический риск"},{"en":"unsystematic risk","ru":"несистематический риск"},{"en":"risk tolerance","ru":"толерантность к риску"},{"en":"risk appetite","ru":"аппетит к риску"},{"en":"expected return","ru":"ожидаемая доходность"},{"en":"downside risk","ru":"риск снижения"},{"en":"risk-free rate","ru":"безрисковая ставка"},{"en":"risk premium","ru":"премия за риск"},{"en":"upside","ru":"потенциал роста"},{"en":"portfolio","ru":"портфель"}]'::jsonb),
  (c,m3,'Portfolio',5,17,'vocabulary',true,true,'[{"en":"portfolio","ru":"портфель"},{"en":"diversification","ru":"диверсификация"},{"en":"asset allocation","ru":"распределение активов"},{"en":"equity allocation","ru":"доля акций"},{"en":"bond allocation","ru":"доля облигаций"},{"en":"rebalancing","ru":"ребалансировка"},{"en":"strategic allocation","ru":"стратегическое распределение"},{"en":"tactical allocation","ru":"тактическое распределение"},{"en":"benchmark","ru":"эталон"},{"en":"tracking error","ru":"ошибка отслеживания"},{"en":"active return","ru":"активная доходность"},{"en":"passive","ru":"пассивный"},{"en":"weights","ru":"веса активов"},{"en":"objective","ru":"инвестиционная цель"},{"en":"horizon","ru":"инвестиционный горизонт"},{"en":"review","ru":"обзор"},{"en":"risk","ru":"риск"},{"en":"return","ru":"доходность"},{"en":"alternative","ru":"альтернативные активы"},{"en":"cash","ru":"денежные средства"}]'::jsonb),
  (c,m3,'Stock Exchange',6,18,'vocabulary',true,true,'[{"en":"stock exchange","ru":"фондовая биржа"},{"en":"listing","ru":"листинг"},{"en":"trading","ru":"торги"},{"en":"market maker","ru":"маркет-мейкер"},{"en":"broker","ru":"брокер"},{"en":"settlement","ru":"расчёт"},{"en":"clearing house","ru":"клиринговая палата"},{"en":"margin","ru":"маржа"},{"en":"short selling","ru":"короткая продажа"},{"en":"bid","ru":"цена покупки"},{"en":"offer","ru":"цена продажи"},{"en":"spread","ru":"спред"},{"en":"volume","ru":"объём торгов"},{"en":"market order","ru":"рыночная заявка"},{"en":"limit order","ru":"лимитная заявка"},{"en":"stop loss","ru":"стоп-лосс"},{"en":"index","ru":"индекс"},{"en":"circuit breaker","ru":"автоматическая остановка торгов"},{"en":"T+2","ru":"дата расчётов T+2"},{"en":"long","ru":"длинная позиция"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Bank Statements',1,19,'vocabulary',true,true,'[{"en":"bank statement","ru":"банковская выписка"},{"en":"opening balance","ru":"начальный остаток"},{"en":"closing balance","ru":"конечный остаток"},{"en":"debit","ru":"дебет"},{"en":"credit","ru":"кредит"},{"en":"transaction","ru":"операция"},{"en":"date","ru":"дата"},{"en":"description","ru":"описание"},{"en":"reference","ru":"ссылка"},{"en":"charges","ru":"комиссии"},{"en":"interest","ru":"проценты"},{"en":"reconcile","ru":"сверять"},{"en":"period","ru":"период"},{"en":"format","ru":"формат"},{"en":"import","ru":"импортировать"},{"en":"download","ru":"загружать"},{"en":"statement period","ru":"период выписки"},{"en":"online statement","ru":"онлайн-выписка"},{"en":"paper statement","ru":"бумажная выписка"},{"en":"e-statement","ru":"электронная выписка"}]'::jsonb),
  (c,m4,'Loan Agreements',2,20,'vocabulary',true,true,'[{"en":"loan agreement","ru":"кредитный договор"},{"en":"principal","ru":"основная сумма"},{"en":"interest rate","ru":"процентная ставка"},{"en":"repayment schedule","ru":"график погашения"},{"en":"term","ru":"срок"},{"en":"collateral","ru":"залог"},{"en":"covenant","ru":"ковенант"},{"en":"event of default","ru":"случай дефолта"},{"en":"prepayment","ru":"досрочное погашение"},{"en":"facility","ru":"кредитная линия"},{"en":"drawdown","ru":"выборка средств"},{"en":"availability period","ru":"период выборки"},{"en":"commitment fee","ru":"комиссия за обязательство"},{"en":"margin","ru":"маржа"},{"en":"benchmark rate","ru":"базовая ставка"},{"en":"penalty","ru":"штраф"},{"en":"waiver","ru":"отказ от права"},{"en":"amendment","ru":"поправка"},{"en":"governing law","ru":"применимое право"},{"en":"security","ru":"обеспечение"}]'::jsonb),
  (c,m4,'Investment Reports',3,21,'vocabulary',true,true,'[{"en":"investment report","ru":"инвестиционный отчёт"},{"en":"performance","ru":"эффективность"},{"en":"benchmark","ru":"эталон"},{"en":"portfolio","ru":"портфель"},{"en":"attribution","ru":"атрибуция доходности"},{"en":"sector","ru":"сектор"},{"en":"geography","ru":"география"},{"en":"top holdings","ru":"основные позиции"},{"en":"risk","ru":"риск"},{"en":"NAV","ru":"СЧА"},{"en":"return","ru":"доходность"},{"en":"period","ru":"период"},{"en":"since inception","ru":"с момента создания"},{"en":"volatility","ru":"волатильность"},{"en":"Sharpe ratio","ru":"коэффициент Шарпа"},{"en":"manager commentary","ru":"комментарий управляющего"},{"en":"outlook","ru":"прогноз"},{"en":"comparison","ru":"сравнение"},{"en":"chart","ru":"диаграмма"},{"en":"table","ru":"таблица"}]'::jsonb),
  (c,m4,'Prospectus',4,22,'vocabulary',true,true,'[{"en":"prospectus","ru":"проспект эмиссии"},{"en":"offer","ru":"предложение"},{"en":"securities","ru":"ценные бумаги"},{"en":"issuer","ru":"эмитент"},{"en":"risks","ru":"риски"},{"en":"use of proceeds","ru":"использование средств"},{"en":"management","ru":"руководство"},{"en":"corporate governance","ru":"корпоративное управление"},{"en":"underwriter","ru":"андеррайтер"},{"en":"listing authority","ru":"листинговый орган"},{"en":"subscription","ru":"подписка"},{"en":"timetable","ru":"расписание"},{"en":"pricing","ru":"ценообразование"},{"en":"allocation","ru":"распределение"},{"en":"admission","ru":"допуск к торгам"},{"en":"trading","ru":"торги"},{"en":"legal","ru":"юридический"},{"en":"audited","ru":"проверенный аудитором"},{"en":"forecast","ru":"прогноз"},{"en":"financial information","ru":"финансовая информация"}]'::jsonb),
  (c,m4,'Term Sheets',5,23,'vocabulary',true,true,'[{"en":"term sheet","ru":"термшит"},{"en":"indicative terms","ru":"ориентировочные условия"},{"en":"amount","ru":"сумма"},{"en":"currency","ru":"валюта"},{"en":"tenor","ru":"срок"},{"en":"interest rate","ru":"процентная ставка"},{"en":"collateral","ru":"залог"},{"en":"conditions precedent","ru":"предварительные условия"},{"en":"covenants","ru":"ковенанты"},{"en":"representations","ru":"заверения"},{"en":"drawdown","ru":"выборка"},{"en":"repayment","ru":"погашение"},{"en":"fees","ru":"комиссии"},{"en":"governing law","ru":"применимое право"},{"en":"exclusivity","ru":"эксклюзивность"},{"en":"binding","ru":"обязывающий"},{"en":"non-binding","ru":"необязывающий"},{"en":"negotiation","ru":"переговоры"},{"en":"approval","ru":"согласование"},{"en":"credit committee","ru":"кредитный комитет"}]'::jsonb),
  (c,m4,'Correspondence',6,24,'vocabulary',true,true,'[{"en":"covering letter","ru":"сопроводительное письмо"},{"en":"transmittal","ru":"письмо о передаче"},{"en":"email","ru":"электронное письмо"},{"en":"formal","ru":"официальный"},{"en":"professional","ru":"профессиональный"},{"en":"reference","ru":"ссылка"},{"en":"subject","ru":"тема"},{"en":"salutation","ru":"обращение"},{"en":"purpose","ru":"цель"},{"en":"content","ru":"содержание"},{"en":"action required","ru":"требуемые действия"},{"en":"attachment","ru":"вложение"},{"en":"timeline","ru":"сроки"},{"en":"contact","ru":"контакт"},{"en":"follow-up","ru":"дальнейшие шаги"},{"en":"acknowledgement","ru":"подтверждение"},{"en":"compliance","ru":"соответствие"},{"en":"confidential","ru":"конфиденциальный"},{"en":"distribution","ru":"рассылка"},{"en":"sign-off","ru":"подпись"}]'::jsonb);

  RAISE NOTICE 'Finance Industry B1: 4 modules, 24 lessons inserted';
END $fin_b1$;
