-- ================================================================
-- HOSPITALITY A2  (ee93b087-d1fe-4b85-838f-1cf7269877f1)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $hosp_a2$ DECLARE
  c UUID := 'ee93b087-d1fe-4b85-838f-1cf7269877f1';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Front Office',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Guest Communication',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Food & Beverage',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Housekeeping',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Check-in & Check-out',1,1,'vocabulary',true,true,'[{"en":"check-in","ru":"заселение"},{"en":"check-out","ru":"выезд"},{"en":"guest","ru":"гость"},{"en":"room number","ru":"номер комнаты"},{"en":"passport","ru":"паспорт"},{"en":"reservation","ru":"бронирование"},{"en":"confirmation","ru":"подтверждение"},{"en":"key card","ru":"карточка-ключ"},{"en":"deposit","ru":"залог"},{"en":"bill","ru":"счёт"},{"en":"folio","ru":"расчётный лист"},{"en":"departure date","ru":"дата выезда"},{"en":"arrival date","ru":"дата заезда"},{"en":"late check-out","ru":"поздний выезд"},{"en":"early check-in","ru":"ранний заезд"},{"en":"luggage","ru":"багаж"},{"en":"porter","ru":"носильщик"},{"en":"reception","ru":"ресепшн"},{"en":"lobby","ru":"лобби"},{"en":"desk","ru":"стойка регистрации"}]'::jsonb),
  (c,m1,'Reservations',2,2,'vocabulary',true,true,'[{"en":"reservation","ru":"бронирование"},{"en":"booking","ru":"бронь"},{"en":"availability","ru":"доступность"},{"en":"room type","ru":"тип номера"},{"en":"arrival","ru":"заезд"},{"en":"departure","ru":"выезд"},{"en":"nights","ru":"количество ночей"},{"en":"rate","ru":"тариф"},{"en":"special request","ru":"особая просьба"},{"en":"confirmation number","ru":"номер подтверждения"},{"en":"cancellation","ru":"отмена"},{"en":"modification","ru":"изменение"},{"en":"guarantee","ru":"гарантия"},{"en":"credit card","ru":"кредитная карта"},{"en":"no-show","ru":"неявка"},{"en":"waitlist","ru":"лист ожидания"},{"en":"overbooking","ru":"овербукинг"},{"en":"block booking","ru":"групповое бронирование"},{"en":"corporate rate","ru":"корпоративный тариф"},{"en":"direct booking","ru":"прямое бронирование"}]'::jsonb),
  (c,m1,'Room Types',3,3,'vocabulary',true,true,'[{"en":"single room","ru":"одноместный номер"},{"en":"double room","ru":"двухместный номер"},{"en":"twin room","ru":"номер с раздельными кроватями"},{"en":"suite","ru":"люкс"},{"en":"junior suite","ru":"джуниор-сюит"},{"en":"standard room","ru":"стандартный номер"},{"en":"deluxe room","ru":"номер делюкс"},{"en":"superior","ru":"номер superior"},{"en":"connecting rooms","ru":"смежные номера"},{"en":"accessible room","ru":"номер для маломобильных"},{"en":"non-smoking","ru":"номер для некурящих"},{"en":"sea view","ru":"вид на море"},{"en":"city view","ru":"вид на город"},{"en":"garden view","ru":"вид на сад"},{"en":"king bed","ru":"кровать king size"},{"en":"queen bed","ru":"кровать queen size"},{"en":"occupancy","ru":"заполняемость"},{"en":"amenities","ru":"удобства"},{"en":"bed type","ru":"тип кровати"},{"en":"smoking","ru":"номер для курящих"}]'::jsonb),
  (c,m1,'Guest Requests',4,4,'vocabulary',true,true,'[{"en":"request","ru":"просьба"},{"en":"maintenance","ru":"техническое обслуживание"},{"en":"extra pillow","ru":"дополнительная подушка"},{"en":"extra towel","ru":"дополнительное полотенце"},{"en":"room service","ru":"обслуживание в номере"},{"en":"wake-up call","ru":"звонок-будильник"},{"en":"ironing board","ru":"гладильная доска"},{"en":"hairdryer","ru":"фен"},{"en":"adapter","ru":"адаптер"},{"en":"rollaway bed","ru":"раскладная кровать"},{"en":"cot","ru":"детская кроватка"},{"en":"newspaper","ru":"газета"},{"en":"minibar","ru":"мини-бар"},{"en":"ice","ru":"лёд"},{"en":"quiet room","ru":"тихий номер"},{"en":"high floor","ru":"высокий этаж"},{"en":"allergy","ru":"аллергия"},{"en":"special occasion","ru":"особый повод"},{"en":"early morning","ru":"ранний утренний сервис"},{"en":"late departure","ru":"поздний выезд"}]'::jsonb),
  (c,m1,'Key Systems',5,5,'vocabulary',true,true,'[{"en":"key card","ru":"карточка-ключ"},{"en":"electronic lock","ru":"электронный замок"},{"en":"magnetic stripe","ru":"магнитная полоса"},{"en":"master key","ru":"мастер-ключ"},{"en":"emergency key","ru":"аварийный ключ"},{"en":"lost key","ru":"потерянный ключ"},{"en":"key programming","ru":"программирование ключа"},{"en":"replacement","ru":"замена"},{"en":"security","ru":"безопасность"},{"en":"swipe","ru":"провести картой"},{"en":"access level","ru":"уровень доступа"},{"en":"door lock","ru":"дверной замок"},{"en":"in-room safe","ru":"сейф в номере"},{"en":"deactivate","ru":"деактивировать"},{"en":"issue","ru":"выдавать"},{"en":"reception","ru":"ресепшн"},{"en":"PIN","ru":"PIN-код"},{"en":"function","ru":"функция"},{"en":"card reader","ru":"считыватель карт"},{"en":"contactless","ru":"бесконтактный"}]'::jsonb),
  (c,m1,'Lobby Services',6,6,'vocabulary',true,true,'[{"en":"concierge","ru":"консьерж"},{"en":"bellboy","ru":"носильщик"},{"en":"doorman","ru":"швейцар"},{"en":"luggage storage","ru":"хранение багажа"},{"en":"taxi","ru":"такси"},{"en":"transport","ru":"транспорт"},{"en":"information","ru":"информация"},{"en":"directions","ru":"направление / указания"},{"en":"map","ru":"карта"},{"en":"recommendation","ru":"рекомендация"},{"en":"booking","ru":"бронирование"},{"en":"message","ru":"сообщение"},{"en":"parcel","ru":"посылка"},{"en":"courier","ru":"курьер"},{"en":"valet","ru":"парковщик"},{"en":"car park","ru":"парковка"},{"en":"umbrella","ru":"зонт"},{"en":"printing","ru":"печать документов"},{"en":"fax","ru":"факс"},{"en":"lobby","ru":"лобби"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Greetings',1,7,'vocabulary',true,true,'[{"en":"greeting","ru":"приветствие"},{"en":"welcome","ru":"добро пожаловать"},{"en":"Good morning","ru":"Доброе утро"},{"en":"Good afternoon","ru":"Добрый день"},{"en":"Good evening","ru":"Добрый вечер"},{"en":"Sir","ru":"сэр"},{"en":"Madam","ru":"мадам"},{"en":"name","ru":"имя"},{"en":"smile","ru":"улыбка"},{"en":"eye contact","ru":"зрительный контакт"},{"en":"body language","ru":"язык тела"},{"en":"helpful","ru":"готовый помочь"},{"en":"polite","ru":"вежливый"},{"en":"professional","ru":"профессиональный"},{"en":"first impression","ru":"первое впечатление"},{"en":"positive","ru":"позитивный"},{"en":"friendly","ru":"дружелюбный"},{"en":"formal","ru":"официальный"},{"en":"informal","ru":"неформальный"},{"en":"salutation","ru":"обращение"}]'::jsonb),
  (c,m2,'Phone Calls',2,8,'vocabulary',true,true,'[{"en":"answer","ru":"отвечать"},{"en":"hold","ru":"удержание вызова"},{"en":"transfer","ru":"переадресовать"},{"en":"message","ru":"сообщение"},{"en":"take a message","ru":"принять сообщение"},{"en":"call back","ru":"перезвонить"},{"en":"extension","ru":"добавочный номер"},{"en":"enquiry","ru":"запрос"},{"en":"booking","ru":"бронирование"},{"en":"information","ru":"информация"},{"en":"confirm","ru":"подтверждать"},{"en":"note","ru":"записать"},{"en":"name","ru":"имя"},{"en":"number","ru":"номер"},{"en":"spelling","ru":"произношение по буквам"},{"en":"slow down","ru":"говорить медленнее"},{"en":"repeat","ru":"повторить"},{"en":"understand","ru":"понять"},{"en":"end call","ru":"завершить звонок"},{"en":"greeting","ru":"приветствие"}]'::jsonb),
  (c,m2,'Complaints',3,9,'vocabulary',true,true,'[{"en":"complaint","ru":"жалоба"},{"en":"problem","ru":"проблема"},{"en":"issue","ru":"вопрос / неполадка"},{"en":"apology","ru":"извинение"},{"en":"sorry","ru":"извините"},{"en":"sincere","ru":"искренний"},{"en":"listen","ru":"слушать"},{"en":"understand","ru":"понять"},{"en":"resolve","ru":"решить"},{"en":"solution","ru":"решение"},{"en":"offer","ru":"предложить"},{"en":"compensate","ru":"компенсировать"},{"en":"follow up","ru":"проследить"},{"en":"escalate","ru":"передать выше"},{"en":"manager","ru":"менеджер"},{"en":"note","ru":"записать"},{"en":"action","ru":"действие"},{"en":"prevent","ru":"предотвратить"},{"en":"feedback","ru":"обратная связь"},{"en":"satisfaction","ru":"удовлетворённость"}]'::jsonb),
  (c,m2,'Requests',4,10,'vocabulary',true,true,'[{"en":"request","ru":"просьба"},{"en":"assist","ru":"помочь"},{"en":"certainly","ru":"конечно"},{"en":"of course","ru":"разумеется"},{"en":"right away","ru":"немедленно"},{"en":"arrange","ru":"организовать"},{"en":"organise","ru":"устроить"},{"en":"confirm","ru":"подтвердить"},{"en":"how can I help","ru":"чем могу помочь"},{"en":"unfortunately","ru":"к сожалению"},{"en":"alternative","ru":"альтернатива"},{"en":"available","ru":"доступно"},{"en":"unavailable","ru":"недоступно"},{"en":"timing","ru":"время / сроки"},{"en":"delivery","ru":"доставка"},{"en":"service","ru":"обслуживание"},{"en":"note","ru":"записать"},{"en":"priority","ru":"приоритет"},{"en":"personalise","ru":"персонализировать"},{"en":"helpful","ru":"готовый помочь"}]'::jsonb),
  (c,m2,'Emails to Guests',5,11,'vocabulary',true,true,'[{"en":"email","ru":"электронное письмо"},{"en":"subject","ru":"тема"},{"en":"greeting","ru":"обращение"},{"en":"body","ru":"основная часть"},{"en":"closing","ru":"заключительная фраза"},{"en":"formal","ru":"официальный"},{"en":"clear","ru":"понятный"},{"en":"polite","ru":"вежливый"},{"en":"confirm","ru":"подтверждать"},{"en":"attachment","ru":"вложение"},{"en":"reservation","ru":"бронирование"},{"en":"details","ru":"детали"},{"en":"information","ru":"информация"},{"en":"correction","ru":"исправление"},{"en":"response time","ru":"время ответа"},{"en":"template","ru":"шаблон"},{"en":"professional","ru":"профессиональный"},{"en":"tone","ru":"тон"},{"en":"accurate","ru":"точный"},{"en":"sign-off","ru":"подпись"}]'::jsonb),
  (c,m2,'Cultural Awareness',6,12,'vocabulary',true,true,'[{"en":"culture","ru":"культура"},{"en":"custom","ru":"обычай"},{"en":"religion","ru":"религия"},{"en":"dietary","ru":"диетические требования"},{"en":"halal","ru":"халяль"},{"en":"kosher","ru":"кошерный"},{"en":"vegetarian","ru":"вегетарианец"},{"en":"vegan","ru":"веган"},{"en":"greeting style","ru":"стиль приветствия"},{"en":"eye contact","ru":"зрительный контакт"},{"en":"language","ru":"язык"},{"en":"preference","ru":"предпочтение"},{"en":"prayer","ru":"молитва"},{"en":"tipping","ru":"чаевые"},{"en":"etiquette","ru":"этикет"},{"en":"respect","ru":"уважение"},{"en":"sensitivity","ru":"тактичность"},{"en":"training","ru":"обучение"},{"en":"awareness","ru":"осведомлённость"},{"en":"diversity","ru":"разнообразие"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Menu Reading',1,13,'vocabulary',true,true,'[{"en":"menu","ru":"меню"},{"en":"starter","ru":"закуска"},{"en":"main course","ru":"основное блюдо"},{"en":"dessert","ru":"десерт"},{"en":"side dish","ru":"гарнир"},{"en":"dish of the day","ru":"блюдо дня"},{"en":"set menu","ru":"комплексное меню"},{"en":"à la carte","ru":"à la carte"},{"en":"vegetarian","ru":"вегетарианское"},{"en":"vegan","ru":"веганское"},{"en":"gluten-free","ru":"без глютена"},{"en":"allergen","ru":"аллерген"},{"en":"seasonal","ru":"сезонный"},{"en":"daily special","ru":"блюдо дня"},{"en":"price","ru":"цена"},{"en":"description","ru":"описание"},{"en":"portion","ru":"порция"},{"en":"ingredient","ru":"ингредиент"},{"en":"accompaniment","ru":"гарнир"},{"en":"recommendation","ru":"рекомендация"}]'::jsonb),
  (c,m3,'Taking Orders',2,14,'vocabulary',true,true,'[{"en":"order","ru":"заказ"},{"en":"take an order","ru":"принять заказ"},{"en":"notepad","ru":"блокнот"},{"en":"confirm","ru":"подтвердить"},{"en":"write down","ru":"записать"},{"en":"repeat back","ru":"повторить заказ"},{"en":"kitchen","ru":"кухня"},{"en":"time","ru":"время приготовления"},{"en":"ready","ru":"готово"},{"en":"course","ru":"блюдо"},{"en":"beverage","ru":"напиток"},{"en":"preference","ru":"предпочтение"},{"en":"well done","ru":"хорошо прожаренный"},{"en":"medium","ru":"средней прожарки"},{"en":"rare","ru":"с кровью"},{"en":"allergy","ru":"аллергия"},{"en":"substitution","ru":"замена"},{"en":"extra","ru":"дополнительно"},{"en":"void","ru":"аннулировать"},{"en":"modifier","ru":"модификатор"}]'::jsonb),
  (c,m3,'Service Styles',3,15,'vocabulary',true,true,'[{"en":"table service","ru":"обслуживание за столом"},{"en":"silver service","ru":"серебряный сервис"},{"en":"buffet","ru":"буфет / шведский стол"},{"en":"counter service","ru":"обслуживание у стойки"},{"en":"room service","ru":"обслуживание в номере"},{"en":"self-service","ru":"самообслуживание"},{"en":"plated service","ru":"сервировка на тарелке"},{"en":"family style","ru":"семейный стиль подачи"},{"en":"tray service","ru":"подача на подносе"},{"en":"banquet service","ru":"банкетное обслуживание"},{"en":"clearance","ru":"уборка посуды"},{"en":"timing","ru":"синхронизация подачи"},{"en":"sequence","ru":"последовательность"},{"en":"presentation","ru":"подача блюда"},{"en":"posture","ru":"осанка"},{"en":"technique","ru":"техника"},{"en":"right side","ru":"правая сторона"},{"en":"cloth","ru":"салфетка"},{"en":"polish","ru":"полировать"},{"en":"set up","ru":"сервировка"}]'::jsonb),
  (c,m3,'Dietary Requirements',4,16,'vocabulary',true,true,'[{"en":"allergy","ru":"аллергия"},{"en":"intolerance","ru":"непереносимость"},{"en":"dairy-free","ru":"без молочных продуктов"},{"en":"gluten-free","ru":"без глютена"},{"en":"nut-free","ru":"без орехов"},{"en":"halal","ru":"халяль"},{"en":"kosher","ru":"кошерный"},{"en":"vegan","ru":"веган"},{"en":"vegetarian","ru":"вегетарианец"},{"en":"coeliac","ru":"целиакия"},{"en":"anaphylaxis","ru":"анафилаксия"},{"en":"cross-contamination","ru":"перекрёстное загрязнение"},{"en":"ingredient","ru":"ингредиент"},{"en":"label","ru":"этикетка"},{"en":"inform kitchen","ru":"сообщить на кухню"},{"en":"alternative","ru":"альтернатива"},{"en":"adapt","ru":"адаптировать блюдо"},{"en":"confirm","ru":"подтвердить"},{"en":"document","ru":"документировать"},{"en":"safety","ru":"безопасность"}]'::jsonb),
  (c,m3,'Kitchen Terms',5,17,'vocabulary',true,true,'[{"en":"chef","ru":"шеф-повар"},{"en":"sous chef","ru":"су-шеф"},{"en":"kitchen brigade","ru":"кухонная бригада"},{"en":"prep","ru":"подготовка"},{"en":"mise en place","ru":"mise en place"},{"en":"cover","ru":"персона / прибор"},{"en":"ticket","ru":"чек заказа"},{"en":"expedite","ru":"контролировать выдачу"},{"en":"fire","ru":"начать готовить"},{"en":"pick up","ru":"забрать блюдо"},{"en":"table number","ru":"номер стола"},{"en":"dietary flag","ru":"пометка о диете"},{"en":"allergen flag","ru":"пометка об аллергене"},{"en":"portion","ru":"порция"},{"en":"plate","ru":"тарелка / сервировать"},{"en":"garnish","ru":"гарнир / украшение"},{"en":"sauce","ru":"соус"},{"en":"temperature","ru":"температура"},{"en":"hygiene","ru":"гигиена"},{"en":"pass","ru":"окно выдачи"}]'::jsonb),
  (c,m3,'Billing',6,18,'vocabulary',true,true,'[{"en":"bill","ru":"счёт"},{"en":"check","ru":"счёт (амер.)"},{"en":"receipt","ru":"квитанция"},{"en":"total","ru":"итого"},{"en":"subtotal","ru":"промежуточная сумма"},{"en":"service charge","ru":"сервисный сбор"},{"en":"cover charge","ru":"плата за столик"},{"en":"VAT","ru":"НДС"},{"en":"split bill","ru":"разделить счёт"},{"en":"cash","ru":"наличные"},{"en":"card","ru":"карта"},{"en":"contactless","ru":"бесконтактный"},{"en":"tip","ru":"чаевые"},{"en":"gratuity","ru":"чаевые / чаевые"},{"en":"void","ru":"аннулировать"},{"en":"discount","ru":"скидка"},{"en":"complimentary","ru":"за счёт заведения"},{"en":"authorise","ru":"авторизовать"},{"en":"settle","ru":"оплатить"},{"en":"separate","ru":"отдельный счёт"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Room Cleaning',1,19,'vocabulary',true,true,'[{"en":"housekeeping","ru":"хозяйственная служба"},{"en":"housekeeping trolley","ru":"тележка горничной"},{"en":"bed making","ru":"заправка кровати"},{"en":"change linen","ru":"смена постельного белья"},{"en":"dusting","ru":"вытирание пыли"},{"en":"vacuum","ru":"пылесосить"},{"en":"mop","ru":"мыть полы"},{"en":"bathroom","ru":"ванная комната"},{"en":"sanitise","ru":"дезинфицировать"},{"en":"replenish","ru":"пополнять"},{"en":"towel","ru":"полотенце"},{"en":"toiletries","ru":"туалетные принадлежности"},{"en":"bin","ru":"мусорная корзина"},{"en":"DND","ru":"не беспокоить"},{"en":"make up room","ru":"убрать номер"},{"en":"departure clean","ru":"уборка после выезда"},{"en":"deep clean","ru":"генеральная уборка"},{"en":"inspection","ru":"проверка"},{"en":"rubbish","ru":"мусор"},{"en":"clean","ru":"убирать"}]'::jsonb),
  (c,m4,'Laundry',2,20,'vocabulary',true,true,'[{"en":"laundry","ru":"прачечная / бельё"},{"en":"linen","ru":"постельное бельё"},{"en":"sheet","ru":"простыня"},{"en":"pillowcase","ru":"наволочка"},{"en":"duvet","ru":"одеяло"},{"en":"towel","ru":"полотенце"},{"en":"wash","ru":"стирать"},{"en":"dry","ru":"сушить"},{"en":"iron","ru":"гладить"},{"en":"fold","ru":"складывать"},{"en":"sort","ru":"сортировать"},{"en":"label","ru":"ярлык"},{"en":"lost","ru":"утерянный"},{"en":"damaged","ru":"повреждённый"},{"en":"guest laundry","ru":"стирка для гостей"},{"en":"dry cleaning","ru":"химчистка"},{"en":"pressing","ru":"глажка"},{"en":"collection","ru":"сбор белья"},{"en":"delivery","ru":"доставка"},{"en":"charge","ru":"стоимость услуги"}]'::jsonb),
  (c,m4,'Amenities',3,21,'vocabulary',true,true,'[{"en":"amenity","ru":"удобство"},{"en":"toiletry","ru":"туалетные принадлежности"},{"en":"shampoo","ru":"шампунь"},{"en":"conditioner","ru":"кондиционер для волос"},{"en":"body wash","ru":"гель для душа"},{"en":"lotion","ru":"лосьон"},{"en":"soap","ru":"мыло"},{"en":"shower cap","ru":"шапочка для душа"},{"en":"comb","ru":"расчёска"},{"en":"sewing kit","ru":"швейный набор"},{"en":"toothbrush","ru":"зубная щётка"},{"en":"toothpaste","ru":"зубная паста"},{"en":"slippers","ru":"тапочки"},{"en":"bathrobe","ru":"халат"},{"en":"stationery","ru":"канцелярские принадлежности"},{"en":"pen","ru":"ручка"},{"en":"notepad","ru":"блокнот"},{"en":"directory","ru":"справочник"},{"en":"minibar","ru":"мини-бар"},{"en":"cotton buds","ru":"ватные палочки"}]'::jsonb),
  (c,m4,'Maintenance Requests',4,22,'vocabulary',true,true,'[{"en":"maintenance","ru":"техническое обслуживание"},{"en":"fault","ru":"неисправность"},{"en":"repair","ru":"ремонт"},{"en":"report","ru":"сообщать"},{"en":"log","ru":"журнал"},{"en":"request","ru":"заявка"},{"en":"urgent","ru":"срочный"},{"en":"routine","ru":"плановый"},{"en":"engineer","ru":"инженер"},{"en":"plumber","ru":"сантехник"},{"en":"electrician","ru":"электрик"},{"en":"HVAC","ru":"система вентиляции и кондиционирования"},{"en":"light bulb","ru":"лампочка"},{"en":"tap","ru":"кран"},{"en":"drain","ru":"сток"},{"en":"lock","ru":"замок"},{"en":"safe","ru":"сейф"},{"en":"TV","ru":"телевизор"},{"en":"telephone","ru":"телефон"},{"en":"air conditioning","ru":"кондиционер"}]'::jsonb),
  (c,m4,'Safety Standards',5,23,'vocabulary',true,true,'[{"en":"safety","ru":"безопасность"},{"en":"fire exit","ru":"пожарный выход"},{"en":"fire extinguisher","ru":"огнетушитель"},{"en":"evacuation","ru":"эвакуация"},{"en":"hazard","ru":"опасность"},{"en":"COSHH","ru":"работа с вредными веществами"},{"en":"chemical","ru":"химическое вещество"},{"en":"PPE","ru":"средства защиты"},{"en":"gloves","ru":"перчатки"},{"en":"mask","ru":"маска"},{"en":"apron","ru":"фартук"},{"en":"slip","ru":"скольжение"},{"en":"trip","ru":"спотыкание"},{"en":"first aid","ru":"первая помощь"},{"en":"manual handling","ru":"ручное перемещение"},{"en":"body fluids","ru":"биологические жидкости"},{"en":"sharps","ru":"острые предметы"},{"en":"accident","ru":"несчастный случай"},{"en":"report","ru":"сообщать / акт"},{"en":"prevent","ru":"предотвращать"}]'::jsonb),
  (c,m4,'Lost & Found',6,24,'vocabulary',true,true,'[{"en":"lost and found","ru":"бюро находок"},{"en":"item","ru":"предмет"},{"en":"found","ru":"найденный"},{"en":"log","ru":"журнал находок"},{"en":"description","ru":"описание"},{"en":"date","ru":"дата"},{"en":"room","ru":"номер комнаты"},{"en":"storage","ru":"хранение"},{"en":"claim","ru":"требование о возврате"},{"en":"owner","ru":"владелец"},{"en":"identity","ru":"удостоверение личности"},{"en":"return","ru":"возвращать"},{"en":"three months","ru":"три месяца (срок хранения)"},{"en":"donation","ru":"пожертвование"},{"en":"high value","ru":"ценный предмет"},{"en":"jewellery","ru":"ювелирные украшения"},{"en":"passport","ru":"паспорт"},{"en":"cash","ru":"наличные"},{"en":"document","ru":"документ"},{"en":"handover","ru":"передача"}]'::jsonb);

  RAISE NOTICE 'Hospitality A2: 4 modules, 24 lessons inserted';
END $hosp_a2$;
