-- ================================================================
-- LAW B1  (2c78884e-4b41-4dcd-b153-4b696bf89621)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $law_b1$ DECLARE
  c UUID := '2c78884e-4b41-4dcd-b153-4b696bf89621';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Legal System Basics',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Contract Law',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Criminal Law',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Legal Documents',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Courts & Jurisdiction',1,1,'vocabulary',true,true,'[{"en":"court","ru":"суд"},{"en":"jurisdiction","ru":"юрисдикция"},{"en":"magistrates court","ru":"мировой суд"},{"en":"crown court","ru":"суд короны"},{"en":"county court","ru":"окружной суд"},{"en":"high court","ru":"высокий суд"},{"en":"court of appeal","ru":"апелляционный суд"},{"en":"supreme court","ru":"верховный суд"},{"en":"tribunal","ru":"трибунал"},{"en":"judge","ru":"судья"},{"en":"magistrate","ru":"мировой судья"},{"en":"claimant","ru":"истец"},{"en":"defendant","ru":"ответчик"},{"en":"civil","ru":"гражданский"},{"en":"criminal","ru":"уголовный"},{"en":"appeal","ru":"апелляция"},{"en":"hierarchy","ru":"иерархия судов"},{"en":"precedent","ru":"прецедент"},{"en":"case","ru":"дело"},{"en":"venue","ru":"место рассмотрения"}]'::jsonb),
  (c,m1,'Types of Law',2,2,'vocabulary',true,true,'[{"en":"civil law","ru":"гражданское право"},{"en":"criminal law","ru":"уголовное право"},{"en":"common law","ru":"общее право"},{"en":"statute","ru":"закон / статут"},{"en":"equity","ru":"справедливость / право справедливости"},{"en":"contract law","ru":"договорное право"},{"en":"tort","ru":"деликт"},{"en":"property law","ru":"имущественное право"},{"en":"family law","ru":"семейное право"},{"en":"company law","ru":"корпоративное право"},{"en":"employment law","ru":"трудовое право"},{"en":"administrative law","ru":"административное право"},{"en":"constitutional law","ru":"конституционное право"},{"en":"international law","ru":"международное право"},{"en":"public law","ru":"публичное право"},{"en":"private law","ru":"частное право"},{"en":"legislation","ru":"законодательство"},{"en":"codification","ru":"кодификация"},{"en":"substantive law","ru":"материальное право"},{"en":"procedural law","ru":"процессуальное право"}]'::jsonb),
  (c,m1,'Legal Persons',3,3,'vocabulary',true,true,'[{"en":"legal person","ru":"юридическое лицо"},{"en":"natural person","ru":"физическое лицо"},{"en":"company","ru":"компания"},{"en":"corporation","ru":"корпорация"},{"en":"partnership","ru":"товарищество"},{"en":"sole trader","ru":"индивидуальный предприниматель"},{"en":"LLP","ru":"ООО с ограниченной ответственностью"},{"en":"capacity","ru":"дееспособность"},{"en":"incorporation","ru":"регистрация компании"},{"en":"registration","ru":"регистрация"},{"en":"director","ru":"директор"},{"en":"shareholder","ru":"акционер"},{"en":"officer","ru":"должностное лицо"},{"en":"liability","ru":"ответственность"},{"en":"limited liability","ru":"ограниченная ответственность"},{"en":"legal entity","ru":"юридическое лицо"},{"en":"agent","ru":"агент"},{"en":"principal","ru":"принципал"},{"en":"representative","ru":"представитель"},{"en":"unincorporated association","ru":"незарегистрированное объединение"}]'::jsonb),
  (c,m1,'Rights & Duties',4,4,'vocabulary',true,true,'[{"en":"right","ru":"право"},{"en":"duty","ru":"обязанность"},{"en":"obligation","ru":"обязательство"},{"en":"burden","ru":"бремя"},{"en":"entitlement","ru":"право / правомочие"},{"en":"statutory right","ru":"законное право"},{"en":"human right","ru":"право человека"},{"en":"fundamental right","ru":"основное право"},{"en":"property right","ru":"право собственности"},{"en":"liability","ru":"ответственность"},{"en":"tort","ru":"деликт"},{"en":"breach","ru":"нарушение"},{"en":"remedy","ru":"средство защиты"},{"en":"enforcement","ru":"принуждение к исполнению"},{"en":"court order","ru":"судебный приказ"},{"en":"damages","ru":"убытки"},{"en":"injunction","ru":"запрет / судебный запрет"},{"en":"specific performance","ru":"исполнение в натуре"},{"en":"waiver","ru":"отказ от права"},{"en":"discharge","ru":"освобождение от обязательства"}]'::jsonb),
  (c,m1,'Sources of Law',5,5,'vocabulary',true,true,'[{"en":"legislation","ru":"законодательство"},{"en":"statute","ru":"закон"},{"en":"Act of Parliament","ru":"Акт Парламента"},{"en":"regulation","ru":"регламент"},{"en":"statutory instrument","ru":"нормативный правовой акт"},{"en":"case law","ru":"прецедентное право"},{"en":"precedent","ru":"прецедент"},{"en":"common law","ru":"общее право"},{"en":"treaty","ru":"договор / соглашение"},{"en":"constitution","ru":"конституция"},{"en":"codification","ru":"кодификация"},{"en":"delegated legislation","ru":"делегированное законодательство"},{"en":"primary legislation","ru":"первичное законодательство"},{"en":"secondary legislation","ru":"вторичное законодательство"},{"en":"interpretation","ru":"толкование"},{"en":"judicial review","ru":"судебный контроль"},{"en":"jurisprudence","ru":"юриспруденция"},{"en":"human rights","ru":"права человека"},{"en":"international law","ru":"международное право"},{"en":"European Convention","ru":"Европейская конвенция"}]'::jsonb),
  (c,m1,'Legal Procedure',6,6,'vocabulary',true,true,'[{"en":"legal procedure","ru":"судебная процедура"},{"en":"claim","ru":"иск"},{"en":"plead","ru":"заявлять"},{"en":"serve","ru":"вручать"},{"en":"file","ru":"подавать"},{"en":"disclose","ru":"раскрывать"},{"en":"evidence","ru":"доказательства"},{"en":"hearing","ru":"слушание"},{"en":"trial","ru":"судебное разбирательство"},{"en":"judgment","ru":"судебное решение"},{"en":"enforcement","ru":"исполнение"},{"en":"appeal","ru":"апелляция"},{"en":"time limit","ru":"процессуальный срок"},{"en":"procedural rule","ru":"процессуальная норма"},{"en":"Civil Procedure Rules","ru":"ГПК"},{"en":"pre-action protocol","ru":"досудебный протокол"},{"en":"mediation","ru":"медиация"},{"en":"settlement","ru":"мировое соглашение"},{"en":"costs","ru":"судебные расходы"},{"en":"litigation","ru":"судебный процесс"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Offer & Acceptance',1,7,'vocabulary',true,true,'[{"en":"offer","ru":"оферта"},{"en":"acceptance","ru":"акцепт"},{"en":"counter-offer","ru":"встречная оферта"},{"en":"invitation to treat","ru":"приглашение делать оферту"},{"en":"communication","ru":"сообщение"},{"en":"revocation","ru":"отзыв оферты"},{"en":"lapse","ru":"истечение срока"},{"en":"postal rule","ru":"правило почты"},{"en":"instantaneous","ru":"мгновенный"},{"en":"effective","ru":"действительный"},{"en":"mirror image","ru":"зеркальное соответствие"},{"en":"conditional","ru":"условный"},{"en":"silence","ru":"молчание"},{"en":"conduct","ru":"поведение"},{"en":"electronic","ru":"электронный"},{"en":"formation","ru":"заключение договора"},{"en":"binding","ru":"обязывающий"},{"en":"terms","ru":"условия"},{"en":"negotiation","ru":"переговоры"},{"en":"agreement","ru":"соглашение"}]'::jsonb),
  (c,m2,'Consideration',2,8,'vocabulary',true,true,'[{"en":"consideration","ru":"встречное удовлетворение"},{"en":"sufficient","ru":"достаточный"},{"en":"adequate","ru":"адекватный"},{"en":"past consideration","ru":"прошлое встречное удовлетворение"},{"en":"existing duty","ru":"существующая обязанность"},{"en":"economic value","ru":"экономическая ценность"},{"en":"benefit","ru":"выгода"},{"en":"detriment","ru":"ущерб"},{"en":"forbearance","ru":"воздержание"},{"en":"promissory estoppel","ru":"запрет на отказ от обещания"},{"en":"intention","ru":"намерение"},{"en":"execute","ru":"исполнять"},{"en":"executed","ru":"исполненный"},{"en":"executory","ru":"подлежащий исполнению"},{"en":"valuable","ru":"ценный"},{"en":"nominal","ru":"номинальный"},{"en":"promisee","ru":"получатель обещания"},{"en":"third party","ru":"третье лицо"},{"en":"reform","ru":"реформа"},{"en":"adequacy","ru":"адекватность"}]'::jsonb),
  (c,m2,'Terms',3,9,'vocabulary',true,true,'[{"en":"term","ru":"условие договора"},{"en":"condition","ru":"существенное условие"},{"en":"warranty","ru":"гарантия"},{"en":"innominate term","ru":"безымянное условие"},{"en":"express term","ru":"явное условие"},{"en":"implied term","ru":"подразумеваемое условие"},{"en":"exemption clause","ru":"оговорка об освобождении"},{"en":"exclusion clause","ru":"оговорка об исключении"},{"en":"limitation clause","ru":"оговорка об ограничении"},{"en":"unfair term","ru":"несправедливое условие"},{"en":"consumer","ru":"потребитель"},{"en":"UCTA","ru":"Закон о несправедливых условиях"},{"en":"incorporated","ru":"включённый"},{"en":"notice","ru":"уведомление"},{"en":"course of dealing","ru":"устойчивая практика"},{"en":"statute","ru":"закон"},{"en":"entire agreement","ru":"полнота соглашения"},{"en":"collateral","ru":"дополнительный"},{"en":"representation","ru":"заявление"},{"en":"CRA","ru":"Закон о правах потребителей"}]'::jsonb),
  (c,m2,'Breach',4,10,'vocabulary',true,true,'[{"en":"breach","ru":"нарушение договора"},{"en":"material breach","ru":"существенное нарушение"},{"en":"repudiatory breach","ru":"отказ от договора"},{"en":"anticipatory breach","ru":"предвидимое нарушение"},{"en":"partial breach","ru":"частичное нарушение"},{"en":"fundamental breach","ru":"фундаментальное нарушение"},{"en":"termination right","ru":"право на расторжение"},{"en":"rescission","ru":"расторжение"},{"en":"keep alive","ru":"сохранить договор"},{"en":"damages","ru":"убытки"},{"en":"mitigation","ru":"снижение ущерба"},{"en":"causation","ru":"причинно-следственная связь"},{"en":"remoteness","ru":"отдалённость ущерба"},{"en":"measure","ru":"мера ущерба"},{"en":"expectation","ru":"ожидаемая выгода"},{"en":"reliance","ru":"понесённые расходы"},{"en":"restitution","ru":"реституция"},{"en":"quantum","ru":"размер"},{"en":"loss","ru":"убыток"},{"en":"condition broken","ru":"нарушение существенного условия"}]'::jsonb),
  (c,m2,'Remedies',5,11,'vocabulary',true,true,'[{"en":"damages","ru":"убытки"},{"en":"specific performance","ru":"исполнение в натуре"},{"en":"injunction","ru":"судебный запрет"},{"en":"rescission","ru":"расторжение"},{"en":"rectification","ru":"исправление"},{"en":"account of profits","ru":"взыскание прибыли"},{"en":"restitution","ru":"реституция"},{"en":"expectation loss","ru":"убытки ожидания"},{"en":"reliance loss","ru":"убытки полагания"},{"en":"consequential loss","ru":"косвенные убытки"},{"en":"direct loss","ru":"прямые убытки"},{"en":"mitigation","ru":"снижение убытков"},{"en":"causation","ru":"причинно-следственная связь"},{"en":"remoteness","ru":"отдалённость"},{"en":"penalty clause","ru":"штрафная оговорка"},{"en":"liquidated damages","ru":"заранее оценённые убытки"},{"en":"unliquidated","ru":"незаранее оценённые"},{"en":"nominal damages","ru":"номинальные убытки"},{"en":"substantial","ru":"существенный"},{"en":"equitable","ru":"справедливый"}]'::jsonb),
  (c,m2,'Void Contracts',6,12,'vocabulary',true,true,'[{"en":"void","ru":"ничтожный"},{"en":"voidable","ru":"оспоримый"},{"en":"unenforceable","ru":"неисполнимый"},{"en":"illegal","ru":"незаконный"},{"en":"mistake","ru":"ошибка"},{"en":"misrepresentation","ru":"ложное заявление"},{"en":"duress","ru":"принуждение"},{"en":"undue influence","ru":"ненадлежащее влияние"},{"en":"incapacity","ru":"недееспособность"},{"en":"frustration","ru":"тщетность договора"},{"en":"restraint of trade","ru":"ограничение торговли"},{"en":"public policy","ru":"публичный порядок"},{"en":"void ab initio","ru":"ничтожный с момента заключения"},{"en":"effect","ru":"последствие"},{"en":"third party","ru":"третье лицо"},{"en":"restitution","ru":"реституция"},{"en":"unjust enrichment","ru":"неосновательное обогащение"},{"en":"rescind","ru":"расторгать"},{"en":"affirmation","ru":"подтверждение договора"},{"en":"bar","ru":"препятствие"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Offences & Elements',1,13,'vocabulary',true,true,'[{"en":"actus reus","ru":"actus reus (деяние)"},{"en":"mens rea","ru":"mens rea (умысел)"},{"en":"strict liability","ru":"строгая ответственность"},{"en":"intention","ru":"умысел"},{"en":"recklessness","ru":"неосторожность"},{"en":"negligence","ru":"халатность"},{"en":"motive","ru":"мотив"},{"en":"result crime","ru":"преступление результата"},{"en":"conduct crime","ru":"преступление деяния"},{"en":"omission","ru":"бездействие"},{"en":"causation","ru":"причинность"},{"en":"chain of causation","ru":"цепочка причинности"},{"en":"novus actus","ru":"новое действие прерывает цепь"},{"en":"burden of proof","ru":"бремя доказывания"},{"en":"standard of proof","ru":"стандарт доказывания"},{"en":"beyond reasonable doubt","ru":"вне разумных сомнений"},{"en":"element","ru":"элемент состава преступления"},{"en":"define","ru":"определять"},{"en":"classify","ru":"классифицировать"},{"en":"state of affairs","ru":"состояние вещей"}]'::jsonb),
  (c,m3,'Evidence',2,14,'vocabulary',true,true,'[{"en":"evidence","ru":"доказательство"},{"en":"admissible","ru":"допустимый"},{"en":"inadmissible","ru":"недопустимый"},{"en":"hearsay","ru":"слухи / показания с чужих слов"},{"en":"direct evidence","ru":"прямые доказательства"},{"en":"circumstantial","ru":"косвенные доказательства"},{"en":"documentary","ru":"документальные доказательства"},{"en":"real evidence","ru":"вещественные доказательства"},{"en":"oral evidence","ru":"устные показания"},{"en":"witness","ru":"свидетель"},{"en":"competent","ru":"правомочный"},{"en":"compellable","ru":"подлежащий вызову"},{"en":"corroboration","ru":"подкрепление"},{"en":"burden","ru":"бремя"},{"en":"standard","ru":"стандарт"},{"en":"inference","ru":"умозаключение"},{"en":"presumption","ru":"презумпция"},{"en":"opinion","ru":"мнение"},{"en":"expert","ru":"эксперт"},{"en":"confession","ru":"признание"}]'::jsonb),
  (c,m3,'Arrest & Detention',3,15,'vocabulary',true,true,'[{"en":"arrest","ru":"арест"},{"en":"warrant","ru":"ордер"},{"en":"without warrant","ru":"без ордера"},{"en":"reasonable grounds","ru":"разумные основания"},{"en":"caution","ru":"предупреждение о правах"},{"en":"right to silence","ru":"право хранить молчание"},{"en":"custody","ru":"содержание под стражей"},{"en":"detention","ru":"задержание"},{"en":"PACE","ru":"PACE"},{"en":"legal advice","ru":"юридическая консультация"},{"en":"solicitor","ru":"солиситор"},{"en":"appropriate adult","ru":"надлежащий взрослый"},{"en":"interview","ru":"допрос"},{"en":"record","ru":"запись"},{"en":"bail","ru":"залог / освобождение под залог"},{"en":"charge","ru":"обвинение"},{"en":"release","ru":"освобождение"},{"en":"time limit","ru":"предельный срок"},{"en":"custody sergeant","ru":"дежурный офицер"},{"en":"cell","ru":"камера"}]'::jsonb),
  (c,m3,'Trial Process',4,16,'vocabulary',true,true,'[{"en":"indictment","ru":"обвинительное заключение"},{"en":"charge","ru":"обвинение"},{"en":"plead","ru":"заявлять"},{"en":"guilty","ru":"виновен"},{"en":"not guilty","ru":"не виновен"},{"en":"jury","ru":"присяжные"},{"en":"judge","ru":"судья"},{"en":"prosecution","ru":"обвинение"},{"en":"defence","ru":"защита"},{"en":"opening","ru":"вступительное слово"},{"en":"evidence","ru":"доказательства"},{"en":"examination","ru":"допрос"},{"en":"cross-examination","ru":"перекрёстный допрос"},{"en":"closing","ru":"заключительное слово"},{"en":"summing up","ru":"напутствие судьи присяжным"},{"en":"verdict","ru":"вердикт"},{"en":"acquit","ru":"оправдать"},{"en":"convict","ru":"признать виновным"},{"en":"directed acquittal","ru":"указанное оправдание"},{"en":"appeal","ru":"апелляция"}]'::jsonb),
  (c,m3,'Sentencing',5,17,'vocabulary',true,true,'[{"en":"sentence","ru":"приговор"},{"en":"custodial sentence","ru":"лишение свободы"},{"en":"community order","ru":"общественные работы"},{"en":"fine","ru":"штраф"},{"en":"suspended sentence","ru":"условный срок"},{"en":"conditional discharge","ru":"условное освобождение"},{"en":"absolute discharge","ru":"безусловное освобождение"},{"en":"compensation","ru":"компенсация"},{"en":"aggravating factor","ru":"отягчающее обстоятельство"},{"en":"mitigating factor","ru":"смягчающее обстоятельство"},{"en":"guilty plea","ru":"признание вины"},{"en":"rehabilitation","ru":"реабилитация"},{"en":"deterrence","ru":"сдерживание"},{"en":"protection","ru":"защита общества"},{"en":"retribution","ru":"возмездие"},{"en":"guidelines","ru":"руководство по назначению наказания"},{"en":"concurrent","ru":"совокупный (одновременный)"},{"en":"consecutive","ru":"последовательный"},{"en":"pre-sentence report","ru":"досудебный доклад"},{"en":"magistrates","ru":"мировые судьи"}]'::jsonb),
  (c,m3,'Appeals',6,18,'vocabulary',true,true,'[{"en":"appeal","ru":"апелляция"},{"en":"Court of Appeal","ru":"Апелляционный суд"},{"en":"ground of appeal","ru":"основание апелляции"},{"en":"unsafe conviction","ru":"ненадёжный обвинительный приговор"},{"en":"fresh evidence","ru":"новые доказательства"},{"en":"error of law","ru":"ошибка в праве"},{"en":"misdirection","ru":"ненадлежащее направление"},{"en":"leave to appeal","ru":"разрешение на апелляцию"},{"en":"prosecution appeal","ru":"апелляция обвинения"},{"en":"reference","ru":"ходатайство"},{"en":"Attorney General","ru":"генеральный прокурор"},{"en":"unduly lenient","ru":"неоправданно мягкий"},{"en":"outcome","ru":"результат"},{"en":"quash","ru":"отменить"},{"en":"substitute","ru":"заменить"},{"en":"retrial","ru":"повторное судебное разбирательство"},{"en":"Supreme Court","ru":"Верховный суд"},{"en":"CCRC","ru":"CCRC"},{"en":"miscarriage of justice","ru":"судебная ошибка"},{"en":"lurking doubt","ru":"скрытые сомнения"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Contracts',1,19,'vocabulary',true,true,'[{"en":"contract","ru":"договор"},{"en":"parties","ru":"стороны"},{"en":"recitals","ru":"вводная часть"},{"en":"definitions","ru":"определения"},{"en":"terms","ru":"условия"},{"en":"conditions","ru":"условия"},{"en":"obligations","ru":"обязательства"},{"en":"payment","ru":"оплата"},{"en":"duration","ru":"срок действия"},{"en":"termination","ru":"расторжение"},{"en":"warranty","ru":"гарантия"},{"en":"indemnity","ru":"возмещение"},{"en":"limitation","ru":"ограничение ответственности"},{"en":"governing law","ru":"применимое право"},{"en":"jurisdiction","ru":"юрисдикция"},{"en":"dispute resolution","ru":"урегулирование споров"},{"en":"notice","ru":"уведомление"},{"en":"amendment","ru":"поправка"},{"en":"entire agreement","ru":"полнота соглашения"},{"en":"counterparts","ru":"экземпляры"}]'::jsonb),
  (c,m4,'Agreements',2,20,'vocabulary',true,true,'[{"en":"agreement","ru":"соглашение"},{"en":"MOU","ru":"меморандум о взаимопонимании"},{"en":"heads of terms","ru":"основные условия"},{"en":"letter of intent","ru":"письмо о намерениях"},{"en":"NDA","ru":"соглашение о неразглашении"},{"en":"confidentiality agreement","ru":"соглашение о конфиденциальности"},{"en":"shareholder agreement","ru":"акционерное соглашение"},{"en":"partnership agreement","ru":"договор товарищества"},{"en":"licence","ru":"лицензия"},{"en":"deed","ru":"акт / документ с печатью"},{"en":"assignment","ru":"уступка"},{"en":"novation","ru":"новация"},{"en":"settlement agreement","ru":"мировое соглашение"},{"en":"consent","ru":"согласие"},{"en":"schedule","ru":"приложение"},{"en":"annexure","ru":"приложение"},{"en":"execution","ru":"подписание"},{"en":"signature","ru":"подпись"},{"en":"witness","ru":"свидетель"},{"en":"framework agreement","ru":"рамочное соглашение"}]'::jsonb),
  (c,m4,'Affidavits',3,21,'vocabulary',true,true,'[{"en":"affidavit","ru":"аффидавит / письменные показания под присягой"},{"en":"sworn statement","ru":"показание под присягой"},{"en":"deponent","ru":"дающий показания"},{"en":"oath","ru":"присяга"},{"en":"affirmation","ru":"торжественное заявление"},{"en":"court","ru":"суд"},{"en":"exhibit","ru":"приложение / вещественное доказательство"},{"en":"paragraph","ru":"абзац"},{"en":"facts","ru":"факты"},{"en":"truthful","ru":"правдивый"},{"en":"signature","ru":"подпись"},{"en":"commissioner","ru":"комиссар по присягам"},{"en":"notary","ru":"нотариус"},{"en":"format","ru":"форма"},{"en":"jurat","ru":"удостоверение присяги"},{"en":"perjury","ru":"лжесвидетельство"},{"en":"purpose","ru":"цель"},{"en":"evidence","ru":"доказательства"},{"en":"file","ru":"подавать"},{"en":"serve","ru":"вручать"}]'::jsonb),
  (c,m4,'Statements',4,22,'vocabulary',true,true,'[{"en":"witness statement","ru":"показание свидетеля"},{"en":"factual","ru":"фактический"},{"en":"chronological","ru":"хронологический"},{"en":"exhibit","ru":"приложение"},{"en":"reference","ru":"ссылка"},{"en":"truth","ru":"правда"},{"en":"statement of truth","ru":"заявление о правдивости"},{"en":"heading","ru":"заголовок"},{"en":"parties","ru":"стороны"},{"en":"date","ru":"дата"},{"en":"sign","ru":"подписывать"},{"en":"support claim","ru":"подкреплять иск"},{"en":"defence","ru":"защита"},{"en":"serve","ru":"вручать"},{"en":"disclose","ru":"раскрывать"},{"en":"exchange","ru":"обмениваться"},{"en":"witness summons","ru":"судебная повестка"},{"en":"compellable","ru":"подлежащий вызову"},{"en":"expert statement","ru":"заключение эксперта"},{"en":"summary","ru":"резюме"}]'::jsonb),
  (c,m4,'Correspondence',5,23,'vocabulary',true,true,'[{"en":"legal letter","ru":"юридическое письмо"},{"en":"without prejudice","ru":"без ущерба для прав"},{"en":"open correspondence","ru":"открытая переписка"},{"en":"subject to contract","ru":"при условии подписания договора"},{"en":"headed paper","ru":"фирменный бланк"},{"en":"reference","ru":"ссылка"},{"en":"date","ru":"дата"},{"en":"addressee","ru":"адресат"},{"en":"purpose","ru":"цель"},{"en":"content","ru":"содержание"},{"en":"demand","ru":"требование"},{"en":"claim","ru":"претензия"},{"en":"response","ru":"ответ"},{"en":"deadline","ru":"срок"},{"en":"action","ru":"действие"},{"en":"consequence","ru":"последствие"},{"en":"enclosure","ru":"вложение"},{"en":"service","ru":"вручение"},{"en":"duly authorised","ru":"надлежащим образом уполномоченный"},{"en":"sign","ru":"подписывать"}]'::jsonb),
  (c,m4,'Court Forms',6,24,'vocabulary',true,true,'[{"en":"claim form","ru":"исковое заявление"},{"en":"defence form","ru":"форма ответа на иск"},{"en":"acknowledgement","ru":"уведомление о получении"},{"en":"directions questionnaire","ru":"анкета по процессуальным вопросам"},{"en":"allocation","ru":"распределение по трекам"},{"en":"Part 36 offer","ru":"предложение по Правилу 36"},{"en":"consent order","ru":"приказ по соглашению"},{"en":"order","ru":"приказ / постановление"},{"en":"judgment","ru":"судебное решение"},{"en":"application notice","ru":"заявление"},{"en":"witness list","ru":"список свидетелей"},{"en":"bundle","ru":"судебное дело"},{"en":"index","ru":"оглавление"},{"en":"tab","ru":"закладка"},{"en":"pagination","ru":"нумерация страниц"},{"en":"skeleton argument","ru":"тезисы аргументации"},{"en":"chronology","ru":"хронология"},{"en":"authorities","ru":"судебные прецеденты"},{"en":"submissions","ru":"доводы сторон"},{"en":"draft","ru":"проект документа"}]'::jsonb);

  RAISE NOTICE 'Law B1: 4 modules, 24 lessons inserted';
END $law_b1$;
