-- ================================================================
-- KHAMADI ENGLISH — ESP Vocabulary Seed
-- Run each DO block separately in Supabase SQL Editor if needed
-- ================================================================

-- STEP 0: CLEANUP (run first)
DO $cleanup$ DECLARE ids UUID[] := ARRAY[
  '9d3d5a99-ba18-4136-807c-d1a347d438fa'::UUID,
  'a1000000-0000-0000-0000-000000000007'::UUID,
  'c52350cf-0c6e-4e0d-83da-6e2668b2ba91'::UUID,
  'a1000000-0000-0000-0000-000000000006'::UUID,
  '13f80caf-c0ea-4cae-bb68-225c418d6b7b'::UUID,
  'a1000000-0000-0000-0000-000000000010'::UUID,
  'ee93b087-d1fe-4b85-838f-1cf7269877f1'::UUID,
  'a1000000-0000-0000-0000-000000000008'::UUID,
  '2c78884e-4b41-4dcd-b153-4b696bf89621'::UUID,
  'a1000000-0000-0000-0000-000000000012'::UUID,
  '41f65a3f-2d1e-4281-a249-7d7b5f255352'::UUID,
  'a1000000-0000-0000-0000-000000000009'::UUID,
  '45800af0-cc5a-4787-bf49-a58bcfda9f1a'::UUID,
  'a1000000-0000-0000-0000-000000000011'::UUID
]; BEGIN
  DELETE FROM english_lessons WHERE course_id = ANY(ids);
  DELETE FROM english_modules WHERE course_id = ANY(ids);
  RAISE NOTICE 'Cleanup done';
END $cleanup$;

-- ================================================================
-- COMPUTER SCIENCE B1  (9d3d5a99-ba18-4136-807c-d1a347d438fa)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $cs_b1$ DECLARE
  c  UUID := '9d3d5a99-ba18-4136-807c-d1a347d438fa';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Computer Fundamentals',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Programming Basics',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Web & Internet',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Digital Tools & Office',4,true) RETURNING id INTO m4;

  -- Module 1: Computer Fundamentals
  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Hardware',1,1,'vocabulary',true,true,'[{"en":"processor","ru":"процессор"},{"en":"motherboard","ru":"материнская плата"},{"en":"RAM","ru":"оперативная память"},{"en":"GPU","ru":"видеокарта"},{"en":"SSD","ru":"твердотельный накопитель"},{"en":"HDD","ru":"жёсткий диск"},{"en":"power supply","ru":"блок питания"},{"en":"cooling fan","ru":"вентилятор охлаждения"},{"en":"USB port","ru":"порт USB"},{"en":"circuit board","ru":"печатная плата"},{"en":"bit","ru":"бит"},{"en":"byte","ru":"байт"},{"en":"chip","ru":"микросхема"},{"en":"driver","ru":"драйвер"},{"en":"firmware","ru":"прошивка"},{"en":"cache","ru":"кэш"},{"en":"component","ru":"компонент"},{"en":"peripheral","ru":"периферийное устройство"},{"en":"benchmark","ru":"тест производительности"},{"en":"overclocking","ru":"разгон процессора"}]'::jsonb),
  (c,m1,'Software',2,2,'vocabulary',true,true,'[{"en":"application","ru":"приложение"},{"en":"operating system","ru":"операционная система"},{"en":"install","ru":"устанавливать"},{"en":"update","ru":"обновление"},{"en":"license","ru":"лицензия"},{"en":"open-source","ru":"открытый исходный код"},{"en":"malware","ru":"вредоносное ПО"},{"en":"patch","ru":"патч / исправление"},{"en":"plugin","ru":"плагин"},{"en":"executable","ru":"исполняемый файл"},{"en":"interface","ru":"интерфейс"},{"en":"compatibility","ru":"совместимость"},{"en":"software suite","ru":"пакет программ"},{"en":"subscription","ru":"подписка"},{"en":"trial version","ru":"пробная версия"},{"en":"uninstall","ru":"удалять программу"},{"en":"startup","ru":"автозапуск"},{"en":"background process","ru":"фоновый процесс"},{"en":"system requirements","ru":"системные требования"},{"en":"freeware","ru":"бесплатное ПО"}]'::jsonb),
  (c,m1,'Operating Systems',3,3,'vocabulary',true,true,'[{"en":"boot","ru":"загрузка системы"},{"en":"login","ru":"вход в систему"},{"en":"user account","ru":"учётная запись"},{"en":"desktop","ru":"рабочий стол"},{"en":"file system","ru":"файловая система"},{"en":"kernel","ru":"ядро ОС"},{"en":"process","ru":"процесс"},{"en":"multitasking","ru":"многозадачность"},{"en":"administrator","ru":"администратор"},{"en":"permissions","ru":"права доступа"},{"en":"virtual memory","ru":"виртуальная память"},{"en":"task manager","ru":"диспетчер задач"},{"en":"system crash","ru":"сбой системы"},{"en":"recovery mode","ru":"режим восстановления"},{"en":"shell","ru":"командная оболочка"},{"en":"log file","ru":"журнал событий"},{"en":"shutdown","ru":"завершение работы"},{"en":"registry","ru":"реестр системы"},{"en":"update manager","ru":"менеджер обновлений"},{"en":"network settings","ru":"сетевые настройки"}]'::jsonb),
  (c,m1,'Files & Storage',4,4,'vocabulary',true,true,'[{"en":"folder","ru":"папка"},{"en":"directory","ru":"директория"},{"en":"file path","ru":"путь к файлу"},{"en":"extension","ru":"расширение файла"},{"en":"compression","ru":"сжатие данных"},{"en":"archive","ru":"архив"},{"en":"backup","ru":"резервная копия"},{"en":"USB drive","ru":"флэш-накопитель"},{"en":"cloud storage","ru":"облачное хранилище"},{"en":"synchronisation","ru":"синхронизация"},{"en":"recycle bin","ru":"корзина"},{"en":"metadata","ru":"метаданные"},{"en":"read-only","ru":"только для чтения"},{"en":"encryption","ru":"шифрование"},{"en":"partition","ru":"раздел диска"},{"en":"file size","ru":"размер файла"},{"en":"shortcut","ru":"ярлык"},{"en":"format","ru":"форматирование"},{"en":"permissions","ru":"права доступа к файлу"},{"en":"version history","ru":"история версий"}]'::jsonb),
  (c,m1,'Input & Output',5,5,'vocabulary',true,true,'[{"en":"keyboard","ru":"клавиатура"},{"en":"mouse","ru":"мышь"},{"en":"monitor","ru":"монитор"},{"en":"printer","ru":"принтер"},{"en":"scanner","ru":"сканер"},{"en":"webcam","ru":"веб-камера"},{"en":"microphone","ru":"микрофон"},{"en":"touchscreen","ru":"сенсорный экран"},{"en":"resolution","ru":"разрешение экрана"},{"en":"refresh rate","ru":"частота обновления"},{"en":"input device","ru":"устройство ввода"},{"en":"output device","ru":"устройство вывода"},{"en":"cursor","ru":"курсор"},{"en":"drag and drop","ru":"перетащить и отпустить"},{"en":"connector","ru":"разъём"},{"en":"cable","ru":"кабель"},{"en":"gesture","ru":"жест"},{"en":"display","ru":"дисплей"},{"en":"accessibility","ru":"специальные возможности"},{"en":"HDMI","ru":"порт HDMI"}]'::jsonb),
  (c,m1,'Computer History',6,6,'vocabulary',true,true,'[{"en":"inventor","ru":"изобретатель"},{"en":"mainframe","ru":"мэйнфрейм"},{"en":"transistor","ru":"транзистор"},{"en":"integrated circuit","ru":"интегральная схема"},{"en":"personal computer","ru":"персональный компьютер"},{"en":"vacuum tube","ru":"электронная лампа"},{"en":"generation","ru":"поколение техники"},{"en":"breakthrough","ru":"прорыв"},{"en":"patent","ru":"патент"},{"en":"prototype","ru":"прототип"},{"en":"innovation","ru":"инновация"},{"en":"milestone","ru":"веха / этап"},{"en":"pioneer","ru":"пионер"},{"en":"digital age","ru":"цифровая эпоха"},{"en":"computing power","ru":"вычислительная мощность"},{"en":"legacy system","ru":"устаревшая система"},{"en":"commercialise","ru":"коммерциализировать"},{"en":"manufacture","ru":"производить"},{"en":"revolution","ru":"революция"},{"en":"evolve","ru":"развиваться"}]'::jsonb);

  -- Module 2: Programming Basics
  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Variables & Data Types',1,7,'vocabulary',true,true,'[{"en":"variable","ru":"переменная"},{"en":"integer","ru":"целое число"},{"en":"string","ru":"строка"},{"en":"boolean","ru":"логическое значение"},{"en":"float","ru":"число с плавающей точкой"},{"en":"array","ru":"массив"},{"en":"constant","ru":"константа"},{"en":"null","ru":"нулевое значение"},{"en":"data type","ru":"тип данных"},{"en":"declare","ru":"объявлять"},{"en":"assign","ru":"присваивать"},{"en":"value","ru":"значение"},{"en":"type casting","ru":"преобразование типа"},{"en":"scope","ru":"область видимости"},{"en":"global variable","ru":"глобальная переменная"},{"en":"local variable","ru":"локальная переменная"},{"en":"initialise","ru":"инициализировать"},{"en":"undefined","ru":"неопределённое значение"},{"en":"mutable","ru":"изменяемый"},{"en":"memory address","ru":"адрес памяти"}]'::jsonb),
  (c,m2,'Conditions & Loops',2,8,'vocabulary',true,true,'[{"en":"condition","ru":"условие"},{"en":"if statement","ru":"условный оператор"},{"en":"else","ru":"иначе"},{"en":"loop","ru":"цикл"},{"en":"iteration","ru":"итерация"},{"en":"while loop","ru":"цикл while"},{"en":"for loop","ru":"цикл for"},{"en":"break","ru":"прерывание цикла"},{"en":"continue","ru":"продолжить итерацию"},{"en":"boolean expression","ru":"логическое выражение"},{"en":"comparison operator","ru":"оператор сравнения"},{"en":"logical operator","ru":"логический оператор"},{"en":"nested","ru":"вложенный"},{"en":"infinite loop","ru":"бесконечный цикл"},{"en":"counter","ru":"счётчик"},{"en":"increment","ru":"увеличивать"},{"en":"decrement","ru":"уменьшать"},{"en":"switch statement","ru":"оператор switch"},{"en":"case","ru":"вариант / случай"},{"en":"flowchart","ru":"блок-схема"}]'::jsonb),
  (c,m2,'Functions',3,9,'vocabulary',true,true,'[{"en":"function","ru":"функция"},{"en":"parameter","ru":"параметр"},{"en":"argument","ru":"аргумент"},{"en":"return value","ru":"возвращаемое значение"},{"en":"call","ru":"вызывать"},{"en":"define","ru":"определять"},{"en":"recursion","ru":"рекурсия"},{"en":"built-in function","ru":"встроенная функция"},{"en":"library","ru":"библиотека"},{"en":"method","ru":"метод"},{"en":"syntax","ru":"синтаксис"},{"en":"code block","ru":"блок кода"},{"en":"modular","ru":"модульный"},{"en":"reusable","ru":"многократно используемый"},{"en":"overload","ru":"перегружать"},{"en":"callback","ru":"функция обратного вызова"},{"en":"anonymous function","ru":"анонимная функция"},{"en":"lambda","ru":"лямбда-функция"},{"en":"void","ru":"без возвращаемого значения"},{"en":"scope","ru":"область видимости функции"}]'::jsonb),
  (c,m2,'Debugging',4,10,'vocabulary',true,true,'[{"en":"bug","ru":"ошибка в коде"},{"en":"debug","ru":"отлаживать"},{"en":"debugger","ru":"отладчик"},{"en":"breakpoint","ru":"точка остановки"},{"en":"error message","ru":"сообщение об ошибке"},{"en":"stack trace","ru":"трассировка стека"},{"en":"syntax error","ru":"синтаксическая ошибка"},{"en":"runtime error","ru":"ошибка времени выполнения"},{"en":"logic error","ru":"логическая ошибка"},{"en":"exception","ru":"исключение"},{"en":"try-catch","ru":"блок обработки ошибок"},{"en":"log","ru":"журналировать"},{"en":"console","ru":"консоль"},{"en":"unit test","ru":"модульный тест"},{"en":"fix","ru":"исправление"},{"en":"reproduce","ru":"воспроизводить"},{"en":"isolate","ru":"изолировать"},{"en":"validate","ru":"проверять"},{"en":"refactor","ru":"рефакторинг"},{"en":"regression","ru":"регрессионная ошибка"}]'::jsonb),
  (c,m2,'First Programs',5,11,'vocabulary',true,true,'[{"en":"print","ru":"вывести на экран"},{"en":"input","ru":"ввод данных"},{"en":"output","ru":"вывод данных"},{"en":"compile","ru":"компилировать"},{"en":"run","ru":"запускать"},{"en":"execute","ru":"выполнять"},{"en":"command line","ru":"командная строка"},{"en":"terminal","ru":"терминал"},{"en":"IDE","ru":"интегрированная среда разработки"},{"en":"source code","ru":"исходный код"},{"en":"comment","ru":"комментарий в коде"},{"en":"indentation","ru":"отступ"},{"en":"save","ru":"сохранять"},{"en":"output window","ru":"окно вывода"},{"en":"Hello World","ru":"первая программа"},{"en":"interpreter","ru":"интерпретатор"},{"en":"compiler","ru":"компилятор"},{"en":"editor","ru":"редактор кода"},{"en":"error","ru":"ошибка"},{"en":"success","ru":"успешное выполнение"}]'::jsonb),
  (c,m2,'Code Structure',6,12,'vocabulary',true,true,'[{"en":"class","ru":"класс"},{"en":"object","ru":"объект"},{"en":"module","ru":"модуль"},{"en":"package","ru":"пакет"},{"en":"import","ru":"импорт"},{"en":"export","ru":"экспорт"},{"en":"interface","ru":"интерфейс"},{"en":"inheritance","ru":"наследование"},{"en":"encapsulation","ru":"инкапсуляция"},{"en":"abstraction","ru":"абстракция"},{"en":"polymorphism","ru":"полиморфизм"},{"en":"constructor","ru":"конструктор"},{"en":"instance","ru":"экземпляр"},{"en":"attribute","ru":"атрибут"},{"en":"public","ru":"открытый (публичный)"},{"en":"private","ru":"закрытый (приватный)"},{"en":"static","ru":"статический"},{"en":"design pattern","ru":"паттерн проектирования"},{"en":"namespace","ru":"пространство имён"},{"en":"dependency","ru":"зависимость"}]'::jsonb);

  -- Module 3: Web & Internet
  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'How the Web Works',1,13,'vocabulary',true,true,'[{"en":"server","ru":"сервер"},{"en":"client","ru":"клиент"},{"en":"request","ru":"запрос"},{"en":"response","ru":"ответ"},{"en":"protocol","ru":"протокол"},{"en":"HTTP","ru":"протокол HTTP"},{"en":"HTTPS","ru":"защищённый HTTP"},{"en":"IP address","ru":"IP-адрес"},{"en":"network","ru":"сеть"},{"en":"bandwidth","ru":"пропускная способность"},{"en":"latency","ru":"задержка"},{"en":"packet","ru":"пакет данных"},{"en":"router","ru":"маршрутизатор"},{"en":"hosting","ru":"хостинг"},{"en":"domain","ru":"домен"},{"en":"firewall","ru":"брандмауэр"},{"en":"ISP","ru":"интернет-провайдер"},{"en":"proxy","ru":"прокси-сервер"},{"en":"port","ru":"сетевой порт"},{"en":"load","ru":"нагрузка на сервер"}]'::jsonb),
  (c,m3,'HTML & CSS Basics',2,14,'vocabulary',true,true,'[{"en":"tag","ru":"тег"},{"en":"element","ru":"элемент"},{"en":"attribute","ru":"атрибут HTML"},{"en":"heading","ru":"заголовок"},{"en":"paragraph","ru":"абзац"},{"en":"link","ru":"ссылка"},{"en":"image","ru":"изображение"},{"en":"selector","ru":"CSS-селектор"},{"en":"property","ru":"свойство CSS"},{"en":"class","ru":"класс CSS"},{"en":"margin","ru":"внешний отступ"},{"en":"padding","ru":"внутренний отступ"},{"en":"layout","ru":"макет"},{"en":"responsive","ru":"адаптивный"},{"en":"flexbox","ru":"флексбокс"},{"en":"grid","ru":"CSS-сетка"},{"en":"colour scheme","ru":"цветовая схема"},{"en":"stylesheet","ru":"таблица стилей"},{"en":"semantic","ru":"семантический"},{"en":"inline style","ru":"встроенный стиль"}]'::jsonb),
  (c,m3,'Browsers',3,15,'vocabulary',true,true,'[{"en":"browser","ru":"браузер"},{"en":"URL","ru":"адрес страницы"},{"en":"address bar","ru":"адресная строка"},{"en":"tab","ru":"вкладка"},{"en":"bookmark","ru":"закладка"},{"en":"history","ru":"история посещений"},{"en":"cache","ru":"кэш браузера"},{"en":"cookie","ru":"куки"},{"en":"extension","ru":"расширение браузера"},{"en":"private mode","ru":"приватный режим"},{"en":"developer tools","ru":"инструменты разработчика"},{"en":"rendering","ru":"отображение страницы"},{"en":"JavaScript engine","ru":"движок JavaScript"},{"en":"download","ru":"скачивать"},{"en":"homepage","ru":"домашняя страница"},{"en":"refresh","ru":"обновить страницу"},{"en":"search engine","ru":"поисковая система"},{"en":"autofill","ru":"автозаполнение"},{"en":"compatibility","ru":"совместимость браузеров"},{"en":"plugin","ru":"плагин браузера"}]'::jsonb),
  (c,m3,'URLs & DNS',4,16,'vocabulary',true,true,'[{"en":"URL","ru":"унифицированный указатель ресурса"},{"en":"domain name","ru":"доменное имя"},{"en":"subdomain","ru":"поддомен"},{"en":"path","ru":"путь к ресурсу"},{"en":"query string","ru":"строка запроса"},{"en":"DNS","ru":"система доменных имён"},{"en":"DNS lookup","ru":"DNS-запрос"},{"en":"registrar","ru":"регистратор доменов"},{"en":"TLD","ru":"домен верхнего уровня"},{"en":"nameserver","ru":"сервер имён"},{"en":"redirect","ru":"перенаправление"},{"en":"SSL certificate","ru":"SSL-сертификат"},{"en":"CDN","ru":"сеть доставки контента"},{"en":"resolve","ru":"разрешать DNS-запрос"},{"en":"expire","ru":"истекать срок действия"},{"en":"WHOIS","ru":"база данных WHOIS"},{"en":"subdirectory","ru":"подпапка"},{"en":"canonical URL","ru":"каноническая ссылка"},{"en":"propagation","ru":"распространение DNS"},{"en":"IP mapping","ru":"сопоставление с IP"}]'::jsonb),
  (c,m3,'Web Applications',5,17,'vocabulary',true,true,'[{"en":"web application","ru":"веб-приложение"},{"en":"frontend","ru":"фронтенд"},{"en":"backend","ru":"бэкенд"},{"en":"database","ru":"база данных"},{"en":"API","ru":"программный интерфейс"},{"en":"authentication","ru":"аутентификация"},{"en":"session","ru":"сессия"},{"en":"dynamic content","ru":"динамическое содержимое"},{"en":"static site","ru":"статический сайт"},{"en":"framework","ru":"фреймворк"},{"en":"deployment","ru":"развёртывание"},{"en":"environment","ru":"среда выполнения"},{"en":"version","ru":"версия"},{"en":"dependency","ru":"зависимость"},{"en":"build","ru":"сборка"},{"en":"staging","ru":"тестовая среда"},{"en":"production","ru":"производственная среда"},{"en":"scalability","ru":"масштабируемость"},{"en":"performance","ru":"производительность"},{"en":"user experience","ru":"пользовательский опыт"}]'::jsonb),
  (c,m3,'Email & Messaging',6,18,'vocabulary',true,true,'[{"en":"inbox","ru":"входящие"},{"en":"subject line","ru":"тема письма"},{"en":"attachment","ru":"вложение"},{"en":"reply","ru":"ответить"},{"en":"forward","ru":"переслать"},{"en":"CC","ru":"копия письма"},{"en":"BCC","ru":"скрытая копия"},{"en":"spam","ru":"спам"},{"en":"phishing","ru":"фишинг"},{"en":"email client","ru":"почтовый клиент"},{"en":"SMTP","ru":"протокол SMTP"},{"en":"signature","ru":"подпись"},{"en":"draft","ru":"черновик"},{"en":"filter","ru":"фильтр"},{"en":"mailing list","ru":"список рассылки"},{"en":"newsletter","ru":"новостная рассылка"},{"en":"instant messaging","ru":"мгновенные сообщения"},{"en":"notification","ru":"уведомление"},{"en":"unsubscribe","ru":"отписаться"},{"en":"thread","ru":"ветка переписки"}]'::jsonb);

  -- Module 4: Digital Tools & Office
  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Spreadsheets',1,19,'vocabulary',true,true,'[{"en":"cell","ru":"ячейка"},{"en":"row","ru":"строка"},{"en":"column","ru":"столбец"},{"en":"formula","ru":"формула"},{"en":"SUM","ru":"функция СУММ"},{"en":"AVERAGE","ru":"среднее значение"},{"en":"chart","ru":"диаграмма"},{"en":"pivot table","ru":"сводная таблица"},{"en":"conditional formatting","ru":"условное форматирование"},{"en":"sort","ru":"сортировать"},{"en":"filter","ru":"фильтровать"},{"en":"merge","ru":"объединять ячейки"},{"en":"freeze","ru":"закрепить строку/столбец"},{"en":"worksheet","ru":"лист"},{"en":"workbook","ru":"книга (файл)"},{"en":"data validation","ru":"проверка данных"},{"en":"VLOOKUP","ru":"функция ВПР"},{"en":"macro","ru":"макрос"},{"en":"absolute reference","ru":"абсолютная ссылка"},{"en":"named range","ru":"именованный диапазон"}]'::jsonb),
  (c,m4,'Word Processing',2,20,'vocabulary',true,true,'[{"en":"document","ru":"документ"},{"en":"paragraph","ru":"абзац"},{"en":"heading style","ru":"стиль заголовка"},{"en":"font","ru":"шрифт"},{"en":"bold","ru":"жирный"},{"en":"italic","ru":"курсив"},{"en":"underline","ru":"подчёркивание"},{"en":"alignment","ru":"выравнивание"},{"en":"indent","ru":"отступ"},{"en":"bullet point","ru":"маркированный список"},{"en":"numbered list","ru":"нумерованный список"},{"en":"header","ru":"верхний колонтитул"},{"en":"footer","ru":"нижний колонтитул"},{"en":"page break","ru":"разрыв страницы"},{"en":"comment","ru":"комментарий"},{"en":"track changes","ru":"отслеживание изменений"},{"en":"spell check","ru":"проверка орфографии"},{"en":"word count","ru":"количество слов"},{"en":"template","ru":"шаблон документа"},{"en":"table of contents","ru":"оглавление"}]'::jsonb),
  (c,m4,'Presentations',3,21,'vocabulary',true,true,'[{"en":"slide","ru":"слайд"},{"en":"slide deck","ru":"набор слайдов"},{"en":"template","ru":"шаблон"},{"en":"transition","ru":"переход между слайдами"},{"en":"animation","ru":"анимация"},{"en":"speaker notes","ru":"заметки докладчика"},{"en":"slide master","ru":"мастер слайдов"},{"en":"design theme","ru":"тема оформления"},{"en":"embed","ru":"встраивать"},{"en":"presentation mode","ru":"режим презентации"},{"en":"aspect ratio","ru":"соотношение сторон"},{"en":"export","ru":"экспортировать"},{"en":"thumbnail","ru":"миниатюра"},{"en":"font size","ru":"размер шрифта"},{"en":"contrast","ru":"контрастность"},{"en":"slideshow","ru":"показ слайдов"},{"en":"handout","ru":"раздаточный материал"},{"en":"rehearse","ru":"репетировать"},{"en":"timing","ru":"хронометраж"},{"en":"key message","ru":"ключевое сообщение"}]'::jsonb),
  (c,m4,'Cloud Storage',4,22,'vocabulary',true,true,'[{"en":"upload","ru":"загружать в облако"},{"en":"download","ru":"скачивать"},{"en":"sync","ru":"синхронизировать"},{"en":"share","ru":"поделиться"},{"en":"permissions","ru":"права доступа"},{"en":"storage quota","ru":"квота хранилища"},{"en":"backup","ru":"резервная копия"},{"en":"version history","ru":"история версий"},{"en":"offline access","ru":"доступ без интернета"},{"en":"collaboration","ru":"совместная работа"},{"en":"file size limit","ru":"ограничение размера файла"},{"en":"encryption","ru":"шифрование"},{"en":"recovery","ru":"восстановление"},{"en":"cloud provider","ru":"облачный провайдер"},{"en":"migrate","ru":"мигрировать данные"},{"en":"two-factor authentication","ru":"двухфакторная аутентификация"},{"en":"bandwidth","ru":"полоса пропускания"},{"en":"account","ru":"аккаунт"},{"en":"folder structure","ru":"структура папок"},{"en":"shared drive","ru":"общий диск"}]'::jsonb),
  (c,m4,'Collaboration Tools',5,23,'vocabulary',true,true,'[{"en":"workspace","ru":"рабочее пространство"},{"en":"channel","ru":"канал"},{"en":"thread","ru":"ветка сообщений"},{"en":"mention","ru":"упоминание"},{"en":"notification","ru":"уведомление"},{"en":"video call","ru":"видеозвонок"},{"en":"screen share","ru":"демонстрация экрана"},{"en":"real-time editing","ru":"совместное редактирование"},{"en":"task board","ru":"доска задач"},{"en":"deadline","ru":"срок выполнения"},{"en":"assign","ru":"назначать"},{"en":"status","ru":"статус задачи"},{"en":"integration","ru":"интеграция"},{"en":"workflow","ru":"рабочий процесс"},{"en":"bot","ru":"бот"},{"en":"archive","ru":"архивировать"},{"en":"comment","ru":"комментарий"},{"en":"sign-in","ru":"вход в систему"},{"en":"mobile app","ru":"мобильное приложение"},{"en":"productivity","ru":"продуктивность"}]'::jsonb),
  (c,m4,'Digital Communication',6,24,'vocabulary',true,true,'[{"en":"video conference","ru":"видеоконференция"},{"en":"webinar","ru":"вебинар"},{"en":"virtual meeting","ru":"виртуальная встреча"},{"en":"mute","ru":"отключить звук"},{"en":"breakout room","ru":"комната для группы"},{"en":"participant","ru":"участник"},{"en":"host","ru":"организатор"},{"en":"record","ru":"записывать"},{"en":"lag","ru":"задержка / торможение"},{"en":"etiquette","ru":"этикет"},{"en":"agenda","ru":"повестка дня"},{"en":"follow-up","ru":"дальнейшие действия"},{"en":"professional tone","ru":"деловой тон"},{"en":"digital signature","ru":"электронная подпись"},{"en":"cybersecurity","ru":"кибербезопасность"},{"en":"bandwidth","ru":"пропускная способность"},{"en":"Q&A","ru":"сессия вопросов и ответов"},{"en":"reaction","ru":"реакция (эмодзи)"},{"en":"raise hand","ru":"поднять руку (в звонке)"},{"en":"poll","ru":"опрос"}]'::jsonb);

  RAISE NOTICE 'Computer Science B1: 4 modules, 24 lessons inserted';
END $cs_b1$;
