-- ================================================================
-- ACCOUNTING B1  (c52350cf-0c6e-4e0d-83da-6e2668b2ba91)
-- 4 modules × 6 lessons × 20 words
-- ================================================================
DO $acc_b1$ DECLARE
  c UUID := 'c52350cf-0c6e-4e0d-83da-6e2668b2ba91';
  m1 UUID; m2 UUID; m3 UUID; m4 UUID;
BEGIN
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Financial Fundamentals',1,true) RETURNING id INTO m1;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Bookkeeping Basics',2,true) RETURNING id INTO m2;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Financial Statements',3,true) RETURNING id INTO m3;
  INSERT INTO english_modules(course_id,title,order_index,is_active) VALUES (c,'Business Documents',4,true) RETURNING id INTO m4;

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m1,'Assets & Liabilities',1,1,'vocabulary',true,true,'[{"en":"asset","ru":"актив"},{"en":"liability","ru":"обязательство"},{"en":"equity","ru":"собственный капитал"},{"en":"balance","ru":"баланс"},{"en":"current asset","ru":"оборотный актив"},{"en":"fixed asset","ru":"основной актив"},{"en":"current liability","ru":"краткосрочное обязательство"},{"en":"long-term debt","ru":"долгосрочный долг"},{"en":"net worth","ru":"чистая стоимость"},{"en":"book value","ru":"балансовая стоимость"},{"en":"depreciation","ru":"амортизация"},{"en":"goodwill","ru":"деловая репутация"},{"en":"intangible asset","ru":"нематериальный актив"},{"en":"tangible asset","ru":"материальный актив"},{"en":"market value","ru":"рыночная стоимость"},{"en":"fair value","ru":"справедливая стоимость"},{"en":"write-off","ru":"списание"},{"en":"carrying amount","ru":"балансовая стоимость актива"},{"en":"amortisation","ru":"амортизация нематериальных активов"},{"en":"solvency","ru":"платёжеспособность"}]'::jsonb),
  (c,m1,'Revenue & Expenses',2,2,'vocabulary',true,true,'[{"en":"revenue","ru":"выручка"},{"en":"income","ru":"доход"},{"en":"expense","ru":"расход"},{"en":"cost","ru":"затраты"},{"en":"profit","ru":"прибыль"},{"en":"gross profit","ru":"валовая прибыль"},{"en":"operating profit","ru":"операционная прибыль"},{"en":"net profit","ru":"чистая прибыль"},{"en":"cost of goods sold","ru":"себестоимость продаж"},{"en":"overhead","ru":"накладные расходы"},{"en":"direct cost","ru":"прямые затраты"},{"en":"indirect cost","ru":"косвенные затраты"},{"en":"variable cost","ru":"переменные затраты"},{"en":"fixed cost","ru":"постоянные затраты"},{"en":"margin","ru":"маржа"},{"en":"break-even","ru":"точка безубыточности"},{"en":"loss","ru":"убыток"},{"en":"gain","ru":"прибыль / выигрыш"},{"en":"sales","ru":"продажи"},{"en":"turnover","ru":"оборот"}]'::jsonb),
  (c,m1,'Equity',3,3,'vocabulary',true,true,'[{"en":"equity","ru":"акционерный капитал"},{"en":"shareholders equity","ru":"капитал акционеров"},{"en":"retained earnings","ru":"нераспределённая прибыль"},{"en":"dividend","ru":"дивиденд"},{"en":"share capital","ru":"уставный капитал"},{"en":"ordinary shares","ru":"обыкновенные акции"},{"en":"preference shares","ru":"привилегированные акции"},{"en":"paid-up capital","ru":"оплаченный капитал"},{"en":"reserves","ru":"резервы"},{"en":"bonus issue","ru":"бонусная эмиссия"},{"en":"rights issue","ru":"выпуск прав"},{"en":"buyback","ru":"обратный выкуп акций"},{"en":"market capitalisation","ru":"рыночная капитализация"},{"en":"earnings per share","ru":"прибыль на акцию"},{"en":"book value per share","ru":"балансовая стоимость акции"},{"en":"dilution","ru":"разводнение капитала"},{"en":"ownership","ru":"владение"},{"en":"par value","ru":"номинальная стоимость"},{"en":"treasury stock","ru":"казначейские акции"},{"en":"stock","ru":"акция / запас"}]'::jsonb),
  (c,m1,'Double Entry',4,4,'vocabulary',true,true,'[{"en":"debit","ru":"дебет"},{"en":"credit","ru":"кредит"},{"en":"double entry","ru":"двойная запись"},{"en":"journal entry","ru":"журнальная запись"},{"en":"ledger","ru":"главная книга"},{"en":"trial balance","ru":"пробный баланс"},{"en":"posting","ru":"разноска проводок"},{"en":"T-account","ru":"Т-счёт"},{"en":"chart of accounts","ru":"план счетов"},{"en":"debit balance","ru":"дебетовое сальдо"},{"en":"credit balance","ru":"кредитовое сальдо"},{"en":"contra account","ru":"контрарный счёт"},{"en":"nominal account","ru":"номинальный счёт"},{"en":"real account","ru":"реальный счёт"},{"en":"opening balance","ru":"начальное сальдо"},{"en":"closing balance","ru":"конечное сальдо"},{"en":"balancing","ru":"сведение баланса"},{"en":"bookkeeper","ru":"бухгалтер"},{"en":"account","ru":"счёт"},{"en":"folio","ru":"лист / ссылка"}]'::jsonb),
  (c,m1,'Chart of Accounts',5,5,'vocabulary',true,true,'[{"en":"account number","ru":"номер счёта"},{"en":"nominal code","ru":"номинальный код"},{"en":"account type","ru":"тип счёта"},{"en":"income statement","ru":"отчёт о прибылях и убытках"},{"en":"balance sheet","ru":"бухгалтерский баланс"},{"en":"classification","ru":"классификация"},{"en":"subaccount","ru":"субсчёт"},{"en":"cost centre","ru":"центр затрат"},{"en":"profit centre","ru":"центр прибыли"},{"en":"hierarchy","ru":"иерархия счетов"},{"en":"mapping","ru":"сопоставление счетов"},{"en":"reporting","ru":"отчётность"},{"en":"reconcile","ru":"сверять"},{"en":"structure","ru":"структура счетов"},{"en":"entity","ru":"юридическое лицо"},{"en":"period","ru":"отчётный период"},{"en":"adjust","ru":"корректировать"},{"en":"code","ru":"код счёта"},{"en":"parent account","ru":"родительский счёт"},{"en":"description","ru":"описание счёта"}]'::jsonb),
  (c,m1,'Basic Transactions',6,6,'vocabulary',true,true,'[{"en":"invoice","ru":"счёт-фактура"},{"en":"receipt","ru":"квитанция"},{"en":"purchase order","ru":"заказ на покупку"},{"en":"payment","ru":"платёж"},{"en":"cash","ru":"наличные"},{"en":"cheque","ru":"чек"},{"en":"bank transfer","ru":"банковский перевод"},{"en":"settlement","ru":"расчёт / погашение"},{"en":"due date","ru":"срок оплаты"},{"en":"payment terms","ru":"условия оплаты"},{"en":"discount","ru":"скидка"},{"en":"credit note","ru":"кредит-нота"},{"en":"debit note","ru":"дебет-нота"},{"en":"billing","ru":"выставление счёта"},{"en":"remittance","ru":"денежный перевод"},{"en":"instalment","ru":"платёж в рассрочку"},{"en":"prepayment","ru":"предоплата"},{"en":"accrual","ru":"начисление"},{"en":"provision","ru":"резерв"},{"en":"collection","ru":"инкассация / сбор оплаты"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m2,'Journals',1,7,'vocabulary',true,true,'[{"en":"general journal","ru":"главный журнал"},{"en":"purchase journal","ru":"журнал покупок"},{"en":"sales journal","ru":"журнал продаж"},{"en":"cash book","ru":"кассовая книга"},{"en":"journal entry","ru":"журнальная запись"},{"en":"source document","ru":"первичный документ"},{"en":"voucher","ru":"ваучер / документ-основание"},{"en":"narration","ru":"описание проводки"},{"en":"posting","ru":"разноска"},{"en":"adjusting entry","ru":"корректирующая запись"},{"en":"closing entry","ru":"закрывающая запись"},{"en":"reversing entry","ru":"сторнировочная запись"},{"en":"compound entry","ru":"сложная проводка"},{"en":"sub-ledger","ru":"аналитическая книга"},{"en":"reference","ru":"ссылка"},{"en":"date","ru":"дата"},{"en":"amount","ru":"сумма"},{"en":"description","ru":"описание"},{"en":"folio","ru":"ссылка на страницу"},{"en":"special journal","ru":"специальный журнал"}]'::jsonb),
  (c,m2,'Ledgers',2,8,'vocabulary',true,true,'[{"en":"general ledger","ru":"главная книга"},{"en":"subsidiary ledger","ru":"аналитическая книга"},{"en":"accounts receivable","ru":"дебиторская задолженность"},{"en":"accounts payable","ru":"кредиторская задолженность"},{"en":"ledger account","ru":"счёт главной книги"},{"en":"running total","ru":"накопительный итог"},{"en":"reconcile","ru":"сверять"},{"en":"audit trail","ru":"след аудита"},{"en":"control account","ru":"контрольный счёт"},{"en":"aged analysis","ru":"анализ по срокам"},{"en":"outstanding","ru":"непогашенная задолженность"},{"en":"settled","ru":"погашенный"},{"en":"write-off","ru":"списание"},{"en":"provision","ru":"резерв"},{"en":"carry forward","ru":"перенос на следующий период"},{"en":"statement","ru":"выписка"},{"en":"balance","ru":"сальдо"},{"en":"update","ru":"обновлять"},{"en":"maintenance","ru":"ведение учёта"},{"en":"net","ru":"нетто"}]'::jsonb),
  (c,m2,'Trial Balance',3,9,'vocabulary',true,true,'[{"en":"trial balance","ru":"пробный баланс"},{"en":"debit column","ru":"дебетовый столбец"},{"en":"credit column","ru":"кредитовый столбец"},{"en":"agreement","ru":"сходимость баланса"},{"en":"error","ru":"ошибка"},{"en":"adjusted trial balance","ru":"скорректированный пробный баланс"},{"en":"unadjusted","ru":"нескорректированный"},{"en":"period-end","ru":"конец периода"},{"en":"suspense account","ru":"счёт невыясненных сумм"},{"en":"correction","ru":"исправление"},{"en":"rounding","ru":"округление"},{"en":"preparation","ru":"составление"},{"en":"extract","ru":"выборка данных"},{"en":"format","ru":"форма"},{"en":"heading","ru":"заголовок"},{"en":"date","ru":"дата"},{"en":"currency","ru":"валюта"},{"en":"total","ru":"итог"},{"en":"closing","ru":"закрытие периода"},{"en":"balance","ru":"баланс"}]'::jsonb),
  (c,m2,'Reconciliation',4,10,'vocabulary',true,true,'[{"en":"bank reconciliation","ru":"сверка с банком"},{"en":"outstanding cheques","ru":"непредъявленные чеки"},{"en":"deposits in transit","ru":"незачисленные депозиты"},{"en":"timing difference","ru":"временная разница"},{"en":"balance per bank","ru":"остаток по банку"},{"en":"balance per books","ru":"остаток по книгам"},{"en":"adjusted balance","ru":"скорректированный остаток"},{"en":"discrepancy","ru":"расхождение"},{"en":"fraud detection","ru":"выявление мошенничества"},{"en":"uncleared","ru":"неклиринговый"},{"en":"matching","ru":"сопоставление"},{"en":"confirm","ru":"подтверждать"},{"en":"approve","ru":"утверждать"},{"en":"sign off","ru":"подписать / согласовать"},{"en":"frequency","ru":"периодичность"},{"en":"variance","ru":"отклонение"},{"en":"statement","ru":"выписка"},{"en":"error","ru":"ошибка"},{"en":"period","ru":"период"},{"en":"reconciliation","ru":"сверка"}]'::jsonb),
  (c,m2,'Petty Cash',5,11,'vocabulary',true,true,'[{"en":"petty cash","ru":"мелкая наличность"},{"en":"float","ru":"аванс / начальная сумма"},{"en":"imprest","ru":"система аванса"},{"en":"voucher","ru":"ваучер"},{"en":"claim","ru":"заявка на возмещение"},{"en":"reimbursement","ru":"возмещение"},{"en":"receipt","ru":"квитанция"},{"en":"authorisation","ru":"авторизация"},{"en":"top-up","ru":"пополнение"},{"en":"replenishment","ru":"пополнение фонда"},{"en":"custodian","ru":"кассир"},{"en":"petty cash book","ru":"книга мелкой наличности"},{"en":"cash box","ru":"кассовый ящик"},{"en":"limit","ru":"лимит"},{"en":"control","ru":"контроль"},{"en":"reconcile","ru":"сверять"},{"en":"approve","ru":"утверждать"},{"en":"record","ru":"записывать"},{"en":"balance","ru":"остаток"},{"en":"small expenses","ru":"мелкие расходы"}]'::jsonb),
  (c,m2,'Bank Statements',6,12,'vocabulary',true,true,'[{"en":"bank statement","ru":"банковская выписка"},{"en":"transaction","ru":"транзакция"},{"en":"deposit","ru":"вклад / поступление"},{"en":"withdrawal","ru":"снятие средств"},{"en":"standing order","ru":"постоянное поручение"},{"en":"direct debit","ru":"прямой дебет"},{"en":"bank charges","ru":"банковские комиссии"},{"en":"interest received","ru":"полученные проценты"},{"en":"closing balance","ru":"конечный остаток"},{"en":"opening balance","ru":"начальный остаток"},{"en":"reference","ru":"ссылка"},{"en":"narrative","ru":"описание операции"},{"en":"amount","ru":"сумма"},{"en":"credit","ru":"кредит / зачисление"},{"en":"debit","ru":"дебет / списание"},{"en":"reconcile","ru":"сверять"},{"en":"match","ru":"сопоставлять"},{"en":"import","ru":"импортировать"},{"en":"download","ru":"загружать"},{"en":"date","ru":"дата"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m3,'Balance Sheet',1,13,'vocabulary',true,true,'[{"en":"balance sheet","ru":"бухгалтерский баланс"},{"en":"assets","ru":"активы"},{"en":"liabilities","ru":"обязательства"},{"en":"equity","ru":"капитал"},{"en":"current","ru":"текущий"},{"en":"non-current","ru":"внеоборотный"},{"en":"total assets","ru":"итого активы"},{"en":"net assets","ru":"чистые активы"},{"en":"working capital","ru":"оборотный капитал"},{"en":"liquidity","ru":"ликвидность"},{"en":"solvency","ru":"платёжеспособность"},{"en":"position","ru":"финансовое положение"},{"en":"snapshot","ru":"моментальная картина"},{"en":"comparative","ru":"сравнительный"},{"en":"note","ru":"примечание"},{"en":"format","ru":"форма"},{"en":"presentation","ru":"представление"},{"en":"IFRS","ru":"МСФО"},{"en":"disclosure","ru":"раскрытие информации"},{"en":"date","ru":"дата составления"}]'::jsonb),
  (c,m3,'Income Statement',2,14,'vocabulary',true,true,'[{"en":"income statement","ru":"отчёт о прибылях и убытках"},{"en":"revenue","ru":"выручка"},{"en":"cost of sales","ru":"себестоимость продаж"},{"en":"gross profit","ru":"валовая прибыль"},{"en":"operating expenses","ru":"операционные расходы"},{"en":"EBITDA","ru":"EBITDA"},{"en":"depreciation","ru":"амортизация"},{"en":"interest","ru":"проценты"},{"en":"tax","ru":"налог"},{"en":"net profit","ru":"чистая прибыль"},{"en":"earnings","ru":"заработок / прибыль"},{"en":"period","ru":"отчётный период"},{"en":"comparative","ru":"сравнительный"},{"en":"segment","ru":"сегмент"},{"en":"comprehensive income","ru":"совокупный доход"},{"en":"other income","ru":"прочие доходы"},{"en":"format","ru":"форма"},{"en":"presentation","ru":"представление"},{"en":"profit and loss","ru":"прибыль и убытки"},{"en":"notes","ru":"примечания"}]'::jsonb),
  (c,m3,'Cash Flow Statement',3,15,'vocabulary',true,true,'[{"en":"cash flow statement","ru":"отчёт о движении денежных средств"},{"en":"operating activities","ru":"операционная деятельность"},{"en":"investing activities","ru":"инвестиционная деятельность"},{"en":"financing activities","ru":"финансовая деятельность"},{"en":"net cash flow","ru":"чистый денежный поток"},{"en":"opening cash","ru":"начальный остаток денег"},{"en":"closing cash","ru":"конечный остаток денег"},{"en":"direct method","ru":"прямой метод"},{"en":"indirect method","ru":"косвенный метод"},{"en":"free cash flow","ru":"свободный денежный поток"},{"en":"capital expenditure","ru":"капитальные затраты"},{"en":"proceeds","ru":"поступления"},{"en":"borrowings","ru":"заимствования"},{"en":"repayments","ru":"погашение долга"},{"en":"dividends paid","ru":"выплаченные дивиденды"},{"en":"non-cash","ru":"неденежные операции"},{"en":"reconciliation","ru":"сверка"},{"en":"liquidity","ru":"ликвидность"},{"en":"sustainability","ru":"устойчивость"},{"en":"working capital changes","ru":"изменения оборотного капитала"}]'::jsonb),
  (c,m3,'Notes to Accounts',4,16,'vocabulary',true,true,'[{"en":"accounting policies","ru":"учётная политика"},{"en":"significant estimates","ru":"существенные оценки"},{"en":"contingent liability","ru":"условное обязательство"},{"en":"commitment","ru":"обязательство / договорённость"},{"en":"related party","ru":"связанная сторона"},{"en":"subsequent event","ru":"последующее событие"},{"en":"going concern","ru":"непрерывность деятельности"},{"en":"disclosure","ru":"раскрытие информации"},{"en":"basis of preparation","ru":"основа подготовки"},{"en":"useful life","ru":"срок полезного использования"},{"en":"depreciation method","ru":"метод амортизации"},{"en":"fair value hierarchy","ru":"иерархия справедливой стоимости"},{"en":"leases","ru":"аренда"},{"en":"provisions","ru":"резервы"},{"en":"intangibles","ru":"нематериальные активы"},{"en":"segment information","ru":"сегментная информация"},{"en":"notes","ru":"примечания"},{"en":"carrying value","ru":"балансовая стоимость"},{"en":"tax","ru":"налог"},{"en":"share payment","ru":"платёж акциями"}]'::jsonb),
  (c,m3,'Reading Reports',5,17,'vocabulary',true,true,'[{"en":"annual report","ru":"годовой отчёт"},{"en":"interim report","ru":"промежуточный отчёт"},{"en":"financial highlights","ru":"ключевые финансовые показатели"},{"en":"key ratios","ru":"ключевые коэффициенты"},{"en":"management commentary","ru":"комментарий руководства"},{"en":"auditor report","ru":"аудиторское заключение"},{"en":"comparative","ru":"сравнительные данные"},{"en":"trend","ru":"тенденция"},{"en":"narrative","ru":"нарративная часть"},{"en":"graph","ru":"график"},{"en":"chart","ru":"диаграмма"},{"en":"disclosure","ru":"раскрытие"},{"en":"extract","ru":"выдержка"},{"en":"summary","ru":"краткое изложение"},{"en":"EBITDA","ru":"EBITDA"},{"en":"margin","ru":"маржа"},{"en":"growth","ru":"рост"},{"en":"segmental","ru":"сегментный"},{"en":"geographic","ru":"географический"},{"en":"notes","ru":"примечания"}]'::jsonb),
  (c,m3,'Basic Analysis',6,18,'vocabulary',true,true,'[{"en":"ratio analysis","ru":"анализ коэффициентов"},{"en":"current ratio","ru":"коэффициент текущей ликвидности"},{"en":"quick ratio","ru":"коэффициент быстрой ликвидности"},{"en":"debt ratio","ru":"коэффициент долга"},{"en":"profit margin","ru":"рентабельность продаж"},{"en":"return on equity","ru":"рентабельность капитала"},{"en":"return on assets","ru":"рентабельность активов"},{"en":"earnings per share","ru":"прибыль на акцию"},{"en":"price-to-earnings","ru":"коэффициент P/E"},{"en":"dividend yield","ru":"дивидендная доходность"},{"en":"gearing","ru":"финансовый рычаг"},{"en":"interest cover","ru":"покрытие процентов"},{"en":"asset turnover","ru":"оборачиваемость активов"},{"en":"benchmark","ru":"эталон / ориентир"},{"en":"compare","ru":"сравнивать"},{"en":"trend","ru":"тенденция"},{"en":"period","ru":"период"},{"en":"conclusion","ru":"вывод"},{"en":"insight","ru":"понимание"},{"en":"working capital ratio","ru":"коэффициент оборотного капитала"}]'::jsonb);

  INSERT INTO english_lessons(course_id,module_id,title,order_index,lesson_order,lesson_type,is_published,is_active,vocabulary) VALUES
  (c,m4,'Invoices',1,19,'vocabulary',true,true,'[{"en":"invoice","ru":"счёт-фактура"},{"en":"invoice number","ru":"номер счёта"},{"en":"due date","ru":"срок оплаты"},{"en":"seller","ru":"продавец"},{"en":"buyer","ru":"покупатель"},{"en":"description","ru":"описание"},{"en":"quantity","ru":"количество"},{"en":"unit price","ru":"цена за единицу"},{"en":"subtotal","ru":"промежуточный итог"},{"en":"VAT","ru":"НДС"},{"en":"total","ru":"итого"},{"en":"payment terms","ru":"условия оплаты"},{"en":"bank details","ru":"банковские реквизиты"},{"en":"purchase order reference","ru":"ссылка на заказ"},{"en":"tax invoice","ru":"налоговый счёт-фактура"},{"en":"pro forma","ru":"проформа-счёт"},{"en":"commercial invoice","ru":"коммерческий счёт"},{"en":"credit invoice","ru":"кредитовый счёт"},{"en":"e-invoice","ru":"электронный счёт"},{"en":"date","ru":"дата"}]'::jsonb),
  (c,m4,'Receipts',2,20,'vocabulary',true,true,'[{"en":"receipt","ru":"квитанция"},{"en":"proof of payment","ru":"подтверждение оплаты"},{"en":"date","ru":"дата"},{"en":"amount","ru":"сумма"},{"en":"paid","ru":"оплачено"},{"en":"payer","ru":"плательщик"},{"en":"payee","ru":"получатель"},{"en":"method","ru":"способ оплаты"},{"en":"cash receipt","ru":"кассовый чек"},{"en":"digital receipt","ru":"электронная квитанция"},{"en":"official receipt","ru":"официальная квитанция"},{"en":"acknowledgement","ru":"подтверждение получения"},{"en":"stamp","ru":"печать"},{"en":"signature","ru":"подпись"},{"en":"reference","ru":"ссылка"},{"en":"itemised","ru":"детализированный"},{"en":"tax receipt","ru":"налоговая квитанция"},{"en":"description","ru":"описание"},{"en":"duplicate","ru":"дубликат"},{"en":"original","ru":"оригинал"}]'::jsonb),
  (c,m4,'Purchase Orders',3,21,'vocabulary',true,true,'[{"en":"purchase order","ru":"заказ на покупку"},{"en":"PO number","ru":"номер заказа"},{"en":"vendor","ru":"поставщик"},{"en":"delivery date","ru":"дата поставки"},{"en":"item","ru":"позиция"},{"en":"quantity","ru":"количество"},{"en":"unit cost","ru":"цена за единицу"},{"en":"total","ru":"итого"},{"en":"authorised","ru":"авторизованный"},{"en":"approval","ru":"согласование"},{"en":"budget","ru":"бюджет"},{"en":"goods received note","ru":"накладная о получении товара"},{"en":"three-way match","ru":"трёхстороннее сопоставление"},{"en":"open PO","ru":"открытый заказ"},{"en":"cancel","ru":"отменять"},{"en":"amend","ru":"изменять"},{"en":"acknowledge","ru":"подтверждать"},{"en":"terms","ru":"условия"},{"en":"conditions","ru":"условия договора"},{"en":"match","ru":"сопоставлять"}]'::jsonb),
  (c,m4,'Contracts',4,22,'vocabulary',true,true,'[{"en":"contract","ru":"договор"},{"en":"parties","ru":"стороны"},{"en":"terms","ru":"условия"},{"en":"obligations","ru":"обязательства"},{"en":"payment schedule","ru":"график платежей"},{"en":"termination","ru":"расторжение"},{"en":"penalty","ru":"штраф"},{"en":"warranty","ru":"гарантия"},{"en":"governing law","ru":"применимое право"},{"en":"signature","ru":"подпись"},{"en":"amendment","ru":"поправка"},{"en":"addendum","ru":"дополнение"},{"en":"clause","ru":"пункт / статья"},{"en":"liability","ru":"ответственность"},{"en":"indemnity","ru":"возмещение убытков"},{"en":"confidentiality","ru":"конфиденциальность"},{"en":"effective date","ru":"дата вступления в силу"},{"en":"renewal","ru":"пролонгация"},{"en":"counterpart","ru":"экземпляр договора"},{"en":"date","ru":"дата"}]'::jsonb),
  (c,m4,'Payslips',5,23,'vocabulary',true,true,'[{"en":"payslip","ru":"расчётный листок"},{"en":"gross pay","ru":"начисленная зарплата"},{"en":"net pay","ru":"зарплата на руки"},{"en":"deduction","ru":"вычет"},{"en":"income tax","ru":"подоходный налог"},{"en":"national insurance","ru":"социальное страхование"},{"en":"pension","ru":"пенсионные отчисления"},{"en":"overtime","ru":"сверхурочные"},{"en":"bonus","ru":"премия"},{"en":"allowance","ru":"надбавка"},{"en":"employer contribution","ru":"взнос работодателя"},{"en":"PAYE","ru":"PAYE (налог у источника)"},{"en":"tax code","ru":"налоговый код"},{"en":"year-to-date","ru":"с начала года"},{"en":"basic salary","ru":"базовый оклад"},{"en":"benefits","ru":"льготы"},{"en":"loan repayment","ru":"погашение займа"},{"en":"holiday pay","ru":"отпускные"},{"en":"statutory pay","ru":"установленные выплаты"},{"en":"period","ru":"период"}]'::jsonb),
  (c,m4,'Business Correspondence',6,24,'vocabulary',true,true,'[{"en":"business letter","ru":"деловое письмо"},{"en":"memo","ru":"служебная записка"},{"en":"formal tone","ru":"официальный тон"},{"en":"subject","ru":"тема"},{"en":"salutation","ru":"обращение"},{"en":"body","ru":"основная часть"},{"en":"closing","ru":"заключительная фраза"},{"en":"signature","ru":"подпись"},{"en":"enclosure","ru":"приложение"},{"en":"CC","ru":"копия"},{"en":"reference","ru":"ссылка"},{"en":"letterhead","ru":"бланк"},{"en":"attachment","ru":"вложение"},{"en":"proofread","ru":"вычитывать"},{"en":"professional","ru":"профессиональный"},{"en":"concise","ru":"лаконичный"},{"en":"response","ru":"ответ"},{"en":"acknowledge","ru":"подтверждать получение"},{"en":"date","ru":"дата"},{"en":"distribute","ru":"распространять"}]'::jsonb);

  RAISE NOTICE 'Accounting B1: 4 modules, 24 lessons inserted';
END $acc_b1$;
