import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 21: Self Expression & Identity ───────────────────────────────────

'7eb130cb-fc23-4a61-abd1-5f0660c6f316':{pass_threshold:70,questions:[
  mc(1,'"Identity" encompasses:','only nationality','only physical appearance','your values, beliefs, personality, and social roles','your job title only','C'),
  mc(2,'"Self-concept" refers to:','how others see you','how you perceive yourself','your physical attributes only','your social status','B'),
  mc(3,'"Authenticity" means:','being the same as others','being genuine and true to yourself','following social norms exactly','changing yourself for others','B'),
  mc(4,'Complete: "She has a ___ (strong/strongly/strength) sense of identity."','strongly','strength','strengths','strong','D'),
  mc(5,'"Belonging" in identity means:','being identical to others','feeling accepted and part of a group','being alone','refusing to be part of a group','B'),
  mc(6,'"Intersectionality" refers to:','how different aspects of identity (race, gender, class) overlap and interact','a mathematical concept','a political party','fashion trends','A'),
  mc(7,'Complete: "Her cultural ___ (background/backing/back) shaped her worldview significantly."','backing','back','background','backed','C'),
  mc(8,'"Fluid identity" suggests that identity is:','fixed at birth','permanent and unchanging','determined by genetics only','dynamic and can change over time','D'),
  mc(9,'"Stereotype" is:','an accurate generalization','an oversimplified fixed image of a particular type of person or group','a personal value','an academic theory','B'),
  mc(10,'Complete: "She ___ (struggle) with questions of identity when she moved abroad."','struggles','struggle','struggling','struggled','D'),
  tf(11,'"Authenticity" means pretending to be someone you are not.','false'),
  tf(12,'"Intersectionality" refers to how multiple aspects of identity interact.','true'),
  tf(13,'"Stereotype" is an accurate and individualized representation of a person.','false'),
  fb(14,'Her strong sense of ___ (identity) helped her navigate the challenges of living abroad.','identity'),
  fb(15,'She ___ (struggled) to reconcile her cultural background with her new environment.','struggled'),
]},

'defae555-0234-439e-ae94-fbe26df66580':{pass_threshold:70,questions:[
  mc(1,'"Articulate" as an adjective means:','unable to express ideas','expressing ideas clearly and fluently','loud and aggressive','shy and reserved','B'),
  mc(2,'"Eloquent" means:','speaking clearly and persuasively','being very quiet','using simple vocabulary only','avoiding public speaking','A'),
  mc(3,'"Introspective" describes someone who:','is always outgoing','examines their own thoughts and feelings','avoids thinking deeply','is very social','B'),
  mc(4,'"Assertive" means:','being aggressive and rude','being too quiet','being able to express your needs and opinions confidently','agreeing with everyone','C'),
  mc(5,'"Empathetic" describes someone who:','lacks emotional intelligence','understands and shares others\' feelings','dominates conversations','avoids emotional topics','B'),
  mc(6,'"Confident" vs "arrogant": what is the key difference?','No difference','Confident = overestimates oneself; arrogant = realistic','Confident = healthy self-belief; arrogant = excessive and dismissive of others','Arrogant = positive; confident = negative','C'),
  mc(7,'"Self-aware" means:','oblivious to your impact on others','having a clear understanding of your own character, feelings, and behaviors','being very self-critical','avoiding reflection','B'),
  mc(8,'Complete: "She is remarkably ___ (articulate/articulation/articulated) when presenting complex ideas."','articulation','articulated','articulately','articulate','D'),
  mc(9,'"Tenacious" means:','easily giving up','very stubborn in a negative way','holding firmly to a purpose, determined','indifferent to outcomes','C'),
  mc(10,'"Resilient" people:','break down under pressure','recover quickly from setbacks','avoid challenges entirely','rely on others entirely','B'),
  tf(11,'"Assertive" and "aggressive" have the same meaning.','false'),
  tf(12,'"Introspective" people tend to examine their own inner thoughts and feelings.','true'),
  tf(13,'"Confident" and "arrogant" are synonyms.','false'),
  fb(14,'She is ___ (articulate) and able to explain complex ideas with remarkable clarity.','articulate'),
  fb(15,'His ___ (resilience) in the face of repeated setbacks was truly admirable.','resilience'),
]},

'5ef6d536-97b6-4824-9fdf-bb1276f71ece':{pass_threshold:70,questions:[
  mc(1,'"Evocative" art:','has no emotional impact','is purely abstract','brings strong feelings or memories to mind','is always political','C'),
  mc(2,'Complete: "The painting ___ (capture) the tension of the period beautifully."','captures','captured','capturing','capture','B'),
  mc(3,'"Abstract art" focuses on:','realistic representation of subjects','mathematical patterns only','using shape, color, and form to express ideas rather than realistic depiction','portraits only','C'),
  mc(4,'"Avant-garde" refers to:','traditional artistic techniques','conservative styles','innovative and experimental art that challenges norms','historical art periods','C'),
  mc(5,'Complete: "The sculpture ___ (convey) a powerful sense of movement."','conveying','convey','conveyed','conveys','D'),
  mc(6,'"Motif" in visual art is:','a unique style','a recurring visual element or pattern','a painting technique','a type of art exhibition','B'),
  mc(7,'Complete: "Her paintings are characterized by ___ (bold/boldly/boldness) use of color."','boldly','boldness','bolded','bold','D'),
  mc(8,'"Composition" in art refers to:','the chemical materials used','the artist\'s biography','the arrangement of visual elements in a work','the price of the artwork','C'),
  mc(9,'"Patron" of the arts is:','an art critic','an artist\'s student','a person who supports artists financially or politically','a type of artistic style','C'),
  mc(10,'Complete: "Critics ___ (praise) the artist\'s innovative approach to color and form."','praising','praised','praise','praising','B'),
  tf(11,'"Abstract art" focuses on realistic depiction of subjects.','false'),
  tf(12,'"Avant-garde" art challenges conventional norms and pushes boundaries.','true'),
  tf(13,'"Composition" in art refers to the artist\'s personal history.','false'),
  fb(14,'The ___ (composition) of the painting draws the eye to the center of the canvas.','composition'),
  fb(15,'Her work is deeply ___ (evocative), bringing to mind the landscapes of her childhood.','evocative'),
]},

'12f6a31e-9c22-40e5-98e2-f655c20667b8':{pass_threshold:70,questions:[
  mc(1,'Complete: "___ a trend." (set)','make','do','set','create','C'),
  mc(2,'Complete: "high-end ___."','fashion','fashioning','fashioned','fashions','A'),
  mc(3,'Complete: "a ___ of clothes."','range','rank','row','rating','A'),
  mc(4,'Complete: "fast ___." (disposable, mass-produced fashion)','fashion','dress','style','trend','A'),
  mc(5,'"Sustainable fashion" involves:','buying as many clothes as possible','clothes produced with minimal environmental impact','following every trend immediately','fast fashion only','B'),
  mc(6,'Complete: "Her ___ (style/styled/stylish/styling) is effortlessly chic."','styled','stylish','styling','style','D'),
  mc(7,'"Bespoke" clothing is:','mass-produced','off-the-rack','custom-made to an individual\'s specifications','always expensive but ready-made','C'),
  mc(8,'Complete: "She has a very ___ (distinctive/distinction/distinctly) personal style."','distinction','distinctly','distinctions','distinctive','D'),
  mc(9,'"Capsule wardrobe" means:','a very large collection of clothes','a small, curated collection of versatile, timeless pieces','children\'s clothing only','a type of storage system','B'),
  mc(10,'Complete: "The ___ (trend/trendy/trending) for maximalism contrasts with minimalist aesthetics."','trendy','trending','trended','trend','D'),
  tf(11,'"Fast fashion" is celebrated for its positive environmental impact.','false'),
  tf(12,'"Bespoke" clothing is custom-made to individual specifications.','true'),
  tf(13,'A "capsule wardrobe" consists of a small, versatile collection of essential pieces.','true'),
  fb(14,'She ___ (set) a new trend with her unconventional approach to formal wear.','set'),
  fb(15,'The growing demand for ___ (sustainable) fashion reflects changing consumer values.','sustainable'),
]},

'889aa58e-ab79-457e-b38d-42ffa7ccb46c':{pass_threshold:70,questions:[
  mc(1,'"Digital identity" is:','your offline personality only','how you present yourself online through social media and digital platforms','your national ID card','your email address','B'),
  mc(2,'Complete: "curate ___."','content','contenting','contented','contents','A'),
  mc(3,'"Influencer" in social media means:','someone with no online presence','someone who discourages product purchases','a person with a large following who can affect others\' opinions and behavior','a social media company employee','C'),
  mc(4,'"Algorithm" in social media:','is irrelevant to content','the set of rules a platform uses to determine what content users see','a type of computer virus','a user\'s privacy settings','B'),
  mc(5,'Complete: "She carefully ___ (curate) her online presence to project a professional image."','curates','curated','curating','curation','B'),
  mc(6,'"Echo chamber" in social media means:','a literal sound space','a diverse range of viewpoints','an environment where you only encounter views that reinforce your own','a debate platform','C'),
  mc(7,'Complete: "Social media can create unrealistic ___ (standard/standards/standardize) of beauty."','standard','standardize','standardized','standards','D'),
  mc(8,'"Digital footprint" refers to:','a technical error','your computer\'s memory','only your social media posts','the data trail you leave through your online activity','D'),
  mc(9,'"Viral" content is:','always harmful','content that spreads rapidly through sharing','content that is deleted quickly','private content','B'),
  mc(10,'Complete: "She was ___ (aware/awareness/awaring) of the risks of oversharing online."','awaring','awareness','aware','awared','C'),
  tf(11,'"Digital footprint" refers to the data trail left through online activity.','true'),
  tf(12,'"Echo chamber" exposes users to a wide variety of differing viewpoints.','false'),
  tf(13,'"Influencer" is someone with a significant online following who affects others\' opinions.','true'),
  fb(14,'She carefully ___ (curated) her social media profile to attract professional opportunities.','curated'),
  fb(15,'Living only in an ___ (echo chamber) can limit critical thinking and exposure to diverse views.','echo chamber'),
]},

'5dd1e77a-b364-4f3c-a7c3-ff1a139aa231':{pass_threshold:70,questions:[
  mc(1,'"Cultural identity" includes:','only nationality','language, traditions, values, and shared history of a group','only physical appearance','only religion','B'),
  mc(2,'Complete: "She takes great ___ (pride/proud/priding) in her heritage."','proud','priding','prideful','pride','D'),
  mc(3,'"Assimilation" in cultural context means:','adopting and fully integrating into the dominant culture','maintaining all aspects of your original culture','combining two cultures equally','refusing to engage with another culture','A'),
  mc(4,'"Multiculturalism" promotes:','cultural uniformity','the coexistence and mutual respect of multiple cultures in one society','eliminating cultural differences','a single national culture','B'),
  mc(5,'Complete: "She struggled to ___ (reconcile) her traditional upbringing with modern city life."','reconciling','reconciled','reconcile','reconciliation','C'),
  mc(6,'"Diaspora" refers to:','a type of cultural festival','the spread of a population from its original homeland to other countries','a government policy','a language dialect','B'),
  mc(7,'Complete: "Cultural ___ (exchange/exchanges/exchanging) broadens our understanding of the world."','exchanges','exchanging','exchanged','exchange','D'),
  mc(8,'"Ethnocentrism" means:','valuing all cultures equally','believing your own culture is superior to others','studying multiple cultures','cultural exchange','B'),
  mc(9,'Complete: "The ___ (diversity/diverse/diversify) of languages spoken in this city is remarkable."','diverse','diversify','diversified','diversity','D'),
  mc(10,'"Code-switching" refers to:','a computer programming technique','alternating between two languages or dialects depending on the social context','speaking only one language','refusing to adapt language','B'),
  tf(11,'"Diaspora" refers to a population dispersed from their original homeland.','true'),
  tf(12,'"Ethnocentrism" promotes equal respect for all cultures.','false'),
  tf(13,'"Code-switching" in linguistics means alternating between languages or dialects.','true'),
  fb(14,'She took great ___ (pride) in maintaining her cultural traditions despite living abroad.','pride'),
  fb(15,'The city\'s remarkable cultural ___ (diversity) makes it one of the most vibrant in the world.','diversity'),
]},

'8f5163fc-6fe5-40fc-80cc-56e9f1844bf6':{pass_threshold:70,questions:[
  mc(1,'"Practice what you preach" means:','study philosophy','do what you advise others to do','preach in public','avoid giving advice','B'),
  mc(2,'"Know your own mind" means:','be indecisive','be clear about what you want and believe','be self-critical','follow others\' advice','B'),
  mc(3,'"Be true to yourself" means:','act in accordance with your own values and character','follow the crowd','adapt constantly to others\' expectations','avoid all self-reflection','A'),
  mc(4,'"Stand your ground" means:','refuse to move physically','leave a difficult situation','abandon your beliefs','maintain your position or opinion when challenged','D'),
  mc(5,'"Live by your principles" means:','abandon your values when convenient','to act consistently with your moral beliefs','follow others\' rules only','avoid making decisions','B'),
  mc(6,'"Have the courage of your convictions" means:','be cowardly','follow the crowd','have the bravery to act on your beliefs','avoid conflict at all costs','C'),
  mc(7,'"Wear many hats" means:','have a large hat collection','have multiple roles or responsibilities','be indecisive about your identity','avoid commitment','B'),
  mc(8,'"March to the beat of your own drum" means:','be a musician','follow popular trends','avoid all social contact','live and behave independently of social norms','D'),
  mc(9,'"Stay true to your roots" means:','never leave your hometown','remain connected to your origins and values','forget your past','change your identity','B'),
  mc(10,'"Find yourself" means:','get lost and need directions','discover what is truly important to you','find your physical location','choose a career','B'),
  tf(11,'"Practice what you preach" encourages hypocrisy.','false'),
  tf(12,'"March to the beat of your own drum" means to live independently according to your own values.','true'),
  tf(13,'"Stand your ground" means to give in to pressure.','false'),
  fb(14,'She always ___ (practices what she preaches), which earns her great respect.','practices what she preaches'),
  fb(15,'It took years of self-reflection before she truly ___ (found herself).','found herself'),
]},

'1e42be47-7a3f-4e35-9c5b-db979fcf806f':{pass_threshold:80,questions:[
  mc(1,'"Authenticity" means:','copying others','following trends','changing constantly','being genuine and true to yourself','D'),
  mc(2,'"Intersectionality" refers to:','how multiple aspects of identity overlap','a mathematical concept','fashion trends','political parties','A'),
  mc(3,'"Articulate" as an adjective means:','shy and reserved','aggressive','unable to express ideas','expressing ideas clearly and fluently','D'),
  mc(4,'"Avant-garde" art is:','traditional and conservative','experimental and challenging conventional norms','realistic and representational','historical only','B'),
  mc(5,'Complete: "___ a trend." (establish something new in fashion)','make','do','create','set','D'),
  mc(6,'"Capsule wardrobe" means:','a storage system','a children\'s clothing line','a type of fashion brand','a small, curated collection of versatile pieces','D'),
  mc(7,'"Echo chamber" on social media means:','a diverse range of viewpoints','a literal sound space','an environment reinforcing only existing views','a debate platform','C'),
  mc(8,'"Diaspora" refers to:','a cultural festival','a government policy','a language dialect','a population dispersed from its original homeland','D'),
  mc(9,'"Ethnocentrism" means:','valuing all cultures equally','only studying other cultures','focusing on cultural exchange','believing your own culture is superior','D'),
  mc(10,'"Code-switching" in linguistics means:','switching between computer codes','alternating between languages/dialects based on social context','speaking only one language','a type of grammar error','B'),
  mc(11,'"March to the beat of your own drum" means:','be a musician','follow trends','live independently according to your own values','avoid social contact','C'),
  mc(12,'"Digital footprint" refers to:','a computer error','social media posts only','your email account','the data trail left through online activity','D'),
  mc(13,'Complete: "She ___ (reconcile) her traditional upbringing with her modern lifestyle."','reconciling','reconciliation','reconciled','reconcile','C'),
  mc(14,'"Resilient" means:','breaking down under pressure','avoiding all challenges','relying on others','recovering quickly from setbacks','D'),
  mc(15,'"Multiculturalism" promotes:','cultural uniformity','eliminating cultural differences','a single national identity','coexistence and respect of multiple cultures','D'),
  tf(16,'"Stand your ground" means to abandon your position.','false'),
  tf(17,'"Sustainable fashion" aims to minimize environmental impact.','true'),
  tf(18,'"Self-aware" people have a clear understanding of their own character and behavior.','true'),
  fb(19,'She carefully ___ (curated) her digital identity to present a professional image online.','curated'),
  fb(20,'Her strong sense of cultural ___ (identity) helped her navigate life in a foreign country.','identity'),
]},

// ── MODULE 22: Winners & Losers ──────────────────────────────────────────────

'78f5f61f-736b-4fd1-b96d-9204f8d734ac':{pass_threshold:70,questions:[
  mc(1,'"Resilience" in the face of failure means:','giving up after the first setback','allowing failure to define you','the ability to recover and continue despite setbacks','avoiding all risk','C'),
  mc(2,'Complete: "Failure is ___ (often/commonly) a stepping stone to success."','often / commonly — both correct','never','rarely','sometimes only','A'),
  mc(3,'"Stoicism" as a life philosophy promotes:','avoiding all challenges','pursuing pleasure only','emotional reactivity','accepting what cannot be changed and focusing on what you can control','D'),
  mc(4,'Complete: "She ___ (overcome) tremendous adversity to reach the top of her field."','overcame','overcoming','overcomes','overcome','A'),
  mc(5,'"Embrace failure" means:','avoid failure at all costs','accept and learn from failure as part of the growth process','fear failure','never attempt risky things','B'),
  mc(6,'Complete: "Success is not ___ (define/defined/defining) by wealth alone."','define','defining','defines','defined','D'),
  mc(7,'"Zero-sum" competition means:','everyone can win','cooperation leads to success','one person\'s gain is another\'s loss','success benefits all','C'),
  mc(8,'Complete: "He ___ (attribute) his success to hard work and the support of his family."','attributing','attributes','attributed','attribution','C'),
  mc(9,'"Grit" (Angela Duckworth) refers to:','physical strength','short-term motivation','perseverance and passion for long-term goals','intelligence only','C'),
  mc(10,'Complete: "She ___ (demonstrate) that determination matters more than innate talent."','demonstrates','demonstrating','demonstrated','demonstrate','C'),
  tf(11,'"Grit" refers to short-term motivation rather than long-term perseverance.','false'),
  tf(12,'"Zero-sum" competition implies one winner requires another\'s loss.','true'),
  tf(13,'Stoicism encourages emotional reactivity and impulsiveness.','false'),
  fb(14,'She ___ (attributed) her success to years of disciplined practice.','attributed'),
  fb(15,'Failure is often a valuable ___ (stepping stone) on the path to success.','stepping stone'),
]},

'287b8616-3f69-4f8d-908f-8cf001aa207a':{pass_threshold:70,questions:[
  mc(1,'Complete: "___ motivation." (intrinsic)','internal','intrinsic','self-driven','inner','B'),
  mc(2,'Complete: "___ potential." (unlock/reach/fulfill)','unlock / reach / fulfill — all correct','unlock only','reach only','fulfill only','A'),
  mc(3,'Complete: "___ a goal." (set/achieve/reach)','set / achieve / reach — all correct','set only','achieve only','reach only','A'),
  mc(4,'"Growth mindset" (Carol Dweck) is the belief that:','abilities are fixed at birth','intelligence cannot be developed','talent is all that matters','abilities can be developed through effort and learning','D'),
  mc(5,'Complete: "She ___ (maintain) a positive mindset despite enormous setbacks."','maintains','maintaining','maintained','maintain','C'),
  mc(6,'"Intrinsic motivation" comes from:','external rewards like money','social pressure','fear of failure','internal interest and personal satisfaction','D'),
  mc(7,'"Extrinsic motivation" is driven by:','personal curiosity','internal passion','enjoyment of the task','external rewards like grades, money, or praise','D'),
  mc(8,'Complete: "Positive ___ (reinforcement/reinforce/reinforce) strengthens desired behaviors."','reinforcing','reinforce','reinforces','reinforcement','D'),
  mc(9,'"Self-efficacy" means:','self-confidence in social situations','belief in one\'s ability to succeed in a specific task','general happiness','lack of confidence','B'),
  mc(10,'Complete: "She ___ (commit) fully to her training program."','commits','committing','committed','commit','C'),
  tf(11,'"Growth mindset" believes abilities are fixed at birth.','false'),
  tf(12,'"Intrinsic motivation" comes from internal interest and personal satisfaction.','true'),
  tf(13,'"Self-efficacy" refers to belief in your ability to perform specific tasks.','true'),
  fb(14,'She maintained a ___ (growth) mindset, viewing every challenge as an opportunity to learn.','growth'),
  fb(15,'"___ (Intrinsic) motivation is more sustainable than external rewards," argued the psychologist.','Intrinsic'),
]},

'18bff802-62da-4ebe-89b0-53ca73a06fd9':{pass_threshold:70,questions:[
  mc(1,'Past Perfect in narratives of challenge shows:','ongoing current actions','completed actions before the key story moment','future plans','general facts','B'),
  mc(2,'Complete: "By the time she reached the finish line, she ___ (run) for over four hours."','ran','has run','had been running','was running','C'),
  mc(3,'"Against all odds" in a narrative means:','with all advantages','with great ease','with no opposition','despite very unfavorable circumstances','D'),
  mc(4,'"Pivotal moment" means:','an unimportant event','the beginning of a story','a decisive moment that changes the course of events','a conclusion','C'),
  mc(5,'Complete: "She ___ (refuse) to give up, even when everything seemed lost."','refusing','refused','refuses','refusal','B'),
  mc(6,'"Watershed moment" means:','a moment near water','a turning point after which things are fundamentally different','a trivial incident','a beginning','B'),
  mc(7,'Complete: "His perseverance ___ (pay) off when he was finally offered his dream job."','paying','pays','paid','pay','C'),
  mc(8,'"Triumph over adversity" means:','succeeding after great difficulty','winning without challenges','succeeding immediately','being lucky','A'),
  mc(9,'Complete: "She ___ (rise) to the challenge and delivered an outstanding performance."','rises','rising','risen','rose','D'),
  mc(10,'"Inner strength" refers to:','physical power','external support systems','emotional and psychological resilience','material resources','C'),
  tf(11,'"Watershed moment" refers to a turning point that changes everything.','true'),
  tf(12,'"Triumph over adversity" means succeeding without any difficulty.','false'),
  tf(13,'Past Perfect Continuous is used in challenge narratives to emphasize duration before a key event.','true'),
  fb(14,'By the time help arrived, she ___ (had been fighting) for survival for three days.','had been fighting'),
  fb(15,'It was a ___ (pivotal) moment that changed the course of her career forever.','pivotal'),
]},

'5f8465cb-d33e-4a8e-b613-d1ea6f62cd69':{pass_threshold:70,questions:[
  mc(1,'"Fair play" means:','winning at all costs','following the rules and playing with integrity','only applicable in sports','always losing','B'),
  mc(2,'Complete: "The results ___ (spark) a debate about the fairness of the judging criteria."','sparks','sparking','sparked','spark','C'),
  mc(3,'"Level playing field" means:','a flat sports surface','a situation where all competitors have equal opportunities','an unfair competitive advantage','a sports facility','B'),
  mc(4,'"Doping" in sport means:','a legal training method','a dietary supplement','the use of prohibited performance-enhancing substances','a type of equipment','C'),
  mc(5,'Complete: "She ___ (argue) that the rules disadvantage smaller countries."','argues','argued','arguing','argument','B'),
  mc(6,'"Meritocracy" in competition means:','winning based on social status','rewarding talent and effort rather than privilege','inheriting success','using connections to win','B'),
  mc(7,'Complete: "Competitive ___ (spirit/spirits/spirituality) should be tempered by respect for opponents."','spirits','spirituality','spirit','spiritual','C'),
  mc(8,'"Sportsmanship" refers to:','professional contract negotiations','ethical behavior, fairness, and respect in sport','winning strategies','physical training','B'),
  mc(9,'Complete: "The decision ___ (prove) controversial among the athletes."','proving','proved','proves','proven','B'),
  mc(10,'"Zero-sum competition" means:','cooperation leads to best results','everyone improves together','one person\'s gain necessarily means another\'s loss','there are no winners','C'),
  tf(11,'"Fair play" involves competing with integrity and respect for rules.','true'),
  tf(12,'"Doping" is a legal method of performance enhancement in sport.','false'),
  tf(13,'"Level playing field" describes a situation of equal opportunity for all competitors.','true'),
  fb(14,'The scandal ___ (sparked) a global debate about the ethics of professional sport.','sparked'),
  fb(15,'True ___ (sportsmanship) means respecting your opponents as much as the rules of the game.','sportsmanship'),
]},

'f92073f4-ceb0-4117-a086-dbab4e4a12d8':{pass_threshold:70,questions:[
  mc(1,'"Mentor" is someone who:','competes against you','a peer at the same level','an experienced person who guides and supports someone less experienced','your employer','C'),
  mc(2,'"Trailblazer" means:','someone who follows existing paths','someone who is very conventional','someone who is the first to do or achieve something new','someone who gets lost frequently','C'),
  mc(3,'"Icon" in the context of achievement means:','a computer symbol','a religious image','a widely recognized symbol of something','a person or thing considered a representative symbol of a field or movement','D'),
  mc(4,'Complete: "She ___ (inspire) a whole generation of young athletes."','inspires','inspiring','inspired','inspiration','C'),
  mc(5,'"Legacy" means:','a current achievement','something left behind (achievements, influence) that lasts after you are gone','a type of sports trophy','a financial inheritance only','B'),
  mc(6,'"Unprecedented" achievement is:','something that has never been done or achieved before','a common achievement','something that was expected','a minor improvement','A'),
  mc(7,'Complete: "His ___ (legacy/legacies/legated/legating) in the field of science endures decades after his death."','legacies','legated','legating','legacy','D'),
  mc(8,'"Groundbreaking" work is:','routine and predictable','innovative and doing something that has never been done before','expensive','historical only','B'),
  mc(9,'Complete: "She ___ (dedicate) her life to improving education in underserved communities."','dedicates','dedicating','dedicated','dedication','C'),
  mc(10,'"Perseverance" distinguishes the most successful people because:','talent is all that matters','luck determines success','external support is most important','sustained effort over time overcomes obstacles','D'),
  tf(11,'"Legacy" refers to achievements and influence that persist after someone is gone.','true'),
  tf(12,'"Groundbreaking" means routine and expected.','false'),
  tf(13,'"Unprecedented" means something that has happened many times before.','false'),
  fb(14,'Her ___ (groundbreaking) research transformed our understanding of the human genome.','groundbreaking'),
  fb(15,'He will be remembered for the extraordinary ___ (legacy) he left in humanitarian work.','legacy'),
]},

'd0785a09-1c5d-4b6c-bbfb-482d945d2a88':{pass_threshold:70,questions:[
  mc(1,'"Every cloud has a silver lining" means:','every problem is permanent','clouds always bring rain','every negative situation has a positive aspect','success comes without effort','C'),
  mc(2,'"What doesn\'t kill you makes you stronger" expresses:','overcoming difficulties builds character and resilience','all difficulties should be avoided','weakness is desirable','pain is unnecessary','B'),
  mc(3,'"You reap what you sow" means:','farming metaphor only','the results of your actions will eventually affect you','others suffer your consequences','hard work is never rewarded','B'),
  mc(4,'"Actions speak louder than words" means:','silence is golden','what you actually do is more important than what you say','physical activity is more important than discussion','loud actions are wrong','B'),
  mc(5,'"Failure is the mother of success" suggests:','never attempt anything risky','avoid failure at all costs','failures are necessary steps on the path to success','success comes from luck alone','C'),
  mc(6,'"No pain, no gain" means:','avoiding discomfort is wise','struggle and effort are necessary for achievement','all effort is wasted','success comes easily','B'),
  mc(7,'"The early bird catches the worm" means:','birds have early meals','starting early leads to success or advantage','worms are valuable','birds are hardworking','B'),
  mc(8,'"Look before you leap" means:','always jump slowly','consider consequences carefully before acting','leap is better than looking','caution is always wrong','B'),
  mc(9,'"Fall seven times, stand up eight" expresses:','failure is permanent','resilience and persistence in the face of repeated failure','giving up is acceptable','only seven attempts are allowed','B'),
  mc(10,'"Fortune favors the brave" means:','brave people are always lucky','success comes easily','those who take bold action are more likely to succeed','luck is the main factor','C'),
  tf(11,'"You reap what you sow" suggests your actions have consequences.','true'),
  tf(12,'"Actions speak louder than words" values speech over action.','false'),
  tf(13,'"No pain, no gain" suggests achievement requires effort and hardship.','true'),
  fb(14,'"___ (Every cloud has a silver lining)" — she kept this in mind during the difficult months.','Every cloud has a silver lining'),
  fb(15,'"Fall seven times, stand up ___ (eight)" — this proverb captures the essence of resilience.','eight'),
]},

'a8a2d1f2-b013-4ae1-bbde-3f4aac9abfa0':{pass_threshold:70,questions:[
  mc(1,'"Growth mindset" (Dweck) is the belief that:','intelligence is fixed','abilities develop through dedication and effort','talent determines all outcomes','failure should be avoided','B'),
  mc(2,'Complete: "A growth mindset ___ (embrace) challenges as opportunities for learning."','embracing','embraced','embraces','embrace','C'),
  mc(3,'"Fixed mindset" leads to:','embracing challenges','seeing effort as pointless since abilities are innate','improving continuously','taking on new risks','B'),
  mc(4,'Complete: "Research ___ (demonstrate) that effort matters more than innate ability."','demonstrating','demonstrated','demonstrates','demonstration','C'),
  mc(5,'"Neuroplasticity" means:','the brain cannot change','the brain\'s ability to reorganize itself by forming new neural connections throughout life','only children\'s brains can change','physical flexibility','B'),
  mc(6,'Complete: "She ___ (adopt) a growth mindset after reading about cognitive psychology."','adopts','adopting','adopt','adopted','D'),
  mc(7,'"Deliberate practice" means:','practicing randomly without focus','practicing specifically to improve weaknesses, with focused effort','natural talent development','practicing without feedback','B'),
  mc(8,'Complete: "The research ___ (suggest) that feedback accelerates the learning process."','suggesting','suggested','suggestion','suggests','D'),
  mc(9,'"Metacognition" means:','thinking about facts','memorizing information','avoiding thinking','thinking about one\'s own thinking and learning processes','D'),
  mc(10,'Complete: "Students with a growth mindset ___ (view) failure as feedback."','viewed','viewing','views','view','D'),
  tf(11,'"Fixed mindset" views abilities as inherent and unchangeable.','true'),
  tf(12,'"Neuroplasticity" suggests the brain cannot form new connections after childhood.','false'),
  tf(13,'"Deliberate practice" involves focused effort to improve specific weaknesses.','true'),
  fb(14,'She ___ (adopted) a growth mindset and transformed her approach to learning.','adopted'),
  fb(15,'___ (Neuroplasticity) explains why consistent practice can fundamentally change our abilities.','Neuroplasticity'),
]},

'0e6cac4b-40d7-492a-bdff-db29a3ffc254':{pass_threshold:80,questions:[
  mc(1,'"Grit" means:','physical strength','luck','natural talent','long-term perseverance and passion for goals','D'),
  mc(2,'"Growth mindset" believes abilities are:','fixed at birth','determined by IQ','developed through effort and learning','inherited genetically','C'),
  mc(3,'Complete: "___ (Intrinsic/Extrinsic) motivation comes from internal interest."','Extrinsic','Neither','Both equally','Intrinsic','D'),
  mc(4,'"Legacy" means:','a current award','achievements and influence that persist after someone is gone','a financial inheritance only','a sports trophy','B'),
  mc(5,'"Groundbreaking" means:','routine and expected','innovative, doing something never done before','expensive and exclusive','historically irrelevant','B'),
  mc(6,'"Zero-sum competition" means:','everyone benefits from the outcome','cooperation leads to best results','there are no winners','one person\'s gain is another\'s loss','D'),
  mc(7,'"Sportsmanship" refers to:','contract negotiations','physical training','winning at all costs','ethical, fair behavior in competition','D'),
  mc(8,'"Level playing field" means:','a flat sports surface','one team has an advantage','an unfair situation','equal opportunities for all competitors','D'),
  mc(9,'Complete: "She ___ (attribute) her success to years of disciplined practice."','attributing','attributes','attribute','attributed','D'),
  mc(10,'"Neuroplasticity" is the brain\'s ability to:','remain fixed throughout life','form new neural connections and reorganize throughout life','increase in physical size','only develop in childhood','B'),
  mc(11,'"Mentor" is someone who:','competes against you','a peer at the same level','offers no guidance','guides and supports someone less experienced','D'),
  mc(12,'Complete: "Her ___ (resilience/resilient/resiliently) was remarkable throughout the ordeal."','resilient','resiliently','resiliencer','resilience','D'),
  mc(13,'"Deliberate practice" involves:','random practice without focus','fun recreational activities','avoidance of feedback','focused effort to improve specific weaknesses','D'),
  mc(14,'Complete: "Success is not ___ (define) by financial wealth alone."','defining','defines','define','defined','D'),
  mc(15,'"Watershed moment" is:','a trivial event','a beginning','a type of weather','a turning point that changes everything','D'),
  tf(16,'"Trailblazer" means someone who follows conventional paths.','false'),
  tf(17,'"Growth mindset" views effort as key to developing abilities.','true'),
  tf(18,'"Every cloud has a silver lining" suggests every negative situation has a positive aspect.','true'),
  fb(19,'Her ___ (perseverance) in the face of repeated failure ultimately led to her breakthrough.','perseverance'),
  fb(20,'"___ (Fortune favors the brave)" — this principle drove her to take bold career risks.','Fortune favors the brave'),
]},

// ── MODULE 23: Movement & Sport ──────────────────────────────────────────────

'0acf19d6-273b-43ed-9d25-e3ef376fad5a':{pass_threshold:70,questions:[
  mc(1,'Complete: "___ a record." (set)','make','do','break or set','get','C'),
  mc(2,'Complete: "achieve ___ victory."','a decisive','decisive','decision','deciding','A'),
  mc(3,'"Peak performance" refers to:','average output','declining ability','the highest level of performance an athlete can achieve','beginner performance','C'),
  mc(4,'Complete: "She ___ (clinch) the championship with a last-minute goal."','clinching','clinches','clinch','clinched','D'),
  mc(5,'"Qualifying round" means:','the final competition','a round to determine who advances to the next stage','a practice session','a penalty shootout','B'),
  mc(6,'Complete: "___ (Host) the Olympics is a great honor for any nation."','Hosting','Hosted','Hosts','Host','A'),
  mc(7,'"Underdog" means:','the favorite to win','the strongest competitor','a type of sports equipment','a competitor not expected to win','D'),
  mc(8,'Complete: "The team ___ (defy) expectations with a stunning upset victory."','defied','defying','defies','defy','A'),
  mc(9,'"Grand slam" (tennis) means:','a type of shot','winning all four major tournaments in one calendar year','a penalty in a match','a type of serve','B'),
  mc(10,'"Stamina" refers to:','explosive short-term power','technical skill','the ability to sustain prolonged physical effort','speed over short distances','C'),
  tf(11,'"Underdog" refers to the competitor most likely to win.','false'),
  tf(12,'"Grand slam" in tennis means winning all four major tournaments in a year.','true'),
  tf(13,'"Stamina" refers to short-term explosive power.','false'),
  fb(14,'She ___ (clinched) the title with a record-breaking performance in the final event.','clinched'),
  fb(15,'The ___ (underdog) team shocked the world by defeating the reigning champions.','underdog'),
]},

'234e7a59-3e50-4184-84a8-89720cee504f':{pass_threshold:70,questions:[
  mc(1,'Complete: "Olympic ___." (spirit)','spirit','spiritual','spirited','spirits','A'),
  mc(2,'Complete: "push the ___ (boundaries/boundary/bound)."','boundary','bound','limits — also correct','boundaries','D'),
  mc(3,'Complete: "achieve personal ___." (best)','bests','better','best','besting','C'),
  mc(4,'Complete: "break a ___." (world record)','world record','worldwide record','global record','international record','A'),
  mc(5,'Complete: "represent one\'s ___." (country)','countries','country','countered','countrified','B'),
  mc(6,'"Amateur" athlete is:','paid professionally','competing for money only','a volunteer coach','someone who participates in a sport without financial reward','D'),
  mc(7,'Complete: "The Olympic ___ (ideal/idealism/idealize) promotes peace and international understanding."','idealism','idealize','idealized','ideal','D'),
  mc(8,'"Ceremony" of the Olympics includes:','only sports competitions','the opening and closing ceremonies with cultural performances','press conferences only','medal distribution only','B'),
  mc(9,'Complete: "She ___ (devote) years of her life to competitive gymnastics."','devotes','devoted','devoting','devote','B'),
  mc(10,'"Podium finish" means:','winning a participation certificate','an honorable mention','a top 3 placing (gold, silver, or bronze)','a qualifying position','C'),
  tf(11,'"Amateur" athletes compete without financial reward.','true'),
  tf(12,'The Olympic ideal promotes peace and international cooperation.','true'),
  tf(13,'"Podium finish" refers to any finishing position in a competition.','false'),
  fb(14,'She ___ (devoted) every hour to training for the Olympic Games.','devoted'),
  fb(15,'Achieving a ___ (podium) finish at the World Championships was her lifelong dream.','podium'),
]},

'f6182cd8-4c98-40bf-a912-3e0bcc588aeb':{pass_threshold:70,questions:[
  mc(1,'Complete narrative: "She ___ (train) for months when she finally received the call."','trained','was training','had been training','trains','C'),
  mc(2,'Past Perfect: "By the time the competition began, she ___ (prepare) for a year."','was preparing','prepared','prepares','had been preparing','D'),
  mc(3,'"By the skin of her teeth" means:','easily and comfortably','with a wide margin','just barely','with great skill','C'),
  mc(4,'Complete: "She ___ (persevere) through injury, exhaustion, and self-doubt."','perseveres','persevered','persevering','persevere','B'),
  mc(5,'"Grueling" challenge is:','easy and enjoyable','moderately difficult','very easy','extremely demanding and exhausting','D'),
  mc(6,'Complete: "Nothing could ___ (deter) her from completing the race."','deterred','deterring','deters','deter','D'),
  mc(7,'"Harrowing" experience is:','mildly unpleasant','motivating and positive','extremely distressing','moderately challenging','C'),
  mc(8,'Complete: "The team ___ (overcome) every obstacle placed in their path."','overcomes','overcoming','overcame','overcome','C'),
  mc(9,'Narrative past tense: "As she ___ (cross) the finish line, tears ___ (stream) down her face."','was crossing / streamed','crosses / streamed','crossed / streams','had crossed / was streaming','A'),
  mc(10,'"Break records" in competitive sports means:','fail to qualify','achieve a new standard higher than any previously recorded','match existing records','withdraw from competition','B'),
  tf(11,'"Grueling" describes something extremely demanding and exhausting.','true'),
  tf(12,'"By the skin of her teeth" means she won easily.','false'),
  tf(13,'Past Perfect Continuous is used to show duration of action before a key past event.','true'),
  fb(14,'She ___ (had been training) for two years before she finally achieved her personal best.','had been training'),
  fb(15,'Against all odds, he ___ (overcame) his injury to compete in the final.','overcame'),
]},

'2e29b08c-06f2-46d9-9cd4-76f0a0ef0fcc':{pass_threshold:70,questions:[
  mc(1,'"Agility" means:','strength in lifting','the ability to move quickly and easily','endurance over time','explosive speed only','B'),
  mc(2,'"Flexibility" in sport refers to:','mental adaptability only','physical speed','the range of motion available in a joint','physical strength','C'),
  mc(3,'Complete: "The gymnast ___ (execute) the routine with flawless precision."','executes','executing','executed','execution','C'),
  mc(4,'"Core strength" refers to:','strength of the legs','the muscles of the trunk (abdomen, back) that stabilize the body','strength of the arms','mental toughness','B'),
  mc(5,'Complete: "She ___ (demonstrate) exceptional balance and coordination."','demonstrates','demonstrating','demonstrated','demonstrating','C'),
  mc(6,'"Biomechanics" is the study of:','sports psychology','dietary requirements in sport','the mechanics of human movement','team tactics','C'),
  mc(7,'Complete: "The athlete ___ (maintain) his form despite the intense fatigue."','maintaining','maintained','maintains','maintain','B'),
  mc(8,'"Proprioception" refers to:','visual perception in sport','the sense of your body\'s position and movement in space','hearing in sport','balance only','B'),
  mc(9,'Complete: "Proper ___ (technique/technical/technically) reduces the risk of injury."','technical','technically','techniques','technique','D'),
  mc(10,'"Coordination" means:','ability to lift heavy weights','the ability to use different parts of the body together smoothly','running speed','lung capacity','B'),
  tf(11,'"Agility" refers to the ability to move quickly and change direction easily.','true'),
  tf(12,'"Core strength" refers primarily to the strength of the legs.','false'),
  tf(13,'"Biomechanics" studies the physical mechanics of human movement.','true'),
  fb(14,'The swimmer\'s flawless ___ (technique) allowed her to shave seconds off her personal best.','technique'),
  fb(15,'She demonstrated extraordinary ___ (agility) throughout the martial arts competition.','agility'),
]},

'e2b9a887-464b-4421-b7b9-bb3f2e23fabe':{pass_threshold:70,questions:[
  mc(1,'"Sports psychology" focuses on:','training schedules','nutrition and diet','the mental and emotional aspects of sport performance','physical conditioning','C'),
  mc(2,'"Visualization" in sport psychology means:','watching match recordings','mentally rehearsing a performance to improve physical execution','physical warm-up','watching opponents','B'),
  mc(3,'Complete: "She ___ (attribute) her victory to mental preparation as much as physical training."','attributes','attributing','attributed','attribute','C'),
  mc(4,'"Flow state" (Csikszentmihalyi) means:','feeling bored during performance','a state of complete absorption and optimal performance','being distracted','experiencing pain','B'),
  mc(5,'"Pre-competition anxiety" means:','complete calmness before competition','absence of nervous feelings','feeling relaxed and confident','nervousness experienced before competing','D'),
  mc(6,'Complete: "Focusing on ___ (process) goals rather than outcome goals reduces anxiety."','processing','processed','processes','process','D'),
  mc(7,'"Self-talk" in sport is:','talking to your coach','internal dialogue that affects confidence and performance','speaking to opponents','post-match analysis','B'),
  mc(8,'Complete: "The coach ___ (encourage) the team to use positive self-talk techniques."','encouraged','encouraging','encourages','encourage','A'),
  mc(9,'"Burnout" in athletes is caused by:','occasional rest','taking enough breaks','too many holidays','prolonged overtraining and stress without adequate recovery','D'),
  mc(10,'"Mental toughness" means:','physical endurance','speed and agility','the ability to maintain focus and composure under pressure','technical skill','C'),
  tf(11,'"Visualization" helps athletes mentally rehearse performance.','true'),
  tf(12,'"Flow state" is a state of boredom and distraction.','false'),
  tf(13,'"Mental toughness" refers only to physical endurance.','false'),
  fb(14,'She ___ (attributed) her gold medal performance to years of psychological training.','attributed'),
  fb(15,'Positive ___ (self-talk) helped her overcome her pre-race anxiety.','self-talk'),
]},

'cefdf10c-3b86-45e3-8e13-a2448019df28':{pass_threshold:70,questions:[
  mc(1,'Complete: "Sport ___ (play) a vital role in building social cohesion."','played','playing','plays','play','C'),
  mc(2,'"Grassroots sport" refers to:','elite professional sport','sport at the local community level for ordinary participants','professional leagues','Olympic sport only','B'),
  mc(3,'"Social cohesion" through sport means:','dividing communities','economic inequality','sport bringing people together across social divides','exclusive sports clubs','C'),
  mc(4,'Complete: "She ___ (argue) that sport should be more accessible to disadvantaged communities."','argues','argued','arguing','argument','B'),
  mc(5,'"Commercialization" of sport means:','sport becoming more amateur','the influence of money and business interests on sport','reducing ticket prices','grassroots development','B'),
  mc(6,'Complete: "Equal ___ (access/accessible/accessibility) to sport is a fundamental right."','accessible','accessibility','accessed','access','D'),
  mc(7,'"Gender equality" in sport means:','men\'s sport receives more funding','women should not compete','equal opportunities, resources, and recognition for all genders','differences in pay are natural','C'),
  mc(8,'Complete: "The report ___ (highlight) the significant gender pay gap in professional sport."','highlights','highlighting','highlighted','highlight','C'),
  mc(9,'"Disability sport" refers to:','sport excluding disabled athletes','eliminating sport for disabled people','sport specifically designed for athletes with physical or intellectual disabilities','mainstream sport only','C'),
  mc(10,'Complete: "Sport has the power to ___ (transcend) cultural and political barriers."','transcended','transcending','transcends','transcend','D'),
  tf(11,'"Grassroots sport" refers to elite professional sport.','false'),
  tf(12,'"Commercialization" of sport involves increasing business and financial interests.','true'),
  tf(13,'Sport has the power to promote social cohesion across different communities.','true'),
  fb(14,'Improving ___ (access) to sport for all members of society is a key policy goal.','access'),
  fb(15,'Sport has the remarkable ability to ___ (transcend) political and cultural divides.','transcend'),
]},

'1760e119-f199-47a1-9162-989e8355ee6a':{pass_threshold:70,questions:[
  mc(1,'Extended reading: which strategy helps with unknown vocabulary?','Stop reading','Look up every word','Use context clues to infer meaning','Skip the paragraph','C'),
  mc(2,'Complete: "The article ___ (chronicle) her remarkable journey from obscurity to global fame."','chronicles','chronicled','chronicling','chronicle','B'),
  mc(3,'"Prolific" athlete is one who:','rarely competes','fails frequently','achieves very little','produces a large body of work or achievements','D'),
  mc(4,'Complete: "She ___ (overcome) numerous injuries throughout her illustrious career."','overcomes','overcoming','overcome','overcame','D'),
  mc(5,'"Posthumous" recognition means:','recognition while alive','recognition given after someone\'s death','immediate recognition','recognition during childhood','B'),
  mc(6,'Complete: "His ___ (unprecedented/precedent/precede) achievements have never been equalled."','precedent','precede','preceded','unprecedented','D'),
  mc(7,'"Accolade" means:','a type of criticism','a sports injury','an award or honor given in recognition of achievement','a training technique','C'),
  mc(8,'Complete: "She received numerous ___ (accolade/accolades/acclaimed) throughout her career."','accolade','acclaimed','acclaimations','accolades','D'),
  mc(9,'"Illustrious career" means:','an average career','a poorly regarded career','a career marked by great success and distinction','a short career','C'),
  mc(10,'Complete: "His ___ (legacy/legacies/legated) endures long after his retirement from sport."','legacies','legated','legating','legacy','D'),
  tf(11,'"Prolific" means producing a large body of work or achievements.','true'),
  tf(12,'"Posthumous" recognition is given while the person is still alive.','false'),
  tf(13,'"Accolade" refers to an award or honor.','true'),
  fb(14,'Her ___ (illustrious) career spanned three decades and included six World Championship titles.','illustrious'),
  fb(15,'She received a ___ (posthumous) award recognizing her lifetime contribution to the sport.','posthumous'),
]},

'c4bd3498-ff2a-43f7-b08b-8702ac577d95':{pass_threshold:80,questions:[
  mc(1,'"Underdog" means:','the favorite to win','a spectator','a referee','a competitor not expected to win','D'),
  mc(2,'"Stamina" is:','explosive power','the ability to sustain prolonged physical effort','speed','flexibility','B'),
  mc(3,'Complete: "She ___ (clinch) victory with a record-breaking performance."','clinching','clinches','clinch','clinched','D'),
  mc(4,'"Flow state" means:','boredom during performance','a state of complete focus and optimal performance','pre-competition anxiety','physical fatigue','B'),
  mc(5,'"Visualization" helps athletes by:','reducing physical training','replacing physical training','increasing fatigue','mentally rehearsing performance','D'),
  mc(6,'"Grassroots sport" refers to:','professional leagues','elite competition only','sport at the local community level','Olympic sport','C'),
  mc(7,'Complete: "___ (Break) a world record" (set a new global standard)','Setting','Making','Doing','Breaking','D'),
  mc(8,'"Agility" means:','strength in lifting','endurance over time','lung capacity','ability to move quickly and change direction','D'),
  mc(9,'"Grand slam" in tennis means:','one tournament win','winning a local event','a type of serve','winning all four major tournaments in one year','D'),
  mc(10,'Complete: "By the time the match ended, she ___ (compete) for over five hours."','was competing','competed','is competing','had been competing','D'),
  mc(11,'"Mental toughness" means:','physical strength','speed and agility','technical skill','maintaining focus and composure under pressure','D'),
  mc(12,'Complete: "Sport has the power to ___ (transcend) political and cultural barriers."','transcended','transcending','transcends','transcend','D'),
  mc(13,'"Biomechanics" studies:','nutrition in sport','sports psychology','the mechanics of human movement','team tactics','C'),
  mc(14,'"Prolific" athlete:','rarely competes','produces many achievements','fails often','competes only locally','B'),
  mc(15,'"Illustrious career" is:','an average career','a short career','a poorly regarded career','a career marked by great success and distinction','D'),
  tf(16,'"Flow state" is characterized by complete absorption and peak performance.','true'),
  tf(17,'"Grassroots sport" refers to elite professional sport.','false'),
  tf(18,'"Posthumous" recognition is given after someone\'s death.','true'),
  fb(19,'She ___ (attributed) her success to mental preparation as much as physical training.','attributed'),
  fb(20,'The ___ (underdog) team defeated the reigning champions in one of the greatest upsets in history.','underdog'),
]},

// ── MODULE 24: The Final Mile ────────────────────────────────────────────────

'038f14b7-d0cc-42db-af5c-056c1f7a85b9':{pass_threshold:70,questions:[
  mc(1,'Present Perfect Continuous: "She ___ here for ten years."','worked','has worked','has been working','is working','C'),
  mc(2,'Past Continuous Passive: "The road ___ repaired when the accident happened."','was','were','was being','has been','C'),
  mc(3,'Future Perfect: "By Monday, I ___ the report."','will finish','will be finishing','finish','will have finished','D'),
  mc(4,'Third Conditional: "If she ___ earlier, she would have caught the flight."','left','leaves','had left','would have left','C'),
  mc(5,'Past Perfect: "They had already ___ by the time we arrived."','leave','left','leaving','been leaving','B'),
  mc(6,'Present Simple Passive: "Coffee ___ in Colombia."','is grown','was grown','has been grown','grows','A'),
  mc(7,'Modal Passive: "The reports ___ submitted by Friday." (obligation)','must','must be','must been','is must','B'),
  mc(8,'Future Continuous: "This time tomorrow, we ___ on the beach."','will lie','will be lying','will have lied','lie','B'),
  mc(9,'Mixed Conditional (3+2): "If she ___ medicine, she would be a doctor now."','studies','studied','was studying','had studied','D'),
  mc(10,'Reported Speech: "I am tired," he said. → He said he ___ tired.','is','was','were','has been','B'),
  tf(11,'Past Perfect Passive uses "had been + past participle."','true'),
  tf(12,'"Would" can appear in the if-clause of any conditional.','false'),
  tf(13,'Future Perfect Continuous uses "will have been + -ing."','true'),
  fb(14,'By graduation, she ___ (will have been studying) for four years.','will have been studying'),
  fb(15,'The project ___ (had been completed) before the inspection took place.','had been completed'),
]},

'87eefe02-a469-4d0b-a026-61e7c9d32c06':{pass_threshold:70,questions:[
  mc(1,'"Must" for deduction: "She ___ be exhausted — she worked 14 hours."','can','might','may','must','D'),
  mc(2,'"Should have done" expresses:','past ability','certainty about the past','past permission','criticism of a past action not done','D'),
  mc(3,'"Needn\'t have done" implies:','the action was necessary','the action was forbidden','the action was done but wasn\'t necessary','the action wasn\'t done','C'),
  mc(4,'Zero Conditional: "If you heat ice, ___."','it would melt','it melts','it will melt','it melted','B'),
  mc(5,'Second Conditional: "If I were you, I ___ accept the offer."','will','would','had','am going to','B'),
  mc(6,'"Could have + past participle" means:','certainty about the past','past ability that was used','impossibility','past ability that existed but wasn\'t used','D'),
  mc(7,'First Conditional: "If she ___, we\'ll wait for her."','is late','was late','had been late','would be late','A'),
  mc(8,'"Can\'t have + past participle" expresses:','certainty','possibility','past ability','logical impossibility about the past','D'),
  mc(9,'Mixed Conditional (2+3): "If she ___ more patient, she would have handled it better."','is','was','were','had been','C'),
  mc(10,'Complete: "The report ___ be submitted by Friday." (strong obligation — modal passive)','must','must be','must been','is must','B'),
  tf(11,'"Must have" is used for logical deduction about the past.','true'),
  tf(12,'"Needn\'t have done" means the action was obligatory but wasn\'t done.','false'),
  tf(13,'"Would" can appear in the if-clause of conditional sentences.','false'),
  fb(14,'She ___ (must have been) studying all night — the lights were on until 3am.','must have been'),
  fb(15,'If he ___ (had taken) the opportunity, he would be running the department now. (Mixed 3+2)','had taken'),
]},

'7989a4d7-49b6-48e6-ac23-ce926dc8f07c':{pass_threshold:70,questions:[
  mc(1,'Reported Speech: "I have finished," she said. → She said she ___.','has finished','finished','had finished','was finishing','C'),
  mc(2,'Reported Question: "Where do you work?" → She asked where I ___.','do work','works','work','worked','D'),
  mc(3,'Reported Command: "Don\'t be late!" → He told me ___ late.','to not be','not to be','don\'t be','not being','B'),
  mc(4,'Time expression: "tomorrow" → reported speech:','tomorrow','the next day / the following day','yesterday','today','B'),
  mc(5,'Inversion: "Never ___ I seen such dedication."','have','did','was','had','A'),
  mc(6,'"Not only did she win, ___ she broke the record."','but she also','but also she','and she also','but she also too','A'),
  mc(7,'Reporting verb: "I stole it," he said. → He ___ stealing it.','denied','refused','admitted','promised','C'),
  mc(8,'Inversion: "Seldom ___ such an opportunity arise."','does','is','was','did','A'),
  mc(9,'Cleft sentence: "It was ___ who invented the telephone."','Graham Bell','Bell Graham','Alexander Graham Bell','the Bell who','C'),
  mc(10,'Reporting verb "suggest": correct form?','She suggested to go.','She suggested going.','She suggested that we to go.','She suggested went.','B'),
  tf(11,'In reported questions, we use statement word order (no inversion).','true'),
  tf(12,'"Seldom does she complain" is correct subject-auxiliary inversion.','true'),
  tf(13,'Inversion is commonly used in informal everyday conversation.','false'),
  fb(14,'He ___ (admitted having made) several errors in the final report.','admitted having made'),
  fb(15,'___ (Never) have I encountered such a complex and rewarding project.','Never'),
]},

'47f8328f-3fdc-49da-ab71-3aef005c9ed9':{pass_threshold:70,questions:[
  mc(1,'Complete: "She plays ___ violin beautifully." (musical instrument)','a','an','(no article)','the','D'),
  mc(2,'Complete: "___ Pacific Ocean is the largest ocean on Earth."','A','An','(no article)','The','D'),
  mc(3,'Determiner: "There is ___ milk left." (small amount, positive)','few','a few','a little','little','C'),
  mc(4,'Comparison: "The ___ you read, the ___ you learn."','much / better','many / most','more / better','more / more','D'),
  mc(5,'"Double comparative": "It\'s getting ___ (increasingly expensive)"','more and more expensive','much expensive','a lot expensive','very and very expensive','A'),
  mc(6,'Determiner: "___ people attended — the hall was empty." (almost none, negative)','A few','A little','Few','Little','C'),
  mc(7,'Complete: "He is ___ more experienced than any other candidate."','very','a lot — also correct','much / a lot (both correct)','quite','C'),
  mc(8,'Complete: "This is by far ___ book I\'ve read this year."','the most interesting','more interesting','most interesting','very interesting','A'),
  mc(9,'Inversion: "___ (No sooner) had she arrived ___ the crisis began."','No sooner / then','No sooner / than','As soon as / than','No sooner / when','B'),
  mc(10,'Complete: "She speaks ___ English." (language — no article)','the','a','an','(no article)','D'),
  tf(11,'"Few" is more negative than "a few."','true'),
  tf(12,'"Very" can intensify comparative adjectives ("very more interesting").','false'),
  tf(13,'"The + comparative, the + comparative" is used for parallel changes.','true'),
  fb(14,'"No sooner had he left ___ (than) the phone rang."','than'),
  fb(15,'The ___ (more) you practice, the more confident you become.','more'),
]},

'dfda6893-1c90-4b8f-bca1-4134d190235f':{pass_threshold:75,questions:[
  mc(1,'"Gradable" adjective can be modified by:','absolutely / utterly','very / quite / rather','completely / entirely','only absolutely','B'),
  mc(2,'"Tenacious" means:','easily giving up','shy and reserved','reckless','persistent and determined','D'),
  mc(3,'"Gerunds vs Infinitives": "She denied ___ the money."','to steal','steal','stolen','stealing','D'),
  mc(4,'"Used to + infinitive" expresses:','a past habit or state that no longer exists','a current habit','a future plan','a general truth','A'),
  mc(5,'"Get used to + gerund" means:','to be already accustomed','to stop a habit','to become accustomed','to refuse to adjust','C'),
  mc(6,'"I wish I ___ spoken to him sooner!" (past regret)','should have','would have','have','had','D'),
  mc(7,'Complex Object: "She made him ___."','to apologize','apologizing','apologized','apologize','D'),
  mc(8,'"Modal perfect": "She ___ have been nervous — her hands were shaking."','might','can','should','must','D'),
  mc(9,'"Stative verb" that should NOT be in continuous:','run','write','belong','travel','C'),
  mc(10,'"Hit it off" means:','to argue','to ignore each other','to end a friendship','to like each other right away','D'),
  mc(11,'"Indefatigable" means:','easily tired','very lazy','careless','unable to be tired out, tireless','D'),
  mc(12,'"Burn one\'s bridges" means:','start a fire','travel abroad','build better relationships','destroy valuable relationships irreparably','D'),
  mc(13,'"Metaphor" differs from "simile" because metaphor:','uses "like" or "as"','is a type of rhythm','is only used in poetry','makes a comparison without "like" or "as"','D'),
  mc(14,'"Peer-reviewed" research is:','checked by students','reviewed by other experts in the field','written by peers','reviewed by the government','B'),
  mc(15,'"Ethnocentrism" means:','respecting all cultures equally','studying cultural diversity','being neutral about culture','believing your own culture is superior','D'),
  tf(16,'"Would" can replace "used to" for past states like "He would be shy."','false'),
  tf(17,'Academic writing uses hedging language to avoid overstating claims.','true'),
  tf(18,'"Eloquent" refers to clear and persuasive expression of ideas.','true'),
  fb(19,'She ___ (used to) spend every summer at the family cottage by the lake.','used to'),
  fb(20,'His ___ (charismatic) personality made him a natural leader within the organization.','charismatic'),
]},

'7513560c-4e81-48e5-b316-e41c2db0fe2c':{pass_threshold:75,questions:[
  mc(1,'"Exponential growth" means:','slow, steady growth','linear growth','declining output','increasingly rapid acceleration','D'),
  mc(2,'"Hedging language" in academic writing shows:','complete certainty','anger or frustration','caution about claims','informal opinion','C'),
  mc(3,'"Gastronomic" relates to:','building design','exercise science','the art and science of food and cooking','psychology','C'),
  mc(4,'"Al dente" pasta is:','overcooked','cooked firmly with a slight bite','raw','cooked in sauce only','B'),
  mc(5,'"Get away with" means:','to travel far away','to overcome a challenge','to avoid work','to escape punishment for doing something wrong','D'),
  mc(6,'"Once in a blue moon" means:','frequently','monthly','never','very rarely','D'),
  mc(7,'"Inter-" prefix means:','within','under','over','between or among','D'),
  mc(8,'"Sensible" vs "sensitive": "sensible" means:','easily upset','related to the senses','now / at this moment','having good practical judgment','D'),
  mc(9,'"Social mobility" means:','physical movement','social media use','government policy','the ability to move between socioeconomic positions','D'),
  mc(10,'"Meritocracy" means success is based on:','social connections','inherited wealth','luck','talent and effort','D'),
  mc(11,'"Growth mindset" believes:','abilities are fixed at birth','intelligence cannot develop','talent determines all','abilities develop through effort','D'),
  mc(12,'"Watershed moment" is:','near water','a minor event','the beginning of something','a turning point that changes everything','D'),
  mc(13,'"Grand slam" in tennis means:','winning one major tournament','a type of serve','a penalty','winning all four major tournaments in a year','D'),
  mc(14,'"Grassroots sport" refers to:','elite professional sport','Olympic sport','sport at the local community level','international sport','C'),
  mc(15,'"Prolific" means:','rarely achieving','producing many achievements or works','failing often','competing locally only','B'),
  tf(16,'"Code-switching" involves alternating between languages in different social contexts.','true'),
  tf(17,'"Avant-garde" art is traditional and conservative.','false'),
  tf(18,'"Neuroplasticity" means the brain can form new connections throughout life.','true'),
  fb(19,'Her ___ (illustrious) career spanning four decades is an inspiration to all.','illustrious'),
  fb(20,'The ___ (breakthrough) in renewable energy technology offers hope for the future.','breakthrough'),
]},

'be0913f0-f951-4eb8-9e53-d7a1a90a4443':{pass_threshold:75,questions:[
  mc(1,'Modal Passive: "The results ___ announced tomorrow."','must','will be','are being','were','B'),
  mc(2,'Reported: "I haven\'t finished," she said. → She said she ___.','hasn\'t finished','hadn\'t finished','didn\'t finish','wasn\'t finishing','B'),
  mc(3,'Third Conditional: "If they ___ harder, they would have won."','train','trained','were training','had trained','D'),
  mc(4,'Inversion: "Rarely ___ such talent in a single generation."','we see','saw we','did we see','we did see','C'),
  mc(5,'Academic writing: "go up" →','get bigger','rise / increase','move up','grow larger','B'),
  mc(6,'Complete: "___ (Despite) the setbacks, the project was completed on time." (formal)','Although','Even though','Despite','However','C'),
  mc(7,'Determiner: "___ water remains — ration carefully." (almost none, negative emphasis)','A little','A few','Few','Little','D'),
  mc(8,'Phrasal verb: "She ___ (put off) the meeting until next week."','put away','put up with','put forward','put off','D'),
  mc(9,'Idiom: "Once in a blue moon" means:','frequently','every month','very rarely','never','C'),
  mc(10,'Reported question: "Are you free?" → He asked ___ I was free.','that','whether','what','who','B'),
  mc(11,'Comparison: "The ___ more you practice, the better you become."','much','very','quite','more','D'),
  mc(12,'Cleft sentence: "___ was her dedication that made the project succeed."','That','Which','It','What','C'),
  mc(13,'"Inalienable" rights are:','rights that can be traded','rights that apply to citizens only','privileges, not rights','rights that cannot be taken away','D'),
  mc(14,'Vocabulary: "Eloquent" means:','shy and reserved','expressing ideas clearly and persuasively','aggressive in argument','unable to speak','B'),
  mc(15,'Grammar: "Have something done": "She ___ her car serviced."','did','made','got','had','D'),
  mc(16,'Reporting verb: "Let\'s go!" → She ___ going.','refused','denied','admitted','suggested','D'),
  mc(17,'Word formation: "investigate" → noun:','investigating','investigated','investigates','investigation','D'),
  mc(18,'Discourse: "Nevertheless" signals:','addition','example','result','contrast or concession','D'),
  mc(19,'Collocation: "___ awareness."','make','do','get','raise','D'),
  mc(20,'B2 level: "Interlocutor" in a speaking exam is:','the candidate','a type of question','the examiner who speaks with the candidate','a grammar term','C'),
]},

'e124497d-f562-4efc-bef7-edaffea3280b':{pass_threshold:80,questions:[
  mc(1,'Inversion: "Never ___ I encountered such a complex problem."','do','have','had','was','B'),
  mc(2,'Complete: "It was ___ who discovered penicillin." (cleft)','Fleming / Alexander Fleming','the Alexander','Alexander','Fleming who / Alexander Fleming who — both correct','D'),
  mc(3,'Mixed Conditional (3+2): "If she ___ law, she would be a barrister now."','studies','studied','was studying','had studied','D'),
  mc(4,'Reported: "I\'ll call you," he said. → He said he ___ call me.','will','shall','would','could','C'),
  mc(5,'Gerunds vs Infinitives: "She regrets ___ him the secret."','to tell','tell','told','telling','D'),
  mc(6,'Academic style: "lots of evidence" →','a lot of evidence','many evidence','loads of evidence','plenty evidences','A'),
  mc(7,'"Nominalization": "analyze" →','analyzing','analyzes','analyzed','analysis','D'),
  mc(8,'Article: "She is ___ pioneer in this field." (first mention, gradable)','an','the','(no article)','a','D'),
  mc(9,'Determiner: "She has ___ friends in the city." (almost none, negative)','a few','a little','little','few','D'),
  mc(10,'"Have something done": "He ___ his passport photo taken yesterday."','did','made','had','got','C'),
  mc(11,'Impersonal passive: "People believe the ruins date to 500 BC." →','It is believed that the ruins date to 500 BC.','People are believed to date the ruins.','The ruins are believed by people.','Believed ruins date to 500 BC.','A'),
  mc(12,'Modal Perfect: "She ___ been nervous — it was her first performance."','may have','might have','must have','could have','C'),
  mc(13,'Future Perfect Continuous: "By 2030, she ___ in this role for 15 years."','will work','will be working','will have worked','will have been working','D'),
  mc(14,'Word formation: "responsible" → noun:','responsibly','responsive','responsibleness','responsibility','D'),
  mc(15,'Idiom: "The tip of the iceberg" means:','the highest part','the complete picture','a solved problem','a small visible part of a much larger problem','D'),
  mc(16,'Collocation: "conduct ___."','a research','researches','researched','research','D'),
  mc(17,'Comparison: "This is by far ___ decision they\'ve ever made."','the most disastrous','more disastrous','most disastrous','very disastrous','A'),
  mc(18,'Discourse: "Admittedly, the results were mixed; however, ___."','the conclusion is obvious','the meaning is clear','the approach was flawed nevertheless','this represents significant progress','D'),
  mc(19,'Phrasal verb: "She eventually ___ (come round) to the idea."','came round','came around','came over — A and B both mean to change opinion','came through','C'),
  mc(20,'B2 Grammar: Complete: "Not until the 20th century ___ women given voting rights."','was','were','did','is','B'),
  mc(21,'Speculation: "He ___ have taken a different route — the GPS shows him elsewhere."','might','can\'t','should','would','B'),
  mc(22,'Vocabulary: "Unprecedented" means:','very common','expected','slight improvement','never done or seen before','D'),
  mc(23,'Vocabulary: "Meritocracy" means success is based on:','social class','inheritance','connections','talent and effort','D'),
  mc(24,'"Digital footprint" refers to:','a physical computer error','your email address only','data trail left through online activity','your social security number','C'),
  mc(25,'Final: Academic writing avoids:','technical vocabulary','passive voice','citing sources','contractions and informal language','D'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 21: "Self Expression & Identity"', lessons: ['7eb130cb-fc23-4a61-abd1-5f0660c6f316','defae555-0234-439e-ae94-fbe26df66580','5ef6d536-97b6-4824-9fdf-bb1276f71ece','12f6a31e-9c22-40e5-98e2-f655c20667b8','889aa58e-ab79-457e-b38d-42ffa7ccb46c','5dd1e77a-b364-4f3c-a7c3-ff1a139aa231','8f5163fc-6fe5-40fc-80cc-56e9f1844bf6','1e42be47-7a3f-4e35-9c5b-db979fcf806f'] },
  { name: 'Module 22: "Winners & Losers"', lessons: ['78f5f61f-736b-4fd1-b96d-9204f8d734ac','287b8616-3f69-4f8d-908f-8cf001aa207a','18bff802-62da-4ebe-89b0-53ca73a06fd9','5f8465cb-d33e-4a8e-b613-d1ea6f62cd69','f92073f4-ceb0-4117-a086-dbab4e4a12d8','d0785a09-1c5d-4b6c-bbfb-482d945d2a88','a8a2d1f2-b013-4ae1-bbde-3f4aac9abfa0','0e6cac4b-40d7-492a-bdff-db29a3ffc254'] },
  { name: 'Module 23: "Movement & Sport"', lessons: ['0acf19d6-273b-43ed-9d25-e3ef376fad5a','234e7a59-3e50-4184-84a8-89720cee504f','f6182cd8-4c98-40bf-a912-3e0bcc588aeb','2e29b08c-06f2-46d9-9cd4-76f0a0ef0fcc','e2b9a887-464b-4421-b7b9-bb3f2e23fabe','cefdf10c-3b86-45e3-8e13-a2448019df28','1760e119-f199-47a1-9162-989e8355ee6a','c4bd3498-ff2a-43f7-b08b-8702ac577d95'] },
  { name: 'Module 24: "The Final Mile"', lessons: ['038f14b7-d0cc-42db-af5c-056c1f7a85b9','87eefe02-a469-4d0b-a026-61e7c9d32c06','7989a4d7-49b6-48e6-ac23-ce926dc8f07c','47f8328f-3fdc-49da-ab71-3aef005c9ed9','dfda6893-1c90-4b8f-bca1-4134d190235f','7513560c-4e81-48e5-b316-e41c2db0fe2c','be0913f0-f951-4eb8-9e53-d7a1a90a4443','e124497d-f562-4efc-bef7-edaffea3280b'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 21–24 B2 Upper-Intermediate — КУРС ЗАВЕРШЁН!');
}
main();
