/**
 * Seed quizzes for A2 Pre-Intermediate — Modules 1, 2, 3.
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-a2-mod1-3.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // ═══ MODULE 1: Building Confidence ═══

  '671e4a36-210e-4f4a-b5eb-dfd725563522':{pass_threshold:70,questions:[  // Present Perfect
    mc(1,'Present Perfect is formed with:','subject + did + pp','subject + have/has + pp','subject + am/is + pp','subject + will + pp','B'),
    mc(2,'Choose correct: "She ___ (visit) Paris three times."','visited','has visited','visits','had visited','B'),
    mc(3,'Which time word signals Present Perfect?','yesterday','last year','in 2010','already','D'),
    mc(4,'Complete: "I ___ (never/try) bungee jumping."','never tried','have never tried','never tries','had never tried','B'),
    mc(5,'Choose correct question: "___ you ever ___ (eat) sushi?"','Did / eat','Have / eaten','Has / eat','Have / ate','B'),
    mc(6,'What is the past participle of "write"?','wrote','writed','written','writing','C'),
    mc(7,'Complete: "She ___ (just/finish) her presentation."','just finished','has just finished','just finishes','had just finished','B'),
    mc(8,'Choose: "He ___ (already/see) this film."','already saw','has already seen','already seen','already sees','B'),
    mc(9,'What is the past participle of "go"?','went','goed','gone','going','C'),
    mc(10,'Complete: "___ she ___ (ever/work) abroad?"','Did / worked','Has / worked','Have / worked','Had / worked','B'),
    tf(11,'Present Perfect uses have/has + past participle.','true'),
    tf(12,'"She has went" is correct Present Perfect.','false'),
    tf(13,'"Ever" and "never" are common with Present Perfect when discussing life experiences.','true'),
    fb(14,'I ___ (never/meet) a famous person. Have you ___ (ever/be) to Central Asia?','have never met, ever been'),
    fb(15,'She ___ (just/arrive). He ___ (already/book) the restaurant.','has just arrived, has already booked'),
  ]},

  '6cf73e5e-84fe-4978-8882-a12b6118a337':{pass_threshold:70,questions:[  // Present Perfect + For/Since
    mc(1,'"For" is used with:','a point in time','a duration of time','a specific date','a day of the week','B'),
    mc(2,'"Since" is used with:','a duration','a period of time','a starting point in time','a frequency','C'),
    mc(3,'Complete: "I have lived here ___ 2018."','for','during','since','ago','C'),
    mc(4,'Complete: "She has worked there ___ five years."','since','during','ago','for','D'),
    mc(5,'Choose the correct sentence:','I have known her since three years.','I have known her for three years.','I know her since three years.','I knew her for three years.','B'),
    mc(6,'Complete: "They haven\'t seen each other ___ they graduated."','for','during','since','ago','C'),
    mc(7,'Choose correct: "How long ___ you ___ (study) English?"','did / study','have / studied','do / study','are / studying','B'),
    mc(8,'Complete: "He has been a teacher ___ over 20 years."','since','ago','during','for','D'),
    mc(9,'Choose correct: "She hasn\'t called me ___ last Monday."','for','during','since','ago','C'),
    mc(10,'Complete: "We ___ (live) here ___ we got married."','have lived / since','lived / since','have lived / for','live / since','A'),
    tf(11,'"For" is used with a period of time (e.g. for three years, for a week).','true'),
    tf(12,'"Since" is used with a duration, not a point in time.','false'),
    tf(13,'"I have studied English since 2019" is correct.','true'),
    fb(14,'I have known her ___ (for/since) 2015. She has worked there ___ (for/since) ten years.','since, for'),
    fb(15,'How long ___ (have) you lived here? I ___ (live, PP) here ___ (since/for) 2020.','have, have lived, since'),
  ]},

  '604e3b3c-7499-4601-8ee5-fd0d7e1b7384':{pass_threshold:70,questions:[  // Past Simple vs Present Perfect
    mc(1,'Use Past Simple for:','actions with a connection to now','actions at a specific past time','life experiences','recent events','B'),
    mc(2,'Use Present Perfect for:','actions at a specific past time','completed actions with stated time','life experiences and recent events','past habits','C'),
    mc(3,'Choose: "She ___ (win) an award last year."','has won','have won','won','wins','C'),
    mc(4,'Choose: "He ___ (win) three awards so far."','won','has won','wins','had won','B'),
    mc(5,'Which sentence is correct?','I have seen him yesterday.','I saw him yesterday.','I have saw him yesterday.','I seen him yesterday.','B'),
    mc(6,'Which sentence uses Present Perfect correctly?','I have visited Tokyo last summer.','I visited Tokyo last summer.','I have visited Tokyo — it\'s amazing!','I have visit Tokyo.','C'),
    mc(7,'Choose: "Did you ___ (meet) anyone interesting at the conference?"','have met','met','meet','meeting','C'),
    mc(8,'Choose: "___ you ever ___ (be) to Antarctica?"','Did / go','Have / been','Has / went','Have / went','B'),
    mc(9,'Complete: "I ___ (not/see) her since Monday."','didn\'t see','don\'t see','haven\'t seen','wasn\'t seeing','C'),
    mc(10,'Which signals Past Simple?','already','just','ever','three years ago','D'),
    tf(11,'"Yesterday", "last year", "in 2020" signal Past Simple.','true'),
    tf(12,'"I have seen him yesterday" is correct.','false'),
    tf(13,'Present Perfect can be used when no specific time is mentioned.','true'),
    fb(14,'She ___ (win, PS) last year. She ___ (win, PP) twice this year.','won, has won'),
    fb(15,'I ___ (never/eat, PP) snake. I ___ (eat, PS) frog in France once.','have never eaten, ate'),
  ]},

  '4b84e700-0b2b-4039-a72f-9b3392e15b96':{pass_threshold:70,questions:[  // Comparative & Superlative
    mc(1,'Comparative of "expensive":','more expensive','expensiver','most expensive','the most expensive','A'),
    mc(2,'Superlative of "bad":','the baddest','the most bad','the worse','the worst','D'),
    mc(3,'Complete: "London is ___ (expensive) ___ Almaty."','more expensive / than','expensiver / than','most expensive / than','the more expensive / than','A'),
    mc(4,'Superlative of "far":','the farest','the farrest','the farthest / furthest','the most far','C'),
    mc(5,'Complete: "She is ___ (good) student in the class."','the most good','the better','the best','the goodest','C'),
    mc(6,'Comparative of "little" (quantity):','littler','more little','less','the fewest','C'),
    mc(7,'Choose correct: "This exam is ___ (difficult) ___ the last one."','more difficult / than','difficulter / than','the most difficult / than','more difficult / that','A'),
    mc(8,'Superlative of "modern":','the modernestt','modernest','the most modern','more modern','C'),
    mc(9,'Complete: "The ___ (early) you start, the ___ (good) your chances."','earlier / better','more early / gooder','earliest / best','earlier / best','A'),
    mc(10,'Complete: "She runs ___ (fast) than anyone else on the team."','more fast','the fastest','faster','most fast','C'),
    tf(11,'One-syllable adjectives form comparatives by adding -er.','true'),
    tf(12,'"More bigger" is correct.','false'),
    tf(13,'"The earlier, the better" uses comparative correctly.','true'),
    fb(14,'This road is ___ (long) than the other. That mountain is ___ (high) in the range.','longer, the highest'),
    fb(15,'She is ___ (good) player on the team. He is ___ (bad) at punctuation.','the best, the worst'),
  ]},

  'cea99dcd-7291-4ae5-878d-2bdcd0ea86eb':{pass_threshold:70,questions:[  // Adverbs of Degree
    mc(1,'"Very" is an adverb of:','frequency','manner','degree','time','C'),
    mc(2,'Choose correct: "She is ___ tired to continue."','very','too','so','enough','B'),
    mc(3,'Complete: "He speaks English ___ well." (extremely)','very','too','enough','fairly','A'),
    mc(4,'"Too" implies:','a positive degree','more than needed or desired','not enough','a neutral degree','B'),
    mc(5,'Complete: "She isn\'t ___ experienced to lead the project." (not sufficiently)','very','too','so','enough','D'),
    mc(6,'Choose correct: "The coffee is ___ hot to drink right now."','very','enough','too','quite','C'),
    mc(7,'Complete: "He is ___ clever — everyone admires him." (really)','too','enough','quite','so','D'),
    mc(8,'"Fairly" implies:','completely','extremely','moderately / to a reasonable degree','not at all','C'),
    mc(9,'Complete: "She is ___ talented, but she needs more practice." (to some degree)','too','enough','quite / fairly','very much','C'),
    mc(10,'Choose correct: "I am ___ tired today — I can barely move." (extremely)','fairly','quite','too','extremely','D'),
    tf(11,'"Too" has a negative meaning — more than what is good or needed.','true'),
    tf(12,'"She is enough tall to reach the shelf" is correct.','false'),
    tf(13,'"Quite" and "fairly" both suggest a moderate degree.','true'),
    fb(14,'It is ___ (too/very) hot to go outside. She is ___ (quite/very) good at maths.','too, quite / very'),
    fb(15,'He is ___ (enough) experienced — he has 10 years of practice. The film was ___ (extremely) boring.','enough / sufficiently, extremely'),
  ]},

  'dab52742-86a8-48f2-a932-96ace8915c2e':{pass_threshold:70,questions:[  // Subjunctive Mood — Wish/If Only intro
    mc(1,'Complete: "I wish I ___ (speak) Spanish." (I don\'t speak it now)','spoke','speak','will speak','am speaking','A'),
    mc(2,'Complete: "If only she ___ (be) here right now." (she\'s not)','is','was/were','will be','has been','B'),
    mc(3,'"I wish" + past simple expresses:','a real condition','a regret about the present','a future hope','a past fact','B'),
    mc(4,'Complete: "He wishes he ___ (have) more time."','has','will have','had','is having','C'),
    mc(5,'Complete: "If only I ___ (not/say) that — it was rude."','didn\'t say','don\'t say','hadn\'t said','won\'t say','C'),
    mc(6,'Which expresses a wish about the present?','I wish I went there.','I wish I could go there.','I wish I had gone there.','I wish I will go there.','B'),
    mc(7,'Complete: "She wishes she ___ (know) the answer."','knows','will know','knew','has known','C'),
    mc(8,'"If only" has ___ meaning than "I wish":','a weaker','a stronger/more emphatic','an opposite','exactly the same','B'),
    mc(9,'Complete: "I wish I ___ (can) fly!" (impossible wish)','can','could','will','am','B'),
    mc(10,'Complete: "If only they ___ (arrive) on time yesterday!"','arrive','will arrive','arrived','had arrived','D'),
    tf(11,'"I wish I spoke French" expresses a wish about the present — I don\'t speak French.','true'),
    tf(12,'"I wish I will go" is correct.','false'),
    tf(13,'"If only" is used to express stronger regret or a stronger wish.','true'),
    fb(14,'I wish I ___ (know) how to dance. If only she ___ (be) here with us now.','knew, were / was'),
    fb(15,'He wishes he ___ (have) more money. If only they ___ (not/leave) so early.','had, hadn\'t left'),
  ]},

  '58cf6042-000a-446c-8464-5b94d44df1ee':{pass_threshold:70,questions:[  // Clause Patterns
    mc(1,'In the sentence "She gave him a book", the indirect object is:','She','gave','him','book','C'),
    mc(2,'What is the subject complement in "She became a doctor"?','She','became','a doctor','There is none','C'),
    mc(3,'Identify the adverbial in "She works hard every day":','She','works','hard','every day','D'),
    mc(4,'Which pattern is SVO?','She is tired.','She runs fast.','She reads novels.','She became a nurse.','C'),
    mc(5,'Which pattern is SVC (subject + verb + complement)?','She reads novels.','She is a teacher.','She gave him a book.','She runs quickly.','B'),
    mc(6,'What is the object in "He sent her a letter"?','He','sent','her','a letter','D'),
    mc(7,'Identify the adverbial phrase: "We met at the café."','We','met','at the café','There is none','C'),
    mc(8,'Which sentence has pattern SVOO (two objects)?','She runs fast.','She is happy.','She gave him a present.','She became a doctor.','C'),
    mc(9,'The complement in "The soup tastes delicious" is:','The soup','tastes','delicious','There is none','C'),
    mc(10,'Which is a linking verb?','run','eat','seem','write','C'),
    tf(11,'In English, the subject usually comes before the verb.','true'),
    tf(12,'A complement describes or renames the object.','false'),
    tf(13,'"She seems tired" contains a linking verb and a subject complement.','true'),
    fb(14,'Identify: "She ___ (verb) him ___ (IO) a gift ___ (DO)." Pattern = S-V-IO-DO','gave, him, a gift'),
    fb(15,'"The coffee tastes ___." — "tastes" is a ___ verb; "bitter" is a subject ___.','bitter, linking, complement'),
  ]},

  'a3af0a3e-b572-4d48-abf0-af326c66f951':{pass_threshold:80,questions:[  // Module 1 Review
    mc(1,'Present Perfect: "She ___ (visit) Paris twice."','visited','visits','has visited','had visited','C'),
    mc(2,'Which signals Present Perfect?','yesterday','last week','in 2010','already','D'),
    mc(3,'Complete: "I have lived here ___ 2019."','for','during','since','ago','C'),
    mc(4,'Complete: "She has worked there ___ five years."','since','ago','during','for','D'),
    mc(5,'Use Past Simple for:','life experiences','recent events','actions at a specific stated past time','events connected to now','C'),
    mc(6,'Correct sentence:','I have seen him yesterday.','I saw him yesterday.','I have saw him.','I seen him.','B'),
    mc(7,'Comparative of "expensive":','more expensive','expensiver','most expensive','the most expensive','A'),
    mc(8,'Superlative of "good":','the goodest','the most good','the better','the best','D'),
    mc(9,'"Too" implies:','a positive degree','more than needed','not enough','a neutral degree','B'),
    mc(10,'Complete: "She is ___ tired to continue."','very','too','so','enough','B'),
    mc(11,'"I wish" + past simple expresses:','a real condition','a regret about the present','a future hope','a past fact','B'),
    mc(12,'Complete: "I wish I ___ (speak) French." (I can\'t)','speak','spoke','will speak','am speaking','B'),
    mc(13,'Which is an SVC pattern?','She reads novels.','She is a teacher.','She gave him a book.','She runs quickly.','B'),
    mc(14,'What is the complement in "He became a lawyer"?','He','became','a lawyer','There is none','C'),
    mc(15,'Complete: "She has known him ___ they were children."','for','during','since','ago','C'),
    tf(16,'"I have seen him yesterday" is correct.','false'),
    tf(17,'"For" is used with a period of time; "since" with a point in time.','true'),
    tf(18,'"I wish I could fly" is a correct wish about an impossible situation.','true'),
    fb(19,'She ___ (win, PP) three medals. She ___ (win, PS) the final last year.','has won, won'),
    fb(20,'I wish I ___ (know) the answer. If only she ___ (be) here now.','knew, were'),
  ]},

  // ═══ MODULE 2: Understanding the World ═══

  '52ad5399-9e29-49a0-a872-20125300fdb2':{pass_threshold:70,questions:[  // Passive Voice intro
    mc(1,'Passive voice is formed with:','subject + have + past participle','subject + be + past participle','subject + do + past participle','subject + will + past participle','B'),
    mc(2,'Change to passive: "They built this bridge in 1990."','This bridge was built in 1990.','This bridge built in 1990.','This bridge is built in 1990.','This bridge has been built in 1990.','A'),
    mc(3,'Why do we use passive voice?','When the subject is obvious or unknown','When we want to emphasise the doer','Only in questions','Only in the past','A'),
    mc(4,'Complete: "The report ___ (write) by the manager."','wrote','writes','was written','is written','C'),
    mc(5,'Change to passive: "Someone stole my bike."','My bike stole.','My bike was stolen.','My bike is stolen.','My bike has stolen.','B'),
    mc(6,'Complete: "English ___ (speak) all over the world." (present, general fact)','spoke','is spoken','speaks','was spoken','B'),
    mc(7,'Complete: "The letter ___ (send) yesterday."','sent','sends','was sent','is sent','C'),
    mc(8,'Choose the passive sentence:','She cooked dinner.','Dinner was cooked.','She is cooking dinner.','She will cook dinner.','B'),
    mc(9,'Complete: "The news ___ (broadcast) every evening."','broadcast','is broadcast','broadcasts','was broadcasting','B'),
    mc(10,'Change to passive: "A dog bit him."','He was bitten by a dog.','He bitten by a dog.','He is bitten by a dog.','A dog was bitten by him.','A'),
    tf(11,'Passive voice is formed with "be" + past participle.','true'),
    tf(12,'"The book wrote by Tolkien" is correct passive.','false'),
    tf(13,'We use passive when the agent (doer) is unknown or unimportant.','true'),
    fb(14,'The Eiffel Tower ___ (build) in 1889. It ___ (visit) by millions of tourists every year.','was built, is visited'),
    fb(15,'English ___ (speak, present passive) worldwide. This road ___ (repair, past passive) last year.','is spoken, was repaired'),
  ]},

  '44a9d11e-7977-4070-a5b2-ceb4a39a26fa':{pass_threshold:70,questions:[  // Passive Voice Present
    mc(1,'Present Simple Passive is formed with:','am/is/are + past participle','have/has + past participle','was/were + past participle','will + past participle','A'),
    mc(2,'Choose correct: "Rice ___ (grow) in many Asian countries."','grew','grows','is grown','has grown','C'),
    mc(3,'Complete: "The office ___ (clean) every morning."','cleans','is cleaned','was cleaned','has cleaned','B'),
    mc(4,'Change to passive: "They produce oil here."','Oil produces here.','Oil is produced here.','Oil was produced here.','Oil produced here.','B'),
    mc(5,'Complete: "These cars ___ (make) in Germany."','make','made','are made','have made','C'),
    mc(6,'Choose the passive present:','She wrote the report.','The report is written by her.','She writes the report.','She is writing the report.','B'),
    mc(7,'Complete: "The results ___ (publish) online every week."','publish','published','are published','were published','C'),
    mc(8,'Change to passive: "They speak French in this region."','French spoken in this region.','French is spoken in this region.','French was spoken here.','French speaks here.','B'),
    mc(9,'Complete: "The data ___ (analyse) by a team of experts."','analyse','analyses','is analysed','was analysed','C'),
    mc(10,'Which sentence is in Present Passive?','The manager wrote the report.','The report is written by the manager.','The manager writes reports.','The report was written.','B'),
    tf(11,'Present Simple Passive uses am/is/are + past participle.','true'),
    tf(12,'"Rice are grown in Asia" is correct.','false'),
    tf(13,'We can use "by + agent" in the passive to show who did the action.','true'),
    fb(14,'Coffee ___ (grow, present passive) in Ethiopia. It ___ (export, present passive) to many countries.','is grown, is exported'),
    fb(15,'These products ___ (make, present passive) locally. They ___ (sell, present passive) worldwide.','are made, are sold'),
  ]},

  '95c453dc-7eb3-4b15-a880-1aa8a200c337':{pass_threshold:70,questions:[  // Articles in Context
    mc(1,'Complete: "She bought ___ car. ___ car is red."','a / A','an / The','a / The','the / A','C'),
    mc(2,'Complete: "___ Nile is the longest river in the world."','A','An','The','No article','C'),
    mc(3,'Complete: "I play ___ tennis every weekend." (sport)','a','an','the','no article','D'),
    mc(4,'Complete: "He is ___ honest man."','a','an','the','no article','B'),
    mc(5,'Complete: "She is studying at ___ university." (general concept)','a','an','the','no article','D'),
    mc(6,'Complete: "Can you pass me ___ salt, please?" (the salt on the table)','a','an','the','no article','C'),
    mc(7,'Complete: "___ Himalayas are in Asia."','A','An','The','No article','C'),
    mc(8,'Complete: "I love ___ music." (music in general)','a','an','the','no article','D'),
    mc(9,'Complete: "He plays ___ piano." (musical instruments)','a','an','the','no article','C'),
    mc(10,'Complete: "___ President gave a speech." (specific, known)','A','An','The','No article','C'),
    tf(11,'We use "the" for unique things (the sun, the moon, the Eiffel Tower).','true'),
    tf(12,'"She plays a piano" is correct.','false'),
    tf(13,'"A" is used before consonant sounds; "an" before vowel sounds.','true'),
    fb(14,'I saw ___ (a/the) film last night. ___ (A/The) film was very moving.','a, The'),
    fb(15,'___ (The/A) Pacific Ocean is ___ (the/a) largest ocean. I love ___ (the/no article) swimming.','The, the, no article'),
  ]},

  'c5f70b32-e785-4679-86dc-1076fb8f0b54':{pass_threshold:70,questions:[  // Gerunds & Infinitives
    mc(1,'Complete: "She enjoys ___ (swim)."','swim','swims','swimming','to swimming','C'),
    mc(2,'Complete: "He decided ___ (leave) early."','leaving','leave','to leave','left','C'),
    mc(3,'Complete: "They avoided ___ (talk) about it."','to talk','talk','talked','talking','D'),
    mc(4,'Complete: "She promised ___ (call) me."','calling','call','to call','called','C'),
    mc(5,'Which verb is followed by gerund only?','want','decide','enjoy','plan','C'),
    mc(6,'Which verb is followed by infinitive only?','enjoy','avoid','finish','refuse','D'),
    mc(7,'Complete: "He stopped ___ (smoke) last year."','to smoke','smokes','smoking','smoke','C'),
    mc(8,'Complete: "I forgot ___ (lock) the door." (I didn\'t lock it)','locking','lock','locked','to lock','D'),
    mc(9,'Complete: "She is good at ___ (negotiate)."','to negotiate','negotiate','negotiating','negotiation','C'),
    mc(10,'Which is correct?','He wants go to Paris.','He wants going to Paris.','He wants to go to Paris.','He wanting to go.','C'),
    tf(11,'"Enjoy" is always followed by the gerund (-ing form).','true'),
    tf(12,'"She refused going" is grammatically correct.','false'),
    tf(13,'After prepositions we always use the gerund.','true'),
    fb(14,'She enjoys ___ (read). He promised ___ (help) me.','reading, to help'),
    fb(15,'They finished ___ (discuss) the plan. She decided ___ (apply) for the job.','discussing, to apply'),
  ]},

  'd1d6f408-8992-48c3-95b0-e882863a9bc0':{pass_threshold:70,questions:[  // Idioms & Expressions
    mc(1,'What does "break a leg" mean?','to injure yourself','good luck','to break something','to run fast','B'),
    mc(2,'What does "hit the nail on the head" mean?','to hammer something','to be exactly right','to make a mistake','to work hard','B'),
    mc(3,'What does "it\'s raining cats and dogs" mean?','animals are falling','it\'s raining very heavily','it\'s a light rain','cats and dogs are fighting','B'),
    mc(4,'What does "under the weather" mean?','outdoors','feeling ill/unwell','in bad weather','confused','B'),
    mc(5,'What does "bite the bullet" mean?','to eat something hard','to endure something painful/difficult','to argue','to give up','B'),
    mc(6,'What does "cost an arm and a leg" mean?','to be free','to be very cheap','to be very expensive','to cost exactly $1','C'),
    mc(7,'What does "the ball is in your court" mean?','it is your turn to play sport','it is now your responsibility to act','the ball has landed somewhere','you have won','B'),
    mc(8,'What does "once in a blue moon" mean?','every month','very rarely','every full moon','very often','B'),
    mc(9,'What does "spill the beans" mean?','to drop something','to reveal a secret','to cook food','to make a mess','B'),
    mc(10,'What does "burning the midnight oil" mean?','starting a fire','studying or working very late','lighting a lamp','being very tired','B'),
    tf(11,'Idioms should be interpreted literally word by word.','false'),
    tf(12,'"Break a leg" is a way of wishing someone good luck.','true'),
    tf(13,'"It\'s raining cats and dogs" means it is raining very hard.','true'),
    fb(14,'"Under the ___ (weather)" means feeling ill. "Once in a blue ___" means very rarely.','weather, moon'),
    fb(15,'"Break a ___" means good luck. "Spill the ___" means reveal a secret.','leg, beans'),
  ]},

  '8efefc1a-b7c5-4854-a3de-756b516291b5':{pass_threshold:70,questions:[  // Word Order Advanced — Inversion & Fronting
    mc(1,'What is inversion in English grammar?','placing the verb before the subject','placing the object before the verb','using passive voice','adding a negative particle','A'),
    mc(2,'Choose correct inversion: "Never ___ I seen such a beautiful sunset."','have','did','had','was','A'),
    mc(3,'Complete with inversion: "Rarely ___ she complain about anything."','she does','does she','she is','is she','B'),
    mc(4,'What is "fronting" in grammar?','moving an element to the front of a sentence for emphasis','moving the verb to the end','using the passive','inverting subject and object','A'),
    mc(5,'Complete: "Not only ___ she speak French, but she also speaks Italian."','she does','she is','does she','is she','C'),
    mc(6,'Choose correct: "Only then ___ we realise the mistake."','we did','did we','we had','had we','B'),
    mc(7,'Complete: "Hardly ___ she left when it started raining."','she had','had she','she did','did she','B'),
    mc(8,'Which sentence uses fronting for emphasis?','She never gives up.','Never does she give up.','She does not give up.','She gives up never.','B'),
    mc(9,'Complete: "So tired ___ she that she fell asleep immediately."','was','she was','is','she is','A'),
    mc(10,'Choose correct: "Seldom ___ he arrive on time."','he does','does he','he is','is he','B'),
    tf(11,'Inversion often occurs after negative adverbials (never, rarely, seldom).','true'),
    tf(12,'"Never I have seen such beauty" is correct inversion.','false'),
    tf(13,'Fronting moves an element to the start of a sentence for emphasis or style.','true'),
    fb(14,'Never ___ (have) I tasted such food. Rarely ___ (does) she complain.','have, does'),
    fb(15,'Not only ___ (does) he speak Arabic, but he ___ (also) speaks Persian.','does, also'),
  ]},

  '15d12772-c580-4bb4-b9b1-2ba06152f81d':{pass_threshold:70,questions:[  // American English
    mc(1,'What is the American English spelling of "colour"?','colour','color','coulor','coler','B'),
    mc(2,'What is the American English spelling of "centre"?','center','centere','centre','centr','A'),
    mc(3,'What is the American English word for "lift" (in a building)?','lifter','rise','elevator','escalator','C'),
    mc(4,'What is the American English word for "biscuit"?','biscuit','cake','cookie','cracker','C'),
    mc(5,'What is the British English word for "apartment"?','flat','room','studio','apartment','A'),
    mc(6,'What is the American English spelling of "favourite"?','favourite','favurite','favorite','favorit','C'),
    mc(7,'What is the American English word for "rubbish" (waste)?','rubbish','garbage/trash','litter','waste','B'),
    mc(8,'What is the American English word for "motorway"?','freeway/highway','motorway','expressway','speedway','A'),
    mc(9,'What is the American English spelling of "organise"?','organise','organise','organize','organisze','C'),
    mc(10,'What is the American English word for "autumn"?','autumn','fall','harvest','season','B'),
    tf(11,'American English uses "-ize" (organize) where British English uses "-ise" (organise).','true'),
    tf(12,'"Colour" is the American English spelling.','false'),
    tf(13,'"Elevator" is the American English word for "lift".','true'),
    fb(14,'British: "colour" → American: "___". British: "centre" → American: "___".','color, center'),
    fb(15,'British: "biscuit" → American: "___". British: "autumn" → American: "___".','cookie, fall'),
  ]},

  '7ffb3805-7dcb-4c8d-b553-17f38b3e2114':{pass_threshold:80,questions:[  // Module 2 Review
    mc(1,'Passive formed with:','subject + have + pp','subject + be + pp','subject + do + pp','subject + will + pp','B'),
    mc(2,'Change to passive: "They built this bridge in 1990."','This bridge was built in 1990.','This bridge built in 1990.','This bridge is built in 1990.','This bridge has been built.','A'),
    mc(3,'Present Passive: "Rice ___ (grow) in Asia."','grew','grows','is grown','has grown','C'),
    mc(4,'Complete: "She bought ___ car. ___ car is red."','a/A','an/The','a/The','the/A','C'),
    mc(5,'Complete: "___ Nile is the longest river."','A','An','The','No article','C'),
    mc(6,'Complete: "She enjoys ___ (swim)."','swim','swims','swimming','to swimming','C'),
    mc(7,'Complete: "He decided ___ (leave) early."','leaving','leave','to leave','left','C'),
    mc(8,'What does "break a leg" mean?','injure yourself','good luck','break something','run fast','B'),
    mc(9,'What does "cost an arm and a leg" mean?','be free','be cheap','be very expensive','cost exactly $1','C'),
    mc(10,'Correct inversion: "Never ___ I seen such a sunset."','have','did','had','was','A'),
    mc(11,'American English spelling of "colour":','colour','color','coulor','coler','B'),
    mc(12,'American word for "lift" (building):','lifter','rise','elevator','escalator','C'),
    mc(13,'Complete: "The results ___ (publish, present passive) online."','publish','published','are published','were published','C'),
    mc(14,'Complete: "She avoided ___ (talk) about it."','to talk','talk','talked','talking','D'),
    mc(15,'Complete: "___ she plays tennis every weekend." (sport — no article)','A','An','The','No article','D'),
    tf(16,'"The book wrote by Tolkien" is correct passive.','false'),
    tf(17,'After prepositions we always use the gerund.','true'),
    tf(18,'"Elevator" is the American English word for "lift".','true'),
    fb(19,'English ___ (speak, present passive) worldwide. Cars ___ (make, present passive) in Germany.','is spoken, are made'),
    fb(20,'Never ___ (have) I tasted such food. She enjoys ___ (read) every evening.','have, reading'),
  ]},

  // ═══ MODULE 3: Language Structure I ═══

  '7cefb47d-49dd-45bf-aef4-a0643f2e48db':{pass_threshold:70,questions:[  // Zero & First Conditional
    mc(1,'Zero Conditional is used for:','imaginary situations','general truths and facts','future possibilities','regrets','B'),
    mc(2,'First Conditional is used for:','general truths','imaginary present situations','real/possible future situations','past regrets','C'),
    mc(3,'Complete (Zero): "If you ___ (heat) water to 100°C, it ___ (boil)."','heat / boils','heated / boiled','heat / will boil','would heat / boils','A'),
    mc(4,'Complete (First): "If she ___ (study) hard, she ___ (pass) the exam."','studied / would pass','studies / will pass','study / will pass','studies / pass','B'),
    mc(5,'Choose the correct First Conditional:','If it will rain, I stay home.','If it rains, I will stay home.','If it rained, I would stay home.','If it rains, I stayed home.','B'),
    mc(6,'Choose the correct Zero Conditional:','If you freeze water, it becomes ice.','If you freeze water, it will become ice.','If you froze water, it becomes ice.','If you freeze water, it became ice.','A'),
    mc(7,'Complete (First): "___ she call you if she ___ (need) help?"','Would / needed','Will / needs','Does / will need','Will / need','B'),
    mc(8,'Complete (Zero): "Plants ___ (die) if they ___ (not/get) water."','die / don\'t get','would die / didn\'t get','died / don\'t get','die / won\'t get','A'),
    mc(9,'Which is a First Conditional?','If I were rich, I would travel.','If I am rich, I travel.','If I am rich, I will travel.','If I had been rich, I would have travelled.','C'),
    mc(10,'Complete: "If the weather ___ (be) good tomorrow, we ___ (go) to the beach."','is / will go','was / would go','will be / go','is / go','A'),
    tf(11,'Zero Conditional uses present simple in both clauses.','true'),
    tf(12,'First Conditional uses past simple in the if-clause.','false'),
    tf(13,'"If it rains, I will stay home" is a correct First Conditional.','true'),
    fb(14,'Zero: "If you ___ (mix) red and blue, you ___ (get) purple."','mix, get'),
    fb(15,'First: "If she ___ (study), she ___ (pass) the test."','studies, will pass'),
  ]},

  '2d6ea3e6-6e7b-4e15-a29a-855fca910851':{pass_threshold:70,questions:[  // Second Conditional
    mc(1,'Second Conditional is used for:','general truths','real future possibilities','imaginary or unlikely present/future situations','past regrets','C'),
    mc(2,'How is Second Conditional formed?','If + present simple, will + base verb','If + past simple, would + base verb','If + present perfect, would + base verb','If + past perfect, would have + pp','B'),
    mc(3,'Complete: "If I ___ (be) rich, I ___ (travel) the world."','am / will travel','was/were / would travel','were / will travel','am / would travel','B'),
    mc(4,'Choose the correct Second Conditional:','If she studied harder, she will pass.','If she studied harder, she would pass.','If she studies harder, she would pass.','If she had studied harder, she would pass.','B'),
    mc(5,'Complete: "What ___ you ___ (do) if you ___ (win) the lottery?"','would / do / win','would / do / won','will / do / win','would / did / won','B'),
    mc(6,'Why do we use "were" for all persons in Second Conditional?','It\'s a grammar error','It is formal/subjunctive use — "was" is also accepted informally','Only "was" is correct','It depends on the subject','B'),
    mc(7,'Complete: "If he ___ (know) the answer, he ___ (tell) us."','knows / will tell','knew / would tell','know / would tell','knew / will tell','B'),
    mc(8,'Choose correct:','If I were a bird, I would fly south.','If I was a bird, I will fly south.','If I am a bird, I would fly.','If I were a bird, I will fly south.','A'),
    mc(9,'Complete: "She ___ (be) happier if she ___ (have) more free time."','would be / had','will be / has','would be / has','is / had','A'),
    mc(10,'Which is NOT a Second Conditional?','If I had a car, I would drive to work.','If it were warmer, we would go outside.','If she studies, she will pass.','If he knew, he would tell us.','C'),
    tf(11,'Second Conditional uses past simple in the if-clause.','true'),
    tf(12,'"If I would be rich, I would travel" is correct.','false'),
    tf(13,'Second Conditional describes situations that are unreal or unlikely.','true'),
    fb(14,'If I ___ (be) president, I ___ (change) many things.','were, would change'),
    fb(15,'What ___ (would) you do if you ___ (find) a wallet in the street?','would, found'),
  ]},

  '8cca6f6a-e0e6-4471-8f12-461b9142375e':{pass_threshold:70,questions:[  // Wishes & Regrets
    mc(1,'Complete: "I wish I ___ (speak) Chinese." (I can\'t)','spoke','speak','will speak','am speaking','A'),
    mc(2,'Complete: "If only I ___ (not/say) that — it was wrong."','didn\'t say','don\'t say','hadn\'t said','won\'t say','C'),
    mc(3,'"I wish" + past simple expresses:','a regret about the past','a wish about the present situation','a hope for the future','a real condition','B'),
    mc(4,'"I wish" + past perfect expresses:','a wish about the present','a regret about a past event','a future hope','a present fact','B'),
    mc(5,'Complete: "She wishes she ___ (study) harder when she was young."','studied','studies','had studied','would study','C'),
    mc(6,'Complete: "I wish I ___ (can) help you more."','can','could','will','am','B'),
    mc(7,'Which expresses a regret about the past?','I wish I knew the answer.','I wish I could help.','I wish I had studied more.','I wish I were taller.','C'),
    mc(8,'Complete: "If only they ___ (arrive) earlier — we missed them!"','arrive','arrived','had arrived','would arrive','C'),
    mc(9,'Complete: "He wishes he ___ (not/spend) so much money last month."','didn\'t spend','hadn\'t spent','doesn\'t spend','won\'t spend','B'),
    mc(10,'Choose correct:','I wish I had more time now.','I wish I have more time.','I wish I would have more time.','I wish I will have more time.','A'),
    tf(11,'"I wish I spoke French" expresses a present wish (I don\'t speak French).','true'),
    tf(12,'"I wish I had gone" refers to a wish about the present.','false'),
    tf(13,'"If only" and "I wish" both express regret but "if only" is stronger.','true'),
    fb(14,'I wish I ___ (know) more about history. If only I ___ (study) harder at school.','knew, had studied'),
    fb(15,'She wishes she ___ (not/quit) her job. He wishes he ___ (be) taller.','hadn\'t quit, were'),
  ]},

  '202b163a-d0fa-401a-bb2f-7eec6014f21c':{pass_threshold:70,questions:[  // Reported Speech — Statements
    mc(1,'Change to reported speech: He said, "I am tired."','He said he is tired.','He said he was tired.','He said he were tired.','He said I am tired.','B'),
    mc(2,'Change to reported speech: She said, "I will call you."','She said she will call me.','She said she would call me.','She said she calls me.','She said she called me.','B'),
    mc(3,'Change to reported speech: "I have finished," he said.','He said he finished.','He said he has finished.','He said he had finished.','He said he will finish.','C'),
    mc(4,'What changes in reported speech?','verb tenses shift back one tense','verb tenses stay the same','only pronouns change','only time expressions change','A'),
    mc(5,'Change to reported speech: "We are leaving now," they said.','They said they are leaving now.','They said they were leaving then.','They said we were leaving now.','They said they will leave then.','B'),
    mc(6,'Complete: She said she ___ (can) help us.','can','could','will','would','B'),
    mc(7,'Change: "I don\'t know," he said.','He said he doesn\'t know.','He said he didn\'t know.','He said I don\'t know.','He said he didn\'t knows.','B'),
    mc(8,'What happens to "will" in reported speech?','stays as will','changes to would','changes to could','changes to should','B'),
    mc(9,'Change: "I saw her yesterday," she said.','She said she saw her the previous day.','She said she sees her yesterday.','She said she had seen her the previous day.','She said she saw her yesterday.','C'),
    mc(10,'Complete: He told me he ___ (be) a student.','is','are','was','were','C'),
    tf(11,'In reported speech, "am/is/are" usually changes to "was/were".','true'),
    tf(12,'Tenses never change in reported speech.','false'),
    tf(13,'"Will" changes to "would" in reported speech.','true'),
    fb(14,'"I am happy," she said. → She said she ___ (be) happy.','was'),
    fb(15,'"I will come," he promised. → He promised he ___ (will) come.','would'),
  ]},

  'b2b3eb24-72c4-4f1a-acd8-579bf178d499':{pass_threshold:70,questions:[  // Reported Questions
    mc(1,'Change to reported question: "Where do you live?" she asked.','She asked where I live.','She asked where did I live.','She asked where I lived.','She asked where lived I.','C'),
    mc(2,'In reported questions, the word order is:','question word order (inverted)','normal statement order (no inversion)','same as direct question','depends on the question word','B'),
    mc(3,'Change: "Are you coming?" he asked.','He asked if I was coming.','He asked if I am coming.','He asked was I coming.','He asked I was coming.','A'),
    mc(4,'What word introduces a reported yes/no question?','what','where','if / whether','that','C'),
    mc(5,'Change: "What time does the film start?" she asked.','She asked what time did the film start.','She asked what time the film started.','She asked what time the film starts.','She asked what time start the film.','B'),
    mc(6,'Change: "Have you ever been to Japan?" he asked.','He asked if I have ever been to Japan.','He asked if I had ever been to Japan.','He asked had I ever been to Japan.','He asked whether I been to Japan.','B'),
    mc(7,'Complete: She asked me ___ I was ready.','that','what','if','when','C'),
    mc(8,'Change: "Why are you late?" the teacher asked.','The teacher asked why I was late.','The teacher asked why was I late.','The teacher asked why am I late.','The teacher asked why I am late.','A'),
    mc(9,'In reported questions, auxiliary "do/does/did" is:','kept','removed','moved to the end','changed to "would"','B'),
    mc(10,'Complete: He asked me ___ I liked the food.','that','what','whether','which','C'),
    tf(11,'Reported questions use normal statement word order (no inversion).','true'),
    tf(12,'"She asked where did I live" is correct reported speech.','false'),
    tf(13,'"If" or "whether" is used to introduce reported yes/no questions.','true'),
    fb(14,'"Do you like coffee?" → She asked me ___ I liked coffee.','if / whether'),
    fb(15,'"Where does he work?" → She asked ___ he worked.','where'),
  ]},

  'c9a42676-41cb-43cf-b775-c332ba969a21':{pass_threshold:70,questions:[  // Noun Clauses
    mc(1,'A noun clause functions as:','an adjective','a noun (subject, object, or complement)','an adverb','a verb','B'),
    mc(2,'Identify the noun clause: "I know that she left."','I know','that she left','I know that','she left','B'),
    mc(3,'Which word often introduces a noun clause?','who','because','that','since','C'),
    mc(4,'Complete: "She believes ___ he is honest."','where','when','that','because','C'),
    mc(5,'Which sentence contains a noun clause?','She left because she was tired.','I think that he is right.','The man who called was her father.','She left when it got dark.','B'),
    mc(6,'Complete: "Do you know ___ the meeting starts?"','why','that','when','which','C'),
    mc(7,'Complete: "The fact ___ she passed surprised everyone."','when','how','that','which','C'),
    mc(8,'What is the subject in: "What he said surprised me."','What he said','surprised','me','he','A'),
    mc(9,'Complete: "I wonder ___ she will come."','that','if/whether','which','what','B'),
    mc(10,'Identify the noun clause: "She told me what she needed."','She told me','what she needed','she needed','told me what','B'),
    tf(11,'A noun clause can be the subject of a sentence.','true'),
    tf(12,'"That" can always be omitted in a noun clause without changing the meaning.','false'),
    tf(13,'"I know that she left" and "I know she left" are both correct.','true'),
    fb(14,'I believe ___ (that) he is telling the truth. Do you know ___ (where) she went?','that, where'),
    fb(15,'"___ (What) you said was very helpful." ___ (That) she passed surprised us.','What, That'),
  ]},

  '9bec3e6a-670e-4ed9-9127-0fbb91203b8c':{pass_threshold:70,questions:[  // Adverbial Clauses
    mc(1,'An adverbial clause modifies:','a noun','a verb, adjective, or whole clause','another adverb only','a pronoun','B'),
    mc(2,'Which word introduces an adverbial clause of time?','because','although','when/while/after','that','C'),
    mc(3,'Complete: "___ she was tired, she kept working."','Because','When','Although','That','C'),
    mc(4,'Complete: "He called me ___ he arrived."','although','because','since','as soon as','D'),
    mc(5,'Complete: "___ it was cold, she wore a coat."','Although','Because','When','Since','B'),
    mc(6,'Which introduces an adverbial clause of reason?','when','although','because/since/as','while','C'),
    mc(7,'Complete: "She studied hard ___ she could pass the exam."','although','unless','so that','since','C'),
    mc(8,'Complete: "He will wait ___ you are ready."','although','until','because','that','B'),
    mc(9,'Which introduces an adverbial clause of condition?','because','although','when','if/unless','D'),
    mc(10,'Complete: "___ you study, you won\'t pass." (negative condition)','If','Unless','Although','Because','B'),
    tf(11,'Adverbial clauses of concession often use "although" or "even though".','true'),
    tf(12,'"Because" introduces a clause of contrast.','false'),
    tf(13,'"Unless" means "if not".','true'),
    fb(14,'___ (Although/Because) she was tired, she finished the work. She succeeded ___ (because/although) she worked hard.','Although, because'),
    fb(15,'I will call you ___ (when/although) I arrive. ___ (Unless/Although) you hurry, you\'ll miss the bus.','when, Unless'),
  ]},

  '375a14b7-6cae-42b6-9787-c4d8f2ecd774':{pass_threshold:80,questions:[  // Module 3 Review
    mc(1,'Zero Conditional: "If you heat water, it ___ (boil)."','boils','will boil','boiled','would boil','A'),
    mc(2,'First Conditional: "If she studies, she ___ (pass)."','pass','passed','will pass','would pass','C'),
    mc(3,'Second Conditional: "If I ___ (be) rich, I would travel."','am','is','was/were','will be','C'),
    mc(4,'Choose correct Second Conditional:','If she studied harder, she will pass.','If she studied harder, she would pass.','If she studies harder, she would pass.','If she had studied, she would pass.','B'),
    mc(5,'"I wish" + past simple expresses:','regret about the past','wish about the present','future hope','real condition','B'),
    mc(6,'Complete: "I wish I ___ (speak) Japanese." (I can\'t)','speak','spoke','will speak','am speaking','B'),
    mc(7,'Reported: "I am tired," he said. → He said he ___ tired.','is','are','was','were','C'),
    mc(8,'"Will" in reported speech becomes:','will','shall','would','should','C'),
    mc(9,'Reported question: "Where do you live?" → She asked where I ___.','live','lived','do live','living','B'),
    mc(10,'In reported questions, the word order is:','inverted','normal statement order','depends on question word','same as direct','B'),
    mc(11,'A noun clause functions as:','an adjective','a noun','an adverb','a verb','B'),
    mc(12,'Complete: "I know ___ she left early."','where','when','that','because','C'),
    mc(13,'"Because" introduces a clause of:','contrast','condition','reason','time','C'),
    mc(14,'Complete: "___ she was tired, she kept working." (contrast)','Because','When','Although','That','C'),
    mc(15,'Complete: "___ you hurry, you\'ll miss the bus." (negative condition)','If','Unless','Although','Because','B'),
    tf(16,'First Conditional uses past simple in the if-clause.','false'),
    tf(17,'"If I would be rich" is correct Second Conditional.','false'),
    tf(18,'"If" or "whether" introduces reported yes/no questions.','true'),
    fb(19,'If I ___ (be, 2nd cond.) a bird, I would fly south. If it ___ (rain, 1st cond.), I will stay home.','were, rains'),
    fb(20,'"I have finished," he said. → He said he ___ finished. She asked where I ___.','had, lived'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'f88d9de0-a7d7-4319-a607-2bc7b8fe2e91',n:1,title:'Building Confidence'},
    {id:'2fb5648c-cda5-4434-a871-1a4c85509af7',n:2,title:'Understanding the World'},
    {id:'d14a754b-4bd0-4c36-ad69-c79bf4b01cf3',n:3,title:'Language Structure I'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 A2 Pre-Intermediate — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 1–3 A2 Pre-Intermediate`)
}
main().catch(e=>{console.error(e);process.exit(1)})
