/**
 * Seed quizzes for A1 Elementary — Modules 1, 2, 3.
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-a1e-mod1-3.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // ═══ MODULE 1: All About Me ═══

  'ad4c01d4-3483-444f-ae5c-40e97e6e7ba3':{pass_threshold:70,questions:[  // Talking About Yourself — To Be
    mc(1,'Complete (present): "She ___ a university student."','am','are','is','be','C'),
    mc(2,'Complete (past): "They ___ tired yesterday."','are','is','was','were','D'),
    mc(3,'Complete (future): "It ___ a beautiful day tomorrow."','is','was','will be','are','C'),
    mc(4,'Choose the correct negative (past): "He ___ at home last night."','wasn\'t','aren\'t','isn\'t','weren\'t','A'),
    mc(5,'Choose the correct question (past): "___ you at the party?"','Are','Is','Were','Was','C'),
    mc(6,'Complete: "I ___ born in 2001."','am','is','was','were','C'),
    mc(7,'Choose the correct sentence:','We was students.','We were students.','We are was students.','We is students.','B'),
    mc(8,'Complete: "She ___ a teacher in the future."','is','was','will be','are','C'),
    mc(9,'Short answer: "Were they happy?" — "Yes, ___."','Yes, they are.','Yes, they were.','Yes, they was.','Yes, they will.','B'),
    mc(10,'Complete: "There ___ a big storm last night."','is','are','was','were','C'),
    tf(11,'"Was" is used with I, he, she, it in the past.','true'),
    tf(12,'"They was late" is grammatically correct.','false'),
    tf(13,'"Will be" is used to form the future of the verb "to be".','true'),
    fb(14,'I ___ (be, present) a student. Last year I ___ (be, past) in high school.','am, was'),
    fb(15,'She ___ (be, past, negative) at school yesterday. Where ___ (be, past) she?','wasn\'t, was'),
  ]},

  'cefeb72c-a7c7-4e46-8ea7-820dafad3626':{pass_threshold:70,questions:[  // My Preferences — Like/Love/Hate + V-ing
    mc(1,'Choose the correct form: "She enjoys ___ (read)."','read','reads','reading','to reading','C'),
    mc(2,'Which sentence is correct?','He loves play tennis.','He loves to playing tennis.','He loves playing tennis.','He love playing tennis.','C'),
    mc(3,'Complete: "I don\'t mind ___ (wait) for you."','wait','waits','waited','waiting','D'),
    mc(4,'Which verb is NOT normally followed by -ing?','enjoy','finish','prefer','must','D'),
    mc(5,'Complete: "They hate ___ (get up) early on weekdays."','get up','gets up','got up','getting up','D'),
    mc(6,'"Prefer" can be followed by:','-ing or to-infinitive','only -ing','only to-infinitive','past tense','A'),
    mc(7,'Choose the correct sentence:','She prefers swimming to running.','She prefers swim to run.','She prefers to swimming rather running.','She prefer swimming to running.','A'),
    mc(8,'Complete: "Do you like ___ (cook) at home?"','cook','cooks','cooking','to cooking','C'),
    mc(9,'Which means "to not dislike something"?','love it','hate it','don\'t mind it','detest it','C'),
    mc(10,'Complete: "He can\'t stand ___ (sit) in traffic."','sit','sits','sat','sitting','D'),
    tf(11,'"Enjoy" is always followed by the gerund (-ing form).','true'),
    tf(12,'"I love to swim" and "I love swimming" are both correct.','true'),
    tf(13,'"She hates to wake up early" is grammatically incorrect.','false'),
    fb(14,'I love ___ (travel). She hates ___ (do) housework.','travelling, doing'),
    fb(15,'He prefers ___ (read) to ___ (watch) TV.','reading, watching'),
  ]},

  'd93735dc-56f7-4976-bcd5-a356798a774d':{pass_threshold:70,questions:[  // My Family & Home — Possessive Case & Adjectives
    mc(1,'Which is the correct possessive form?','my brothers car',"my brother's car",'my car brother','my brother car','B'),
    mc(2,'Choose the correct adjective: "She has ___ hair." (long + brown)','a long brown','long and brown','long, brown','long brown','D'),
    mc(3,'Where do adjectives go in English?','after the noun','after the verb only','before the noun','at the end','C'),
    mc(4,'Complete: "___ house is very modern." (they)','Their','There','Them','Theirs','A'),
    mc(5,'Which sentence uses possessive correctly?','The dog of my sister is cute.','My sister dog is cute.','My sister\'s dog is cute.','My sisters dog is cute.','C'),
    mc(6,'Choose the correct adjective order:','a wooden old table','an old wooden table','a wooden table old','old a wooden table','B'),
    mc(7,'Complete: "He has ___ eyes." (blue + big)','blue big','big blue','a big blue','big a blue','B'),
    mc(8,'Which is the possessive adjective for "we"?','us','our','ours','we','B'),
    mc(9,'Complete: "This is ___ (she) favourite book."','she','hers','her','herself','C'),
    mc(10,'Choose the correct sentence:','Their house are big.','Their house is big.','Them house is big.','They house is big.','B'),
    tf(11,'In English, adjectives usually come before the noun they describe.','true'),
    tf(12,'"Her\'s bag is on the table" is correct.','false'),
    tf(13,'We use an apostrophe + s to show possession: e.g. "Tom\'s car".','true'),
    fb(14,'This is ___ (my mother) bedroom. ___ (she) wardrobe is very big.','my mother\'s, Her'),
    fb(15,'He has a ___ (small, modern) flat. ___ (they) garden is ___ (beautiful, large).','small modern, Their, beautifully large / large and beautiful'),
  ]},

  '11dabe12-4356-4e57-b6bb-82d662508a33':{pass_threshold:70,questions:[  // Describing People — Object Pronouns
    mc(1,'What is the object pronoun for "I"?','my','me','mine','myself','B'),
    mc(2,'Replace "my teacher" with an object pronoun: "I respect my teacher."','I respect she.','I respect her.','I respect hers.','I respect herself.','B'),
    mc(3,'What is the object pronoun for "they"?','their','them','theirs','themselves','B'),
    mc(4,'Choose the correct sentence:','Can you help we?','Can you help us?','Can you help our?','Can you help ours?','B'),
    mc(5,'Complete: "She called ___ last night." (he)','his','he','him','himself','C'),
    mc(6,'What is the object pronoun for "you" (plural)?','your','yourselves','you','yours','C'),
    mc(7,'Which sentence is correct?','The teacher praised she.','The teacher praised her.','The teacher praised hers.','The teacher praised herself.','B'),
    mc(8,'Complete: "I saw ___ at the gym." (they)','their','they','theirs','them','D'),
    mc(9,'Describe someone using adjectives: "He is tall, ___."','talls and handsome','tall and handsome','tall handsome','a tall and handsome','B'),
    mc(10,'What is the object pronoun for "we"?','our','ours','us','ourselves','C'),
    tf(11,'Object pronouns come after the verb or preposition.','true'),
    tf(12,'"She" and "her" are both subject pronouns.','false'),
    tf(13,'"I gave him a present" uses "him" correctly as an object pronoun.','true'),
    fb(14,'I → ___ (object). He → ___ (object). She → ___ (object).','me, him, her'),
    fb(15,'She sent ___ (we) a message. I saw ___ (he) at the library.','us, him'),
  ]},

  '225491f8-b3e5-469b-8e63-b1f008f97d3f':{pass_threshold:70,questions:[  // Dates & Numbers — Ordinal Numbers
    mc(1,'What is the ordinal form of 1?','oneth','first','firsted','onest','B'),
    mc(2,'What is the ordinal form of 21?','twenty-oneth','twenty-first','twentyfirst','twenty-one','B'),
    mc(3,'How do you say "14th"?','fourteenth','fourthteen','fourteen','fourteeneth','A'),
    mc(4,'How do you say the date "5 March"?','March five','the fifth of March','March the five','the five of March','B'),
    mc(5,'What is the ordinal form of 12?','twelfth','twelveth','twelfteenth','twelvth','A'),
    mc(6,'Which is correct for "22nd"?','twenty-secondth','twenty-twoth','twenty-second','twenty-two','C'),
    mc(7,'What is the ordinal form of 9?','nineth','ninth','ninthly','nined','B'),
    mc(8,'How do we write "the third month of the year"?','March','March 3rd','the 3rd month','third month','A'),
    mc(9,'What is the ordinal form of 30?','thirtyth','thirtieth','thirty-eth','thirtiethly','B'),
    mc(10,'What is the ordinal form of 100?','hundredth','one-hundredth','hundredest','hundrededly','A'),
    tf(11,'"She lives on the fifth floor" uses an ordinal number correctly.','true'),
    tf(12,'The ordinal form of 8 is "eighteenth".','false'),
    tf(13,'We use ordinal numbers for dates: "the first of January".','true'),
    fb(14,'1st = ___, 3rd = ___, 12th = ___.','first, third, twelfth'),
    fb(15,'Today is the ___ (21) of May. She was born on the ___ (3) of April.','twenty-first, third'),
  ]},

  'c538683f-bfcd-4729-8d22-3eb2eba4e2ff':{pass_threshold:70,questions:[  // Reflexive Pronouns
    mc(1,'What is the reflexive pronoun for "I"?','meself','Iself','myself','myselves','C'),
    mc(2,'What is the reflexive pronoun for "they"?','theirselves','themself','theirself','themselves','D'),
    mc(3,'Choose the correct sentence:','He hurt him.','He hurt hisself.','He hurt himself.','He hurt he.','C'),
    mc(4,'What is the reflexive pronoun for "we"?','weselves','ourself','ourselves','usselves','C'),
    mc(5,'When do we use reflexive pronouns?','When subject and object are different','When subject and object are the same person','Only in past tense','Only in questions','B'),
    mc(6,'Complete: "She made this dress ___." (alone)','her','hers','herself','sheself','C'),
    mc(7,'What is the reflexive pronoun for "you" (singular)?','youself','yourself','yourselves','you','B'),
    mc(8,'Choose the correct sentence:','They enjoyed theirselves.','They enjoyed theirself.','They enjoyed themselves.','They enjoyed them.','C'),
    mc(9,'Reflexive pronouns can be used for emphasis. Which is correct?','I cooked dinner myself.','I cooked dinner meself.','I myself cooked dinner meself.','Myself I cooked dinner.','A'),
    mc(10,'What is the reflexive pronoun for "she"?','sheself','herselves','hisself','herself','D'),
    tf(11,'"Himself" is the reflexive pronoun for "he".','true'),
    tf(12,'"Theirselves" is the correct reflexive pronoun for "they".','false'),
    tf(13,'"I taught myself English" is a correct use of a reflexive pronoun.','true'),
    fb(14,'She introduced ___ (she) to the class. He fixed the car ___ (he).','herself, himself'),
    fb(15,'I → ___, you → ___, we → ___, they → ___.','myself, yourself, ourselves, themselves'),
  ]},

  'c9ded9a4-80c6-412b-b6d0-6460fb5f90b3':{pass_threshold:70,questions:[  // Pronunciation Advanced — Stress, Intonation, Connected Speech
    mc(1,'What is word stress?','saying every syllable equally loudly','emphasising one syllable in a word more than others','speaking very quickly','connecting words together','B'),
    mc(2,'Which syllable is stressed in "PHOtograph"?','second','third','first','none','C'),
    mc(3,'What does rising intonation at the end of a sentence usually signal?','a statement','a command','a yes/no question','anger','C'),
    mc(4,'What is "connected speech"?','speaking very slowly','the way words link together in natural speech','speaking word by word','using formal vocabulary','B'),
    mc(5,'In which word is the stress on the second syllable?','HAPpy','toDAY','SUnday','ENglish','B'),
    mc(6,'What happens to the "t" sound in "butter" in natural British English speech?','it is very clearly pronounced','it sounds like a "d" or is softened','it is completely silent','it sounds like "th"','B'),
    mc(7,'What does falling intonation at the end of a sentence usually signal?','a yes/no question','uncertainty','a statement or command','surprise','C'),
    mc(8,'Which word has stress on the LAST syllable?','teacher','happy','toDAY','morning','C'),
    mc(9,'"Gonna" is the informal pronunciation of:','going','want to','going to','got a','C'),
    mc(10,'What is the main stress in "unBElievable"?','first','second','third (BE)','fourth','C'),
    tf(11,'In English, the stressed syllable in a word is usually spoken louder and longer.','true'),
    tf(12,'All sentences in English end with rising intonation.','false'),
    tf(13,'"Wanna" is the informal pronunciation of "want to".','true'),
    fb(14,'The word "PHOtograph" has stress on the ___ syllable. "toDAY" has stress on the ___ syllable.','first, second'),
    fb(15,'Rising intonation is used in ___ questions. Falling intonation is used in ___.','yes/no, statements / commands'),
  ]},

  '3e8175c9-82b5-4ad4-b66b-8402f000cdba':{pass_threshold:80,questions:[  // Module 1 Review & Test
    mc(1,'Complete (past): "They ___ tired after the journey."','are','is','was','were','D'),
    mc(2,'Complete (future): "She ___ a doctor one day."','is','was','will be','are','C'),
    mc(3,'Choose: "She enjoys ___ (swim)."','swim','swims','swum','swimming','D'),
    mc(4,'Which is correct?','He loves play chess.','He loves playing chess.','He love playing chess.','He loves to playing chess.','B'),
    mc(5,'Which possessive is correct?','my brothers car',"my brother's car",'my car brother','my brother car','B'),
    mc(6,'Choose correct adjective order:','a wooden old table','old a wooden table','an old wooden table','a old wooden table','C'),
    mc(7,'What is the object pronoun for "she"?','her','hers','herself','she','A'),
    mc(8,'Complete: "She sent ___ (we) an email."','we','our','us','ours','C'),
    mc(9,'What is the ordinal form of 21?','twenty-oneth','twenty-first','twentyfirst','twentyone','B'),
    mc(10,'How do you say the date "3 April"?','April three','the third of April','April the three','the three of April','B'),
    mc(11,'What is the reflexive pronoun for "he"?','hisself','him','himself','his','C'),
    mc(12,'Complete: "She made this meal ___." (alone, no help)','her','hers','herself','sheself','C'),
    mc(13,'What does rising intonation signal?','a statement','a yes/no question','a command','certainty','B'),
    mc(14,'"Gonna" is the informal pronunciation of:','going','going to','got to','want to','B'),
    mc(15,'Complete: "___ (they) house is beautiful."','There','Them','Theirs','Their','D'),
    tf(16,'"Was" is used with I, he, she, it in the past simple of "to be".','true'),
    tf(17,'"I love to swim" and "I love swimming" are both correct.','true'),
    tf(18,'"Theirselves" is the correct reflexive pronoun for "they".','false'),
    fb(19,'She ___ (be, past) a student. Now she ___ (be, present) a teacher.','was, is'),
    fb(20,'He introduced ___ (he). They enjoyed ___ (they) at the concert.','himself, themselves'),
  ]},

  // ═══ MODULE 2: Daily Life ═══

  'bed57b66-f7d5-40b8-9992-b53adbf86db7':{pass_threshold:70,questions:[  // My Daily Routine — Present Simple
    mc(1,'Choose the correct form: "He ___ breakfast at 7 am."','eat','ate','eats','eating','C'),
    mc(2,'Which subject takes a verb WITHOUT -s?','she','he','they','it','C'),
    mc(3,'Choose the correct sentence:','She go to school by bus.','She goes to school by bus.','She going to school by bus.','She goed to school by bus.','B'),
    mc(4,'Complete: "My father ___ (work) at a hospital."','work','working','worked','works','D'),
    mc(5,'When do we use Present Simple?','For actions happening right now','For completed past actions','For habits and repeated actions','For actions in the near future','C'),
    mc(6,'Which is a time expression for Present Simple?','right now','at the moment','every morning','yesterday','C'),
    mc(7,'Complete: "She always ___ (brush) her teeth before bed."','brush','brushed','brushing','brushes','D'),
    mc(8,'Choose the correct question: "___ she walk to work?"','Is','Are','Does','Did','C'),
    mc(9,'Complete: "We ___ (have) lunch at noon."','has','having','had','have','D'),
    mc(10,'Complete: "The sun ___ (rise) in the east."','rise','rising','rised','rises','D'),
    tf(11,'In Present Simple, we add -s to the verb for he, she, it.','true'),
    tf(12,'"She go to work every day" is correct.','false'),
    tf(13,'Present Simple is used for general truths and habits.','true'),
    fb(14,'She ___ (wake) up at 6. He ___ (have) a shower every morning.','wakes, has'),
    fb(15,'___ (do/does) he walk to school? No, he ___ (not/walk) — he takes the bus.','Does, doesn\'t walk'),
  ]},

  '9687b13f-3cef-4f95-a826-0c04ad29ab44':{pass_threshold:70,questions:[  // How Often? — Adverbs of Frequency
    mc(1,'Where does an adverb of frequency usually go?','Before the subject','After the object','Before the main verb (after subject)','At the end of the sentence','C'),
    mc(2,'Which adverb means "100% of the time"?','usually','often','always','sometimes','C'),
    mc(3,'Choose the correct sentence:','She goes always to the gym.','Always she goes to the gym.','She always goes to the gym.','She goes to always the gym.','C'),
    mc(4,'Where does "always" go with the verb "to be"?','before "to be"','after "to be"','at the end','before the subject','B'),
    mc(5,'"Rarely" means:','50% of the time','75% of the time','almost never','always','C'),
    mc(6,'Complete: "He is ___ late for meetings." (he is never on time)','sometimes','often','rarely','always','D'),
    mc(7,'Choose the correct sentence with "to be":','She always is tired.','She is always tired.','Always she is tired.','She tired is always.','B'),
    mc(8,'Which question asks about frequency?','Where do you work?','What do you eat?','How often do you exercise?','Who is your teacher?','C'),
    mc(9,'Put correctly: "She / never / eats / meat."','Never she eats meat.','She never eats meat.','She eats never meat.','She eats meat never.','B'),
    mc(10,'Which means "more often than not, 75%"?','always','usually','sometimes','rarely','B'),
    tf(11,'Adverbs of frequency go after the main verb in most sentences.','false'),
    tf(12,'"He is never late" is correctly positioned.','true'),
    tf(13,'"Always" represents 100% frequency.','true'),
    fb(14,'I ___ (always) brush my teeth after meals. She ___ (never) drinks coffee.','always, never'),
    fb(15,'How ___ do you exercise? I go to the gym ___ a week. (three times)','often, three times'),
  ]},

  '795da8a0-026a-46e5-bbae-55185ab82046':{pass_threshold:70,questions:[  // Right Now — Present Continuous
    mc(1,'How do we form Present Continuous?','subject + verb-ed','subject + am/is/are + verb-ing','subject + will + verb','subject + has/have + verb','B'),
    mc(2,'Choose the correct sentence:','She is eat lunch.','She eating lunch.','She is eating lunch.','She are eating lunch.','C'),
    mc(3,'Complete: "They ___ (study) for the exam right now."','study','studies','are studying','is studying','C'),
    mc(4,'What is the -ing form of "make"?','makeing','maked','makes','making','D'),
    mc(5,'Complete: "I ___ (not/watch) TV at the moment."','don\'t watching','am not watching','isn\'t watching','not watching','B'),
    mc(6,'What is the -ing form of "lie"?','lieing','lie-ing','lying','lied','C'),
    mc(7,'Complete the question: "___ she ___ (work) from home today?"','Does / work','Is / working','Are / working','Do / working','B'),
    mc(8,'Which sentence is in Present Continuous?','She eats every day.','She is eating now.','She ate pizza.','She will eat.','B'),
    mc(9,'What is the -ing form of "swim"?','swiming','swammed','swimming','swims','C'),
    mc(10,'Choose the correct negative:','She isn\'t sleep.','She don\'t sleeping.','She isn\'t sleeping.','She not sleeping.','C'),
    tf(11,'"He is running" is correct Present Continuous.','true'),
    tf(12,'Present Continuous is formed with subject + verb + -ed.','false'),
    tf(13,'Some verbs like "know" and "want" are not normally used in Present Continuous.','true'),
    fb(14,'She ___ (write) a report right now. They ___ (not/watch) TV at the moment.','is writing, aren\'t watching'),
    fb(15,'___ you ___ (listen) to music? Yes, I ___.','Are, listening, am'),
  ]},

  '0d37f6fa-94a6-4d6d-b740-1d01850a76cb':{pass_threshold:70,questions:[  // Always or Now? — Present Simple vs Continuous
    mc(1,'Which describes a habit?','She is cooking now.','She cooks every day.','She was cooking.','She will cook.','B'),
    mc(2,'Which describes an action happening now?','He plays guitar.','He is playing guitar.','He played guitar.','He will play guitar.','B'),
    mc(3,'Choose the correct tense: "I ___ (read) a book right now."','read','reads','am reading','is reading','C'),
    mc(4,'Choose the correct tense: "She ___ (go) to the gym three times a week."','is going','are going','goes','going','C'),
    mc(5,'Which word signals Present Continuous?','always','usually','at the moment','every day','C'),
    mc(6,'Which word signals Present Simple?','now','right now','at the moment','often','D'),
    mc(7,'Which verb is NOT used in Present Continuous?','run','eat','belong','write','C'),
    mc(8,'Choose correct: "Look! The baby ___."','smiles','is smiling','smiled','will smile','B'),
    mc(9,'Choose correct: "I usually ___ coffee in the morning."','am drinking','drink','drinks','is drinking','B'),
    mc(10,'Which is correct?','He is knowing the answer.','He knows the answer.','He knowing the answer.','He know the answer now.','B'),
    tf(11,'"Now" and "at the moment" signal Present Continuous.','true'),
    tf(12,'"I am understanding" is correct English.','false'),
    tf(13,'"Always" and "every day" are signals for Present Simple.','true'),
    fb(14,'I ___ (read) every night. Right now I ___ (read) a novel.','read, am reading'),
    fb(15,'She ___ (work) at a hospital. Today she ___ (not/work) — it\'s a holiday.','works, isn\'t working'),
  ]},

  'fa95f39b-26fa-4f56-8ad1-0293858c71ec':{pass_threshold:70,questions:[  // Asking Questions — Question Word Order
    mc(1,'What is the correct word order for a question?','You where do live?','Where you do live?','Where do you live?','Where live you?','C'),
    mc(2,'Complete: "___ does she work?" — "In a bank."','When','What','Where','Who','C'),
    mc(3,'Which is correct?','What you do in the morning?','What do you do in the morning?','What you are doing?','Do what you do?','B'),
    mc(4,'Complete: "___ is your favourite subject?" — "English."','Where','Who','When','What','D'),
    mc(5,'Choose the correct Yes/No question:','Does she works here?','Do she work here?','Does she work here?','She does work here?','C'),
    mc(6,'"Why" asks about:','time','place','reason','person','C'),
    mc(7,'Complete: "___ do you go to work?" — "By bus."','When','How','Why','Who','B'),
    mc(8,'What is the correct question?','How are you?','How you are?','Are how you?','You how are?','A'),
    mc(9,'Complete: "___ does the lesson start?" — "At 9 am."','Where','What','When','Why','C'),
    mc(10,'Choose the correct question:','Who does she love?','Who she loves?','Who she does love?','Does who she love?','A'),
    tf(11,'In English questions, the auxiliary verb comes before the subject.','true'),
    tf(12,'"Where you live?" is correct English.','false'),
    tf(13,'"How often" asks about frequency.','true'),
    fb(14,'___ do you wake up? (time) ___ do you live? (place)','When, Where'),
    fb(15,'___ does he work? (place) ___ does she study English? (reason)','Where, Why'),
  ]},

  '07839e10-bae4-4c73-9a6d-63ad85036867':{pass_threshold:70,questions:[  // Negation Advanced — Never/Neither/Nor
    mc(1,'Which sentence correctly uses "never"?','I don\'t never eat meat.','I never eat meat.','I never don\'t eat meat.','Never I eat meat.','B'),
    mc(2,'"Never" = :','not always','not ever','not usually','not sometimes','B'),
    mc(3,'Complete: "She doesn\'t like coffee. ___ do I." (agreement in negative)','So','Neither','Either','Nor','B'),
    mc(4,'"Neither...nor" is used to:','connect two positives','show a choice','connect two negatives','show a result','C'),
    mc(5,'Choose the correct sentence:','I don\'t like tea, and neither does she.','I don\'t like tea, and so does she.','I don\'t like tea, neither she does.','I don\'t like tea, nor she does.','A'),
    mc(6,'Complete: "Neither my brother ___ my sister speaks Spanish."','or','and','nor','but','C'),
    mc(7,'Which sentence has a double negative error?','I never go there.','I don\'t never go there.','She never eats meat.','He never speaks loudly.','B'),
    mc(8,'Complete: "She ___ drinks alcohol." (0%, never)','always','sometimes','often','never','D'),
    mc(9,'Complete: "He doesn\'t study. ___ does his brother." (agreement)','So','Either','Neither','Both','C'),
    mc(10,'Choose the correct sentence:','Neither he or she came.','Neither he nor she came.','Neither he and she came.','Neither he but she came.','B'),
    tf(11,'"I don\'t never go there" contains a double negative and is incorrect in standard English.','true'),
    tf(12,'"Neither do I" expresses agreement with a negative statement.','true'),
    tf(13,'"Never" can be used with "don\'t" in the same clause in standard English.','false'),
    fb(14,'I ___ (never) watch horror films. ___ (neither) does my sister.','never, Neither'),
    fb(15,'Neither Tom ___ (nor/or) Anna was there. She doesn\'t like jazz, and ___ (neither/either) do I.','nor, neither'),
  ]},

  'fd5798aa-037a-4acd-9f8d-b97ae02603e3':{pass_threshold:70,questions:[  // Quantifiers Advanced — Both/Either/Neither/Enough/Too many
    mc(1,'"Both" refers to:','one of two things','neither of two things','two things together','more than two things','C'),
    mc(2,'"Either" means:','both options','one or the other (choice)','none of the options','all of them','B'),
    mc(3,'"Neither" means:','one of two','both of two','not one and not the other','some of them','C'),
    mc(4,'Complete: "I don\'t like ___ option. Both are bad."','either','neither','both','some','A'),
    mc(5,'Complete: "___ my parents speak English." (both of them)','Neither','Either','Both','Some','C'),
    mc(6,'"Enough" means:','too much','too little','the right amount','none','C'),
    mc(7,'Complete: "There are ___ students — the room is overcrowded."','enough','too few','too many','both','C'),
    mc(8,'Complete: "I don\'t have ___ time to finish this." (insufficient)','too many','enough','both','either','B'),
    mc(9,'Choose the correct sentence:','Both of them is correct.','Both of them are correct.','Both of them was correct.','Both of them be correct.','B'),
    mc(10,'Complete: "___ team played well. It was a draw."','Either','Neither','Both','Some','C'),
    tf(11,'"Both" is used with two things to say they are included together.','true'),
    tf(12,'"Either" always has a negative meaning.','false'),
    tf(13,'"Too many" is used with uncountable nouns.','false'),
    fb(14,'___ (both/either) my brothers can drive. I don\'t like ___ (either/neither) film.','Both, either'),
    fb(15,'She doesn\'t have ___ (enough) money. There are ___ (too many) cars on the road.','enough, too many'),
  ]},

  'e926095a-d90e-4e48-94c1-f67a68cb620a':{pass_threshold:80,questions:[  // Module 2 Review & Test
    mc(1,'Choose: "He ___ breakfast at 7 am every day."','eat','ate','eats','eating','C'),
    mc(2,'Choose: "She ___ (go) to the gym right now."','goes','went','is going','go','C'),
    mc(3,'Which signals Present Continuous?','always','usually','right now','every day','C'),
    mc(4,'Choose: "I ___ (read) every night. Right now I ___ (read) a novel."','read / am reading','reads / reads','am reading / read','read / reads','A'),
    mc(5,'Correct sentence:','She goes always to the gym.','She always goes to the gym.','Always she goes to the gym.','She goes to always the gym.','B'),
    mc(6,'"Rarely" means:','100%','75%','50%','almost never','D'),
    mc(7,'Correct question:','Where you do live?','Where do you live?','You where live?','Do where you live?','B'),
    mc(8,'Complete: "___ does she work?" — "In Almaty."','When','What','Where','Who','C'),
    mc(9,'"Never" = :','not always','not ever','not usually','not often','B'),
    mc(10,'Correct sentence:','I don\'t never go there.','I never go there.','I go there never.','Never I go there.','B'),
    mc(11,'"Both" refers to:','one of two','neither of two','two things together','more than two','C'),
    mc(12,'Complete: "There are ___ students — the room is overcrowded."','enough','too few','too many','both','C'),
    mc(13,'Correct sentence:','She is knowing the answer.','She knows the answer.','She knowing the answer.','She know the answer now.','B'),
    mc(14,'Complete: "Does she work here?" — "Yes, ___."','Yes, she does.','Yes, she do.','Yes, she is.','Yes, she works.','A'),
    mc(15,'Complete: "___ my parents speak English." (both)','Neither','Either','Both','Some','C'),
    tf(16,'"She go to work every day" is correct.','false'),
    tf(17,'"At the moment" and "right now" signal Present Continuous.','true'),
    tf(18,'"I don\'t never go there" contains a double negative error.','true'),
    fb(19,'I ___ (always/position) wake up at 6. She ___ (be, present continuous) studying.','always wake up, is studying'),
    fb(20,'Neither Tom ___ (nor) Anna was there. She doesn\'t have ___ (enough) time.','nor, enough'),
  ]},

  // ═══ MODULE 3: People & Places ═══

  '122eadf7-99f8-4d51-91cb-a298146174ae':{pass_threshold:70,questions:[  // Countries & Nationalities — Proper Nouns
    mc(1,'Proper nouns always start with:','lowercase letter','capital letter','a number','a symbol','B'),
    mc(2,'Which is a proper noun?','city','country','Kazakhstan','language','C'),
    mc(3,'What is the nationality for Germany?','Germanian','German','Germish','Germanish','B'),
    mc(4,'Which sentence is correct?','She is from france.','She is from France.','she is from France.','She is from france.','B'),
    mc(5,'What is the nationality for Japan?','Japanish','Japaner','Japanian','Japanese','D'),
    mc(6,'Which country matches "Brazilian"?','Argentina','Mexico','Brazil','Chile','C'),
    mc(7,'Which is NOT a proper noun?','London','Astana','university','Pacific Ocean','C'),
    mc(8,'What is the nationality for China?','Chinian','Chines','Chinese','Chinish','C'),
    mc(9,'Complete: "He is ___ — he comes from Turkey."','Turk','Turkian','Turkish','Turkic','C'),
    mc(10,'Which sentence is correct?','She speaks arabic.','She speaks Arabic.','She speaks Arabic language.','She speaks the Arabic.','B'),
    tf(11,'Countries and nationalities must always be written with a capital letter.','true'),
    tf(12,'"american" written with a lowercase "a" is correct.','false'),
    tf(13,'A common noun refers to general things; a proper noun refers to specific ones.','true'),
    fb(14,'She is from ___ (Italy). She is ___ (Italian).','Italy, Italian'),
    fb(15,'___ (Kazakhstan) is a large country. People from there are ___ (Kazakhstani).','Kazakhstan, Kazakhstani'),
  ]},

  '282dc4af-9dd3-4725-97db-ee33418910f3':{pass_threshold:70,questions:[  // In the City — There is/are & Prepositions
    mc(1,'Complete: "___ a bank near the station."','There are','There is','There am','There be','B'),
    mc(2,'Complete: "___ three parks in our neighbourhood."','There is','There am','There are','There be','C'),
    mc(3,'The library is ___ the school and the post office. (in the middle)','next to','behind','between','in front of','C'),
    mc(4,'The bus stop is ___ the hotel. (directly in front)','behind','next to','in front of','between','C'),
    mc(5,'Complete: "___ any banks in this street?"','Is there','Are there','There is','There are','B'),
    mc(6,'Complete: "The supermarket is ___ the left."','in','at','on','by','C'),
    mc(7,'Which is correct?','There is many shops.','There are many shops.','There is a many shops.','There are a many shops.','B'),
    mc(8,'The café is ___ the corner. (at the corner of the street)','in','on','at','by','C'),
    mc(9,'Complete: "There ___ a museum and two galleries in the city."','are','is','am','be','B'),
    mc(10,'The park is ___ the hospital. (directly opposite)','next to','behind','opposite','between','C'),
    tf(11,'"There is" is used with singular countable nouns and uncountable nouns.','true'),
    tf(12,'"There are a museum" is correct.','false'),
    tf(13,'"Opposite" means directly across from something.','true'),
    fb(14,'___ (there is/are) a cinema and two theatres. ___ (there is/are) a big park opposite the town hall.','There are, There is'),
    fb(15,'The bank is ___ (between) the café and the library. The taxi rank is ___ (in front of) the station.','between, in front of'),
  ]},

  'a3236ee3-8a83-4479-8498-69daca233788':{pass_threshold:70,questions:[  // Getting Around — Transport Vocabulary
    mc(1,'Which transport travels on rails?','bus','taxi','train','plane','C'),
    mc(2,'Complete: "___ the number 10 bus to the city centre."','Go','Drive','Take','Ride','C'),
    mc(3,'What does "on foot" mean?','by car','by bike','walking','by bus','C'),
    mc(4,'Complete: "I ___ to work — it takes about 20 minutes on foot." (walk)','drive','take the bus','walk','fly','C'),
    mc(5,'Which is used to travel underground?','tram','ferry','metro/subway','cable car','C'),
    mc(6,'Complete: "Get ___ the bus at Central Station." (leave the bus)','on','in','off','into','C'),
    mc(7,'Complete: "Get ___ the taxi." (enter the taxi)','off','out of','into','beside','C'),
    mc(8,'What do you need to travel on public transport?','a driving licence','a passport','a ticket','a visa','C'),
    mc(9,'Which is correct?','She goes to work on bus.','She goes to work by bus.','She goes to work with bus.','She goes to work in bus.','B'),
    mc(10,'What does "traffic jam" mean?','a type of vehicle','when roads are blocked by too many cars','a bus schedule','a type of road','B'),
    tf(11,'"By car", "by bus", "by train" are all correct ways to say how you travel.','true'),
    tf(12,'"On foot" means by bicycle.','false'),
    tf(13,'You "get on" a bus and "get off" a bus.','true'),
    fb(14,'I ___ (take) the metro to work. She ___ (travel) by car every day.','take, travels'),
    fb(15,'___ (get on/off) the bus at the last stop. Take the ___ (underground/bus) — it\'s faster.','Get off, underground / metro'),
  ]},

  'daf994bc-5d2d-48b2-aacd-bf34c06b0c6e':{pass_threshold:70,questions:[  // Home & Furniture — Countable & Uncountable
    mc(1,'Which noun is uncountable?','chair','table','furniture','sofa','C'),
    mc(2,'Which noun is countable?','water','rice','window','information','C'),
    mc(3,'Complete: "How much ___ is in the living room?" (furniture)','furnitures','pieces of furniture','furniture','piece of furniture','C'),
    mc(4,'Complete: "There are ___ chairs in the kitchen."','much','a little','many','a bit of','C'),
    mc(5,'Which is correct?','She bought a furniture.','She bought furniture.','She bought furnitures.','She bought some furnitures.','B'),
    mc(6,'Which item is NOT typically in a bedroom?','wardrobe','bed','oven','desk','C'),
    mc(7,'Complete: "There isn\'t ___ space in the flat."','many','a few','much','a lot','C'),
    mc(8,'Which sentence is correct?','I need some informations.','I need some information.','I need an information.','I need informations.','B'),
    mc(9,'Which is an uncountable noun?','room','kitchen','electricity','flat','C'),
    mc(10,'Complete: "We have ___ furniture but ___ chairs." (not much / several)','a little / many','little / many','much / a lot','few / little','B'),
    tf(11,'"Furniture" is an uncountable noun — we cannot say "a furniture".','true'),
    tf(12,'"Informations" is the correct plural of "information".','false'),
    tf(13,'Countable nouns can be made plural and used with numbers.','true'),
    fb(14,'I need some ___ (furniture) for my new flat. There is a ___ (sofa) in the living room.','furniture, sofa'),
    fb(15,'How ___ (much/many) chairs are there? How ___ (much/many) furniture is there?','many, much'),
  ]},

  '1204b357-a5db-486b-8beb-7d66c54dc8b3':{pass_threshold:70,questions:[  // Describing Places — Comparative Adjectives
    mc(1,'What is the comparative form of "big"?','more big','bigger','biger','most big','B'),
    mc(2,'What is the comparative form of "beautiful"?','beautifuller','more beautiful','more beautifull','beautifuler','B'),
    mc(3,'Complete: "London is ___ (large) than Almaty."','larger','more large','more larger','largest','A'),
    mc(4,'What is the comparative form of "good"?','gooder','more good','better','goodest','C'),
    mc(5,'What is the comparative form of "bad"?','badder','more bad','worse','bader','C'),
    mc(6,'Complete: "The new library is ___ (modern) ___ the old one."','more modern / as','more modern / than','most modern / than','modern / than','B'),
    mc(7,'Choose the correct sentence:','Moscow is more big than Paris.','Moscow is bigger than Paris.','Moscow is more bigger than Paris.','Moscow is biger than Paris.','B'),
    mc(8,'What is the comparative of "far"?','farer','more far','farther/further','most far','C'),
    mc(9,'Complete: "This hotel is ___ (expensive) ___ I expected."','more expensive / than','expensiver / than','more expensive / that','most expensive / than','A'),
    mc(10,'What is the comparative of "interesting"?','interestinger','more interestinger','more interesting','most interesting','C'),
    tf(11,'One-syllable adjectives usually form comparatives by adding -er.','true'),
    tf(12,'"More bigger" is correct.','false'),
    tf(13,'The comparative of "good" is "better".','true'),
    fb(14,'Almaty is ___ (big) than Shymkent. The new road is ___ (long) than the old one.','bigger, longer'),
    fb(15,'This flat is ___ (expensive) than the other. It\'s ___ (good) value for money.','more expensive, better'),
  ]},

  'fa650f3f-4fda-4298-b987-713333fd73f7':{pass_threshold:70,questions:[  // Conjunctions — Although/However/Therefore
    mc(1,'"Although" introduces:','a result','a contrast/concession','a reason','a choice','B'),
    mc(2,'"However" is used to:','add similar information','show result','show contrast','give reason','C'),
    mc(3,'"Therefore" is used to show:','contrast','a result or conclusion','addition','a choice','B'),
    mc(4,'Complete: "___ it was raining, we went for a walk."','Therefore','However','Although','So','C'),
    mc(5,'Complete: "She studied hard. ___, she passed the exam."','Although','However','Therefore','But','C'),
    mc(6,'Complete: "The film was long. ___, it was very entertaining."','Therefore','Although','However','So','C'),
    mc(7,'Choose the correct sentence:','Although she was tired, but she kept working.','Although she was tired, she kept working.','Although she was tired. She kept working.','Although, she was tired she kept working.','B'),
    mc(8,'"However" is similar in meaning to:','and','so','but','because','C'),
    mc(9,'Complete: "He didn\'t study. ___, he failed the test."','Although','However','Therefore','Unless','C'),
    mc(10,'Which is correct?','Therefore she studied, she passed.','She studied; therefore, she passed.','She studied therefore she passed.','Therefore, she studied she passed.','B'),
    tf(11,'"Although" and "however" have similar meanings but different grammatical use.','true'),
    tf(12,'"Therefore" introduces a contrast.','false'),
    tf(13,'"Although it was cold, she wore a t-shirt." is grammatically correct.','true'),
    fb(14,'___ (although/however) it was expensive, we bought it. It was expensive. ___ (however/therefore), we bought it.','Although, However'),
    fb(15,'She didn\'t sleep. ___ (therefore), she was tired. ___ (although) she was tired, she worked.','Therefore, Although'),
  ]},

  '368bace2-257c-41fb-b9fd-6c4e04d11f69':{pass_threshold:70,questions:[  // Irregular Plurals Advanced
    mc(1,'What is the plural of "sheep"?','sheeps','sheepes','sheep','sheeppen','C'),
    mc(2,'What is the plural of "fish"?','fishs','fishes','fish','fishies','C'),
    mc(3,'What is the plural of "deer"?','deers','deerses','deer','deerien','C'),
    mc(4,'What is the plural of "datum" (Latin origin)?','datums','dati','datas','data','D'),
    mc(5,'What is the plural of "criterion"?','criterions','criterias','criteria','criterion','C'),
    mc(6,'What is the plural of "phenomenon"?','phenomenons','phenomenas','phenomena','phenomenen','C'),
    mc(7,'Which is correct?','There are three sheeps in the field.','There are three sheep in the field.','There are three sheepen in the field.','There are three sheepes in the field.','B'),
    mc(8,'What is the plural of "analysis"?','analysises','analysis','analyses','analyzis','C'),
    mc(9,'What is the plural of "cactus"?','cactuses or cacti','cactiss','cactusses','cactii','A'),
    mc(10,'Which word has the same form for singular and plural?','goose','ox','deer','calf','C'),
    tf(11,'"Sheeps" is the correct plural of "sheep".','false'),
    tf(12,'"Data" is the plural of "datum".','true'),
    tf(13,'"Criteria" is the plural of "criterion".','true'),
    fb(14,'One sheep → many ___. One fish → many ___.','sheep, fish'),
    fb(15,'The ___ (criterion/criteria) for the job are clear. The ___ (datum/data) shows the trend.','criteria, data'),
  ]},

  '0332f3ff-4d79-42e7-9840-3e1d67e65124':{pass_threshold:80,questions:[  // Module 3 Review & Test
    mc(1,'Proper nouns always start with:','lowercase','capital letter','a number','a symbol','B'),
    mc(2,'What is the nationality for Brazil?','Brazilish','Braziler','Brazilian','Brazilion','C'),
    mc(3,'Complete: "___ a bank near the station."','There are','There am','There is','There be','C'),
    mc(4,'Complete: "___ three parks in the city."','There is','There am','There are','There be','C'),
    mc(5,'Complete: "___ the number 10 bus." (how to travel)','Go','Drive','Take','Ride','C'),
    mc(6,'Which is correct?','She goes to work on bus.','She goes to work by bus.','She goes to work with bus.','She goes to work in bus.','B'),
    mc(7,'Which noun is uncountable?','chair','window','furniture','sofa','C'),
    mc(8,'Complete: "There isn\'t ___ space in the flat."','many','a few','much','a lot','C'),
    mc(9,'Comparative of "big":','more big','bigger','biger','most big','B'),
    mc(10,'Comparative of "good":','gooder','more good','better','goodest','C'),
    mc(11,'Complete: "___ it was raining, we went out."','Therefore','However','Although','So','C'),
    mc(12,'Complete: "She studied. ___, she passed." (result)','Although','However','Therefore','But','C'),
    mc(13,'Plural of "sheep":','sheeps','sheepes','sheep','sheepen','C'),
    mc(14,'Plural of "criterion":','criterions','criterias','criteria','criteriones','C'),
    mc(15,'Comparative of "beautiful":','beautifuller','more beautiful','more beautifull','beautifuler','B'),
    tf(16,'"There are a museum" is correct.','false'),
    tf(17,'"Furniture" is an uncountable noun.','true'),
    tf(18,'"However" shows contrast.','true'),
    fb(19,'London is ___ (big) than Almaty. It is ___ (expensive) than I thought.','bigger, more expensive'),
    fb(20,'___ (although/however) it was cold, she wore a t-shirt. ___ (therefore/although), I stayed home.','Although, Therefore'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'7fcef8ae-70be-44f3-adf4-ec060f51aee7',n:1,title:'All About Me'},
    {id:'01d10dd9-47ed-4ba8-8980-af12f2bf3b22',n:2,title:'Daily Life'},
    {id:'f528510f-a303-44ae-be32-6408002cf5d6',n:3,title:'People & Places'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 A1 Elementary — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 1–3 A1 Elementary`)
}
main().catch(e=>{console.error(e);process.exit(1)})
