import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 17: Reading Skills ────────────────────────────────────────────────

'a399cd62-703b-4e4e-ba3e-e8a0ad01cf64':{pass_threshold:70,questions:[
  mc(1,'"Skimming" a text means:','reading every word carefully','reading to find specific information','reading quickly to get the general idea','reading aloud','C'),
  mc(2,'"Scanning" means:','reading quickly for gist','reading every word','reading to find a specific piece of information','reading slowly and carefully','C'),
  mc(3,'When reading an unadapted text, the best strategy for unknown words is:','stop reading entirely','look up every word in the dictionary','use context to infer meaning','skip the entire paragraph','C'),
  mc(4,'"Inference" in reading means:','understanding the literal meaning only','understanding implied meaning not directly stated','identifying grammar mistakes','counting words','B'),
  mc(5,'"Topic sentence" is:','the last sentence of a paragraph','the most complex sentence','usually the first sentence that states the main idea of a paragraph','a sentence with difficult vocabulary','C'),
  mc(6,'"Text cohesion" refers to:','the length of a text','how well the ideas and sentences are logically connected','the difficulty level','the number of paragraphs','B'),
  mc(7,'Which reading strategy is best for finding a specific fact?','skimming','reading aloud','scanning','intensive reading','C'),
  mc(8,'"Gist" of a text means:','a specific detail','the general meaning or main idea','the conclusion','the vocabulary level','B'),
  mc(9,'In academic texts, "hedging language" (e.g., "suggests," "may indicate") signals:','confirmed facts','the writer\'s personal emotions','cautious claims that may not be certain','incorrect information','C'),
  mc(10,'Which question type requires inference skills?','What year was X founded?','What does "X" mean in line 5?','What can be inferred about the author\'s attitude?','List three examples given.','C'),
  tf(11,'"Skimming" and "scanning" are the same reading strategy.','false'),
  tf(12,'Inferring meaning from context is a key skill for reading unadapted texts.','true'),
  tf(13,'The "topic sentence" usually appears at the end of a paragraph.','false'),
  fb(14,'She ___ (skimmed) the article to get the general idea before reading in detail.','skimmed'),
  fb(15,'The ___ (inference) question required her to read between the lines.','inference'),
]},

'dd228807-f223-4d72-8879-e2b6c66bb773':{pass_threshold:70,questions:[
  mc(1,'"Headline" in a news article:','summarizes the article\'s main point briefly','gives background information','contains the journalist\'s opinion only','appears at the end','A'),
  mc(2,'"Lead paragraph" (lede) in journalism:','provides background','answers who, what, where, when, why, how','is the final summary','gives the reporter\'s opinion','B'),
  mc(3,'Critical reading of news involves:','accepting all information as true','identifying bias, source credibility, and evidence','reading only the headline','ignoring counter-arguments','B'),
  mc(4,'"Op-ed" refers to:','an objective news report','an editorial expressing the newspaper\'s opinion','a personal opinion article opposite the editorial page','a sports column','C'),
  mc(5,'"Source attribution" in news means:','writing without identifying sources','identifying who provided the information','using anonymous quotes only','paraphrasing all sources','B'),
  mc(6,'Complete: "The journalist ___ (attribute) the quote to a senior government official."','attributing','attributed','attributes','attribution','B'),
  mc(7,'"Sensationalism" in journalism means:','objective, factual reporting','presenting news in a dramatic way to create excitement/shock','in-depth investigative reporting','using neutral language','B'),
  mc(8,'Which is a sign of RELIABLE journalism?','Anonymous sources only','Unverified claims','Multiple corroborating sources','Emotional language','C'),
  mc(9,'"Byline" in a newspaper article refers to:','the article\'s publication date','the author\'s name','the editor\'s note','the article\'s headline','B'),
  mc(10,'"Investigative journalism" involves:','reporting only official press releases','in-depth research to uncover hidden information or wrongdoing','writing opinion pieces','covering celebrity news','B'),
  tf(11,'"Sensationalism" prioritizes emotional impact over factual accuracy.','true'),
  tf(12,'A "byline" gives the author\'s name in a newspaper article.','true'),
  tf(13,'Critical readers should accept all news from established media as completely unbiased.','false'),
  fb(14,'Always check the ___ (source) before sharing news to avoid spreading misinformation.','source'),
  fb(15,'The article was ___ (attributed) to an anonymous government insider.','attributed'),
]},

'0c3267e7-67e0-41af-ab32-081a57cc9118':{pass_threshold:70,questions:[
  mc(1,'"Narrative voice" in literature refers to:','the main theme','the language register','the perspective from which a story is told','the setting of the story','C'),
  mc(2,'First-person narration uses:','he/she/it','you/your','they/their','I/me/my','D'),
  mc(3,'"Metaphor" is:','a direct comparison using "like" or "as"','a comparison without "like" or "as"','a description of setting','a type of rhythm','B'),
  mc(4,'"Simile" uses:','a direct comparison without "like" or "as"','an implicit comparison','a direct comparison using "like" or "as"','personification','C'),
  mc(5,'"Tone" in a literary text refers to:','the physical setting','the author\'s or narrator\'s attitude toward the subject','the plot structure','the vocabulary level','B'),
  mc(6,'"Motif" in literature is:','a character\'s main problem','a recurring element that has symbolic significance','a type of rhyme scheme','the climax of the plot','B'),
  mc(7,'Complete: "The author ___ (use) vivid imagery to convey the protagonist\'s anguish."','uses','using','used','use','C'),
  mc(8,'"Foreshadowing" means:','summarizing previous events','resolving the main conflict','hinting at future events','describing the setting in detail','C'),
  mc(9,'"Unreliable narrator" is one who:','always tells the truth','presents information that may be biased, mistaken, or incomplete','never speaks in first person','avoids personal opinion','B'),
  mc(10,'"Theme" in a literary work is:','the setting','the plot','the protagonist\'s name','a central idea or message explored in the work','D'),
  tf(11,'"Simile" and "metaphor" both make comparisons, but simile uses "like" or "as."','true'),
  tf(12,'"Foreshadowing" reveals what has already happened in the story.','false'),
  tf(13,'An "unreliable narrator" may present a biased or incorrect version of events.','true'),
  fb(14,'The recurring symbol of water throughout the novel serves as a ___ (motif) representing renewal.','motif'),
  fb(15,'The author uses ___ (foreshadowing) in chapter one to hint at the tragic ending.','foreshadowing'),
]},

'dca11e5c-3ac6-42c9-8704-d77987e6cf04':{pass_threshold:70,questions:[
  mc(1,'Academic texts are characterized by:','informal vocabulary and contractions','personal anecdotes and emotional appeal','objective language, hedging, and formal register','colloquial expressions','C'),
  mc(2,'"Abstract" at the beginning of an academic paper:','gives full methodology','summarizes the key findings and purpose of the paper','lists all references','provides raw data','B'),
  mc(3,'"Literature review" in academia means:','writing fiction for a course','reviewing books for pleasure','a survey of existing research on a topic','a creative writing assignment','C'),
  mc(4,'Complete: "The study ___ (aim) to examine the relationship between sleep and academic performance."','aimed','aims','aiming','aim','B'),
  mc(5,'In academic writing, "it can be argued that" is an example of:','a definitive statement','hedging language','informal expression','an error','B'),
  mc(6,'"Peer-reviewed" articles are:','written by students','checked only for grammar','reviewed and evaluated by other experts in the field before publication','published by any author online','C'),
  mc(7,'Which is the most appropriate academic citation style?','"Smith said that..."','As Smith (2020) notes, "..."','Smith wrote stuff about...','According to some research...','B'),
  mc(8,'"Methodology" in a research paper describes:','the conclusion','the abstract','the results','how the research was conducted','D'),
  mc(9,'Academic reading requires:','accepting all stated conclusions','reading only the abstract','critically evaluating evidence and argument','ignoring the methodology','C'),
  mc(10,'Complete: "The evidence ___ (suggest) a strong correlation between variables."','suggests','suggesting','suggested','suggest','A'),
  tf(11,'Academic texts frequently use hedging language to avoid overstating conclusions.','true'),
  tf(12,'An "abstract" provides a complete detailed analysis of the research.','false'),
  tf(13,'Peer-reviewed articles undergo expert evaluation before publication.','true'),
  fb(14,'The ___ (methodology) section explains how the data was collected and analyzed.','methodology'),
  fb(15,'As Smith (2023) ___ (argues), the relationship between variables is complex.','argues'),
]},

'd7fca742-0479-4226-b423-ae497389fbb6':{pass_threshold:70,questions:[
  mc(1,'When reading about abstract topics, the best approach is:','skip unfamiliar concepts','look up every word','use context clues and re-read key passages','read only the first paragraph','C'),
  mc(2,'"Abstract concept" examples include:','tables, chairs, buildings','justice, freedom, consciousness','specific people and events','dates and numbers','B'),
  mc(3,'Complete: "The philosopher ___ (argue) that consciousness cannot be reduced to physical processes."','argues','arguing','argued','argument','A'),
  mc(4,'To understand abstract academic language, it helps to:','avoid technical texts','identify definitions and examples within the text','read faster','skip the introduction','B'),
  mc(5,'"Dense text" means:','text with very short sentences','text containing many complex ideas in compact form','easy-to-read material','text with few words','B'),
  mc(6,'Which is a strategy for reading dense academic texts?','Read once quickly','Underline key terms and write summaries','Skip unfamiliar vocabulary','Avoid re-reading','B'),
  mc(7,'Complete: "She struggled to ___ (grasp) the full implications of the theory."','grasping','grasped','grasp','graspful','C'),
  mc(8,'"Paradigm shift" means:','a minor adjustment','a gradual change','a fundamental change in assumptions or approach','maintaining current methods','C'),
  mc(9,'When reading an argumentative text, you should identify:','the author\'s main claim and supporting evidence','only the vocabulary','the number of paragraphs','the publication date only','A'),
  mc(10,'Complete: "The text ___ (deal) with the complex relationship between language and thought."','dealing','deals','deal','has dealing','B'),
  tf(11,'Re-reading difficult passages is a valid and effective reading strategy.','true'),
  tf(12,'"Paradigm shift" refers to a very small, minor change.','false'),
  tf(13,'Identifying examples within a text helps readers understand abstract concepts.','true'),
  fb(14,'She re-read the passage three times before she could fully ___ (grasp) its meaning.','grasp'),
  fb(15,'The text ___ (explores) the relationship between language and social identity.','explores'),
]},

'97b9cbe6-24c0-4510-863a-04138cf207a7':{pass_threshold:70,questions:[
  mc(1,'In IELTS Reading, "True/False/Not Given" questions require:','only finding mentioned information','guessing answers','determining whether a statement agrees, contradicts, or is not mentioned in the text','summarizing the text','C'),
  mc(2,'IELTS "matching headings" tasks require:','finding specific data','identifying the main idea of each paragraph and matching it to headings','completing sentences','answering true/false','B'),
  mc(3,'In FCE Reading, "multiple matching" involves:','choosing one answer from four','matching questions to parts of a text','completing a text with missing sentences','identifying errors','B'),
  mc(4,'In IELTS/FCE, "Not Given" means:','the answer is false','the answer is true','the information is mentioned but unclear','the information is neither confirmed nor denied in the text','D'),
  mc(5,'Time management in IELTS Reading: texts become ___ difficult.','less and less','more and more','equally','randomly','B'),
  mc(6,'Which strategy helps with IELTS "sentence completion" tasks?','Read only the first paragraph','Read the sentence carefully to predict what type of information is needed','Guess answers without reading','Paraphrase all answers','B'),
  mc(7,'The FCE B2 Reading exam tests:','only grammar','only vocabulary','overall reading comprehension, vocabulary in context, and text structure','speaking ability','C'),
  mc(8,'Complete: "Candidates are ___ (advise) not to spend too much time on one question."','advising','advice','advised','advise','C'),
  mc(9,'In IELTS "matching information" tasks, you should:','read the whole text first, then scan for key words','only read the questions','ignore the text headings','read the last paragraph only','A'),
  mc(10,'"Paraphrasing" in exam reading means:','copying exact words from the text','using synonyms and rephrasing to match answer options to text','guessing vocabulary','writing summaries','B'),
  tf(11,'"True/False/Not Given" and "Yes/No/Not Given" are used in different IELTS Reading question types.','true'),
  tf(12,'In IELTS Reading, answers always appear in the same order as the questions.','false'),
  tf(13,'Scanning for key words before reading closely is an effective exam strategy.','true'),
  fb(14,'In IELTS Reading, "Not Given" means the information is ___ (neither confirmed nor denied) in the text.','neither confirmed nor denied'),
  fb(15,'Effective time management is ___ (crucial) in timed reading exams.','crucial'),
]},

'6a4b2b4f-f125-40db-8814-520dee176d71':{pass_threshold:70,questions:[
  mc(1,'Choose the best strategy for a dense academic paragraph you don\'t understand:','Skip it entirely','Read only the first sentence','Re-read, identify key terms, and paraphrase each sentence','Ask someone else','C'),
  mc(2,'A "rhetorical question" in a text:','requires a written answer','is asked for effect, not expecting an actual reply','is always answered in the next line','is an error','B'),
  mc(3,'"Counterargument" in a text means:','the main argument','an argument that supports the author\'s view','an argument that opposes the main argument','a conclusion','C'),
  mc(4,'Complete: "The author ___ (acknowledge) several limitations of the study."','acknowledging','acknowledgment','acknowledged','acknowledge','C'),
  mc(5,'Which question type requires you to identify the author\'s PURPOSE?','What does "X" mean in line 6?','In which paragraph is X mentioned?','What is the author\'s main purpose in writing paragraph 3?','List three features of X.','C'),
  mc(6,'"Cohesive devices" in reading include:','character descriptions','formatting only','conjunctions, pronouns, and synonyms that link ideas','word count restrictions','C'),
  mc(7,'Complete: "The evidence ___ (support) the hypothesis that diet affects cognitive function."','supporting','supported','support','supports','D'),
  mc(8,'In academic reading, "however" and "nevertheless" signal:','addition of similar information','an example','conclusion','contrast or concession','D'),
  mc(9,'When identifying bias in a text, look for:','only grammar errors','factual information','emotive language, one-sided arguments, or selective evidence','only complex vocabulary','C'),
  mc(10,'"Connotation" means:','the literal dictionary meaning of a word','an additional implied meaning or emotional association','the grammatical function','the etymology','B'),
  tf(11,'Cohesive devices help connect ideas within and between paragraphs.','true'),
  tf(12,'"However" signals the addition of similar information.','false'),
  tf(13,'"Connotation" refers only to the literal meaning of a word.','false'),
  fb(14,'The ___ (connotation) of "home" often suggests warmth and security beyond its literal meaning.','connotation'),
  fb(15,'___ (However), not all researchers agree with this interpretation of the data.','However'),
]},

'b4d6430b-847f-40d8-8dca-0cb2c5c925cb':{pass_threshold:80,questions:[
  mc(1,'"Skimming" vs "scanning": which is used to get the general idea?','scanning','reading intensively','skimming','re-reading','C'),
  mc(2,'IELTS "Not Given" means:','the statement is false','the statement is true','the statement contradicts the text','the information is not in the text','D'),
  mc(3,'"Inference" means:','finding specific data','understanding implied meaning','identifying grammar errors','reading aloud','B'),
  mc(4,'In a news article, the "lead paragraph" answers:','only the "what"','who, what, where, when, why, how','background history','the journalist\'s opinion','B'),
  mc(5,'"Peer-reviewed" articles are evaluated by:','the author\'s students','the general public','other experts in the field','only the editor','C'),
  mc(6,'"Metaphor" vs "simile": which uses "like" or "as"?','Metaphor','Neither uses it','Both use it','Simile','D'),
  mc(7,'"Unreliable narrator" may present:','only objective facts','a biased or incomplete version of events','no opinions','historical accuracy always','B'),
  mc(8,'Academic hedging: which is a hedge?','It is universally proven that...','It is certain that...','It would appear that...','All evidence confirms...','C'),
  mc(9,'"Op-ed" in journalism is:','an objective news report','a financial report','a personal opinion article','a sports column','C'),
  mc(10,'"Cohesive devices" help:','identify the author\'s age','count words','assess vocabulary level','logically connect ideas within a text','D'),
  mc(11,'"Connotation" is:','the dictionary definition','the grammatical function','the physical sound of a word','an implied or emotional meaning beyond the literal','D'),
  mc(12,'Which strategy is best for "sentence completion" in IELTS Reading?','Read only the last sentence','Scan for key words only','Predict what type of information is needed, then locate it','Guess without reading','C'),
  mc(13,'"Foreshadowing" in literature:','reveals past events','explains the setting','summarizes the plot','hints at future events','D'),
  mc(14,'In academic reading, "however" signals:','addition','example','result','contrast','D'),
  mc(15,'Bias in a text can be detected through:','word count','font size','publication date','emotive language and one-sided arguments','D'),
  tf(16,'"Scanning" and "skimming" are different reading strategies with different purposes.','true'),
  tf(17,'"True/False/Not Given" in IELTS requires you to determine if information is in the text.','true'),
  tf(18,'Academic texts should be accepted without critical evaluation.','false'),
  fb(19,'She ___ (skimmed) the report quickly before the meeting to get the main points.','skimmed'),
  fb(20,'The ___ (motif) of isolation recurs throughout the novel, reflecting the protagonist\'s loneliness.','motif'),
]},

// ── MODULE 18: Writing Skills ────────────────────────────────────────────────

'2cc71093-8711-416c-860c-1a1603de8d07':{pass_threshold:70,questions:[
  mc(1,'A well-structured essay typically contains:','introduction / body / conclusion','only body paragraphs','introduction and conclusion only','random paragraphs','A'),
  mc(2,'The "thesis statement" in an essay:','introduces background information','gives a list of facts','states the writer\'s main argument or purpose','concludes the essay','C'),
  mc(3,'A "topic sentence" in a body paragraph:','summarizes the whole essay','gives examples only','states the main point of that paragraph','provides a counterargument','C'),
  mc(4,'Complete: "Furthermore, ___ (it should be noted/we should note/noting) that the data shows a significant trend."','we should note','noting','to note','it should be noted','D'),
  mc(5,'Which is the correct essay structure order?','Hook → Background → Thesis → Body → Conclusion','Conclusion → Body → Introduction','Body → Introduction → Conclusion','Thesis → Conclusion → Body → Introduction','A'),
  mc(6,'"Coherence" in writing means:','using complex sentences only','ideas flow logically and are easy to follow','using many linking words','writing very long paragraphs','B'),
  mc(7,'Complete: "___ (In conclusion/To sum up/Finally), the evidence suggests that early intervention is most effective."','In conclusion / To sum up / Finally — all are correct','Only "finally"','Only "in conclusion"','None of these','A'),
  mc(8,'Which linking word introduces a CONTRASTING idea?','Furthermore','Moreover','Nevertheless','In addition','C'),
  mc(9,'Which phrase introduces an EXAMPLE?','In contrast','However','Nevertheless','For instance / For example','D'),
  mc(10,'Academic essays should avoid:','evidence and examples','logical structure','thesis statements','informal language and contractions','D'),
  tf(11,'A thesis statement should be vague and general.','false'),
  tf(12,'Each body paragraph should focus on one main idea supported by evidence.','true'),
  tf(13,'"Nevertheless" is used to introduce additional information.','false'),
  fb(14,'The ___ (thesis) statement presents the writer\'s central argument.','thesis'),
  fb(15,'___ (Furthermore), the research reveals a strong correlation between the variables.','Furthermore'),
]},

'd2445eca-dc2b-45bf-a6c6-af7d0424cb56':{pass_threshold:70,questions:[
  mc(1,'An "argument" in an essay is:','an angry dispute','a list of facts','a supported claim or position','a narrative story','C'),
  mc(2,'"Counter-argument" is:','a supporting point for your argument','a view that opposes your main argument','a conclusion','an example','B'),
  mc(3,'How should you handle a counter-argument in a formal essay?','Ignore it completely','Acknowledge it and then refute it with evidence','Agree with it completely','Change your main argument','B'),
  mc(4,'Complete: "___ (While/Although) some argue that X, the evidence suggests Y."','While / Although — both are correct','Only "although"','Only "while"','Only "however"','A'),
  mc(5,'Which phrase introduces a CONCESSION (acknowledging the other side)?','Furthermore...','However...','Admittedly / It is true that...','In conclusion...','C'),
  mc(6,'Complete: "Admittedly, ___ (there are/it is true that) challenges, but the benefits outweigh them."','there are / it is true that — both correct','only "there are"','only "it is true that"','neither is correct','A'),
  mc(7,'Which phrase REFUTES a counterargument?','On the other hand...','However, the evidence clearly shows that...','Some people believe...','It can be argued that...','B'),
  mc(8,'Complete: "___ (Despite/In spite of) these challenges, the policy has produced positive results."','Despite / In spite of — both correct','Only "despite"','Only "in spite of"','Neither is correct','A'),
  mc(9,'Which structure best presents an argument?','Claim → Evidence → Analysis','Evidence → Claim → Analysis','Analysis → Evidence → Claim','Random order','A'),
  mc(10,'"To rebut" an argument means:','to support it','to ignore it','to prove it correct','to disprove or counter it with evidence','D'),
  tf(11,'Counter-arguments should always be ignored in formal essays.','false'),
  tf(12,'"Admittedly" introduces a concession before making a counterpoint.','true'),
  tf(13,'"Rebut" means to strengthen an argument.','false'),
  fb(14,'___ (Admittedly), the initial costs are high; however, the long-term savings are significant.','Admittedly'),
  fb(15,'The study ___ (refutes) the claim that there is no link between diet and cognitive performance.','refutes'),
]},

'e2dcfa1d-c4ea-456d-87ab-b2b7bc5fcc27':{pass_threshold:70,questions:[
  mc(1,'Which is the correct salutation for a FORMAL letter when you don\'t know the name?','Dear John,','Hi there,','Dear Sir/Madam,','Hey,','C'),
  mc(2,'Which is the correct closing for a formal letter (name unknown)?','Yours sincerely,','Cheers,','Talk soon,','Best,','A'),
  mc(3,'"Yours sincerely" is used when:','you don\'t know the name','you know the recipient\'s name','it\'s a casual letter','it\'s an internal memo','B'),
  mc(4,'Correct structure for a formal letter:','Greeting → Body → Closing → Signature','Body → Greeting → Closing','Signature → Body → Greeting','Random order','A'),
  mc(5,'Which opening is appropriate for an INFORMAL letter?','I am writing to inquire about...','Dear Sir/Madam,','I hope this finds you well. I wanted to catch up!','Please find attached...','C'),
  mc(6,'Which phrase is appropriate for an informal letter closing?','Yours faithfully,','Yours sincerely,','Take care! Looking forward to hearing from you.','I remain yours truly,','C'),
  mc(7,'Complete (formal letter): "I ___ (write) to express my interest in the advertised position."','wrote','writing','am writing','was writing','C'),
  mc(8,'Complete (formal): "I would be grateful if you could ___ (provide) further information."','providing','provided','provision','provide','D'),
  mc(9,'Which is INAPPROPRIATE in a formal letter?','Please find enclosed...','I am writing to...','Gonna tell you about...','I look forward to your response.','C'),
  mc(10,'Purpose of a formal complaint letter:','to make small talk','to express dissatisfaction and request action','to thank for a service','to apply for a loan','B'),
  tf(11,'"Yours faithfully" is used when you know the recipient\'s name.','false'),
  tf(12,'Informal letters can use contractions and colloquial language.','true'),
  tf(13,'The closing of a formal letter always includes a signature.','true'),
  fb(14,'___ (Dear Sir/Madam), I am writing to express my concerns regarding...','Dear Sir/Madam'),
  fb(15,'I look forward to ___ (hearing) from you at your earliest convenience.','hearing'),
]},

'b40df151-64cd-438d-a89b-a253b27b2570':{pass_threshold:70,questions:[
  mc(1,'A "report" typically includes:','personal opinions only','findings, analysis, and recommendations based on research or investigation','a narrative story','a letter of complaint','B'),
  mc(2,'"Executive summary" in a report:','gives the full methodology','provides a brief overview of the key findings and recommendations','lists all references','is the same as the introduction','B'),
  mc(3,'A "review" evaluates:','only facts','only the author\'s feelings','a product, service, film, book, or place, giving a balanced assessment','only negative aspects','C'),
  mc(4,'Complete: "The ___ (report/reports/reported/reporting) recommends the following measures be taken immediately."','reports','reported','reporting','report','D'),
  mc(5,'Which heading is typical in a formal report?','Once upon a time...','Introduction / Findings / Recommendations','Dear Reader,...','In my personal opinion...','B'),
  mc(6,'Complete: "The data ___ (reveal) significant patterns in consumer behavior."','revealing','revealed','reveals','reveal','C'),
  mc(7,'A "review" should be:','one-sided and negative only','entirely positive','balanced, evaluating both strengths and weaknesses','written without evidence','C'),
  mc(8,'Complete: "On the whole, the restaurant ___ (offer) excellent value for money."','offered','offering','offers','offer','C'),
  mc(9,'Which phrase introduces a RECOMMENDATION in a report?','Once upon a time...','On the other hand...','It is recommended that / It would be advisable to...','In my personal view...','C'),
  mc(10,'Formal reports avoid:','passive voice','recommendations','findings sections','personal pronouns (I, we) and informal language','D'),
  tf(11,'A report is a factual document based on findings and analysis.','true'),
  tf(12,'A "review" should only present negative aspects of the subject.','false'),
  tf(13,'Formal reports can use informal language and contractions.','false'),
  fb(14,'The ___ (findings) indicate a significant decline in customer satisfaction.','findings'),
  fb(15,'It is ___ (recommended) that the company invest in staff training immediately.','recommended'),
]},

'cf91f622-1d07-4fbe-a33c-ae929b27c1ea':{pass_threshold:70,questions:[
  mc(1,'When describing a bar chart showing an increase, you should use:','decreased / fell / dropped','rose / increased / grew','remained stable','fluctuated wildly','B'),
  mc(2,'Which phrase describes a dramatic increase?','rose slightly','declined gradually','fluctuated marginally','rose sharply / surged','D'),
  mc(3,'"Fluctuate" means:','to rise steadily','to fall sharply','to remain exactly the same','to go up and down irregularly','D'),
  mc(4,'Complete: "The figures ___ (reach) a peak of 85% in 2020."','reaching','reach','reached','has reached','C'),
  mc(5,'Which phrase describes a PEAK?','reached a low point','remained stable','reached its highest point / peaked at','began to decline','C'),
  mc(6,'Complete: "Sales ___ (decline) steadily throughout the second quarter."','declining','declined','declines','decline','B'),
  mc(7,'Which is used for a SLIGHT decrease?','plummeted','surged','fell marginally / dropped slightly','increased dramatically','C'),
  mc(8,'Complete: "The proportion of ___ (female/females) managers rose from 20% to 45%."','females','female — both are possible','the female','femaled','B'),
  mc(9,'"Stabilize" means:','to fall sharply','to rise dramatically','to become stable after change','to fluctuate','C'),
  mc(10,'Which phrase compares two data points?','By contrast / compared to / whereas','Furthermore / moreover','In conclusion','For example / for instance','A'),
  tf(11,'"Surged" describes a dramatic increase.','true'),
  tf(12,'"Fluctuate" means to remain constant.','false'),
  tf(13,'"Peaked at" describes the highest point in a data set.','true'),
  fb(14,'The number of applicants ___ (peaked) at 1,200 in 2021 before declining.','peaked'),
  fb(15,'___ (By contrast), the proportion of female applicants remained relatively stable.','By contrast'),
]},

'c0bc0840-f124-4bcf-a1a0-b5b86a40cb4c':{pass_threshold:70,questions:[
  mc(1,'Academic writing style prefers:','informal vocabulary','contractions','passive voice and impersonal structures','conversational tone','C'),
  mc(2,'Which is the most appropriate academic sentence?','We think this proves our theory.','Gonna explain the results now.','I believe the data supports my view.','The data suggest a significant correlation.','D'),
  mc(3,'"Nominalization" in academic style: convert "analyze" to a noun:','analyzing','analyzed','analyzes','analysis','D'),
  mc(4,'"Hedging" in academic writing expresses:','absolute certainty','personal emotions','caution about claims','informal opinion','C'),
  mc(5,'Which is NOT appropriate in academic writing?','It has been suggested that...','The study demonstrates...','Loads of people believe...','This implies that...','C'),
  mc(6,'Complete: "The results ___ (indicate) a statistically significant difference between groups."','indicating','indicated','indicate','indication','C'),
  mc(7,'Formal academic verbs replace informal ones: "go up" →','increase / rise','go higher','move up','get bigger','A'),
  mc(8,'Which phrase introduces evidence in academic writing?','A lot of people say...','As Smith (2022) argues...','Everyone knows that...','I\'ve seen that...','B'),
  mc(9,'Academic writing avoids first-person (I/we) because:','it is grammatically incorrect','it sounds more objective to use impersonal structures','it makes writing longer','it is a new rule','B'),
  mc(10,'Complete: "It ___ (be) argued that the policy has had unintended consequences."','should','can','can be argued','could be argued — C and D both work','D'),
  tf(11,'"Nominalization" helps make academic writing more formal and concise.','true'),
  tf(12,'Academic writing frequently uses contractions like "it\'s" and "don\'t."','false'),
  tf(13,'Hedging language is appropriate in academic writing.','true'),
  fb(14,'The ___ (investigation) of the data revealed unexpected patterns. (nominalized)','investigation'),
  fb(15,'It ___ (can be argued) that globalization has both positive and negative effects.','can be argued'),
]},

'77e87dfc-e687-4489-9e8b-3d513d36c0e8':{pass_threshold:70,questions:[
  mc(1,'IELTS Writing Task 1 (Academic) requires:','a discursive essay','an opinion essay','a description and comparison of visual data (charts, graphs, diagrams)','a letter of complaint','C'),
  mc(2,'IELTS Writing Task 2 requires:','a report','a letter','a description of data','a discursive or opinion essay of at least 250 words','D'),
  mc(3,'FCE Writing Part 1 typically requires:','a report','a review','a letter/email based on input material','a description of data','C'),
  mc(4,'In IELTS Task 1, you should NOT:','include an overview','describe main trends','include all minor details','compare data','C'),
  mc(5,'In IELTS Task 2, the conclusion should:','introduce new arguments','repeat the introduction exactly','restate your position and main points concisely','be one word','C'),
  mc(6,'Complete: "The graph ___ (illustrate) the changes in energy consumption between 2000 and 2020."','illustrated','illustrating','illustration','illustrates','D'),
  mc(7,'In FCE Writing, which tense is most common in a narrative?','Present Simple','Future Perfect','Past Simple and Past Continuous','Future Continuous','C'),
  mc(8,'Which is NOT a recommended strategy for IELTS Writing?','Planning before writing','Using a variety of sentence structures','Writing about your own experience only','Using topic-specific vocabulary','C'),
  mc(9,'In IELTS Task 1, "overview" means:','a detailed description of every data point','a summary of the main trends and overall patterns','a conclusion to the essay','a list of all data','B'),
  mc(10,'Time management for IELTS Writing: Task 2 should take:','10 minutes','5 minutes','40 minutes','exactly the same as Task 1','C'),
  tf(11,'IELTS Task 1 (Academic) requires describing and comparing visual data.','true'),
  tf(12,'An "overview" in IELTS Task 1 describes every specific detail.','false'),
  tf(13,'In IELTS Task 2, you should clearly state your position in the introduction.','true'),
  fb(14,'The chart ___ (illustrates) the changes in renewable energy production between 2010 and 2023.','illustrates'),
  fb(15,'In IELTS Task 2, the ___ (conclusion) should restate your main argument concisely.','conclusion'),
]},

'0d5ab1e1-5baf-4c6b-a845-e5b188110e83':{pass_threshold:80,questions:[
  mc(1,'"Thesis statement" is:','a list of supporting points','the conclusion of an essay','a vague opening sentence','the writer\'s central argument or purpose','D'),
  mc(2,'Which linking word shows CONTRAST?','Furthermore','Moreover','In addition','Nevertheless','D'),
  mc(3,'Handling a counterargument: best approach:','ignore it','agree completely','present it and refute it with evidence','change your position','C'),
  mc(4,'IELTS Task 1 Academic: what should you ALWAYS include?','your personal opinion','every minor detail','an overview of the main trends','a conclusion with recommendations','C'),
  mc(5,'Academic writing: "go up" →','get higher','rise / increase','move up','grow bigger','B'),
  mc(6,'Formal letter: "Dear Sir/Madam" → closing:','Yours sincerely,','Cheers,','Best wishes,','Yours faithfully,','D'),
  mc(7,'In a report, "executive summary" provides:','full methodology details','a brief overview of key findings and recommendations','a list of all sources','raw data tables','B'),
  mc(8,'"Fluctuate" means:','rise steadily','fall sharply','remain constant','go up and down irregularly','D'),
  mc(9,'Nominalization: "investigate" →','investigating','investigated','investigation','investigates','C'),
  mc(10,'Academic writing: "loads of people" → formal:','a lot of people','many people / a significant number of people','most people','all people','B'),
  mc(11,'IELTS Task 2 word count requirement:','100 words minimum','150 words minimum','250 words minimum','500 words minimum','C'),
  mc(12,'In a review, you should:','only praise the subject','only criticize it','present a balanced assessment with evidence','give only facts without opinion','C'),
  mc(13,'"Peaked at" describes:','the lowest data point','a period of decline','a stable period','the highest data point','D'),
  mc(14,'Academic hedging: which is NOT a hedging device?','It could be argued that...','It appears that...','It is universally certain that...','It would seem that...','C'),
  mc(15,'Which phrase introduces a CONCESSION before a counterargument?','Furthermore,','However,','Admittedly, / It is true that...','In addition,','C'),
  tf(16,'"Cohesion" in writing means ideas are logically connected and flow well.','true'),
  tf(17,'Formal letters with "Dear Sir/Madam" end with "Yours sincerely."','false'),
  tf(18,'"Surged" describes a dramatic and rapid increase.','true'),
  fb(19,'The ___ (findings) of the report indicate significant room for improvement.','findings'),
  fb(20,'___ (It can be argued) that technology has transformed the nature of work.','It can be argued'),
]},

// ── MODULE 19: Listening & Speaking ─────────────────────────────────────────

'1a3a5665-9937-401b-9ce3-ddc2555a1124':{pass_threshold:70,questions:[
  mc(1,'"Connected speech" features include:','each word pronounced separately','linking, elision, and assimilation of sounds','very slow, deliberate pronunciation','only formal pronunciation','B'),
  mc(2,'"Elision" in fast speech means:','adding sounds','making sounds stronger','omitting sounds (e.g., "next day" → "nex\' day")','changing meaning','C'),
  mc(3,'"Assimilation" means:','one sound becomes similar to a neighboring sound (e.g., "ten people" → "tem people")','sounds are omitted','words are linked together','speed increases','A'),
  mc(4,'"Linking" in connected speech connects:','sentences','paragraphs','a final consonant to the following initial vowel sound','only stressed syllables','C'),
  mc(5,'Complete: "___ (Reduce/Reducing/Reduced) forms" in speech make unstressed words less prominent.','Reduce','Reducing','Reduced','Reduction','C'),
  mc(6,'Common weak forms in natural speech: "and" is often pronounced as:','/ænd/','/ɛnd/','/ənd/ (schwa)','/nd/','C'),
  mc(7,'Strategy for understanding fast native speech:','Expect perfect pronunciation','Focus on every word equally','Focus on stressed words and use context to fill in reduced sounds','Transcribe every word','C'),
  mc(8,'"Stress-timed" language (like English) means:','every syllable is equally long','stressed syllables occur at regular intervals','only content words are stressed','rhythm is irrelevant','B'),
  mc(9,'"Schwa" /ə/ is:','a stressed vowel','the most common unstressed vowel in English','a consonant sound','a type of linking','B'),
  mc(10,'Which sounds are typically reduced in fast speech?','nouns and main verbs','adjectives and adverbs','function words (articles, prepositions, auxiliaries)','all stressed syllables','C'),
  tf(11,'"Elision" involves adding extra sounds in fast speech.','false'),
  tf(12,'The schwa /ə/ is the most common vowel sound in English.','true'),
  tf(13,'In natural English, every word is given equal stress and pronunciation.','false'),
  fb(14,'In fast speech, "want to" is often reduced to "___ (wanna)."','wanna'),
  fb(15,'Focusing on ___ (stressed) words helps listeners understand fast native speech.','stressed'),
]},

'3ea326f1-3e58-41f0-8e98-b6e01c95baee':{pass_threshold:70,questions:[
  mc(1,'TV news uses language that is:','informal and conversational','academic and technical only','a mix of formal and accessible language','colloquial and full of slang','C'),
  mc(2,'Strategy for watching English news: focus on:','every word equally','only the visuals','key words, numbers, and repeated phrases','grammar rules','C'),
  mc(3,'Complete: "The reporter ___ (cover) the story live from the scene."','covered','covers','covering','cover','A'),
  mc(4,'"Breaking news" refers to:','old stories','news from other countries','unconfirmed gossip','very recent news that is developing rapidly','D'),
  mc(5,'"Commentary" in sports broadcasting means:','a factual report','a written transcript','the spoken description and analysis of a live event','background music','C'),
  mc(6,'Which strategy helps with TV news comprehension?','Watching without subtitles always','Using subtitles to support understanding','Only reading the news','Ignoring visual context','B'),
  mc(7,'Complete: "She was ___ (interview) about her experience by a major TV network."','interviewing','interview','interviews','interviewed','D'),
  mc(8,'"Headline" in broadcast news:','is the full story','a brief summary of the main stories covered','is the journalist\'s opinion','appears only online','B'),
  mc(9,'Which feature is common in broadcast news English?','Complex subordinate clauses only','Very slow, formal speech','Passive constructions and reporting verbs','Colloquial expressions and slang','C'),
  mc(10,'Complete: "The documentary ___ (explore) the impact of social media on mental health."','explored','exploring','explores','exploration','C'),
  tf(11,'"Breaking news" refers to old or background stories.','false'),
  tf(12,'Using subtitles when watching news can support listening comprehension.','true'),
  tf(13,'Broadcast news typically uses a very formal, academic register throughout.','false'),
  fb(14,'The news ___ (reported) that three people had been injured in the accident.','reported'),
  fb(15,'The ___ (documentary) examined the long-term effects of climate change on coastal communities.','documentary'),
]},

'87cb6e14-3c25-41ea-b1ab-0c6c4606e547':{pass_threshold:70,questions:[
  mc(1,'Complete: "In my ___ (see/view/thought/opinion), the solution requires a multi-faceted approach."','see','thought','look','view','D'),
  mc(2,'Which phrase introduces a STRONG opinion?','I\'m not sure, but...','I strongly believe that...','Some people think...','It\'s possible that...','B'),
  mc(3,'Which phrase softens a statement?','Absolutely not.','It is somewhat questionable whether...','I completely disagree.','This is entirely wrong.','B'),
  mc(4,'Complete: "To ___ (put/take/make) it another way, the policy had unintended consequences."','take','make','give','put','D'),
  mc(5,'Which phrase concedes a point while maintaining your position?','I completely agree.','I disagree entirely.','Fair point, but one must also consider...','That\'s irrelevant.','C'),
  mc(6,'Complete: "While I ___ (appreciate/recognized/note/understand) your point, I believe the evidence suggests otherwise."','all four are possible — A, C, D','recognized','note only','appreciate only','A'),
  mc(7,'"Devil\'s advocate" in a discussion means:','supporting the popular view','agreeing with everyone','arguing the opposite side for the sake of debate','remaining neutral','C'),
  mc(8,'Complete: "It\'s a ___ (complex/complicated/difficult) issue with no simple answer."','complicated','difficult','all three — A, B, C — are correct','complex','C'),
  mc(9,'Which is the most formal way to disagree?','No, that\'s wrong.','I disagree.','I beg to differ.','You\'re mistaken.','C'),
  mc(10,'Complete: "Building on that point, ___ (it could be argued/we could say/one might suggest) that..."','one might suggest','we could say','all are possible — A, B, C','it could be argued','C'),
  tf(11,'"I beg to differ" is a formal/polite way to disagree.','true'),
  tf(12,'"Playing devil\'s advocate" means you strongly believe the opposite position.','false'),
  tf(13,'"Fair point, but..." is a concession phrase used to acknowledge another view before countering.','true'),
  fb(14,'In my ___ (view), the benefits of renewable energy far outweigh the costs.','view'),
  fb(15,'While I appreciate your point, ___ (it could be argued) that the long-term consequences are more significant.','it could be argued'),
]},

'1a66e0d9-dab0-433d-9203-8aa34500be78':{pass_threshold:70,questions:[
  mc(1,'"Thesis" in a debate is:','the opposing side\'s argument','the moderator\'s role','the central claim being argued','a question asked to the audience','C'),
  mc(2,'The "floor" in a formal debate refers to:','the physical floor','the right to speak at a given moment','the audience\'s opinion','the venue','B'),
  mc(3,'Complete: "I ___ (would like/should like) to refute the claim that economic growth always reduces inequality."','should like','would like — both are formally acceptable','would liking','like','B'),
  mc(4,'"Rebuttal" means:','agreeing with the opponent','elaborating on your own argument','a response that disproves the opposing argument','a statement of facts','C'),
  mc(5,'Complete: "The ___ (motion/proposal/claim/argument) for debate tonight is: Technology does more harm than good."','proposal','claim','argument','motion','D'),
  mc(6,'"Ad hominem" attack in a debate means:','attacking the argument','attacking the person rather than their argument','making a strong emotional appeal','citing evidence','B'),
  mc(7,'Complete: "Far from ___ (prove/proving/proved/proof) the point, this evidence actually contradicts it."','prove','proved','proof','proving','D'),
  mc(8,'Which is a logical fallacy?','Citing peer-reviewed evidence','Acknowledging counterarguments','Using verifiable statistics','Appealing only to emotion without evidence','D'),
  mc(9,'Complete: "I ___ (would argue/can argue/would like to argue) that the proposed policy is fundamentally flawed."','all are correct — A, B, C','can argue only','would like to argue only','would argue only','A'),
  mc(10,'Formal debate structure typically includes:','only opening statements','random comments','opening statement / argument / rebuttal / conclusion','questions only','C'),
  tf(11,'"Ad hominem" attacks are considered a logical fallacy.','true'),
  tf(12,'"Rebuttal" means agreeing with the opposing argument.','false'),
  tf(13,'A well-structured debate argument includes a claim, evidence, and analysis.','true'),
  fb(14,'The ___ (motion) for tonight\'s debate is: "Technology has done more harm than good."','motion'),
  fb(15,'She delivered a powerful ___ (rebuttal) that undermined the opposing team\'s main claim.','rebuttal'),
]},

'7c0002fa-499e-4482-aaa3-950de710ba12':{pass_threshold:70,questions:[
  mc(1,'An effective presentation opening should:','list all your main points immediately','start with a question, quote, or striking fact to engage the audience','apologize for being there','start with background details','B'),
  mc(2,'Complete: "Today I ___ (would like/am going to/will) walk you through the key findings."','would like to / am going to / will — all are correct','am going to only','will only','would like to only','A'),
  mc(3,'Which helps manage nerves during public speaking?','Memorizing every word','Focusing only on the audience','Avoiding eye contact','Controlled breathing and preparation','D'),
  mc(4,'Signposting language ("Firstly," "Moving on," "To summarize") helps:','confuse the audience','make the presentation shorter','guide the audience through the structure','create visual aids','C'),
  mc(5,'Complete: "To ___ (recap/summarize/conclude), the evidence strongly suggests a need for policy reform."','recap / summarize / conclude — all are correct','conclude only','recap only','summarize only','A'),
  mc(6,'"Rhetorical question" in a presentation:','requires audience to write answers','invites a debate','is asked for effect, not a literal answer','is a grammatical error','C'),
  mc(7,'Complete: "As you can see ___ (from/in/on) the graph, sales peaked in Q3."','in','on','at','from','D'),
  mc(8,'Which body language tip is most effective in presentations?','Avoid all movement','Look only at your notes','Maintain eye contact with different parts of the audience','Stand completely still','C'),
  mc(9,'Complete: "I\'d like to ___ (draw/bring) your attention to the key statistics here."','bring','drawing','draws','draw','D'),
  mc(10,'Closing a presentation effectively:','ends abruptly','summarizes key points, restates the message, and invites questions','only thanks the audience','repeats the introduction word-for-word','B'),
  tf(11,'Signposting language helps the audience follow the structure of a presentation.','true'),
  tf(12,'A rhetorical question requires an immediate answer from the audience.','false'),
  tf(13,'Maintaining eye contact during a presentation builds connection with the audience.','true'),
  fb(14,'___ (To summarize), the three key findings are efficiency, sustainability, and scalability.','To summarize'),
  fb(15,'I\'d like to ___ (draw) your attention to the dramatic increase shown in this graph.','draw'),
]},

'61f9c39c-6e31-4311-a8f6-b7471114fcc2':{pass_threshold:70,questions:[
  mc(1,'IELTS Speaking Part 1 involves:','a long monologue on a given topic','questions about familiar personal topics','a discussion with a partner','reading aloud','B'),
  mc(2,'IELTS Speaking Part 2 requires:','a short conversation','a 1-2 minute talk on a given topic using a task card','answering yes/no questions','a written response','B'),
  mc(3,'IELTS Speaking Part 3 involves:','describing a picture','discussing abstract ideas related to the Part 2 topic','giving a prepared speech','reading a passage','B'),
  mc(4,'FCE Speaking Part 2 requires candidates to:','answer personal questions','debate a topic','compare two photographs and discuss their differences','write an essay','C'),
  mc(5,'Which phrase helps buy time while thinking in speaking exams?','I don\'t know.','Silence.','That\'s a great question; let me think about that for a moment...','I pass.','C'),
  mc(6,'Complete: "In my ___ (experience/view/opinion/estimation), city life offers more opportunities."','all four — A, B, C, D are correct','experience only','view only','opinion only','A'),
  mc(7,'Which strategy improves speaking exam performance?','Speaking as fast as possible','Using a wide range of vocabulary and structures','Giving very short answers','Memorizing entire responses','B'),
  mc(8,'Complete: "What I ___ (particularly/especially) admire about this place is its diversity."','especially','extremely','very much','particularly — both A and D are correct','D'),
  mc(9,'In IELTS Speaking, "fluency" means:','speaking without any grammar errors','speaking at an appropriate pace without excessive hesitation','using only simple sentences','speaking very slowly','B'),
  mc(10,'Which IELTS Speaking Band descriptor is most associated with "coherence"?','Pronunciation','Lexical Resource','Grammatical Range','Fluency and Coherence','D'),
  tf(11,'IELTS Speaking Part 2 gives candidates preparation time before speaking.','true'),
  tf(12,'In FCE Speaking Part 2, candidates compare two photographs.','true'),
  tf(13,'Memorizing pre-written responses is the best strategy for speaking exams.','false'),
  fb(14,'In IELTS Speaking Part 2, you have ___ (1 minute) to prepare your response.','1 minute'),
  fb(15,'Using a variety of ___ (vocabulary/structures) demonstrates a higher language level.','vocabulary / structures'),
]},

'27d48a15-66ba-4fab-9a52-15cb00ef91ec':{pass_threshold:70,questions:[
  mc(1,'When doing a listening gap-fill, the best approach is:','write everything you hear','predict the type of information needed before listening','listen only once','ignore the questions','B'),
  mc(2,'Complete: "The speaker ___ (argue) that current education systems are failing students."','argues / argued — depends on context','argued only','is arguing only','argued only','A'),
  mc(3,'In multiple-choice listening, the wrong options are designed to:','be obvious distractors','perfectly match the audio','be identical to the correct answer','all be correct','A'),
  mc(4,'Which listening strategy helps with IELTS Section 4 (academic lecture)?','Focus on every word equally','Focus on key terms and note-taking','Avoid predicting information','Ignore examples','B'),
  mc(5,'Complete: "She ___ (take) detailed notes throughout the lecture."','takes','took','taking','taken','B'),
  mc(6,'In note-taking, effective abbreviations include:','writing every word in full','using symbols (→, =, ↑, ↓) and shortened forms','writing nothing','drawing pictures only','B'),
  mc(7,'When you miss an answer in a listening exam:','go back and try to relive it','stop and give up','keep listening and attempt missed questions at the end','start over','C'),
  mc(8,'In IELTS Listening, the audio is played:','multiple times','only once','twice for difficult sections','as many times as needed','B'),
  mc(9,'"Gist listening" means:','understanding every word','listening for specific details','listening for the general meaning','only hearing key words','C'),
  mc(10,'Complete: "The documentary ___ (highlight) the challenges facing urban communities."','highlighted','highlighting','highlights','highlight','A'),
  tf(11,'In IELTS Listening, the audio is played only once.','true'),
  tf(12,'Predicting the type of answer before listening is an effective strategy.','true'),
  tf(13,'In a listening exam, you should stop if you miss one answer.','false'),
  fb(14,'___ (Predicting) the type of information needed improves listening performance.','Predicting'),
  fb(15,'She used abbreviations and symbols to make her ___ (note-taking) faster and more efficient.','note-taking'),
]},

'cabd24a3-66e9-41b5-8956-71febc3911be':{pass_threshold:80,questions:[
  mc(1,'"Elision" in fast speech means:','adding sounds','making sounds stronger','lengthening words','omitting sounds','D'),
  mc(2,'IELTS Speaking Part 2 requires:','yes/no answers','a 1-2 minute talk on a task card topic','a debate','a written essay','B'),
  mc(3,'Signposting language in presentations:','confuses the audience','guides the audience through the structure','is inappropriate in formal presentations','replaces content','B'),
  mc(4,'"Rebuttal" in a debate means:','agreeing with the opponent','introducing a new argument','a response that counters the opposing argument','giving up the floor','C'),
  mc(5,'Complete: "In my ___, the environmental costs far outweigh the economic benefits."','look','see','think','view','D'),
  mc(6,'IELTS Task 1 Academic requires:','an opinion essay','a description and analysis of visual data','a report with recommendations','a letter','B'),
  mc(7,'Formal letter: "Dear Sir/Madam" closes with:','Yours sincerely,','Best wishes,','Cheers,','Yours faithfully,','D'),
  mc(8,'"Ad hominem" in debate means:','citing strong evidence','attacking the person rather than their argument','presenting a logical counter-argument','making an emotional appeal','B'),
  mc(9,'Academic writing: "go up" →','get bigger','rise / increase','move up','grow more','B'),
  mc(10,'"Skimming" a text means:','reading every word carefully','scanning for specific information','reading quickly for the general idea','reading aloud','C'),
  mc(11,'Which is NOT a reading strategy?','Skimming','Scanning','Guessing random answers','Inferencing','C'),
  mc(12,'"Connected speech" features:','every word pronounced separately','linking, elision, and assimilation','no reduction of sounds','very slow pronunciation','B'),
  mc(13,'In IELTS Writing Task 2, the conclusion should:','introduce new arguments','repeat the introduction verbatim','restate your position concisely','be three paragraphs long','C'),
  mc(14,'"Rhetorical question" in a presentation:','requires an audience answer','is a grammar error','is asked for effect only','causes confusion','C'),
  mc(15,'In IELTS Listening, audio is played:','twice always','as many times as needed','only once','three times','C'),
  tf(16,'"Gist listening" means understanding the general idea rather than every word.','true'),
  tf(17,'A "byline" in journalism gives the editor\'s name.','false'),
  tf(18,'Predicting the type of answer before listening improves comprehension.','true'),
  fb(19,'She delivered a powerful ___ (rebuttal), dismantling each point of the opposing argument.','rebuttal'),
  fb(20,'___ (To summarize), the three key recommendations are efficiency, inclusivity, and sustainability.','To summarize'),
]},

// ── MODULE 20: Society & Global Issues ──────────────────────────────────────

'0ea84827-1c05-461f-8125-98335f5d3447':{pass_threshold:70,questions:[
  mc(1,'Complete: "carbon ___."','footprints','footprint','footing','foot','B'),
  mc(2,'Complete: "greenhouse ___."','gasses','gas','gases — both B and C are correct','gas / gases','D'),
  mc(3,'Complete: "renewable ___."','energy','energies','energized','energetic','A'),
  mc(4,'Complete: "___ emissions."','reduce/cut','reducing','emission','emitting','A'),
  mc(5,'"Biodiversity" refers to:','the study of biology','the variety of plant and animal life in a particular habitat','carbon emissions only','urban development','B'),
  mc(6,'Complete: "The ___ (melting/melt/meld) of Arctic ice is accelerating."','meld','melt','melting','melts','C'),
  mc(7,'"Sustainable development" means:','economic growth at any cost','development meeting current needs without compromising future generations\' needs','environmental protection only','technology only','B'),
  mc(8,'Complete: "The report ___ (warn) of catastrophic consequences if emissions continue unchecked."','warned','warns','warning','warn','B'),
  mc(9,'"Mitigation" vs "adaptation" in climate policy: mitigation means:','adjusting to climate change effects','reducing greenhouse gas emissions to limit warming','ignoring climate change','developing coastal defenses','B'),
  mc(10,'Complete: "Governments must ___ (tackle) climate change with urgent, coordinated action."','tackles','tackling','tackled','tackle','D'),
  tf(11,'"Carbon footprint" refers to the total greenhouse gas emissions caused by an individual or organization.','true'),
  tf(12,'"Renewable energy" sources include coal and natural gas.','false'),
  tf(13,'"Biodiversity" refers only to animal species.','false'),
  fb(14,'Scientists ___ (warn) that we have less than a decade to prevent irreversible climate damage.','warn'),
  fb(15,'Countries must reduce their ___ (carbon footprint) dramatically to meet Paris Agreement targets.','carbon footprint'),
]},

'cd2d121e-ebb4-4211-9354-b76b1b46030b':{pass_threshold:70,questions:[
  mc(1,'Complete: "address ___."','poverty','poor','poorness','poverties','A'),
  mc(2,'Complete: "alleviate ___."','suffering','suffer','suffered','suffers','A'),
  mc(3,'Complete: "bridge the ___."','divide','dividing','divided','division','A'),
  mc(4,'Complete: "combat ___."','inequality','inequal','unequality','inequalities — both A and D','D'),
  mc(5,'Complete: "promote ___."','sustainable development','sustain','sustainment','developed','A'),
  mc(6,'Complete: "tackle ___."','global challenges','global challenge','challenging globally','challenge','A'),
  mc(7,'"Multilateral" agreement involves:','two countries','one country alone','three or more countries or parties','a regional body only','C'),
  mc(8,'Complete: "foster ___."','international cooperation','cooperating internationally','international cooperated','cooperations','A'),
  mc(9,'"Geopolitical" tensions refer to:','environmental issues only','conflicts or disagreements arising from geographic and political factors','economic inequality only','cultural differences only','B'),
  mc(10,'Complete: "The UN ___ (aim) to maintain international peace and security."','aims','aiming','aimed','aim','A'),
  tf(11,'"Alleviate" means to make something worse.','false'),
  tf(12,'"Multilateral" refers to agreements involving three or more parties.','true'),
  tf(13,'"Geopolitical" relates to the influence of geography on political matters.','true'),
  fb(14,'International organizations must ___ (tackle) global challenges through multilateral cooperation.','tackle'),
  fb(15,'The agreement aims to ___ (bridge) the growing economic divide between nations.','bridge'),
]},

'f4860dd4-0099-4bcb-95d9-3921c8ceb928':{pass_threshold:70,questions:[
  mc(1,'Complete: "The government ___ (implement) sweeping reforms to the healthcare system."','implementing','implemented','implements','has implementing','B'),
  mc(2,'"Democracy" is characterized by:','rule by one person','decisions made by citizens through elected representatives','military rule','theocratic governance','B'),
  mc(3,'"Authoritarian" government is characterized by:','free elections and civil liberties','open democratic debate','strong central power with limited political freedoms','decentralized power','C'),
  mc(4,'Complete: "She ___ (advocate) for greater transparency in government spending."','advocating','advocated','advocates','advocate','C'),
  mc(5,'"Legislation" means:','government spending','military action','laws made by a legislative body','a political speech','C'),
  mc(6,'Complete: "The policy ___ (aim) to reduce inequality through progressive taxation."','aimed','aiming','aims','aim','C'),
  mc(7,'"Civil society" refers to:','the military','government institutions','organizations and institutions outside government, like NGOs and charities','only political parties','C'),
  mc(8,'Complete: "The bill ___ (pass) into law after months of debate."','passes','is passing','passed','passing','C'),
  mc(9,'"Referendum" is:','a type of taxation','a direct vote by the public on a specific question','a parliamentary election','a type of legislation','B'),
  mc(10,'Complete: "It ___ (be) widely acknowledged that access to education is a fundamental right."','has','is','was','is widely acknowledged that — correct','D'),
  tf(11,'"Authoritarian" governments typically restrict political freedoms.','true'),
  tf(12,'"Civil society" includes only government institutions.','false'),
  tf(13,'A "referendum" allows citizens to vote directly on a specific issue.','true'),
  fb(14,'The government ___ (implemented) new legislation to reduce corporate tax evasion.','implemented'),
  fb(15,'Civil ___ (society) organizations play a vital role in holding governments accountable.','society'),
]},

'7fcb2100-aac7-42e7-922b-0d9b26f7a73a':{pass_threshold:70,questions:[
  mc(1,'"STEM education" focuses on:','Sport, Technology, Environment, Music','Science, Technology, Engineering, and Mathematics','Social, Text, Economics, Media','Society, Teaching, Ethics, Mentorship','B'),
  mc(2,'Complete: "access ___ quality education."','of','about','into','to','D'),
  mc(3,'"Compulsory education" means:','optional attendance','education that is legally required up to a certain age','higher education only','vocational training','B'),
  mc(4,'Complete: "The literacy ___ (rate/rating/ration) in the region has improved significantly."','rating','ration','rations','rate','D'),
  mc(5,'"Critical thinking" in education means:','memorizing facts','following instructions exactly','evaluating evidence and forming independent judgments','avoiding difficult questions','C'),
  mc(6,'Complete: "The gap between ___ (rich/well-off) and poor in educational outcomes must be addressed."','well-off / rich — both are correct','well-off only','rich only','wealthy only','A'),
  mc(7,'"Curriculum" refers to:','a school building','the subjects and content taught in a school','the school timetable only','after-school activities','B'),
  mc(8,'Complete: "The university ___ (admit) a record number of international students this year."','admitting','admitted','admittance','admits','B'),
  mc(9,'"Inclusive education" means:','education for gifted students only','private schooling','teaching all students, including those with disabilities, in mainstream settings','online education only','C'),
  mc(10,'Complete: "She ___ (earn) a scholarship to study at a leading international university."','earning','earns','earned','earn','C'),
  tf(11,'"Compulsory education" is optional.','false'),
  tf(12,'"Curriculum" refers to the subjects and content taught in an educational institution.','true'),
  tf(13,'"Inclusive education" aims to exclude students with special needs.','false'),
  fb(14,'Improving access ___ (to) quality education is essential for reducing inequality.','to'),
  fb(15,'She ___ (earned) a full scholarship to pursue her doctorate at Oxford.','earned'),
]},

'ea2348ab-9706-468e-8f72-19546e8333d9':{pass_threshold:70,questions:[
  mc(1,'"Systemic" poverty refers to:','poverty caused by individual laziness','poverty caused by isolated incidents','poverty deeply embedded in social, economic, and political systems','temporary financial difficulty','C'),
  mc(2,'Sensitive language for poverty: which is preferred?','The poor','Destitute people','People living in poverty','Paupers','C'),
  mc(3,'"Inequality" in income means:','everyone earns the same','large gaps between high and low earners','moderate differences in income','full employment','B'),
  mc(4,'Complete: "The initiative ___ (aim) to provide affordable housing for low-income families."','aiming','aimed','aim','aims','D'),
  mc(5,'"Social mobility" means:','physical movement between cities','the ability to move between different socioeconomic positions','social media activity','cultural exchange','B'),
  mc(6,'Complete: "More than 700 million people ___ (live) in extreme poverty."','lives','lived','living','live','D'),
  mc(7,'"Disproportionately" means:','equally distributed','randomly','affecting some groups much more than others','fairly shared','C'),
  mc(8,'"Food insecurity" means:','a shortage of food products in supermarkets','lack of reliable access to sufficient nutritious food','high food prices only','food waste','B'),
  mc(9,'Complete: "She was the first in her family to ___ (break) the cycle of poverty."','breaking','broke','breaks','break','D'),
  mc(10,'"Marginalized communities" are those:','with the most political power','at the center of society','that are pushed to the edges and excluded from mainstream society','with the most economic resources','C'),
  tf(11,'Using "people living in poverty" rather than "the poor" is recommended sensitive language.','true'),
  tf(12,'"Social mobility" refers to physical movement between cities.','false'),
  tf(13,'"Disproportionate impact" means the impact is spread equally among all groups.','false'),
  fb(14,'___ (Social mobility) allows individuals to move to higher socioeconomic positions through education and work.','Social mobility'),
  fb(15,'Food ___ (insecurity) affects millions of people, even in wealthy countries.','insecurity'),
]},

'761c66b6-4a09-423a-9f8f-7df63ec11e62':{pass_threshold:70,questions:[
  mc(1,'"Universal Declaration of Human Rights" was adopted by:','NATO','the European Union','the United Nations','the World Bank','C'),
  mc(2,'Complete: "Everyone has the right to ___ (freedom) of expression."','free','freely','freed','freedom','D'),
  mc(3,'"Human dignity" means:','the right to luxury','the right to work','the inherent worth and respect owed to every person','physical health only','C'),
  mc(4,'Complete: "Human rights are ___ (universal/universally/universe/universalize) — they apply to all people."','universally','universe','universalize','universal','D'),
  mc(5,'"Genocide" is defined as:','a minor crime','peaceful protest','a natural disaster','acts committed with intent to destroy a national, ethnic, or religious group','D'),
  mc(6,'Complete: "The NGO ___ (campaign) for the release of political prisoners."','campaign','campaigned','campaigns','campaigning','C'),
  mc(7,'"Asylum seeker" is someone who:','travels for tourism','has permanent residency','requests protection in another country because of persecution at home','is an economic migrant','C'),
  mc(8,'Complete: "These rights are ___ (inalienable/inalienably/alienate/unalienable) — they cannot be taken away."','inalienably','alienate','unalienable — also accepted','inalienable','D'),
  mc(9,'"Ratify" a treaty means:','to reject it','to modify it','to formally confirm and approve it','to draft it','C'),
  mc(10,'Complete: "The government ___ (violate) international human rights law by detaining protesters."','violating','violated','violation','violates','B'),
  tf(11,'Human rights are universal and apply to all people.','true'),
  tf(12,'An "asylum seeker" is someone who travels for business purposes.','false'),
  tf(13,'"Ratify" a treaty means to formally approve and confirm it.','true'),
  fb(14,'Every person has the right to ___ (dignity) and equal treatment before the law.','dignity'),
  fb(15,'The country ___ (ratified) the treaty on refugee rights in 2018.','ratified'),
]},

'deb1a4bd-5b71-46c6-9d4f-abc74b0c2548':{pass_threshold:70,questions:[
  mc(1,'Complete: "Society is ___ (undergo) rapid transformation due to technological disruption."','undergoing','undergo','undergoes','undergone','A'),
  mc(2,'"Polarization" of society means:','bringing society together','division into two extreme opposing groups','moderate political views','economic growth','B'),
  mc(3,'Complete: "AI is ___ (predict) to transform the labour market within the next decade."','predicted','predicting','predict','prediction','A'),
  mc(4,'"Intergenerational equity" means:','equal rights for all genders','fair treatment between different professions','ensuring future generations have the same opportunities as today\'s','distributing wealth within one generation','C'),
  mc(5,'Complete: "The ___ (digital/digitalize/digitalization) divide refers to inequality in access to technology."','digitalize','digitalization','digital divide — "digital" is the adjective','digital','D'),
  mc(6,'"Demographic change" includes:','technological advances','shifts in population structure (age, birth rate, migration)','political reform','cultural trends only','B'),
  mc(7,'Complete: "Urbanization ___ (lead) to growing demand for infrastructure."','led','leads','leading','lead','B'),
  mc(8,'"Civic engagement" means:','avoiding political issues','participating in democratic and community life','following social media','working for the government','B'),
  mc(9,'Complete: "It is crucial that societies ___ (adapt) to the challenges of the 21st century."','adapts','adapted','adapting','adapt','D'),
  mc(10,'"Meritocracy" means a system where:','wealth is inherited','people succeed based on their talent and effort','all resources are equally distributed','success depends on social connections','B'),
  tf(11,'"Polarization" of society refers to increasing division into extreme opposing groups.','true'),
  tf(12,'"Intergenerational equity" is concerned only with the current generation.','false'),
  tf(13,'"Civic engagement" involves active participation in community and democratic life.','true'),
  fb(14,'Rising ___ (urbanization) is placing enormous pressure on city infrastructure worldwide.','urbanization'),
  fb(15,'A true ___ (meritocracy) rewards talent and hard work regardless of background.','meritocracy'),
]},

'6ba6976b-a83d-401e-86bb-d42c47c93b74':{pass_threshold:80,questions:[
  mc(1,'Complete: "carbon ___."','footing','footprints','footprint','foot','C'),
  mc(2,'Complete: "renewable ___."','energetic','energies','energized','energy','D'),
  mc(3,'"Biodiversity" refers to:','energy production','the variety of life in an ecosystem','carbon emissions','soil quality','B'),
  mc(4,'Complete: "tackle ___."','challenge','challenged','global challenges','challenging globally','C'),
  mc(5,'"Multilateral" means involving:','one country','two countries','three or more countries or parties','only regional bodies','C'),
  mc(6,'"Democracy" is characterized by:','rule by one person','military power','theocratic rule','governance through elected representatives','D'),
  mc(7,'Complete: "The bill ___ (pass) into law after a lengthy parliamentary debate."','passes','is passing','passing','passed','D'),
  mc(8,'"Systemic" poverty is caused by:','individual poor choices only','isolated incidents','deep flaws in social, economic, and political systems','bad luck','C'),
  mc(9,'Sensitive language: "people living in poverty" vs "the poor" — which is preferred?','The poor','Paupers','Poor people','People living in poverty','D'),
  mc(10,'"Inalienable" rights are:','rights that can be taken away','rights that can be sold','rights that apply only to citizens','rights that cannot be taken away','D'),
  mc(11,'Complete: "She was the first in her family to ___ the cycle of poverty."','breaking','breaks','broke','break','D'),
  mc(12,'"Social mobility" means:','physical movement between cities','ability to change socioeconomic position','social media influence','cultural exchange','B'),
  mc(13,'"Civic engagement" means:','avoiding political issues','following social media','working only for the government','participating in democratic and community life','D'),
  mc(14,'"Meritocracy" rewards people based on:','social connections','inherited wealth','talent and effort','family background','C'),
  mc(15,'Complete: "It is crucial that societies ___ (adapt) to 21st-century challenges."','adapts','adapted','adapting','adapt','D'),
  tf(16,'"Asylum seeker" is someone requesting protection due to persecution in their home country.','true'),
  tf(17,'"Ratify" a treaty means to reject it.','false'),
  tf(18,'"Polarization" of society refers to increasing division between opposing groups.','true'),
  fb(19,'Rising ___ (urbanization) is placing enormous strain on housing and infrastructure.','urbanization'),
  fb(20,'Every person has the right to ___ (dignity) and equal treatment under international law.','dignity'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 17: "Reading Skills"', lessons: ['a399cd62-703b-4e4e-ba3e-e8a0ad01cf64','dd228807-f223-4d72-8879-e2b6c66bb773','0c3267e7-67e0-41af-ab32-081a57cc9118','dca11e5c-3ac6-42c9-8704-d77987e6cf04','d7fca742-0479-4226-b423-ae497389fbb6','97b9cbe6-24c0-4510-863a-04138cf207a7','6a4b2b4f-f125-40db-8814-520dee176d71','b4d6430b-847f-40d8-8dca-0cb2c5c925cb'] },
  { name: 'Module 18: "Writing Skills"', lessons: ['2cc71093-8711-416c-860c-1a1603de8d07','d2445eca-dc2b-45bf-a6c6-af7d0424cb56','e2dcfa1d-c4ea-456d-87ab-b2b7bc5fcc27','b40df151-64cd-438d-a89b-a253b27b2570','cf91f622-1d07-4fbe-a33c-ae929b27c1ea','c0bc0840-f124-4bcf-a1a0-b5b86a40cb4c','77e87dfc-e687-4489-9e8b-3d513d36c0e8','0d5ab1e1-5baf-4c6b-a845-e5b188110e83'] },
  { name: 'Module 19: "Listening & Speaking"', lessons: ['1a3a5665-9937-401b-9ce3-ddc2555a1124','3ea326f1-3e58-41f0-8e98-b6e01c95baee','87cb6e14-3c25-41ea-b1ab-0c6c4606e547','1a66e0d9-dab0-433d-9203-8aa34500be78','7c0002fa-499e-4482-aaa3-950de710ba12','61f9c39c-6e31-4311-a8f6-b7471114fcc2','27d48a15-66ba-4fab-9a52-15cb00ef91ec','cabd24a3-66e9-41b5-8956-71febc3911be'] },
  { name: 'Module 20: "Society & Global Issues"', lessons: ['0ea84827-1c05-461f-8125-98335f5d3447','cd2d121e-ebb4-4211-9354-b76b1b46030b','f4860dd4-0099-4bcb-95d9-3921c8ceb928','7fcb2100-aac7-42e7-922b-0d9b26f7a73a','ea2348ab-9706-468e-8f72-19546e8333d9','761c66b6-4a09-423a-9f8f-7df63ec11e62','deb1a4bd-5b71-46c6-9d4f-abc74b0c2548','6ba6976b-a83d-401e-86bb-d42c47c93b74'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 17–20 B2 Upper-Intermediate');
}
main();
