import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 5: Friendship & People ───────────────────────────────────────────

'e8eec0f5-3c5e-4d40-b522-2039eb673a75':{pass_threshold:70,questions:[
  mc(1,'Which verb is followed by a GERUND?','want','plan','enjoy','decide','C'),
  mc(2,'Complete: "She enjoys ___ in the park."','run','to run','ran','running','D'),
  mc(3,'Which verb is followed by TO-INFINITIVE?','avoid','finish','miss','manage','D'),
  mc(4,'Complete: "He managed ___ the exam."','pass','passing','passed','to pass','D'),
  mc(5,'Which verb can be followed by BOTH gerund and infinitive with no meaning change?','deny','suggest','start','admit','C'),
  mc(6,'Complete: "She denied ___ the report."','to steal','steal','stolen','stealing','D'),
  mc(7,'Complete: "I hope ___ you soon."','see','seeing','seen','to see','D'),
  mc(8,'Complete: "Would you mind ___ the window?"','close','to close','closed','closing','D'),
  mc(9,'Complete: "She admitted ___ the mistake."','make','to make','made','making','D'),
  mc(10,'Complete: "They decided ___ a new strategy."','adopt','adopting','adopted','to adopt','D'),
  tf(11,'"I suggested to go to the cinema" is grammatically correct.','false'),
  tf(12,'"She agreed to help" is correct (agree + to-infinitive).','true'),
  tf(13,'"He avoided to make eye contact" is grammatically correct.','false'),
  fb(14,'She finished ___ (writing) the essay at midnight.','writing'),
  fb(15,'He refused ___ (to answer) any questions.','to answer'),
]},

'b67cd65b-52d0-417d-9ebf-739cfd93027b':{pass_threshold:70,questions:[
  mc(1,'"I remember meeting her." — what does this mean?','I will remember to meet her.','I have a memory of meeting her.','I forgot to meet her.','I must meet her.','B'),
  mc(2,'"Remember to call her." means:','I recall calling her.','You must call her (future obligation).','You are calling her now.','You called her.','B'),
  mc(3,'"She stopped smoking." means:','She paused in order to smoke.','She quit smoking permanently.','She started smoking.','She was about to smoke.','B'),
  mc(4,'"She stopped to smoke." means:','She quit smoking.','She paused in order to have a cigarette.','She had smoked.','She will smoke.','B'),
  mc(5,'"I tried fixing the computer." — what does this mean?','I attempted but may have failed.','I experimented by fixing it to see if it worked.','I succeeded in fixing it.','I was asked to fix it.','B'),
  mc(6,'"I forgot posting the letter." means:','I forgot that I needed to post it.','I forgot that I had already posted it.','I will forget to post it.','I never posted it.','B'),
  mc(7,'"I forgot to post the letter." means:','I forgot that I had already posted it.','I forgot that I needed to post it.','I remembered to post it.','I never forget to post.','B'),
  mc(8,'"She went on to become a doctor." means:','She continued studying.','She subsequently became a doctor (after something else).','She became a doctor and then stopped.','She was going to become a doctor.','B'),
  mc(9,'"I regret to inform you that..." is used to:','express a past regret','deliver bad news formally','make a complaint','give advice','B'),
  mc(10,'"I regret telling him the secret." means:','I will tell him the secret.','I wish I hadn\'t told him the secret.','I told him the secret correctly.','I never told him.','B'),
  tf(11,'"Stop + -ing" means to cease; "stop + to-infinitive" means to pause in order to do something.','true'),
  tf(12,'"I regret to tell you" is used for past regrets.','false'),
  tf(13,'"Try + -ing" = experiment; "try + to-infinitive" = attempt.','true'),
  fb(14,'Don\'t forget ___ (to lock) the door before you leave.','to lock'),
  fb(15,'I remember ___ (meeting) him at the conference last year.','meeting'),
]},

'a491012a-2ce9-40d5-8a02-a5203dac818a':{pass_threshold:70,questions:[
  mc(1,'"Tenacious" means:','easily giving up','shy and reserved','persistent and determined','reckless and careless','C'),
  mc(2,'"Meticulous" describes someone who:','is careless about details','speaks very eloquently','avoids social interaction','pays very careful attention to details','D'),
  mc(3,'"Eloquent" describes someone who:','writes poorly','is very shy','expresses ideas clearly and effectively','lacks confidence','C'),
  mc(4,'"Charismatic" describes a person who:','has a powerful and attractive personality','is very introverted','is overly critical','avoids public speaking','A'),
  mc(5,'"Shrewd" means:','naive and trusting','easily deceived','having sharp practical judgment','indifferent to results','C'),
  mc(6,'"Pragmatic" means:','idealistic and unrealistic','sentimental','focused purely on theory','practical and focused on results','D'),
  mc(7,'"Resilient" describes someone who:','falls apart under pressure','recovers quickly from difficulties','avoids all challenges','complains frequently','B'),
  mc(8,'"Pedantic" describes someone who:','ignores rules completely','is spontaneous','makes creative leaps','is excessively focused on minor details and rules','D'),
  mc(9,'"Gregarious" means:','preferring to be alone','enjoying the company of others, sociable','being strict and disciplined','being aggressive','B'),
  mc(10,'What is the opposite of "introverted"?','pedantic','tenacious','extroverted','meticulous','C'),
  tf(11,'"Empathetic" means understanding and sharing the feelings of others.','true'),
  tf(12,'"Shrewd" always has a negative connotation.','false'),
  tf(13,'"Eloquent" refers specifically to written communication only.','false'),
  fb(14,'Despite the setbacks, she remained ___ (resilient) throughout the crisis.','resilient'),
  fb(15,'His ___ (charismatic) personality made him a natural leader.','charismatic'),
]},

'219a92bc-24e6-4fbb-a84c-bb8fe4b48b0e':{pass_threshold:70,questions:[
  mc(1,'The prefix "im-" as in "impossible" means:','too much','again','not','under','C'),
  mc(2,'The prefix "over-" in "overconfident" means:','not enough','wrongly','again','too much','D'),
  mc(3,'Which word uses "mis-" correctly?','misunderstand','misable','misfully','misment','A'),
  mc(4,'The suffix "-ness" forms:','verbs','adjectives','adverbs','nouns','D'),
  mc(5,'The suffix "-ful" means:','without','relating to','not','full of','D'),
  mc(6,'The suffix "-less" means:','full of','again','relating to','without','D'),
  mc(7,'The prefix "re-" means:','not','under','wrongly','again','D'),
  mc(8,'The prefix "under-" in "underestimate" means:','too much','again','wrongly','not enough','D'),
  mc(9,'Which suffix creates ADJECTIVES from nouns or verbs?','-ment','-tion','-ness','-ive','D'),
  mc(10,'The prefix "un-" as in "unhappy" means:','too much','not','wrongly','again','B'),
  tf(11,'"Un-" and "dis-" can both negate adjectives and verbs.','true'),
  tf(12,'"Overwork" means to work insufficiently.','false'),
  tf(13,'Adding "-ity" to "responsible" gives "responsibility."','true'),
  fb(14,'She was ___ (misunderstood) by her colleagues, who thought she was arrogant.','misunderstood'),
  fb(15,'His ___ (carelessness) caused several errors in the report.','carelessness'),
]},

'bb165347-799f-47f2-bb23-932c3d01e6ff':{pass_threshold:70,questions:[
  mc(1,'"They hit it off immediately." means:','they argued right away','they ignored each other','they liked each other right away','they ended their friendship','C'),
  mc(2,'"We don\'t see eye to eye on this issue." means:','we agree completely','we disagree','we can\'t see each other','we are competitive','B'),
  mc(3,'"She gets on my nerves." means:','she calms me down','she helps me','she annoys me','she supports me','C'),
  mc(4,'"He gave me the cold shoulder." means:','he greeted me warmly','he gave me cold food','he ignored me deliberately','he apologized','C'),
  mc(5,'"Don\'t burn your bridges." means:','don\'t start fires','don\'t travel far','don\'t cross bridges','don\'t destroy valuable relationships','D'),
  mc(6,'"They buried the hatchet." means:','they hid a weapon','they started a new fight','they continued arguing','they reconciled after a dispute','D'),
  mc(7,'"She keeps people at arm\'s length." means:','she is very close to people','she maintains emotional distance','she hugs people','she pushes people physically','B'),
  mc(8,'"He wears his heart on his sleeve." means:','he hides his feelings','he is very private','he expresses his emotions openly','he avoids relationships','C'),
  mc(9,'"They fell out over money." means:','they cooperated','they had an argument and became estranged','they discussed money calmly','they agreed on finances','B'),
  mc(10,'"They patched things up." means:','they damaged their relationship','they argued again','they avoided each other','they repaired their relationship','D'),
  tf(11,'"Hit it off" means to have an immediate positive connection.','true'),
  tf(12,'"Bury the hatchet" means to continue a fight aggressively.','false'),
  tf(13,'"Give someone the cold shoulder" is a friendly gesture.','false'),
  fb(14,'After years of arguing, the brothers finally ___ (buried the hatchet).','buried the hatchet'),
  fb(15,'Although she was upset, she didn\'t ___ (burn her bridges) with the company.','burn her bridges'),
]},

'666c15e4-39f0-494c-baf5-6960d6b98bfc':{pass_threshold:70,questions:[
  mc(1,'Complete the collocation: "make ___."','friendly','friendship','friend','friends','D'),
  mc(2,'Complete: "keep in ___."','place','mind','time','touch','D'),
  mc(3,'Complete: "lose ___."','contact','mind','friends','touch','D'),
  mc(4,'Complete: "build ___." (develop positive professional relationship)','friend','bond','touch','rapport','D'),
  mc(5,'Complete: "break the ___." (start a social interaction)','pattern','rules','silence','ice','D'),
  mc(6,'Complete: "expand one\'s ___." (meet more professional contacts)','friendship','group','circle','network','D'),
  mc(7,'A "close-knit community" is:','a community with little interaction','a new community','a large diverse community','a community with strong bonds','D'),
  mc(8,'Complete: "She maintained a strong ___ with her mentor."','friendship','network','rapport','bond','C'),
  mc(9,'Complete: "She struggled to ___ her new colleagues."','get along with','get along','along with','get with','A'),
  mc(10,'"Networking" professionally means:','using a computer network','managing social media','forming a sports team','building and maintaining professional relationships','D'),
  tf(11,'"Keep in touch" and "lose touch" are antonyms.','true'),
  tf(12,'"Break the ice" means to end a relationship suddenly.','false'),
  tf(13,'"Close-knit" always has a negative connotation.','false'),
  fb(14,'It can be hard to ___ (make friends) when you move to a new city.','make friends'),
  fb(15,'He tried to ___ (break the ice) by telling a joke.','break the ice'),
]},

'd456ef6c-f3f0-43d0-b625-157d23819e93':{pass_threshold:70,questions:[
  mc(1,'"Altruistic" describes someone who:','is selfish','is highly competitive','avoids responsibility','is primarily concerned with the welfare of others','D'),
  mc(2,'"Magnanimous" means:','petty and vindictive','overly strict','easily angered','generous and forgiving, especially toward a rival','D'),
  mc(3,'"Indefatigable" means:','easily tired','very lazy','quick to give up','unable to be tired out, tireless','D'),
  mc(4,'"Perspicacious" means:','lacking judgment','very talkative','emotionally sensitive','having sharp insight and shrewd judgment','D'),
  mc(5,'"Formidable" describes someone or something:','weak and unimpressive','very ordinary','lacking confidence','inspiring awe through impressive capability','D'),
  mc(6,'"Steadfast" means:','inconsistent and changeable','careless and impulsive','overly emotional','resolutely firm and unwavering','D'),
  mc(7,'"Audacious" means:','very cautious','risk-averse','showing boldness to take risks or challenge convention','overly conventional','C'),
  mc(8,'"Conscientious" describes someone who:','is careless','avoids responsibility','ignores instructions','takes care to do things correctly','D'),
  mc(9,'"Compassionate" means:','indifferent to suffering','feeling or showing sympathy for others','unconcerned with others','dismissive of problems','B'),
  mc(10,'Which word is closest in meaning to "innovative"?','conventional','traditional','conservative','pioneering','D'),
  tf(11,'"Altruistic" and "selfish" are antonyms.','true'),
  tf(12,'"Indefatigable" has a negative connotation.','false'),
  tf(13,'"Formidable" can have a positive meaning when describing impressive qualities.','true'),
  fb(14,'She was ___ (steadfast) in her commitment despite the obstacles.','steadfast'),
  fb(15,'His ___ (audacious) plan surprised everyone, but it worked.','audacious'),
]},

'a4090650-cdd0-4692-a5af-06c026e91b0e':{pass_threshold:80,questions:[
  mc(1,'Which verb is followed by a GERUND?','want','plan','hope','enjoy','D'),
  mc(2,'"She stopped to smoke." means:','She quit smoking.','She paused in order to have a cigarette.','She will smoke later.','She had smoked.','B'),
  mc(3,'"I remember meeting him" — "meeting" is:','a gerund meaning a recalled memory','a gerund expressing future action','an infinitive','a present participle','A'),
  mc(4,'"She admitted ___ the error." (gerund)','to make','make','making','made','C'),
  mc(5,'"Tenacious" means:','shy','reckless','generous','persistent and determined','D'),
  mc(6,'"Meticulous" means:','impulsive','paying careful attention to details','overly confident','speaking eloquently','B'),
  mc(7,'The prefix "over-" in "overconfident" means:','not','again','wrongly','too much','D'),
  mc(8,'The suffix "-less" means:','full of','relating to','again','without','D'),
  mc(9,'"They hit it off." means:','they argued','they ignored each other','they ended the friendship','they liked each other right away','D'),
  mc(10,'"Bury the hatchet" means:','start a new conflict','ignore each other','compete more aggressively','reconcile after a dispute','D'),
  mc(11,'Complete: "build ___." (professional relationship)','friend','touch','circle','rapport','D'),
  mc(12,'"Altruistic" describes someone primarily concerned with:','their own success','status and prestige','material wealth','the welfare of others','D'),
  mc(13,'"She went on ___ a successful author." (subsequently became)','becoming','to become','became','become','B'),
  mc(14,'"I tried ___ the door but it was locked." (experiment)','to open','open','opened','opening','D'),
  mc(15,'"Steadfast" means:','changeable','impulsive','emotional','resolutely firm and unwavering','D'),
  tf(16,'"Try + gerund" = experiment to see if it works; "try + to-infinitive" = make an effort/attempt.','true'),
  tf(17,'"Shrewdness" (noun) comes from the adjective "shrewd."','true'),
  tf(18,'"Keep in touch" and "lose touch" are synonyms.','false'),
  fb(19,'She ___ (refused to answer) any questions during the interview.','refused to answer'),
  fb(20,'His ___ (resilience) helped him overcome every obstacle.','resilience'),
]},

// ── MODULE 6: Work & Business ────────────────────────────────────────────────

'c74efe4e-7968-424c-a61d-58b6c3633da6':{pass_threshold:70,questions:[
  mc(1,'"Must" expresses:','permission','possibility','strong obligation or logical necessity','past ability','C'),
  mc(2,'"May" expresses:','strong obligation','past ability','certainty','possibility or formal permission','D'),
  mc(3,'"Should" expresses:','certainty','past ability','impossibility','recommendation or mild obligation','D'),
  mc(4,'Which modal expresses ABILITY?','must','may','will','can','D'),
  mc(5,'"It\'s not necessary to submit Form B." — which modal is correct?','You mustn\'t submit it.','You couldn\'t submit it.','You shouldn\'t submit it.','You don\'t have to submit it.','D'),
  mc(6,'"Mustn\'t" vs "don\'t have to" — key difference?','No difference','Mustn\'t = not allowed; don\'t have to = not necessary','Mustn\'t = not necessary; don\'t have to = not allowed','Both express prohibition','B'),
  mc(7,'"Could you pass the report?" expresses:','past ability','impossibility','obligation','a polite request','D'),
  mc(8,'"Ought to" is closest in meaning to:','can','must','may','should','D'),
  mc(9,'Complete: "You ___ be exhausted after the presentation." (logical deduction)','can','may','will','must','D'),
  mc(10,'"She was able to finish early." expresses:','past possibility','past necessity','past permission','past specific achievement','D'),
  tf(11,'"Mustn\'t" and "don\'t have to" have the same meaning.','false'),
  tf(12,'"Could" can be used for both past ability and polite requests.','true'),
  tf(13,'"Might" expresses slightly less certainty than "may."','true'),
  fb(14,'She ___ (must) be the new manager — she has the director\'s pass.','must'),
  fb(15,'You ___ (don\'t have to) attend the meeting if you\'re busy.','don\'t have to'),
]},

'28c4f1c3-31a7-458e-b6bb-1ff4956c9100':{pass_threshold:70,questions:[
  mc(1,'"She must have worked late." expresses:','past ability','possibility about the past','logical deduction about a past action','criticism of a past action','C'),
  mc(2,'"He might have missed the train." expresses:','certainty he missed it','he definitely didn\'t miss it','he was able to miss it','possibility he missed it','D'),
  mc(3,'"You should have told me!" expresses:','past certainty','past ability','past permission','criticism of a past action not done','D'),
  mc(4,'"She can\'t have been there." expresses:','past ability','possibility','certainty about the past','logical impossibility about the past','D'),
  mc(5,'"You needn\'t have bought flowers." expresses:','you were right to buy them','you forgot to buy them','you were unable to buy them','it wasn\'t necessary, but you did it anyway','D'),
  mc(6,'"He could have helped but didn\'t." expresses:','it was impossible','he was obliged to help','he accidentally helped','he had the ability but chose not to','D'),
  mc(7,'"They may have left already." expresses:','certainty they left','they definitely didn\'t leave','obligation to leave','possibility they left','D'),
  mc(8,'Complete: "She looks exhausted. She ___ have slept well."','must not','can not','might not','couldn\'t not','C'),
  mc(9,'Complete: "The lights are off. They ___ have gone home."','might','can','should','must','D'),
  mc(10,'"You shouldn\'t have said that." means:','you said it and it was a mistake','you were unable to say it','you didn\'t say it','you had permission to say it','A'),
  tf(11,'"Must have" is used for logical deduction about the past.','true'),
  tf(12,'"Needn\'t have done" means the action was necessary but wasn\'t done.','false'),
  tf(13,'"Can\'t have" expresses logical impossibility in the past.','true'),
  fb(14,'She ___ (must have been) nervous — her hands were shaking.','must have been'),
  fb(15,'You ___ (shouldn\'t have) interrupted him in the middle of his speech.','shouldn\'t have'),
]},

'cbf9658e-2bc9-43b7-8606-3147fbcb4c92':{pass_threshold:70,questions:[
  mc(1,'"Ought to have done" is most similar to:','must have done','could have done','might have done','should have done','D'),
  mc(2,'"Was supposed to have finished by Friday." means:','it was expected but may not have happened','it was impossible','it was forbidden','it definitely happened','A'),
  mc(3,'Complete: "He ___ arrived by now. Where is he?"','must have','should have','might to have','can have','B'),
  mc(4,'"She was meant to present, but fell ill." — "was meant to" expresses:','a past prohibition','an arrangement or expectation that didn\'t happen','past certainty','past ability','B'),
  mc(5,'Complete: "I ___ (ability, past, specific) solve the problem after hours of effort."','could','might','was able to','should','C'),
  mc(6,'Which is correct for a past PROHIBITION?','She might not have gone.','She couldn\'t have been.','She was not allowed to enter.','She needn\'t have attended.','C'),
  mc(7,'Complete: "He ___ the report on time, but he procrastinated." (ability, didn\'t use it)','should have submitted','could have submitted','might have submitted','must have submitted','B'),
  mc(8,'"We needn\'t have rushed — the flight was delayed." — the implication is:','we rushed, and it was the right thing to do','we rushed, but it was unnecessary','we didn\'t rush enough','we should have rushed more','B'),
  mc(9,'Modal Perfect "may have + past participle" expresses:','certainty','past ability','past obligation','50/50 possibility about the past','D'),
  mc(10,'Complete: "She can\'t ___ the email — her account was offline."','have sent','has sent','sent','be sending','A'),
  tf(11,'"Should have" and "ought to have" have essentially the same meaning.','true'),
  tf(12,'"Could have" always means the action was completed.','false'),
  tf(13,'"Was supposed to" implies an expectation that may not have been fulfilled.','true'),
  fb(14,'You ___ (needn\'t have waited) — I told you I\'d be late.','needn\'t have waited'),
  fb(15,'He ___ (could have been) promoted earlier if he had asked.','could have been'),
]},

'aa422023-0db4-41da-b403-8ff6c1db8e27':{pass_threshold:70,questions:[
  mc(1,'Which phrase is appropriate to open a formal professional email?','Hey there,','I am writing to inform you...','Just dropping a note...','Thought I\'d reach out...','B'),
  mc(2,'Which closing is most formal?','Cheers,','Talk soon,','Yours sincerely,','See you,','C'),
  mc(3,'"Yours faithfully" is used when:','you know the recipient\'s name','it\'s a casual email','the email is internal','you don\'t know the recipient\'s name (Dear Sir/Madam)','D'),
  mc(4,'Which phrase politely requests action?','Do it immediately.','I want you to send this.','Please could you send me the report?','Send it now.','C'),
  mc(5,'Which is the most appropriate formal way to reference an attachment?','FYI, attached.','See attached.','Please find attached the relevant document.','Here it is.','C'),
  mc(6,'Which phrase formally indicates a purpose?','Just to say...','I am writing to request clarification on...','Wanted to ask...','BTW...','B'),
  mc(7,'Which phrase is a formal follow-up?','Chasing this up.','Just checking in.','I would be grateful for a response at your earliest convenience.','Any update?','C'),
  mc(8,'Which phrase formally declines an invitation?','No thanks.','Can\'t make it.','Unfortunately, I am unable to attend.','I\'m busy.','C'),
  mc(9,'Which phrase formally expresses agreement?','Sure, no problem.','That works.','I concur with your assessment.','Sounds good.','C'),
  mc(10,'"As per our previous correspondence" means:','ignoring our previous conversation','as we discussed/agreed previously','something completely new','a contradiction of what was discussed','B'),
  tf(11,'"I look forward to hearing from you" is a standard formal email closing.','true'),
  tf(12,'"Yours sincerely" is used when you don\'t know the recipient\'s name.','false'),
  tf(13,'"Please do not hesitate to contact me" is a formal way to invite further communication.','true'),
  fb(14,'___ (Please find attached) the updated contract for your review.','Please find attached'),
  fb(15,'I look forward to ___ (hearing) from you at your earliest convenience.','hearing'),
]},

'730580e9-974b-41d9-a43a-f9373544fb20':{pass_threshold:70,questions:[
  mc(1,'Which is the correct structure for a formal business email?','greeting / purpose / body / closing / sign-off','hello / chat / bye','subject only','signature first','A'),
  mc(2,'"Executive summary" means:','a detailed full report','a financial spreadsheet','a brief overview of key points','a meeting agenda','C'),
  mc(3,'Which phrase is used to formally introduce a topic?','I wanted to chat about...','Regarding the matter of...','So, about that thing...','Just quickly...','B'),
  mc(4,'Which linking word shows CONTRAST in formal writing?','Furthermore','In addition','Nevertheless','Moreover','C'),
  mc(5,'Which linking word adds information in formal writing?','However','Nevertheless','Although','Furthermore','D'),
  mc(6,'Which phrase formally acknowledges a previous email?','Got your email.','Thank you for your email of 5th May.','Saw your message.','Re: your note.','B'),
  mc(7,'Which phrase is used to formally conclude a business email?','Please see attached and let me know.','Should you require any further information, please do not hesitate to contact me.','Call if you need anything.','Attached. Thanks.','B'),
  mc(8,'Complete: "I ___ (write) to enquire about the vacancy advertised on your website."','wrote','writing','am writing','was writing','C'),
  mc(9,'In business writing, "cc" stands for:','confirmed copy','carbon copy (copy sent to others)','current contact','circular communication','B'),
  mc(10,'Which phrase formally requests a meeting?','Can we meet?','I would like to schedule a meeting at your convenience.','Meet me tomorrow.','Let\'s catch up.','B'),
  tf(11,'Business emails should generally use shorter sentences than academic writing.','true'),
  tf(12,'"Dear Sir or Madam" is used when you know the recipient\'s name.','false'),
  tf(13,'"I am writing to follow up on our previous discussion" is a common business email opener.','true'),
  fb(14,'___ (With reference to) your inquiry of 3rd May, please find our response below.','With reference to'),
  fb(15,'I look forward to ___ (meeting) you at the conference next week.','meeting'),
]},

'030847c6-385c-45a6-9d4e-49575ef8ef1a':{pass_threshold:70,questions:[
  mc(1,'In negotiations, "to reach a compromise" means:','to win completely','to refuse to negotiate','to make concessions on both sides to reach agreement','to end the negotiation','C'),
  mc(2,'Which phrase is used to make an offer in a negotiation?','Take it or leave it.','We\'d be willing to offer...','That\'s our final position.','We refuse to budge.','B'),
  mc(3,'"Let\'s table this for now." means:','let\'s decide now','let\'s discuss this topic later','let\'s put it in writing','let\'s raise the price','B'),
  mc(4,'"To haggle" means:','to agree immediately','to argue about price in a back-and-forth manner','to set a fixed price','to refuse to sell','B'),
  mc(5,'Which phrase signals you want to return to a previous topic?','Going forward...','Let\'s circle back to...','I\'d like to raise a new issue...','Let\'s conclude...','B'),
  mc(6,'Which phrase makes a conditional offer?','Our price is fixed.','We can agree to X, provided that Y.','We refuse to compromise.','Take it or leave it.','B'),
  mc(7,'"Best alternative to a negotiated agreement" (BATNA) refers to:','your best offer','your preferred outcome','what you will do if negotiations fail','your opening position','C'),
  mc(8,'"To leverage" in business means:','to reduce costs','to use something to maximum advantage','to negotiate poorly','to walk away from a deal','B'),
  mc(9,'Which phrase politely pushes back on a price?','That\'s too expensive.','No way.','I\'m afraid that falls outside our budget.','We can\'t afford it.','C'),
  mc(10,'"Win-win outcome" in negotiations means:','one party gets everything','both parties gain acceptable benefits','negotiations fail','one party loses entirely','B'),
  tf(11,'"To reach a deadlock" means both sides have agreed.','false'),
  tf(12,'"Our hands are tied" means we have no flexibility.','true'),
  tf(13,'"To go back to the drawing board" means to start again from scratch.','true'),
  fb(14,'We ___ (would be willing to) consider a longer payment schedule.','would be willing to'),
  fb(15,'Let\'s ___ (reach a compromise) that works for both parties.','reach a compromise'),
]},

'575ae15d-c871-4036-8c66-079eab9d323b':{pass_threshold:70,questions:[
  mc(1,'Complete the collocation: "launch a ___."','product/campaign/startup','launching','launched','launch','A'),
  mc(2,'Complete: "___ a risk." (take a calculated risk)','make','take','do','get','B'),
  mc(3,'Complete: "secure ___."','funding','fundings','funded','fund','A'),
  mc(4,'Complete: "___ market share."','gain','make','get','take','A'),
  mc(5,'Complete: "meet a ___."','deadline','deadlined','lining','dead','A'),
  mc(6,'Complete: "disrupt the ___."','market','marketing','marketer','markets','A'),
  mc(7,'A "startup" is:','an established multinational','a government agency','a newly founded business venture','a non-profit organization','C'),
  mc(8,'"Scale a business" means:','reduce its size','close the business','grow it significantly while maintaining efficiency','change its name','C'),
  mc(9,'Complete: "generate ___."','revenue','revenues','revenued','revenueing','A'),
  mc(10,'A "pitch" in business is:','a sports field','a financial report','a presentation to investors to secure funding','a legal document','C'),
  tf(11,'"Bootstrap a startup" means to grow it using external venture capital.','false'),
  tf(12,'"Pivot" in business means to change direction or business model.','true'),
  tf(13,'"ROI" stands for "Return on Investment."','true'),
  fb(14,'They secured ___ (funding) from three major investors.','funding'),
  fb(15,'The team worked hard to ___ (meet the deadline) for the product launch.','meet the deadline'),
]},

'ee9f90d4-53ec-4363-a973-55daea776db1':{pass_threshold:80,questions:[
  mc(1,'"Must" for deduction vs "have to" for obligation — complete: "You ___ be tired." (deduction)','have to','should','must','need to','C'),
  mc(2,'"She must have left." — this expresses:','past ability','obligation in the past','logical deduction about the past','past permission','C'),
  mc(3,'"You needn\'t have rushed." — the implication is:','you rushed, and it was correct','you didn\'t rush enough','you rushed, but it was unnecessary','you should rush more','C'),
  mc(4,'Which is correct for a past CRITICISM?','She can\'t have gone.','She might have gone.','She should have called.','She must have called.','C'),
  mc(5,'Which phrase opens a formal email?','Hey, quick question...','I am writing to inquire about...','Just wondering if...','Touching base re:...','B'),
  mc(6,'Which closing is most formal?','See ya,','Take care,','All the best,','Yours faithfully,','D'),
  mc(7,'In negotiations, "BATNA" refers to:','your best offer','your opening bid','what you do if negotiations fail','a negotiation technique','C'),
  mc(8,'Complete: "She ___ have notified us — we had no idea!" (criticism, she didn\'t do it)','might','must','should','could','C'),
  mc(9,'Which collocation is correct? "secure ___"','investors','invest','investing','invested','A'),
  mc(10,'"Disrupt the market" means:','follow market trends','avoid competition','compete at a low level','radically change how a market operates','D'),
  mc(11,'Complete: "We ___ be willing to negotiate on delivery terms." (modal for willingness)','must','might','should','would','D'),
  mc(12,'Which phrase is used to politely push back on a price?','No way.','I\'m afraid that falls outside our budget.','Too expensive.','We won\'t pay that.','B'),
  mc(13,'Complete: "generate ___."','revenue','revenues','revenued','revenueing','A'),
  mc(14,'"Going to scale the business" means:','reduce it','grow it significantly','close it','rebrand it','B'),
  mc(15,'Which verb collocates with "deadline"?','make','do','meet','have','C'),
  tf(16,'"Could have" always means the action was completed.','false'),
  tf(17,'"Yours faithfully" is used when you don\'t know the recipient\'s name.','true'),
  tf(18,'"Bootstrap" means to grow a startup using only external investment.','false'),
  fb(19,'He ___ (must have been) late — the meeting had already started.','must have been'),
  fb(20,'___ (Please find attached) the proposal for your consideration.','Please find attached'),
]},

// ── MODULE 7: Conditionals Mastery ──────────────────────────────────────────

'a686a8e8-6a44-4191-a2a9-3ee8cae525e9':{pass_threshold:70,questions:[
  mc(1,'Zero Conditional is used for:','hypothetical present situations','past regrets','unreal future possibilities','general truths and scientific facts','D'),
  mc(2,'Complete (Zero Conditional): "If you heat water to 100°C, it ___."','would boil','boils','boiled','will boil','B'),
  mc(3,'First Conditional is used for:','impossible past situations','general facts','hypothetical present','real or likely future situations','D'),
  mc(4,'Complete (First Conditional): "If she studies hard, she ___ pass."','would','passed','will','had passed','C'),
  mc(5,'Zero Conditional uses: if + ___, + ___:','Past Simple / would + inf','Present Simple / Present Simple','Past Simple / Past Simple','Present Simple / will + inf','B'),
  mc(6,'First Conditional uses: if + ___, + ___:','Past Simple / would + inf','Present Simple / Present Simple','Past Simple / Past Simple','Present Simple / will + inf','D'),
  mc(7,'Complete: "If it ___ tomorrow, we\'ll cancel the trip."','rained','rains','would rain','will rain','B'),
  mc(8,'Complete: "If you mix red and blue, you ___ purple."','get','would get','got','will have got','A'),
  mc(9,'Which sentence uses First Conditional correctly?','If I had time, I would call.','If I have time, I will call.','If I had had time, I would have called.','If I would have time, I call.','B'),
  mc(10,'Can we use "when" instead of "if" in Zero Conditional?','Never','Only in formal writing','Yes, because the result is certain','Only in academic writing','C'),
  tf(11,'The Zero Conditional can use "when" instead of "if" because the result is always true.','true'),
  tf(12,'"If it will rain, we\'ll cancel" is grammatically correct.','false'),
  tf(13,'First Conditional implies the condition is possible or likely.','true'),
  fb(14,'If you ___ (press) this button, the machine stops.','press'),
  fb(15,'If she ___ (passes) the test, she will celebrate.','passes'),
]},

'be4e95a1-3032-4527-aa19-e166c6af583e':{pass_threshold:70,questions:[
  mc(1,'Second Conditional is used for:','real likely future situations','general truths','unreal or hypothetical present/future situations','past regrets','C'),
  mc(2,'Second Conditional structure: if + ___, + ___:','Present Simple / will + inf','Present Simple / Present Simple','Past Simple / would + inf','Past Perfect / would have + pp','C'),
  mc(3,'Complete: "If I ___ a million dollars, I would travel the world."','have','had','have had','would have','B'),
  mc(4,'Complete: "She would apply for the job if she ___ more confident."','is','will be','would be','were','D'),
  mc(5,'In Second Conditional, "were" is used instead of "was" with:','plural subjects only','formal/subjunctive style with all subjects','third person singular only','informal spoken English','B'),
  mc(6,'Complete: "If I were you, I ___ accept the offer."','will','am going to','should','would','D'),
  mc(7,'Which sentence uses Second Conditional correctly?','If I have time, I will help.','If I had time, I will help.','If I had time, I would help.','If I would have time, I help.','C'),
  mc(8,'Second Conditional implies: the condition is:','likely to happen','a general truth','happening right now','unlikely or hypothetical','D'),
  mc(9,'Complete: "What would you do if you ___ the CEO for a day?"','are','will be','were','have been','C'),
  mc(10,'"If I were taller, I\'d be a basketball player." — the speaker:','is tall','is currently a basketball player','will become a basketball player','is not tall (unreal situation)','D'),
  tf(11,'"If I was you" and "If I were you" are both acceptable, with "were" more formal.','true'),
  tf(12,'Second Conditional refers only to past situations.','false'),
  tf(13,'"Would" appears in the if-clause in Second Conditional.','false'),
  fb(14,'If she ___ (had) more experience, she\'d get the promotion.','had'),
  fb(15,'I ___ (would travel) the world if I had more time.','would travel'),
]},

'f9c9961f-bcd3-48f6-af25-c088341c0e8b':{pass_threshold:70,questions:[
  mc(1,'Third Conditional is used for:','real future situations','general truths','unreal situations in the present','imagining a different outcome in the past','D'),
  mc(2,'Third Conditional structure: if + ___, + ___:','Past Simple / would + inf','Present Simple / will + inf','Past Perfect / would have + past participle','Past Perfect / had + past participle','C'),
  mc(3,'Complete: "If I ___ harder, I would have passed."','study','studied','had studied','have studied','C'),
  mc(4,'Complete: "She would have got the job if she ___ more prepared."','is','was','had been','were','C'),
  mc(5,'Complete: "If he ___ the map, he wouldn\'t have got lost."','checked','had checked','would check','checks','B'),
  mc(6,'Third Conditional implies: the condition and result are:','both real','both hypothetical about the future','both unreal — contrary to what actually happened','both present','C'),
  mc(7,'Which sentence correctly uses Third Conditional?','If I had more time, I would help.','If I had had more time, I would have helped.','If I have time, I will help.','If I had time, I will help.','B'),
  mc(8,'Complete: "They wouldn\'t have lost if they ___ harder."','train','trained','had trained','would have trained','C'),
  mc(9,'Complete: "I ___ you if I had known your number."','call','would call','will have called','would have called','D'),
  mc(10,'"If she had left earlier, she wouldn\'t have missed the train." — In reality:','she left early','she didn\'t miss the train','she left late and missed the train','she arrived on time','C'),
  tf(11,'Third Conditional uses Past Perfect in the if-clause.','true'),
  tf(12,'"Would have + past participle" appears in the result clause of Third Conditional.','true'),
  tf(13,'Third Conditional can be used to describe real past situations.','false'),
  fb(14,'If they ___ (had arrived) on time, they would have seen the opening.','had arrived'),
  fb(15,'She ___ (would have won) if she had prepared more thoroughly.','would have won'),
]},

'38fa0ae7-5570-4fb8-9a21-ed6632c705b6':{pass_threshold:70,questions:[
  mc(1,'Mixed Conditional Type 2+3 combines:','2nd conditional if-clause + 3rd conditional result','3rd conditional if-clause + 2nd conditional result','1st + 2nd conditionals','Zero + 1st conditionals','A'),
  mc(2,'Mixed Conditional (2+3) expresses:','a real future situation','a past unreal situation (if-clause) affecting a present result','a present unreal situation affecting a past result','a general truth','B'),
  mc(3,'Complete (2+3): "If I ___ richer (but I\'m not), I would have bought it."','am','were','had been','would be','B'),
  mc(4,'Complete: "If she ___ (past unreal fact: she isn\'t a doctor), she would have treated him."','is a doctor','were a doctor','had been a doctor','was a doctor','B'),
  mc(5,'In Mixed Conditional (2+3), the if-clause uses:','Past Simple','Past Perfect','would + inf','Present Simple','A'),
  mc(6,'In Mixed Conditional (2+3), the result clause uses:','would + inf','would have + past participle','will + inf','Past Simple','B'),
  mc(7,'Complete: "If he were more careful, he ___ the mistake."','wouldn\'t make','wouldn\'t have made','won\'t make','hadn\'t made','B'),
  mc(8,'Complete: "If I were braver, I ___ spoken up in the meeting."','would','will have','would have','had','C'),
  mc(9,'Which sentence is Mixed Conditional (2+3)?','If I had money, I would buy it.','If she had studied, she would have passed.','If he were smarter, he would have avoided the mistake.','If I will have time, I\'ll call.','C'),
  mc(10,'"If I were you, I would have refused the offer." — "were" shows:','a past action','an unreal present condition (I am not you)','a real present situation','a future plan','B'),
  tf(11,'Mixed Conditional (2+3) combines an unreal present condition with a past result.','true'),
  tf(12,'The if-clause of Mixed Conditional (2+3) uses Past Perfect.','false'),
  tf(13,'"If he were more organized, he would have finished on time" is a correct Mixed Conditional.','true'),
  fb(14,'If she ___ (were) more patient, she would have handled it better.','were'),
  fb(15,'If he ___ (weren\'t) so shy, he would have introduced himself.','weren\'t'),
]},

'6ed29931-cef1-4185-bb19-783d8ee13efc':{pass_threshold:70,questions:[
  mc(1,'Mixed Conditional Type 3+2 combines:','3rd conditional if-clause + 2nd conditional result','2nd conditional if-clause + 3rd conditional result','1st + 3rd conditionals','Zero + 2nd conditionals','A'),
  mc(2,'Mixed Conditional (3+2) expresses:','a present unreal situation affecting a present result','a past unreal condition affecting a PRESENT result','a future unreal situation','a real past event and its real result','B'),
  mc(3,'Complete (3+2): "If I had studied law, I ___ a lawyer now."','would be','would have been','was','had been','A'),
  mc(4,'In Mixed Conditional (3+2), the if-clause uses:','Past Simple','would + inf','Past Perfect','Present Simple','C'),
  mc(5,'In Mixed Conditional (3+2), the result clause uses:','would have + past participle','will + inf','would + bare infinitive','Past Simple','C'),
  mc(6,'Complete: "If she had taken that job offer, she ___ in New York now."','would have lived','would live','lived','will live','B'),
  mc(7,'Complete: "If they had invested wisely, they ___ rich now."','would have been','will be','would be','had been','C'),
  mc(8,'Which sentence is Mixed Conditional (3+2)?','If she had studied, she would have passed.','If she had studied law, she would be a lawyer now.','If she studies, she will pass.','If she were smarter, she would have avoided the mistake.','B'),
  mc(9,'Complete: "If he had taken better care of himself, he ___ healthier today."','would have been','would be','will be','had been','B'),
  mc(10,'"If I had chosen a different career, I wouldn\'t be here now." — The speaker:','changed career and is not here','didn\'t change career and IS here now','will change career','had no choice','B'),
  tf(11,'Mixed Conditional (3+2) uses Past Perfect in the if-clause.','true'),
  tf(12,'Mixed Conditional (3+2) refers to a past condition with a present consequence.','true'),
  tf(13,'In Mixed Conditional (3+2), the result clause uses "would have + past participle."','false'),
  fb(14,'If she ___ (had accepted) the scholarship, she would be at Oxford now.','had accepted'),
  fb(15,'If he hadn\'t dropped out, he ___ (would be) working as an engineer today.','would be'),
]},

'd9e60d94-5ffc-4f08-ac26-bff6f556b273':{pass_threshold:70,questions:[
  mc(1,'Complete: "I prefer ___ to flying." (prefer + gerund)','to drive','driving','drive','drove','B'),
  mc(2,'"I\'d prefer" is followed by:','gerund','to-infinitive','bare infinitive','past participle','B'),
  mc(3,'Complete: "I\'d prefer ___ home tonight."','to stay','staying','stay','stayed','A'),
  mc(4,'Complete: "I\'d rather ___ than drive." (own preference, no subject)','take the train','taking the train','to take the train','taken the train','A'),
  mc(5,'Complete: "I\'d rather you ___ tomorrow." (preference about someone else)','come','to come','coming','came','D'),
  mc(6,'"She prefers reading to watching TV." — "prefer + noun/gerund + to + noun/gerund" — is "to" here a preposition or part of infinitive?','part of infinitive','a preposition','a conjunction','an adverb','B'),
  mc(7,'Complete: "I\'d rather not ___ tonight." (negative, own preference)','going out','go out','to go out','went out','B'),
  mc(8,'Complete: "I\'d prefer it if you ___ on time." (conditional preference)','would arrive','arrived','arrive','arriving','B'),
  mc(9,'Which is CORRECT?','I prefer to reading.','I\'d rather to go.','I\'d prefer going by bus.','I\'d rather going home.','C'),
  mc(10,'Complete: "I prefer coffee ___ tea."','than','more than','to','instead','C'),
  tf(11,'"I\'d rather" + bare infinitive (no subject) or past simple (with different subject).','true'),
  tf(12,'"I prefer" is always followed by a gerund.','false'),
  tf(13,'"I\'d prefer you to leave" and "I\'d rather you left" have a similar meaning.','true'),
  fb(14,'I\'d rather ___ (stay) home than go to that party.','stay'),
  fb(15,'She prefers working outdoors ___ (to) sitting at a desk all day.','to'),
]},

'089b28f2-fe9e-4a98-a5a0-22600ad2551d':{pass_threshold:70,questions:[
  mc(1,'Which is a Zero Conditional?','If I had money, I\'d travel.','If you freeze water, it becomes ice.','If she had known, she would have helped.','If it rains, I\'ll cancel.','B'),
  mc(2,'Which is a First Conditional?','If I won the lottery, I\'d quit.','If he had worked harder, he would have passed.','If you heat ice, it melts.','If she calls, tell her I\'m busy.','D'),
  mc(3,'Which is a Second Conditional?','If you freeze water, it becomes ice.','If she calls, I\'ll answer.','If she had known, she would have helped.','If I had a car, I would drive to work.','D'),
  mc(4,'Which is a Third Conditional?','If I were richer, I\'d buy a house.','If she had arrived earlier, she would have met him.','If you heat metal, it expands.','If he calls, I\'ll answer.','B'),
  mc(5,'Which is a Mixed Conditional (3+2)?','If I were a doctor, I would have treated him.','If I had studied medicine, I would be a doctor now.','If you heat ice, it melts.','If she worked harder, she would pass.','B'),
  mc(6,'Complete: "If I ___ you, I\'d accept the offer." (advice)','am','was','had been','were','D'),
  mc(7,'Complete: "If she ___ harder last year, she would have passed." (Third)','studied','studies','had studied','were studying','C'),
  mc(8,'Complete: "If he had taken the job, he ___ in Tokyo now." (Mixed 3+2)','would have been','will be','would be','had been','C'),
  mc(9,'Complete: "She would have helped if she ___ available." (Third)','is','was','were','had been','D'),
  mc(10,'Which conditional uses "were" for all subjects (subjunctive)?','Zero','First','Second','Third','C'),
  tf(11,'"If I would have known" is a grammatically incorrect way to form Third Conditional.','true'),
  tf(12,'"Would" can appear in the if-clause of any conditional.','false'),
  tf(13,'Mixed Conditionals combine if-clauses and result clauses from different conditional types.','true'),
  fb(14,'If she ___ (had told) me, I would have helped her.','had told'),
  fb(15,'If he ___ (were) more experienced, he would have handled the crisis better. (Mixed 2+3)','were'),
]},

'8e971af6-dd78-42ff-98c4-71dbcc454d8c':{pass_threshold:80,questions:[
  mc(1,'Zero Conditional uses:','Past Simple + would + inf','Past Perfect + would have + pp','Present Simple + Present Simple','Present Simple + will + inf','C'),
  mc(2,'First Conditional uses:','Past Simple + would + inf','Past Perfect + would have + pp','Present Simple + Present Simple','Present Simple + will + inf','D'),
  mc(3,'Second Conditional uses:','Past Perfect + would have + pp','Present Simple + Present Simple','Past Simple + would + inf','Present Simple + will + inf','C'),
  mc(4,'Third Conditional uses:','Past Simple + would + inf','Present Simple + Present Simple','Present Simple + will + inf','Past Perfect + would have + pp','D'),
  mc(5,'Complete: "If I ___ you, I\'d negotiate harder." (2nd Conditional)','am','was','had been','were','D'),
  mc(6,'Complete: "If she ___ the report earlier, the meeting would have gone better." (3rd)','submits','submitted','had submitted','would have submitted','C'),
  mc(7,'Mixed Conditional (3+2): "If he ___ medicine, he would be a doctor now."','studied','studies','had studied','would study','C'),
  mc(8,'Mixed Conditional (2+3): "If she ___ more patient, she would have accepted the offer."','is','were','had been','was','B'),
  mc(9,'Complete: "I\'d rather you ___ here tomorrow." (preference about someone else)','come','came','to come','coming','B'),
  mc(10,'Complete: "I prefer coffee ___ tea."','than','more than','instead','to','D'),
  mc(11,'Complete: "I\'d prefer ___ the bus." (prefer + to-inf)','take','taking','taken','to take','D'),
  mc(12,'"If I had a billion dollars, I ___ give it all away." (2nd Conditional)','will','would','had','have','B'),
  mc(13,'"Can\'t have + past participle" expresses:','past ability','possibility','past permission','logical impossibility in the past','D'),
  mc(14,'Which conditional is for scientific/general facts?','First','Second','Third','Zero','D'),
  mc(15,'Complete: "If they ___ (3rd Conditional) in time, the deal would have closed."','arrived','arrive','had arrived','were arriving','C'),
  tf(16,'"Would" can appear in the if-clause of conditional sentences.','false'),
  tf(17,'Mixed Conditional (3+2) uses Past Perfect in the if-clause and "would + bare inf" in the result.','true'),
  tf(18,'Second Conditional implies the situation is hypothetical or unlikely.','true'),
  fb(19,'If I ___ (had known) about the event, I would have attended.','had known'),
  fb(20,'She ___ (would be) more successful now if she had taken that opportunity.','would be'),
]},

// ── MODULE 8: Passive Voice Mastery ─────────────────────────────────────────

'4ffb09fc-6fa1-4f4a-8b4b-7c8c4ef6a81d':{pass_threshold:70,questions:[
  mc(1,'Present Simple Passive: "Letters ___ every morning."','are sending','is sent','are sent','have been sent','C'),
  mc(2,'Present Continuous Passive: "The new road ___ built."','is','was','is being','has been','C'),
  mc(3,'Present Perfect Passive: "The report ___ submitted."','is','is being','was','has been','D'),
  mc(4,'Past Simple Passive: "The contract ___ yesterday."','is signed','was signed','has been signed','had been signed','B'),
  mc(5,'Past Continuous Passive: "The bridge ___ repaired when the flood hit."','is being','was being','has been','had been','B'),
  mc(6,'Past Perfect Passive: "All the evidence ___ destroyed before the trial."','is','was','has been','had been','D'),
  mc(7,'Future Simple Passive: "The results ___ announced tomorrow."','are being','were','will be','have been','C'),
  mc(8,'Future Perfect Passive: "The project ___ completed by December."','will be','will have been','is being','was','B'),
  mc(9,'Modal Passive: "The policy ___ changed." (obligation: must)','must change','must be changed','must have changed','must changing','B'),
  mc(10,'Why is passive voice preferred in scientific writing?','to sound more informal','to emphasize the agent','to focus on the action/result rather than the doer','to use shorter sentences','C'),
  tf(11,'The agent is always mentioned in passive sentences.','false'),
  tf(12,'All passive tenses include a form of "be" + past participle.','true'),
  tf(13,'Active: "They built the bridge in 1990." → Passive: "The bridge was built in 1990." is correct.','true'),
  fb(14,'The new law ___ (will be announced) next week.','will be announced'),
  fb(15,'Several improvements ___ (have been made) to the system.','have been made'),
]},

'a42ab367-99f9-4f8a-ad68-cd71cc207aed':{pass_threshold:70,questions:[
  mc(1,'Modal Passive is formed with:','modal + be + past participle','modal + been + past participle','modal + being + present participle','modal + past participle','A'),
  mc(2,'Complete: "This door ___ be left unlocked." (prohibition: must)','must not','must not be','not must','is must not','B'),
  mc(3,'Complete: "The exam ___ be rescheduled." (permission: may)','may','may be','might being','be may','B'),
  mc(4,'Complete: "The report ___ be submitted by Friday." (obligation)','should','should be','should been','be should','B'),
  mc(5,'Complete: "A decision ___ be reached soon." (necessity: need)','needs to','needs be','needs to be','to be need','C'),
  mc(6,'Complete: "The project ___ be completed on time." (future ability: will be able to)','can','could be','might be','will be able to be','D'),
  mc(7,'Complete: "Visitors ___ not be admitted after 9pm."','must','are must','can must','should must','A'),
  mc(8,'Which is CORRECT modal passive?','The problem should solved.','The problem should be solving.','The problem should be solved.','The problem should being solved.','C'),
  mc(9,'Complete: "The CEO\'s statement ___ be misunderstood." (possibility)','could','could be','might being','can being','B'),
  mc(10,'Convert: "They should update the software regularly." → passive','The software should update regularly.','The software should be updated regularly.','The software should updated be.','Regularly the software should be update.','B'),
  tf(11,'Modal passive: "must + be + past participle" is the correct structure.','true'),
  tf(12,'"The budget might increased" is grammatically correct passive.','false'),
  tf(13,'"The issue needs to be addressed" is a correct modal passive.','true'),
  fb(14,'All applications ___ (must be submitted) online.','must be submitted'),
  fb(15,'The results ___ (should be released) by the end of the month.','should be released'),
]},

'3af0acc1-dfd4-4c1c-b84f-def28991e8c8':{pass_threshold:70,questions:[
  mc(1,'"Have something done" structure is:','have + object + past participle','have + object + to-infinitive','have + past participle','have been + past participle','A'),
  mc(2,'"Have something done" means:','to do something yourself','to arrange for someone else to do something for you','to be forced to do something','to do something in the past','B'),
  mc(3,'Complete: "She ___ her hair cut yesterday."','has','had','got','B and C are correct','D'),
  mc(4,'Complete: "We need to ___ the office repainted."','have','get','had','A and B are correct','D'),
  mc(5,'Complete: "They ___ their car serviced every year."','get','have','had','A and B are correct','D'),
  mc(6,'Complete: "She ___ her portrait painted by a famous artist."','has had','had','got','all are possible','D'),
  mc(7,'Negative form: "She ___ her report checked." (hasn\'t had)','hasn\'t had','hasn\'t had it','didn\'t had','not have had','A'),
  mc(8,'Question form: "___ you ___ your eyes tested recently?"','Did / had','Have / had','Are / having','Were / had','B'),
  mc(9,'Which is CORRECT "have something done"?','She has cut her hair.','She had her hair cutting.','She has had her hair cut.','She had cut her hair.','C'),
  mc(10,'Complete: "We\'re ___ a new security system installed next week."','having','have','had','got','A'),
  tf(11,'"Get something done" is more informal than "have something done."','true'),
  tf(12,'"Have something done" always implies the speaker does the action themselves.','false'),
  tf(13,'"She had her car repaired" means someone repaired her car for her.','true'),
  fb(14,'They ___ (are having) the building renovated next month.','are having'),
  fb(15,'He needs to ___ (have / get) his passport renewed.','have / get'),
]},

'f4a59cf3-31d0-4458-98b7-e1f1b4a7bc94':{pass_threshold:70,questions:[
  mc(1,'Passive is common in news/media because:','it is more exciting','it sounds conversational','it focuses on what happened rather than who did it','it is shorter','C'),
  mc(2,'Complete: "The Prime Minister ___ questioned about the scandal."','has','was','is being','had been','B'),
  mc(3,'Which is more typical in a news headline?','People arrested three suspects.','Three suspects were arrested.','Three suspects have been arresting.','The police have arrested three suspects.','B'),
  mc(4,'Complete: "Several buildings ___ destroyed in the earthquake."','have been','were','are being','had','B'),
  mc(5,'News passive: "A new vaccine ___ developed." (recent)','is being','was','were','has been','D'),
  mc(6,'Complete: "The talks ___ expected to continue through the weekend."','is','are','were','will be','B'),
  mc(7,'Complete: "The suspect ___ released without charge."','was','has','is','were','A'),
  mc(8,'In news English, passive is often used with:','reporting verbs (say, report, believe)','informal expressions','direct speech only','colloquial vocabulary','A'),
  mc(9,'Complete: "It ___ reported that the economy is improving."','has been','is','was','have been','C'),
  mc(10,'Complete: "The emergency meeting ___ called by the board."','was','has','is','were','A'),
  tf(11,'Passive voice is frequently used in news English to report facts without specifying the doer.','true'),
  tf(12,'News headlines always use full passive constructions with "be."','false'),
  tf(13,'"It was reported that..." is a common passive reporting structure in news English.','true'),
  fb(14,'The stolen paintings ___ (were recovered) by police last night.','were recovered'),
  fb(15,'The company\'s shares ___ (have been suspended) pending investigation.','have been suspended'),
]},

'ed84cf85-01ac-4dbf-b2fb-087a30766f87':{pass_threshold:70,questions:[
  mc(1,'Impersonal passive "It is said that..." is used to:','state a personal opinion','report what people in general say or believe','give a direct command','express personal experience','B'),
  mc(2,'Convert: "People say he is brilliant." → impersonal passive:','He is said to brilliant.','It is said that he is brilliant.','It says that he is brilliant.','He says to be brilliant.','B'),
  mc(3,'Complete: "It ___ believed that the economy will recover."','says','is','was','has been','B'),
  mc(4,'Personal impersonal passive: "He is said ___."','to be genius','that he is genius','being genius','to be a genius','D'),
  mc(5,'Complete: "It ___ thought that the building dates to 1850."','is','was','says','has been','A'),
  mc(6,'Convert: "People believed he had left." → personal impersonal:','He believed to have left.','He is believed to have left.','It believed he had left.','He was believed leaving.','B'),
  mc(7,'Which verb is NOT typically used in impersonal passive?','say','report','believe','run','D'),
  mc(8,'Complete: "It ___ reported that three people were injured."','has','is','was','says','C'),
  mc(9,'"Scientists are known to have discovered..." — the personal passive uses:','is known + gerund','is known + infinitive','to be + past participle','known + gerund','B'),
  mc(10,'Complete: "The artist is thought ___ have lived in poverty."','that','to','of','by','B'),
  tf(11,'"It is said that" and "He is said to be" are both correct impersonal passive structures.','true'),
  tf(12,'"It is known" can only refer to the present.','false'),
  tf(13,'Impersonal passive is commonly used in academic and journalistic writing.','true'),
  fb(14,'It ___ (is believed) that the ruins date back to the 5th century.','is believed'),
  fb(15,'She is ___ (said to be) one of the most influential scientists of her generation.','said to be'),
]},

'514474e9-cc7b-41dd-b4e3-097c71aa1e6f':{pass_threshold:70,questions:[
  mc(1,'Passive voice is preferred in academic writing to:','sound informal','emphasize personal opinion','maintain objectivity and focus on findings','make sentences shorter','C'),
  mc(2,'Complete: "The samples ___ collected over a period of six months."','are','were','have been','had been','B'),
  mc(3,'Complete: "The hypothesis ___ tested using a controlled experiment."','was','is','has been','had','A'),
  mc(4,'Complete: "The data ___ analyzed using statistical software."','were','are','has been','is being','A'),
  mc(5,'Complete: "The results ___ summarized in Table 3."','have been','are','are being','were','D'),
  mc(6,'Which sentence is most appropriate for academic writing?','We collected the data last month.','Someone collected the data last month.','The data were collected last month.','They collected the data recently.','C'),
  mc(7,'Complete: "Participants ___ asked to complete a questionnaire."','are','were','have been','had been','B'),
  mc(8,'Complete: "The findings ___ discussed in the following section."','are','were','will be','have been','C'),
  mc(9,'Academic passive: "A correlation ___ found between X and Y."','is','was','has been','had been','B'),
  mc(10,'Which phrase is used to introduce passive methodology?','We did the experiment like this...','The following procedure was adopted...','Let me explain how we did it...','The experiment was done.','B'),
  tf(11,'"The experiment was conducted by the research team" specifies the agent.','true'),
  tf(12,'Academic writing always avoids the passive voice.','false'),
  tf(13,'"Data were collected" is correct (data is plural in formal academic English).','true'),
  fb(14,'The methodology ___ (was outlined) in the previous chapter.','was outlined'),
  fb(15,'Three hypotheses ___ (were tested) during the course of the study.','were tested'),
]},

'81ca71b8-d13a-442f-93a4-456f8e2a9624':{pass_threshold:70,questions:[
  mc(1,'Choose the correct passive: "Someone has just repaired the printer."','The printer has just been repaired.','The printer was just repaired.','The printer is just repaired.','The printer had just been repaired.','A'),
  mc(2,'Choose the correct passive: "They were building the new airport."','The new airport is being built.','The new airport was being built.','The new airport has been built.','The new airport had been built.','B'),
  mc(3,'Complete: "It ___ believed that he escaped abroad."','has','is','was','were','C'),
  mc(4,'Complete: "She ___ her laptop repaired at the shop."','had','got','was','A and B are correct','D'),
  mc(5,'Modal passive: "The rules ___ followed at all times."','can','must be','should','must','B'),
  mc(6,'Convert to passive: "They should have informed the committee."','The committee should have informed.','The committee should be informed.','The committee should have been informed.','The committee was informed.','C'),
  mc(7,'Impersonal passive: "Experts believe prices will rise." →','Prices are believed to rise.','It is believed that prices will rise.','Prices will be believed to rise.','It believes prices will rise.','B'),
  mc(8,'Passive with get: "She ___ promoted to manager." (informal)','was','got','has','had','B'),
  mc(9,'Choose the INCORRECT passive:','The car was repaired.','The work is being done.','He was promoted.','The report has written.','D'),
  mc(10,'Academic passive: "The experiment ___ conducted under controlled conditions."','is','were','has','was','D'),
  tf(11,'"Have something done" can also be used for unpleasant experiences: "He had his wallet stolen."','true'),
  tf(12,'"The documents were being signed when she arrived" is Past Continuous Passive.','true'),
  tf(13,'"Get" is more common in formal academic passive than "be."','false'),
  fb(14,'The bridge ___ (was being built) when the flood struck.','was being built'),
  fb(15,'She is ___ (said to have been) the most talented student of her generation.','said to have been'),
]},

'16c6ed79-1dd6-48e5-bd53-0ab44a5f1806':{pass_threshold:80,questions:[
  mc(1,'Present Perfect Passive: "The problem ___."','has been solved','is solved','was solved','is being solving','A'),
  mc(2,'Past Continuous Passive: "The road ___ repaired when the storm hit."','is being','has been','was being','had been','C'),
  mc(3,'Modal Passive: "The report ___ submitted by Friday."','must','must be','must being','must been','B'),
  mc(4,'"Have something done" complete: "She ___ her car serviced."','did','made','had','is','C'),
  mc(5,'Impersonal passive: "People say she is the best." →','She is said to be the best.','She says to be the best.','It said she is the best.','She has been said the best.','A'),
  mc(6,'Passive in academic writing: "The samples ___ analyzed." (past, formal)','are','were','have','had','B'),
  mc(7,'News passive: "Three arrests ___ made last night."','have been','has been','are','were','D'),
  mc(8,'Future Passive: "Results ___ announced tomorrow."','are','were','will be','have been','C'),
  mc(9,'Convert: "The board should have approved the budget." → passive','The budget should been approved.','The budget should have been approved.','The budget should approved.','The budget was should approved.','B'),
  mc(10,'"Get promoted" is ___ "be promoted."','more formal than','an incorrect version of','a more informal equivalent of','identical to in all contexts','C'),
  mc(11,'Past Perfect Passive: "All evidence ___ removed before the inspection."','was','has been','had been','were','C'),
  mc(12,'"It is thought that..." is used in:','casual conversation only','formal academic/journalistic writing','technical manuals','legal documents only','B'),
  mc(13,'Complete: "Several experiments ___ conducted over a five-year period."','are','were','have','is','B'),
  mc(14,'"She had her portrait painted." Who painted it?','She did.','Her portrait painted.','Someone else did it for her.','She will paint it.','C'),
  mc(15,'Which is INCORRECT?','The meeting was postponed.','She was promoted.','The budget should be approved.','The results have written.','D'),
  tf(16,'"Be" + past participle is the core structure of all passive tenses.','true'),
  tf(17,'Impersonal passive ("It is said that...") is typical of informal conversation.','false'),
  tf(18,'"Data were collected" is correct in formal academic English (data = plural).','true'),
  fb(19,'The discovery ___ (is said to have been) made by accident.','is said to have been'),
  fb(20,'The building ___ (will have been completed) before the opening ceremony.','will have been completed'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 5: "Friendship & People"', lessons: ['e8eec0f5-3c5e-4d40-b522-2039eb673a75','b67cd65b-52d0-417d-9ebf-739cfd93027b','a491012a-2ce9-40d5-8a02-a5203dac818a','219a92bc-24e6-4fbb-a84c-bb8fe4b48b0e','bb165347-799f-47f2-bb23-932c3d01e6ff','666c15e4-39f0-494c-baf5-6960d6b98bfc','d456ef6c-f3f0-43d0-b625-157d23819e93','a4090650-cdd0-4692-a5af-06c026e91b0e'] },
  { name: 'Module 6: "Work & Business"', lessons: ['c74efe4e-7968-424c-a61d-58b6c3633da6','28c4f1c3-31a7-458e-b6bb-1ff4956c9100','cbf9658e-2bc9-43b7-8606-3147fbcb4c92','aa422023-0db4-41da-b403-8ff6c1db8e27','730580e9-974b-41d9-a43a-f9373544fb20','030847c6-385c-45a6-9d4e-49575ef8ef1a','575ae15d-c871-4036-8c66-079eab9d323b','ee9f90d4-53ec-4363-a973-55daea776db1'] },
  { name: 'Module 7: "Conditionals Mastery"', lessons: ['a686a8e8-6a44-4191-a2a9-3ee8cae525e9','be4e95a1-3032-4527-aa19-e166c6af583e','f9c9961f-bcd3-48f6-af25-c088341c0e8b','38fa0ae7-5570-4fb8-9a21-ed6632c705b6','6ed29931-cef1-4185-bb19-783d8ee13efc','d9e60d94-5ffc-4f08-ac26-bff6f556b273','089b28f2-fe9e-4a98-a5a0-22600ad2551d','8e971af6-dd78-42ff-98c4-71dbcc454d8c'] },
  { name: 'Module 8: "Passive Voice Mastery"', lessons: ['4ffb09fc-6fa1-4f4a-8b4b-7c8c4ef6a81d','a42ab367-99f9-4f8a-ad68-cd71cc207aed','3af0acc1-dfd4-4c1c-b84f-def28991e8c8','f4a59cf3-31d0-4458-98b7-e1f1b4a7bc94','ed84cf85-01ac-4dbf-b2fb-087a30766f87','514474e9-cc7b-41dd-b4e3-097c71aa1e6f','81ca71b8-d13a-442f-93a4-456f8e2a9624','16c6ed79-1dd6-48e5-bd53-0ab44a5f1806'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 5–8 B2 Upper-Intermediate');
}
main();
