import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 9: Reported Speech Mastery ───────────────────────────────────────

'c3089ed4-60fb-4429-a741-087b808217d0':{pass_threshold:70,questions:[
  mc(1,'Reported Speech shifts Present Simple to:','Present Simple','Past Continuous','Past Perfect','Past Simple','D'),
  mc(2,'Reported Speech shifts Present Continuous to:','Past Simple','Past Continuous','Past Perfect','Past Perfect Continuous','B'),
  mc(3,'Reported Speech shifts Past Simple to:','Past Perfect','Past Continuous','Present Perfect','Past Simple (unchanged)','A'),
  mc(4,'Reported Speech shifts Present Perfect to:','Past Perfect','Past Simple','Present Perfect (unchanged)','Past Perfect Continuous','A'),
  mc(5,'Reported Speech shifts "will" to:','shall','would','could','should','B'),
  mc(6,'Reported Speech shifts "can" to:','would','should','could','shall','C'),
  mc(7,'"I am working on the report." → She said she ___ on the report.','is working','was working','worked','has been working','B'),
  mc(8,'"I have finished." → He said he ___.','has finished','finished','had finished','was finishing','C'),
  mc(9,'"I will call you." → She said she ___ call me.','will','would','could','should','B'),
  mc(10,'When does backshift NOT occur?','when the reporting verb is in present tense','when using direct speech','when the speaker is reporting something said long ago','when the information is still true or the reporting verb is present tense','D'),
  tf(11,'Tense backshift is always obligatory in reported speech.','false'),
  tf(12,'"I told him I was tired" uses correct tense backshift from "I am tired."','true'),
  tf(13,'"She said that she has finished" is always correct in reported speech.','false'),
  fb(14,'He said: "I\'m leaving." → He said he ___ (was leaving).','was leaving'),
  fb(15,'"We have arrived." → They said they ___ (had arrived).','had arrived'),
]},

'102b08a3-f846-4a9a-b646-ad4eb85cbc96':{pass_threshold:70,questions:[
  mc(1,'In reported questions, word order changes to:','question word order (auxiliary before subject)','statement word order (subject before verb)','inverted order only','passive voice','B'),
  mc(2,'"Where do you live?" → She asked me where I ___.','live','did live','lived','would live','C'),
  mc(3,'In reported YES/NO questions, we use:','if or whether','what or how','that','which','A'),
  mc(4,'"Do you speak French?" → He asked me ___ I spoke French.','that','what','which','if','D'),
  mc(5,'"Are you coming?" → She asked him ___ he was coming.','that','where','if','what','C'),
  mc(6,'"What time is it?" → She asked ___ time it was.','which','that','what','if','C'),
  mc(7,'Identify the error: "She asked me where did I work."','No error','The tense is wrong','"did" should not be used in reported questions — it should be "where I worked"','"where" should be "what"','C'),
  mc(8,'"Why did he leave?" → They asked ___ he had left.','that','if','why','what','C'),
  mc(9,'"Have you ever been to Paris?" → She asked me ___ I had ever been to Paris.','that','whether','what','which','B'),
  mc(10,'"Who is responsible?" → He asked ___ was responsible.','that','whether','whom','who','D'),
  tf(11,'In reported questions, we use statement word order (no inversion).','true'),
  tf(12,'"She asked me where did I live" is grammatically correct.','false'),
  tf(13,'"If" and "whether" can both introduce reported yes/no questions.','true'),
  fb(14,'"Why are you crying?" → She asked him why he ___ (was crying).','was crying'),
  fb(15,'"Can you help me?" → He asked me ___ (if/whether) I could help him.','if / whether'),
]},

'bb22d1a5-ab78-4a89-b77a-ad8d4b9a8f77':{pass_threshold:70,questions:[
  mc(1,'"Tell" in reported commands is followed by:','that + subject + verb','object + to-infinitive','gerund','bare infinitive','B'),
  mc(2,'"Sit down!" → He told me ___.','to sit down','sitting down','sit down','that I sit down','A'),
  mc(3,'"Don\'t be late!" → She told him ___ late.','to not be','not to be','don\'t be','not being','B'),
  mc(4,'"Ask" in reported commands is followed by:','object + to-infinitive','that-clause','gerund','bare infinitive','A'),
  mc(5,'"Please open the window." → She asked me ___ the window.','open','opening','that I open','to open','D'),
  mc(6,'"Order" in reported commands is followed by:','gerund','that-clause','object + to-infinitive','bare infinitive','C'),
  mc(7,'"Leave immediately!" → The manager ordered them ___ immediately.','leave','to leave','leaving','that they leave','B'),
  mc(8,'"Warn" in reported commands: She warned him ___ touch it.','not to','to not','don\'t','not','A'),
  mc(9,'"Advise" is followed by:','gerund','bare infinitive','object + to-infinitive','that-clause','C'),
  mc(10,'"Take a rest," the doctor said. → The doctor advised him ___ a rest.','take','taking','that he takes','to take','D'),
  tf(11,'"Tell" is always followed by object + to-infinitive in reported commands.','true'),
  tf(12,'"She ordered me that I leave" is grammatically correct.','false'),
  tf(13,'"Ask" and "tell" both require an object before the infinitive in reported commands.','true'),
  fb(14,'"Close the door!" → She told him ___ (to close) the door.','to close'),
  fb(15,'"Don\'t touch the exhibits!" → He warned visitors ___ (not to touch) the exhibits.','not to touch'),
]},

'32ab9412-0505-425e-b092-96114511bf7b':{pass_threshold:70,questions:[
  mc(1,'"Admit + -ing" reports:','an invitation','a promise','an accusation','a confession of doing something','D'),
  mc(2,'"She admitted stealing the money." — what did she say?','I steal the money.','I stole the money.','I have stolen the money.','I had stolen the money.','B'),
  mc(3,'"Deny + -ing" reports:','a denial that something happened','a promise','an offer','an agreement','A'),
  mc(4,'"He denied breaking the vase." — what did he say originally?','I broke the vase.','I didn\'t break the vase.','Did I break the vase?','I\'ll break the vase.','B'),
  mc(5,'"Suggest + -ing or that-clause" reports:','a proposal','a command','a denial','a complaint','A'),
  mc(6,'"She suggested going to the cinema." — what did she say?','Let\'s go to the cinema.','Go to the cinema.','She goes to the cinema.','We should have gone.','A'),
  mc(7,'"Promise + to-infinitive" reports:','a suggestion','a refusal','a guarantee about future action','an order','C'),
  mc(8,'"He promised to help." — what did he say?','I might help.','I\'ll help.','Help me.','I helped.','B'),
  mc(9,'"Refuse + to-infinitive" reports:','a refusal to do something','a suggestion','an offer','an admission','A'),
  mc(10,'"She refused to sign." — what did she say?','I\'ll sign.','Sign this.','I won\'t sign.','She signed.','C'),
  tf(11,'"Admit," "deny," and "suggest" are all followed by a gerund.','true'),
  tf(12,'"He promised that he would help" is an alternative to "He promised to help."','true'),
  tf(13,'"She denied to steal" is grammatically correct.','false'),
  fb(14,'He ___ (admitted) making an error in the accounts.','admitted'),
  fb(15,'She ___ (refused to answer) any questions about her private life.','refused to answer'),
]},

'727ac288-0ddb-4618-a5c7-22aa45546af7':{pass_threshold:70,questions:[
  mc(1,'Sequence of tenses: what happens to "tomorrow" in reported speech?','stays as "tomorrow"','becomes "today"','becomes "the next day / the following day"','becomes "yesterday"','C'),
  mc(2,'What happens to "yesterday" in reported speech?','stays as "yesterday"','becomes "the day before / the previous day"','becomes "tomorrow"','becomes "last week"','B'),
  mc(3,'What happens to "here" in reported speech?','stays as "here"','becomes "near"','becomes "there"','becomes "somewhere"','C'),
  mc(4,'What happens to "this" in reported speech?','stays as "this"','becomes "these"','becomes "the"','becomes "that"','D'),
  mc(5,'What happens to "now" in reported speech?','stays as "now"','becomes "here"','becomes "then"','becomes "soon"','C'),
  mc(6,'What happens to "last week" in reported speech?','stays as "last week"','becomes "next week"','becomes "the previous week / the week before"','becomes "this week"','C'),
  mc(7,'"Meet me here tomorrow," he said. → He told me to meet him ___ the next day.','here','there','somewhere','nearby','B'),
  mc(8,'"I saw her yesterday," she said. → She said she had seen her ___.','yesterday','the next day','the day before','today','C'),
  mc(9,'"This is our policy," she said. → She said ___ was their policy.','this','that','the','it','B'),
  mc(10,'"We will decide next month," they said. → They said they would decide ___.','next month','the next month','the following month','this month','C'),
  tf(11,'"Now" becomes "then" in reported speech.','true'),
  tf(12,'"Here" stays as "here" in reported speech.','false'),
  tf(13,'"This" becomes "that" and "these" becomes "those" in reported speech.','true'),
  fb(14,'"Come here now!" → He told me to come ___ (there) immediately.','there'),
  fb(15,'"I\'ll call you tomorrow," she said. → She said she\'d call me ___ (the next day / the following day).','the next day / the following day'),
]},

'c23b5024-9c5b-4c26-ae08-057e5886f6f7':{pass_threshold:70,questions:[
  mc(1,'In media reporting, "It is reported that..." introduces:','a personal opinion','unverified information attributed to a source','a guaranteed fact','an editorial opinion','B'),
  mc(2,'Which structure reports news without specifying the source?','According to..., he stated','It is believed that...','He personally told me...','I saw that...','B'),
  mc(3,'Complete: "According to the report, profits ___ risen sharply."','are','have','had','will have','B'),
  mc(4,'Reporting verb in media: "The minister ___ that the bill would pass."','asked','confirmed','refused','warned','B'),
  mc(5,'Which reporting verb implies the speaker is not sure of the truth?','confirm','announce','allege','state','C'),
  mc(6,'"Allege" means:','to prove','to confirm officially','to claim without proof','to deny completely','C'),
  mc(7,'Complete: "Experts ___ that the situation is improving."','refuse','allege','believe','warn','C'),
  mc(8,'Complete: "The company ___ that no data was lost." (official statement)','alleged','denied','asked','requested','B'),
  mc(9,'Which structure is used for impersonal reporting in media?','I think that...','Journalists say personally...','It is understood that...','My opinion is...','C'),
  mc(10,'Complete: "She is ___ to have links to the organization." (reported, not confirmed)','known','said','told','asked','B'),
  tf(11,'"Allege" suggests the claim is unproven.','true'),
  tf(12,'"It is understood that" is commonly used in formal journalism.','true'),
  tf(13,'"Claim" and "confirm" have the same meaning in media reporting.','false'),
  fb(14,'It is ___ (alleged) that the funds were misappropriated.','alleged'),
  fb(15,'According to sources, the CEO is ___ (said to be) considering resignation.','said to be'),
]},

'ec51cda9-a326-4bac-a5a9-554bf68eaca0':{pass_threshold:70,questions:[
  mc(1,'Choose the correct reported speech: "I\'ll be there at 8," he said.','He said he would be there at 8.','He said he will be there at 8.','He said he is there at 8.','He said he was there at 8.','A'),
  mc(2,'"Don\'t open that box!" → She told him ___ that box.','to not open','not open','not to open','don\'t open','C'),
  mc(3,'"Are you free on Friday?" → She asked him ___ free on Friday.','if he is','whether he was','if he were','that he was','B'),
  mc(4,'"I have never been abroad," he said. → He said he ___ abroad.','never went','had never been','has never been','never had been','B'),
  mc(5,'"Where are you going?" → She asked him ___ he was going.','that where','if where','whether','where','D'),
  mc(6,'"We will meet tomorrow," they said. → They said they ___ meet the next day.','will','are going to','would','were going to','C'),
  mc(7,'"She suggested ___ to the beach." (reported suggestion)','go','to go','going','we go','C'),
  mc(8,'"He admitted ___ the money." (reported admission)','steal','to steal','stealing','stolen','C'),
  mc(9,'"She refused ___ the contract." (reported refusal)','sign','signing','to sign','that she signs','C'),
  mc(10,'Which time expression changes from "now" to ___ in reported speech?','here','then','there','soon','B'),
  tf(11,'In reported questions, we do NOT use question word order (no inversion).','true'),
  tf(12,'"He denied that he had stolen" is an acceptable alternative to "He denied stealing."','true'),
  tf(13,'"She promised going" is the correct reported form of "I promise to go."','false'),
  fb(14,'He asked me where I ___ (had been) the previous evening.','had been'),
  fb(15,'She ___ (admitted having made) several mistakes in the calculations.','admitted having made'),
]},

'6243e904-dbe5-4d84-8e6e-5bcdb365a577':{pass_threshold:80,questions:[
  mc(1,'Tense backshift: "I am happy." → She said she ___ happy.','is','was','were','had been','B'),
  mc(2,'Tense backshift: "I have finished." → He said he ___.','has finished','finished','had finished','was finishing','C'),
  mc(3,'Tense backshift: "I can do it." → She said she ___ do it.','can','could','should','would','B'),
  mc(4,'Reported question (word order): "Where does he work?" → She asked where he ___.','does work','worked','works','did work','B'),
  mc(5,'Reported YES/NO question: "Are you ready?" → He asked ___ I was ready.','that','what','where','whether','D'),
  mc(6,'Reported command: "Don\'t leave!" → She told him ___.','to not leave','not leaving','not to leave','don\'t leave','C'),
  mc(7,'Reporting verb: "I stole it," he said. → He ___ stealing it.','denied','refused','admitted','promised','C'),
  mc(8,'Reporting verb: "Let\'s go to the beach." → She ___ going to the beach.','refused','denied','ordered','suggested','D'),
  mc(9,'Time expression: "Meet me here tomorrow," he said. → He told me to meet him ___ the following day.','here','now','there','this place','C'),
  mc(10,'Time expression: "I saw her yesterday." → She said she had seen her ___.','yesterday','the next day','the day before','today','C'),
  mc(11,'Impersonal passive in media: "People believe prices will rise." →','Prices are believed to rise.','It is believed that prices will rise.','Both A and B are correct.','Neither is correct.','C'),
  mc(12,'"Allege" in media reporting implies:','confirmed truth','a claim without proof','a personal admission','official announcement','B'),
  mc(13,'Complete: "She ___ to have been present at the scene." (media, not confirmed)','confirmed','said','is said','denied','C'),
  mc(14,'"He promised ___ the report by Friday."','submit','to submit','submitting','he submits','B'),
  mc(15,'"She denied ___ any knowledge of the incident."','to have','have','having','had','C'),
  tf(16,'In reported speech, "this" becomes "that" and "these" becomes "those."','true'),
  tf(17,'Backshift is optional when the information is still true or the reporting verb is in the present.','true'),
  tf(18,'"She asked me where did I live" is grammatically correct reported speech.','false'),
  fb(19,'He ___ (admitted making) an error in the annual report.','admitted making'),
  fb(20,'She asked me ___ (whether / if) I had ever been to Japan.','whether / if'),
]},

// ── MODULE 10: Advanced Grammar I ───────────────────────────────────────────

'ce4ca1f2-e43c-4d3c-8267-0c77c3fcd372':{pass_threshold:70,questions:[
  mc(1,'Which relative pronoun is used for people?','which','who','whose','where','B'),
  mc(2,'Which relative pronoun is used for things?','who','whose','which','whom','C'),
  mc(3,'Defining vs Non-defining: which uses commas?','Defining relative clause','Non-defining relative clause','Both use commas','Neither uses commas','B'),
  mc(4,'Can "that" replace "which" in a NON-DEFINING relative clause?','Yes, always','Only in informal speech','Never — "that" is not used in non-defining clauses','Only in writing','C'),
  mc(5,'"The man whom I met yesterday is my manager." — "whom" functions as:','subject','object','possessive','adverbial','B'),
  mc(6,'Complete: "This is the city ___ she was born."','which','who','where','whom','C'),
  mc(7,'Complete: "The woman ___ bag was stolen reported it immediately."','who','which','whose','whom','C'),
  mc(8,'"My brother, ___ lives in Tokyo, is visiting next week." (non-defining)','that','which','whom','who','D'),
  mc(9,'Which sentence contains a DEFINING relative clause?','My car, which is new, broke down.','She spoke to the man who she trusted.','London, where I was born, is a great city.','Her mother, who is a doctor, helped her.','B'),
  mc(10,'In formal English, which pronoun is used as an object in relative clauses?','who','which','whom','whose','C'),
  tf(11,'"That" can be used in non-defining relative clauses.','false'),
  tf(12,'"Where" can introduce relative clauses referring to a place.','true'),
  tf(13,'Non-defining relative clauses add extra information that is not essential to the meaning.','true'),
  fb(14,'The village ___ (where) I grew up has changed enormously.','where'),
  fb(15,'She is the only person ___ (whose) opinion I trust completely.','whose'),
]},

'24c46ed5-dd6e-4492-843a-ea77d69d7e16':{pass_threshold:70,questions:[
  mc(1,'A participle clause can replace a relative clause when:','the relative clause is non-defining','the verb in the relative clause is active','the subject is different from the main clause','the clause is in the past','B'),
  mc(2,'Replace with participle clause: "The man who is reading the paper..."','The man read the paper...','The man reads the paper...','The man reading the paper...','The man has read the paper...','C'),
  mc(3,'Replace with participle clause (passive): "The report that was written by the team..."','The report writing by the team...','The report written by the team...','The report write by the team...','The report being written by the team...','B'),
  mc(4,'Complete: "Anyone ___ (wish) to apply should submit a CV."','wishes','wishing','wished','to wish','B'),
  mc(5,'Complete: "The documents ___ (sign) yesterday are now official."','signing','sign','signed','have signed','C'),
  mc(6,'Which participle clause shows a completed action BEFORE the main verb?','Using all the evidence...','Having reviewed all the evidence,...','Reviewing all the evidence,...','Being reviewed,...','B'),
  mc(7,'Complete: "The results ___ (obtain) were highly significant."','obtaining','obtains','obtained','obtain','C'),
  mc(8,'"Written in 1984, the novel explores totalitarianism." — "written" functions as:','a main verb','a reduced relative clause (past participle)','a gerund','an adverb','B'),
  mc(9,'Identify the error: "The woman leaving the building is greeted her colleague."','No error','"is greeted" should be "greeted her colleague"','"leaving" should be "left"','"The woman" should be "The women"','B'),
  mc(10,'Complete: "___ (Have) completed the course, she received her certificate."','Completed','Having','Being','To have','B'),
  tf(11,'A present participle clause replaces an active relative clause.','true'),
  tf(12,'A past participle clause replaces a passive relative clause.','true'),
  tf(13,'"Having + past participle" shows an action simultaneous with the main verb.','false'),
  fb(14,'The scientists ___ (working) on this project have made a major breakthrough.','working'),
  fb(15,'___ (Having submitted) her application, she waited anxiously for a reply.','Having submitted'),
]},

'3170d617-3589-4388-9f21-8d5e7fd9192a':{pass_threshold:70,questions:[
  mc(1,'Use "the" with:','unique objects (the sun, the moon)','uncountable nouns in general','plural nouns in general','abstract nouns in general','A'),
  mc(2,'Use "a/an" with:','specific known nouns','first mention of a countable noun','uncountable nouns','unique objects','B'),
  mc(3,'Use no article with:','the names of specific rivers','proper nouns used in general (languages, sports, meals)','unique institutions','specific known things','B'),
  mc(4,'Complete: "___ Pacific Ocean is the largest ocean."','A','An','The','(no article)','C'),
  mc(5,'Complete: "She plays ___ violin beautifully." (musical instruments)','a','an','(no article)','the','D'),
  mc(6,'Complete: "___ information you provided was helpful." (specific known information)','A','An','The','(no article)','C'),
  mc(7,'Complete: "He had ___ amazing idea this morning."','the','(no article)','a','an','D'),
  mc(8,'Complete: "___ Mount Everest is in Nepal." (named mountains: no article)','The','A','(no article)','An','C'),
  mc(9,'Complete: "I love ___ music." (general category)','the','a','an','(no article)','D'),
  mc(10,'Complete: "She became ___ first woman to win the prize."','a','an','(no article)','the','D'),
  tf(11,'"The" is used before superlatives.','true'),
  tf(12,'No article is used with languages: "She speaks French."','true'),
  tf(13,'"A" is used before words starting with a vowel sound.','false'),
  fb(14,'___ (The) Alps are a mountain range in central Europe.','The'),
  fb(15,'She is studying ___ (no article / Ø) medicine at university.','Ø'),
]},

'4fd512d1-04c3-42a0-8e50-dd2c453b99c6':{pass_threshold:70,questions:[
  mc(1,'Which determiner is used with UNCOUNTABLE nouns?','many','few','much','several','C'),
  mc(2,'Which determiner is used with COUNTABLE plural nouns?','much','little','a little','several','D'),
  mc(3,'"There is ___ milk left." (a small amount)','few','a few','a little','little','C'),
  mc(4,'"There are ___ students absent today." (a small number)','a little','little','a few','few','C'),
  mc(5,'"___ people attended — the hall was nearly empty." (almost none, negative)','A few','A little','Few','Little','C'),
  mc(6,'"___ water remains — we must ration it." (almost none, negative)','A little','A few','Few','Little','D'),
  mc(7,'"Both," "either," and "neither" are used with:','uncountable nouns','singular nouns only','plural nouns (2 things)','mass nouns','C'),
  mc(8,'Complete: "___ of my suggestions was accepted." (neither of two)','None','Either','Neither','Both','C'),
  mc(9,'Complete: "___ the candidates were impressive."','Either','Neither','Both','None','C'),
  mc(10,'Complete: "I have ___ time for this." (not enough, stressed)','a little','little','few','a few','B'),
  tf(11,'"Much" is more common in affirmative sentences than in questions or negatives.','false'),
  tf(12,'"A few" has a slightly positive meaning (some, enough); "few" is more negative (not many).','true'),
  tf(13,'"Either" can mean "both" (of two) in some positive contexts.','true'),
  fb(14,'There are ___ (few) opportunities for advancement in this company.','few'),
  fb(15,'She had ___ (a little) difficulty understanding the instructions.','a little'),
]},

'b3c814ae-4d8b-4dfa-a28a-ab94bee24bc1':{pass_threshold:70,questions:[
  mc(1,'"As ___ as possible." — which comparative structure is this?','more','much/many','as...as','less','C'),
  mc(2,'Complete: "The more you practice, ___ you become."','the better','better','more better','the more better','A'),
  mc(3,'"Double comparative": "It\'s getting ___ expensive." (increasingly)','more and more','much more','a lot more','the more','A'),
  mc(4,'Complete: "She works ___ any other employee in the company." (harder than)','harder as','as hard as','harder than','as harder than','C'),
  mc(5,'Complete: "This is by far ___ book I\'ve ever read."','the most interesting','more interesting','most interesting','very interesting','A'),
  mc(6,'"He is nothing like as tall as his brother." means:','he is taller','he is much shorter','they are the same height','he is slightly shorter','B'),
  mc(7,'Complete: "___ sooner you start, ___ sooner you finish."','The / the','A / a','More / more','The / a','A'),
  mc(8,'Intensifiers with comparatives: "She is ___ more experienced than him."','very','much','a lot','B and C are correct','D'),
  mc(9,'Complete: "The results were ___ worse than expected."','much','very','more','a lot of','A'),
  mc(10,'"No sooner had she arrived ___ the problems started."','then','that','than','when','C'),
  tf(11,'"Very" can be used to intensify comparative adjectives (e.g., "very more interesting").','false'),
  tf(12,'"The more you read, the more you know" uses a double comparative structure.','true'),
  tf(13,'"As soon as" and "no sooner...than" have similar meanings but different structures.','true'),
  fb(14,'The situation is getting ___ (worse and worse).','worse and worse'),
  fb(15,'This is by far ___ (the most challenging) project I have ever undertaken.','the most challenging'),
]},

'18a63002-2493-4360-8707-36c76eb13977':{pass_threshold:70,questions:[
  mc(1,'Inversion is used for:','general statements','emphasis and formal/literary effect','questions only','informal speech','B'),
  mc(2,'Complete: "___ had I left the office when it started raining."','Rarely','No sooner','Barely','Scarcely','B'),
  mc(3,'Complete: "___ have I seen such dedication."','Rarely','Never','Hardly','Scarcely','B'),
  mc(4,'After "Never have I," the sentence structure is:','subject + auxiliary + main verb','auxiliary + subject + past participle','subject + past participle','normal statement order','B'),
  mc(5,'Complete: "___ would I agree to such terms."','Never','Rarely','Scarcely','Under no circumstances','D'),
  mc(6,'Complete: "Not only ___ she win, but she also broke the record."','she did','did she','she','does she','B'),
  mc(7,'Inversion after "Only when": "Only when the data was analyzed ___ the error discovered."','was','is','were','had','A'),
  mc(8,'Complete: "Seldom ___ she complain about the workload."','does','is','she does','did','A'),
  mc(9,'Complete: "Not until the 20th century ___ women given full voting rights."','was','were','is','are','B'),
  mc(10,'"Little did I know that..." — what is the effect of inversion here?','makes the sentence shorter','emphasizes surprise or unexpected discovery','makes it informal','reduces formality','B'),
  tf(11,'Inversion is triggered by negative or restrictive adverbs at the start of a clause.','true'),
  tf(12,'"Rarely I have seen" is correct subject-auxiliary inversion.','false'),
  tf(13,'"Not only...but also" requires inversion after "not only."','true'),
  fb(14,'___ (Never) have I witnessed such extraordinary bravery.','Never'),
  fb(15,'___ (Seldom) does such an opportunity arise in one\'s career.','Seldom'),
]},

'02c9d60f-817d-4860-866c-bc982bf9415f':{pass_threshold:70,questions:[
  mc(1,'Cleft sentences with "It is/was...that/who" are used for:','shortening sentences','reducing clauses','emphasizing a specific element','making sentences passive','C'),
  mc(2,'Complete: "___ the director who approved the budget."','That is','It is','There is','He is','B'),
  mc(3,'Cleft sentence emphasizing the TIME: "She met him in Paris in 2020." →','It was 2020 where she met him.','It was in 2020 that she met him.','It was in Paris that she met him in 2020.','It was her that met him.','B'),
  mc(4,'"What I need is a holiday." — "What I need" is:','a relative clause','a wh-cleft (pseudo-cleft)','a defining clause','a nominal clause only','B'),
  mc(5,'Complete: "___ bothers me is the constant noise."','It','There','What','That','C'),
  mc(6,'Cleft emphasizing the OBJECT: "I met HER yesterday." →','It was me that she met.','It was yesterday that I met her.','It was her that I met yesterday.','It was her meeting me.','C'),
  mc(7,'Complete: "It ___ in this lab that the discovery was made."','is','was','were','has been','B'),
  mc(8,'Wh-cleft: "The thing that worries me most is the deadline." → Cleft:','What worries me most is the deadline.','It is the deadline that worries me.','The deadline worries me most.','A and B are both correct clefts.','D'),
  mc(9,'Complete: "___ I want is for you to listen carefully."','It','All','What','That','C'),
  mc(10,'"It was not until midnight that she finished." emphasizes:','who finished','what she finished','the time she finished','how she finished','C'),
  tf(11,'"It was Shakespeare who wrote Hamlet" is a cleft sentence emphasizing the subject.','true'),
  tf(12,'"What I need" in "What I need is rest" is a type of wh-cleft.','true'),
  tf(13,'Cleft sentences reduce emphasis on a particular element.','false'),
  fb(14,'___ (What) surprised everyone was the speed of the recovery.','What'),
  fb(15,'It was ___ (her dedication) that made the project a success.','her dedication'),
]},

'9b9bc661-86fa-4c50-8b99-bddc0dd01789':{pass_threshold:70,questions:[
  mc(1,'A complex sentence contains:','only one independent clause','one independent clause + one or more dependent clauses','two independent clauses only','no verbs','B'),
  mc(2,'"Although she was tired, she continued working." — "Although" introduces a:','result clause','reason clause','concession clause','time clause','C'),
  mc(3,'"Because he studied hard, he passed." — "Because" introduces a:','concession','result','condition','reason clause','D'),
  mc(4,'"So that we could finish on time, we worked late." — the subordinate clause expresses:','concession','purpose','reason','result','B'),
  mc(5,'"Provided that you submit by Friday, you will pass." — the clause expresses:','purpose','reason','condition','result','C'),
  mc(6,'"She worked hard; consequently, she was promoted." — "consequently" expresses:','concession','purpose','condition','result','D'),
  mc(7,'Which conjunction introduces a TIME clause?','although','unless','whenever','so that','C'),
  mc(8,'"Despite the rain, they continued." — "despite" is followed by:','a clause','a noun/noun phrase or gerund','a verb','an adjective','B'),
  mc(9,'Complete: "___ he had the qualifications, he lacked experience."','Although','Because','So that','Provided','A'),
  mc(10,'"No matter how hard she tried, she couldn\'t pass." — "no matter how" expresses:','condition','purpose','concession (regardless of degree)','result','C'),
  tf(11,'"Although" and "even though" introduce concession clauses.','true'),
  tf(12,'"Despite" and "in spite of" are followed by a full clause.','false'),
  tf(13,'"So that" and "in order to" both express purpose.','true'),
  fb(14,'___ (Despite) working overtime every day, he failed to meet the deadline.','Despite'),
  fb(15,'She prepared thoroughly ___ (so that) she would not be caught off guard.','so that'),
]},

'24805033-338b-4dc7-9d81-e749da4bbd11':{pass_threshold:70,questions:[
  mc(1,'Ellipsis means:','adding extra information','repeating all key words','omitting words that are understood from context','using long complex sentences','C'),
  mc(2,'Substitution means:','omitting words','replacing words with shorter forms (do so, one, so, not)','using passive voice','adding extra clauses','B'),
  mc(3,'"A: Did she pass? B: I think so." — "so" here is:','a conjunction','an adverb of degree','a substitution for "she passed"','an ellipsis','C'),
  mc(4,'"A: Are you coming? B: I hope so." — "I hope so" substitutes for:','I hope I am coming.','I hope you are coming.','I hope so.','I hope to come.','A'),
  mc(5,'"A: Who wrote it? B: She did." — "did" replaces:','the object','the subject','the whole verb phrase "wrote it"','an adjective','C'),
  mc(6,'"I can play chess, and so can she." — "so" here is used for:','adding a negative idea','contrasting information','expressing agreement (so + auxiliary + subject)','expressing result','C'),
  mc(7,'"She wanted to stay but didn\'t." — this is an example of:','substitution','ellipsis (omission of "stay")','passive voice','inversion','B'),
  mc(8,'"The one on the left is mine." — "the one" is:','an ellipsis','a pronoun substituting a noun','a determiner','an article','B'),
  mc(9,'"A: Should I apply? B: I\'d say not." — "not" here substitutes:','the subject','the verb','the negative idea (you shouldn\'t apply)','an adjective','C'),
  mc(10,'Ellipsis in "She could have called but didn\'t [call]." — what is omitted?','She could have','called','call','but didn\'t','C'),
  tf(11,'Ellipsis and substitution both help avoid unnecessary repetition.','true'),
  tf(12,'"I think so" is an example of ellipsis.','false'),
  tf(13,'In English, "do so" is a formal substitute for a previous verb phrase.','true'),
  fb(14,'A: "Can she drive?" B: "I believe ___ (so)."','so'),
  fb(15,'She said she would call, but she ___ (didn\'t).','didn\'t'),
]},

'6f0bd2c8-9775-43ae-ad99-bad384869927':{pass_threshold:70,questions:[
  mc(1,'A noun clause functions as:','an adjective','a subject, object, or complement in a sentence','a time expression','an adverbial phrase','B'),
  mc(2,'Complete: "___ you said surprised everyone."','How','What','That','Which','B'),
  mc(3,'"I know that she will succeed." — "that she will succeed" is a:','relative clause','adverbial clause','noun clause (object)','participle clause','C'),
  mc(4,'Complete: "___ matters most is the quality of your work."','How','Which','That','What','D'),
  mc(5,'Complete: "The fact ___ she won is remarkable."','what','which','that','who','C'),
  mc(6,'Noun clause as SUBJECT: which is correct?','It is surprising what she said.','What she said is surprising.','Both A and B are correct.','Neither is correct.','C'),
  mc(7,'"Whether he comes or not is irrelevant." — "Whether...or not" introduces a:','relative clause','noun clause (subject)','conditional clause','adverbial clause','B'),
  mc(8,'Complete: "It remains unclear ___ caused the accident."','what','that','which','how','A'),
  mc(9,'"The reason why she left is unknown." — "why she left" is a:','relative clause','noun clause','adverbial clause','concession clause','B'),
  mc(10,'Complete: "I wonder ___ they will accept our proposal."','if / whether','that','who','which','A'),
  tf(11,'Noun clauses can function as subjects, objects, or complements.','true'),
  tf(12,'"That" introducing a noun clause can sometimes be omitted: "I think (that) she\'s right."','true'),
  tf(13,'"What" in noun clauses functions as a relative pronoun with a specific antecedent.','false'),
  fb(14,'___ (What) concerns me most is the lack of transparency.','What'),
  fb(15,'The committee decided ___ (that) the proposal would be rejected.','that'),
]},

'c6db6d5e-085c-4987-803a-68921cdecb14':{pass_threshold:80,questions:[
  mc(1,'Which relative pronoun is NEVER used in non-defining relative clauses?','who','which','whom','that','D'),
  mc(2,'Replace with participle clause: "the documents that were signed yesterday"','the documents signing yesterday','the documents sign yesterday','the documents signed yesterday','the documents to sign yesterday','C'),
  mc(3,'"Never have I seen such courage." — this is an example of:','passive voice','ellipsis','inversion for emphasis','a cleft sentence','C'),
  mc(4,'Complete: "It was ___ that discovered penicillin." (cleft)','Fleming who','Fleming which','who Fleming','whom Fleming','A'),
  mc(5,'Complete: "___ I find most difficult is managing my time."','It','There','That','What','D'),
  mc(6,'Article: "She plays ___ piano." (musical instrument)','a','an','the','(no article)','C'),
  mc(7,'Determiner: "There are ___ students absent." (a small number, positive)','few','little','a few','a little','C'),
  mc(8,'Comparison: "The ___ you practice, the ___ you improve."','much / better','more / more','many / most','more / better','D'),
  mc(9,'Noun clause: "I know ___ she is telling the truth."','what','which','that','who','C'),
  mc(10,'Ellipsis: "She could have helped but ___ [didn\'t help]."','couldn\'t','didn\'t','she doesn\'t','hasn\'t','B'),
  mc(11,'"Despite" is followed by:','a full clause (subject + verb)','a noun phrase or gerund','an adjective','an adverb','B'),
  mc(12,'Complete: "Not until 1920 ___ women allowed to vote in the UK." (inversion)','was','were','did','are','B'),
  mc(13,'Cleft: "The time when it all changed was 2020." → "It ___ 2020 that everything changed."','is','was','were','has been','B'),
  mc(14,'"Do so" in "She asked him to open the window, and he did so" substitutes for:','asked him','the window','open the window','he opened','C'),
  mc(15,'Advanced relative: "The company, ___ headquarters are in Zurich, employs 10,000 people."','whose','which','who','that','A'),
  tf(16,'"What I need is a break" is a wh-cleft sentence.','true'),
  tf(17,'"A few" and "few" have the same meaning.','false'),
  tf(18,'"Not only...but also" requires inversion after "not only."','true'),
  fb(19,'___ (Having completed) the analysis, she submitted her findings to the committee.','Having completed'),
  fb(20,'It was ___ (her persistence) that ultimately led to the breakthrough.','her persistence'),
]},

// ── MODULE 11: Adrenaline & Adventure ───────────────────────────────────────

'7ac04f1b-c7a5-4d2a-bdae-ea5550c4855a':{pass_threshold:70,questions:[
  mc(1,'"Adrenaline rush" refers to:','a sudden feeling of intense excitement caused by danger/challenge','a medical condition','a type of sport','a relaxation technique','A'),
  mc(2,'"Bungee jumping" involves:','jumping into water from a cliff','jumping from a height while attached to a long elastic cord','free-falling from a plane','climbing a mountain','B'),
  mc(3,'"White-water rafting" means:','sailing on calm seas','crossing a river on foot','navigating a river with strong rapids on a raft','swimming in open water','C'),
  mc(4,'Complete the collocation: "___ a risk." (take a calculated risk)','make','do','take','get','C'),
  mc(5,'"Thrill-seeker" describes:','someone who avoids danger','someone who actively seeks exciting or dangerous experiences','an outdoor sports instructor','a professional athlete','B'),
  mc(6,'Complete: "She ___ (reach) the summit after three days of climbing."','reached','has reached','was reaching','had reach','A'),
  mc(7,'"Death-defying" means:','extremely safe','boring and predictable','apparently risking death but surviving','related to death','C'),
  mc(8,'Complete: "The ___ (dare/daring/dared/dares) climbers attempted the north face in winter."','dare','dared','dares','daring','D'),
  mc(9,'"Vertigo" is:','love of heights','a dizzying sensation when looking down from a height','a type of extreme sport','reckless behavior','B'),
  mc(10,'Complete: "It takes ___ (nerve/nerves/nervous/nervously) to attempt a free solo climb."','nerves','nervous','nervously','nerve','D'),
  tf(11,'"Extreme sports" typically involve high levels of physical risk.','true'),
  tf(12,'"A daredevil" is someone who is extremely cautious and risk-averse.','false'),
  tf(13,'"Freefall" in skydiving refers to the period before the parachute opens.','true'),
  fb(14,'She ___ (took) the plunge and booked her first skydiving lesson.','took'),
  fb(15,'His ___ (reckless) behavior put the entire team in danger.','reckless'),
]},

'8aab8f12-b966-44af-b7ce-3b6f87a98c54':{pass_threshold:70,questions:[
  mc(1,'A "homebody" is someone who:','travels constantly','prefers staying at home','seeks adventure outdoors','works from home','B'),
  mc(2,'"Adventurous" describes someone who:','prefers routine and familiarity','is willing to take risks and try new things','is afraid of new experiences','stays close to home','B'),
  mc(3,'Complete: "He would rather ___ home than go camping."','to stay','staying','stayed','stay','D'),
  mc(4,'"Wanderlust" means:','fear of travel','a type of travel insurance','a strong desire to travel and explore','homesickness','C'),
  mc(5,'Complete: "She ___ to adventure sports — she prefers reading." (be not into)','is not into','is against','avoids','doesn\'t like','A'),
  mc(6,'Which is a "push factor" for travel?','desire to experience new cultures','bad weather at home','improved transport links','reduced travel costs','B'),
  mc(7,'"Globe-trotter" means:','a type of sports ball','someone who stays at home','someone who travels extensively around the world','a travel agent','C'),
  mc(8,'Complete: "Some people ___ (thrive/thrill/drive/tribe) on routine; others need variety."','thrill','drive','tribe','thrive','D'),
  mc(9,'"Creature of habit" describes someone who:','adapts easily to change','prefers routine and dislikes change','is very adventurous','seeks new experiences','B'),
  mc(10,'Complete: "She ___ (step/stepped/steps/stepping) out of her comfort zone by trying paragliding."','step','stepping','steps','stepped','D'),
  tf(11,'"Homebody" and "adventurer" describe opposite personality types.','true'),
  tf(12,'"Wanderlust" is always used negatively.','false'),
  tf(13,'"Stepping out of your comfort zone" means doing something challenging or unfamiliar.','true'),
  fb(14,'He is a real ___ (homebody) who prefers a quiet evening in to any social event.','homebody'),
  fb(15,'She decided to ___ (broaden) her horizons by spending a year volunteering abroad.','broaden'),
]},

'be520d3f-8902-43eb-aae8-6f720b8f23c6':{pass_threshold:70,questions:[
  mc(1,'"Hit the road" means:','to have an accident','to repair a road','to start a journey','to stop travelling','C'),
  mc(2,'"Off the beaten track" means:','on a main road','in a popular tourist area','on a dangerous route','in a remote or unexplored place','D'),
  mc(3,'"Go the extra mile" means:','to travel farther than planned','to make more effort than required','to follow the usual route','to take a shorter route','B'),
  mc(4,'"In the same boat" means:','travelling together','in the same vehicle','in a similar (usually difficult) situation','competing for the same prize','C'),
  mc(5,'"Keep a low profile" means:','travel quietly','avoid drawing attention to oneself','stay in a low place','work in secret','B'),
  mc(6,'"Bite off more than you can chew" means:','to eat too much','to take on more responsibility than you can handle','to be very greedy','to make many small promises','B'),
  mc(7,'"On the spur of the moment" means:','after careful planning','because of tradition','done suddenly without planning','slowly and carefully','C'),
  mc(8,'"Blaze a trail" means:','to cause a fire','to be the first to do something new','to follow an existing path','to get lost in the wilderness','B'),
  mc(9,'"At the drop of a hat" means:','carefully and slowly','without hesitation, immediately','when the right moment comes','after long consideration','B'),
  mc(10,'"Get cold feet" means:','to become physically cold','to become very frightened or anxious before doing something','to stop wanting to go somewhere cold','to change climate preference','B'),
  tf(11,'"Off the beaten track" refers to popular tourist destinations.','false'),
  tf(12,'"Go the extra mile" means to make exceptional effort.','true'),
  tf(13,'"Bite off more than you can chew" is used when someone succeeds easily.','false'),
  fb(14,'She decided ___ (on the spur of the moment) to book a flight to Iceland.','on the spur of the moment'),
  fb(15,'He ___ (got cold feet) and cancelled the solo expedition at the last minute.','got cold feet'),
]},

'7c4672be-21a8-4af4-94be-5b82701b4b13':{pass_threshold:70,questions:[
  mc(1,'Complete the collocation: "___ a risk."','make','do','take','get','C'),
  mc(2,'Complete: "minimize ___."','risks','riskily','riskful','risky','A'),
  mc(3,'Complete: "ensure ___."','safety','safely','safe','safeness','A'),
  mc(4,'Complete: "___ precautions."','make','take','do','get','B'),
  mc(5,'Complete: "comply ___ safety regulations."','to','on','with','about','C'),
  mc(6,'"Hazard" means:','a safety measure','something that could cause danger','a piece of safety equipment','a type of insurance','B'),
  mc(7,'"Mitigate a risk" means:','to increase the risk','to eliminate all risk','to reduce or lessen the severity of a risk','to ignore the risk','C'),
  mc(8,'Complete: "The climbers were equipped ___ state-of-the-art safety gear."','by','of','in','with','D'),
  mc(9,'"Risk assessment" is:','ignoring potential dangers','a process of identifying and evaluating potential risks','a type of extreme sport','an insurance policy','B'),
  mc(10,'"Due diligence" means:','being careless','acting without preparation','making a proper level of careful investigation','taking unnecessary risks','C'),
  tf(11,'"Hazardous" and "dangerous" are synonyms.','true'),
  tf(12,'"Mitigate" means to make a risk worse.','false'),
  tf(13,'"Take precautions" is a common collocation related to safety.','true'),
  fb(14,'The expedition team ___ (took) every precaution before attempting the summit.','took'),
  fb(15,'It is essential to ___ (minimize) risks when working in extreme environments.','minimize'),
]},

'884ddd78-8a5e-42cf-87d2-4de5348fff22':{pass_threshold:70,questions:[
  mc(1,'Which tense combination is typical in adventure narratives?','Present Simple + Future','Past Simple + Past Continuous + Past Perfect','Present Perfect + Future Perfect','Past Continuous only','B'),
  mc(2,'Complete: "We ___ (paddle) for hours when we suddenly ___ (hear) a roar."','paddled / heard','had been paddling / heard','were paddling / heard','paddled / were hearing','C'),
  mc(3,'"Out of nowhere" means:','in a specific location','gradually','suddenly and unexpectedly','with careful planning','C'),
  mc(4,'"Against all odds" means:','with great support','despite very unfavorable circumstances','easily and without effort','with advanced technology','B'),
  mc(5,'Complete: "By the time help arrived, we ___ stranded for 12 hours."','were','had been','are','have been','B'),
  mc(6,'Which phrase best opens an adventure anecdote?','I always do this.','You won\'t believe what happened to us last summer.','It was a perfectly ordinary day.','This is a plan.','B'),
  mc(7,'Complete: "Just as she ___ (reach) the top, the fog ___ (set) in."','reached / set','was reaching / set','had reached / was setting','reaches / sets','B'),
  mc(8,'"Make it" in narratives means:','to arrive on time or survive','to make something','to travel far','to plan successfully','A'),
  mc(9,'Complete: "She ___ (never/experience) anything like it before." (narrative past perfect)','never experienced','had never experienced','never had experienced','hasn\'t ever experienced','B'),
  mc(10,'Building suspense in a narrative: which technique is most effective?','Using only Past Simple','Using short sentences to increase pace','Avoiding descriptive language','Using Present Simple throughout','B'),
  tf(11,'Past Continuous is used in narratives for background actions.','true'),
  tf(12,'Past Perfect in narratives explains what had happened before the main story event.','true'),
  tf(13,'"Against all odds" means with great support and easy conditions.','false'),
  fb(14,'We ___ (had been hiking) for six hours when the storm suddenly broke.','had been hiking'),
  fb(15,'Against all ___ (odds), the small team completed the crossing.','odds'),
]},

'16ef48c9-01d5-4154-a7f9-d2ae6f7061c1':{pass_threshold:70,questions:[
  mc(1,'Complete: "He ___ (fracture) his leg in the fall."','fractures','fractured','has fractured','was fracturing','B'),
  mc(2,'"Sprain" means:','to break a bone','to twist a joint, damaging the ligaments','to cut the skin','to dislocate a joint','B'),
  mc(3,'"Sustain an injury" is a collocation meaning:','to treat an injury','to cause an injury to someone else','to suffer/receive an injury','to recover from an injury','C'),
  mc(4,'Complete: "Despite sustaining a ___ (serious/seriously/seriousness/serioused) injury, she finished the race."','seriously','seriousness','serioused','serious','D'),
  mc(5,'"A narrow escape" means:','a wide exit route','barely avoiding a dangerous or fatal situation','a planned emergency exit','a common occurrence','B'),
  mc(6,'Complete: "The rescue team ___ (arrive) just in time."','arrives','arrived','were arriving','had arrive','B'),
  mc(7,'"Hypothermia" is:','overheating of the body','a type of altitude sickness','a dangerously low body temperature','dehydration','C'),
  mc(8,'"First aid" refers to:','a long-term medical treatment','the first medical attention given to someone in an emergency','a hospital procedure','regular health check-ups','B'),
  mc(9,'Complete: "She managed to ___ (make) it to safety despite the blizzard."','made','making','makes','make','D'),
  mc(10,'"Ordeal" means:','a pleasant adventure','a type of sports equipment','a highly unpleasant or difficult experience','a formal ceremony','C'),
  tf(11,'"Fracture" and "sprain" both refer to injuries involving broken bones.','false'),
  tf(12,'"Sustain" collocates with "injury" (sustain an injury).','true'),
  tf(13,'"Ordeal" has a positive connotation.','false'),
  fb(14,'It was a ___ (miraculous) escape — nobody was seriously injured.','miraculous'),
  fb(15,'They were rescued after enduring a three-day ___ (ordeal) in the freezing mountains.','ordeal'),
]},

'3aa9f716-26f6-4908-b97c-64369e53a036':{pass_threshold:70,questions:[
  mc(1,'Which tense best describes what had already happened before the main story?','Past Simple','Past Continuous','Past Perfect','Present Perfect','C'),
  mc(2,'Complete: "After ___ (be) stranded for two days, they were finally rescued."','being','been','be','to be','A'),
  mc(3,'"Resourcefulness" means:','having many physical resources','the ability to find creative solutions in difficult situations','being reckless','being overly cautious','B'),
  mc(4,'Complete: "They had ___ (exhaust) their supplies by day three."','exhausted','exhausting','exhaust','been exhausting','A'),
  mc(5,'"Against the elements" means:','with help from nature','in conflict or struggle with natural forces','beside natural features','avoiding natural areas','B'),
  mc(6,'"Perseverance" means:','giving up when things get hard','continued effort despite difficulty or delay','physical strength','quick thinking','B'),
  mc(7,'Complete: "Not ___ (until/unless/though/whether) rescue arrived on day four did they abandon hope."','unless','though','whether','until','D'),
  mc(8,'Complete: "Their ___ (determination/determined/determine/determines) kept them alive."','determined','determine','determines','determination','D'),
  mc(9,'"Harrowing" means:','mildly unpleasant','intensely distressing or traumatic','exciting and positive','motivating','B'),
  mc(10,'Complete: "The survivors later ___ (recount) their ordeal in a bestselling memoir."','recount','recounting','recounted','were recount','C'),
  tf(11,'"Perseverance" and "persistence" have similar meanings.','true'),
  tf(12,'"Harrowing" has a positive connotation.','false'),
  tf(13,'"Resourcefulness" is particularly valued in survival situations.','true'),
  fb(14,'Their ___ (survival) was nothing short of miraculous.','survival'),
  fb(15,'She ___ (recounted) every detail of the harrowing ordeal.','recounted'),
]},

'bebd8391-e0bc-4586-a404-c163cdcb3c1f':{pass_threshold:80,questions:[
  mc(1,'"Thrill-seeker" is someone who actively seeks:','routine and safety','remote quiet locations','exciting and often dangerous experiences','indoor hobbies','C'),
  mc(2,'"Off the beaten track" means:','on a popular tourist route','in a familiar environment','in a remote or unexplored place','with a tour guide','C'),
  mc(3,'"Get cold feet" means:','to become physically cold','to become nervous before doing something','to travel to cold climates','to change your route','B'),
  mc(4,'Narrative tenses: "While we ___, the storm broke."','paddled','were paddling','had been paddling','paddle','B'),
  mc(5,'"Against all odds" means:','with significant advantages','against the rules','with great ease','despite very unfavorable circumstances','D'),
  mc(6,'Complete: "He ___ (fractured) his wrist in the fall."','fractures','had fracture','fractured','is fracturing','C'),
  mc(7,'"Sustain an injury" means:','to treat an injury','to cause injury to others','to suffer an injury','to prevent injury','C'),
  mc(8,'"Perseverance" means:','giving up quickly','continuous effort despite difficulty','physical endurance only','risk-taking behavior','B'),
  mc(9,'"Harrowing" means:','mildly difficult','exciting and positive','intensely distressing','motivating and inspiring','C'),
  mc(10,'Complete collocation: "___ a risk."','make','do','get','take','D'),
  mc(11,'"Blaze a trail" means:','to start a fire for warmth','to be the first to do something new','to follow an existing path','to get lost','B'),
  mc(12,'Complete: "By the time they reached base camp, they ___ for 14 hours."','were walking','walked','have been walking','had been walking','D'),
  mc(13,'"Due diligence" in a safety context means:','ignoring risks','proper careful investigation and precaution','taking unnecessary risks','acting without preparation','B'),
  mc(14,'"Resourcefulness" means:','owning many resources','having physical strength','finding creative solutions in difficult circumstances','following a strict plan','C'),
  mc(15,'Complete: "___ (Seldom/Barely/Never) had she faced such a terrifying situation." (inversion)','Rarely','Often','Scarcely','Never','D'),
  tf(16,'"White-water rafting" involves navigating strong river rapids.','true'),
  tf(17,'"A narrow escape" means something that happened easily without problems.','false'),
  tf(18,'"Hypothermia" is caused by extreme cold.','true'),
  fb(19,'___ (Against all odds), the rescue team reached the survivors in time.','Against all odds'),
  fb(20,'She ___ (recounted) the harrowing tale of survival to a captivated audience.','recounted'),
]},

// ── MODULE 12: Health & Lifestyle ───────────────────────────────────────────

'cadb1440-5c84-4949-85e5-bc7095bd192b':{pass_threshold:70,questions:[
  mc(1,'Complete: "lead a ___ lifestyle."','health','healthier','healthily','healthy','D'),
  mc(2,'Complete: "___ a balanced diet."','make','do','follow','get','C'),
  mc(3,'"Sedentary" lifestyle means:','very active','involving little physical activity','outdoors-focused','healthy and balanced','B'),
  mc(4,'Complete: "She ___ (take) up yoga to improve her flexibility."','took','takes','has take','taking','A'),
  mc(5,'"Holistic" health approach considers:','only physical symptoms','only medication','the whole person — body, mind, and lifestyle','diet only','C'),
  mc(6,'Complete: "___ a habit." (form a habit)','make','develop/form','do','get','B'),
  mc(7,'"Metabolism" refers to:','the immune system','physical strength','sleep quality','chemical processes in the body that maintain life','D'),
  mc(8,'"Cardiovascular exercise" benefits:','only muscle strength','only flexibility','the heart and circulatory system','only mental health','C'),
  mc(9,'Complete: "She follows a ___ diet, avoiding all animal products."','vegetarian','balanced','vegan','restricted','C'),
  mc(10,'"Moderation" in healthy living means:','avoiding everything enjoyable','consuming everything in large amounts','consuming in reasonable, balanced amounts','following extreme diets','C'),
  tf(11,'"Sedentary" has a positive health connotation.','false'),
  tf(12,'"Holistic health" considers mental, physical, and social well-being.','true'),
  tf(13,'"Metabolism" refers to how the body processes food and produces energy.','true'),
  fb(14,'She decided to ___ (cut down on) processed foods and sugar.','cut down on'),
  fb(15,'A ___ (sedentary) lifestyle significantly increases the risk of cardiovascular disease.','sedentary'),
]},

'ebcec5e5-6327-4267-9bbd-fe444e5caf08':{pass_threshold:70,questions:[
  mc(1,'"Addiction" is characterized by:','occasional use without negative effects','compulsive dependence despite harmful consequences','enjoying a hobby regularly','taking prescribed medication','B'),
  mc(2,'Complete: "___ a habit." (give up a habit)','lose','kick/break','end','stop','B'),
  mc(3,'"Withdrawal symptoms" occur when:','someone starts a new habit','a person reduces or stops a substance they are dependent on','someone exercises too much','someone tries a new diet','B'),
  mc(4,'Complete: "She ___ (give up) smoking after a health scare."','give up','gives up','gave up','given up','C'),
  mc(5,'"Compulsive" behavior is:','done once by choice','moderate and controlled','hard to control or stop, driven by an urge','done occasionally for pleasure','C'),
  mc(6,'Complete: "He couldn\'t ___ (break) his habit of checking his phone every few minutes."','breaking','broke','break','breaks','C'),
  mc(7,'"Relapse" means:','successfully overcoming an addiction','beginning treatment','returning to a previous harmful behavior after improvement','developing a new habit','C'),
  mc(8,'"Moderation" when discussing habits means:','extreme restriction','doing something without any control','doing something in limited, controlled amounts','avoiding something completely','C'),
  mc(9,'"Peer pressure" influences:','individual decision-making only','social media habits','behavior through influence from one\'s social group','government policy','C'),
  mc(10,'Complete: "The ___ (adverse/adversely/adversity/adverted) effects of excessive alcohol are well documented."','adversely','adversity','adverted','adverse','D'),
  tf(11,'"Kick a habit" means to successfully give up a bad habit.','true'),
  tf(12,'"Withdrawal" symptoms are experienced when someone starts a new addiction.','false'),
  tf(13,'"Compulsive" behavior is easy to control and stop.','false'),
  fb(14,'After years of struggle, she finally ___ (kicked) her addiction to caffeine.','kicked'),
  fb(15,'Relapse ___ (rates) remain high for many types of addiction.','rates'),
]},

'966f43dc-7667-4a6a-9110-15c9b5b0f182':{pass_threshold:70,questions:[
  mc(1,'Which adjective is UNGRADABLE (extreme)?','beautiful','good-looking','attractive','stunning','D'),
  mc(2,'Complete: "She was ___ gorgeous." (ungradable intensifier)','very','quite','absolutely','fairly','C'),
  mc(3,'What does "immaculate" mean in the context of appearance?','slightly untidy','extremely clean and well-presented','casually dressed','average-looking','B'),
  mc(4,'"Striking" appearance means:','ordinary and unremarkable','physically attractive in a dramatic way','slightly above average','plain and simple','B'),
  mc(5,'Complete: "The model was ___ perfect." (ungradable)','fairly','quite','very','utterly','D'),
  mc(6,'"Flawless" means:','slightly imperfect','without any flaws or imperfections','naturally imperfect','deliberately messy','B'),
  mc(7,'"Gaunt" describes someone who:','is very fit and muscular','has a healthy glow','is very thin and bony, often due to illness','is slightly overweight','C'),
  mc(8,'Complete: "Despite her ___ (exhausting/exhausted/exhaustion/exhaust) schedule, she always looks composed."','exhausted','exhaustion','exhaust','exhausting','D'),
  mc(9,'"Radiant" typically describes:','a pale and unhealthy look','a bright, glowing, and healthy appearance','a very thin appearance','a tired complexion','B'),
  mc(10,'Gradable vs Ungradable: which CAN be modified by "very"?','beautiful/gorgeous','exhausted/freezing','perfect/unique','enormous/brilliant','A'),
  tf(11,'"Utterly" is used with ungradable (extreme) adjectives.','true'),
  tf(12,'"She was very stunning" is grammatically correct.','false'),
  tf(13,'"Flawless" and "immaculate" both mean without any defect or fault.','true'),
  fb(14,'She looked ___ (absolutely) radiant on her wedding day.','absolutely'),
  fb(15,'His ___ (gaunt) appearance made everyone worry about his health.','gaunt'),
]},

'90e77827-49b7-4fa2-87f7-82ed4c6af83f':{pass_threshold:70,questions:[
  mc(1,'Which phrase appropriately introduces mental health topics?','What\'s wrong with you?','It\'s nothing serious.','I want to check in — how are you really doing?','Stop being dramatic.','C'),
  mc(2,'"Anxiety" is best described as:','extreme happiness','a persistent feeling of worry, unease, or fear','occasional sadness','physical pain','B'),
  mc(3,'"Stigma" around mental health means:','wide acceptance','strong support from society','a mark of disgrace or shame that discourages people from seeking help','government policy','C'),
  mc(4,'Complete: "She ___ (struggle) with depression for several years."','struggles','struggled','struggling','struggle','B'),
  mc(5,'"Burnout" is:','a type of fire','physical and emotional exhaustion from prolonged stress','mild fatigue','excitement about work','B'),
  mc(6,'"Resilience" in psychology means:','inability to cope','complete avoidance of stress','the capacity to recover quickly from difficulties','never experiencing stress','C'),
  mc(7,'Complete: "It takes courage to ___ help for mental health issues."','ask','seek','request','find','B'),
  mc(8,'"Mindfulness" refers to:','ignoring emotions','staying constantly busy','being fully aware and present in the current moment','multitasking effectively','C'),
  mc(9,'Which phrase AVOIDS stigmatizing language?','She is mentally ill.','He is a schizophrenic.','She lives with schizophrenia.','He\'s crazy.','C'),
  mc(10,'Complete: "She ___ (cope) remarkably well with the pressure."','cope','coped','coping','copes','B'),
  tf(11,'"Burnout" is exclusively a physical condition.','false'),
  tf(12,'"Mindfulness" practices can reduce stress and anxiety.','true'),
  tf(13,'Using person-first language (e.g., "person with depression") is recommended in mental health contexts.','true'),
  fb(14,'She finally sought ___ (help) from a therapist after months of struggling alone.','help'),
  fb(15,'Reducing the ___ (stigma) around mental health is essential for public well-being.','stigma'),
]},

'edd68776-73f2-4c63-aca8-ac4857c9072a':{pass_threshold:70,questions:[
  mc(1,'Complete: "___ a diet." (follow / go on)','make','follow / go on','do','start','B'),
  mc(2,'Complete: "___ weight." (put on / gain / lose)','make','do','put on / gain / lose','take','C'),
  mc(3,'"Calorie deficit" means:','consuming more calories than you burn','consuming fewer calories than you burn','having exactly the right calories','avoiding all calories','B'),
  mc(4,'Complete: "___ exercise." (take / do / get)','make','take / do / get','have','go','B'),
  mc(5,'"Endurance" in sports refers to:','strength training','flexibility','the ability to sustain prolonged physical effort','speed training','C'),
  mc(6,'Complete: "She ___ (work) out six days a week."','works','worked','work','working','A'),
  mc(7,'"Interval training" involves:','long steady workouts','alternating between high and low intensity periods','only stretching','yoga and meditation','B'),
  mc(8,'Complete: "A ___ (balance/balanced/balancing/balancer) diet includes all food groups."','balance','balancing','balancer','balanced','D'),
  mc(9,'"Sedentary" lifestyle increases the risk of:','athletic achievement','cardiovascular disease, diabetes, and obesity','improved fitness','muscle gain','B'),
  mc(10,'Complete: "She ___ (commit) to a regular exercise routine after her health check."','commit','commits','committed','committing','C'),
  tf(11,'"Interval training" and "endurance training" are exactly the same thing.','false'),
  tf(12,'"Calorie deficit" is commonly associated with weight loss.','true'),
  tf(13,'A "balanced diet" includes proteins, carbohydrates, fats, vitamins, and minerals.','true'),
  fb(14,'She ___ (committed to) a healthier lifestyle after her doctor\'s advice.','committed to'),
  fb(15,'Regular ___ (cardiovascular) exercise significantly reduces the risk of heart disease.','cardiovascular'),
]},

'555be8f7-7c8d-4c5c-9f66-f64d319832c4':{pass_threshold:70,questions:[
  mc(1,'Complete: "The patient was ___ (diagnose) with hypertension."','diagnosed','diagnosing','diagnose','diagnosis','A'),
  mc(2,'"Prognosis" means:','the cause of a disease','a doctor\'s opinion about the likely course and outcome of a disease','a list of symptoms','a type of treatment','B'),
  mc(3,'"Chronic" illness means:','sudden and severe','lasting a long time or recurring','easily curable','mild and temporary','B'),
  mc(4,'"Acute" illness means:','lasting a long time','easily prevented','severe and sudden in onset','mild and chronic','C'),
  mc(5,'Complete: "She ___ (prescribe) a course of antibiotics."','was prescribed','prescribed','has prescribed','prescribes','A'),
  mc(6,'"Remission" means:','getting worse','a period when a disease is less active or absent','being cured permanently','starting treatment','B'),
  mc(7,'Complete: "The symptoms ___ (subside) after a week of medication."','subside','subsided','subsiding','have subsided','B'),
  mc(8,'"Contraindication" means:','a reason FOR a treatment','a side effect','a reason AGAINST a treatment due to risk','a type of medication','C'),
  mc(9,'"Preventive medicine" focuses on:','treating existing diseases','diagnosing rare conditions','preventing disease before it occurs','emergency care','C'),
  mc(10,'Complete: "Regular screenings can help ___ (detect) cancer at an early stage."','detection','detected','detecting','detect','D'),
  tf(11,'"Chronic" and "acute" are antonyms in medical terminology.','true'),
  tf(12,'"Prognosis" and "diagnosis" have the same meaning.','false'),
  tf(13,'"Remission" in oncology means the cancer is completely cured.','false'),
  fb(14,'The doctor gave a positive ___ (prognosis), predicting a full recovery.','prognosis'),
  fb(15,'She was ___ (prescribed) a strict course of treatment by the specialist.','prescribed'),
]},

'f520d7b1-df30-42ae-92df-e5d4f35a31fd':{pass_threshold:70,questions:[
  mc(1,'Complete: "She ___ (give up) processed food for a month as an experiment."','gives up','gave up','give up','given up','B'),
  mc(2,'"Work-life balance" refers to:','working as much as possible','dividing time effectively between professional and personal life','avoiding work completely','maximizing leisure time','B'),
  mc(3,'"Screen time" refers to:','time spent exercising','time spent outdoors','time spent looking at digital screens','time reading books','C'),
  mc(4,'Complete: "More people are ___ (opt) for plant-based diets."','opt','opted','opting','opts','C'),
  mc(5,'"Moderation" is key to:','extreme dieting','sustainable healthy habits','intense training programs','avoidance of all enjoyment','B'),
  mc(6,'"Sustainable" lifestyle choices are those that:','are very expensive','can be maintained over time without negative impact','require extreme sacrifice','are fashionable temporarily','B'),
  mc(7,'Complete: "She made a conscious decision to ___ (prioritize) her mental health."','priorities','prioritized','prioritize','prioritizing','C'),
  mc(8,'"Sedentary behavior" is linked to:','improved cardiovascular health','increased flexibility','higher risk of chronic disease','faster metabolism','C'),
  mc(9,'"Digital detox" means:','upgrading your devices','a period of abstaining from digital technology','improving your digital skills','using technology more efficiently','B'),
  mc(10,'Complete: "They ___ (adopt) a more flexible approach to their daily routine."','adopt','adopting','adopted','adopts','C'),
  tf(11,'"Work-life balance" is important for long-term well-being.','true'),
  tf(12,'"Digital detox" involves spending more time on social media.','false'),
  tf(13,'"Sustainable" habits are those that can be maintained over the long term.','true'),
  fb(14,'She decided to ___ (prioritize) sleep as a key part of her wellness plan.','prioritize'),
  fb(15,'A ___ (sustainable) approach to fitness is more effective than quick-fix solutions.','sustainable'),
]},

'f38a8817-cddd-4160-b3af-1329a49b1e60':{pass_threshold:80,questions:[
  mc(1,'"Sedentary" lifestyle means:','very active and outdoors','mostly inactive, involving little physical movement','balanced and healthy','highly stressful','B'),
  mc(2,'Complete: "follow a ___."','diet balanced','balancing diet','balanced diet','balance diet','C'),
  mc(3,'"Burnout" is characterized by:','excessive energy','physical and emotional exhaustion from chronic stress','occasional mild fatigue','enthusiasm for work','B'),
  mc(4,'"Mindfulness" involves:','multitasking','ignoring emotions','being fully present and aware in the current moment','planning the future','C'),
  mc(5,'"Chronic" illness is:','sudden and severe','long-lasting or recurring','easily cured','very mild','B'),
  mc(6,'"Prognosis" means:','cause of disease','type of treatment','list of symptoms','doctor\'s prediction about the course of illness','D'),
  mc(7,'Complete: "She was ___ (prescribe) antibiotics for the infection."','prescribing','prescribed','prescribes','prescription','B'),
  mc(8,'Complete: "___ (Kick/Break/Lose/End) a habit" (successfully stop a bad habit)','Lose','End','Break/Kick','Get','C'),
  mc(9,'"Remission" means:','getting worse','starting treatment','a period when symptoms are less active or absent','permanent cure','C'),
  mc(10,'Ungradable adjective: which is correctly modified?','very stunning','absolutely perfect','rather flawless','a bit unique','B'),
  mc(11,'"Resilience" in psychology means:','inability to cope with stress','the capacity to recover quickly from difficulties','complete avoidance of stress','never experiencing difficulty','B'),
  mc(12,'"Work-life balance" refers to:','working as much as possible','avoiding work','effective division between professional and personal life','maximizing leisure time','C'),
  mc(13,'Complete: "she managed to ___ up smoking."','gave','give','giving','given','B'),
  mc(14,'"Digital detox" means:','using technology more efficiently','a period of abstaining from digital devices','upgrading your devices','learning digital skills','B'),
  mc(15,'"Sustainable" habits are:','fashionable temporarily','very expensive','requiring extreme sacrifice','maintainable over time without negative impact','D'),
  tf(16,'"Addiction" involves compulsive behavior despite harmful consequences.','true'),
  tf(17,'"Acute" illness lasts a long time and recurs frequently.','false'),
  tf(18,'Using person-first language (e.g., "person with depression") is recommended in healthcare.','true'),
  fb(19,'She ___ (prioritized) her mental well-being by setting clear work boundaries.','prioritized'),
  fb(20,'The doctor gave an optimistic ___ (prognosis) after reviewing the test results.','prognosis'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 9: "Reported Speech Mastery"', lessons: ['c3089ed4-60fb-4429-a741-087b808217d0','102b08a3-f846-4a9a-b646-ad4eb85cbc96','bb22d1a5-ab78-4a89-b77a-ad8d4b9a8f77','32ab9412-0505-425e-b092-96114511bf7b','727ac288-0ddb-4618-a5c7-22aa45546af7','c23b5024-9c5b-4c26-ae08-057e5886f6f7','ec51cda9-a326-4bac-a5a9-554bf68eaca0','6243e904-dbe5-4d84-8e6e-5bcdb365a577'] },
  { name: 'Module 10: "Advanced Grammar I"', lessons: ['ce4ca1f2-e43c-4d3c-8267-0c77c3fcd372','24c46ed5-dd6e-4492-843a-ea77d69d7e16','3170d617-3589-4388-9f21-8d5e7fd9192a','4fd512d1-04c3-42a0-8e50-dd2c453b99c6','b3c814ae-4d8b-4dfa-a28a-ab94bee24bc1','18a63002-2493-4360-8707-36c76eb13977','02c9d60f-817d-4860-866c-bc982bf9415f','9b9bc661-86fa-4c50-8b99-bddc0dd01789','24805033-338b-4dc7-9d81-e749da4bbd11','6f0bd2c8-9775-43ae-ad99-bad384869927','c6db6d5e-085c-4987-803a-68921cdecb14'] },
  { name: 'Module 11: "Adrenaline & Adventure"', lessons: ['7ac04f1b-c7a5-4d2a-bdae-ea5550c4855a','8aab8f12-b966-44af-b7ce-3b6f87a98c54','be520d3f-8902-43eb-aae8-6f720b8f23c6','7c4672be-21a8-4af4-94be-5b82701b4b13','884ddd78-8a5e-42cf-87d2-4de5348fff22','16ef48c9-01d5-4154-a7f9-d2ae6f7061c1','3aa9f716-26f6-4908-b97c-64369e53a036','bebd8391-e0bc-4586-a404-c163cdcb3c1f'] },
  { name: 'Module 12: "Health & Lifestyle"', lessons: ['cadb1440-5c84-4949-85e5-bc7095bd192b','ebcec5e5-6327-4267-9bbd-fe444e5caf08','966f43dc-7667-4a6a-9110-15c9b5b0f182','90e77827-49b7-4fa2-87f7-82ed4c6af83f','edd68776-73f2-4c63-aca8-ac4857c9072a','555be8f7-7c8d-4c5c-9f66-f64d319832c4','f520d7b1-df30-42ae-92df-e5d4f35a31fd','f38a8817-cddd-4160-b3af-1329a49b1e60'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 9–12 B2 Upper-Intermediate');
}
main();
