/**
 * B1 Intermediate — Modules 4, 5, 6.
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-b1-mod4-6.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // ═══ MODULE 4: Money & Shopping ═══
  '09eca220-06e7-4c3b-9290-2c75b6e6d8d4':{pass_threshold:70,questions:[ // Comparatives Review
    mc(1,'Comparative of "expensive"?','more expensive','expensiver','most expensive','the most expensive','A'),
    mc(2,'Comparative of "good"?','gooder','more good','better','bester','C'),
    mc(3,'Complete: "Online shopping is ___ (convenient) ___ going to a physical store."','more convenient / than','convenienter / than','most convenient / than','more convenient / that','A'),
    mc(4,'Comparative of "cheap"?','more cheap','cheaper','cheapest','the cheaper','B'),
    mc(5,'Complete: "The ___ (early) you buy, the ___ (good) the deal."','more early / gooder','earlier / better','earliest / best','earlier / best','B'),
    mc(6,'Comparative of "far"?','farer','farther/further','more far','most far','B'),
    mc(7,'Complete: "This product is ___ (much) overpriced ___ the competitor\'s."','more much / than','much more / than','much more / that','much / than','B'),
    mc(8,'Double comparative: Choose correct.','The more you spend, the less you save.','The more you spend, the fewer you save.','The more you spend, the more less you save.','More you spend, less you save.','A'),
    mc(9,'Comparative of "little" (amount)?','littler','more little','less','lesser','C'),
    mc(10,'Complete: "She is a ___ (experienced) negotiator ___ her colleague."','more experienced / than','most experienced / than','experienced more / than','more experience / than','A'),
    tf(11,'The comparative of "bad" is "worse".','true'),
    tf(12,'"More cheaper" is correct.','false'),
    tf(13,'"The harder you work, the better the results" uses double comparative correctly.','true'),
    fb(14,'This deal is ___ (good) than the last one. It is ___ (much) affordable than I expected.','better, much more'),
    fb(15,'The ___ (more) you invest, the ___ (high) the potential return.','more, higher'),
  ]},
  'c2f11a19-9b4a-479a-9990-6d9ab633bcd5':{pass_threshold:70,questions:[ // As...As / Not As...As
    mc(1,'"As...as" is used to show:','superiority','inferiority','equality','difference','C'),
    mc(2,'"Not as...as" is used to show:','equality','that one thing is less than another','superiority','a double comparison','B'),
    mc(3,'Complete: "This phone is ___ expensive ___ the flagship model."','as / as','not as / as','more / than','less / than','B'),
    mc(4,'Complete: "She earns ___ much ___ her manager." (they earn the same)','not as / as','as / as','more / than','so / as','B'),
    mc(5,'Complete: "Online prices are ___ competitive ___ ever."','not as / as','as / as','more / than','as / than','B'),
    mc(6,'Complete: "The service wasn\'t ___ good ___ I expected."','as / as','as / than','so / as (both A and C acceptable)','not / as','C'),
    mc(7,'Choose the correct sentence:','She is not as tall than him.','She is not as tall as him.','She is not so tall than him.','She is less tall as him.','B'),
    mc(8,'Complete: "This laptop performs ___ well ___ the more expensive one."','so / as','as / as','not as / as','as / than','B'),
    mc(9,'Complete: "The discount wasn\'t ___ large ___ advertised."','more / than','as / than','as / as','not as / than','C'),
    mc(10,'Complete: "He is ___ influential ___ his predecessor." (equal influence)','not as / as','more / than','as / as','less / than','C'),
    tf(11,'"As...as" expresses equality between two things.','true'),
    tf(12,'"Not as tall than him" is correct.','false'),
    tf(13,'"Not as...as" and "less...than" can sometimes express the same idea.','true'),
    fb(14,'This budget laptop is not ___ (powerful) ___ the premium model.','as powerful as'),
    fb(15,'Prices here are ___ (low) ___ in the discount store. (not equal — lower)','not as low as / lower than'),
  ]},
  '02d431dd-2495-415b-bcf6-1a295344dab3':{pass_threshold:70,questions:[ // Advertising — Persuasive Language
    mc(1,'What is "a call to action" in advertising?','a background image','a phrase that urges the audience to do something immediately','a product description','a legal disclaimer','B'),
    mc(2,'What does "testimonial" mean in advertising?','a celebrity appearance','a customer statement endorsing a product','a jingle','a price comparison','B'),
    mc(3,'What is "bandwagon appeal"?','a logical argument','persuading people to join because "everyone is doing it"','a fear-based approach','an expert endorsement','B'),
    mc(4,'What is a "USP" (Unique Selling Point)?','a price strategy','what makes a product different and better than competitors','a type of discount','a slogan','B'),
    mc(5,'What does "scarcity appeal" do?','increases price','creates urgency by suggesting limited availability','reduces demand','explains the product\'s features','B'),
    mc(6,'What is "greenwashing"?','making products green in colour','falsely claiming a product is environmentally friendly','a type of eco-advertising','a green marketing strategy','B'),
    mc(7,'What does "targeted advertising" mean?','advertising to everyone','showing ads to specific audiences based on data','a TV advertisement','a billboard campaign','B'),
    mc(8,'What is "emotional appeal" in advertising?','using logic to persuade','using facts and figures','using emotions to connect with the audience','using celebrity endorsement only','C'),
    mc(9,'What is an "endorsement"?','a price reduction','a complaint','approval or recommendation from a famous person','a type of contract','C'),
    mc(10,'What does "brand loyalty" mean?','switching brands frequently','consistently preferring and purchasing a specific brand','buying the cheapest option','avoiding brand-name products','B'),
    tf(11,'A "USP" distinguishes a product from its competitors.','true'),
    tf(12,'"Greenwashing" refers to genuinely sustainable marketing practices.','false'),
    tf(13,'"Bandwagon appeal" encourages people to join a trend that "everyone" is following.','true'),
    fb(14,'___ (Testimonials) from satisfied customers build trust. A "___ (USP)" makes a product stand out.','Testimonials, USP'),
    fb(15,'"Buy now before it\'s gone!" is an example of ___ (scarcity) appeal. "___ (Greenwashing)" falsely claims eco-friendliness.','scarcity, Greenwashing'),
  ]},
  'f339c17d-9ae5-4f95-95a2-2aab56bcef08':{pass_threshold:70,questions:[ // Consumer Society — Vocabulary
    mc(1,'What is "consumerism"?','a political system','a culture focused on buying and consuming goods','a type of environmental movement','a savings strategy','B'),
    mc(2,'What does "disposable income" mean?','money thrown away','income available after taxes and essential expenses','total gross income','income from investments','B'),
    mc(3,'What is "fast fashion"?','expensive designer clothing','quickly produced, low-cost, short-lived clothing','athletic wear','sustainable fashion','B'),
    mc(4,'What does "ethical consumption" mean?','buying the cheapest products','buying while considering the social, environmental, and ethical impact','consumption of organic food only','avoiding all shopping','B'),
    mc(5,'What is "planned obsolescence"?','a quality assurance strategy','designing products to become outdated or unusable within a short time','recycling programmes','long-term product warranties','B'),
    mc(6,'What does "impulse buying" mean?','carefully planned purchases','purchasing without prior planning, driven by sudden desire','bulk buying','online shopping','B'),
    mc(7,'What is a "loyalty card"?','a credit card','a card that rewards repeat customers with points or discounts','a gift card','a student discount card','B'),
    mc(8,'What does "consumer rights" refer to?','rights of companies','legal protections for buyers of goods and services','marketing regulations','import duties','B'),
    mc(9,'What is "overconsumption"?','buying nothing','consuming far more resources than is sustainable','careful shopping','minimal spending','B'),
    mc(10,'What does "second-hand" (secondhand) mean?','brand new','previously owned','made from recycled materials','imported goods','B'),
    tf(11,'"Planned obsolescence" involves designing products to become outdated quickly.','true'),
    tf(12,'"Impulse buying" refers to carefully planned purchases.','false'),
    tf(13,'"Ethical consumption" considers the social and environmental impact of purchases.','true'),
    fb(14,'___ (Consumerism) encourages buying more than needed. ___ (Planned obsolescence) makes products go out of date quickly.','Consumerism, Planned obsolescence'),
    fb(15,'___ (Disposable) income is what remains after taxes. ___ (Fast fashion) produces low-cost, short-lived clothes.','Disposable, Fast fashion'),
  ]},
  '2742bd6e-a7a8-493d-8196-f66af1b2a2f2':{pass_threshold:70,questions:[ // Online Shopping — Phrasal Verbs
    mc(1,'What does "shop around" mean?','buy immediately','compare prices at different stores before buying','shop online only','return items','B'),
    mc(2,'What does "add to cart" mean?','remove from cart','place an item in your virtual shopping basket','check out','save for later','B'),
    mc(3,'What does "sign up for" mean?','cancel a service','register or enrol for something','log out of','subscribe to (both A and D — but the answer is "register/enrol")','C'),
    mc(4,'What does "log in" mean?','exit a system','create an account','enter a system using credentials','delete an account','C'),
    mc(5,'What does "track your order" mean?','cancel the order','monitor the delivery progress of your purchase','return the order','pay for the order','B'),
    mc(6,'What does "opt out of" mean?','choose to participate','choose not to participate in something','pay for something','sign up for something','B'),
    mc(7,'What does "check out" mean (online shopping)?','browse the store','add items to cart','complete a purchase and pay','return an item','C'),
    mc(8,'What does "look for" mean?','find immediately','search for something','buy something','compare prices','B'),
    mc(9,'What does "set up an account" mean?','delete an account','browse without an account','create and configure a new account','log into an account','C'),
    mc(10,'What does "run out of stock" mean?','have too much stock','have no more items available','restock','offer a discount','B'),
    tf(11,'"Shop around" means to compare prices before buying.','true'),
    tf(12,'"Check out" online means to browse the store.','false'),
    tf(13,'"Opt out of" means choosing not to participate.','true'),
    fb(14,'She always ___ (shop around) before buying electronics. I ___ (sign up for) the newsletter.','shops around, signed up for'),
    fb(15,'They ___ (run out of) stock during the sale. I need to ___ (log in) to check my order status.','ran out of, log in'),
  ]},
  '52756b27-a9ab-4002-8852-ecc3ff862f9b':{pass_threshold:70,questions:[ // Banking & Saving — Formal Language
    mc(1,'What is an "interest rate"?','a tax on savings','the percentage charged for borrowing or paid for saving money','a banking fee','an investment return','B'),
    mc(2,'What does "to accrue interest" mean?','to pay interest','to gradually accumulate interest over time','to reduce a debt','to open an account','B'),
    mc(3,'What is "compound interest"?','interest on the original amount only','interest calculated on the initial principal and the accumulated interest','a type of tax','a fixed rate of return','B'),
    mc(4,'What does "overdraft" mean?','saving more than needed','spending more than is available in an account, resulting in a negative balance','a type of loan','a bank transfer','B'),
    mc(5,'What is "APR" (Annual Percentage Rate)?','the monthly rate','the yearly cost of borrowing expressed as a percentage','a savings rate','a tax rate','B'),
    mc(6,'What does "to diversify a portfolio" mean?','to invest in one asset only','to spread investments across different asset types to reduce risk','to sell all investments','to open multiple bank accounts','B'),
    mc(7,'What is "inflation"?','a decrease in prices','the rate at which the general level of prices rises over time','a type of investment','a tax policy','B'),
    mc(8,'What is a "current account"?','a savings account with high interest','an everyday bank account used for transactions','a loan account','a retirement fund','B'),
    mc(9,'What does "to default on a loan" mean?','to repay a loan early','to fail to make required loan repayments','to apply for a loan','to increase a loan amount','B'),
    mc(10,'What is "net worth"?','total assets only','total liabilities only','total assets minus total liabilities','annual income','C'),
    tf(11,'"Compound interest" grows faster than simple interest because it includes interest on previously earned interest.','true'),
    tf(12,'An "overdraft" means you have more money than needed in your account.','false'),
    tf(13,'"Diversifying a portfolio" spreads investment risk across multiple assets.','true'),
    fb(14,'___ (Inflation) reduces the purchasing power of money. ___ (APR) expresses the annual cost of borrowing.','Inflation, APR'),
    fb(15,'She ___ (accrue) interest on her savings. He ___ (default) on his loan payments.','accrued, defaulted'),
  ]},
  'eee1566b-59f5-4b1a-88d8-b81eedcb1314':{pass_threshold:70,questions:[ // Budget & Investment — Collocations
    mc(1,'Which is correct?','make a budget','do a budget','set a budget','both A and C','D'),
    mc(2,'Which is correct?','make an investment','do an investment','take an investment','get an investment','A'),
    mc(3,'Which is correct?','achieve financial goals','reach financial goals','both A and B','do financial goals','C'),
    mc(4,'Which is correct?','pay off a debt','pay a debt off','clear a debt','all of the above','D'),
    mc(5,'Which is correct?','cut costs','reduce costs','both A and B','make costs','C'),
    mc(6,'Which is correct with "return"?','earn a return','make a return','both A and B','do a return','C'),
    mc(7,'Which is correct?','save money','save up money','accumulate savings','all of the above','D'),
    mc(8,'Which is correct?','manage finances','handle finances','both A and B','do finances','C'),
    mc(9,'Which is correct?','raise capital','gather capital','collect capital','both A and B','A'),
    mc(10,'Which is correct?','generate revenue','make revenue','produce revenue','all of the above','D'),
    tf(11,'"Make an investment" is a correct collocation.','true'),
    tf(12,'"Do a budget" is the most natural collocation in financial English.','false'),
    tf(13,'"Pay off a debt" means to finish repaying a debt completely.','true'),
    fb(14,'They ___ (set) a budget and ___ (cut) unnecessary costs.','set, cut'),
    fb(15,'She ___ (make) a wise investment and ___ (achieve) her financial goals.','made, achieved'),
  ]},
  '8e0e8898-adab-46f5-b366-26dda131b91f':{pass_threshold:80,questions:[ // Module 4 Review
    mc(1,'Comparative of "expensive"?','more expensive','expensiver','most expensive','the most expensive','A'),
    mc(2,'"As...as" shows:','superiority','inferiority','equality','difference','C'),
    mc(3,'Complete: "This phone is not ___ (fast) ___ the new model."','as fast as','so fast than','more fast than','faster than','A'),
    mc(4,'What is a "USP"?','a price strategy','what makes a product unique/better','a type of discount','a slogan','B'),
    mc(5,'What is "greenwashing"?','genuine eco-marketing','falsely claiming eco-friendliness','green product design','a recycling campaign','B'),
    mc(6,'What is "planned obsolescence"?','quality assurance','designing products to become outdated quickly','recycling programmes','long-term warranties','B'),
    mc(7,'What does "shop around" mean?','buy immediately','compare prices before buying','shop online only','return items','B'),
    mc(8,'What does "opt out of" mean?','choose to join','choose not to participate','pay for something','sign up for','B'),
    mc(9,'What is "compound interest"?','interest on principal only','interest on principal plus accumulated interest','a tax','a fixed return','B'),
    mc(10,'What is "APR"?','monthly rate','yearly cost of borrowing as a percentage','a savings rate','a tax rate','B'),
    mc(11,'Which is correct?','make a budget','set a budget','both A and B','do a budget','C'),
    mc(12,'"Pay off a debt" means:','take more debt','make a partial payment','repay a debt completely','increase a debt','C'),
    mc(13,'"Double comparative": "The ___ you invest, the ___ the return."','more / high','more / higher','most / highest','more / most','B'),
    mc(14,'What does "disposable income" mean?','money wasted','income after taxes and necessities','total gross income','investment returns','B'),
    mc(15,'What does "impulse buying" mean?','planned purchases','buying driven by sudden desire without planning','bulk buying','online shopping','B'),
    tf(16,'"More cheaper" is correct English.','false'),
    tf(17,'"Bandwagon appeal" persuades people that "everyone is doing it".','true'),
    tf(18,'An overdraft means you\'ve spent more than is in your account.','true'),
    fb(19,'This laptop is not ___ (powerful) ___ the flagship model. The ___ (more) you save, the ___ (better) your future.','as powerful as, more, better'),
    fb(20,'She ___ (set) a budget and ___ (cut) costs. He ___ (make) a wise investment.','set, cut, made'),
  ]},

  // ═══ MODULE 5: Law & Society ═══
  'b69b3731-2569-4e79-bbbd-c0998f91805a':{pass_threshold:70,questions:[ // Passive Voice Simple
    mc(1,'Present Simple Passive: "Laws ___ (enact) by parliament."','enact','are enacted','enacted','have enacted','B'),
    mc(2,'Past Simple Passive: "The suspect ___ (arrest) last night."','arrested','was arrested','has been arrested','is arrested','B'),
    mc(3,'Change to passive: "The judge sentenced the defendant."','The defendant sentenced the judge.','The defendant was sentenced by the judge.','The defendant is sentenced.','The judge was sentenced.','B'),
    mc(4,'Why is passive used in legal contexts?','to make text shorter','to focus on the action/outcome rather than who performed it','it sounds more casual','it avoids using "they"','B'),
    mc(5,'Complete: "Evidence ___ (submit) by both parties before the hearing."','submitted','was submitted','submits','had submitted','B'),
    mc(6,'Present Passive: "Citizens ___ (protect) by the constitution."','protect','are protected','protected','have protected','B'),
    mc(7,'Past Passive: "The law ___ (repeal) in 2018."','repealed','was repealed','has been repealed','is repealed','B'),
    mc(8,'Change to passive: "Parliament passed the new legislation."','The new legislation passed parliament.','The new legislation was passed by parliament.','The new legislation is passed.','Parliament was passed.','B'),
    mc(9,'Complete: "Fines ___ (impose) on those who violate the regulation."','imposed','are imposed','impose','have imposed','B'),
    mc(10,'Passive voice: "The rights ___ (enshrine) in the constitution decades ago."','enshrined','were enshrined','are enshrined','have enshrined','B'),
    tf(11,'Passive voice focuses on what was done, not who did it.','true'),
    tf(12,'"The defendant was sentenced by the judge" is an incorrect passive sentence.','false'),
    tf(13,'The passive is common in legal and academic writing.','true'),
    fb(14,'The criminal ___ (arrest, past passive) by police. The verdict ___ (announce, present passive) tomorrow.','was arrested, is announced / will be announced'),
    fb(15,'The law ___ (pass, past passive) unanimously. New regulations ___ (implement, present passive) each year.','was passed, are implemented'),
  ]},
  'd6dd4385-5021-4d61-bab4-866252afad3a':{pass_threshold:70,questions:[ // Passive Voice Continuous
    mc(1,'Present Continuous Passive: "The case ___ (investigate) by detectives."','investigates','is being investigated','was investigated','has been investigated','B'),
    mc(2,'Past Continuous Passive: "The witness ___ (question) when we arrived."','questioned','was questioning','was being questioned','has been questioned','C'),
    mc(3,'Complete: "New evidence ___ (currently/analyse) by forensic experts."','is currently being analysed','currently analyses','was currently analysed','has been currently analysed','A'),
    mc(4,'Form of Present Continuous Passive:','am/is/are + being + pp','am/is/are + pp','was/were + being + pp','have/has + been + pp','A'),
    mc(5,'Complete: "The reforms ___ (still/debate) in parliament."','are still being debated','still debates','were still debated','has still debated','A'),
    mc(6,'Complete: "At the time of the raid, the documents ___ (shred)."','were shredding','are being shredded','were being shredded','had shredded','C'),
    mc(7,'Change to passive: "Police are monitoring the suspect."','The suspect is being monitored by police.','The suspect monitors police.','The suspect was monitored.','Police is being monitored.','A'),
    mc(8,'Complete: "Thousands of asylum applications ___ (process) every month."','are being processed','process','processed','were processed','A'),
    mc(9,'Past Continuous Passive form:','was/were + being + pp','was/were + pp','had + been + pp','am/is/are + being + pp','A'),
    mc(10,'Complete: "As the verdict was read, the defendant ___ (escort) to the dock."','was escorting','is being escorted','was being escorted','has been escorted','C'),
    tf(11,'Present Continuous Passive = am/is/are + being + past participle.','true'),
    tf(12,'"The case is being investigate" is correct.','false'),
    tf(13,'Past Continuous Passive describes an action in progress at a past moment.','true'),
    fb(14,'The policy ___ (review, present continuous passive) by a committee. The suspect ___ (question, past continuous passive) when more evidence emerged.','is being reviewed, was being questioned'),
    fb(15,'New procedures ___ (implement, present continuous passive) across all departments. The building ___ (search, past continuous passive) when they found the evidence.','are being implemented, was being searched'),
  ]},
  '9f34ebe7-ad73-499e-8098-5df47778ea42':{pass_threshold:70,questions:[ // Passive Voice Perfect
    mc(1,'Present Perfect Passive: "The verdict ___ (deliver)."','delivered','has been delivered','was delivered','is delivered','B'),
    mc(2,'Past Perfect Passive: "The evidence ___ (destroy) before the trial."','destroyed','was destroyed','had been destroyed','has been destroyed','C'),
    mc(3,'Form of Present Perfect Passive:','was/were + pp','have/has + been + pp','am/is/are + being + pp','had + been + pp','B'),
    mc(4,'Form of Past Perfect Passive:','was/were + pp','have/has + been + pp','am/is/are + being + pp','had + been + pp','D'),
    mc(5,'Complete: "Several witnesses ___ (already/interview) by the time we arrived."','already interviewed','have already been interviewed','had already been interviewed','were already interviewed','C'),
    mc(6,'Complete: "New regulations ___ (introduce) to tackle online fraud."','introduced','were introduced','have been introduced','had introduced','C'),
    mc(7,'Complete: "The case ___ (not/resolve) yet."','not resolved','was not resolved','has not been resolved','hadn\'t resolved','C'),
    mc(8,'Change to passive (PP): "The court has overturned the decision."','The decision has overturned.','The decision has been overturned by the court.','The decision was overturned.','The court was overturned.','B'),
    mc(9,'Past Perfect Passive: "By 2020, the law ___ (amend) three times."','amended three times','was amended three times','has been amended three times','had been amended three times','D'),
    mc(10,'Complete: "The suspect ___ (charge) before the warrant was issued."','was charged','had been charged','has been charged','is charged','B'),
    tf(11,'Present Perfect Passive = have/has + been + past participle.','true'),
    tf(12,'"The evidence had been destroyed" is Past Perfect Passive.','true'),
    tf(13,'"Has been delivered" and "was delivered" always have the same meaning.','false'),
    fb(14,'The law ___ (reform, PP Passive) several times. By last year, the bill ___ (pass, Past Perfect Passive).','has been reformed, had been passed'),
    fb(15,'The case ___ (close, PP Passive) due to lack of evidence. The suspect ___ (release, Past Perfect Passive) before we arrived.','has been closed, had been released'),
  ]},
  '29fe739d-fe60-45b2-9135-bcb67376fa43':{pass_threshold:70,questions:[ // Have Something Done
    mc(1,'"Have something done" is used when:','you do something yourself','you arrange for someone else to do something for you','someone does something without your knowledge','you help someone do something','B'),
    mc(2,'Complete: "She ___ her car ___ (service) every year." (have + done)','has / serviced','had / servicing','gets / service','has / service','A'),
    mc(3,'Complete: "He ___ his suit ___ (tailor) before the court appearance."','had / tailored','has / tailoring','get / tailor','had / tailor','A'),
    mc(4,'What is another way to express "have something done"?','make something do','get something done','do something yourself','let someone do it','B'),
    mc(5,'Complete: "They are ___ the building ___ (inspect) for violations."','have / inspected','having / inspected','making / inspect','letting / inspect','B'),
    mc(6,'Complete: "I ___ my laptop ___ (repair) last week."','have / repaired','had / repaired','make / repaired','get / repair','B'),
    mc(7,'Complete: "She ___ her apartment ___ (renovate) before the inspection."','had / renovated','has / renovating','got / renovate','make / renovated','A'),
    mc(8,'What does "she had her handbag stolen" mean?','she stole a handbag','she had her handbag stolen by someone (unpleasant experience)','she arranged for someone to steal it','she lost her handbag','B'),
    mc(9,'Complete: "The company ___ its accounts ___ (audit) annually."','make / audited','has / audited','had / auditing','gets / audit','B'),
    mc(10,'Complete: "He ___ the contract ___ (draft) by a specialist lawyer."','had / drafted','has / drafting','makes / draft','letting / drafted','A'),
    tf(11,'"Have something done" means someone else performs the action for you.','true'),
    tf(12,'"She had her car repaired" means she repaired it herself.','false'),
    tf(13,'"Get something done" is an informal alternative to "have something done".','true'),
    fb(14,'She ___ (have) her passport ___ (renew). They ___ (get) the office ___ (redecorate).','had, renewed, got, redecorated'),
    fb(15,'He ___ (have) his legal documents ___ (certify). The company ___ (have) its software ___ (update) monthly.','had, certified, has, updated'),
  ]},
  'c42adb94-bff5-40da-90a4-b716830c3ea9':{pass_threshold:70,questions:[ // Passive Voice Review
    mc(1,'Change to passive (present simple): "Courts administer justice."','Justice administers courts.','Justice is administered by courts.','Justice was administered.','Justice has been administered.','B'),
    mc(2,'Change to passive (past simple): "The police arrested the suspect."','The suspect arrested the police.','The suspect is arrested by the police.','The suspect was arrested by the police.','The police was arrested.','C'),
    mc(3,'Change to passive (present perfect): "Lawyers have filed the appeal."','The appeal filed by lawyers.','The appeal is filed by lawyers.','The appeal has been filed by lawyers.','The appeal was filed.','C'),
    mc(4,'Change to passive (past continuous): "They were examining the evidence."','The evidence was examining.','The evidence was being examined.','The evidence is being examined.','The evidence had been examined.','B'),
    mc(5,'Change to passive (present continuous): "The jury is deliberating."','already passive — intransitive verb (no object)','The jury is being deliberated.','Deliberating is the jury.','It is deliberating by the jury.','A'),
    mc(6,'Complete: "The law ___ (currently/review, present cont. passive) by a parliamentary committee."','currently reviewed','is currently being reviewed','currently is reviewed','has currently been reviewed','B'),
    mc(7,'Complete: "By the time the verdict was read, all evidence ___ (present, past perfect passive)."','presented','was presented','had been presented','is presented','C'),
    mc(8,'Complete: "The suspect ___ (question, have + done) by the detective."','had questioned','had been questioned','was having questioned','had questioning','B'),
    mc(9,'Which passive form is used for ongoing/continuous actions?','was/were + pp','have/has + been + pp','am/is/are + being + pp','had + been + pp','C'),
    mc(10,'Complete: "The reforms ___ (implement, past perfect passive) before the new government came to power."','were implemented','had been implemented','have been implemented','are implemented','B'),
    tf(11,'Passive voice is formed with be + past participle.','true'),
    tf(12,'"The evidence was being examine" is correct.','false'),
    tf(13,'"Have something done" is a passive-like structure meaning you arrange for others to act.','true'),
    fb(14,'The policy ___ (adopt, present perfect passive). New laws ___ (debate, present continuous passive).','has been adopted, are being debated'),
    fb(15,'She ___ (have) her contract ___ (review, have + done). The document ___ (sign, past simple passive) yesterday.','had, reviewed, was signed'),
  ]},
  '76d550a9-dfc3-4e3b-b81f-f16234171f38':{pass_threshold:70,questions:[ // Justice System — Vocabulary
    mc(1,'What is a "defendant"?','the judge','the lawyer for the prosecution','the person accused in a court case','the jury member','C'),
    mc(2,'What does "to acquit" mean?','to find someone guilty','to find someone not guilty','to sentence someone','to appeal a verdict','B'),
    mc(3,'What is "due process"?','a quick trial','the legal requirement that the state respects all legal rights owed to a person','a type of appeal','a sentencing guideline','B'),
    mc(4,'What does "to appeal" mean in law?','to accept a verdict','to challenge a court decision in a higher court','to represent a client','to give evidence','B'),
    mc(5,'What is "habeas corpus"?','a type of crime','a legal right preventing unlawful detention without trial','a court order','a type of evidence','B'),
    mc(6,'What does "burden of proof" mean?','the sentence imposed','the obligation to prove a claim or allegation','the cost of a trial','the length of a case','B'),
    mc(7,'What is a "plaintiff"?','the judge','the person who brings a case against another','the defendant\'s lawyer','the jury','B'),
    mc(8,'What is "perjury"?','stealing evidence','lying under oath in court','refusing to testify','tampering with evidence','B'),
    mc(9,'What does "statute" mean?','a court decision','a written law passed by a legislature','a legal precedent','a judicial opinion','B'),
    mc(10,'What is "precedent" in law?','a new law','a previous court decision that influences future cases','a legal principle','a type of verdict','B'),
    tf(11,'A "defendant" is the person accused in a court case.','true'),
    tf(12,'"To acquit" means to find someone guilty.','false'),
    tf(13,'"Perjury" involves lying under oath in court.','true'),
    fb(14,'___ (Habeas corpus) prevents unlawful detention. ___ (Perjury) is lying under oath.','Habeas corpus, Perjury'),
    fb(15,'The ___ (plaintiff) brought the case. The court ___ (acquit) the defendant due to lack of evidence.','plaintiff, acquitted'),
  ]},
  'df2d3cc7-cd86-4e78-8a1b-1c4e34e13628':{pass_threshold:70,questions:[ // Human Rights — Collocations
    mc(1,'Which is correct?','protect human rights','defend human rights','uphold human rights','all of the above','D'),
    mc(2,'Which is correct?','violate human rights','break human rights','both A and B','infringe human rights (all three are correct)','D'),
    mc(3,'Which is correct?','promote equality','advance equality','both A and B','make equality','C'),
    mc(4,'Which is correct?','fight for justice','struggle for justice','campaign for justice','all of the above','D'),
    mc(5,'Which is correct?','suffer discrimination','face discrimination','both A and B','get discrimination','C'),
    mc(6,'Which is correct with "rights"?','exercise your rights','use your rights','take your rights','both A and B (exercise is more formal)','D'),
    mc(7,'Which is correct?','grant asylum','give asylum','both A and B','make asylum','C'),
    mc(8,'Which is correct?','raise awareness','increase awareness','both A and B','make awareness','C'),
    mc(9,'Which is correct?','call for reform','demand reform','advocate reform (advocate FOR reform)','both A and B','D'),
    mc(10,'Which is correct?','tackle inequality','address inequality','both A and B','solve inequality (all three work)','D'),
    tf(11,'"Uphold human rights" is a correct collocation.','true'),
    tf(12,'"Make equality" is the standard collocation in English.','false'),
    tf(13,'"Raise awareness" and "increase awareness" are both correct collocations.','true'),
    fb(14,'NGOs ___ (fight) for justice and ___ (raise) awareness of human rights violations.','fight, raise'),
    fb(15,'The government ___ (grant) asylum to refugees. The court ___ (uphold) the defendant\'s rights.','granted, upheld'),
  ]},
  '285b1155-a03d-4868-90d5-f470079b1397':{pass_threshold:80,questions:[ // Module 5 Review
    mc(1,'Present Simple Passive: "Laws ___ by parliament."','enact','enacted','are enacted','have enacted','C'),
    mc(2,'Past Passive: "The suspect ___ by police."','arrested','was arrested','is arrested','has been arrested','B'),
    mc(3,'Present Continuous Passive: "The case ___ by detectives."','investigates','is being investigated','was investigated','has been investigated','B'),
    mc(4,'Present Perfect Passive: "The verdict ___."','delivered','was delivered','has been delivered','is delivered','C'),
    mc(5,'Past Perfect Passive: "The evidence ___ before the trial."','destroyed','had been destroyed','was destroyed','has been destroyed','B'),
    mc(6,'"Have something done": "She ___ her car ___ (service)."','has / serviced','had / servicing','has / service','make / serviced','A'),
    mc(7,'What does "acquit" mean?','find guilty','find not guilty','sentence someone','appeal','B'),
    mc(8,'What is "perjury"?','stealing evidence','lying under oath','refusing to testify','bribery','B'),
    mc(9,'What does "precedent" mean in law?','a new law','a previous case that influences future decisions','a legal principle','a verdict','B'),
    mc(10,'What is "burden of proof"?','the sentence','the obligation to prove a claim','the cost of a trial','the length of a case','B'),
    mc(11,'Correct collocation: "___ human rights"','make','do','uphold/protect','take','C'),
    mc(12,'Correct collocation: "___ awareness"','make','raise','do','create (all except make are possible; raise is most common)','B'),
    mc(13,'Past Continuous Passive: "The witness ___ when we arrived."','questioned','was being questioned','was questioned','has been questioned','B'),
    mc(14,'What does "plaintiff" mean?','the judge','the accused','the person who brings a case','a witness','C'),
    mc(15,'What is "due process"?','a quick trial','respect for all legal rights owed to a person','a type of appeal','a sentencing guideline','B'),
    tf(16,'Passive voice focuses on what was done, not who did it.','true'),
    tf(17,'"Get something done" is an informal alternative to "have something done".','true'),
    tf(18,'"To acquit" means to find someone guilty.','false'),
    fb(19,'The policy ___ (adopt, PP Passive). Laws ___ (debate, present continuous passive) in parliament.','has been adopted, are being debated'),
    fb(20,'She ___ (have) her legal documents ___ (certify). The suspect ___ (release, past perfect passive) early.','had, certified, had been released'),
  ]},

  // ═══ MODULE 6: Modal World ═══
  'f34a64d0-740b-42c5-a759-db5b43b753a8':{pass_threshold:70,questions:[ // Can/Could/Be Able To
    mc(1,'Which is used for present ability?','could','was able to','can','would be able to','C'),
    mc(2,'Which is used for past ability?','can','could / was able to','will be able to','am able to','B'),
    mc(3,'"Could" vs "was able to": which emphasises a specific achievement in the past?','could','was able to','can','had been able to','B'),
    mc(4,'Complete: "He ___ speak four languages by the age of 12."','can','could','is able to','was able to','D'),
    mc(5,'Complete: "She ___ complete the marathon despite her injury." (specific achievement)','could','can','was able to','is able to','C'),
    mc(6,'Future ability: "With enough practice, she ___ master this skill."','can','could','will be able to','is able to','C'),
    mc(7,'Complete: "They ___ (negative, could) solve the problem without outside help."','can\'t','couldn\'t','won\'t be able to','isn\'t able to','B'),
    mc(8,'Complete: "She ___ (formal, present) to attend the hearing this afternoon."','can','could','is able','is able to','D'),
    mc(9,'Complete: "He ___ (past, specific) pass the bar exam on his first attempt."','could','can','was able to','has been able to','C'),
    mc(10,'Which expresses general past ability (not specific)?','was able to (specific success)','could (general ability)','can (present)','will be able to (future)','B'),
    tf(11,'"Could" generally refers to past ability or possibility.','true'),
    tf(12,'"Was able to" and "could" always have identical meanings.','false'),
    tf(13,'"Will be able to" expresses future ability.','true'),
    fb(14,'She ___ (could/was able to, specific success) defend her thesis brilliantly. He ___ (can, present) code in Python.','was able to, can'),
    fb(15,'With more resources, they ___ (will be able to) expand. He ___ (could, general past) run 10km when he was younger.','will be able to, could'),
  ]},
  '9a0440b1-0f84-493a-ac0e-456793fd22b6':{pass_threshold:70,questions:[ // Must/Have To/Need To
    mc(1,'"Must" expresses:','external obligation','personal strong necessity or internal obligation','advice','possibility','B'),
    mc(2,'"Have to" expresses:','personal obligation','external obligation (rules, requirements)','advice','deduction','B'),
    mc(3,'Complete: "You ___ cite your sources — it\'s academic policy." (external rule)','must','should','have to','need to','C'),
    mc(4,'Complete: "I ___ finish this chapter tonight — I feel I simply must." (personal conviction)','have to','should','must','need to','C'),
    mc(5,'Negative: "You ___ reveal confidential information." (prohibition)','don\'t have to','needn\'t','mustn\'t','shouldn\'t','C'),
    mc(6,'Negative: "You ___ attend every lecture — just the core ones." (no obligation)','mustn\'t','don\'t have to','can\'t','shouldn\'t','B'),
    mc(7,'"Mustn\'t" vs "don\'t have to" — key difference:','no difference','mustn\'t = prohibition; don\'t have to = no obligation','both mean prohibition','both mean no obligation','B'),
    mc(8,'Complete: "She ___ submit the form by Friday — it\'s mandatory."','should','might','has to','would','C'),
    mc(9,'"Need to" is similar to:','must','have to (both correct)','could','might','B'),
    mc(10,'Complete: "He ___ (past obligation) work weekends when he was a junior associate."','must','has to','had to','needs to','C'),
    tf(11,'"Mustn\'t" means it is not necessary to do something.','false'),
    tf(12,'"Don\'t have to" means there is no obligation.','true'),
    tf(13,'"Had to" is the past form of both "must" and "have to" for obligation.','true'),
    fb(14,'Students ___ (have to) register before the deadline. You ___ (mustn\'t) plagiarise — it\'s prohibited.','have to, mustn\'t'),
    fb(15,'She ___ (need to) improve her methodology. He ___ (don\'t have to) attend the seminar — it\'s optional.','needs to, doesn\'t have to'),
  ]},
  '5d08d8fc-1f05-4df5-9ccb-b51ff85eb224':{pass_threshold:70,questions:[ // Should/Ought To
    mc(1,'"Should" is used for:','strong obligation','advice and moral obligation','ability','past certainty','B'),
    mc(2,'"Ought to" compared to "should":','stronger','weaker','similar meaning but slightly more formal','completely different','C'),
    mc(3,'Complete: "She ___ proofread her work before submitting."','must','can','should/ought to','will','C'),
    mc(4,'Complete: "He ___ (negative) have shared the confidential data."','shouldn\'t','mustn\'t','can\'t','wouldn\'t','A'),
    mc(5,'Complete: "You ___ declare a conflict of interest, morally speaking."','must','have to','ought to','might','C'),
    mc(6,'"Should have + pp" expresses:','a past obligation that was met','a past recommendation that was not followed (criticism)','a future obligation','a present ability','B'),
    mc(7,'Complete: "She ___ prepared more thoroughly — her presentation suffered." (past criticism)','should have','ought','must have','would have','A'),
    mc(8,'Complete: "Researchers ___ maintain ethical standards at all times."','could','might','should/ought to','need','C'),
    mc(9,'"Ought not to" is:','wrong','the negative form of "ought to"','the past form','the same as "mustn\'t"','B'),
    mc(10,'Complete: "He ___ considered the counterargument more carefully." (criticism)','should have','must have','can have','would have','A'),
    tf(11,'"Should" and "ought to" are similar in meaning.','true'),
    tf(12,'"Should have done" expresses a past obligation that was fulfilled.','false'),
    tf(13,'"Ought to" is slightly more formal than "should".','true'),
    fb(14,'She ___ (should) review her methodology. He ___ (should have) acknowledged the limitations earlier.','should, should have'),
    fb(15,'They ___ (ought to) address the ethical concerns. The data ___ (should have) been collected more carefully.','ought to, should have been'),
  ]},
  '69e992c2-670b-43f9-a122-0e655b37367d':{pass_threshold:70,questions:[ // Possibility — May/Might/Could
    mc(1,'"May" expresses:','certainty','past ability','possibility (about 50%)','strong deduction','C'),
    mc(2,'"Might" compared to "may":','stronger possibility','same or slightly weaker possibility','certainty','impossibility','B'),
    mc(3,'Complete: "She ___ attend the seminar — it depends on her schedule."','will','must','may/might/could','should','C'),
    mc(4,'Complete: "There ___ be significant limitations to this methodology."','will','must','might/could/may','shall','C'),
    mc(5,'"Could" for possibility (not ability): "The results ___ indicate a correlation."','will','could/may/might','must','shall','B'),
    mc(6,'Complete: "He ___ have missed the submission deadline — I\'ll check."','must','may/might','will','should','B'),
    mc(7,'Complete: "The conference ___ be moved online due to the pandemic."','will','must','might/may/could','should','C'),
    mc(8,'"May" is also used for:','obligation','past habit','formal permission','deduction','C'),
    mc(9,'Complete: "This research ___ have wider implications than initially expected."','will','must','could/may/might','shall','C'),
    mc(10,'"Might have + pp" expresses:','a certain past action','a possible past action that may have occurred','a past obligation','a deduction about the past','B'),
    tf(11,'"May", "might", and "could" all express possibility.','true'),
    tf(12,'"Must" is used when we are unsure about something.','false'),
    tf(13,'"Might have gone" expresses a possible past action.','true'),
    fb(14,'She ___ (might) change her research focus. This ___ (could) significantly impact the findings.','might, could'),
    fb(15,'He ___ (may have) misread the data. The results ___ (might) not be generalisable.','may have, might'),
  ]},
  '83ba2726-e1f3-4d3f-822a-eba6a2282c2a':{pass_threshold:70,questions:[ // Deduction — Must/Can\'t/Might
    mc(1,'"Must" for deduction expresses:','weak possibility','strong certainty based on evidence','past certainty','advice','B'),
    mc(2,'"Can\'t" for deduction expresses:','certainty that something is true','strong certainty that something is impossible','possibility','permission','B'),
    mc(3,'Complete: "She ___ be exhausted — she\'s been working 18-hour days." (strong deduction)','might','must','can\'t','could','B'),
    mc(4,'Complete: "He ___ be the author — his writing style is completely different." (impossibility)','might not','mustn\'t','can\'t','shouldn\'t','C'),
    mc(5,'Complete: "They ___ have made an error — the calculations don\'t add up." (present deduction)','might','must','can\'t','would','B'),
    mc(6,'"Must have + pp" expresses:','a past obligation','a strong deduction about a completed past action','a past possibility','criticism','B'),
    mc(7,'Complete: "She ___ have submitted the wrong file — the name is completely different."','must','might','can\'t','should','A'),
    mc(8,'"Can\'t have + pp" expresses:','a strong past deduction of impossibility','a weak possibility','a past obligation','permission','A'),
    mc(9,'Complete: "He ___ have forgotten — he has an excellent memory." (impossibility)','might not','must not','can\'t','shouldn\'t','C'),
    mc(10,'Complete: "The results ___ be wrong — they\'re consistent with previous studies." (near certainty — positive)','might','can\'t','must','could','C'),
    tf(11,'"Must" for deduction shows strong certainty based on evidence.','true'),
    tf(12,'"Can\'t" for deduction means "it is not allowed".','false'),
    tf(13,'"Must have done" is used for deductions about past events.','true'),
    fb(14,'She ___ (must) be the lead researcher — she knows every detail. He ___ (can\'t) have read the paper — he just arrived.','must, can\'t'),
    fb(15,'They ___ (must have) worked all night on this. She ___ (can\'t have) made such a basic error.','must have, can\'t have'),
  ]},
  '5fef4532-649e-4955-adf8-f929c875580e':{pass_threshold:70,questions:[ // Should Have/Could Have
    mc(1,'"Should have + pp" expresses:','a past obligation met','a past action that was advisable but not done (criticism)','a future plan','a present possibility','B'),
    mc(2,'"Could have + pp" expresses:','a past obligation','a past possibility that was not realised','a deduction','a future ability','B'),
    mc(3,'Complete: "She ___ proofread the paper — it has many errors." (criticism)','should have proofread','could have proofread','must have proofread','would have proofread','A'),
    mc(4,'Complete: "He ___ applied for the scholarship — he met all the criteria." (missed opportunity)','should have applied','could have applied','must have applied','would have applied','B'),
    mc(5,'"Shouldn\'t have + pp" expresses:','something not done that should have been','something done that shouldn\'t have been','a future regret','a present obligation','B'),
    mc(6,'Complete: "She ___ shared those findings publicly before peer review." (criticism — she did it)','shouldn\'t have shared','should have shared','can\'t have shared','mustn\'t have shared','A'),
    mc(7,'Complete: "They ___ achieved better results with a larger sample size." (unrealised possibility)','should have','could have','must have','would have','B'),
    mc(8,'"Would have + pp" expresses:','a deduction','a past criticism','a hypothetical past action (usually in 3rd conditional)','a missed obligation','C'),
    mc(9,'Complete: "I ___ told her earlier — she deserved to know." (regret/criticism of self)','could have','should have','must have','would have','B'),
    mc(10,'Complete: "He ___ submitted the form earlier — he knew the deadline." (criticism)','should have','could have','must have','can have','A'),
    tf(11,'"Should have done" means the action was advisable but not done.','true'),
    tf(12,'"Could have done" means the action was done but it was wrong.','false'),
    tf(13,'"Shouldn\'t have done" means the action was done but it was a mistake.','true'),
    fb(14,'She ___ (should have) cited her sources. He ___ (could have) done more research.','should have, could have'),
    fb(15,'They ___ (shouldn\'t have) published prematurely. I ___ (should have) disclosed the conflict of interest.','shouldn\'t have, should have'),
  ]},
  '32e399d8-fbb4-4a26-a323-f904291093a2':{pass_threshold:70,questions:[ // Mixed Modals Review
    mc(1,'"Can" = ability, "must" = obligation, "might" = possibility. Which is the deduction modal?','can','should','must (for deduction)','might','C'),
    mc(2,'Complete: "She ___ (strong deduction) be the department head — everyone defers to her."','might','could','must','should','C'),
    mc(3,'Complete: "You ___ (obligation, external rule) obtain ethical approval before research."','should','might','have to','could','C'),
    mc(4,'Complete: "He ___ (past criticism) disclosed his methodology more clearly."','could have','should have','must have','would have','B'),
    mc(5,'Complete: "The results ___ (strong impossibility) be accurate — the methodology is flawed."','might not','must not','can\'t','shouldn\'t','C'),
    mc(6,'Complete: "With better planning, she ___ (past unrealised possibility) completed the project on time."','should have','could have','must have','would have','B'),
    mc(7,'Complete: "They ___ (future ability) expand the programme with additional funding."','can','could','will be able to','are able to','C'),
    mc(8,'Complete: "Researchers ___ (moral advice) maintain integrity throughout the study."','can','could','should/ought to','might','C'),
    mc(9,'Complete: "She ___ (permission, formal) request an extension if needed."','must','should','may','can (both C and D are correct, may is more formal)','C'),
    mc(10,'Complete: "He ___ (past specific ability/achievement) defend his thesis despite heavy criticism."','could','was able to','can','might have','B'),
    tf(11,'"Must" expresses both strong obligation and strong deduction.','true'),
    tf(12,'"Mustn\'t" and "don\'t have to" have the same meaning.','false'),
    tf(13,'"Should have done" and "could have done" both refer to past unrealised actions, but with different connotations.','true'),
    fb(14,'She ___ (must) be brilliant — she solved it in minutes. You ___ (shouldn\'t have) published without peer review.','must, shouldn\'t have'),
    fb(15,'He ___ (could have) applied but chose not to. They ___ (have to) submit by noon.','could have, have to'),
  ]},
  'b591cd84-68ad-4155-a4e6-cd5064e88e5a':{pass_threshold:80,questions:[ // Module 6 Review
    mc(1,'"Can" vs "could" vs "was able to": which emphasises a specific past achievement?','can','could','was able to','will be able to','C'),
    mc(2,'"Must" vs "have to": which is typically external obligation?','must','have to','should','ought to','B'),
    mc(3,'"Mustn\'t" vs "don\'t have to": "You ___ cite sources — it\'s mandatory." (prohibition)','don\'t have to','mustn\'t','needn\'t','couldn\'t','B'),
    mc(4,'"Should have + pp": "She ___ disclosed the conflict." (criticism — she didn\'t)','should have','could have','must have','would have','A'),
    mc(5,'Deduction: "He ___ be the author — the style is unmistakable." (strong)','might','could','must','should','C'),
    mc(6,'Impossibility deduction: "She ___ have submitted it — she was abroad."','might not','mustn\'t','can\'t','shouldn\'t','C'),
    mc(7,'"Could have + pp": "They ___ achieved more with better resources." (unrealised)','should have','could have','must have','would have','B'),
    mc(8,'"Might": "The conference ___ be postponed." (possibility)','will','must','might/may/could','should','C'),
    mc(9,'"Will be able to": "She ___ conduct fieldwork next year." (future ability)','can','could','will be able to','is able to','C'),
    mc(10,'"Ought to": "Researchers ___ maintain ethical standards." (moral advice)','can','could','ought to/should','must','C'),
    mc(11,'Past deduction: "She ___ worked all night — the report is perfect." (strong)','might have','could have','must have','should have','C'),
    mc(12,'"Shouldn\'t have + pp": "He ___ shared the data publicly." (it was wrong)','shouldn\'t have','should have','can\'t have','mustn\'t have','A'),
    mc(13,'Future ability: "With training, she ___ master this technique."','can','could','will be able to','is able to','C'),
    mc(14,'Advice: "You ___ proofread before submitting." (recommendation)','must','have to','should/ought to','might','C'),
    mc(15,'"May" for permission (formal): "___ I request an extension?"','Can','Should','May','Must','C'),
    tf(16,'"Don\'t have to" means prohibition.','false'),
    tf(17,'"Must have done" is used for strong deductions about past events.','true'),
    tf(18,'"Could have done" always implies a past mistake.','false'),
    fb(19,'She ___ (must) be exhausted. He ___ (shouldn\'t have) disclosed that data.','must, shouldn\'t have'),
    fb(20,'They ___ (could have) done more research. You ___ (have to) register before the deadline.','could have, have to'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'1466a50a-5085-4b5f-bca2-8a2c1d29bdfe',n:4,title:'Money & Shopping'},
    {id:'f5f0a63f-05ee-42c9-8ea1-7c1758a37c9e',n:5,title:'Law & Society'},
    {id:'b2ac0109-cb77-4935-a2be-f80fd13f48f2',n:6,title:'Modal World'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 B1 Intermediate — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 4–6 B1 Intermediate`)
}
main().catch(e=>{console.error(e);process.exit(1)})
