/**
 * B1 Intermediate — Modules 16–20 (Reading, Writing, Listening, Communication, Final Mile).
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-b1-mod16-20.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // MODULE 16: Reading Skills
  '6ba174d5-b2a7-4e09-be26-86c18d54d191':{pass_threshold:70,questions:[ // Skimming & Scanning
    mc(1,'Skimming is used to:','read every word carefully','get a general overview of a text quickly','find a specific fact','translate the text','B'),
    mc(2,'Scanning is used to:','understand the main idea','read for pleasure','find specific information quickly','read every word','C'),
    mc(3,'What do you focus on when skimming?','every single word','headings, topic sentences, and key phrases','footnotes only','the conclusion only','B'),
    mc(4,'What do you focus on when scanning?','the general message','specific words, numbers, or names','paragraph structure','style and tone','B'),
    mc(5,'When would you skim a text?','to find a specific date','to proofread carefully','to decide if a text is relevant to read in full','to memorise content','C'),
    mc(6,'In IELTS, which task requires scanning?','matching headings','finding the main idea','True/False/Not Given','finding where specific information appears','D'),
    mc(7,'What is a "signpost word" in a text?','a direction word (turn left)','a word that signals the structure or direction of the argument (however, therefore)','a vocabulary item','a technical term','B'),
    mc(8,'What is "active reading"?','reading passively','engaging with the text by annotating, questioning, and predicting','reading very fast','reading without a purpose','B'),
    mc(9,'What is "annotating" a text?','copying it out','highlighting or making notes to engage with the text','reading aloud','memorising passages','B'),
    mc(10,'What does "reading for gist" mean?','reading word by word','understanding the overall meaning without details','reading for specific information','reading critically','B'),
    tf(11,'Skimming gives you a general overview of a text.','true'),
    tf(12,'Scanning involves reading every word carefully.','false'),
    tf(13,'"Active reading" involves engaging with the text through annotation and questioning.','true'),
    fb(14,'___ (Skimming) = general idea. ___ (Scanning) = specific information.','Skimming, Scanning'),
    fb(15,'"Reading for ___ (gist)" means getting the overall meaning. "___ (Signpost)" words guide you through arguments.','gist, Signpost'),
  ]},
  'a0c022f7-767d-4087-a854-6dfde723964d':{pass_threshold:70,questions:[ // Main Idea — Topic Sentences
    mc(1,'A topic sentence usually appears:','at the end of a paragraph','anywhere in a paragraph','at the beginning of a paragraph','in the conclusion only','C'),
    mc(2,'What does a topic sentence do?','give a specific example','introduce the main idea of a paragraph','conclude the essay','list all facts','B'),
    mc(3,'Which is a well-written topic sentence?','The weather is bad.','Many people live in cities.','Urbanisation presents significant challenges for sustainable development.','Cities are growing.','C'),
    mc(4,'What is a "supporting sentence"?','the topic sentence','a sentence providing evidence or detail for the topic sentence','the concluding sentence','any sentence in a paragraph','B'),
    mc(5,'A concluding sentence:','introduces a new idea','restates the main idea or links to the next paragraph','gives a new example','always starts with "First"','B'),
    mc(6,'What is "coherence" in paragraph writing?','using many long sentences','logically connected ideas with smooth transitions','diverse vocabulary','many quotations','B'),
    mc(7,'What is "cohesion" in writing?','the unity of ideas','the use of linguistic devices (pronouns, conjunctions) to connect ideas','paragraph length','vocabulary range','B'),
    mc(8,'What is "paragraph unity"?','all sentences being long','all sentences relating to one main idea','having many examples','using varied structures','B'),
    mc(9,'What does "transition" mean between paragraphs?','starting a new topic abruptly','smooth logical connection from one paragraph to the next','a type of conclusion','a type of introduction','B'),
    mc(10,'Which is the best topic sentence for a paragraph about AI in education?','AI stands for Artificial Intelligence.','Many students use computers.','Artificial intelligence has the potential to transform personalised learning in higher education.','Technology is changing.','C'),
    tf(11,'A topic sentence states the main idea of a paragraph.','true'),
    tf(12,'All sentences in a paragraph should support the topic sentence (paragraph unity).','true'),
    tf(13,'A concluding sentence can introduce a brand-new idea not related to the paragraph.','false'),
    fb(14,'A ___ (topic) sentence introduces the main idea. ___ (Supporting) sentences provide evidence.','topic, Supporting'),
    fb(15,'Good paragraphs have ___ (coherence) — logical connection — and ___ (cohesion) — linguistic connectors.','coherence, cohesion'),
  ]},
  'd7729396-ee58-4839-b4f0-1e37b6539259':{pass_threshold:70,questions:[ // Reading for Detail — Inference
    mc(1,'What is "inference" in reading?','reading every word','drawing conclusions not directly stated','summarising','translating','B'),
    mc(2,'What does "reading between the lines" mean?','reading footnotes','understanding implied meaning','reading slowly','reading headers','B'),
    mc(3,'"The author implies that..." means:','the author states directly','the author suggests without saying explicitly','the author proves','the author contradicts','B'),
    mc(4,'What does "the tone of a text" refer to?','the font size','the author\'s attitude or feeling expressed through word choice','the length of sentences','the bibliography','B'),
    mc(5,'What signal word indicates contrast?','Furthermore','Therefore','However/Although','In addition','C'),
    mc(6,'What signal word indicates result?','However','Although','Furthermore','Therefore/Consequently','D'),
    mc(7,'What signal word indicates addition?','However','Although','Furthermore/Moreover/In addition','Therefore','C'),
    mc(8,'What does "hedging language" signal?','certainty','possibility or caution (may, might, appears to)','impossibility','a command','B'),
    mc(9,'What is "bias" in a text?','neutral reporting','a preference or prejudice that influences the author\'s perspective','objective analysis','factual reporting','B'),
    mc(10,'What does "corroborate" mean?','contradict','confirm or support with additional evidence','disprove','question','B'),
    tf(11,'Inference involves understanding what is implied but not directly stated.','true'),
    tf(12,'"However" signals addition of information.','false'),
    tf(13,'"May" and "might" are examples of hedging language.','true'),
    fb(14,'"___ (Furthermore)" adds information. "___ (Nevertheless)" shows contrast/concession.','Furthermore, Nevertheless'),
    fb(15,'The author ___ (imply) that the results are unreliable. This can be ___ (infer) from the hedging language used.','implies, inferred'),
  ]},
  '06fd9ba5-a9bf-4675-843c-f955843addc5':{pass_threshold:70,questions:[ // Understanding Articles — News & Magazines
    mc(1,'What is the "inverted pyramid" structure in journalism?','most important information at the bottom','most important information at the top, details below','chronological order','alphabetical order','B'),
    mc(2,'What is "the lead" (lede) in a news article?','the headline','the opening paragraph summarising the key facts','the conclusion','a subheading','B'),
    mc(3,'What does "to attribute" information mean?','to ignore the source','to state the source of information','to invent information','to translate','B'),
    mc(4,'What is an "editorial"?','a news report','an opinion piece written by the editor or editorial board','a letter to the editor','an advertisement','B'),
    mc(5,'What does "to sensationalise" mean?','to report accurately','to exaggerate or dramatise information to make it more shocking','to minimise a story','to correct a story','B'),
    mc(6,'What is a "byline"?','a subtitle','a brief description of an image','the name of the journalist who wrote the article','a pull quote','C'),
    mc(7,'What is a "pull quote"?','a source quote','a highlighted quote from the article used as a graphic design element','a translated quote','an anonymous quote','B'),
    mc(8,'What does "on the record" mean?','information shared anonymously','information that can be quoted and attributed to the source','off the record information','background information','B'),
    mc(9,'What is "fact-checking"?','writing an opinion piece','verifying the accuracy of claims in an article','editing for style','translating articles','B'),
    mc(10,'What does "a tabloid" typically refer to?','a serious broadsheet paper','a sensationalist newspaper focusing on celebrities and scandal','an academic journal','an online magazine','B'),
    tf(11,'The "inverted pyramid" puts the most important information at the top.','true'),
    tf(12,'A "byline" is a subtitle under the main headline.','false'),
    tf(13,'"Fact-checking" verifies the accuracy of claims.','true'),
    fb(14,'The "___ (lead/lede)" summarises the key facts. A "___ (byline)" names the author.','lead / lede, byline'),
    fb(15,'"___ (Fact-checking)" verifies accuracy. "___ (Sensationalise)" means to exaggerate for impact.','Fact-checking, Sensationalise / To sensationalise'),
  ]},
  '7703e038-d593-4124-bd48-3a2460789362':{pass_threshold:70,questions:[ // Academic Texts — University Level
    mc(1,'What is an "abstract" in an academic paper?','a full paper','a brief summary of the paper\'s aim, methods, results, and conclusions','an introduction','a bibliography','B'),
    mc(2,'What is a "literature review"?','a review of novels','a critical survey of existing research relevant to a topic','the conclusion of a paper','a list of references','B'),
    mc(3,'What is a "thesis statement"?','a general opening sentence','the central argument or claim of an essay or research paper','a literature review summary','a research methodology','B'),
    mc(4,'What is "peer review"?','student review of teachers','experts in the same field evaluating academic work before publication','self-assessment','editorial review','B'),
    mc(5,'What does "methodology" refer to in research?','the results section','the approach and methods used to collect and analyse data','the introduction','the conclusion','B'),
    mc(6,'What is a "citation"?','a personal opinion','a reference to a source used in a text','a type of quotation only','a bibliography','B'),
    mc(7,'What is "plagiarism"?','original research','copying someone else\'s work without proper attribution','citing too many sources','writing a literature review','B'),
    mc(8,'What does "empirical" mean?','theoretical','based on observation or experimental data rather than theory','historical','anecdotal','B'),
    mc(9,'What is a "hypothesis"?','a proven fact','a tentative explanation or prediction to be tested','a conclusion','a theory','B'),
    mc(10,'What does "quantitative research" mean?','research using interviews and observations','research using numerical data and statistical analysis','research based on personal experience','research using historical texts','B'),
    tf(11,'An "abstract" is a brief summary of an academic paper.','true'),
    tf(12,'A "hypothesis" is a proven, accepted fact.','false'),
    tf(13,'"Empirical" research is based on observation and experimental data.','true'),
    fb(14,'The ___ (literature review) surveys existing research. The ___ (hypothesis) is tested through experiments.','literature review, hypothesis'),
    fb(15,'___ (Plagiarism) is using others\' work without attribution. ___ (Peer review) validates academic quality.','Plagiarism, Peer review'),
  ]},
  '1b18e101-8c47-497f-a73b-12c6a1dbde66':{pass_threshold:70,questions:[ // Opinion Pieces — Critical Reading
    mc(1,'What distinguishes an opinion piece from a news article?','it is shorter','it expresses the author\'s personal views rather than objective reporting','it has no evidence','it is always published online','B'),
    mc(2,'What is a "counterargument"?','an argument that supports the main claim','an argument that challenges or opposes the main claim','a conclusion','an example','B'),
    mc(3,'What is "rhetorical question" in opinion writing?','a factual question','a question asked for effect, not expecting a literal answer','a survey question','an interview question','B'),
    mc(4,'What does "to refute" mean?','to agree with','to prove an argument is wrong or false','to summarise','to cite a source','B'),
    mc(5,'What is "appeal to authority"?','ignoring experts','using an expert\'s opinion to support a claim','a logical fallacy only','a type of evidence','B'),
    mc(6,'What is "straw man" argument?','a valid argument','misrepresenting an opponent\'s argument to make it easier to attack','a type of evidence','a conclusion','B'),
    mc(7,'What is "ad hominem" fallacy?','attacking an argument logically','attacking the person making the argument rather than the argument itself','a valid form of criticism','a rhetorical technique','B'),
    mc(8,'What does "the burden of proof" mean?','the sentence in court','the obligation of the person making a claim to provide evidence','a legal penalty','a logical consequence','B'),
    mc(9,'What is "cherry-picking" in argumentation?','selecting the best argument fairly','selectively using only evidence that supports your position while ignoring contradictory evidence','a type of fallacy about food','giving equal weight to all evidence','B'),
    mc(10,'What does "nuanced" mean in an argument?','simple and absolute','acknowledging complexity and avoiding oversimplification','biased','one-sided','B'),
    tf(11,'An opinion piece expresses a personal viewpoint.','true'),
    tf(12,'A "straw man" argument accurately represents the opposing view.','false'),
    tf(13,'"Ad hominem" attacks the person rather than the argument.','true'),
    fb(14,'___ (Cherry-picking) uses only favourable evidence. ___ (Ad hominem) attacks the person, not the argument.','Cherry-picking, Ad hominem'),
    fb(15,'A well-___ (nuanced) argument acknowledges complexity. The author must ___ (refute) the counterargument.','nuanced, refute'),
  ]},
  'de9cd349-82fc-4a22-924b-9ef469e63176':{pass_threshold:70,questions:[ // IELTS Reading — Exam Strategies
    mc(1,'In IELTS True/False/Not Given, "Not Given" means:','the statement is false','the statement contradicts the text','the information is not mentioned in the text','the statement is true but paraphrased','C'),
    mc(2,'In IELTS matching headings, you should:','read every word first','skim paragraphs and match main ideas to headings','only read first sentences','match based on keywords alone','B'),
    mc(3,'In IELTS sentence completion, answers must:','always be numbers','be no more than the specified number of words','always include a date','be full sentences','B'),
    mc(4,'What is "paraphrase" in IELTS context?','copying exact words from the text','expressing the same idea using different words','a type of question','a reading strategy','B'),
    mc(5,'What does "the question uses a synonym" mean in IELTS?','the answer is not in the text','the text uses a different word with the same meaning as the question','the question is wrong','the text contradicts','B'),
    mc(6,'How should you approach "matching information" questions?','skim all paragraphs first then read for detail','read every paragraph word by word','only read the last paragraph','ignore the questions','A'),
    mc(7,'What is the danger of "over-relying on keywords" in IELTS?','no danger','missing paraphrased answers (same meaning, different words)','making answers too long','running out of time','B'),
    mc(8,'In IELTS Reading, can you write more than the word limit?','Yes, always','No — exceeding the limit results in the answer being marked wrong','Yes, for long answers','Only in Academic','B'),
    mc(9,'What does "Yes/No/Not Given" differ from "True/False/Not Given"?','nothing','Yes/No/Not Given refers to writer\'s opinions/claims; T/F/NG refers to factual information','Yes/No/NG is harder','T/F/NG is for General IELTS only','B'),
    mc(10,'What is the best strategy for a difficult IELTS reading passage?','give up','move on and come back if time allows','re-read the whole passage','only answer the first question','B'),
    tf(11,'"Not Given" in IELTS means the information is not mentioned, not that it is false.','true'),
    tf(12,'In IELTS sentence completion, you must always give exactly one word.','false'),
    tf(13,'IELTS answers often use paraphrase (different words, same meaning) rather than exact text.','true'),
    fb(14,'"___ (Not Given)" = not mentioned. "___ (Paraphrase)" = same idea, different words.','Not Given, Paraphrase'),
    fb(15,'In "matching headings", ___ (skim) paragraphs. Answers may use ___ (synonyms) instead of exact words.','skim, synonyms'),
  ]},
  'ae42cd53-bd59-47e2-922d-2a424eed2c6e':{pass_threshold:80,questions:[ // Module 16 Review
    mc(1,'Skimming is used for:','finding specific facts','general overview of a text','reading every word','translating','B'),
    mc(2,'Scanning is used for:','understanding main idea','finding specific information quickly','reading for pleasure','writing summaries','B'),
    mc(3,'A topic sentence usually appears:','at the end','in the middle','at the beginning of a paragraph','in the conclusion','C'),
    mc(4,'Good paragraphs have:','only topic sentences','coherence and cohesion','many examples only','varied sentence length only','B'),
    mc(5,'Inference means:','reading every word','understanding what is implied','summarising','translating','B'),
    mc(6,'"However" signals:','addition','result','contrast','reason','C'),
    mc(7,'The "inverted pyramid" in journalism puts:','least important info at the top','most important info at the top','info in alphabetical order','info chronologically','B'),
    mc(8,'A "byline" is:','a subtitle','the journalist\'s name','a pull quote','an editorial note','B'),
    mc(9,'An "abstract" in academic writing is:','a full paper','a brief summary of aim, methods, results, conclusions','an introduction','a bibliography','B'),
    mc(10,'A "hypothesis" is:','a proven fact','a tentative explanation to be tested','a conclusion','a theory','B'),
    mc(11,'"Straw man" argument means:','a valid argument','misrepresenting an opposing view to attack it more easily','factual evidence','a conclusion','B'),
    mc(12,'"Ad hominem" fallacy:','attacks the argument logically','attacks the person not the argument','provides evidence','summarises','B'),
    mc(13,'IELTS "Not Given" means:','the statement is false','contradicts text','not mentioned in the text','true but paraphrased','C'),
    mc(14,'"Paraphrase" in IELTS means:','copying text exactly','same idea, different words','a type of question','a strategy','B'),
    mc(15,'"Hedging language" (may, might, appears) signals:','certainty','possibility/caution','impossibility','a command','B'),
    tf(16,'Active reading involves annotating and questioning the text.','true'),
    tf(17,'In IELTS sentence completion, you can exceed the word limit.','false'),
    tf(18,'"Cherry-picking" uses only favourable evidence while ignoring contradictory data.','true'),
    fb(19,'___ (Skimming) = general idea. ___ (Inference) = understanding implied meaning.','Skimming, Inference'),
    fb(20,'The ___ (hypothesis) is tested. ___ (Peer review) validates academic quality.','hypothesis, Peer review'),
  ]},

  // MODULE 17: Writing Skills
  '0223e526-7f15-46c6-acf2-db15395067a7':{pass_threshold:70,questions:[ // Paragraph Structure
    mc(1,'A well-structured paragraph has:','only a topic sentence','topic sentence + supporting sentences + concluding sentence','as many ideas as possible','only examples','B'),
    mc(2,'What is "paragraph unity"?','all sentences being short','all sentences relating to one main idea','using many connectors','having varied sentence length','B'),
    mc(3,'What is the function of a "concluding sentence"?','introduce a new idea','give a new example','restate or summarise the main idea or link to the next paragraph','start a new topic','C'),
    mc(4,'"Furthermore" is used to:','contrast','show result','add a point','give reason','C'),
    mc(5,'"However" is used to:','add information','show result','contrast','give example','C'),
    mc(6,'"Therefore" is used to:','contrast','add information','show result/conclusion','give example','C'),
    mc(7,'What is a "concluding sentence" in a body paragraph?','the topic sentence repeated word for word','a sentence that signals the end of the point and links to the next','always a long sentence','always a short sentence','B'),
    mc(8,'What is "over-generalization" in academic writing?','making precise claims','making a claim that is too broad without sufficient evidence','using too many citations','hedging appropriately','B'),
    mc(9,'In a paragraph about climate policy, the topic sentence should:','give a detailed example','state the main argument about climate policy that the paragraph will develop','list all facts','begin with "In conclusion"','B'),
    mc(10,'What does "substantiate a claim" mean?','make an unsupported assertion','provide evidence to support a claim','reject a claim','repeat a claim','B'),
    tf(11,'A paragraph should present one unified main idea.','true'),
    tf(12,'"Therefore" shows contrast.','false'),
    tf(13,'Supporting sentences provide evidence, examples, or elaboration for the topic sentence.','true'),
    fb(14,'A ___ (topic) sentence introduces the idea. ___ (Furthermore) adds another point. ___ (However) shows contrast.','topic, Furthermore, However'),
    fb(15,'___ (Therefore) signals a result. A ___ (concluding) sentence ends the paragraph.','Therefore, concluding'),
  ]},
  '7a249cf3-aec5-4555-8f4e-9b1611dd7a48':{pass_threshold:70,questions:[ // Linking Words
    mc(1,'Which connector introduces an example?','However','Furthermore','For instance / For example','Therefore','C'),
    mc(2,'Which connector shows concession?','Furthermore','Although / Even though','Therefore','In addition','B'),
    mc(3,'Which introduces a condition?','However','Therefore','If / Unless / Provided that','Furthermore','C'),
    mc(4,'Which introduces an alternative?','Furthermore','Therefore','Alternatively / On the other hand','In addition','C'),
    mc(5,'Which summarises?','However','Furthermore','In conclusion / To summarise / In summary','Therefore','C'),
    mc(6,'Complete: "___ the data was limited, the findings were significant." (concession)','Therefore','Furthermore','Although / Even though','In conclusion','C'),
    mc(7,'Complete: "The results were positive. ___, further research is needed." (contrast)','Furthermore','Therefore','Although','Nevertheless / However','D'),
    mc(8,'Complete: "She submitted the data. ___, she prepared the presentation." (addition, same time)','However','Although','Meanwhile / In addition','Therefore','C'),
    mc(9,'Complete: "The budget was cut. ___, the project continued." (contrast)','Therefore','Furthermore','Consequently','Nevertheless','D'),
    mc(10,'Complete: "The hypothesis was supported. ___, the team published." (result)','However','Although','Consequently / Therefore','Furthermore','C'),
    tf(11,'"Although" introduces a clause of concession.','true'),
    tf(12,'"Therefore" introduces contrast.','false'),
    tf(13,'"Alternatively" presents another option.','true'),
    fb(14,'___ (Furthermore), the data supports this view. ___ (However), there are limitations.','Furthermore, However'),
    fb(15,'___ (Although) the sample was small, results were significant. ___ (Therefore), we recommend further study.','Although, Therefore'),
  ]},
  '490b8a85-bd83-443e-a5aa-348462cb8b49':{pass_threshold:70,questions:[ // Describing Data — Charts & Graphs
    mc(1,'Which phrase describes a sharp increase?','remained stable','declined gradually','rose dramatically / surged','fluctuated','C'),
    mc(2,'Which phrase describes a small decrease?','rose sharply','dropped significantly','declined slightly / fell marginally','remained constant','C'),
    mc(3,'Complete: "Sales ___ (rise) by 25% in Q2."','fell','rose / increased','levelled','fluctuated','B'),
    mc(4,'Complete: "The figures ___ at approximately 500 over three years." (no change)','rose','fell','levelled off / remained stable','fluctuated','C'),
    mc(5,'What does "peaked at" mean?','reached the lowest point','remained constant','reached the highest point','started to decline','C'),
    mc(6,'What does "trough" mean?','the highest point','a constant period','the lowest point','a sharp increase','C'),
    mc(7,'Complete: "Exports ___ to a record high." (sharp increase)','fell','soared / rose sharply','levelled','declined','B'),
    mc(8,'Complete: "There was a ___ (gradual) increase over the decade."','sudden','gradual / steady','dramatic','significant','B'),
    mc(9,'What does "fluctuate" mean?','remain stable','rise steadily','go up and down irregularly','decline sharply','C'),
    mc(10,'Complete: "The data shows a ___ (significant) upward trend."','slight','insignificant','significant / notable','downward','C'),
    tf(11,'"Peaked at" means reaching the highest point.','true'),
    tf(12,'"Levelled off" means the value increased rapidly.','false'),
    tf(13,'"Fluctuate" means to rise and fall irregularly.','true'),
    fb(14,'Sales ___ (rise, sharp) in Q1. They ___ (fall, gradual) in Q2.','rose sharply, fell gradually'),
    fb(15,'The graph ___ (show) a ___ (steady) increase. The value ___ (peak) at $5 million.','shows, steady, peaked'),
  ]},
  'a4718efe-e3b5-4f57-92be-e8f3094007e5':{pass_threshold:70,questions:[ // Informal Letters — Structure & Style
    mc(1,'What is the typical opening of an informal letter?','Dear Sir/Madam,','Dear Mr Johnson,','Hi/Dear [first name],','To Whom It May Concern,','C'),
    mc(2,'Which closing is appropriate for an informal letter?','Yours sincerely,','Yours faithfully,','Best wishes / Love / Take care,','Yours truly,','C'),
    mc(3,'Which feature is acceptable in informal letters?','passive voice only','contractions and colloquial language','formal vocabulary only','no personal pronouns','B'),
    mc(4,'What is the purpose of the opening paragraph in an informal letter?','state a formal complaint','re-establish the relationship and state the purpose of writing','provide statistical data','begin with a thesis statement','B'),
    mc(5,'Complete: "It\'s been ages since we last ___ (catch up) — I hope you\'re doing well!"','caught up','catch up','catching up','have caught up','A'),
    mc(6,'What should an informal letter NOT include?','casual language','personal opinions','emotional content','formal academic vocabulary and passive constructions throughout','D'),
    mc(7,'What is "anecdote" in a letter?','a formal argument','a short personal story used to illustrate a point','a statistical fact','a formal request','B'),
    mc(8,'Complete: "I\'m writing to ___ you to my graduation party." (invite)','invite','order','request','tell','A'),
    mc(9,'What tone should an informal letter have?','distant and impersonal','academic and objective','warm, friendly, and conversational','legal and formal','C'),
    mc(10,'Which phrase is appropriate to close an informal letter?','I await your prompt response.','Looking forward to hearing from you!','Yours faithfully,','I am at your disposal.','B'),
    tf(11,'Contractions are acceptable in informal letters.','true'),
    tf(12,'"Yours faithfully" is the appropriate closing for an informal letter.','false'),
    tf(13,'An anecdote in a letter is a short personal story.','true'),
    fb(14,'___ (Hi) Sarah! It\'s great to hear from you. I\'m writing to ___ (invite) you to my party.','Hi, invite'),
    fb(15,'___ (Looking forward) to hearing from you soon. ___ (Best wishes), Emma.','Looking forward, Best wishes'),
  ]},
  '975781d5-5491-4a52-8240-8faa5b252db9':{pass_threshold:70,questions:[ // Formal Letters — Business Writing
    mc(1,'What is the appropriate opening when you know the name?','Dear Sir/Madam,','Hey John,','Dear Mr Johnson,','Hi there,','C'),
    mc(2,'What is the appropriate opening when you do NOT know the name?','Dear John,','Hey,','Dear Sir/Madam,','To the person in charge,','C'),
    mc(3,'Complete: "I am writing ___ (purpose) to enquire about the vacancy."','to','for','by','about','A'),
    mc(4,'Which phrase makes a polite formal request?','Send me the form.','Could you please send me the application form?','I want the form.','Give me the form.','B'),
    mc(5,'Complete: "I look forward to ___ from you." (formal closing phrase)','hear','hearing','heard','to hear','B'),
    mc(6,'"Yours sincerely" is used when:','you don\'t know the recipient\'s name','you know the recipient\'s name','always','never','B'),
    mc(7,'"Yours faithfully" is used when:','you know the recipient','you don\'t know the recipient (Dear Sir/Madam)','always','never','B'),
    mc(8,'What is "the enclosure notation" in a letter?','the letterhead','"Enc:" or "Encl:" to indicate documents attached to the letter','the return address','the date','B'),
    mc(9,'Which phrase formally apologises?','Sorry!','I apologise for the inconvenience this may cause.','Oops.','My bad.','B'),
    mc(10,'What does "I would be grateful if you could" do?','make a demand','make a polite formal request','refuse a request','accept a request','B'),
    tf(11,'"Yours sincerely" follows when you know the recipient\'s name.','true'),
    tf(12,'"Yours faithfully" follows when you know the recipient\'s name.','false'),
    tf(13,'"I look forward to hearing from you" is a standard formal letter closing.','true'),
    fb(14,'___ (Dear) Mr Kim, I am writing ___ (to) request further information.','Dear, to'),
    fb(15,'___ (Yours sincerely), [name]. I look forward to ___ (hearing) from you.','Yours sincerely, hearing'),
  ]},
  '73edf6ea-41d0-4687-8464-4afa1474f959':{pass_threshold:70,questions:[ // Opinion Essays — Argument & Counter-argument
    mc(1,'What is the structure of a basic opinion essay?','introduction + one body paragraph + conclusion','introduction + 2-3 body paragraphs + conclusion','just body paragraphs','just an introduction and conclusion','B'),
    mc(2,'What should an introduction contain?','all main arguments in detail','background context + thesis statement','the conclusion + examples','only facts','B'),
    mc(3,'What is a "thesis statement"?','a general opening sentence','the central argument of the essay','a literature review','a bibliography item','B'),
    mc(4,'What is a "counter-argument"?','an argument that supports your view','an argument that opposes your view (which you then address)','a conclusion','an introduction','B'),
    mc(5,'Why should you include a counter-argument?','to weaken your own argument','to show you understand multiple perspectives and can refute opposing views','to add more paragraphs','to confuse the reader','B'),
    mc(6,'What does it mean to "refute" a counter-argument?','to agree with it fully','to prove it is wrong or less convincing than your view','to ignore it','to repeat it','B'),
    mc(7,'What phrase can introduce a counter-argument?','Furthermore','In addition','Admittedly / It could be argued that / Some claim that','Therefore','C'),
    mc(8,'What phrase can then refute a counter-argument?','Furthermore / Moreover','However / Nevertheless / Despite this','In conclusion','For instance','B'),
    mc(9,'What should a conclusion contain?','a new argument','a summary of main points and a restated thesis (no new information)','only examples','a counter-argument','B'),
    mc(10,'What is "hedging" in academic opinion essays?','being definitive and certain','expressing claims cautiously (may, might, could, appears to)','avoiding opinions','using passive only','B'),
    tf(11,'A counter-argument presents an opposing view which you then address.','true'),
    tf(12,'A conclusion should introduce brand-new arguments.','false'),
    tf(13,'"Admittedly" is used to acknowledge a counter-argument before refuting it.','true'),
    fb(14,'___ (Admittedly), there are arguments against this view. ___ (Nevertheless), the evidence suggests the opposite.','Admittedly, Nevertheless'),
    fb(15,'The ___ (thesis statement) states the essay\'s main argument. ___ (Hedging) language avoids overstatement.','thesis statement, Hedging'),
  ]},
  '52daddfe-f901-4c50-85d5-6863493bc96d':{pass_threshold:70,questions:[ // IELTS Writing — Exam Strategies
    mc(1,'IELTS Writing Task 1 (Academic) requires:','an essay','a graph/chart description','a letter','a story','B'),
    mc(2,'IELTS Writing Task 2 requires:','a graph description','a letter','an essay','a report','C'),
    mc(3,'What is the minimum word count for IELTS Task 2?','100 words','150 words','250 words','300 words','C'),
    mc(4,'What is the minimum word count for IELTS Task 1?','100 words','150 words','200 words','250 words','B'),
    mc(5,'What is "Task Achievement" in IELTS?','vocabulary range','how well you address all parts of the task','grammar accuracy','coherence','B'),
    mc(6,'What is "Coherence and Cohesion" in IELTS?','vocabulary range','how well ideas are organised and connected','grammar accuracy','task fulfilment','B'),
    mc(7,'What is "Lexical Resource" in IELTS?','grammar range','paragraph structure','vocabulary range and accuracy','task achievement','C'),
    mc(8,'What is "Grammatical Range and Accuracy" in IELTS?','vocabulary range','paragraph structure','the variety and accuracy of grammatical structures','task fulfilment','C'),
    mc(9,'What is the recommended structure for IELTS Task 2?','just write continuously','Introduction + 2 body paragraphs + Conclusion (minimum)','Only a conclusion','Write 1 very long paragraph','B'),
    mc(10,'In IELTS Task 1 (Academic), you should:','give your personal opinion','objectively describe the key features and trends','write an argument','compare your experience','B'),
    tf(11,'IELTS Task 2 requires at least 250 words.','true'),
    tf(12,'"Lexical Resource" in IELTS refers to grammar accuracy.','false'),
    tf(13,'IELTS Task 1 Academic requires an objective description of data.','true'),
    fb(14,'IELTS Task 2 needs ___ (250+) words. "___ (Task Achievement)" measures how well you address the question.','250, Task Achievement'),
    fb(15,'"___ (Coherence and Cohesion)" measures organisation. "___ (Lexical Resource)" measures vocabulary.','Coherence and Cohesion, Lexical Resource'),
  ]},
  '4d97a6f5-02c8-4a16-8bf2-c109b0f6433a':{pass_threshold:80,questions:[ // Module 17 Review
    mc(1,'A paragraph should:','present many ideas','present one main idea with supporting evidence','only have examples','be as long as possible','B'),
    mc(2,'"Furthermore" is used to:','contrast','show result','add a point','give reason','C'),
    mc(3,'"Although" introduces:','addition','result','contrast/concession','a condition','C'),
    mc(4,'In chart description, "peaked at" means:','lowest point','constant value','highest point','started declining','C'),
    mc(5,'What does "fluctuate" mean?','remain stable','rise steadily','go up and down irregularly','decline sharply','C'),
    mc(6,'Informal letter opening:','Dear Sir/Madam,','Yours faithfully,','Hi/Dear [first name],','To Whom It May Concern,','C'),
    mc(7,'Formal letter closing (when you know the name):','Yours faithfully,','Love,','Take care,','Yours sincerely,','D'),
    mc(8,'IELTS Task 2 minimum words:','100','150','250','300','C'),
    mc(9,'IELTS "Task Achievement" measures:','vocabulary','grammar','how well you address all parts of the task','paragraph length','C'),
    mc(10,'A thesis statement:','is a general opening','the central argument of the essay','a bibliography item','the conclusion','B'),
    mc(11,'A counter-argument:','supports your view','opposes your view (which you then refute)','is the conclusion','is the introduction','B'),
    mc(12,'"Admittedly" introduces:','your main argument','a counter-argument you acknowledge','a conclusion','an example','B'),
    mc(13,'What does "substantiate a claim" mean?','make unsupported assertion','provide evidence for it','reject it','repeat it','B'),
    mc(14,'"Hedging" in academic writing:','makes definitive claims','expresses caution (may, might, appears)','avoids all opinions','uses only passive','B'),
    mc(15,'IELTS Task 1 Academic requires:','a personal opinion essay','objective description of data','a letter','a story','B'),
    tf(16,'"Yours sincerely" is used when you know the recipient\'s name.','true'),
    tf(17,'"Levelled off" means the value increased rapidly.','false'),
    tf(18,'A conclusion in an opinion essay should not introduce new arguments.','true'),
    fb(19,'___ (Furthermore), the data supports this. ___ (Nevertheless), limitations must be noted.','Furthermore, Nevertheless'),
    fb(20,'Sales ___ (rise, sharply) in Q1. They ___ (level off) by Q3.','rose sharply, levelled off'),
  ]},

  // MODULE 18: Listening Skills
  '5f613ce3-17fc-4a93-af75-30004c0e7efd':{pass_threshold:70,questions:[ // Fast Speech — Reduction & Linking
    mc(1,'What is "elision" in natural speech?','adding extra sounds','dropping sounds or syllables in rapid speech','speaking very slowly','emphasising all words','B'),
    mc(2,'"Gonna" is the reduced form of:','going','going to','got a','getting','B'),
    mc(3,'"Wanna" is the reduced form of:','want a','want to','will want','went to','B'),
    mc(4,'"Gotta" is the reduced form of:','got a','going to','got to / have got to','getting','C'),
    mc(5,'What is "assimilation" in phonetics?','adding sounds','a sound changing to become more like a neighbouring sound','removing sounds','stressing sounds','B'),
    mc(6,'What is "liaison" in English?','pausing between words','linking the end of one word to the start of the next','adding extra syllables','stressing every word','B'),
    mc(7,'What are "weak forms"?','unimportant words','reduced pronunciations of function words in unstressed positions','strong vowel sounds','stressed syllables','B'),
    mc(8,'"Whadya" is the reduced form of:','what do you','what a you','what did you','what are you','A'),
    mc(9,'What does "connected speech" mean?','speaking word by word','the natural flow of sounds linking words together in speech','speaking slowly and clearly','an accent','B'),
    mc(10,'Which is a good strategy when you miss part of a listening?','stop listening','give up','use context and surrounding information to infer the missing part','re-listen endlessly','C'),
    tf(11,'"Gonna" is the informal/reduced form of "going to".','true'),
    tf(12,'In natural speech, every word is pronounced clearly and completely.','false'),
    tf(13,'"Weak forms" are reduced pronunciations of function words.','true'),
    fb(14,'"Wanna" = "___ (want to)". "Gotta" = "___ (have got to)".','want to, have got to'),
    fb(15,'"___ (Elision)" drops sounds. "___ (Liaison)" links words together.','Elision, Liaison'),
  ]},
  '3c56be28-7cec-4bd6-99db-eb2caa1ac2ce':{pass_threshold:70,questions:[ // Accents & Dialects — Awareness
    mc(1,'What is a "dialect"?','a foreign language','a variety of a language with distinct vocabulary, grammar, and pronunciation used in a region','a type of accent','a formal register','B'),
    mc(2,'What is an "accent"?','a grammar difference','a vocabulary difference','differences in pronunciation between regional speakers','a formal writing style','C'),
    mc(3,'What is "RP" (Received Pronunciation)?','Regional Pronunciation','the traditional prestige accent of British English (BBC English)','an American accent','a Scottish accent','B'),
    mc(4,'What is "General American"?','a British accent','a regional American dialect','a widely used standard accent in American English','the accent of General Officers','C'),
    mc(5,'What does "code-switching" mean?','switching computers','alternating between two or more languages or dialects in conversation','using formal language only','learning a new language','B'),
    mc(6,'What is "a lingua franca"?','a dead language','a language used for communication between speakers of different native languages','a dialect','an accent','B'),
    mc(7,'What does "intelligibility" mean?','being very intelligent','the degree to which speech can be understood','pronunciation accuracy','vocabulary richness','B'),
    mc(8,'What is "a rhotic accent"?','an accent without the "r" sound','an accent where the letter "r" is pronounced in all positions','a very fast accent','an accent with strong stress','B'),
    mc(9,'What does "sociolect" mean?','a regional dialect','a variety of language associated with a particular social group','an accent','a formal register','B'),
    mc(10,'What is "idiolect"?','a national language','the unique language variety used by an individual person','a dialect','a sociolect','B'),
    tf(11,'"RP" stands for Received Pronunciation — the traditional prestige British accent.','true'),
    tf(12,'An "accent" refers to differences in vocabulary between regional speakers.','false'),
    tf(13,'A "lingua franca" is a language used between speakers of different native languages.','true'),
    fb(14,'"___ (RP)" is the traditional prestige British accent. A "___ (dialect)" varies in vocabulary and grammar.','RP, dialect'),
    fb(15,'"___ (Code-switching)" alternates between languages. "___ (Intelligibility)" measures how well speech is understood.','Code-switching, Intelligibility'),
  ]},
  '254f38ad-b6f4-455f-a8cb-e8e57ae7ed29':{pass_threshold:70,questions:[ // Note-Taking — Listening Strategies
    mc(1,'What is the best approach to note-taking during a lecture?','write every single word','listen for key ideas and use abbreviations and symbols','only write headings','copy from slides only','B'),
    mc(2,'What does "NB" stand for?','No Business','Nota Bene (important note)','Not Before','No Better','B'),
    mc(3,'What does "eg" stand for?','example given','exempli gratia (for example)','each given','everything good','B'),
    mc(4,'What does "ie" stand for?','in everyone','id est (that is)','it\'s easy','in English','B'),
    mc(5,'What does "cf" mean in notes?','compare/contrast','confer with / compare','come forward','cannot find','B'),
    mc(6,'What is the "Cornell Method" of note-taking?','writing in full sentences','a system with a cue column, notes area, and summary section','only writing headings','copy-pasting slides','B'),
    mc(7,'What are "signal phrases" in lectures?','filler words','phrases that indicate the speaker is about to make an important point (e.g. "The key point is...")','irrelevant phrases','connectors only','B'),
    mc(8,'What does "the main point is" signal?','a minor detail is coming','an important key point is about to be stated','a summary is beginning','a new topic is starting','B'),
    mc(9,'Why is reviewing notes soon after a lecture important?','it is not important','to consolidate learning and fill gaps while information is fresh','to correct spelling only','to memorise word for word','B'),
    mc(10,'What is an effective abbreviation for "because"?','bec','b/c','bc','both B and C','D'),
    tf(11,'Good notes capture key ideas, not every word.','true'),
    tf(12,'"eg" stands for "that is" (id est).','false'),
    tf(13,'The Cornell Method uses a cue column, notes area, and summary section.','true'),
    fb(14,'"___ (NB)" = important note. "___ (eg)" = for example. "___ (ie)" = that is.','NB, eg, ie'),
    fb(15,'___ (Signal phrases) like "the key point is" alert you to important information. Review notes ___ (soon) after lectures.','Signal phrases, soon'),
  ]},
  '6380549a-43f1-4fd2-a007-aa199bd5ee11':{pass_threshold:70,questions:[ // Podcasts & Radio — Real English
    mc(1,'What is a "podcast"?','a radio broadcast','a digital audio programme available for download or streaming','a TV show','a music album','B'),
    mc(2,'What does "subscribe" to a podcast mean?','download one episode','pay for premium content','automatically receive new episodes','share a podcast','B'),
    mc(3,'What is a "transcript"?','a written version of spoken content','a subtitle file','a summary only','a type of recording','A'),
    mc(4,'What is "authentic listening material"?','specially prepared simplified texts','real-world content not created for language learning purposes','a textbook dialogue','a scripted exercise','B'),
    mc(5,'What is a useful strategy for understanding podcasts/radio?','understand every single word','focus on the general meaning and key words; listen multiple times if needed','always read the transcript first','never use transcripts','B'),
    mc(6,'What does "stream" mean?','download to your device','listen/watch directly over the internet without downloading','record','broadcast','B'),
    mc(7,'What is "background noise" in a listening context?','music added for effect','irrelevant sounds that can make listening more challenging','a type of accent','an audio signal','B'),
    mc(8,'What is "monologue" vs "dialogue"?','monologue = two speakers, dialogue = one speaker','monologue = one speaker, dialogue = two or more speakers','no difference','both mean one speaker','B'),
    mc(9,'What is "listening for gist"?','understanding every detail','understanding the overall main idea without focusing on details','listening for specific facts','listening to check notes','B'),
    mc(10,'What does "to paraphrase" while listening mean?','copy exactly what you heard','restate the key idea in your own words','translate the content','ignore the content','B'),
    tf(11,'A "transcript" is a written version of spoken content.','true'),
    tf(12,'"Streaming" means downloading content to your device.','false'),
    tf(13,'"Authentic listening material" is real-world content not designed for language learning.','true'),
    fb(14,'___ (Listening for gist) = general idea. ___ (Subscribing) means automatically receiving new episodes.','Listening for gist, Subscribing'),
    fb(15,'A "___ (transcript)" is the written text of spoken content. "___ (Streaming)" = listening online without downloading.','transcript, Streaming'),
  ]},
  '1b5f0b9a-b32a-4646-8f3a-d91b5c678078':{pass_threshold:70,questions:[ // Academic Lectures — University Listening
    mc(1,'What is a "lecture"?','a small group seminar','a formal presentation by an expert to a large audience','an online quiz','a student presentation','B'),
    mc(2,'What is a "seminar"?','a large lecture','a smaller group discussion or workshop led by a tutor','a solo assignment','a tutorial (same as tutorial in British English)','B'),
    mc(3,'What is "critical listening"?','passive listening','listening that involves evaluating, questioning, and analysing what is heard','reading while listening','ignoring the lecture','B'),
    mc(4,'What are "hedges" in academic lectures?','clear definitive statements','cautious language (might, may, it seems) indicating uncertainty','examples','summaries','B'),
    mc(5,'What is "a rhetorical question" in a lecture?','a question requiring a student answer','a question used by the lecturer for effect, not expecting a student response','an exam question','a survey question','B'),
    mc(6,'What signal means the lecturer is summarising?','"Furthermore..."','To sum up / In conclusion / So, to recap...','"Firstly..."','Interestingly...','B'),
    mc(7,'What signal means the lecturer is giving an example?','However','Therefore','For instance / For example / Take the case of...','In conclusion','C'),
    mc(8,'What is "a tutorial" in British university context?','a large lecture','a one-to-one or small group meeting with a tutor for academic discussion','a written assignment','an online video','B'),
    mc(9,'What is "office hours"?','a time students are not allowed in','scheduled time when academics are available to meet with students','the university opening hours','a work shift','B'),
    mc(10,'What is "active listening"?','sitting quietly','engaging with content through note-taking, questioning, and connecting ideas','sleeping through a lecture','only hearing content','B'),
    tf(11,'Critical listening involves evaluating and analysing what is heard.','true'),
    tf(12,'"Hedges" in lectures indicate complete certainty.','false'),
    tf(13,'"Office hours" are scheduled times when academics meet with students.','true'),
    fb(14,'"For instance" signals ___ (an example). "To sum up" signals ___ (a summary).','an example, a summary'),
    fb(15,'"___ (Critical listening)" evaluates content. "___ (Active listening)" engages through note-taking and questioning.','Critical listening, Active listening'),
  ]},
  'e7f09b65-c571-4ee5-8ab1-ed281b9a2963':{pass_threshold:70,questions:[ // IELTS Listening — Exam Strategies
    mc(1,'How many sections does IELTS Listening have?','2','3','4','5','C'),
    mc(2,'What is the purpose of the preparation time before each IELTS section?','to check answers','to read the questions and predict content','to read the passage','to write notes','B'),
    mc(3,'In IELTS "note completion", answers should:','always be numbers','be taken from the audio (within word limit)','be paraphrased','be full sentences','B'),
    mc(4,'What is "multiple choice" in IELTS Listening?','writing a word','selecting one answer from several options','matching speakers','ordering events','B'),
    mc(5,'What is "matching" in IELTS Listening?','writing answers','connecting items from two lists','choosing from multiple options','completing sentences','B'),
    mc(6,'What happens if you miss an answer in IELTS Listening?','re-listen to the whole section','move on and focus on the next question','ask for more time','write anything','B'),
    mc(7,'What is the danger of fixating on one missed answer?','no danger','missing several subsequent answers while distracted','being penalised','getting help','B'),
    mc(8,'IELTS Listening Section 4 is:','a casual conversation','a two-person discussion','an academic monologue (lecture)','an interview','C'),
    mc(9,'In "form/table completion" tasks, answers are typically:','full paragraphs','single words or numbers','long phrases','quoted sentences','B'),
    mc(10,'What is a "map/plan labelling" task in IELTS?','drawing a map','identifying and labelling locations on a plan using spoken directions','comparing two maps','describing a map in writing','B'),
    tf(11,'IELTS Listening has 4 sections.','true'),
    tf(12,'You should re-listen to find a missed answer in IELTS Listening.','false'),
    tf(13,'IELTS Listening Section 4 is an academic monologue.','true'),
    fb(14,'In IELTS "note completion", answers come from ___ (the audio). Preparation time allows you to ___ (read questions and predict).','the audio, read questions and predict'),
    fb(15,'"___ (Section 4)" is an academic monologue. "___ (Moving on)" from a missed answer prevents losing more.','Section 4, Moving on'),
  ]},
  '028e2e12-7776-494e-9e8c-b8d45fc1d5cc':{pass_threshold:70,questions:[ // Mixed Listening Practice
    mc(1,'You hear: "The meeting has been rescheduled." "Rescheduled" means:','cancelled','moved to a different time','confirmed','started','B'),
    mc(2,'You hear: "Despite the challenges, the project succeeded." "Despite" signals:','reason','addition','contrast/concession','result','C'),
    mc(3,'You hear: "It is estimated that..." — This is an example of:','definite fact','hedging language','a command','a comparison','B'),
    mc(4,'You hear: "Consequently, the results were revised." "Consequently" signals:','contrast','addition','result/consequence','reason','C'),
    mc(5,'You hear "1,250,000" — this is said as:','one million two hundred fifty thousand','one point two five million','one million, two hundred and fifty thousand','one two five zero zero zero zero','C'),
    mc(6,'You hear: "I\'d like to hand over to my colleague." This means:','ending the meeting','introducing the next speaker','asking a question','summarising','B'),
    mc(7,'You hear: "To revisit the key points..." — This signals:','a new argument is starting','a summary or review is beginning','a counter-argument','an example','B'),
    mc(8,'You hear: "He can\'t have submitted the form — he was abroad." — This modal expresses:','possibility','strong advice','impossibility deduction','past obligation','C'),
    mc(9,'You hear: "She\'s been working on this for three years." — What tense is used?','Past Simple','Present Simple','Present Perfect Continuous','Future Perfect','C'),
    mc(10,'You hear: "Unless funding is secured, the project will stall." — "Unless" means:','even if','if','if not','provided that','C'),
    tf(11,'When you hear "consequently", it signals a result or consequence.','true'),
    tf(12,'"Despite" introduces a reason.','false'),
    tf(13,'"Hedging language" in a lecture signals the speaker is being cautious, not definitive.','true'),
    fb(14,'"Despite" = ___ (contrast/concession). "Consequently" = ___ (result).','contrast / concession, result'),
    fb(15,'"Unless" = "___ (if not)". "It is estimated that" = ___ (hedging language).','if not, hedging language'),
  ]},
  '1345ef81-7ee8-4acb-b7f0-f2c754b18d5c':{pass_threshold:80,questions:[ // Module 18 Review
    mc(1,'"Gonna" = reduced form of:','going','going to','got a','getting','B'),
    mc(2,'"Elision" means:','adding sounds','dropping sounds in rapid speech','stressing sounds','linking sounds','B'),
    mc(3,'"RP" stands for:','Regional Pronunciation','Received Pronunciation (traditional prestige British accent)','a dialect','General American','B'),
    mc(4,'A "lingua franca" is:','a dead language','a language used for communication between speakers of different native languages','a dialect','an accent','B'),
    mc(5,'"NB" stands for:','No Business','Nota Bene (important note)','Not Before','No Better','B'),
    mc(6,'The "Cornell Method" uses:','only headings','cue column + notes area + summary section','full sentences only','copy-pasting slides','B'),
    mc(7,'A "transcript" is:','a recording','a written version of spoken content','a subtitle file only','a summary','B'),
    mc(8,'"Listening for gist" means:','understanding every detail','understanding the overall main idea','listening for specific facts','checking notes','B'),
    mc(9,'IELTS Listening has:','2 sections','3 sections','4 sections','5 sections','C'),
    mc(10,'IELTS Section 4 is:','a casual conversation','an interview','an academic monologue','a two-person discussion','C'),
    mc(11,'"Hedges" in lectures indicate:','certainty','caution/uncertainty','definitive facts','examples','B'),
    mc(12,'"Active listening" involves:','passive hearing','engaging through note-taking and questioning','sleeping through lectures','only hearing','B'),
    mc(13,'"Despite" signals:','reason','addition','contrast/concession','result','C'),
    mc(14,'In IELTS "note completion", answers come from:','your own knowledge','the audio (within word limit)','paraphrase','full sentences','B'),
    mc(15,'A "signal phrase" in a lecture:','is irrelevant','indicates an important point is about to be made','is filler','is a grammatical term','B'),
    tf(16,'"Liaison" links words together in natural speech.','true'),
    tf(17,'You should re-listen to find a missed answer in IELTS.','false'),
    tf(18,'Reviewing notes soon after a lecture improves retention.','true'),
    fb(19,'"Wanna" = "___ (want to)". "___ (Liaison)" links sounds between words.','want to, Liaison'),
    fb(20,'"___ (Consequently)" signals result. "___ (Signal phrases)" alert you to key information.','Consequently, Signal phrases'),
  ]},

  // MODULE 19: Communication Skills
  '4bbbb1b0-1b3b-4a3d-8799-5e587708aa59':{pass_threshold:70,questions:[ // Expressing Opinions
    mc(1,'Which phrase introduces a personal view?','According to everyone','In my view / I think / I believe','It is a proven fact','Everyone agrees','B'),
    mc(2,'Complete: "From my ___, this approach is the most effective."','sight','perspective','look','area','B'),
    mc(3,'Which phrase asks for someone\'s opinion?','I totally agree.','That\'s interesting.','What is your take on this?','I disagree.','C'),
    mc(4,'Complete: "As far as I ___ (concern), the evidence is clear."','concern','am concerned','concerns','is concerned','B'),
    mc(5,'Which phrase concedes a point before disagreeing?','You\'re wrong.','That\'s nonsense.','I take your point, but...','I totally agree.','C'),
    mc(6,'Which phrase is a strong agreement?','I see what you mean.','That\'s a valid point.','I couldn\'t agree more.','I\'m not sure about that.','C'),
    mc(7,'Complete: "It is my ___ that further research is necessary."','opinion','sight','thought','idea','A'),
    mc(8,'Which phrase expresses a tentative opinion?','I strongly believe...','I\'m certain that...','I tend to think / It seems to me that...','It\'s obviously true that...','C'),
    mc(9,'Complete: "While I appreciate your point, I remain ___ (unconvinced)."','unconvinced','unsure','against','below','A'),
    mc(10,'Which phrase invites others to contribute?','I\'ve made my point — moving on.','What does everyone else think?','I disagree completely.','That\'s wrong.','B'),
    tf(11,'"In my view" introduces a personal opinion.','true'),
    tf(12,'"It is a proven fact" is the same as expressing a personal opinion.','false'),
    tf(13,'"I tend to think" expresses a tentative or careful opinion.','true'),
    fb(14,'___ (In my view), this policy is ineffective. ___ (What is) your take on this?','In my view, What is'),
    fb(15,'As far as I ___ (am concerned), the evidence is clear. I ___ (couldn\'t agree) more.','am concerned, couldn\'t agree'),
  ]},
  'a170d0b4-91f9-40cc-8ea9-99495fc78c15':{pass_threshold:70,questions:[ // Agreeing & Disagreeing
    mc(1,'Which phrase agrees strongly?','I see what you mean.','That\'s a fair point.','I couldn\'t agree more.','I\'m not convinced.','C'),
    mc(2,'Which phrase partially agrees?','I totally disagree.','I see your point, but I think there\'s more to consider.','That\'s completely wrong.','I couldn\'t agree less.','B'),
    mc(3,'Which phrase formally disagrees?','No!','That\'s rubbish!','I\'m afraid I hold a different view on this matter.','You\'re wrong.','C'),
    mc(4,'Complete: "I take your ___, but I would argue..."','side','point','meaning','idea','B'),
    mc(5,'Which phrase shows you understand but disagree?','I agree completely.','That\'s a valid point; however, I disagree for the following reason...','I don\'t care.','You\'re right.','B'),
    mc(6,'What does "to concede a point" mean?','to win an argument','to acknowledge that the opposing view has some validity','to disagree strongly','to ignore the argument','B'),
    mc(7,'Complete: "While I acknowledge that ___, I would nevertheless argue..."','you are right','there is some merit in this view','you are wrong','I disagree','B'),
    mc(8,'Which phrase formally invites response?','Tell me what you think.','I\'d be interested to hear your perspective.','What do you reckon?','Say something.','B'),
    mc(9,'Complete: "I am ___ (not) persuaded by this argument for the following reasons..."','completely','not','very','entirely','B'),
    mc(10,'Which is an appropriate formal agreement?','Yeah, sure.','I concur with that assessment.','OK.','That works.','B'),
    tf(11,'"I couldn\'t agree more" expresses strong agreement.','true'),
    tf(12,'"I\'m afraid I hold a different view" is a rude way to disagree.','false'),
    tf(13,'"To concede a point" means to acknowledge some validity in the opposing view.','true'),
    fb(14,'I ___ (take) your point, but I would argue otherwise. I ___ (concur) with that assessment.','take, concur'),
    fb(15,'I ___ (acknowledge) there is merit in this view. ___ (Nevertheless), I hold a different position.','acknowledge, Nevertheless'),
  ]},
  '3b14a8ea-7677-49da-872a-e325cb153c06':{pass_threshold:70,questions:[ // Debates — Structuring Arguments
    mc(1,'What is "a proposition" in a debate?','the conclusion','the motion or statement being debated','the opposition','a question','B'),
    mc(2,'What is "the opposition"?','the side supporting the motion','the side arguing against the motion','the chairperson','the audience','B'),
    mc(3,'What does "to make a concession" mean?','to disagree entirely','to acknowledge a valid point from the opposing side','to win the debate','to avoid the argument','B'),
    mc(4,'What is "rebuttal"?','a statement of position','a response that counters an opponent\'s argument','a question','a conclusion','B'),
    mc(5,'What is "to floor the house"?','to drop something','to win the debate and persuade the audience','to lose a debate','to confuse the audience','B'),
    mc(6,'What is "a motion" in a formal debate?','a physical movement','the statement to be argued for or against','a type of evidence','a procedure','B'),
    mc(7,'What is "the chair" in a debate?','a piece of furniture','the person who moderates and manages the debate','a type of argument','the first speaker','B'),
    mc(8,'Complete: "I would like to ___ (rebut) the previous speaker\'s argument about..."','rebut','debate','chair','floor','A'),
    mc(9,'What is a "closing statement" in a debate?','the opening position','a final summary of the team\'s arguments','a rebuttal','a new argument','B'),
    mc(10,'What phrase formally challenges an argument?','You\'re wrong!','That\'s nonsense.','With respect, this argument overlooks a crucial factor...','Absolutely not!','C'),
    tf(11,'"Rebuttal" is a response countering an opponent\'s argument.','true'),
    tf(12,'The "opposition" supports the motion.','false'),
    tf(13,'A "closing statement" summarises the team\'s key arguments.','true'),
    fb(14,'I would like to ___ (rebut) this point. The ___ (chair) moderates the debate.','rebut, chair'),
    fb(15,'With ___ (respect), this argument overlooks key evidence. I ___ (concede) one point — however...','respect, concede'),
  ]},
  '30f23605-eff4-41c4-b284-0f646777b234':{pass_threshold:70,questions:[ // Presentations — Public Speaking
    mc(1,'What should you do at the start of a presentation?','jump straight into details','greet the audience, introduce yourself, and state the purpose','read from your notes','give the conclusion first','B'),
    mc(2,'What is "eye contact" important for?','looking at notes','reading the screen','engaging the audience and projecting confidence','focusing on one person only','C'),
    mc(3,'What is "signposting language"?','using road signs','language that guides the audience through the structure (e.g. "Turning to...")','a grammar term','a vocabulary term','B'),
    mc(4,'What does "moving on" signal?','the conclusion','a new point or section is beginning','returning to a previous point','giving an example','B'),
    mc(5,'What is a "rhetorical question" in a presentation?','a question expecting an answer','a question used for effect to engage the audience','an interview question','a survey question','B'),
    mc(6,'Complete: "I\'d like to draw your ___ to the key findings."','eye','attention','interest','focus','B'),
    mc(7,'What is "pacing" in public speaking?','the speed and rhythm of speech','the slide design','the room layout','the vocabulary level','A'),
    mc(8,'What does "Q&A" stand for?','Quality and Assurance','Questions and Answers','Quick and Accurate','None of these','B'),
    mc(9,'Complete: "To ___ up, the evidence clearly supports..."','sum','wrap','round','bring','A'),
    mc(10,'What is the best way to handle a question you can\'t answer?','make up an answer','ignore it','say "That\'s a great question — let me look into that."','say nothing','C'),
    tf(11,'Eye contact with the audience is important in presentations.','true'),
    tf(12,'Reading directly from notes is the best public speaking technique.','false'),
    tf(13,'"Signposting language" guides the audience through the presentation structure.','true'),
    fb(14,'I\'d like to draw your ___ (attention) to the data. Moving ___ (on) to the next point.','attention, on'),
    fb(15,'To sum ___ (up), the findings confirm our hypothesis. ___ (Q&A) follows the presentation.','up, Q&A'),
  ]},
  'f6b8733b-d62a-4eb1-85a3-9b38c7daf833':{pass_threshold:70,questions:[ // Negotiations — Business Communication
    mc(1,'What does "to make a concession" mean in negotiation?','to win a point','to give up something to reach agreement','to withdraw from negotiation','to refuse a demand','B'),
    mc(2,'What is "BATNA"?','a type of agreement','Best Alternative To a Negotiated Agreement','a negotiation tactic','a contract type','B'),
    mc(3,'What does "to reach a deadlock" mean?','to finalise an agreement','to reach a situation where no progress can be made','to start negotiating','to win','B'),
    mc(4,'What is "a win-win outcome"?','one party benefits at the other\'s expense','both parties feel satisfied with the agreement','one party wins','no agreement is reached','B'),
    mc(5,'What does "to open the bidding" mean?','to close negotiation','to make the first offer','to refuse an offer','to accept an offer','B'),
    mc(6,'Complete: "I think we can ___ (find) some common ground on this." (negotiation)','find','make','take','get','A'),
    mc(7,'What is "to stonewall" in negotiations?','to agree quickly','to refuse to cooperate or give information, blocking progress','to negotiate effectively','to propose a compromise','B'),
    mc(8,'What is a "compromise"?','one side winning','both sides giving up something to reach a middle ground','refusing to negotiate','an initial offer','B'),
    mc(9,'Complete: "We\'re prepared to ___ (offer) a 10% discount in exchange for a longer contract."','offer','take','make','get','A'),
    mc(10,'What does "to table an offer" mean?','to remove an offer','to formally put an offer forward for consideration','to reject an offer','to accept immediately','B'),
    tf(11,'"BATNA" is your best alternative if the negotiation fails.','true'),
    tf(12,'A "win-win outcome" means only one party benefits.','false'),
    tf(13,'"To reach a deadlock" means progress in negotiations has stalled.','true'),
    fb(14,'We can ___ (find) common ground. They ___ (reach) a deadlock after three hours.','find, reached'),
    fb(15,'"___ (BATNA)" is your best alternative if talks fail. A "___ (compromise)" means both sides give something up.','BATNA, compromise'),
  ]},
  '2a6645de-d6e5-4b9a-a64d-66c98832c015':{pass_threshold:70,questions:[ // Small Talk — Social English
    mc(1,'What is "small talk"?','a short, direct business conversation','light, informal conversation on non-controversial topics','a formal speech','a type of interview','B'),
    mc(2,'Which topic is generally safe for small talk?','personal finances','religion','the weather / local events / travel','politics','C'),
    mc(3,'Complete: "How are you finding life in ___ (the city)?" (small talk opener)','the city','your country','working here','this place','A'),
    mc(4,'What is a "conversation filler"?','a meaningful statement','a phrase used to maintain conversation flow while thinking (e.g. "you know", "well...")','a formal discourse marker','a debate technique','B'),
    mc(5,'What does "to break the ice" mean?','to damage something frozen','to initiate social interaction and ease awkwardness','to end a conversation','to make a cultural faux pas','B'),
    mc(6,'Complete: "It\'s been a ___ (lovely) day today, hasn\'t it?" (small talk about weather)','lovely','difficult','interesting','long','A'),
    mc(7,'What is "active listening" in small talk?','doing all the talking','nodding, asking follow-up questions, and showing genuine interest','ignoring the other person','staying silent','B'),
    mc(8,'What is a "follow-up question"?','a question asked before the main question','a question that continues the conversation based on what was said','a closing question','a formal question','B'),
    mc(9,'What does "to wrap up a conversation" mean?','to start talking','to conclude the conversation politely','to ask a question','to change the topic','B'),
    mc(10,'Which phrase politely ends a conversation?','Goodbye!','Stop talking!','It was lovely chatting — I must let you get on.','I\'m done talking.','C'),
    tf(11,'The weather is a common safe topic for small talk in English-speaking cultures.','true'),
    tf(12,'Politics and religion are universally considered safe small talk topics.','false'),
    tf(13,'"Breaking the ice" means initiating social interaction to ease awkwardness.','true'),
    fb(14,'"___ (Breaking the ice)" eases awkwardness. "___ (Active listening)" shows genuine interest.','Breaking the ice, Active listening'),
    fb(15,'"It was lovely ___ (chatting)" wraps up a conversation. A "___ (follow-up question)" keeps it going.','chatting, follow-up question'),
  ]},
  'e05ca8e0-5963-455b-a7a8-bf76b23bdfc6':{pass_threshold:70,questions:[ // Interviews — Question & Answer Practice
    mc(1,'Which phrase formally introduces yourself at an interview?','I\'m just John.','Hi!','Good morning. My name is [Name]. I\'m delighted to be here today.','Hey, I\'m here.','C'),
    mc(2,'Complete (strength): "One of my greatest ___ (strength) is my ability to analyse complex data."','strengths','skill','quality','ability','A'),
    mc(3,'Complete (weakness, strategic): "I\'m working on ___ (improve) my public speaking skills."','improving','improve','improvement','improved','A'),
    mc(4,'STAR method: what is the correct order?','Action, Situation, Task, Result','Situation, Task, Action, Result','Result, Action, Situation, Task','Task, Situation, Result, Action','B'),
    mc(5,'Complete: "In my previous role, I ___ (lead) a team of researchers." (past)','lead','leads','was leading','led','D'),
    mc(6,'Which closing phrase is appropriate?','That\'s all from me.','I\'m really keen on this role and I look forward to the next steps.','Thanks.','I want the job.','B'),
    mc(7,'Complete: "I am particularly ___ (drawn) to this role because..."','drawn','interest','attract','pull','A'),
    mc(8,'What is "a competency-based question"?','a technical test','"Tell me about a time when you..." — asking for past examples of specific skills','a personality test','a general knowledge test','B'),
    mc(9,'Complete: "Could you tell me more about the ___ (opportunity) for professional development?"','opportunity','possibilities','chances','options','A'),
    mc(10,'Which phrase asks a thoughtful closing question?','Do I get the job?','What are the key challenges I would face in this role?','When do I start?','What\'s the salary?','B'),
    tf(11,'The STAR method stands for Situation, Task, Action, Result.','true'),
    tf(12,'A strategic weakness at interview should be a genuine strength in disguise.','false'),
    tf(13,'"I am particularly drawn to this role because..." is a formal way to express interest.','true'),
    fb(14,'I ___ (led) a team of twelve. My key ___ (strength) is critical analysis.','led, strength'),
    fb(15,'I am ___ (drawn) to this role. Could you tell me about ___ (opportunities) for development?','drawn, opportunities'),
  ]},
  '2ac68c5a-7566-404c-84cd-224a81559523':{pass_threshold:80,questions:[ // Module 19 Review
    mc(1,'"In my view" introduces:','a proven fact','a personal opinion','a counter-argument','a conclusion','B'),
    mc(2,'Complete: "As far as I ___ (am concerned)..."','concern','concerned','am concerned','is concerned','C'),
    mc(3,'"I couldn\'t agree more" means:','I strongly disagree','I partially agree','I strongly agree','I\'m not sure','C'),
    mc(4,'"To concede a point" means:','to win an argument','to acknowledge the opposing view has some validity','to disagree strongly','to ignore','B'),
    mc(5,'"Rebuttal" is:','a statement of position','a response countering an opponent\'s argument','a conclusion','a question','B'),
    mc(6,'"The opposition" in a debate:','supports the motion','argues against the motion','chairs the debate','represents the audience','B'),
    mc(7,'Signposting language in presentations:','confuses the audience','guides the audience through the structure','replaces content','is only for summaries','B'),
    mc(8,'"Moving on" in a presentation signals:','the conclusion','a new point or section beginning','returning to previous point','giving an example','B'),
    mc(9,'"BATNA" means:','a negotiation contract','Best Alternative To a Negotiated Agreement','a type of compromise','a closing technique','B'),
    mc(10,'"A win-win outcome" means:','one party wins','both parties are satisfied','no agreement is reached','one party loses','B'),
    mc(11,'Safe small talk topics include:','politics and religion','weather and local events','salary and personal finances','both A and C','B'),
    mc(12,'"Breaking the ice" means:','damaging something','initiating social interaction to ease awkwardness','ending a conversation','making a mistake','B'),
    mc(13,'STAR method order:','Action, Situation, Task, Result','Result, Action, Situation, Task','Situation, Task, Action, Result','Task, Situation, Result, Action','C'),
    mc(14,'"Competency-based question" uses:','technical tests','"Tell me about a time when..." format','personality tests','general knowledge','B'),
    mc(15,'Which formally closes a presentation?','Great, that\'s it!','To sum up, the evidence clearly demonstrates...','I\'m done.','Next slide.','B'),
    tf(16,'"I tend to think" expresses a tentative or careful opinion.','true'),
    tf(17,'The "opposition" in a debate supports the motion.','false'),
    tf(18,'"Active listening" in small talk shows genuine interest.','true'),
    fb(19,'I ___ (acknowledge) your point. ___ (Nevertheless), I maintain my position.','acknowledge, Nevertheless'),
    fb(20,'I am particularly ___ (drawn) to this role. My greatest ___ (strength) is...','drawn, strength'),
  ]},

  // MODULE 20: The Final Mile
  'ee4aa177-c002-4566-8775-70bb72e1541c':{pass_threshold:70,questions:[ // Grammar Review I — Tenses Active & Passive
    mc(1,'PP Continuous: "She ___ (work) on the paper for months."','worked','has worked','has been working','is working','C'),
    mc(2,'Past Perfect: "By the time he arrived, she ___ (submit)."','submitted','has submitted','had submitted','was submitting','C'),
    mc(3,'Present Passive: "English ___ (speak) worldwide."','spoke','speaks','is spoken','has spoken','C'),
    mc(4,'Past Passive: "The law ___ (repeal) in 2018."','repealed','was repealed','is repealed','has been repealed','B'),
    mc(5,'PP Passive: "The report ___ (publish) yet."','isn\'t published','wasn\'t published','hasn\'t been published','wasn\'t been published','C'),
    mc(6,'Present Continuous Passive: "The data ___ (currently/analyse)."','is currently being analysed','currently analyses','was currently analysed','has been analysed','A'),
    mc(7,'Past Continuous: "She ___ (write) her thesis when the power failed."','wrote','had written','was writing','has written','C'),
    mc(8,'Future Continuous: "At 3 pm tomorrow, they ___ (present)."','will present','are presenting','will be presenting','present','C'),
    mc(9,'Future Perfect: "By 2030, she ___ (publish) 50 papers."','will publish','is publishing','will have published','publishes','C'),
    mc(10,'Present Perfect Simple vs Continuous: "I ___ (just/finish) the review." vs "I ___ (work) all day."','have just finished / have been working','just finished / worked','have just finished / have worked','finished / was working','A'),
    tf(11,'Present Perfect Passive = have/has + been + past participle.','true'),
    tf(12,'Past Continuous Passive = was/were + past participle.','false'),
    tf(13,'Future Perfect shows an action completed before a specific future time.','true'),
    fb(14,'She ___ (work, PP Cont.) on this for years. The data ___ (analyse, present passive) now.','has been working, is being analysed'),
    fb(15,'By 2030, they ___ (complete, FP). The results ___ (publish, PP passive) last year.','will have completed, were published'),
  ]},
  'c0e5954a-a601-4b6d-b162-3ae172d24180':{pass_threshold:70,questions:[ // Grammar Review II — Modals & Conditionals
    mc(1,'Strong deduction: "She ___ be exhausted — she\'s worked 20 hours."','might','could','must','should','C'),
    mc(2,'Impossibility deduction: "He ___ have submitted it — he was abroad."','might not','mustn\'t','can\'t','shouldn\'t','C'),
    mc(3,'Past criticism: "She ___ disclosed the conflict of interest." (she didn\'t)','should have','could have','must have','would have','A'),
    mc(4,'Unrealised past possibility: "He ___ achieved more with better resources."','should have','could have','must have','would have','B'),
    mc(5,'Zero Conditional: "If you ___ (heat) metal, it ___ (expand)."','heat / expands','heated / expanded','heat / will expand','would heat / expand','A'),
    mc(6,'Third Conditional: "If they ___ (replicate), findings ___ (stronger)."','had replicated / would have been','replicated / would be','had replicated / would be','replicated / would have been','A'),
    mc(7,'Mixed (3→2): "If she ___ (not/make) that error, her career ___ (better) now."','hadn\'t made / would be','didn\'t make / would be','hadn\'t made / would have been','hasn\'t made / would be','A'),
    mc(8,'Wish (present): "I wish I ___ (speak) Arabic." (I can\'t)','spoke','speak','will speak','would speak','A'),
    mc(9,'Conditional linker: "___ funding is secured, research will begin."','Unless','Even if','As long as / Provided that','Although','C'),
    mc(10,'Modal: "You ___ submit by noon — it\'s mandatory." (external obligation)','should','might','have to / must','could','C'),
    tf(11,'"Must have done" is used for strong deductions about past events.','true'),
    tf(12,'Third Conditional uses past simple in the if-clause.','false'),
    tf(13,'"Unless" means "if not".','true'),
    fb(14,'If she ___ (study, 3rd cond.), she ___ (pass). He ___ (must) be the expert — he knows everything.','had studied, would have passed, must'),
    fb(15,'I wish I ___ (know) the answer now. She ___ (should have) disclosed that earlier.','knew, should have'),
  ]},
  '169e59a8-81f7-4a57-b8a2-d530f4b213f2':{pass_threshold:70,questions:[ // Grammar Review III — Reported Speech & Relatives
    mc(1,'Report: "I am conducting research." → She said she ___ conducting research.','is','was','were','has been','B'),
    mc(2,'"Will" in reported speech becomes:','will','shall','would','should','C'),
    mc(3,'Reported question: "Where do you publish?" → She asked where I ___.','publish','published','do publish','was publishing','B'),
    mc(4,'Reported command: "Submit your work." → She told us ___ our work.','submit','to submit','submitting','that submit','B'),
    mc(5,'Defining relative: "The researcher ___ conducted the study published her findings."','which','who','whom','whose','B'),
    mc(6,'Non-defining relative: "Her paper, ___ was published last year, is widely cited."','that','who','which','whose','C'),
    mc(7,'Reduced relative: "The data ___ (collect) last year was analysed."','collecting','collected','having collected','which collecting','B'),
    mc(8,'Indirect question: "Could you tell me ___ the seminar starts?"','when does','when','when is','that when','B'),
    mc(9,'Reporting verb "deny": "He ___ having plagiarised."','admitted','denied','claimed','refused','B'),
    mc(10,'Reporting verb "suggest": "She ___ reviewing the methodology."','told','suggested','said','informed','B'),
    tf(11,'Indirect questions use normal statement word order (no inversion).','true'),
    tf(12,'"That" can be used in non-defining relative clauses.','false'),
    tf(13,'"Deny + gerund" reports a denial: "She denied having made an error."','true'),
    fb(14,'"I have finished," he said → He said he ___ finished. She ___ (deny) having been there.','had, denied'),
    fb(15,'The study, ___ (whose) results were unexpected, changed the field. She asked where I ___ (work).','whose, worked'),
  ]},
  'ba0bcbaa-312c-4a98-a7b7-27ec29a9dc7c':{pass_threshold:70,questions:[ // Grammar Review IV — Articles & Word Formation
    mc(1,'Complete: "She published ___ article. ___ article was widely cited."','an / The','the / A','a / The','an / An','C'),
    mc(2,'Zero article: "___ research is essential."','The','A','No article','An','C'),
    mc(3,'British English: "He was admitted to ___ hospital." (as a patient)','the','a','no article','an','C'),
    mc(4,'Non-defining: "The study, ___ took three years, has been published."','that','who','which','whose','C'),
    mc(5,'Defining: "The researcher ___ conducted the study published her findings."','which','who','whose','that','B'),
    mc(6,'Reduced relative: "Studies ___ (show) a correlation are more publishable."','which show','showing','shown','showed','B'),
    mc(7,'Prefix "un-": opposite of "reliable"?','disreliable','unreliable','inreliable','imreliable','B'),
    mc(8,'Prefix "over-": meaning?','under','not','too much/excessive','again','C'),
    mc(9,'Suffix "-tion": noun of "communicate"?','communicatment','communicatness','communication','communicatize','C'),
    mc(10,'Suffix "-ful": adjective of "hope"?','hopeless','hopeful','hopeless or hopeful (both)','hopeful only','C'),
    tf(11,'"The" is used for unique things (the sun, the Nile).','true'),
    tf(12,'"Im-" is used before all consonant sounds.','false'),
    tf(13,'Reduced relative clauses use -ing for active meaning and past participle for passive.','true'),
    fb(14,'She ___ (submit, past) the paper. The study ___ (already/publish, PP passive).','submitted, has already been published'),
    fb(15,'Reliable → ___ (un-). Decide → ___ (-sion). Hope → hopeful (___) / hopeless (___).','unreliable, decision, -ful, -less'),
  ]},
  'eaa9a28d-c4b9-4637-bf1f-9b0b500a01da':{pass_threshold:70,questions:[ // Vocabulary Review I — Modules 1–10
    mc(1,'What does "go viral" mean?','crash a website','spread rapidly online','become popular slowly','delete content','B'),
    mc(2,'What does "hit it off" mean?','have an argument','get along very well from the start','lose contact','break up','B'),
    mc(3,'What does "break a world record" mean (collocation)?','destroy a record','achieve a new world record','fail at sport','set an official record (both break and set)','D'),
    mc(4,'What is "planned obsolescence"?','quality assurance','designing products to become outdated quickly','eco-design','long warranties','B'),
    mc(5,'What is "habeas corpus"?','a type of crime','a right preventing unlawful detention','a court order','a type of evidence','B'),
    mc(6,'What does "must have" express?','weak possibility','strong deduction about a past action','past obligation','advice','B'),
    mc(7,'What does "can\'t have" express?','possibility','past ability','impossibility deduction about the past','past permission','C'),
    mc(8,'What is "biodiversity"?','a single species','the variety of life in an area','a type of pollution','a policy','B'),
    mc(9,'What does "bury the hatchet" mean?','hide something','start a conflict','make peace after a conflict','dig a hole','C'),
    mc(10,'What does "critically acclaimed" mean?','commercially successful','widely criticised','praised by critics','popular worldwide','C'),
    tf(11,'"Going viral" means content spreads very rapidly online.','true'),
    tf(12,'"A fair-weather friend" is extremely loyal.','false'),
    tf(13,'"Planned obsolescence" designs products to become outdated quickly.','true'),
    fb(14,'"___ (Biodiversity)" = variety of life. "___ (Habeas corpus)" prevents unlawful detention.','Biodiversity, Habeas corpus'),
    fb(15,'"Bury the ___ (hatchet)" = make peace. "___ (Critically acclaimed)" = praised by critics.','hatchet, Critically acclaimed'),
  ]},
  'aa1294d0-a5ca-4651-a50b-4af23fe0a2eb':{pass_threshold:70,questions:[ // Vocabulary Review II — Modules 11–19
    mc(1,'What does "STAR method" stand for?','Skill, Task, Achievement, Result','Situation, Task, Action, Result','Strategy, Talent, Ambition, Result','Speed, Task, Accuracy, Result','B'),
    mc(2,'What does "burnout" mean?','being fired','physical/emotional exhaustion from prolonged work stress','a short-term tiredness','a workplace injury','B'),
    mc(3,'What is "net zero"?','no economic growth','balancing emissions and removals to zero overall','no renewable energy','zero population','B'),
    mc(4,'What does "look into" mean?','look upward','investigate/research','look downward','avoid','B'),
    mc(5,'What does "give rise to" mean?','end','cause or create something','give way to','give in to','B'),
    mc(6,'What does "call into question" mean?','confirm','cast doubt on/challenge validity','call for','call out','B'),
    mc(7,'What is "rote learning"?','critical thinking','memorising without understanding','discovery learning','project-based learning','B'),
    mc(8,'What is "palliative care"?','treatment for curable disease','care focusing on relief from symptoms','surgery','preventive medicine','B'),
    mc(9,'What is "coherence" in academic writing?','vocabulary richness','logically connected ideas with smooth flow','paragraph length','grammar accuracy','B'),
    mc(10,'What is "inference" in reading?','reading aloud','understanding what is implied','summarising','translating','B'),
    tf(11,'"Burnout" is caused by prolonged work-related stress.','true'),
    tf(12,'"Rote learning" emphasises understanding over memorisation.','false'),
    tf(13,'"Call into question" means to cast doubt on the validity of something.','true'),
    fb(14,'"___ (STAR)" = Situation, Task, Action, Result. "___ (Net zero)" = balancing emissions and removals.','STAR, Net zero'),
    fb(15,'"___ (Give rise to)" = cause. "___ (Palliative)" care focuses on symptom relief.','Give rise to, Palliative'),
  ]},
  '8a654434-df9f-4f0e-92af-96362f16f0ce':{pass_threshold:75,questions:[ // Mock Test — IELTS Style
    mc(1,'PP Continuous: "She ___ (research) this topic for years."','researched','has researched','has been researching','is researching','C'),
    mc(2,'Past Perfect: "By the time the paper was submitted, she ___ (revise) it three times."','revised','has revised','had revised','was revising','C'),
    mc(3,'Present Perfect Passive: "The data ___ (analyse) by the team."','analysed','was analysed','has been analysed','is analysed','C'),
    mc(4,'Third Conditional: "If they ___ (use) a larger sample, the findings ___ (be) more reliable."','had used / would have been','used / would be','had used / would be','used / would have been','A'),
    mc(5,'"I wish I ___ (speak) Mandarin." — This expresses:','a real condition','a past regret','a present wish (I can\'t speak it)','a future plan','C'),
    mc(6,'Non-defining relative: "Her thesis, ___ was supervised by Prof. Lee, won an award."','that','who','which','whose','C'),
    mc(7,'Reduced relative: "The methodology ___ in this paper is novel."','which is used','using','used','having used','C'),
    mc(8,'Reported statement: "I will present tomorrow," she said. → She said she ___ present the next day.','will','would','could','should','B'),
    mc(9,'Modal — deduction: "She ___ be the lead author — she knows every detail."','might','could','must','should','C'),
    mc(10,'Modal — past criticism: "He ___ disclosed the funding source." (he didn\'t)','should have','could have','must have','would have','A'),
    mc(11,'"However" signals:','addition','result','contrast','reason','C'),
    mc(12,'IELTS Task 2 minimum word count:','100','150','250','300','C'),
    mc(13,'"Inference" means:','reading every word','understanding what is implied','summarising','translating','B'),
    mc(14,'Prefix "re-" means:','not','again','too much','under','B'),
    mc(15,'Collocation: "___ a conclusion"','make','draw/reach','take','get','B'),
    tf(16,'"Not Given" in IELTS True/False/Not Given means the information is not mentioned.','true'),
    tf(17,'"Should have done" means the action was done correctly.','false'),
    tf(18,'Present Perfect Passive = have/has + been + past participle.','true'),
    fb(19,'She ___ (have been working, PP Cont.) on this for months. The study ___ (has been published, PP passive).','has been working, has been published'),
    fb(20,'If they ___ (had replicated, 3rd cond.), they ___ (would have confirmed) the results.','had replicated, would have confirmed'),
  ]},
  '8550f8ab-5980-4a8a-ac64-8c2a21545634':{pass_threshold:70,questions:[ // Common Mistakes & Important Contrasts
    mc(1,'"Fewer" vs "Less": "There are ___ students this year." (countable)','less','fewer','little','a few','B'),
    mc(2,'"Less" vs "Fewer": "She has ___ free time." (uncountable)','fewer','less','a little','a few','B'),
    mc(3,'"Affect" vs "Effect": "The research ___ (impact/verb) the policy."','effects','affected','effectuated','effected','B'),
    mc(4,'"Affect" vs "Effect": "The ___ (result/noun) was significant."','affect','effect','effection','affection','B'),
    mc(5,'"Comprise" vs "consist of": "The study ___ five experiments." (the whole contains the parts)','consists of','comprises','is comprised of (debated)','both A and B','D'),
    mc(6,'"Since" vs "For": "She has worked here ___ 2019."','for','since','during','ago','B'),
    mc(7,'"Since" vs "For": "He has been a professor ___ 20 years."','since','during','for','ago','C'),
    mc(8,'"Who" vs "Whom": "___ did she collaborate with?" (object)','Who','Whom','Whose','Which','B'),
    mc(9,'"Lay" vs "Lie": "Please ___ the documents on the table." (transitive verb)','lie','lay','lied','laid','B'),
    mc(10,'"Continual" vs "continuous": "___ interruptions disrupted the lecture." (repeated, not constant)','Continuous','Continual','Continuously','Continually','B'),
    tf(11,'"Fewer" is used with countable nouns; "less" with uncountable nouns.','true'),
    tf(12,'"Effect" is usually a verb; "affect" is usually a noun.','false'),
    tf(13,'"Whom" is used as the object in formal English.','true'),
    fb(14,'"Fewer" students, "___ (less)" time. She has worked here ___ (since) 2020, ___ (for) two years.','less, since, for'),
    fb(15,'"The policy ___ (affected) the results." "The ___ (effect) was significant."','affected, effect'),
  ]},
  'a44a4458-06d1-4760-b3dc-7be84a8c313b':{pass_threshold:80,questions:[ // Final Test & Certificate (25 questions)
    mc(1,'PP Continuous: "She ___ (research) this for years."','researched','has researched','has been researching','is researching','C'),
    mc(2,'Present Passive: "The data ___ (analyse) daily."','analyses','analysed','is analysed','has analysed','C'),
    mc(3,'Past Perfect Passive: "By 2020, the law ___ (amend) three times."','amended','was amended','has been amended','had been amended','D'),
    mc(4,'Third Conditional: "If they ___ (conduct) a pilot, the flaw ___ (identify) earlier."','had conducted / would have been identified','conducted / would have been identified','had conducted / would be identified','conducted / would identify','A'),
    mc(5,'"Must" for deduction: "She ___ be the supervisor — she answered every question."','might','could','must','should','C'),
    mc(6,'"Should have + pp": "He ___ disclosed the conflict of interest." (criticism)','should have','could have','must have','would have','A'),
    mc(7,'Non-defining relative: "Her paper, ___ was published in Nature, won awards."','that','who','which','whose','C'),
    mc(8,'Reported speech: "I have submitted it," she said. → She said she ___ submitted it.','has','had','was','would have','B'),
    mc(9,'Indirect question: "Could you tell me ___ the results will be published?"','when will','when','when are','that when','B'),
    mc(10,'Reporting verb: "She ___ (suggest) reviewing the methodology."','told','suggested','said','informed','B'),
    mc(11,'Zero Cond.: "If you ___ (heat) water to 100°C, it ___ (boil)."','heat / boils','heat / will boil','heated / boiled','would heat / boils','A'),
    mc(12,'Wish (present): "I wish I ___ (speak) Japanese." (I can\'t)','spoke','speak','will speak','would speak','A'),
    mc(13,'Articles: "She published ___ article. ___ article was cited."','an / The','a / The','the / A','an / An','A'),
    mc(14,'"Gonna" is the reduced form of:','going','going to','got a','getting','B'),
    mc(15,'Phrasal verb: "___ (give up)" means:','start','quit/stop trying','give away','give in','B'),
    mc(16,'Prefix "over-" means:','insufficient','again','too much/excessive','not','C'),
    mc(17,'Suffix "-tion" creates:','adjectives','adverbs','verbs','nouns from verbs','D'),
    mc(18,'Collocation: "___ a study"','make','do','conduct / carry out','take','C'),
    mc(19,'"IELTS Task 2" minimum words:','100','150','250','300','C'),
    mc(20,'"Inference" in reading means:','reading every word','understanding implied meaning','summarising','translating','B'),
    tf(21,'"Mustn\'t" and "don\'t have to" have the same meaning.','false'),
    tf(22,'Non-defining relative clauses use commas and cannot use "that".','true'),
    tf(23,'"Fewer" is used with countable nouns.','true'),
    fb(24,'She ___ (work, PP Cont.) on this for two years. The policy ___ (affect) the results.','has been working, affected'),
    fb(25,'If they ___ (replicate, 3rd cond.), they ___ (confirm) the findings. She ___ (should have) disclosed the data.','had replicated, would have confirmed, should have'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'2dcca104-ef48-4732-b664-9917a4c01043',n:16,title:'Reading Skills'},
    {id:'2a40dd70-adb3-44f5-b3e3-6d662663d737',n:17,title:'Writing Skills'},
    {id:'e590f07d-1637-4441-a560-f39abdd39cd7',n:18,title:'Listening Skills'},
    {id:'2388eecd-f1bf-4c21-9900-2288c748e62f',n:19,title:'Communication Skills'},
    {id:'c3c84e86-aa12-48d1-a3fe-e415bcfd8f48',n:20,title:'The Final Mile'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 B1 — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 16–20 B1 Intermediate`)
}
main().catch(e=>{console.error(e);process.exit(1)})
