import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 13: Mysteries & Progress ─────────────────────────────────────────

'212569b3-297b-48f7-b6c3-5248c8b0c918':{pass_threshold:70,questions:[
  mc(1,'"Might" for speculation about the present means:','certainty','logical impossibility','a past deduction','possibility (maybe true)','D'),
  mc(2,'Complete: "She ___ be at the library — her bag is still here."','must not','can\'t','could','might','D'),
  mc(3,'Complete: "It ___ be true — I saw it happen myself." (certainty)','might','could','must','can\'t','C'),
  mc(4,'Complete: "He ___ have taken the money — he was at work all day." (impossibility)','must','might','can\'t','could','C'),
  mc(5,'Which modal expresses a DEDUCTION (strong probability)?','might','could','may','must','D'),
  mc(6,'"Enigmatic" means:','straightforward and obvious','mysterious and difficult to understand','boring and predictable','well-explained','B'),
  mc(7,'Complete: "The cause of the phenomenon ___ (remain) unknown to this day."','remained','remains','is remaining','had remained','B'),
  mc(8,'"Shrouded in mystery" means:','completely understood','surrounded by secrecy and mystery','fully explained','well-documented','B'),
  mc(9,'"Speculate" means:','to confirm a fact','to refuse to comment','to form a theory without firm evidence','to prove conclusively','C'),
  mc(10,'"Inconclusive" evidence means:','very strong evidence','evidence that proves guilt','evidence that does not lead to a clear conclusion','easily interpretable data','C'),
  tf(11,'"Must" for deduction expresses logical certainty based on evidence.','true'),
  tf(12,'"Can\'t have done" expresses certainty that something was impossible in the past.','true'),
  tf(13,'"Might" expresses more certainty than "must" when speculating.','false'),
  fb(14,'The disappearance ___ (remains) one of the greatest unsolved mysteries.','remains'),
  fb(15,'She ___ (must have taken) a different route — she arrived 30 minutes early.','must have taken'),
]},

'd204d330-11f4-43c3-bb91-eef4c6f5a878':{pass_threshold:70,questions:[
  mc(1,'"Breakthrough" in science means:','a failed experiment','a significant discovery or achievement','a minor improvement','a theoretical debate','B'),
  mc(2,'Complete: "___ (conduct) research into the cause of the disease."','Researchers are conducting','Research is conducting','Researchers conduct','Research conducts','A'),
  mc(3,'"Empirical" evidence is based on:','theory alone','assumption','observation and experience rather than theory','speculation','C'),
  mc(4,'Complete: "The data ___ (analyze) by the research team over six months."','was analyzed','were analyzed','is analyzing','analyzed','B'),
  mc(5,'"Hypothesis" is:','a proven theory','a set of results','a tentative explanation to be tested','a published conclusion','C'),
  mc(6,'Complete: "The study ___ (aim) to identify the key risk factors."','aims','aimed','is aiming','aiming','B'),
  mc(7,'"Peer review" in academia means:','reviewing your own work','a process where other experts evaluate a study before publication','a student evaluation','a government audit','B'),
  mc(8,'Complete: "Significant ___ (advance) have been made in artificial intelligence."','advance','advances','advancing','advanced','B'),
  mc(9,'"Pioneering" research means:','following established methods','being the first to explore a new area','replicating previous studies','disproving old theories','B'),
  mc(10,'Complete: "Further research is needed to ___ (substantiate) these preliminary findings."','substantiating','substantiated','substantiate','substantiation','C'),
  tf(11,'"Empirical" evidence is based on theoretical reasoning only.','false'),
  tf(12,'"Peer review" is a quality control process in academic publishing.','true'),
  tf(13,'A "hypothesis" is a proven and accepted explanation.','false'),
  fb(14,'The team ___ (conducted) three years of research before publishing their results.','conducted'),
  fb(15,'The ___ (breakthrough) in quantum computing could revolutionize data processing.','breakthrough'),
]},

'261df6fd-dd24-4aea-9266-98580bf105ca':{pass_threshold:70,questions:[
  mc(1,'Complete: "make ___."','progress','progressing','progressed','progressively','A'),
  mc(2,'Complete: "achieve ___."','development','develop','developing','developed','A'),
  mc(3,'Complete: "___ a milestone."','make','reach','do','get','B'),
  mc(4,'Complete: "foster ___."','innovation','innovating','innovative','innovated','A'),
  mc(5,'Complete: "drive ___."','growth','growing','grew','grown','A'),
  mc(6,'Complete: "sustainable ___."','develop','developing','development','developer','C'),
  mc(7,'"Exponential growth" means:','slow, steady growth','rapid increase that accelerates over time','declining output','flat growth','B'),
  mc(8,'Complete: "The project ___ (undergo) significant changes in its final phase."','underwent','undergoes','undergoing','has undergo','A'),
  mc(9,'"State-of-the-art" means:','outdated','experimental','using the most advanced technology currently available','historical','C'),
  mc(10,'Complete: "The initiative ___ (aim) to bridge the digital divide."','aimed','aims','is aiming','aiming','B'),
  tf(11,'"Make progress" is a standard collocation in English.','true'),
  tf(12,'"State-of-the-art" has a negative connotation.','false'),
  tf(13,'"Exponential growth" means linear, steady growth.','false'),
  fb(14,'The company ___ (reached) a major milestone with the launch of its 10th product.','reached'),
  fb(15,'Sustainable ___ (development) is a key goal of the United Nations.','development'),
]},

'cdca87e8-c872-49bf-91fb-39628c3b784b':{pass_threshold:70,questions:[
  mc(1,'Critical thinking involves:','accepting all information as true','evaluating evidence and arguments before forming a conclusion','believing whatever you read first','avoiding complex questions','B'),
  mc(2,'"Corroborate" means:','to contradict','to disprove','to ignore','to confirm or support with additional evidence','D'),
  mc(3,'"Bias" in media or research means:','objectivity and balance','a tendency to favor one side unfairly','accuracy and precision','neutral reporting','B'),
  mc(4,'Complete: "The article ___ (fail) to provide sufficient evidence for its claims."','fail','failing','failed','fails','D'),
  mc(5,'"Anecdotal evidence" is:','statistically significant data','peer-reviewed research','based on personal accounts rather than systematic research','a government report','C'),
  mc(6,'"Credible" source is one that is:','entertaining','widely shared on social media','reliable and trustworthy','new and unpublished','C'),
  mc(7,'Complete: "We must ___ (distinguish) between correlation and causation."','distinguishing','distinguished','distinction','distinguish','D'),
  mc(8,'"Correlation" vs "causation": which is correct?','Correlation = one thing causes another','Causation = two things happen together but one doesn\'t cause the other','Correlation = two things occur together; causation = one directly causes the other','They mean the same thing','C'),
  mc(9,'"Fallacy" means:','a correct argument','a mistaken belief or faulty reasoning','a proven fact','a logical conclusion','B'),
  mc(10,'Complete: "The argument ___ (contain) several logical fallacies."','contains','containing','contained','contain','A'),
  tf(11,'"Anecdotal evidence" is the strongest form of scientific evidence.','false'),
  tf(12,'"Correlation does not imply causation" is a fundamental principle in statistics.','true'),
  tf(13,'"Bias" means treating all sides equally.','false'),
  fb(14,'Critical thinkers always ___ (evaluate) sources before accepting claims as true.','evaluate'),
  fb(15,'The study\'s ___ (findings) were corroborated by three independent research teams.','findings'),
]},

'5abd8d77-9ac5-4106-8cd3-fc3d042688b3':{pass_threshold:70,questions:[
  mc(1,'"Hedging language" in academic writing is used to:','make strong claims','avoid expressing any opinion','show certainty about everything','express caution or uncertainty about claims','D'),
  mc(2,'Which phrase is a HEDGE?','It definitely proves that...','It is certain that...','It could be argued that...','This conclusively demonstrates...','C'),
  mc(3,'Complete: "___ suggests that the trend may continue."','Definite evidence','Some evidence','All data','The proof','B'),
  mc(4,'"Tentative" language means:','confident and assertive','cautious and uncertain','aggressive and direct','ironic and sarcastic','B'),
  mc(5,'Which phrase avoids overstating a claim?','Always, without exception...','In many cases...','It is absolutely certain that...','Everyone agrees that...','B'),
  mc(6,'"Apparently" is used to:','state a confirmed fact','suggest something seems to be the case but may not be certain','exaggerate a claim','contradict a statement','B'),
  mc(7,'Complete: "The evidence ___ (seem) to support this theory, although further study is needed."','seem','seems','seemed','seeming','B'),
  mc(8,'Which is NOT a hedging device?','it appears that','it is universally proven','it would seem that','there is some evidence to suggest','B'),
  mc(9,'"It is widely believed that..." indicates:','personal certainty','a universal law','a hedged statement reflecting general opinion','a scientific fact','C'),
  mc(10,'"Conspiracy theory" typically lacks:','popular appeal','social media coverage','verified evidence and credible sources','emotional impact','C'),
  tf(11,'Hedging language makes academic writing appear more objective and cautious.','true'),
  tf(12,'"It is absolutely certain" is an example of hedging language.','false'),
  tf(13,'"Apparently" can be used to hedge a claim.','true'),
  fb(14,'It ___ (would seem) that the original data had been misinterpreted.','would seem'),
  fb(15,'The results ___ (suggest) a possible link between diet and cognitive performance.','suggest'),
]},

'924a470c-5853-40c1-aa71-fa3aacb22fc4':{pass_threshold:70,questions:[
  mc(1,'Complete: "Artificial intelligence is ___ to transform every sector of the economy."','expecting','likely','expected','expect','C'),
  mc(2,'Which modal is used for PREDICTIONS in formal writing?','must','will / is likely to / is predicted to','shall','could to','B'),
  mc(3,'"Autonomous vehicles" refers to:','electric cars','self-driving cars','public transport','high-speed trains','B'),
  mc(4,'Complete: "By 2050, renewable energy ___ have replaced fossil fuels." (future perfect prediction)','will','shall','should','would','A'),
  mc(5,'"Exponential" technological progress means:','slow and steady','increasingly rapid acceleration','gradual decline','plateau of growth','B'),
  mc(6,'Complete: "Machine learning algorithms ___ (become) more sophisticated each year."','become','became','are becoming','will becoming','C'),
  mc(7,'"Disruption" in technology means:','gradual, minor improvement','a radical change that overturns existing systems','a technical failure','a regulatory policy','B'),
  mc(8,'Complete: "It is ___ (predict) that global temperatures will rise by 2°C by 2100."','predicting','predict','predicted','prediction','C'),
  mc(9,'"Bioethics" deals with:','environmental policy','financial technology','ethical issues arising from biological and medical research','computer programming ethics','C'),
  mc(10,'Complete: "The development of ___ (gene/genes/genetic/genetics) editing raises serious ethical questions."','gene','genes','genetics','genetic','D'),
  tf(11,'"Will" is the only future form used in formal predictions.','false'),
  tf(12,'"Autonomous" means self-governing or self-operating.','true'),
  tf(13,'"Disruption" in technology always has a negative meaning.','false'),
  fb(14,'Experts ___ (predict) that quantum computers will outperform classical ones within a decade.','predict'),
  fb(15,'The ___ (exponential) growth of AI capabilities presents both opportunities and risks.','exponential'),
]},

'ebaa440f-1463-494e-a7e5-4bb32e5ca498':{pass_threshold:70,questions:[
  mc(1,'"Innovation" means:','copying existing methods','introducing new ideas or methods','following traditional approaches','improving marginally','B'),
  mc(2,'Complete: "The company ___ (pioneer) the use of blockchain in supply chain management."','pioneered','pioneers','is pioneering','A and C are correct','D'),
  mc(3,'"Disruptive innovation" refers to:','small, incremental improvements','innovation that replaces existing products/services or creates new markets','failed innovation','government-led innovation','B'),
  mc(4,'Complete: "She ___ (come up with) a revolutionary solution to the problem."','comes up with','came up with','come up with','coming up with','B'),
  mc(5,'"Scalable" technology means:','technology that only works at small scale','technology that can grow and handle increasing demand','expensive technology','obsolete technology','B'),
  mc(6,'"Iterate" in product development means:','to launch and never change','to repeat and refine a process through multiple cycles','to completely abandon a project','to copy a competitor','B'),
  mc(7,'Complete: "Their innovative approach ___ (revolutionize) the industry."','revolutionized','revolutionizes','is revolutionizing','A and C are correct','D'),
  mc(8,'"Prototype" is:','a final product','a mass-produced item','an early version of a product used for testing','a marketing strategy','C'),
  mc(9,'"R&D" stands for:','Revenue and Distribution','Regulation and Design','Research and Development','Risk and Delivery','C'),
  mc(10,'Complete: "The startup ___ (secure) $10 million in funding for their next phase."','secures','secured','securing','secure','B'),
  tf(11,'"Prototype" refers to the final, market-ready version of a product.','false'),
  tf(12,'"Iterate" means to test and refine through repeated cycles.','true'),
  tf(13,'"R&D" stands for Research and Development.','true'),
  fb(14,'The team ___ (came up with) an innovative solution to reduce energy consumption.','came up with'),
  fb(15,'Their technology ___ (revolutionized) the way medical diagnoses are made.','revolutionized'),
]},

'dea01a1b-c5d5-49a1-a971-cdcc46b5b223':{pass_threshold:80,questions:[
  mc(1,'Speculation: "She ___ be at home — the lights are on."','can\'t','won\'t','must','might','C'),
  mc(2,'"Empirical" evidence is based on:','theory and assumption','peer review only','observation and experiment','speculation','C'),
  mc(3,'"Hedging" language serves to:','strengthen claims to certainty','make writing more conversational','avoid overstating claims','add emphasis','C'),
  mc(4,'Which is a HEDGE?','It is absolutely certain that...','It is universally agreed...','It could be argued that...','The data conclusively proves...','C'),
  mc(5,'"Corroborate" means:','to disprove','to suggest','to contradict','to confirm with additional evidence','D'),
  mc(6,'"Correlation does not imply causation" means:','two related events share a cause','two things happening together proves one caused the other','two things occurring together does not mean one causes the other','correlated data is unreliable','C'),
  mc(7,'Complete: "make ___."','progress','progressing','progressive','progressively','A'),
  mc(8,'"Exponential growth" means:','linear increase','gradual steady growth','increasingly rapid acceleration','declining trend','C'),
  mc(9,'"Disruptive innovation" refers to:','incremental improvement','innovation that overturns existing markets','failed innovation','government regulation','B'),
  mc(10,'"Prototype" is:','a final product','an early test version of a product','a mass-produced item','a patent','B'),
  mc(11,'Complete: "The findings ___ (suggest) a possible link." (hedged)','suggested','suggest','suggesting','suggests','B'),
  mc(12,'"Breakthrough" means:','a minor improvement','a significant new discovery or achievement','a theoretical debate','a failed experiment','B'),
  mc(13,'Complete: "It is ___ (predict) that AI will transform healthcare."','predicting','prediction','predict','predicted','D'),
  mc(14,'"Enigmatic" means:','clear and obvious','mysterious and hard to understand','boring','well-explained','B'),
  mc(15,'Complete: "The startup ___ (secure) funding from three major investors."','secures','securing','secured','secure','C'),
  tf(16,'"Anecdotal evidence" is the most reliable form of scientific evidence.','false'),
  tf(17,'"Peer review" is a quality control process in academic publishing.','true'),
  tf(18,'"Disruption" in technology always has a negative meaning.','false'),
  fb(19,'It ___ (would seem) that the original hypothesis was flawed.','would seem'),
  fb(20,'The team ___ (came up with) a scalable solution to the water crisis.','came up with'),
]},

// ── MODULE 14: Food & Home ───────────────────────────────────────────────────

'ac53a20b-f123-4948-9791-58d549ea7ebd':{pass_threshold:70,questions:[
  mc(1,'"Gastronomy" refers to:','fast food culture','cooking for large groups','the art and science of food and cooking','food packaging','B'),
  mc(2,'Complete: "___ (palate/palette/pallet) refers to a person\'s sense of taste."','palette','pallet','palate','palatine','C'),
  mc(3,'"Fusion cuisine" combines:','traditional methods from one culture','ingredients and techniques from different culinary traditions','only vegetarian dishes','only French cooking','B'),
  mc(4,'Complete: "The dish has a ___ (robust/robustly/robustness) flavor profile."','robustly','robustness','robuster','robust','D'),
  mc(5,'"Umami" is described as:','sweet taste','sour taste','a savory, meaty taste (5th basic taste)','bitter taste','C'),
  mc(6,'Complete: "The chef ___ (garnish) the plate with fresh herbs."','garnitures','garnished','garnishing','garnish','B'),
  mc(7,'"Artisanal" food is produced by:','large factories','machines only','a skilled craftsperson using traditional methods','imported from abroad','C'),
  mc(8,'Complete: "The dish ___ (pair) well with a full-bodied red wine."','pair','pairing','paired','pairs','D'),
  mc(9,'"Culinary heritage" means:','modern food trends','fast food culture','the traditional foods and cooking practices of a culture','international cuisine','C'),
  mc(10,'Complete: "She has a very ___ (discern/discerning/discernment/discerned) palate."','discern','discernment','discerned','discerning','D'),
  tf(11,'"Umami" is considered the fifth basic taste.','true'),
  tf(12,'"Artisanal" food is typically mass-produced.','false'),
  tf(13,'"Fusion cuisine" involves combining elements from different food cultures.','true'),
  fb(14,'The restaurant is known for its innovative ___ (cuisine) blending Asian and European flavors.','cuisine'),
  fb(15,'She has a very refined ___ (palate) and can detect subtle differences in flavor.','palate'),
]},

'46270fb2-7885-40a4-9629-8cc220ee6c3f':{pass_threshold:70,questions:[
  mc(1,'To "sauté" means:','to cook slowly in liquid','to bake in an oven','to fry quickly in a small amount of oil','to steam','C'),
  mc(2,'To "braise" means:','to fry at high heat','to grill on open flame','to cook slowly in liquid at low temperature','to deep-fry','C'),
  mc(3,'To "blanch" means:','to season heavily','to briefly boil and then cool in cold water','to smoke over wood','to roast at high heat','B'),
  mc(4,'Complete: "The vegetables were ___ (steam/steamed/steaming) for five minutes."','steam','steaming','steams','steamed','D'),
  mc(5,'To "marinade" means:','to cook in oil','to dry out using salt','to soak in a seasoned liquid before cooking','to bake with butter','C'),
  mc(6,'Complete: "___ (simmer/simmering/simmers/simmered) the sauce for 20 minutes over low heat."','Simmering','Simmers','Simmered','Simmer','D'),
  mc(7,'"Caramelize" means:','to add caramel sauce','to heat sugar until it turns brown and sweet','to coat food in chocolate','to add cream','B'),
  mc(8,'To "reduce" a sauce means:','to add more liquid','to thicken it by boiling off liquid','to freeze it','to strain it','B'),
  mc(9,'"Al dente" in pasta cooking means:','overcooked and soft','cooked firmly so it still has a slight bite','raw and uncooked','cooked in sauce','B'),
  mc(10,'Complete: "The recipe calls for the onions to be ___ (finely chop/finely chopped/fine chop)."','finely chop','fine chop','fine chopped','finely chopped','D'),
  tf(11,'"Blanching" involves briefly boiling and then immediately cooling in ice water.','true'),
  tf(12,'"Al dente" means pasta should be fully soft and mushy.','false'),
  tf(13,'"Braising" involves cooking food slowly in liquid at low temperature.','true'),
  fb(14,'Sauté the garlic until ___ (golden) before adding the tomatoes.','golden'),
  fb(15,'The sauce was ___ (reduced) by half to intensify the flavor.','reduced'),
]},

'd2cb8d26-3fd1-48c5-b90c-dbb749b4b791':{pass_threshold:70,questions:[
  mc(1,'"Feel at home" means:','to feel confused','to feel comfortable and relaxed in a place','to be homesick','to want to leave','B'),
  mc(2,'"Home is where the heart is" means:','your physical house is most important','home is wherever you feel loved and happy','you must own a house','home is always in the countryside','B'),
  mc(3,'"Open house" means:','a house with no walls','a house for sale','a social event where many people are invited to visit','a temporary shelter','C'),
  mc(4,'"Make yourself at home" means:','please clean the house','be comfortable and relaxed as if it were your own home','make improvements to the house','move in permanently','B'),
  mc(5,'"Hit the roof" means:','to repair a roof','to become very angry','to rise quickly','to find something at the top','B'),
  mc(6,'"Bring the house down" in performance means:','damage the theatre','to get a very enthusiastic response from the audience','to clear the venue','to start a fire','B'),
  mc(7,'"On the house" means:','something must be paid for','something structural','free of charge (provided by the establishment)','referring to home-based work','C'),
  mc(8,'"Safe as houses" means:','a house is for sale','very unstable','temporarily secure','completely safe and secure','D'),
  mc(9,'"Put your house in order" means:','to tidy up physically','to organize your own affairs before criticizing others','to sell your house','to invite guests','B'),
  mc(10,'"Home stretch" means:','the beginning of a task','the middle section','the final stage of a task or journey','a long delay','C'),
  tf(11,'"On the house" means the customer must pay extra.','false'),
  tf(12,'"Hit the roof" is an idiom for becoming very angry.','true'),
  tf(13,'"Bring the house down" refers to physical destruction of a building.','false'),
  fb(14,'The comedian ___ (brought the house down) with his final joke.','brought the house down'),
  fb(15,'We\'re in the ___ (home stretch) — just one more chapter to finish.','home stretch'),
]},

'7d2c0296-2f2f-4b29-8a81-19f28a0f1533':{pass_threshold:70,questions:[
  mc(1,'"Minimalist" design style features:','many decorative objects','bright contrasting colors','very few, simple elements','traditional ornate patterns','C'),
  mc(2,'Complete: "The apartment has a ___ (airy/airily/airiness) open-plan layout."','airily','airiness','airies','airy','D'),
  mc(3,'"Feng shui" is:','a type of furniture','a Chinese system of arranging space to promote harmony and well-being','a cleaning technique','a type of architecture','B'),
  mc(4,'Complete: "The room was ___ (furnish) in a Scandinavian style."','furnishes','furnishing','furnish','furnished','D'),
  mc(5,'"Ergonomic" design prioritizes:','visual beauty','low cost','historical accuracy','comfort and efficiency for the user','D'),
  mc(6,'Complete: "Natural light ___ (flood) the open-plan living area."','floods','flooded','is flooding','A and C are correct','D'),
  mc(7,'"Bespoke" furniture is:','mass-produced','flat-pack','custom-made to specific requirements','vintage and antique','C'),
  mc(8,'Complete: "The architect incorporated ___ (sustainable/sustainably/sustainability) materials throughout the build."','sustainably','sustainability','sustaining','sustainable','D'),
  mc(9,'"Neutral palette" in interior design refers to:','bright, bold colors','a range of soft, understated colors (white, beige, grey)','primary colors only','black and white only','B'),
  mc(10,'Complete: "The ___ (focal/focus/focused/focusing) point of the room is the fireplace."','focus','focused','focusing','focal','D'),
  tf(11,'"Bespoke" items are made to individual specifications.','true'),
  tf(12,'"Minimalist" design features many decorative objects.','false'),
  tf(13,'"Ergonomic" design focuses primarily on aesthetic appeal.','false'),
  fb(14,'The designer chose a ___ (neutral) palette to make the space feel calm and spacious.','neutral'),
  fb(15,'The room was ___ (furnished) with bespoke pieces crafted by local artisans.','furnished'),
]},

'7384052e-bb4a-4efd-8af1-76435171fc53':{pass_threshold:70,questions:[
  mc(1,'Past Perfect is used in nostalgia narratives to:','describe ongoing past actions','show what existed before the present story time','express current feelings','describe future plans','B'),
  mc(2,'Complete: "The house ___ (stand) in the same spot for over a century."','stands','stood','had stood','has stood','C'),
  mc(3,'"Nostalgia" means:','hope for the future','a sentimental longing for the past','indifference to the past','regret about the future','B'),
  mc(4,'Complete: "She vividly ___ (remember) the smell of her grandmother\'s kitchen."','remembers','remembered','has remembered','is remembering','B'),
  mc(5,'"Evocative" means:','forgettable','bringing strong memories or feelings to mind','logical and analytical','futuristic','B'),
  mc(6,'Complete: "Those ___ (be) simpler times."','are','were','have been','had been','B'),
  mc(7,'"Bittersweet" means:','completely happy','completely sad','painful and pleasant at the same time','neither happy nor sad','C'),
  mc(8,'Complete: "She ___ (cherish) the memories of her childhood home."','cherishes','cherished','has cherished','A and B are correct','D'),
  mc(9,'"Reminisce" means:','to forget the past','to plan for the future','to think and talk fondly about past experiences','to regret past decisions','C'),
  mc(10,'Complete: "The photograph ___ (transport) her back to her childhood."','transports','transported','was transporting','has transported','B'),
  tf(11,'"Nostalgia" has a purely negative connotation.','false'),
  tf(12,'"Bittersweet" emotions combine both happy and sad elements.','true'),
  tf(13,'"Reminisce" means to plan and prepare for the future.','false'),
  fb(14,'She ___ (cherished) the bittersweet memories of her years abroad.','cherished'),
  fb(15,'The old song was deeply ___ (evocative) of summer evenings in her childhood garden.','evocative'),
]},

'f66d762d-b58a-4261-97ec-0f26983e647d':{pass_threshold:70,questions:[
  mc(1,'Which is the most formal way to decline an invitation?','Can\'t make it.','I\'m afraid I\'m unable to attend.','Not coming.','Busy that day.','B'),
  mc(2,'Correct table manners: when should you begin eating?','Immediately when served','After the host has begun','Before the host sits down','Whenever you feel like it','B'),
  mc(3,'Complete: "It is ___ (consider/considered/considering) impolite to speak with your mouth full."','consider','considering','considers','considered','D'),
  mc(4,'"RSVP" in formal invitations stands for:','Respond if you can','A French phrase meaning "please reply"','Return seats, verify presence','Required social venue policy','B'),
  mc(5,'Which phrase appropriately thanks a host?','Food was OK.','Thank you so much for a wonderful evening.','Not bad.','It was fine.','B'),
  mc(6,'Complete: "It is customary to ___ (bring) a gift when visiting someone\'s home."','bringing','brought','brings','bring','D'),
  mc(7,'"Faux pas" means:','a French dish','a social blunder or embarrassing mistake','a formal greeting','an elegant gesture','B'),
  mc(8,'Complete: "In many cultures, ___ (punctuality/punctual/punctually/punctuate) is considered a sign of respect."','punctual','punctually','punctuate','punctuality','D'),
  mc(9,'Which is appropriate in formal dining?','Using your phone at the table','Elbows on the table','Waiting for everyone to be served before eating','Eating with your hands','C'),
  mc(10,'"Small talk" in formal settings typically avoids:','weather','travel','personal finances and controversial topics','local events','C'),
  tf(11,'"Faux pas" refers to a social blunder.','true'),
  tf(12,'"RSVP" means you only need to reply if you are NOT attending.','false'),
  tf(13,'In most Western formal dining settings, you should wait until the host begins eating.','true'),
  fb(14,'She committed a serious ___ (faux pas) by discussing politics at the dinner table.','faux pas'),
  fb(15,'It is considered polite to ___ (RSVP) promptly to formal invitations.','RSVP'),
]},

'a478b4ce-f50b-4d4b-8655-bdf3cc224569':{pass_threshold:70,questions:[
  mc(1,'"Staple food" means:','a luxury ingredient','a rare delicacy','a food eaten regularly and in large quantities in a particular culture','a fast food item','C'),
  mc(2,'Complete: "Rice is a ___ (staple/stable/stale) food in most Asian cuisines."','stable','stale','stapling','staple','D'),
  mc(3,'"Street food" refers to:','food sold in supermarkets','food prepared and sold by vendors in public places','gourmet restaurant food','home-cooked meals','B'),
  mc(4,'"Delicacy" means:','common everyday food','a type of cooking method','a choice or expensive food considered rare or special','inexpensive street food','C'),
  mc(5,'Complete: "Sushi has become a ___ (global/globe/globally/globalized) phenomenon."','globe','globally','globalized','global','D'),
  mc(6,'"Fermented" foods include:','raw salads','yogurt, kimchi, and sauerkraut','grilled meats','baked bread only','B'),
  mc(7,'Complete: "The dish is ___ (season) with aromatic spices and fresh herbs."','seasoning','seasoned','seasons','season','B'),
  mc(8,'"Food sovereignty" means:','the right of nations to define their own food systems and policies','international food trade','food quality control','dietary restriction','A'),
  mc(9,'Complete: "Many dishes reflect the ___ (culinary/culinarily/cuisine/culinary heritage) of the region."','culinarily','cuisine','culinary heritage','culinary','C'),
  mc(10,'"Sustainable" food choices include:','buying heavily packaged foods','consuming seasonal and locally sourced produce','eating only imported foods','choosing convenience foods always','B'),
  tf(11,'"Staple food" refers to a luxury item eaten rarely.','false'),
  tf(12,'"Fermentation" is a food preservation technique used across many cultures.','true'),
  tf(13,'"Street food" is always considered lower quality than restaurant food.','false'),
  fb(14,'Kimchi is a ___ (fermented) Korean dish that has gained worldwide popularity.','fermented'),
  fb(15,'Eating ___ (seasonal) and locally sourced food reduces your carbon footprint.','seasonal'),
]},

'5716d7ce-78fb-46e8-9bc3-0910db08c6ed':{pass_threshold:80,questions:[
  mc(1,'To "sauté" means to:','cook slowly in liquid','bake in an oven','boil briefly','fry quickly in a small amount of oil','D'),
  mc(2,'"Al dente" means pasta is:','overcooked','cooked firmly with a slight bite','raw and uncooked','cooked in sauce only','B'),
  mc(3,'"Bring the house down" (idiom) means:','damage a building','to get an extremely enthusiastic audience response','to demolish something','to make everyone angry','B'),
  mc(4,'"On the house" means:','a structural feature','to pay extra','to work from home','free of charge','D'),
  mc(5,'"Minimalist" design features:','many decorative objects','bright colors','very few, simple elements','traditional patterns','C'),
  mc(6,'"Bespoke" furniture is:','mass-produced','custom-made','flat-pack','antique','B'),
  mc(7,'"Nostalgia" is:','fear of the future','hatred of the past','a sentimental longing for the past','indifference to memories','C'),
  mc(8,'"Bittersweet" memories are:','purely positive','completely negative','painful and pleasant simultaneously','emotionally neutral','C'),
  mc(9,'"Faux pas" means:','a French dish','an elegant gesture','a formal greeting','an embarrassing social blunder','D'),
  mc(10,'"RSVP" means:','Respond if you can\'t attend','A French phrase: please reply','Required standard venue policy','Return seats, verify presence','B'),
  mc(11,'"Staple food" is:','a luxury delicacy','imported exotic food','a food eaten regularly in large quantities','street food','C'),
  mc(12,'"Culinary heritage" refers to:','fast food culture','modern food trends','the traditional foods and cooking practices of a culture','international restaurant chains','C'),
  mc(13,'Complete: "She has a refined ___ (palate)."','palette','pallet','palatine','palate','D'),
  mc(14,'"Ergonomic" design prioritizes:','visual beauty','low cost','historical accuracy','comfort and efficiency for the user','D'),
  mc(15,'Complete: "___ a risk." (collocate correctly)','make','do','take','get','C'),
  tf(16,'"Artisanal" products are handcrafted using traditional methods.','true'),
  tf(17,'"Blanching" involves cooking food for a long time in boiling water.','false'),
  tf(18,'"Reminisce" means to think and talk fondly about past experiences.','true'),
  fb(19,'The comedian ___ (brought the house down) with her final performance.','brought the house down'),
  fb(20,'The dish is ___ (seasoned) with a blend of aromatic spices from Southeast Asia.','seasoned'),
]},

// ── MODULE 15: Phrasal Verbs & Idioms ───────────────────────────────────────

'67a5038d-1365-4e16-83e5-ca4b3f9ff8e5':{pass_threshold:70,questions:[
  mc(1,'"Get away with" means:','to escape punishment for doing something wrong','to travel far away','to avoid a difficult task','to disagree strongly','A'),
  mc(2,'"Get over" means:','to cross an obstacle','to begin again','to become angry','to recover from something (illness, shock, relationship)','D'),
  mc(3,'"Get round to" means:','to avoid something','to travel around','to finally find time to do something','to get physical exercise','C'),
  mc(4,'"Take off" (business/flight) means:','to land','to become very successful or to depart by air','to fail quickly','to reduce gradually','B'),
  mc(5,'"Take on" means:','to give up','to accept extra work, responsibility, or employees','to finish a task','to reject an offer','B'),
  mc(6,'"Take up" means:','to give back','to end an activity','to start a new hobby or occupation','to take something illegally','C'),
  mc(7,'"Put off" means:','to encourage someone','to postpone or to cause someone to dislike something','to start immediately','to improve a situation','B'),
  mc(8,'"Put up with" means:','to enjoy something','to encourage someone','to build something','to tolerate something unpleasant','D'),
  mc(9,'"Put forward" means:','to suggest or propose an idea','to delay','to dismiss an idea','to ask for help','A'),
  mc(10,'Complete: "She ___ (put off) her dentist appointment for the third time."','put away','put forward','put off','put up','C'),
  tf(11,'"Get away with" means to escape without punishment.','true'),
  tf(12,'"Take off" (of a business) means it starts to fail.','false'),
  tf(13,'"Put up with" means to tolerate something unpleasant.','true'),
  fb(14,'She finally ___ (got round to) replying to her emails.','got round to'),
  fb(15,'He ___ (took on) too many projects and ended up exhausted.','took on'),
]},

'108f1ece-8eb6-4629-93b2-99cef93acba2':{pass_threshold:70,questions:[
  mc(1,'"Come across" means:','to lose something','to cross a bridge','to find or meet by chance','to come back','C'),
  mc(2,'"Come up with" means:','to fail to produce an idea','to arrive late','to produce an idea or solution','to go up quickly','C'),
  mc(3,'"Come round" (opinion) means:','to visit briefly','to faint','to regain consciousness','to gradually change your opinion','D'),
  mc(4,'"Go off" (food) means:','to become popular','to go abroad','to make a loud noise or to go bad (food)','to improve greatly','C'),
  mc(5,'"Go through" means:','to travel abroad','to successfully complete or to experience something difficult','to abandon a plan','to go around something','B'),
  mc(6,'"Go over" means:','to cross a river','to exceed a limit','to review or examine something carefully','to travel to another country','C'),
  mc(7,'"Turn up" means:','to disappear','to decrease in volume','to arrive or appear unexpectedly','to rotate upwards','C'),
  mc(8,'"Turn down" means:','to accept an offer','to increase the volume','to reject an offer or to reduce volume','to turn something over','C'),
  mc(9,'"Turn into" means:','to rotate inward','to transform or change into something else','to enter a building','to return','B'),
  mc(10,'Complete: "She ___ (came across) an interesting article while researching."','went across','came across','went over','came over','B'),
  tf(11,'"Come up with" means to find or produce a new idea or solution.','true'),
  tf(12,'"Go off" only means to make a loud noise.','false'),
  tf(13,'"Turn down" can mean to reject an offer.','true'),
  fb(14,'The milk has ___ (gone off) — don\'t drink it.','gone off'),
  fb(15,'She ___ (turned down) the job offer because the salary was too low.','turned down'),
]},

'35029435-00ee-47f9-9906-d56e76d31460':{pass_threshold:70,questions:[
  mc(1,'"Look into" means:','to observe someone','to investigate or examine','to look upward','to ignore a problem','B'),
  mc(2,'"Look up to" means:','to search online','to physically look upward','to admire someone','to disrespect someone','C'),
  mc(3,'"Look after" means:','to search for something','to investigate','to take care of someone or something','to admire someone','C'),
  mc(4,'"Make up" (invent) means:','to apply cosmetics','to compensate for','to invent a story or excuse','to arrange a meeting','C'),
  mc(5,'"Make out" means:','to understand with difficulty or to see with difficulty','to give away','to finish quickly','to build something','A'),
  mc(6,'"Make up for" means:','to invent an excuse','to compensate for something lost or missed','to start over','to reduce','B'),
  mc(7,'"Give away" means:','to receive something for free','to give something for free or to reveal a secret','to borrow money','to increase an amount','B'),
  mc(8,'"Give up" means:','to start again','to succeed after difficulty','to donate','to stop trying or to surrender','D'),
  mc(9,'"Give in" means:','to donate money','to start an activity','to yield or surrender after resistance','to reject an offer','C'),
  mc(10,'Complete: "She ___ (looked into) the possibility of switching careers."','looked up','looked after','looked out','looked into','D'),
  tf(11,'"Look up to" means to admire someone.','true'),
  tf(12,'"Make up for" means to compensate for something.','true'),
  tf(13,'"Give in" and "give up" have exactly the same meaning.','false'),
  fb(14,'He finally ___ (gave in) and agreed to their terms after weeks of negotiation.','gave in'),
  fb(15,'She ___ (looks up to) her mentor and values her advice greatly.','looks up to'),
]},

'6c412e9a-c3c8-41ee-a5d7-0facac17c969':{pass_threshold:70,questions:[
  mc(1,'"Wear your heart on your sleeve" means:','to hide your feelings','to be fashionable','to express your emotions openly','to avoid emotional topics','C'),
  mc(2,'"Drive someone up the wall" means:','to help someone travel','to provide transport','to inspire someone','to greatly annoy someone','D'),
  mc(3,'"See eye to eye" means:','to maintain eye contact','to disagree strongly','to have good eyesight','to agree completely','D'),
  mc(4,'"Go through thick and thin" means:','to have a varied diet','to travel frequently','to stay together through good and bad times','to change frequently','C'),
  mc(5,'"Fall out" means:','to fall from a height','to drop objects','to have an argument and become estranged','to fail an exam','C'),
  mc(6,'"Make up" (after argument) means:','to invent a story','to apply makeup','to reconcile after a disagreement','to create a plan','C'),
  mc(7,'"Keep someone at arm\'s length" means:','to keep someone physically close','to maintain emotional distance from someone','to stay in contact frequently','to offer help','B'),
  mc(8,'"Bear a grudge" means:','to forgive someone','to hold ongoing resentment toward someone','to help someone','to meet regularly','B'),
  mc(9,'"Patch things up" means:','to damage something','to repair a physical object','to mend a broken relationship','to avoid someone','C'),
  mc(10,'"On good terms" means:','in a formal relationship','having a good relationship without conflict','strangers to each other','in a legal dispute','B'),
  tf(11,'"Fall out" in relationships means to have an argument that causes estrangement.','true'),
  tf(12,'"Bury the hatchet" means to continue a conflict.','false'),
  tf(13,'"Bear a grudge" means to forgive someone willingly.','false'),
  fb(14,'After years of silence, the two sisters finally ___ (made up).','made up'),
  fb(15,'She ___ (bears a grudge) against her former employer for unfair dismissal.','bears a grudge'),
]},

'9aa87009-f795-4633-8fff-8ac064f2c8bf':{pass_threshold:70,questions:[
  mc(1,'"Cut corners" means:','to use scissors','to take a short route','to save money or effort by doing something hastily or improperly','to be very precise','C'),
  mc(2,'"Go the extra mile" means:','to travel farther than planned','to make additional effort beyond what is expected','to walk to work','to reduce effort','B'),
  mc(3,'"Back to the drawing board" means:','to draw pictures','to start a creative project','to start planning again from the beginning','to submit final work','C'),
  mc(4,'"The bottom line" means:','the last line of a text','the most important fact or financial result','the lowest price','a sports result','B'),
  mc(5,'"Get the ball rolling" means:','to play sports','to start an activity or process','to complicate things','to finish a task','B'),
  mc(6,'"In the red" (financially) means:','making a profit','breaking even','in debt or losing money','receiving a bonus','C'),
  mc(7,'"Think outside the box" means:','to use a physical box','to think in a conventional way','to approach a problem in a creative or unconventional way','to avoid thinking','C'),
  mc(8,'"Learn the ropes" means:','to learn sailing','to do physical training','to learn the basics of a job or activity','to be fired','C'),
  mc(9,'"Strike a deal" means:','to physically attack someone','to agree on and finalize an agreement','to fail a negotiation','to cancel a meeting','B'),
  mc(10,'"On the same page" means:','reading the same document','being in agreement and understanding the same thing','working on the same project','sitting together','B'),
  tf(11,'"Cut corners" implies doing something to the highest possible standard.','false'),
  tf(12,'"In the red" means a company is making a profit.','false'),
  tf(13,'"Think outside the box" means to approach problems creatively.','true'),
  fb(14,'After the project failed, they went ___ (back to the drawing board).','back to the drawing board'),
  fb(15,'The two companies finally ___ (struck a deal) after months of negotiation.','struck a deal'),
]},

'8fc87f5e-70c3-423e-9dab-d23cfced22d1':{pass_threshold:70,questions:[
  mc(1,'"Once in a blue moon" means:','frequently','regularly','very rarely','every month','C'),
  mc(2,'"At the eleventh hour" means:','at 11 o\'clock','at the very last moment','very early in the morning','in the middle of the day','B'),
  mc(3,'"The tip of the iceberg" means:','a small visible part of a much larger hidden problem','a complete picture','an obvious fact','a solved problem','A'),
  mc(4,'"Against the clock" means:','slowly and carefully','working under time pressure to meet a deadline','opposing time zone changes','ignoring a deadline','B'),
  mc(5,'"A blessing in disguise" means:','a hidden curse','something that seems bad but turns out to be good','a religious event','something very expensive','B'),
  mc(6,'"Bite the bullet" means:','to eat something hard','to be a coward','to endure a painful or difficult situation bravely','to make a quick decision','C'),
  mc(7,'"The ball is in your court" means:','a sports term only','it is now up to you to make a decision or take action','you won the game','you have no choice','B'),
  mc(8,'"Spill the beans" means:','to make a cooking mess','to reveal a secret unintentionally','to spread false information','to share good news','B'),
  mc(9,'"Under the weather" means:','during bad weather','outdoors','feeling slightly unwell','extremely ill','C'),
  mc(10,'"Every cloud has a silver lining" means:','all weather is temporary','every problem has a positive aspect','clouds contain precious metals','life is always positive','B'),
  tf(11,'"Once in a blue moon" means something happens very frequently.','false'),
  tf(12,'"The tip of the iceberg" refers to a small visible part of a larger hidden problem.','true'),
  tf(13,'"Bite the bullet" means to avoid a difficult situation.','false'),
  fb(14,'It was a ___ (blessing in disguise) — losing that job led to a much better opportunity.','blessing in disguise'),
  fb(15,'She only sees her family ___ (once in a blue moon) due to her demanding career.','once in a blue moon'),
]},

'2c656216-5eaa-4f4d-b314-526d06066eb0':{pass_threshold:70,questions:[
  mc(1,'"By and large" means:','in small quantities','in total','generally speaking, on the whole','definitely','C'),
  mc(2,'"For the time being" means:','permanently','for a very long time','for the foreseeable future','temporarily, for now','D'),
  mc(3,'"In the long run" means:','in a short time','after a long period of time','immediately','occasionally','B'),
  mc(4,'"On the whole" means:','entirely','specifically','rarely','generally, considering everything','D'),
  mc(5,'"As a matter of fact" means:','as a question','actually, in reality','perhaps','sometimes','B'),
  mc(6,'"In light of" means:','during daylight hours','considering or in view of','despite','after a long delay','B'),
  mc(7,'"To put it simply" is used to:','complicate an explanation','introduce a complex idea','restate something in simpler terms','avoid explaining','C'),
  mc(8,'"Needless to say" means:','it is necessary to explain','it should be said more carefully','this is obvious and therefore doesn\'t need to be mentioned','it is surprising','C'),
  mc(9,'"By no means" means:','definitely','absolutely not','sometimes','partially','B'),
  mc(10,'"In the meantime" means:','at the end','at the beginning','while something else is happening','after completion','C'),
  tf(11,'"By and large" means "on the whole" or "generally."','true'),
  tf(12,'"For the time being" means something is permanent.','false'),
  tf(13,'"In light of" means considering or taking into account.','true'),
  fb(14,'___ (By and large), the conference was a great success.','By and large'),
  fb(15,'___ (In the meantime), please complete the preliminary questionnaire.','In the meantime'),
]},

'9eb87a76-9cf5-447c-959f-5b41369b1b08':{pass_threshold:80,questions:[
  mc(1,'"Get away with" means:','to travel far','to escape punishment','to overcome a challenge','to avoid work','B'),
  mc(2,'"Put off" means:','to encourage','to start immediately','to dismiss','to postpone or to discourage','D'),
  mc(3,'"Come across" means:','to cross a river','to find or encounter by chance','to come back','to arrive late','B'),
  mc(4,'"Turn down" means:','to increase volume','to accept an offer','to reject an offer or to reduce volume','to turn something over','C'),
  mc(5,'"Give up" means:','to donate','to start again','to increase effort','to stop trying or surrender','D'),
  mc(6,'"Look into" means:','to look upward','to observe','to admire','to investigate','D'),
  mc(7,'"See eye to eye" means:','to maintain eye contact','to agree','to have good eyesight','to argue','B'),
  mc(8,'"Bear a grudge" means:','to forgive','to carry a heavy object','to start fresh','to hold ongoing resentment','D'),
  mc(9,'"Cut corners" means:','to be very precise','to use a short route','to do something hastily and improperly','to improve quality','C'),
  mc(10,'"Once in a blue moon" means:','frequently','never','monthly','very rarely','D'),
  mc(11,'"At the eleventh hour" means:','very early','at 11am exactly','after the deadline','at the very last moment','D'),
  mc(12,'"By and large" means:','entirely','partially','generally, on the whole','specifically','C'),
  mc(13,'"In light of" means:','despite the evidence','ignoring the facts','in view of / considering','after a delay','C'),
  mc(14,'"Make up for" means:','to invent a story','to apply cosmetics','to start again','to compensate for something','D'),
  mc(15,'"The ball is in your court" means:','a sports term only','you have no choice','it is now your turn to act or decide','the game is over','C'),
  tf(16,'"Bury the hatchet" means to reconcile after a conflict.','true'),
  tf(17,'"In the red" means making a profit.','false'),
  tf(18,'"A blessing in disguise" means something that seems bad but turns out to be good.','true'),
  fb(19,'She ___ (came across) a fascinating article about AI ethics.','came across'),
  fb(20,'After months of negotiation, they finally ___ (struck a deal).','struck a deal'),
]},

// ── MODULE 16: Word Formation Mastery ───────────────────────────────────────

'c81762ad-97e6-4ebb-9532-682092021a5d':{pass_threshold:70,questions:[
  mc(1,'The prefix "anti-" means:','in favor of','before','against or opposing','wrongly','C'),
  mc(2,'The prefix "inter-" means:','within','below','between or among','after','C'),
  mc(3,'The prefix "pre-" means:','again','not','after','before','D'),
  mc(4,'The prefix "post-" means:','before','within','against','after','D'),
  mc(5,'The prefix "semi-" means:','completely','half or partly','over','wrongly','B'),
  mc(6,'The prefix "hyper-" means:','under or below','normal','in favor of','over or excessively','D'),
  mc(7,'The prefix "sub-" means:','above','over','equal','under or below','D'),
  mc(8,'"Unprecedented" = un + precedent + ed. "Un-" here means:','again','excessively','before','not','D'),
  mc(9,'The prefix "trans-" means:','within','below','before','across or beyond','D'),
  mc(10,'Complete: "The government introduced ___ (counter/contra/anti) terrorism legislation."','contra','counter','counter/anti — both are possible','anti','C'),
  tf(11,'"Pre-" and "post-" are antonyms as prefixes.','true'),
  tf(12,'"Hyper-" means under or less than normal.','false'),
  tf(13,'"Inter-" means between or among (e.g., international = between nations).','true'),
  fb(14,'The new ___ (anti) -pollution measures were welcomed by environmental groups.','anti'),
  fb(15,'She works in ___ (inter) -cultural communication across multiple countries.','inter'),
]},

'bfb5bca6-1b26-4086-9ef8-ab2cfd6fcec9':{pass_threshold:70,questions:[
  mc(1,'The suffix "-tion/-sion" forms:','adjectives','adverbs','nouns','verbs','C'),
  mc(2,'The suffix "-ous" forms:','nouns','adverbs','verbs','adjectives','D'),
  mc(3,'The suffix "-ify" forms:','nouns','adverbs','adjectives','verbs','D'),
  mc(4,'The suffix "-al" forms:','nouns from verbs','adjectives or nouns from other words','adverbs from adjectives','verbs from nouns','B'),
  mc(5,'The suffix "-ity" forms:','adjectives','verbs','adverbs','nouns from adjectives','D'),
  mc(6,'"Simplify" contains the suffix "-ify" which means:','to make or become','the quality of','relating to','without','A'),
  mc(7,'"Creativity" is formed from "creative" + "-ity". What word class is "creativity"?','verb','adjective','adverb','noun','D'),
  mc(8,'Which suffix creates an ADVERB?','-ous','-ment','-ly','-ation','C'),
  mc(9,'Which word is formed with suffix "-ous"?','beautify','beautification','beauteous/beautiful','beautifully','C'),
  mc(10,'Complete: "The scientist made a ___ (signify/significant/significance/signification) breakthrough."','signify','significance','signification','significant','D'),
  tf(11,'The suffix "-ify" creates verbs from nouns or adjectives.','true'),
  tf(12,'The suffix "-ous" creates adverbs.','false'),
  tf(13,'"Nationality" is formed by adding "-ity" to "national."','true'),
  fb(14,'The ___ (technological) advances of the past decade have been remarkable.','technological'),
  fb(15,'Her ___ (creativity) and ___ (determination) set her apart from the competition.','creativity / determination'),
]},

'd4b4064b-8525-4f6b-8880-840ed05a666d':{pass_threshold:70,questions:[
  mc(1,'Word formation: "She was filled with ___ (admire/admiration/admirable/admired)."','admire','admirable','admired','admiration','D'),
  mc(2,'Complete: "The new policy proved ___ (controversy/controversial/controversially)."','controversy','controversially','controversied','controversial','D'),
  mc(3,'Complete: "His ___ (responsive/responsibility/respond/responsibly) to the team was remarkable."','responsive','respond','responsibly','responsibility','D'),
  mc(4,'Complete: "She showed great ___ (patient/patience/patiently)."','patient','patiently','patientness','patience','D'),
  mc(5,'Complete: "The results were ___ (disappoint/disappointment/disappointing)."','disappoint','disappointment','disappointingly','disappointing','D'),
  mc(6,'Complete: "There has been a significant ___ (improve/improvement/improved) in her grades."','improve','improved','improving','improvement','D'),
  mc(7,'Complete: "His ___ (commit/committed/commitment) to excellence is admirable."','commit','committed','committing','commitment','D'),
  mc(8,'Complete: "The ___ (discover/discovery/discoverer) of penicillin changed medicine."','discover','discoverer','discovering','discovery','D'),
  mc(9,'Complete: "She was ___ (determine/determination/determined) to succeed."','determine','determination','determining','determined','D'),
  mc(10,'Complete: "His ___ (creative/creativity/create/creatively) approach solved the problem."','creativity','create','creatively','creative','D'),
  tf(11,'Word formation often involves changing the suffix to shift between word classes.','true'),
  tf(12,'"Responsibility" is a verb.','false'),
  tf(13,'"Disappointing" (adj.) and "disappointment" (n.) are derived from the same root verb.','true'),
  fb(14,'The team showed remarkable ___ (perseverance) throughout the project.','perseverance'),
  fb(15,'Her ___ (dedication) to the cause was an inspiration to everyone around her.','dedication'),
]},

'e3ca2e2d-575b-4eb4-828b-4e733d1831b2':{pass_threshold:70,questions:[
  mc(1,'Complete: "make a ___."','progress','decision','develop','achievement','B'),
  mc(2,'Complete: "reach a ___."','decision','deciding','decide','decided','A'),
  mc(3,'Complete: "___ a conclusion."','make','reach/draw','do','get','B'),
  mc(4,'Complete: "conduct ___."','a research','researches','research','researched','C'),
  mc(5,'Complete: "raise ___."','awareness','aware','awaring','awared','A'),
  mc(6,'Complete: "achieve a ___."','breakthrough','breaking','break','broken','A'),
  mc(7,'Complete: "meet ___."','deadline','a deadline','deadlines','the deadline — all are correct except A','D'),
  mc(8,'Complete: "draw ___."','conclusions','concludes','conclusion','concluding','A'),
  mc(9,'Complete: "provide ___."','evidence','evidences','evidenced','evidencing','A'),
  mc(10,'Complete: "address ___."','issues','issue','issuing','issued','A'),
  tf(11,'"Conduct research" is a standard academic collocation.','true'),
  tf(12,'"Raise awareness" and "lower awareness" are both valid collocations.','false'),
  tf(13,'"Draw a conclusion" and "reach a conclusion" are both correct collocations.','true'),
  fb(14,'The study aimed to ___ (raise) awareness about the effects of sleep deprivation.','raise'),
  fb(15,'Researchers ___ (conducted) a comprehensive review of 200 published studies.','conducted'),
]},

'3a65f0bd-5119-4369-a12d-39cfa00d1d07':{pass_threshold:70,questions:[
  mc(1,'Complete: "have a significant ___."','impact','impactful','impacted','impacting','A'),
  mc(2,'Complete: "face ___."','challenges','challenge','challenging','challenged','A'),
  mc(3,'Complete: "take ___ action."','decisive','decision','decide','decided','A'),
  mc(4,'Complete: "pose a ___."','threat','threaten','threatening','threatened','A'),
  mc(5,'Complete: "play a ___."','role','rolling','roles — both A and C','rolled','C'),
  mc(6,'Complete: "maintain ___."','standards','standard','standardize','standardized','A'),
  mc(7,'Complete: "express ___."','concerns','concern','concerning — both A and B','concerned','C'),
  mc(8,'Complete: "bridge the ___."','gap','gapping','gapped','gaps — only A','A'),
  mc(9,'Complete: "build ___."','consensus','consensual','consensuses','consenting','A'),
  mc(10,'Complete: "implement ___."','changes / solutions / measures','change','implementation','changed','A'),
  tf(11,'"Pose a threat" is a common collocation in academic and journalistic writing.','true'),
  tf(12,'"Express a concern" is incorrect — you can only "say a concern."','false'),
  tf(13,'"Build consensus" means to achieve general agreement.','true'),
  fb(14,'The policy changes ___ (posed) a significant threat to biodiversity.','posed'),
  fb(15,'Both parties worked together to ___ (build) consensus on the contentious issue.','build'),
]},

'e9627e30-1d61-4012-8cb6-4d5e794a3d87':{pass_threshold:70,questions:[
  mc(1,'"Sensible" means:','sensitive','having good judgment and common sense','easily offended','related to the senses','B'),
  mc(2,'"Sensitive" means:','having good judgment','logical and practical','easily upset or responsive to stimuli','insensitive','C'),
  mc(3,'"Actual" means:','happening now at this moment','occurring in the present time','existing in fact, real','future','C'),
  mc(4,'"Currently" means:','eventually','at the present time','in the near future','in the past','B'),
  mc(5,'"Eventually" means:','immediately','at the present time','in the past','in the end, after some time','D'),
  mc(6,'"Sympathetic" in English means:','nice and pleasant to be with','showing agreement or understanding of someone\'s feelings','enthusiastic and supportive of a cause','likeable in character','B'),
  mc(7,'"Embarrassed" means:','feeling trapped','feeling ashamed or self-conscious','angry','confused','B'),
  mc(8,'"Confused" vs "confusing": "The ___ student asked for help." (the student felt confusion)','confusing','confusingly','confuse','confused','D'),
  mc(9,'"Bored" vs "boring": "The ___ presentation went on for two hours." (it caused boredom)','bored','boringly','bore','boring','D'),
  mc(10,'"Comprehensive" means:','easy to understand','covering all aspects completely','of limited scope','very short','B'),
  tf(11,'"Sensible" and "sensitive" are false friends with different meanings.','true'),
  tf(12,'"Actually" (English) means "at the moment" in the same way as "actuellement" in French.','false'),
  tf(13,'"Comprehensive" means including everything, thorough.','true'),
  fb(14,'It was a very ___ (sensible) decision to buy travel insurance.','sensible'),
  fb(15,'She is very ___ (sensitive) — you should be careful how you word your feedback.','sensitive'),
]},

'9fe4287c-27b2-4c37-b5be-4b919da95e14':{pass_threshold:70,questions:[
  mc(1,'Which phrase is FORMAL?','Hi there,','Good to meet ya.','Dear Sir/Madam, I am writing to...','How\'s it going?','C'),
  mc(2,'Which phrase is INFORMAL?','I would be grateful if you could...','Let\'s grab a coffee sometime.','I am writing to enquire...','Please find attached...','B'),
  mc(3,'"Get" in formal writing is replaced by:','receive / obtain','got / getting','get along with','getting better','A'),
  mc(4,'Formal: "We need to look into this." → more formal:','We must look at this.','This requires further investigation.','We got to check this out.','We\'re gonna investigate.','B'),
  mc(5,'Which is the formal equivalent of "find out"?','ascertain / determine','figure out','check out','look up','A'),
  mc(6,'Which is the formal equivalent of "buy"?','get','purchase / acquire','pick up','order online','B'),
  mc(7,'Formal writing avoids:','passive voice','technical vocabulary','Latin phrases','contractions (don\'t, won\'t)','D'),
  mc(8,'Which sentence is appropriate for a formal report?','We think prices will go up.','It is anticipated that prices will increase.','Prices gonna rise.','We\'re pretty sure prices will rise.','B'),
  mc(9,'Formal: "It is our intention to..." — informal equivalent:','We plan to...','It is planned...','We would intend to...','Intention is our plan to...','A'),
  mc(10,'"Nevertheless" is the formal equivalent of:','however/even so','but','although','whereas','A'),
  tf(11,'Contractions are generally avoided in formal written English.','true'),
  tf(12,'"Get" is commonly used in formal academic writing.','false'),
  tf(13,'"Nevertheless" and "however" are synonyms used to show contrast.','true'),
  fb(14,'___ (Despite) several setbacks, the project was completed on time. (formal)','Despite'),
  fb(15,'It is ___ (anticipated) that the new policy will reduce costs significantly.','anticipated'),
]},

'3e5318d4-0621-4d47-8f6e-6f120f463a27':{pass_threshold:70,questions:[
  mc(1,'Spoken English commonly uses:','complex noun phrases','passive constructions','contractions and informal vocabulary','impersonal structures','C'),
  mc(2,'Written English typically features:','incomplete sentences','contractions','false starts and fillers','complex subordinate clauses and precise vocabulary','D'),
  mc(3,'Complete the formal equivalent of "a lot of":','many/much/a considerable number of','lots of','loads of','tons of','A'),
  mc(4,'Which is more typical in SPOKEN English?','It is anticipated that...','Furthermore, it should be noted...','I mean, it\'s kind of interesting, isn\'t it?','The aforementioned policy...','C'),
  mc(5,'Which feature is characteristic of ACADEMIC WRITTEN English?','Use of "you" and "we"','Informal vocabulary','Hedging language and nominalization','Short, simple sentences','C'),
  mc(6,'"Nominalization" means:','using verbs instead of nouns','converting verbs or adjectives into nouns (e.g., "fail" → "failure")','using informal nouns','avoiding all nouns','B'),
  mc(7,'Formal written: "Analyze" → nominalized form:','analyzing','analyzed','analysis','to analyze','C'),
  mc(8,'Which sentence shows nominalization?','The government decided to invest.','The government\'s decision to invest was significant.','We decided.','They invested.','B'),
  mc(9,'Which is more appropriate in SPOKEN English?','The aforementioned stipulations...','Regarding the previously referenced matter...','So, what I\'m trying to say is...','It has been ascertained that...','C'),
  mc(10,'Which is a "discourse marker" typical in SPOKEN English?','consequently','furthermore','as mentioned above','you know, I mean, right','D'),
  tf(11,'"Nominalization" converts verbs and adjectives into nouns.','true'),
  tf(12,'Formal written English frequently uses contractions.','false'),
  tf(13,'Spoken English often contains fillers such as "you know," "I mean," and "right."','true'),
  fb(14,'The ___ (investigation) of the incident took three months. (nominalized from "investigate")','investigation'),
  fb(15,'___ (Furthermore), the data indicates a significant improvement in efficiency.','Furthermore'),
]},

'441e0a39-7e71-42fb-bd24-c37f0b510a37':{pass_threshold:80,questions:[
  mc(1,'The prefix "anti-" means:','before','after','between','against or opposing','D'),
  mc(2,'The prefix "inter-" means:','within','under','over','between or among','D'),
  mc(3,'The suffix "-ify" creates:','nouns','adjectives','adverbs','verbs','D'),
  mc(4,'The suffix "-ous" creates:','verbs','nouns','adverbs','adjectives','D'),
  mc(5,'Complete: "make a ___."','decision','deciding','decide','decided','A'),
  mc(6,'Complete: "conduct ___."','a research','researches','research','researched','C'),
  mc(7,'"Sensible" means:','easily upset','now / at this moment','having good practical judgment','related to the senses','C'),
  mc(8,'"Actually" in English means:','at this moment','in the near future','in reality / in fact','eventually','C'),
  mc(9,'Formal English avoids:','passive voice','technical vocabulary','subordinate clauses','contractions','D'),
  mc(10,'"Nominalization" converts:','nouns to verbs','verbs/adjectives to nouns','adjectives to adverbs','adverbs to nouns','B'),
  mc(11,'The formal equivalent of "find out" is:','check out','figure out','look up','ascertain/determine','D'),
  mc(12,'Complete: "___ (Sensible/Sensitive) to the situation, she responded carefully."','Sensibly','Sensitive','Sensible','Sensibly or sensitively — both work','B'),
  mc(13,'"Comprehensive" means:','very short','limited in scope','difficult to understand','covering all aspects completely','D'),
  mc(14,'Complete: "raise ___."','aware','awaring','awared','awareness','D'),
  mc(15,'Complete: "pose a ___."','threaten','threatened','threatening','threat','D'),
  tf(16,'"Pre-" and "post-" are opposite prefixes.','true'),
  tf(17,'"Hyper-" means under or less than normal.','false'),
  tf(18,'Spoken English typically features more complex subordinate clauses than written English.','false'),
  fb(19,'The ___ (investigation) revealed serious irregularities in the accounts. (nominalization of "investigate")','investigation'),
  fb(20,'It is ___ (anticipated) that the new regulation will come into force next year.','anticipated'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 13: "Mysteries & Progress"', lessons: ['212569b3-297b-48f7-b6c3-5248c8b0c918','d204d330-11f4-43c3-bb91-eef4c6f5a878','261df6fd-dd24-4aea-9266-98580bf105ca','cdca87e8-c872-49bf-91fb-39628c3b784b','5abd8d77-9ac5-4106-8cd3-fc3d042688b3','924a470c-5853-40c1-aa71-fa3aacb22fc4','ebaa440f-1463-494e-a7e5-4bb32e5ca498','dea01a1b-c5d5-49a1-a971-cdcc46b5b223'] },
  { name: 'Module 14: "Food & Home"', lessons: ['ac53a20b-f123-4948-9791-58d549ea7ebd','46270fb2-7885-40a4-9629-8cc220ee6c3f','d2cb8d26-3fd1-48c5-b90c-dbb749b4b791','7d2c0296-2f2f-4b29-8a81-19f28a0f1533','7384052e-bb4a-4efd-8af1-76435171fc53','f66d762d-b58a-4261-97ec-0f26983e647d','a478b4ce-f50b-4d4b-8655-bdf3cc224569','5716d7ce-78fb-46e8-9bc3-0910db08c6ed'] },
  { name: 'Module 15: "Phrasal Verbs & Idioms"', lessons: ['67a5038d-1365-4e16-83e5-ca4b3f9ff8e5','108f1ece-8eb6-4629-93b2-99cef93acba2','35029435-00ee-47f9-9906-d56e76d31460','6c412e9a-c3c8-41ee-a5d7-0facac17c969','9aa87009-f795-4633-8fff-8ac064f2c8bf','8fc87f5e-70c3-423e-9dab-d23cfced22d1','2c656216-5eaa-4f4d-b314-526d06066eb0','9eb87a76-9cf5-447c-959f-5b41369b1b08'] },
  { name: 'Module 16: "Word Formation Mastery"', lessons: ['c81762ad-97e6-4ebb-9532-682092021a5d','bfb5bca6-1b26-4086-9ef8-ab2cfd6fcec9','d4b4064b-8525-4f6b-8880-840ed05a666d','e3ca2e2d-575b-4eb4-828b-4e733d1831b2','3a65f0bd-5119-4369-a12d-39cfa00d1d07','e9627e30-1d61-4012-8cb6-4d5e794a3d87','9fe4287c-27b2-4c37-b5be-4b919da95e14','3e5318d4-0621-4d47-8f6e-6f120f463a27','441e0a39-7e71-42fb-bd24-c37f0b510a37'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 13–16 B2 Upper-Intermediate');
}
main();
