import * as fs from 'fs'; import * as path from 'path';
function loadEnv(){const ep=path.join(process.cwd(),'.env.local');if(!fs.existsSync(ep))return;const c=fs.readFileSync(ep,'utf8');for(const l of c.split('\n')){const t=l.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<0)continue;process.env[t.slice(0,i).trim()]=t.slice(i+1).trim();}}
loadEnv();
import { createClient } from '@supabase/supabase-js';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES: Record<string,{pass_threshold:number;questions:Q[]}> = {

// ── MODULE 1: Emotions & Communication ──────────────────────────────────────

'abb37b9f-a622-482b-8dec-901495984f23':{pass_threshold:70,questions:[
  mc(1,'Which adverb is used with UNGRADABLE (extreme) adjectives?','very','absolutely','rather','fairly','B'),
  mc(2,'Which adjective is UNGRADABLE (extreme)?','hot','happy','exhausted','cold','C'),
  mc(3,'Complete: "The concert was ___ brilliant."','very','absolutely','a bit','fairly','B'),
  mc(4,'Which word correctly modifies a gradable adjective like "hungry"?','absolutely','utterly','rather','completely','C'),
  mc(5,'Which adjective can be modified by "very"?','furious','enormous','tiny','perfect','C'),
  mc(6,'Which combination is grammatically CORRECT?','very exhausted','absolutely tired','very freezing','absolutely cold','D'),
  mc(7,'Choose the correct sentence:','She was very furious.','She was absolutely furious.','She was fairly furious.','She was utterly furious.','B'),
  mc(8,'"Freezing" is best described as:','a gradable adjective','an ungradable/extreme adjective','a comparative adjective','an adverb','B'),
  mc(9,'Which adverb CANNOT be used with "exhausted"?','completely','absolutely','fairly','utterly','C'),
  mc(10,'Complete: "I was ___ amazed by his performance."','a bit','fairly','rather','completely','D'),
  tf(11,'"Absolutely" can modify gradable adjectives like "hot".','false'),
  tf(12,'"Rather" is a downtoner that weakens gradable adjectives.','true'),
  tf(13,'"Boiling," "freezing," and "furious" are all ungradable (extreme) adjectives.','true'),
  fb(14,'The performance was ___ (absolutely) outstanding.','absolutely'),
  fb(15,'She was ___ (rather) disappointed with the result.','rather'),
]},

'5e3a2d0e-934a-4dab-b0a1-9f043a0efff6':{pass_threshold:70,questions:[
  mc(1,'Present Perfect connects:','two past actions','the past to the present moment','a past and a future action','two future actions','B'),
  mc(2,'Complete: "She has worked here ___ 2019."','for','since','ago','by','B'),
  mc(3,'Which sentence is correct?','I have seen him yesterday.','I saw him yesterday.','I have saw him.','I see him yesterday.','B'),
  mc(4,'Complete: "Have you ___ visited Japan?"','yet','already','ever','still','C'),
  mc(5,'Complete: "I ___ just finished the report."','had','have','was','did','B'),
  mc(6,'"Yet" in questions signals:','completed action','action not completed but expected','past regret','future plan','B'),
  mc(7,'Complete: "We have lived here ___ ten years."','since','yet','already','for','D'),
  mc(8,'Which is NOT a Present Perfect time expression?','just','yesterday','already','yet','B'),
  mc(9,'What does Present Perfect Simple emphasize?','the process','the result or completion','the start of action','future plans','B'),
  mc(10,'Complete: "She ___ never tried sushi."','did','was','has','had','C'),
  tf(11,'"I have seen him three days ago" is grammatically correct.','false'),
  tf(12,'Present Perfect can be used with "since" + a point in time.','true'),
  tf(13,'"Just" in Present Perfect means the action happened a long time ago.','false'),
  fb(14,'She ___ (has just) arrived at the airport.','has just'),
  fb(15,'We ___ (have never been) to Japan before.','have never been'),
]},

'bd2bd64e-d28c-4117-bf05-93d2913ef97b':{pass_threshold:70,questions:[
  mc(1,'What is the function of the participle in "The woman standing at the door is my manager"?','It replaces a relative clause','It replaces a conditional','It shows a future action','It replaces a gerund','A'),
  mc(2,'Complete: "The man ___ in the corner is the CEO."','sit','sat','sitting','to sit','C'),
  mc(3,'After verbs of perception, the present participle shows:','a completed action','an action in progress','a habitual action','a future action','B'),
  mc(4,'Complete: "I heard him ___ in the corridor."','to argue','argued','argues','arguing','D'),
  mc(5,'Which sentence shows simultaneous action via a participle clause?','After finishing, she left.','Finishing early, she went home.','To finish, she worked late.','Having finished, she went home.','B'),
  mc(6,'"Being nervous, he forgot his lines." — "Being nervous" means:','because he was nervous','after being nervous','despite being nervous','before being nervous','A'),
  mc(7,'Why is this wrong: "Seeing the sunset, the camera was taken out."','Wrong tense','The subject of "seeing" must match the main subject','Should be "seen"','There is no error','B'),
  mc(8,'Complete: "He sat ___ his newspaper."','to read','read','reading','having read','C'),
  mc(9,'Reduce: "the man who is running the marathon" →','the man run','the man runs','the man running','the man to run','C'),
  mc(10,'"Having noticed the mistake, she corrected it." — what does "Having noticed" show?','Action completed BEFORE the main action','Action completed AFTER','A simultaneous action','A future action','A'),
  tf(11,'The present participle can replace an active relative clause.','true'),
  tf(12,'"Smiling, she entered the room" means she smiled after entering.','false'),
  tf(13,'After "see/hear/watch," we can use the present participle for an action in progress.','true'),
  fb(14,'The children ___ (playing) in the park are from our school.','playing'),
  fb(15,'___ (Not knowing) the answer, he remained silent.','Not knowing'),
]},

'f4325002-cc0c-4af5-a968-aac5648c306d':{pass_threshold:70,questions:[
  mc(1,'Complete: "I was ___ during the lecture." (speaker experienced boredom)','boring','bored','bore','to bore','B'),
  mc(2,'Complete: "The ___ results surprised everyone." (results caused interest)','interest','interested','interesting','interestingly','C'),
  mc(3,'Which is correct? (She experienced boredom at the party)','She felt boring.','She felt bored.','She is boring.','She was bore.','B'),
  mc(4,'Complete: "The book ___ by Orwell is a classic." (reduced relative clause)','write','writing','written','wrote','C'),
  mc(5,'Choose: "a ___ window" (the window was broken)','break','breaking','broken','broke','C'),
  mc(6,'Complete: "He was ___ by the news."','shock','shocking','shocked','to shock','C'),
  mc(7,'Complete: "The ___ student asked for help." (the student felt confused)','confuse','confusing','confused','to confuse','C'),
  mc(8,'Complete: "The ___ instructions caused errors." (the instructions caused confusion)','confuse','confusing','confused','to confuse','B'),
  mc(9,'What grammatical function does "written" serve in: "Written in 1984, the novel won awards"?','Main verb','Adverb','Past participle as adjective/adverbial','Subject','C'),
  mc(10,'Complete: "She was ___ at his performance." (she felt amazement)','amaze','amazed','amazing','to amaze','B'),
  tf(11,'"Interesting" and "interested" are both adjectives but with different meanings.','true'),
  tf(12,'"The stolen car was found." — "stolen" is a past participle used as an adjective.','true'),
  tf(13,'"I am boring" means the speaker experiences boredom.','false'),
  fb(14,'The ___ (exhausted) athletes collapsed after the race.','exhausted'),
  fb(15,'She was ___ (thrilled) to receive the award.','thrilled'),
]},

'9f093196-66ef-4457-8ef1-84e0d3fe3d45':{pass_threshold:70,questions:[
  mc(1,'Which is a stative verb that should NOT be in continuous form?','run','think (= consider)','contain','walk','C'),
  mc(2,'Which form is correct? "She ___ the answer right now."','is knowing','knows','know','was knowing','B'),
  mc(3,'Complete: "I ___ about your proposal right now." (= actively considering)','think','thought','am thinking','had thought','C'),
  mc(4,'Complete: "This soup ___ delicious."','is tasting','tastes','is taste','taste','B'),
  mc(5,'Which sentence is INCORRECT?','I am understanding the lesson.','I understand the lesson.','She seems tired.','He appears confident.','A'),
  mc(6,'"She is seeing the doctor tomorrow." Is this correct and why?','Yes — "see" here is dynamic (appointment)','No — "see" is always stative','No — should be "She sees"','No — should be "She will seen"','A'),
  mc(7,'Which verb can be BOTH stative AND dynamic?','walk','run','look','speak','C'),
  mc(8,'Complete: "The package ___ ten kilograms."','is weighing','weighs','has weighed','weigh','B'),
  mc(9,'Complete: "He is ___ lunch right now." ("have" = eat = dynamic)','has','have','had','having','D'),
  mc(10,'Stative verbs typically express:','temporary actions','states and conditions','ongoing processes','planned future events','B'),
  tf(11,'"I am believing in hard work" is grammatically correct.','false'),
  tf(12,'"I see what you mean" uses "see" as a stative verb meaning "understand".','true'),
  tf(13,'"I am loving this pizza" is always considered incorrect in standard English.','false'),
  fb(14,'This milk ___ (smells) sour. Are you sure it\'s fresh?','smells'),
  fb(15,'We ___ (have owned) this property since 1990.','have owned'),
]},

'9e69ad92-8df2-498a-aba0-006034fa7183':{pass_threshold:70,questions:[
  mc(1,'What does "to confront" someone mean?','to avoid conflict','to face someone directly about an issue','to agree with someone','to ignore a problem','B'),
  mc(2,'"To empathize with" someone means:','to feel superior','to understand and share their feelings','to disagree','to argue against','B'),
  mc(3,'Which phrase softens a difficult statement?','That\'s completely wrong.','I see your point, but...','You\'re mistaken.','Stop saying that.','B'),
  mc(4,'Complete: "She tried to ___ between the two arguing parties."','argue','mediate','confront','escalate','B'),
  mc(5,'"To articulate" means:','to avoid speaking','to express clearly in words','to listen carefully','to write formally','B'),
  mc(6,'Choose the correct form: "I\'d like to raise a ___ concern."','sensitive','sensitively','sensibility','sensation','A'),
  mc(7,'Complete: "We need to ___ the issue before it escalates."','ignore','dismiss','address','deny','C'),
  mc(8,'What does "to de-escalate" mean?','to make a situation worse','to reduce tension in a conflict','to start an argument','to avoid responsibility','B'),
  mc(9,'Complete: "I understand your frustration, and I ___ for any inconvenience."','apology','apologies','apologize','apologizing','C'),
  mc(10,'What does "to navigate a difficult conversation" mean?','to avoid it','to manage it skillfully','to escalate it','to ignore it','B'),
  tf(11,'"To assert" means to express something forcefully and clearly.','true'),
  tf(12,'"Passive aggression" means expressing anger directly and openly.','false'),
  tf(13,'Empathy and sympathy are identical in meaning.','false'),
  fb(14,'She spoke with great ___ (empathy) when discussing the layoffs.','empathy'),
  fb(15,'It takes courage to ___ (confront) someone about their behavior.','confront'),
]},

'4dac3f57-3455-4ffe-8228-7d8dfbad16cb':{pass_threshold:70,questions:[
  mc(1,'"High-context communication" means:','information is mostly in explicit words','meaning depends on context, relationship, and non-verbal cues','communication is very direct','messages are detailed and explicit','B'),
  mc(2,'Which culture is typically described as "low-context" (direct/explicit)?','Japan','Germany','Saudi Arabia','China','B'),
  mc(3,'"Non-verbal cues" include:','spoken words','gestures, facial expressions, body language','written text','grammar rules','B'),
  mc(4,'"Cross-cultural misunderstanding" occurs when:','people from the same culture disagree','people from different cultures misinterpret each other','two people speak different languages','words are mispronounced','B'),
  mc(5,'"To read between the lines" means:','to read very quickly','to understand hidden meaning','to misread text','to read aloud','B'),
  mc(6,'"Indirect communication" prefers:','clear, explicit statements','hints, implications, and suggestions','confrontation','formal written language only','B'),
  mc(7,'Complete the collocation: "She gave him ___."','a direct feedback','direct feedback','directly feedback','feedback direct','B'),
  mc(8,'"Saving face" is particularly important in:','low-context Western cultures','high-context cultures like East Asia','all business negotiations','purely informal settings','B'),
  mc(9,'"Cultural sensitivity" means:','knowing all cultural rules','being aware and respectful of cultural differences','refusing to adapt','ignoring cultural norms','B'),
  mc(10,'"Talk past each other" means:','to speak loudly','to fail to understand each other despite talking','to speak at the same time','to reach agreement','B'),
  tf(11,'Direct communication is especially valued in high-context cultures.','false'),
  tf(12,'Eye contact rules vary significantly across cultures.','true'),
  tf(13,'"Small talk" serves no real communication purpose.','false'),
  fb(14,'In cross-cultural ___ (communication), misunderstandings often arise from different expectations.','communication'),
  fb(15,'She struggled to ___ (interpret) his indirect response as a polite refusal.','interpret'),
]},

'1106f690-7328-409b-a52e-4e7a48800dd1':{pass_threshold:80,questions:[
  mc(1,'Which adverb modifies UNGRADABLE adjectives?','very','quite','absolutely','fairly','C'),
  mc(2,'Complete: "She was ___ furious." (ungradable)','very','a bit','absolutely','rather','C'),
  mc(3,'Present Perfect is used to connect:','two past events','the past and present','a past and future event','two future events','B'),
  mc(4,'Complete: "Have you ever ___ to Japan?"','went','go','been','being','C'),
  mc(5,'The present participle in "the woman sitting there" functions as:','a main verb','a reduced relative clause','a gerund','an adverb','B'),
  mc(6,'"Being late, she missed the introduction." — "Being late" means:','after being late','because she was late','despite being late','before being late','B'),
  mc(7,'Which is the correct past participle construction?','a break window','a breaking window','a broken window','a broke window','C'),
  mc(8,'"She was ___ (bore/bored/boring) by the lecture." (she experienced boredom)','bore','bored','boring','to bore','B'),
  mc(9,'Which verb is STATIVE and should NOT be used in continuous?','run','belong','write','travel','B'),
  mc(10,'Complete: "He ___ (understand) what you mean."','is understanding','understands','was understanding','has been understanding','B'),
  mc(11,'"To mediate" means:','to escalate conflict','to act as a neutral party between two sides','to ignore a problem','to confront aggressively','B'),
  mc(12,'"High-context" cultures tend to communicate:','directly and explicitly','indirectly, relying on context','only in writing','only in formal settings','B'),
  mc(13,'Complete: "We ___ already ___ the project." (Present Perfect)','did / finish','have / finished','had / finished','were / finishing','B'),
  mc(14,'"Saving face" relates to:','losing money','protecting one\'s reputation and dignity','physical safety','formal negotiations only','B'),
  mc(15,'"She is seeing the doctor tomorrow" — "see" here is:','stative','dynamic (= have an appointment)','incorrect usage','a gerund','B'),
  tf(16,'"Absolutely" can be used with both gradable and ungradable adjectives.','false'),
  tf(17,'The present participle can replace an active relative clause.','true'),
  tf(18,'"Cross-cultural communication" requires awareness of non-verbal cues.','true'),
  fb(19,'The ___ (exhausted) runner collapsed at the finish line.','exhausted'),
  fb(20,'She ___ (has just) received the results of her exam.','has just'),
]},

// ── MODULE 2: Dreams & Ambitions ────────────────────────────────────────────

'819a7e71-e718-4a50-87aa-5b9d087ff64a':{pass_threshold:70,questions:[
  mc(1,'"Used to" + infinitive expresses:','a current habit','a past habit or state that no longer exists','a future plan','a general truth','B'),
  mc(2,'"Would" (for past) can replace "used to" only when expressing:','past states','past habits (repeated actions)','future habits','present habits','B'),
  mc(3,'Complete: "She ___ play the piano as a child."','use to','used to','would to','uses to','B'),
  mc(4,'Which is INCORRECT?','He used to be shy.','He would be shy.','He used to play chess.','He would play chess every Sunday.','B'),
  mc(5,'Complete: "I ___ walk to school every day." (past habit, action)','used to','would','both are correct','neither','C'),
  mc(6,'Complete: "She didn\'t ___ eat vegetables, but now she loves them."','used','use','uses','using','B'),
  mc(7,'Complete: "Did you ___ live in Paris?"','used','use','uses','using','B'),
  mc(8,'Complete: "There ___ to be a cinema here." (past state)','used','would','use','uses','A'),
  mc(9,'Which sentence describes a PAST STATE (not a habit)?','She would study late.','They would go fishing.','He used to be afraid of dogs.','We would visit grandma.','C'),
  mc(10,'Complete: "We ___ spend summers at the lake." (past repeated action)','would','used','use','uses','A'),
  tf(11,'"Would" can express past states in questions: "Would she be shy?"','false'),
  tf(12,'"I didn\'t use to like coffee" is grammatically correct.','true'),
  tf(13,'"He used to working late" is grammatically correct.','false'),
  fb(14,'She ___ (used to) be terrified of public speaking.','used to'),
  fb(15,'We ___ (would) go camping every summer when we were young.','would'),
]},

'e6d4d065-e413-42ab-ada1-0ffa9171c4e7':{pass_threshold:70,questions:[
  mc(1,'Complete: "I am used to ___ early." (be used to + ?)','wake','to wake','woke','waking','D'),
  mc(2,'"Get used to" means:','to be already accustomed','to become accustomed gradually','to stop being accustomed','to refuse to adjust','B'),
  mc(3,'"Be used to" means:','in the process of becoming accustomed','to be already accustomed','to have used something before','to stop a habit','B'),
  mc(4,'Complete: "He can\'t ___ used to driving on the left."','be','is','are','get','D'),
  mc(5,'Complete: "I\'m not used to ___ so much noise."','hear','heard','to hear','hearing','D'),
  mc(6,'Which is CORRECT?','She is used to get up early.','She is used to getting up early.','She gets used to get up early.','She used to getting up early.','B'),
  mc(7,'Complete: "It took months, but they finally ___ used to the climate."','were','have','are','got','D'),
  mc(8,'Complete: "He is used to ___ in stressful situations."','work','worked','to work','working','D'),
  mc(9,'"I used to smoke" vs "I am used to smoking" — what is the key difference?','First = past habit (quit); Second = accustomed to','First = accustomed; Second = past habit','Both mean the same','First = future; Second = present','A'),
  mc(10,'Which form follows "get used to"?','bare infinitive','to-infinitive','gerund (-ing)','past participle','C'),
  tf(11,'"Get used to" is always followed by a gerund (-ing form).','true'),
  tf(12,'"I am used to live here" is grammatically correct.','false'),
  tf(13,'"Be used to" and "get used to" have the same meaning.','false'),
  fb(14,'She is gradually ___ (getting used to) the long commute.','getting used to'),
  fb(15,'Are you ___ (used to) working from home yet?','used to'),
]},

'8f3a8937-dda5-4167-8536-08a0863593cb':{pass_threshold:70,questions:[
  mc(1,'Complete: "I wish I ___ the answer." (present wish)','know','known','had known','knew','D'),
  mc(2,'Complete: "I wish I ___ attended the conference." (past regret)','have','had','would have','should have','B'),
  mc(3,'Complete: "I wish you ___ stop making that noise!" (complaint about now)','will','could','should','would','D'),
  mc(4,'Complete: "If only I ___ spoken to him sooner!" (past regret)','have','would have','should have','had','D'),
  mc(5,'Complete: "I\'d rather you ___ leave now."','would','will','left','leave','C'),
  mc(6,'Complete: "I\'d rather ___ at home." (own preference, no subject after)','stayed','to stay','staying','stay','D'),
  mc(7,'What does "If only" add compared to "I wish"?','A weaker wish','A more emphatic wish','A future possibility','A regret about others','B'),
  mc(8,'Complete: "I wish it ___ raining." (complaint about ongoing situation)','stopped','stops','had stopped','would stop','D'),
  mc(9,'Which expresses PAST REGRET?','I wish I knew.','I wish I would know.','I wish I had known.','I wish I will know.','C'),
  mc(10,'"She\'d rather ___ the bus than drive in traffic."','took','taking','to take','take','D'),
  tf(11,'"I wish I were taller" is correct (subjunctive use of \'were\').','true'),
  tf(12,'"If only" can only be used for future wishes.','false'),
  tf(13,'"I\'d rather you came tomorrow" uses past simple to express a present preference.','true'),
  fb(14,'I wish I ___ (had studied) harder at school.','had studied'),
  fb(15,'If only I ___ (could) speak Italian fluently!','could'),
]},

'3e7182c5-6f34-4a4c-8971-c5338dc5738c':{pass_threshold:70,questions:[
  mc(1,'Complex Object: "I want ___ to succeed."','she','her','hers','herself','B'),
  mc(2,'Complete: "She made him ___." (bare infinitive after "make")','to apologize','apologizing','apologized','apologize','D'),
  mc(3,'Complete: "I saw her ___ the building." (completed whole action)','entering','entered','to enter','enter','D'),
  mc(4,'Complete: "Let me ___ you something."','to ask','asking','asked','ask','D'),
  mc(5,'Complete: "They had us ___ for hours." (have + object + ?)','waited','to wait','waiting','wait','D'),
  mc(6,'Complete: "I heard them ___ loudly." (action in progress)','argue','to argue','argued','arguing','D'),
  mc(7,'Complete: "She encouraged him ___ for the job."','apply','applying','applied','to apply','D'),
  mc(8,'Complete: "I\'d like you ___ on time."','arrive','arriving','arrived','to arrive','D'),
  mc(9,'Complete: "The police made everyone ___ the area."','to evacuate','evacuating','evacuated','evacuate','D'),
  mc(10,'After "let" and "make," we use:','the to-infinitive','the gerund','the bare infinitive','the past participle','C'),
  tf(11,'After "let" and "make," we use the to-infinitive in the active voice.','false'),
  tf(12,'"I want her to succeed" is an example of Complex Object.','true'),
  tf(13,'After "see," "hear," and "watch," we can use bare infinitive or -ing, with different meanings.','true'),
  fb(14,'She ___ (asked) him to help with the project.','asked'),
  fb(15,'They ___ (let) the children stay up late.','let'),
]},

'c59a63d2-eaf9-4309-904b-6815d471df1a':{pass_threshold:70,questions:[
  mc(1,'Complete: "He ordered everyone ___ quiet."','be','being','been','to be','D'),
  mc(2,'Complete: "She told him ___ worry."','not to','to not','don\'t','not','A'),
  mc(3,'Complete: "I invited ___ to the ceremony."','they','their','theirs','them','D'),
  mc(4,'Complete: "The manager asked the team ___ the report."','complete','completing','completed','to complete','D'),
  mc(5,'Complete: "He warned us ___ the water."','to not drink','don\'t drink','not drinking','not to drink','D'),
  mc(6,'Complete: "The coach motivated them ___ harder."','train','training','trained','to train','D'),
  mc(7,'Which verb is followed by object + to-infinitive?','let','make','enjoy','allow','D'),
  mc(8,'Complete: "She reminded ___ to submit the form."','I','my','mine','me','D'),
  mc(9,'Complete: "The doctor advised him ___ smoking."','give up','giving up','gave up','to give up','D'),
  mc(10,'After "help," which structure is POSSIBLE?','object + bare infinitive only','object + to-infinitive only','both bare infinitive and to-infinitive','neither','C'),
  tf(11,'"Tell" is always followed by object + to-infinitive.','true'),
  tf(12,'"I suggested him to take the job" is grammatically correct.','false'),
  tf(13,'"She encouraged me to apply" is an example of complex object with to-infinitive.','true'),
  fb(14,'The manager ___ (persuaded) the team to work overtime.','persuaded'),
  fb(15,'She ___ (warned) him not to be late again.','warned'),
]},

'8e141574-db24-4416-9b5a-e26b886470ab':{pass_threshold:70,questions:[
  mc(1,'A "pioneer" is:','one who follows tradition','one of the first to develop a new method','an expert in a narrow field','a famous politician','B'),
  mc(2,'"Visionary" describes someone who:','has practical skills above all','has original ideas about the future','follows established patterns','avoids innovation','B'),
  mc(3,'"Prodigy" refers to:','an elderly expert','a young person with exceptional talent','a failed inventor','a mid-level manager','B'),
  mc(4,'"Maverick" describes someone who:','always follows rules','thinks and acts independently','is afraid of change','specializes in detail work','B'),
  mc(5,'To "mentor" someone means:','to criticize harshly','to guide and support development','to compete with them','to ignore their progress','B'),
  mc(6,'"Luminary" refers to:','a dim light source','a person who inspires or influences others','a low-ranking employee','a scientific theory','B'),
  mc(7,'"Trailblazer" means:','someone who follows a path','a person who is first to do something new','a slow and cautious person','someone who destroys evidence','B'),
  mc(8,'Complete: "She achieved ___ success in her career."','unprecedently','unprecedented','unprecedentedly','unprecede','B'),
  mc(9,'To "accomplish" a goal means:','to attempt','to achieve','to abandon','to delay','B'),
  mc(10,'"Attain" is most similar in meaning to:','fail','lose','achieve','avoid','C'),
  tf(11,'"Pioneer," "trailblazer," and "maverick" all have positive connotations in most contexts.','true'),
  tf(12,'A "prodigy" is always an adult who achieves late success.','false'),
  tf(13,'"Fulfill an ambition" is a common collocation in English.','true'),
  fb(14,'She was hailed as a ___ (pioneer) in renewable energy.','pioneer'),
  fb(15,'His ___ (visionary) leadership transformed the company.','visionary'),
]},

'46f78b04-1a2f-428c-bbf5-236fe91156c0':{pass_threshold:70,questions:[
  mc(1,'Complete the collocation: "pursue a ___."','dreaming','dreamed','dreams','dream','D'),
  mc(2,'Complete: "overcome ___."','adverse','adversely','adversary','adversity','D'),
  mc(3,'Complete: "fulfill one\'s ___."','ambitious','ambitioned','ambitiously','ambition','D'),
  mc(4,'Complete: "reach one\'s ___."','potency','potent','potentially','potential','D'),
  mc(5,'Complete: "achieve ___."','successful','succeed','successfully','success','D'),
  mc(6,'Complete: "face ___."','fail','failed','failing','failure','D'),
  mc(7,'Complete: "make a ___."','breakout','breakdown','breaking','breakthrough','D'),
  mc(8,'Complete: "set a ___."','recorded','recording','recorder','record','D'),
  mc(9,'Complete: "rise to the ___."','occasion\'s','occasions','occasioning','occasion','D'),
  mc(10,'Complete: "She left a lasting ___ on the field."','impacted','impacts','impacting','impact','D'),
  tf(11,'"Achieve" and "attain" are always perfectly interchangeable.','false'),
  tf(12,'"She made history" means she did something historically significant.','true'),
  tf(13,'"Overcome challenges" and "face challenges" mean exactly the same thing.','false'),
  fb(14,'He worked tirelessly to ___ (realize) his vision.','realize'),
  fb(15,'She ___ (broke) the world record at the championship.','broke'),
]},

'06086034-40a2-4f90-a9d8-5ffac67d72ad':{pass_threshold:80,questions:[
  mc(1,'"Used to + infinitive" can express:','only past habits','only past states','both past habits and past states','future habits','C'),
  mc(2,'Which is INCORRECT? (would cannot express past states)','He used to be shy.','He would be shy.','He used to play chess.','He would play chess.','B'),
  mc(3,'Complete: "She didn\'t ___ eat vegetables as a child."','used','uses','using','use','D'),
  mc(4,'Complete: "I am used to ___ late." (be used to + gerund)','work','worked','to work','working','D'),
  mc(5,'"Get used to" means:','to be accustomed','to become accustomed','to stop a habit','to refuse to adjust','B'),
  mc(6,'Complete: "I wish I ___ more time." (present wish)','have','had','will have','would have','B'),
  mc(7,'Complete: "I wish he ___ stop talking." (complaint about now)','would','will','could','should','A'),
  mc(8,'Complete: "If only I ___ studied harder!" (past regret)','have','would have','should','had','D'),
  mc(9,'Complete: "She made him ___." (bare infinitive)','to apologize','apologizing','apologized','apologize','D'),
  mc(10,'Complete: "I want ___ to succeed." (complex object)','she','her','hers','herself','B'),
  mc(11,'"Visionary" and "pioneering" are both ___ that describe innovative leadership.','nouns','adjectives','adverbs','prepositions','B'),
  mc(12,'Complete: "pursue a dream / achieve ___."','successful','succeed','successfully','success','D'),
  mc(13,'Complete: "She told him ___ late."','not to be','to not be','don\'t be','not being','A'),
  mc(14,'Complete: "I\'d rather you ___ tomorrow." (preference about someone else)','come','came','to come','coming','B'),
  mc(15,'"I\'d rather stay home" — this structure uses:','to-infinitive after "rather"','bare infinitive after "rather"','gerund after "rather"','past simple after "rather"','B'),
  tf(16,'"Would" can replace "used to" for past states like "He would be shy."','false'),
  tf(17,'"Be used to" and "get used to" are both followed by a gerund.','true'),
  tf(18,'"I wish I had studied" expresses a regret about the past.','true'),
  fb(19,'She ___ (encouraged) him to apply for the position.','encouraged'),
  fb(20,'He ___ (used to) live in London before moving to Dubai.','used to'),
]},

// ── MODULE 3: Tenses Mastery I ──────────────────────────────────────────────

'a0d8ce6f-a276-409f-b16a-2b4c6e1ad93f':{pass_threshold:70,questions:[
  mc(1,'Present Simple is used for:','temporary actions happening now','permanent facts, habits, and schedules','actions in progress at the moment','recent completed actions','B'),
  mc(2,'Present Continuous is used for:','permanent states','facts and general truths','actions in progress now or temporary trends','completed actions','C'),
  mc(3,'Complete: "Water ___ at 100°C."','is boiling','has boiled','was boiling','boils','D'),
  mc(4,'Complete: "She ___ for her exam this week." (temporary)','studies','studied','is studying','has studied','C'),
  mc(5,'Present Perfect Simple vs Continuous: which emphasizes duration?','Present Perfect Simple','Present Perfect Continuous','Present Simple','Past Simple','B'),
  mc(6,'Complete: "I ___ this book for two hours." (duration, result visible)','read','am reading','have been reading','have read','C'),
  mc(7,'Complete: "She ___ three books this month." (completed number)','has been reading','is reading','reads','has read','D'),
  mc(8,'Which sentence uses Present Continuous for a future arrangement?','She meets him tomorrow.','She will meet him.','She is meeting him tomorrow.','She has met him.','C'),
  mc(9,'Complete: "They ___ (always/lose) their keys!" (annoying habit)','always lose','are always losing','have always lost','were always losing','B'),
  mc(10,'Which tense describes a trend? "More people ___ to cities."','moved','move','are moving','have moved','C'),
  tf(11,'Stative verbs are rarely used in the Present Continuous.','true'),
  tf(12,'Present Perfect Simple can be used with "for" and "since".','true'),
  tf(13,'"I am knowing the answer" is grammatically correct.','false'),
  fb(14,'She ___ (has worked) at this company for ten years.','has worked'),
  fb(15,'I ___ (am studying) for my finals this week.','am studying'),
]},

'63930411-93a2-4287-a180-1455488c8049':{pass_threshold:70,questions:[
  mc(1,'Present Simple Passive is formed with:','am/is/are + past participle','was/were + past participle','have/has been + past participle','am/is/are + being + past participle','A'),
  mc(2,'Complete: "The report ___ every Monday."','is submitted','is submitting','has submitted','was submitted','A'),
  mc(3,'Present Continuous Passive is formed with:','am/is/are + past participle','am/is/are + being + past participle','have/has been + past participle','was/were + being + past participle','B'),
  mc(4,'Complete: "The bridge ___ repaired at the moment."','is','is being','has been','was being','B'),
  mc(5,'Present Perfect Passive is formed with:','am/is/are + past participle','am/is/are + being + past participle','have/has been + past participle','was/were + past participle','C'),
  mc(6,'Complete: "Several mistakes ___ found in the document."','are','are being','have been','were being','C'),
  mc(7,'Choose the passive voice of "They are building a new highway."','A new highway is built.','A new highway has been built.','A new highway is being built.','A new highway was built.','C'),
  mc(8,'Complete: "English ___ spoken in over 50 countries."','has been','is being','is','was','C'),
  mc(9,'Why is passive voice preferred in scientific writing?','to sound informal','to emphasize the agent','to focus on the action/result, not the doer','to use shorter sentences','C'),
  mc(10,'Complete: "The new policy ___ announced yet."','hasn\'t been','isn\'t being','isn\'t','wasn\'t being','A'),
  tf(11,'The agent (by + noun) is always stated in passive sentences.','false'),
  tf(12,'"The research is being conducted" is Present Continuous Passive.','true'),
  tf(13,'Present Perfect Passive uses "has/have been + past participle."','true'),
  fb(14,'The results ___ (are being) analyzed right now.','are being'),
  fb(15,'Three new hospitals ___ (have been) built this year.','have been'),
]},

'9df44735-9961-40cc-b944-834f15b80905':{pass_threshold:70,questions:[
  mc(1,'Past Simple is used for:','actions in progress when another past action happened','completed actions at a specific past time','ongoing past situations','actions that started before another past action','B'),
  mc(2,'Past Continuous is used for:','completed actions','ongoing actions at a specific past moment','repeated past habits (used to)','actions before another past event','B'),
  mc(3,'Complete: "While I ___ TV, the phone rang."','watched','had watched','was watching','have watched','C'),
  mc(4,'Past Perfect is used for:','the most recent past action','actions completed BEFORE another past action','ongoing past actions','repeated past habits','B'),
  mc(5,'Complete: "By the time she arrived, we ___ already ___ dinner."','had / eaten','were / eating','have / eaten','did / eat','A'),
  mc(6,'Past Perfect Continuous is used for:','completed past actions with no duration','ongoing past actions with duration BEFORE another past event','recent completed actions','future actions from the past','B'),
  mc(7,'Complete: "He ___ all day before he finally gave up."','worked','was working','had been working','has worked','C'),
  mc(8,'Complete: "She ___ when the earthquake struck." (in progress)','slept','had slept','was sleeping','has slept','C'),
  mc(9,'Choose the sentence with correct narrative tense sequence:','I arrived and then she left already.','When I arrived, she had already left.','When I arrived, she already left.','I arrived and she was already going.','B'),
  mc(10,'Complete: "They ___ for three hours when the storm began."','had been driving','were driving','drove','have driven','A'),
  tf(11,'Past Simple and Past Continuous can both appear in the same sentence.','true'),
  tf(12,'Past Perfect can be used without another past action if context is clear.','true'),
  tf(13,'"I worked there for ten years" uses Past Perfect correctly.','false'),
  fb(14,'She ___ (had never visited) Europe before last summer.','had never visited'),
  fb(15,'He ___ (was reading) when the lights went out.','was reading'),
]},

'641b3278-767b-4f0f-b707-cf3f225d58ff':{pass_threshold:70,questions:[
  mc(1,'Past Simple Passive is formed with:','was/were + past participle','was/were + being + past participle','had been + past participle','am/is/are + past participle','A'),
  mc(2,'Complete: "The letter ___ yesterday."','has been sent','is sent','was sent','had been sent','C'),
  mc(3,'Past Continuous Passive is formed with:','was/were + past participle','was/were + being + past participle','had been + past participle','has/have been + past participle','B'),
  mc(4,'Complete: "The project ___ being reviewed when the manager arrived."','is','has','was','had','C'),
  mc(5,'Past Perfect Passive is formed with:','was/were + past participle','was/were + being + past participle','had been + past participle','has been + past participle','C'),
  mc(6,'Complete: "The evidence ___ destroyed before the trial."','was being','has been','had been','was','C'),
  mc(7,'Convert to passive: "Workers built the bridge in 1990."','The bridge built in 1990.','The bridge was built in 1990.','The bridge has been built in 1990.','The bridge is built in 1990.','B'),
  mc(8,'Complete: "The documents ___ being checked when the power failed."','are','have been','were','had been','C'),
  mc(9,'Complete: "All the tickets ___ sold before we arrived."','were','have been','are','had been','D'),
  mc(10,'When is Past Perfect Passive most appropriate?','for recent completed actions','for actions completed before another past event','for general truths','for ongoing past actions','B'),
  tf(11,'"The company was founded in 1990" is Past Simple Passive.','true'),
  tf(12,'"The building had been completed before they moved in" is Past Perfect Passive.','true'),
  tf(13,'"The report was being wrote" is grammatically correct.','false'),
  fb(14,'The project ___ (had been delayed) for months before it was cancelled.','had been delayed'),
  fb(15,'Several employees ___ (were dismissed) after the investigation.','were dismissed'),
]},

'2c235e1d-ffe1-43c7-8a08-6c89edbf2e83':{pass_threshold:70,questions:[
  mc(1,'Present Perfect Continuous is formed with:','has/have + past participle','has/have + been + -ing','am/is/are + been + -ing','was/were + -ing','B'),
  mc(2,'Present Perfect Continuous emphasizes:','the number of completed things','duration of an ongoing/recently stopped activity','a specific past time','a future plan','B'),
  mc(3,'Complete: "She ___ all morning." (ongoing, visibly tired)','worked','has worked','has been working','is working','C'),
  mc(4,'Complete: "How long ___ you ___ English?"','are / learning','did / learn','have / been learning','were / learning','C'),
  mc(5,'"I have been running." What does this most likely explain?','I run every day.','That\'s why I\'m out of breath now.','I ran last week.','I will run tomorrow.','B'),
  mc(6,'Complete: "They ___ on this project since January."','worked','are working','have been working','were working','C'),
  mc(7,'Which time expressions are typical with Present Perfect Continuous?','yesterday, last week','for, since, all day, recently','tomorrow, next week','never, yet','B'),
  mc(8,'Complete: "She ___ that book for weeks but hasn\'t finished it."','read','has been reading','was reading','reads','B'),
  mc(9,'When is Present Perfect Simple preferred over Continuous?','for duration','for ongoing processes','for completed actions with a result or number','for annoying habits','C'),
  mc(10,'Complete: "I ___ three emails today." (completed, number)','have been writing','have written','wrote','am writing','B'),
  tf(11,'Present Perfect Continuous can be used with both "for" and "since."','true'),
  tf(12,'"She has been knowing him for years" is correct.','false'),
  tf(13,'"I have been reading 3 books" (counting completed items) is correct.','false'),
  fb(14,'He ___ (has been studying) all night. No wonder he looks exhausted.','has been studying'),
  fb(15,'We ___ (have been waiting) for over an hour!','have been waiting'),
]},

'fafa1219-aa4c-47ab-bcab-9d1ba2c5dea9':{pass_threshold:70,questions:[
  mc(1,'Past Perfect Continuous is formed with:','had + past participle','had been + -ing','was/were + been + -ing','have been + -ing','B'),
  mc(2,'Past Perfect Continuous emphasizes:','a completed past action','the duration of an action before a specific past moment','a future action from the past','a repeated past habit','B'),
  mc(3,'Complete: "She was exhausted because she ___ all night."','worked','has worked','had been working','was working','C'),
  mc(4,'Complete: "He ___ for the company for five years before he resigned."','worked','has worked','was working','had been working','D'),
  mc(5,'Which time expressions work with Past Perfect Continuous?','yet, already','for, since (+ past reference point)','tomorrow, soon','never, just (+ completion)','B'),
  mc(6,'Complete: "By the time they arrived, we ___ for hours."','waited','were waiting','have been waiting','had been waiting','D'),
  mc(7,'Past Perfect Continuous vs Past Perfect Simple: which emphasizes DURATION?','Past Perfect Simple','Past Perfect Continuous','Both equally','Neither','B'),
  mc(8,'Complete: "His hands were dirty because he ___ in the garden."','worked','has been working','had been working','was working','C'),
  mc(9,'Complete: "They ___ for years before they finally got married."','dated','have been dating','had been dating','were dating','C'),
  mc(10,'Why use Past Perfect Continuous instead of Past Simple?','to show a specific past time','to emphasize duration or ongoing nature before a past event','to show a more recent event','to show completed numbers','B'),
  tf(11,'Past Perfect Continuous is used for actions that were ongoing up to a point in the past.','true'),
  tf(12,'"She had been knowing him" is correct Past Perfect Continuous.','false'),
  tf(13,'Past Perfect Continuous provides context or explains causes of past situations.','true'),
  fb(14,'He ___ (had been playing) tennis for years before his injury.','had been playing'),
  fb(15,'She ___ (had been crying) — her eyes were red.','had been crying'),
]},

'0bfdf045-0228-4627-bac8-b4f7f38f7a73':{pass_threshold:70,questions:[
  mc(1,'Choose the correct tense: "While he ___, she read the paper."','watches TV','watched TV','was watching TV','has watched TV','C'),
  mc(2,'Choose: "By 2020, the company ___ its target."','reached','has reached','had reached','was reaching','C'),
  mc(3,'Choose: "She ___ there for two hours when the bus arrived."','waited','has been waiting','was waiting','had been waiting','D'),
  mc(4,'Choose: "I ___ three coffees already today." (completed number)','am drinking','have drunk','have been drinking','was drinking','B'),
  mc(5,'Choose: "The results ___ yesterday." (Past Simple Passive)','have been published','were published','are published','were being published','B'),
  mc(6,'Choose: "He looks tired. He ___ all day."','worked','has worked','had worked','has been working','D'),
  mc(7,'Choose: "She ___ just ___ a promotion." (recent completion)','has / been given','had / given','was / giving','has / been giving','A'),
  mc(8,'Choose: "When she arrived, the meeting ___."','already started','had already started','was already starting','already starts','B'),
  mc(9,'Which tense pair is correct for: "I (read) for two hours before I (notice) the time."','read / noticed','was reading / noticed','had been reading / noticed','have read / had noticed','C'),
  mc(10,'Which is the most appropriate in formal academic writing?','The team founded the company last year.','The company was founded last year.','The team has been founding the company.','They are founding the company.','B'),
  tf(11,'Past Perfect Simple and Past Perfect Continuous can both appear in the same text.','true'),
  tf(12,'"I have been to Paris" uses Present Perfect Simple correctly.','true'),
  tf(13,'"She is knowing French" is a correct Present Continuous sentence.','false'),
  fb(14,'By the time the exam started, he ___ (had been studying) for 12 hours.','had been studying'),
  fb(15,'The research ___ (has been conducted) over three years.','has been conducted'),
]},

'1ddaedaf-ce10-4d66-9618-517423b0cea4':{pass_threshold:70,questions:[
  mc(1,'The SIMPLE aspect emphasizes:','an ongoing process','a fact, habit, or completed unit','connection to another time','duration','B'),
  mc(2,'The CONTINUOUS aspect emphasizes:','a fact or habit','the number of completed items','an ongoing, in-progress process','connection to another time','C'),
  mc(3,'The PERFECT aspect emphasizes:','a simple fact','an ongoing process','connection between two time points','a habit','C'),
  mc(4,'"I have been working here for 5 years" — which aspects are combined?','Simple + Continuous','Perfect + Continuous','Simple + Perfect','Simple only','B'),
  mc(5,'Why use Perfect Continuous rather than Perfect Simple?','to state a completed quantity','to emphasize both duration and the ongoing nature','to express a simple fact','to show past state','B'),
  mc(6,'Which shows the RESULT of a completed action?','I was running.','I have run 5km today.','I run every day.','I had been running.','B'),
  mc(7,'"She has been crying." What does the continuous aspect add?','A specific number','Duration/ongoing nature (visible effect now)','A completed result','A past habit','B'),
  mc(8,'"They used to argue" — the Simple aspect shows:','an ongoing action','a habit/state (complete unit)','a connection to the present','duration before now','B'),
  mc(9,'Which sentence uses Perfect Simple to express a completed number?','I have been reading all day.','I have read five books this month.','I had been reading when she called.','I was reading yesterday.','B'),
  mc(10,'Complete: "He ___ three reports since Monday." (completed items, number)','has been writing','has written','wrote','was writing','B'),
  tf(11,'The Perfect Continuous can emphasize both duration and a connection to another time.','true'),
  tf(12,'"I am knowing the answer" is correct because "know" can be dynamic.','false'),
  tf(13,'The Simple aspect can be used for habits, facts, and single completed events.','true'),
  fb(14,'She ___ (has written) ten novels during her career. (completed number)','has written'),
  fb(15,'He ___ (has been exercising) every day for a year. (duration + ongoing)','has been exercising'),
]},

'ca37a2fa-c8d6-4996-bc5a-a29ef75edda8':{pass_threshold:80,questions:[
  mc(1,'Present Continuous Passive: "The bridge ___ repaired."','is','is being','has been','was being','B'),
  mc(2,'Past Perfect Continuous: "She ___ all day before she collapsed."','worked','was working','has been working','had been working','D'),
  mc(3,'Choose: "By the time I arrived, they ___ the meeting."','started','were starting','have started','had already started','D'),
  mc(4,'Present Perfect Simple vs Continuous: "I ___ five emails." (completed number)','have been writing','have written','was writing','wrote','B'),
  mc(5,'Past Continuous: "While he ___, she cooked dinner."','reads','read','was reading','has read','C'),
  mc(6,'Present Perfect Passive: "Several errors ___ found."','are','were','have been','had been','C'),
  mc(7,'"She looked tired because she ___ all night." (duration before past moment)','worked','was working','had been working','has worked','C'),
  mc(8,'Which tense is used for a completed past action at a specific time?','Past Continuous','Past Perfect','Past Simple','Present Perfect','C'),
  mc(9,'Complete: "How long ___ you ___ for us?"','are / waiting','have / waited','have / been waiting','were / waiting','C'),
  mc(10,'Past Perfect Passive: "The documents ___ before the trial."','were destroyed','are destroyed','had been destroyed','have been destroyed','C'),
  mc(11,'Present Continuous for future: "She ___ the dentist tomorrow."','see','sees','is seeing','has seen','C'),
  mc(12,'Choose the correct pair for narrative: "I (sleep) when the alarm (ring)."','slept / rang','was sleeping / rang','have slept / rang','slept / was ringing','B'),
  mc(13,'"I have been to Paris" vs "I have gone to Paris" — what is the difference?','No difference','First = visited and came back; Second = is there now','First = will visit; Second = visited','First = went; Second = returned','B'),
  mc(14,'Complete: "The building ___ been completed by December." (future perfect passive)','has','will have','will be','would be','B'),
  mc(15,'Which tense emphasizes an ongoing process with visible effect now?','Past Simple','Present Perfect Simple','Present Perfect Continuous','Past Perfect Simple','C'),
  tf(16,'"The evidence had been destroyed before the police arrived" is Past Perfect Passive.','true'),
  tf(17,'Stative verbs like "know" and "believe" can be used in Present Perfect Continuous.','false'),
  tf(18,'Past Perfect Simple and Past Perfect Continuous can both appear in the same text.','true'),
  fb(19,'She ___ (had been waiting) for over an hour when the doctor finally called her.','had been waiting'),
  fb(20,'Three new schools ___ (have been built) in this region this year.','have been built'),
]},

// ── MODULE 4: Tenses Mastery II ─────────────────────────────────────────────

'a8c8ee87-c9e5-4a62-b904-042274f433ce':{pass_threshold:70,questions:[
  mc(1,'"Will" is used for:','pre-planned intentions','evidence-based predictions and spontaneous decisions','scheduled events','arrangements made in advance','B'),
  mc(2,'"Going to" is used for:','spontaneous decisions','intentions and evidence-based predictions','expressing facts','polite requests','B'),
  mc(3,'Complete: "Look at those clouds! It ___ rain."','will','is going to','rains','has rained','B'),
  mc(4,'Someone calls. You decide to answer. Complete: "I ___ get it!"','am going to','was going to','will','am getting','C'),
  mc(5,'Complete: "She ___ study medicine. She\'s already applied." (prior plan)','will','was going to','is going to','studies','C'),
  mc(6,'Complete: "I promise I ___ be late."','am not going to','won\'t','am not','don\'t','B'),
  mc(7,'Which expresses a PROMISE?','I am going to help you.','I will help you.','I am helping you.','I help you.','B'),
  mc(8,'Complete: "He ___ become a doctor." (based on evidence of his studies/talent)','will','going to','is going to','shall','C'),
  mc(9,'Which expresses a PRE-PLANNED intention?','I will call you later.','I\'m going to call him — I\'ve already found his number.','I shall call him.','I am calling him.','B'),
  mc(10,'Difference between "will" and "going to" for predictions:','No difference','Will = personal opinion/feeling; Going to = evidence-based','Will = certain; Going to = uncertain','Will = future; Going to = present','B'),
  tf(11,'"Will" and "going to" are always interchangeable for predictions.','false'),
  tf(12,'"Shall" is used with "I" and "we" in formal/British English for offers or suggestions.','true'),
  tf(13,'"I am going to have dinner tonight" can express a prior decision.','true'),
  fb(14,'I ___ (will) definitely help you with that report.','will'),
  fb(15,'She ___ (is going to) take a year off. She\'s already booked the flights.','is going to'),
]},

'251b8cda-dd35-40ec-871a-9d650fc4e4e7':{pass_threshold:70,questions:[
  mc(1,'Future Continuous is formed with:','will + infinitive','will + be + -ing','will + have + past participle','will + have been + -ing','B'),
  mc(2,'Future Continuous is used for:','completed future actions','actions in progress at a specific future moment','actions completed before a future moment','past future plans','B'),
  mc(3,'Complete: "At this time tomorrow, I ___ on the beach."','will lie','will be lying','will have lied','will have been lying','B'),
  mc(4,'Future Continuous can be used for:','polite questions about someone\'s future plans','urgent commands','past regrets','general facts','A'),
  mc(5,'Complete: "Will you ___ passing the post office later?" (polite inquiry)','be','have','have been','have been being','A'),
  mc(6,'Complete: "Don\'t call at 8pm. We ___ dinner."','will have','will be having','will have had','are having','B'),
  mc(7,'Which does NOT describe Future Continuous usage?','action in progress at a future moment','polite question about plans','completed action before a future point','parallel future actions','C'),
  mc(8,'Complete: "This time next year, she ___ in New York."','will work','will be working','will have worked','works','B'),
  mc(9,'Future Continuous for parallel actions: "While you ___,  I ___ the table."','will cook / set','will be cooking / will be setting','cook / set','cooked / set','B'),
  mc(10,'Complete: "Will you ___ by the shop? Can you get some milk?"','pass','be passing','have passed','have been passing','B'),
  tf(11,'Future Continuous can make a future question sound more polite.','true'),
  tf(12,'"I will be knowing the result tomorrow" is grammatically correct.','false'),
  tf(13,'"At midnight I will be sleeping" describes an action in progress at a future point.','true'),
  fb(14,'This time tomorrow we ___ (will be flying) over the Atlantic.','will be flying'),
  fb(15,'Will you ___ (be attending) the conference next week?','be attending'),
]},

'9196f443-0383-4aad-89c0-4961830a9346':{pass_threshold:70,questions:[
  mc(1,'Future Perfect is formed with:','will + be + -ing','will + have + past participle','will + infinitive','would + past participle','B'),
  mc(2,'Future Perfect expresses:','an action in progress at a future moment','an action that will be completed BEFORE a future point','a past prediction','an ongoing future state','B'),
  mc(3,'Complete: "By Friday, she ___ the report."','will finish','will be finishing','will have finished','is finishing','C'),
  mc(4,'Which time expression is typical with Future Perfect?','at this time tomorrow','while','by next year','since then','C'),
  mc(5,'Complete: "By the time you arrive, I ___ already ___."','will / leave','will be / leaving','will have / left','am / leaving','C'),
  mc(6,'Complete: "They ___ the project by December."','finish','will finish','will have finished','will be finishing','C'),
  mc(7,'Future Perfect Passive: "The bridge ___ by 2030."','will build','will be building','will have been built','will be built','C'),
  mc(8,'Complete: "Don\'t call at 9 — she ___ to sleep by then."','will go','will be going','will have gone','goes','C'),
  mc(9,'Which sentence correctly uses Future Perfect?','I will finish by Monday.','I will have finished by Monday.','I am finishing by Monday.','I would finish by Monday.','B'),
  mc(10,'Complete: "In two years, he ___ his degree."','will complete','will be completing','will have completed','completes','C'),
  tf(11,'"By" is the most common time marker used with Future Perfect.','true'),
  tf(12,'"I will have been there" is Future Perfect.','true'),
  tf(13,'"She will have finish" is grammatically correct.','false'),
  fb(14,'By the time the film starts, we ___ (will have found) our seats.','will have found'),
  fb(15,'She ___ (will have lived) here for 20 years by next June.','will have lived'),
]},

'4b7df772-5b34-4542-a2a5-e2be2518f636':{pass_threshold:70,questions:[
  mc(1,'Future Perfect Continuous is formed with:','will + be + -ing','will + have + past participle','will + have been + -ing','would + have been + -ing','C'),
  mc(2,'Future Perfect Continuous emphasizes:','a completed future action','the duration of an action up to a future point','an action in progress at a future moment','a past prediction','B'),
  mc(3,'Complete: "By 2030, we ___ in this house for 20 years."','will live','will be living','will have been living','will have lived','C'),
  mc(4,'Key difference: Future Perfect vs Future Perfect Continuous?','No difference','Perfect = completion/result; Perfect Continuous = duration/process','Perfect = more formal','Perfect Continuous = single event','B'),
  mc(5,'Complete: "By the time he retires, he ___ for the company for 35 years."','will work','will be working','will have worked','will have been working','D'),
  mc(6,'Which time expression is typical with Future Perfect Continuous?','at this time','by + future time + for + duration','yet','just','B'),
  mc(7,'Complete: "In June, they ___ for six months."','will be dating','will date','will have been dating','will have dated','C'),
  mc(8,'Which emphasizes the PROCESS and DURATION rather than completion?','She will have written three novels.','She will have been writing all day.','She will write a novel.','She will be writing a novel.','B'),
  mc(9,'Complete: "By tomorrow, I ___ on this essay for a week."','will be working','will have been working','will work','will have worked','B'),
  mc(10,'Future Perfect Continuous is often used with:','specific times in the future','expressions of duration ("for X years")','simple future facts','polite questions','B'),
  tf(11,'Future Perfect Continuous can be used with stative verbs like "know."','false'),
  tf(12,'"By next year, she will have been studying here for three years" is correct.','true'),
  tf(13,'Future Perfect and Future Perfect Continuous always have the same meaning.','false'),
  fb(14,'By graduation, he ___ (will have been studying) for six years.','will have been studying'),
  fb(15,'In December, they ___ (will have been working) together for a decade.','will have been working'),
]},

'96dc0bf6-992d-4a4b-a1b3-0e63274408b1':{pass_threshold:70,questions:[
  mc(1,'"Was/were going to" (Future in the Past) expresses:','current plans','past intentions or plans that may not have happened','future certainties','polite requests','B'),
  mc(2,'Complete: "I ___ call you, but I forgot."','am going to','was going to','will','was about to','B'),
  mc(3,'"Was about to" means:','a plan that was made long ago','an action that was on the verge of happening','a repeated past habit','a future prediction','B'),
  mc(4,'Complete: "She ___ to start the meeting when the fire alarm went off."','is about','was about','will be about','has been about','B'),
  mc(5,'"Was supposed to" implies:','an obligation or arrangement that was expected but may not have occurred','a strong future plan','a past achievement','a completed action','A'),
  mc(6,'Complete: "He ___ to present first, but he fell ill."','is supposed','was supposed','will be supposed','has been supposed','B'),
  mc(7,'"Was due to" is used for:','officially scheduled events that did or didn\'t happen','general past habits','strong future intentions','polite questions','A'),
  mc(8,'Complete: "The train ___ arrive at 6pm, but it was delayed."','was due to','was going to','would','is due to','A'),
  mc(9,'Which expresses a PAST INTENTION that was NOT fulfilled?','I went to the gym.','I was going to go to the gym, but I was tired.','I usually go to the gym.','I have gone to the gym.','B'),
  mc(10,'Complete: "They ___ launch the product in May, but funding fell through."','were going to','are going to','will','would to','A'),
  tf(11,'"Was going to" always means the action did NOT happen.','false'),
  tf(12,'"Was about to" suggests the action was imminent in the past.','true'),
  tf(13,'"Was supposed to" can imply that the expected action didn\'t actually happen.','true'),
  fb(14,'I ___ (was going to) call you, but something came up.','was going to'),
  fb(15,'The concert ___ (was supposed to) start at 8, but was delayed.','was supposed to'),
]},

'15d65c6c-5288-4d14-b906-f67c367bc048':{pass_threshold:70,questions:[
  mc(1,'Present Simple can be used for future in:','personal arrangements','timetables and schedules','spontaneous decisions','ongoing present actions','B'),
  mc(2,'Complete: "The flight ___ at 7am tomorrow." (timetable)','will leave','is leaving','leaves','is going to leave','C'),
  mc(3,'Present Continuous is used for future when:','expressing a timetable','making a spontaneous decision','talking about a personal arrangement','expressing a general fact','C'),
  mc(4,'Complete: "I ___ (meet) Sarah for lunch tomorrow." (arrangement)','meet','will meet','am meeting','am going to meet','C'),
  mc(5,'In conditional clauses, we use ___ to refer to the future:','will','going to','Present Simple','Future Continuous','C'),
  mc(6,'Complete: "If she ___ early, we can go out." (conditional, future)','will come','comes','come','is going to come','B'),
  mc(7,'In time clauses (when, as soon as, until), we use:','will + infinitive','Present Simple for future meaning','Future Perfect','going to','B'),
  mc(8,'Complete: "As soon as he ___, I\'ll tell him." (time clause)','will arrive','is going to arrive','arrives','arrived','C'),
  mc(9,'Which sentence uses Present Continuous for future?','She flies to Rome.','She is flying to Rome tomorrow.','She will fly to Rome.','She flies to Rome tomorrow.','B'),
  mc(10,'Which uses Present Simple for a scheduled future?','I am seeing the dentist tomorrow.','I will see the dentist.','The dentist opens at 9am.','I plan to see the dentist.','C'),
  tf(11,'Present Simple can refer to the future in timetable and schedule contexts.','true'),
  tf(12,'"When she will arrive, I\'ll call you" is grammatically correct.','false'),
  tf(13,'Present Continuous for future implies a prior arrangement.','true'),
  fb(14,'The train ___ (departs) at 6:15 tomorrow morning. (timetable)','departs'),
  fb(15,'As soon as the results ___ (are announced), I\'ll let you know.','are announced'),
]},

'909cb88f-92ae-458d-98af-849e5c8916ed':{pass_threshold:70,questions:[
  mc(1,'Choose: "Look out! You ___ drop that vase!"','are going to','will','would','shall','A'),
  mc(2,'Choose: "At 8pm tomorrow, she ___ dinner."','will have','will be having','has','will have had','B'),
  mc(3,'Choose: "By Friday, I ___ the project."','will finish','will be finishing','will have finished','finish','C'),
  mc(4,'Choose: "The concert ___ at 8pm." (timetable)','will start','starts','is starting','is going to start','B'),
  mc(5,'Choose: "I ___ call you back." (spontaneous decision)','am going to','will','am','shall','B'),
  mc(6,'Choose: "She ___ to become a surgeon. She\'s registered already."','will','is going to','shall','would','B'),
  mc(7,'Choose: "She ___ waiting when we arrive." (in progress at that moment)','will be','will have been','is','will','A'),
  mc(8,'Choose: "By 2030, renewable energy ___ coal." (completion before future point)','will replace','will be replacing','will have replaced','replaces','C'),
  mc(9,'Choose: "In June, I ___ here for ten years." (duration to future point)','will work','will be working','will have worked','will have been working','D'),
  mc(10,'Choose: "___ you ___ the office tomorrow? Can you pass on a message?"','Will / pass','Will / be passing','Are / passing','Do / pass','B'),
  tf(11,'In time clauses with "when" and "until," we use Present Simple for future meaning.','true'),
  tf(12,'"Will" is the only way to express future in English.','false'),
  tf(13,'Future Perfect Continuous emphasizes duration up to a future point.','true'),
  fb(14,'She ___ (is going to) take a gap year — she\'s already deferred her place.','is going to'),
  fb(15,'By the time you wake up, the flight ___ (will have landed).','will have landed'),
]},

'4f613afc-92bb-4d27-9219-3a63a0d72976':{pass_threshold:80,questions:[
  mc(1,'"Will" is used for spontaneous decisions; "going to" is used for:','evidence-based predictions and prior plans','formal writing only','scheduled timetables only','polite requests','A'),
  mc(2,'Future Continuous emphasizes:','a completed future action','an action in progress at a specific future moment','duration up to a future point','a past plan','B'),
  mc(3,'Future Perfect emphasizes:','duration','an action completed BEFORE a future point','an action in progress','a prior intention','B'),
  mc(4,'Future Perfect Continuous emphasizes:','completion','duration of action up to a future point','a timetable event','a spontaneous decision','B'),
  mc(5,'Choose: "At noon tomorrow, they ___ the ceremony."','will start','will have started','will be starting','start','C'),
  mc(6,'Choose: "By graduation, she ___ for four years."','will study','will be studying','will have been studying','will have studied','C'),
  mc(7,'Present Simple for future is used in:','personal arrangements','spontaneous decisions','timetables and conditional clauses','promises','C'),
  mc(8,'Complete: "If he ___ in time, call me." (conditional + time clause)','will arrive','arrives','arriving','arrived','B'),
  mc(9,'"Was going to" expresses:','a current plan','a past intention (may not have occurred)','a completed past event','a future certainty','B'),
  mc(10,'Complete: "She ___ to give the speech, but she got stage fright."','is supposed','was supposed','will be supposed','has been supposed','B'),
  mc(11,'Choose: "The match ___ at 3pm." (timetable, Present Simple)','will kick off','is kicking off','kicks off','kicked off','C'),
  mc(12,'Future Continuous for polite questions: "Will you ___ through town later?"','pass','be passing','have passed','have been passing','B'),
  mc(13,'Choose: "By next month, he ___ in this job for a decade."','will work','will be working','will have been working','will have worked','C'),
  mc(14,'Which does NOT fit Future Perfect usage?','By then, I will have finished.','By 2025, she will have graduated.','At this time next year, he will have working.','They will have built the bridge by March.','C'),
  mc(15,'"Was about to" means the action was:','planned long ago','on the verge of happening in the past','completed successfully','a general past habit','B'),
  tf(16,'"Will" can express both predictions and promises.','true'),
  tf(17,'"I will have been knowing her for years" is grammatically correct.','false'),
  tf(18,'"As soon as she arrives, I will call you" is correct (Present Simple in time clause).','true'),
  fb(19,'Don\'t call at 9pm — I ___ (will be watching) the game.','will be watching'),
  fb(20,'By the time the guests arrive, we ___ (will have prepared) everything.','will have prepared'),
]},

};

// ─────────────────────────────────────────────────────────────────────────────

const MODULES = [
  { name: 'Module 1: "Emotions & Communication"', lessons: ['abb37b9f-a622-482b-8dec-901495984f23','5e3a2d0e-934a-4dab-b0a1-9f043a0efff6','bd2bd64e-d28c-4117-bf05-93d2913ef97b','f4325002-cc0c-4af5-a968-aac5648c306d','9f093196-66ef-4457-8ef1-84e0d3fe3d45','9e69ad92-8df2-498a-aba0-006034fa7183','4dac3f57-3455-4ffe-8228-7d8dfbad16cb','1106f690-7328-409b-a52e-4e7a48800dd1'] },
  { name: 'Module 2: "Dreams & Ambitions"', lessons: ['819a7e71-e718-4a50-87aa-5b9d087ff64a','e6d4d065-e413-42ab-ada1-0ffa9171c4e7','8f3a8937-dda5-4167-8536-08a0863593cb','3e7182c5-6f34-4a4c-8971-c5338dc5738c','c59a63d2-eaf9-4309-904b-6815d471df1a','8e141574-db24-4416-9b5a-e26b886470ab','46f78b04-1a2f-428c-bbf5-236fe91156c0','06086034-40a2-4f90-a9d8-5ffac67d72ad'] },
  { name: 'Module 3: "Tenses Mastery I"', lessons: ['a0d8ce6f-a276-409f-b16a-2b4c6e1ad93f','63930411-93a2-4287-a180-1455488c8049','9df44735-9961-40cc-b944-834f15b80905','641b3278-767b-4f0f-b707-cf3f225d58ff','2c235e1d-ffe1-43c7-8a08-6c89edbf2e83','fafa1219-aa4c-47ab-bcab-9d1ba2c5dea9','0bfdf045-0228-4627-bac8-b4f7f38f7a73','1ddaedaf-ce10-4d66-9618-517423b0cea4','ca37a2fa-c8d6-4996-bc5a-a29ef75edda8'] },
  { name: 'Module 4: "Tenses Mastery II"', lessons: ['a8c8ee87-c9e5-4a62-b904-042274f433ce','251b8cda-dd35-40ec-871a-9d650fc4e4e7','9196f443-0383-4aad-89c0-4961830a9346','4b7df772-5b34-4542-a2a5-e2be2518f636','96dc0bf6-992d-4a4b-a1b3-0e63274408b1','15d65c6c-5288-4d14-b906-f67c367bc048','909cb88f-92ae-458d-98af-849e5c8916ed','4f613afc-92bb-4d27-9219-3a63a0d72976'] },
];

async function main(){
  for(const mod of MODULES){
    console.log(`\n🔍 B2 — ${mod.name}`);
    const {data:existing}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',mod.lessons);
    const have=new Set((existing||[]).map((r:any)=>r.lesson_id));
    const missing=mod.lessons.filter(id=>!have.has(id));
    console.log(`📋 Total: ${mod.lessons.length} | ✅ Have: ${have.size} | ❌ Missing: ${missing.length}`);
    for(const lessonId of missing){
      const quiz=QUIZZES[lessonId];
      if(!quiz){console.log(`  ⚠️  No quiz data for ${lessonId}`);continue;}
      const {data:lesson}=await supabase.from('english_lessons').select('title').eq('id',lessonId).single();
      const {error}=await supabase.from('english_quizzes').insert({lesson_id:lessonId,questions:quiz.questions,pass_threshold:quiz.pass_threshold});
      if(error)console.error(`  ❌ Error for ${lessonId}:`,error.message);
      else console.log(`  ✅ Вставлен квиз: ${lesson?.title} — ${quiz.questions.length} вопросов`);
    }
  }
  console.log('\n✅ Готово: модули 1–4 B2 Upper-Intermediate');
}
main();
