/**
 * Seed quizzes — B1 Intermediate — Modules 1, 2, 3.
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-b1-mod1-3.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // ═══ MODULE 1: Real World English ═══

  '9e0ac15f-76ff-458c-ae33-0966b9c2a7f5':{pass_threshold:70,questions:[ // Gerunds & Infinitives
    mc(1,'Complete: "She avoided ___ (make) eye contact during the interview."','to make','makes','making','made','C'),
    mc(2,'Complete: "He agreed ___ (submit) the report by Friday."','submitting','submit','to submit','submitted','C'),
    mc(3,'Which verb is always followed by gerund?','want','decide','mind','plan','C'),
    mc(4,'Which verb is always followed by infinitive?','enjoy','finish','refuse','avoid','C'),
    mc(5,'Complete: "They suggested ___ (hold) the meeting online."','to hold','hold','holding','held','C'),
    mc(6,'Complete: "I stopped ___ (check) my phone during lectures." (I no longer check)','to check','check','checking','checked','C'),
    mc(7,'Complete: "She remembered ___ (send) the email." (she sent it)','to send','send','sending','sent','C'),
    mc(8,'Complete: "I remember ___ (attend) that lecture." (I recall the memory)','to attend','attend','attending','attended','C'),
    mc(9,'After prepositions we use:','infinitive with to','base form','gerund (-ing)','past participle','C'),
    mc(10,'Complete: "He is keen on ___ (improve) his academic writing."','to improve','improve','improving','improved','C'),
    tf(11,'"I enjoy to swim" is grammatically correct.','false'),
    tf(12,'"She stopped to talk" means she stopped in order to talk (purpose).','true'),
    tf(13,'After "look forward to", we use the gerund.','true'),
    fb(14,'She decided ___ (apply) for the scholarship. He enjoys ___ (conduct) research.','to apply, conducting'),
    fb(15,'I\'m looking forward to ___ (present) my findings. They avoided ___ (commit) to a deadline.','presenting, committing'),
  ]},

  '72f93ef7-48a0-4720-bd0a-a970f9365a69':{pass_threshold:70,questions:[ // Present Simple vs Continuous Review
    mc(1,'Which sentence describes a permanent fact?','She is working in a lab right now.','She works at the university.','She has worked there.','She was working yesterday.','B'),
    mc(2,'Which sentence describes a temporary situation?','He usually cycles to work.','He is taking the bus this week.','He took the bus yesterday.','He will cycle tomorrow.','B'),
    mc(3,'Complete: "This semester, we ___ (study) postcolonial theory."','study','studied','are studying','have studied','C'),
    mc(4,'Which verb is stative and NOT used in continuous form?','run','eat','believe','write','C'),
    mc(5,'Complete: "The university ___ (offer) a new MA programme each year."','is offering','was offering','offers','offered','C'),
    mc(6,'Complete: "She ___ (increasingly/rely) on digital sources." (current trend)','increasingly relies','is increasingly relying','relied increasingly','will increasingly rely','B'),
    mc(7,'Which signals Present Continuous?','always','usually','currently','every semester','C'),
    mc(8,'Complete: "I ___ (not/understand) your argument — can you clarify?"','am not understanding','don\'t understand','haven\'t understood','didn\'t understand','B'),
    mc(9,'"Know", "believe", "own" are:','action verbs used in continuous','stative verbs not normally used in continuous','irregular verbs','auxiliary verbs','B'),
    mc(10,'Complete: "She ___ (give) a keynote address at the conference next week." (arranged future)','gives','is giving','gave','will be giving','B'),
    tf(11,'"She is knowing the answer" is correct.','false'),
    tf(12,'Present Continuous can describe a changing or developing situation.','true'),
    tf(13,'"He always leaves early" is a correct use of Present Simple for habits.','true'),
    fb(14,'She ___ (work, current project) on her dissertation this term. She usually ___ (write) in the mornings.','is working, writes'),
    fb(15,'I ___ (not/believe) his explanation. The department ___ (expand, current trend) its research output.','don\'t believe, is expanding'),
  ]},

  '532c1314-b9db-49b8-93ac-9059da7e470f':{pass_threshold:70,questions:[ // Present Perfect Simple
    mc(1,'Present Perfect is formed with:','subject + did + pp','subject + have/has + pp','subject + am/is + pp','subject + will + pp','B'),
    mc(2,'Complete: "She ___ (publish) three peer-reviewed articles this year."','published','has published','publishes','had published','B'),
    mc(3,'Which signals Present Perfect?','yesterday','last semester','in 2019','recently','D'),
    mc(4,'Complete: "The research team ___ (not/release) its findings yet."','didn\'t release','hasn\'t released','doesn\'t release','won\'t release','B'),
    mc(5,'Complete: "Have you ___ (read) Chomsky\'s latest book?"','read','reads','reading','readed','A'),
    mc(6,'Choose correct: "___ she ___ (submit) her thesis?"','Did / submit','Has / submitted','Is / submitting','Does / submit','B'),
    mc(7,'Complete: "I ___ (just/receive) the reviewer\'s feedback."','just received','have just received','just receives','just receiving','B'),
    mc(8,'Complete: "The professor ___ (teach) here since 2010."','taught','teaches','has taught','had taught','C'),
    mc(9,'What is the past participle of "write"?','wrote','writed','written','writing','C'),
    mc(10,'Complete: "This is the most compelling argument I ___ (ever/encounter)."','ever encountered','have ever encountered','ever encounter','was ever encountering','B'),
    tf(11,'Present Perfect connects a past action to the present.','true'),
    tf(12,'"She has published in 2020" is correct because 2020 is in the past.','false'),
    tf(13,'"Just", "already", "yet", "ever", "never" are common with Present Perfect.','true'),
    fb(14,'She ___ (already/complete) her literature review. I ___ (never/attend) a conference abroad.','has already completed, have never attended'),
    fb(15,'___ you ___ (submit) your assignment? No, I ___ (not/finish) yet.','Have, submitted, haven\'t finished'),
  ]},

  '57f7728c-5541-42d9-b9c9-b1d36ea29139':{pass_threshold:70,questions:[ // Present Perfect Continuous
    mc(1,'Present Perfect Continuous is formed with:','have/has + been + verb-ing','have/has + verb-ing','have/has + pp','had + been + verb-ing','A'),
    mc(2,'We use Present Perfect Continuous to emphasise:','a completed action','an action at a specific past time','the duration or continuity of an ongoing activity','a future event','C'),
    mc(3,'Complete: "She ___ (work) on her dissertation for six months."','worked','has worked','has been working','was working','C'),
    mc(4,'Complete: "I ___ (review) literature all morning — I\'m exhausted."','reviewed','have reviewed','have been reviewing','was reviewing','C'),
    mc(5,'Which is more likely with Present Perfect Continuous?','I have written three chapters.','I have been writing all week.','She has submitted the paper.','He has published the article.','B'),
    mc(6,'Complete: "The committee ___ (deliberate) since 9 am."','deliberated','has deliberated','has been deliberating','is deliberating','C'),
    mc(7,'Complete: "How long ___ he ___ (lecture) at this university?"','did / lecture','has / lectured','has / been lecturing','is / lecturing','C'),
    mc(8,'Which time expression is typical with PP Continuous?','yesterday','last year','for three hours / since Monday','in 2020','C'),
    mc(9,'Complete: "They ___ (negotiate) the contract for weeks — they hope to finalise it soon."','negotiated','have negotiated','have been negotiating','were negotiating','C'),
    mc(10,'Choose: "She has written 40 pages" vs "She has been writing all day." The first emphasises:','the process','the duration','the completed result','how long','C'),
    tf(11,'Present Perfect Continuous is formed with have/has + been + verb-ing.','true'),
    tf(12,'Present Perfect Continuous always means the action is still ongoing.','false'),
    tf(13,'"For" and "since" are common with Present Perfect Continuous.','true'),
    fb(14,'I ___ (study, PP Cont.) this topic for two years. How long ___ you ___ (research) this area?','have been studying, have, been researching'),
    fb(15,'The team ___ (collect, PP Cont.) data since January. She ___ (write, PP Cont.) her thesis all semester.','has been collecting, has been writing'),
  ]},

  '211bdfaa-f950-4fd8-b38f-0b9695cc84f3':{pass_threshold:70,questions:[ // Stative Verbs
    mc(1,'Which is a stative verb?','run','write','belong','eat','C'),
    mc(2,'Why are stative verbs not normally used in continuous tense?','They are irregular','They describe states, not actions','They are always intransitive','They are only in past tense','B'),
    mc(3,'Which sentence is correct?','She is knowing the answer.','She knows the answer.','She is knowing answer.','She knowing the answer.','B'),
    mc(4,'Choose the stative verb: "I ___ your argument, but I disagree."','am understanding','understand','am understand','will understand','B'),
    mc(5,'Which CAN be used in continuous (has an action meaning)?','know','believe','have (possess)','see (perceive)','C'),
    mc(6,'Complete: "She ___ the new methodology better now." (come to understand)','is understanding','understands','was understanding','understand','B'),
    mc(7,'Which is stative?','She is reading','She is believing that','She believes that','She believes in reading','C'),
    mc(8,'Complete: "This argument ___ (seem) unconvincing."','is seeming','seems','seem','was seeming','B'),
    mc(9,'Which verb has BOTH stative and active meanings?','know','think (= believe)','see','belong','B'),
    mc(10,'Complete: "I ___ (think) about the methodology right now." (active — process of thinking)','think','am thinking','thought','have thought','B'),
    tf(11,'Stative verbs describe states or conditions, not actions.','true'),
    tf(12,'"I am knowing the answer" is correct.','false'),
    tf(13,'"She is having dinner" is correct because "have" here is an action verb.','true'),
    fb(14,'"I ___ (think) this theory is flawed." (state/opinion) "She ___ (think, active) about changing her approach."','think, is thinking'),
    fb(15,'"The data ___ (appear) to support the hypothesis." "He ___ (see, active) a specialist next week."','appears, is seeing'),
  ]},

  'e365ed87-bf7c-4b33-b937-d37724291810':{pass_threshold:70,questions:[ // Online Communication — Vocabulary
    mc(1,'What does "to go viral" mean?','to become ill','to spread rapidly online and reach a large audience','to crash a website','to delete content','B'),
    mc(2,'What is "clickbait"?','useful online content','content designed to attract clicks by being sensational or misleading','a type of malware','a subscription service','B'),
    mc(3,'What does "algorithm" refer to in social media?','a type of password','a set of rules that determines what content users see','the number of followers','a type of post format','B'),
    mc(4,'What is a "troll" online?','someone who posts helpful advice','someone who deliberately provokes or upsets others online','someone who moderates content','someone who creates viral content','B'),
    mc(5,'What does "to unsubscribe" mean?','to subscribe to more content','to cancel a subscription or stop receiving messages','to share content','to save content offline','B'),
    mc(6,'What is "user-generated content" (UGC)?','content created by platform companies','content created by the platform\'s users','paid advertising content','content that generates revenue','B'),
    mc(7,'What does "engagement" measure in social media?','number of accounts','likes, comments, shares, and interactions with content','the age of users','the file size of posts','B'),
    mc(8,'What is a "hashtag"?','a type of malware','a word or phrase preceded by # used to categorise content','a private message','a type of profile','B'),
    mc(9,'What does "DM" stand for?','digital media','direct message','data management','digital marketing','B'),
    mc(10,'What is "phishing"?','catching fish online','a type of online scam to steal personal information','a social media strategy','a podcast format','B'),
    tf(11,'"Going viral" means content spreads very rapidly online.','true'),
    tf(12,'"Clickbait" refers to highly credible and informative online content.','false'),
    tf(13,'A hashtag is used to categorise or label social media content.','true'),
    fb(14,'Content that spreads rapidly is said to "___ (go) viral". A "___ (troll)" deliberately provokes others online.','go, troll'),
    fb(15,'An "___ (algorithm)" determines what content you see. "___ (Phishing)" is a scam to steal personal data.','algorithm, Phishing'),
  ]},

  '934b5c57-ffad-45a0-982f-2b846d590948':{pass_threshold:70,questions:[ // Digital World — Collocations
    mc(1,'Which is the correct collocation?','make a website','build a website','do a website','create a website (both A and D)','D'),
    mc(2,'Which is correct?','do research online','make research online','take research online','conduct research online (both A and D)','D'),
    mc(3,'Which is correct?','make a search','do a search / run a search','take a search','get a search','B'),
    mc(4,'Which is correct?','download a file','upload a file (share to cloud)','both A and B are correct collocations','Neither','C'),
    mc(5,'Which is correct?','make a post','post a message','both A and B','take a post','C'),
    mc(6,'Which is correct?','do a mistake online','make a mistake online','take a mistake online','get a mistake online','B'),
    mc(7,'Which is correct?','make a password','create a password','do a password','take a password','B'),
    mc(8,'Which collocation means to read emails quickly?','make your inbox','scan your inbox','do your inbox','take your inbox','B'),
    mc(9,'Which is correct?','make a backup','do a backup','run a backup','both B and C','D'),
    mc(10,'Which is correct?','do a video call','make a video call','take a video call','get a video call','B'),
    tf(11,'"Conduct research" is a correct collocation.','true'),
    tf(12,'"Do a mistake" is the correct collocation in English.','false'),
    tf(13,'"Make a video call" is the correct collocation.','true'),
    fb(14,'She ___ (make/do) a video call every week. He ___ (upload/download) the file from the cloud.','makes, uploaded / downloaded'),
    fb(15,'They ___ (conduct/make) research online. I need to ___ (make/do) a backup of my data.','conduct, make / do'),
  ]},

  '9561d0e6-402f-41b7-aaa4-828cee9ea290':{pass_threshold:80,questions:[ // Module 1 Review
    mc(1,'Complete: "She avoided ___ (discuss) the controversial findings."','to discuss','discuss','discussing','discussed','C'),
    mc(2,'Complete: "He agreed ___ (present) at the conference."','presenting','present','to present','presented','C'),
    mc(3,'Stative verb — choose correct:','She is knowing the answer.','She knows the answer.','She is knowing.','She know the answer.','B'),
    mc(4,'PP Simple: "She ___ (publish) two papers this year."','published','publishes','has published','had published','C'),
    mc(5,'PP Continuous: "They ___ (work) on the prototype for months."','worked','have worked','have been working','are working','C'),
    mc(6,'Which signals PP Continuous?','yesterday','in 2020','for three months','last week','C'),
    mc(7,'Choose correct (habit): "He ___ (lecture) every Tuesday."','is lecturing','lectured','lectures','was lecturing','C'),
    mc(8,'Choose correct (current project): "She ___ (write) a monograph this year."','writes','wrote','is writing','was writing','C'),
    mc(9,'What does "go viral" mean?','crash a site','spread rapidly online','become popular slowly','delete content','B'),
    mc(10,'Correct collocation:','do a video call','make a video call','take a video call','get a video call','B'),
    mc(11,'"Think" can be both stative and active. "She ___ about the problem right now." (active)','thinks','thought','is thinking','has thought','C'),
    mc(12,'PP Simple: "___ you ___ (submit) your ethics form?"','Did / submit','Have / submitted','Are / submitting','Do / submit','B'),
    mc(13,'PP Continuous: "How long ___ you ___ (work) on this research?"','did / work','have / worked','have / been working','are / working','C'),
    mc(14,'What is "phishing"?','fishing online','a social media strategy','a scam to steal personal info','a podcast format','C'),
    mc(15,'Which verb is stative?','run','write','belong','eat','C'),
    tf(16,'"I am knowing the answer" is correct.','false'),
    tf(17,'Present Perfect Continuous uses have/has + been + verb-ing.','true'),
    tf(18,'"Clickbait" refers to sensational content designed to attract clicks.','true'),
    fb(19,'She ___ (enjoy, gerund) ___ (conduct) interviews. He decided ___ (publish, infinitive) his results.','enjoys, conducting, to publish'),
    fb(20,'They ___ (work, PP Cont.) on this project for two years. She ___ (publish, PP Simple) 5 articles.','have been working, has published'),
  ]},

  // ═══ MODULE 2: Love & Relationships ═══

  '60ce0819-0b82-4d4b-84d7-fe80cd47ecdd':{pass_threshold:70,questions:[ // Past Simple Review
    mc(1,'What is the past of "meet"?','meeted','meted','met','meets','C'),
    mc(2,'Complete: "They ___ (establish) their partnership in 2015."','establish','establishes','established','have established','C'),
    mc(3,'Correct negative: "She ___ (not/attend) the ceremony."','doesn\'t attend','didn\'t attend','hasn\'t attended','won\'t attend','B'),
    mc(4,'Correct question: "___ they ___ (agree) on the terms?"','Have / agreed','Do / agree','Did / agree','Are / agreeing','C'),
    mc(5,'What is the past of "choose"?','choosed','chose','chosen','choses','B'),
    mc(6,'Complete: "The couple ___ (announce) their engagement last spring."','announce','announces','announced','has announced','C'),
    mc(7,'What is the past of "fall" (in love)?','falled','fell','fallen','falls','B'),
    mc(8,'Which time expression requires Past Simple?','recently','already','just','last year','D'),
    mc(9,'Complete: "He ___ (not/propose) until he had secured a stable income."','didn\'t propose','hasn\'t proposed','doesn\'t propose','wouldn\'t propose','A'),
    mc(10,'Complete: "When ___ they ___ (get) married?"','have / got','do / get','did / get','are / getting','C'),
    tf(11,'Past Simple is used for completed actions at a specific past time.','true'),
    tf(12,'"She has met him last year" is correct.','false'),
    tf(13,'"Did" is the auxiliary for all subjects in Past Simple questions and negatives.','true'),
    fb(14,'They ___ (fall) in love when they ___ (meet) at a conference. She ___ (choose) to stay.','fell, met, chose'),
    fb(15,'___ (did) he ___ (propose) before or after graduation? She ___ (say) yes immediately.','Did, propose, said'),
  ]},

  '73e0e2a9-165e-45cd-a589-23b910de17a1':{pass_threshold:70,questions:[ // Past Continuous
    mc(1,'Past Continuous is formed with:','was/were + base verb','was/were + verb-ing','had + verb-ing','did + verb-ing','B'),
    mc(2,'Complete: "She ___ (write) her vows when the power went out."','wrote','was writing','has written','had written','B'),
    mc(3,'Past Continuous describes:','completed actions','permanent situations in the past','actions in progress at a specific past time','future arrangements','C'),
    mc(4,'Complete: "They ___ (not/argue) — they were having a serious discussion."','weren\'t arguing','didn\'t argue','haven\'t argued','hadn\'t argued','A'),
    mc(5,'Complete: "What ___ she ___ (do) when you called?"','did / do','was / doing','has / done','had / done','B'),
    mc(6,'Past Continuous is often used to set the scene. Which example does this?','She left at 6.','The rain was falling softly as she walked in.','She had loved him for years.','She would always smile.','B'),
    mc(7,'Complete: "While I ___ (prepare) dinner, he arrived with flowers."','prepared','was preparing','have prepared','had prepared','B'),
    mc(8,'Which pair correctly uses Past Simple interrupting Past Continuous?','She was reading when he called.','She read when he was calling.','She has read when he called.','She had read when he called.','A'),
    mc(9,'Complete: "At 8 pm last night, they ___ (discuss) their plans for the future."','discussed','were discussing','have discussed','had discussed','B'),
    mc(10,'Complete: "She ___ (not/expect) him to propose so soon."','wasn\'t expecting','didn\'t expect','hasn\'t expected','hadn\'t expected','A'),
    tf(11,'Past Continuous uses was/were + verb-ing.','true'),
    tf(12,'"She was loving him deeply" is correct because "love" is used as an action here.','false'),
    tf(13,'Past Continuous can be used to describe a background action that was interrupted.','true'),
    fb(14,'He ___ (walk) through the park when he ___ (see) her for the first time.','was walking, saw'),
    fb(15,'While she ___ (study), he ___ (call) to ask her out. They ___ (talk) all night.','was studying, called, talked'),
  ]},

  '05a8818c-e92a-4726-b58d-231e575c2c22':{pass_threshold:70,questions:[ // Past Simple vs Continuous
    mc(1,'Choose: "While she ___ (read) his letter, tears ___ (run) down her face."','was reading / ran','read / was running','was reading / was running','read / ran','A'),
    mc(2,'Choose: "He ___ (propose) while they ___ (walk) along the beach."','proposed / were walking','was proposing / walked','proposed / walked','was proposing / were walking','A'),
    mc(3,'Past Simple in a while-clause usually means:','background action','two simultaneous long actions','a shorter interrupting event','a habitual action','C'),
    mc(4,'Complete: "She ___ (cook) when the doorbell ___ (ring)."','cooked / was ringing','was cooking / rang','has cooked / rang','was cooking / was ringing','B'),
    mc(5,'Both actions in progress at the same time: choose the correct form.','She was reading while he cooked.','She was reading while he was cooking.','She read while he was cooking.','She reads while he cooked.','B'),
    mc(6,'Complete: "When I ___ (arrive), they ___ (argue) loudly."','arrived / were arguing','was arriving / argued','arrived / argued','was arriving / were arguing','A'),
    mc(7,'Complete: "She ___ (smile) as he ___ (get down) on one knee."','smiled / was getting','was smiling / got','was smiling / was getting','smiled / got','B'),
    mc(8,'Complete: "While he ___ (type) the proposal, his laptop ___ (crash)."','typed / was crashing','was typing / crashed','was typing / was crashing','typed / crashed','B'),
    mc(9,'Choose the correct sentence:','He was meeting her while she waited.','He met her while she was waiting.','He met her while she waited.','He was meeting her while she was waiting for a long time.','B'),
    mc(10,'Complete: "As they ___ (leave) the restaurant, she ___ (realise) she had forgotten her phone."','were leaving / realised','left / was realising','were leaving / was realising','left / realised','A'),
    tf(11,'Past Continuous is used for background actions; Past Simple for shorter interrupting events.','true'),
    tf(12,'"While she was reading, he called" and "While she read, he called" always have the same meaning.','false'),
    tf(13,'"When" can introduce both Past Simple and Past Continuous clauses.','true'),
    fb(14,'She ___ (read) when he ___ (walk) in. While they ___ (dance), the lights ___ (go) out.','was reading, walked, were dancing, went'),
    fb(15,'As she ___ (prepare, PC) her presentation, her supervisor ___ (phone, PS) with feedback.','was preparing, phoned'),
  ]},

  'dc83b9df-46e9-4ff9-8ed4-1d6d071412b7':{pass_threshold:70,questions:[ // Past Perfect
    mc(1,'Past Perfect is formed with:','had + present participle','had + base verb','had + past participle','have + past participle','C'),
    mc(2,'Complete: "By the time she arrived, he ___ (already/leave)."','already left','has already left','had already left','already leaves','C'),
    mc(3,'Past Perfect shows that an action happened:','after another past action','before another past action','at the same time as another past action','in the future','B'),
    mc(4,'Complete: "She ___ (never/meet) anyone like him before."','never met','has never met','had never met','never meets','C'),
    mc(5,'Complete: "He realised he ___ (fall) in love with her long before he admitted it."','fell','has fallen','had fallen','falls','C'),
    mc(6,'Choose correct: "When the relationship ended, they ___ (be) together for 10 years."','were','are','have been','had been','D'),
    mc(7,'Complete: "She ___ (not/expect) to see him there — they ___ (break up) months ago."','didn\'t expect / had broken','hasn\'t expected / broke','hadn\'t expected / broke','didn\'t expect / have broken','A'),
    mc(8,'Past Perfect is often used after: "by the time", "when", "after", "as soon as". Which is correct?','After she left, he was arriving.','After she had left, he arrived.','After she left, he had arrived.','After she was leaving, he arrived.','B'),
    mc(9,'Complete: "She wondered whether he ___ (receive) her message."','received','has received','had received','receives','C'),
    mc(10,'What is the past participle of "know"?','knew','knowed','known','knowing','C'),
    tf(11,'Past Perfect is formed with had + past participle.','true'),
    tf(12,'"She had went" is correct Past Perfect.','false'),
    tf(13,'Past Perfect is used to make clear which of two past events happened first.','true'),
    fb(14,'By the time he proposed, she ___ (already/know) she wanted to marry him.','had already known'),
    fb(15,'He ___ (realise) he ___ (meet) her before — at a conference two years earlier.','realised, had met'),
  ]},

  '57c60e64-517e-434b-a608-42c181355b1a':{pass_threshold:70,questions:[ // Past Perfect vs Past Simple
    mc(1,'Complete: "After they ___ (reconcile), their relationship ___ (become) stronger."','had reconciled / became','reconciled / had become','reconcile / became','had reconciled / had become','A'),
    mc(2,'When "after" makes the sequence clear, Past Perfect can be replaced by:','Present Simple','Past Continuous','Past Simple','Past Perfect Continuous','C'),
    mc(3,'Complete: "She ___ (not/see) him since they ___ (graduate)."','didn\'t see / graduated','hadn\'t seen / had graduated','hasn\'t seen / graduated','hadn\'t seen / graduated','D'),
    mc(4,'Choose: "When he ___ (arrive), she ___ (already/leave)."','arrived / already left','arrived / had already left','had arrived / already left','was arriving / had left','B'),
    mc(5,'Complete: "He ___ (propose) as soon as he ___ (get) the ring."','proposed / had got','had proposed / got','was proposing / had got','proposed / got','A'),
    mc(6,'Complete: "By the time she ___ (realise) how she felt, he ___ (move) abroad."','realised / had moved','had realised / moved','realised / moved','had realised / had moved','A'),
    mc(7,'Choose the clearer sequence: "She loved him before she knew it."','Past Simple + Past Simple','Past Perfect + Past Simple','both are possible','only Past Perfect','C'),
    mc(8,'Complete: "After the couple ___ (separate), friends ___ (take) sides."','had separated / took','separated / had taken','separated / took','had separated / had taken','A'),
    mc(9,'Complete: "He ___ (call) her immediately after he ___ (hear) the news."','called / had heard','had called / heard','called / heard','was calling / had heard','A'),
    mc(10,'Which sentence correctly uses Past Perfect to clarify sequence?','She ate after she left.','She had eaten before she left.','She was eating when she left.','She eats after she leaves.','B'),
    tf(11,'Past Perfect is used when we need to emphasise that one past action preceded another.','true'),
    tf(12,'Past Simple can sometimes replace Past Perfect when "after" or "before" makes the sequence clear.','true'),
    tf(13,'"When he had arrived, she left" means she left before he arrived.','false'),
    fb(14,'After she ___ (realise) she loved him, she ___ (decide) to tell him. (PP + PS)','had realised, decided'),
    fb(15,'By the time the ceremony ___ (begin), most guests ___ (already/arrive). (PS + PP)','began, had already arrived'),
  ]},

  '09ed8edf-0b7d-41e5-9bf2-18b3f84bbbab':{pass_threshold:70,questions:[ // Family Relationships — Vocabulary
    mc(1,'What does "estranged" mean in a family context?','very close','no longer in contact due to a dispute','newly married','adopted','B'),
    mc(2,'What is a "nuclear family"?','a large extended family','parents and children living together','a family affected by conflict','a scientific community','B'),
    mc(3,'What does "sibling" mean?','parent','spouse','brother or sister','child','C'),
    mc(4,'What does "reconcile" mean in a relationship?','separate permanently','restore a friendly relationship after a conflict','meet for the first time','get engaged','B'),
    mc(5,'What is a "blended family"?','a family with only one parent','a family formed when partners with children from previous relationships marry','an extended family','a childless couple','B'),
    mc(6,'What does "custody" mean in a legal context?','the right to care for a child after separation/divorce','a financial arrangement','a marriage contract','a type of guardianship for adults','A'),
    mc(7,'What does "next of kin" mean?','a colleague','a neighbour','the closest living relative','a legal representative','C'),
    mc(8,'What does "to be on good terms with" mean?','to argue frequently','to have a friendly or positive relationship with','to be in debt to','to be related to','B'),
    mc(9,'What is an "arranged marriage"?','a marriage based on romantic love only','a marriage organised by the families of the partners','a marriage after a long relationship','a civil ceremony','B'),
    mc(10,'What does "to reconcile" mean?','to separate','to restore a positive relationship after a conflict','to start a new relationship','to adopt','B'),
    tf(11,'"Siblings" refers to brothers and sisters.','true'),
    tf(12,'A "nuclear family" typically includes grandparents.','false'),
    tf(13,'"Estranged" means no longer in contact due to a dispute.','true'),
    fb(14,'___ (Custody) refers to the legal right to care for a child. A "___ (blended)" family includes children from previous relationships.','Custody, blended'),
    fb(15,'They were ___ (estranged) for years before they ___ (reconcile) at the funeral.','estranged, reconciled'),
  ]},

  '822a2256-f908-46ea-93d6-de174ccbc337':{pass_threshold:70,questions:[ // Friendship & Trust — Idioms
    mc(1,'What does "hit it off" mean?','to have an argument','to get along very well from the start','to break up','to meet formally','B'),
    mc(2,'What does "fall out (with someone)" mean?','to become friends','to have a serious argument and stop being friends','to fall in love','to lose contact gradually','B'),
    mc(3,'What does "have someone\'s back" mean?','to stand behind someone physically','to support and protect someone','to gossip about someone','to ignore someone','B'),
    mc(4,'What does "a fair-weather friend" mean?','a very loyal friend','someone who is only a friend when things are easy','a friend you see in summer','an honest friend','B'),
    mc(5,'What does "bury the hatchet" mean?','to dig a hole','to make peace after a conflict','to hide something important','to start a conflict','B'),
    mc(6,'What does "keep in touch" mean?','to physically hold something','to maintain contact with someone','to stop communicating','to listen carefully','B'),
    mc(7,'What does "see eye to eye" mean?','to have good eyesight','to agree with someone','to avoid someone','to dislike someone','B'),
    mc(8,'What does "a shoulder to cry on" mean?','a physical support','someone who offers emotional support','a formal adviser','a therapist','B'),
    mc(9,'What does "give someone the benefit of the doubt" mean?','to doubt someone completely','to trust someone despite uncertainty','to question someone\'s motives','to blame someone','B'),
    mc(10,'What does "fall out of touch" mean?','to have an argument','to gradually lose contact with someone','to meet again','to break up permanently','B'),
    tf(11,'"Hit it off" means to immediately get along well with someone.','true'),
    tf(12,'A "fair-weather friend" is someone who is extremely loyal.','false'),
    tf(13,'"Bury the hatchet" means to make peace after a conflict.','true'),
    fb(14,'They ___ (hit) ___ (it off) immediately at the conference. After the argument, they ___ (fall out) for months.','hit, it off, fell out'),
    fb(15,'She is always ___ (there) to offer a shoulder to cry on. We need to ___ (bury) the hatchet.','there, bury'),
  ]},

  'e73f6e50-5a0a-4854-a598-4466d5b0ff3e':{pass_threshold:80,questions:[ // Module 2 Review
    mc(1,'Past Simple of "meet":','meeted','meted','met','meets','C'),
    mc(2,'Past Perfect: "By the time she arrived, he ___ (leave)."','left','has left','had left','was leaving','C'),
    mc(3,'Past Continuous: "She ___ (write) when he called."','wrote','was writing','has written','had written','B'),
    mc(4,'Choose correct (PS vs PC): "He ___ (propose) while they ___ (walk)."','proposed / were walking','was proposing / walked','proposed / walked','was proposing / were walking','A'),
    mc(5,'PP vs PS: "After they ___ (reconcile), life ___ (improve)."','had reconciled / improved','reconciled / had improved','reconcile / improved','had reconciled / had improved','A'),
    mc(6,'What does "estranged" mean?','very close','newly married','no longer in contact due to dispute','adopted','C'),
    mc(7,'What is a "blended family"?','extended family','family with one parent','family formed when partners with children from previous relationships combine','childless couple','C'),
    mc(8,'What does "hit it off" mean?','argue immediately','get along very well from the start','lose contact','break up','B'),
    mc(9,'What does "bury the hatchet" mean?','hide something','start a conflict','make peace after a conflict','dig a hole','C'),
    mc(10,'Past Continuous: "At 9 pm, they ___ (discuss) their future."','discussed','were discussing','have discussed','had discussed','B'),
    mc(11,'PP: "She ___ (never/meet) anyone so caring before."','never met','has never met','had never met','never meets','C'),
    mc(12,'What does "a fair-weather friend" mean?','very loyal friend','friend only when things are easy','friend from summer','honest friend','B'),
    mc(13,'PS: "___ they ___ (agree) on the terms?" (question)','Have / agreed','Do / agree','Did / agree','Are / agreeing','C'),
    mc(14,'What does "give the benefit of the doubt" mean?','doubt completely','question motives','trust despite uncertainty','blame someone','C'),
    mc(15,'PC setting scene: "The rain ___ (fall) as they ___ (say) their vows." (both PC)','fell / said','was falling / were saying','was falling / said','fell / were saying','B'),
    tf(16,'"She had went" is correct Past Perfect.','false'),
    tf(17,'Past Perfect clarifies which of two past actions happened first.','true'),
    tf(18,'"Siblings" means brothers and sisters.','true'),
    fb(19,'While she ___ (prepare, PC) the dinner, he ___ (arrive, PS) with flowers.','was preparing, arrived'),
    fb(20,'By the time they ___ (graduate, PS), they ___ (fall, PP) in love.','graduated, had fallen'),
  ]},

  // ═══ MODULE 3: Sport & Fitness ═══

  '5e8f368f-3602-486b-aed2-0f6d0656c0ae':{pass_threshold:70,questions:[ // Future Will vs Going To
    mc(1,'Use "going to" for:','spontaneous decisions','plans decided before speaking','predictions without evidence','offers','B'),
    mc(2,'Use "will" for:','plans made in advance','intentions decided earlier','spontaneous decisions and predictions','ongoing actions','C'),
    mc(3,'Complete: "She ___ (going to) compete in the national championships — she\'s been training all year."','will compete','is going to compete','competes','competed','B'),
    mc(4,'Complete: "I\'ll carry your equipment!" — This is:','a pre-planned intention','a spontaneous decision / offer','a prediction based on evidence','a scheduled event','B'),
    mc(5,'Complete: "Look at his technique — he ___ (going to) break the record!"','will break','is going to break','breaks','broke','B'),
    mc(6,'Complete: "The next Olympics ___ (hold) in Los Angeles in 2028."','holds','is going to hold','will be held','is held','C'),
    mc(7,'Which signals a plan made in advance?','I think I\'ll sign up for the marathon.','I\'ve already signed up for the marathon — I\'m running it.','Oh, that sounds fun, I\'ll run it!','She might run.','B'),
    mc(8,'Complete: "I promise I ___ (train) harder next month."','am going to train','train','trained','will train','D'),
    mc(9,'Complete: "The coach ___ (announce) the team selection later today." (pre-arranged)','will announce','announced','is going to announce','announces','C'),
    mc(10,'Choose correct: "He has booked his flights — he ___ (definitely/compete)."','will definitely compete','is definitely going to compete','definitely competes','definitely competed','B'),
    tf(11,'"Going to" is used for plans decided before the moment of speaking.','true'),
    tf(12,'"Will" is always used for pre-planned intentions.','false'),
    tf(13,'"I\'ll help you carry that!" is an example of a spontaneous decision with "will".','true'),
    fb(14,'She ___ (going to) retire after the Olympics — she\'s already decided. He ___ (will, spontaneous) help with the equipment.','is going to, will'),
    fb(15,'I think the home team ___ (will) win. They\'ve booked the venue — the event ___ (going to) take place on Sunday.','will, is going to'),
  ]},

  '632b318f-17f4-40b1-879b-286533ddb99c':{pass_threshold:70,questions:[ // Future Continuous
    mc(1,'Future Continuous is formed with:','will + verb-ing','will be + verb-ing','am/is/are going to + verb-ing','will have + verb-ing','B'),
    mc(2,'Future Continuous describes:','a completed future action','an action in progress at a specific future time','a spontaneous decision','a past habit','B'),
    mc(3,'Complete: "At this time tomorrow, the marathon runners ___ (cross) the finish line."','will cross','will be crossing','are crossing','cross','B'),
    mc(4,'Complete: "This time next year, she ___ (train) for the World Championships."','trains','will train','will be training','is training','C'),
    mc(5,'Complete: "Don\'t disturb him at 3 pm — he ___ (compete) in the final."','will compete','will be competing','competes','competed','B'),
    mc(6,'Future Continuous can also express a polite or casual inquiry. Which is more polite?','Will you sign the document?','Will you be signing the document?','Are you going to sign?','Do you sign?','B'),
    mc(7,'Complete: "The athletes ___ (warm up) when the press conference begins."','will warm up','warm up','will be warming up','are warming up','C'),
    mc(8,'Complete: "She ___ (compete) in three events at the next Games."','will be competing','competed','has competed','competes','A'),
    mc(9,'Which correctly uses Future Continuous?','She will be crossing the finish line at noon tomorrow.','She will cross the line at noon tomorrow.','She crosses the finish line at noon tomorrow.','She would be crossing at noon.','A'),
    mc(10,'Complete: "By the time the fans arrive, the game ___ (start)." (still in progress)','will start','will have started','will be starting','starts','C'),
    tf(11,'Future Continuous is formed with will + be + verb-ing.','true'),
    tf(12,'Future Continuous is used for completed future actions.','false'),
    tf(13,'Future Continuous can be used to make polite enquiries about someone\'s plans.','true'),
    fb(14,'At 3 pm tomorrow, she ___ (compete, FC) in the semifinal. By next year, he ___ (train, FC) professionally.','will be competing, will be training'),
    fb(15,'___ you ___ (use, FC) the court at 4 pm? (polite inquiry) Yes, I ___ (practice) until 5.','Will, be using, will be practising'),
  ]},

  'd8409c54-3b4f-4240-b50c-a37536531752':{pass_threshold:70,questions:[ // Future Perfect
    mc(1,'Future Perfect is formed with:','will + verb-ing','will be + verb-ing','will have + past participle','would have + past participle','C'),
    mc(2,'Future Perfect describes:','an action in progress in the future','an action that will be completed before a specific future time','a prediction','a past regret','B'),
    mc(3,'Complete: "By the end of this season, she ___ (score) over 100 goals."','will score','will be scoring','will have scored','has scored','C'),
    mc(4,'Complete: "By the time the whistle blows, they ___ (play) for 90 minutes."','will play','will be playing','will have played','play','C'),
    mc(5,'Complete: "She ___ (not/compete) in three Olympics by the time she retires."','won\'t compete','won\'t have competed','hasn\'t competed','won\'t be competing','B'),
    mc(6,'Which signals Future Perfect?','now','yesterday','by next year','at the moment','C'),
    mc(7,'Complete: "By 2030, scientists ___ (develop) more effective training methods."','will develop','will be developing','will have developed','have developed','C'),
    mc(8,'Complete: "___ he ___ (break) the world record by the end of the season?"','Will / break','Will / be breaking','Will / have broken','Does / break','C'),
    mc(9,'Future Perfect vs Future Continuous: "By noon, he will have finished" means:','he finishes at noon exactly','the action is in progress at noon','the action will be complete before noon','he starts at noon','C'),
    mc(10,'Complete: "She ___ (train) for over a decade by the time she competes at the next Olympics."','will train','will have been training','trains','trained','B'),
    tf(11,'Future Perfect uses will + have + past participle.','true'),
    tf(12,'"By the time" is never used with Future Perfect.','false'),
    tf(13,'Future Perfect shows that an action will be complete before a specific point in the future.','true'),
    fb(14,'By the end of the year, they ___ (complete, FP) the training programme. She ___ (win, FP) 10 medals by then.','will have completed, will have won'),
    fb(15,'By 2028, this athlete ___ (compete, FP) in four Olympic Games. ___ you ___ (finish, FP) by 5 pm?','will have competed, Will, have finished'),
  ]},

  'b7b54347-9933-4528-9adc-206863b5adcd':{pass_threshold:70,questions:[ // Present Continuous for Future
    mc(1,'Present Continuous can be used for:','current actions only','arranged future plans','general truths','past habits','B'),
    mc(2,'Complete: "She ___ (compete) in the finals next Saturday." (arranged plan)','competes','competed','is competing','will compete','C'),
    mc(3,'What makes Present Continuous suitable for future arrangements?','There is a future time marker','It is always about now','It never refers to the future','It is only used in sports','A'),
    mc(4,'Complete: "They ___ (travel) to the World Cup next month — hotels are booked."','travel','travelled','will travel','are travelling','D'),
    mc(5,'Which has no arrangement implied?','The team is playing on Friday.','She is running a marathon.','I think it will rain.','We are meeting the coach tomorrow.','C'),
    mc(6,'Complete: "I ___ (not/run) tomorrow — I have a knee injury."','don\'t run','didn\'t run','am not running','won\'t be running','C'),
    mc(7,'Complete: "What ___ you ___ (do) after the championship?" (arranged)','will / do','do / do','are / doing','did / do','C'),
    mc(8,'Present Continuous for future is typically used for:','formal predictions','social and personal arrangements','scientific facts','historical events','B'),
    mc(9,'Complete: "The coach ___ (give) a press conference tonight — it\'s scheduled."','gives','is giving','will give','gave','B'),
    mc(10,'Which is a future arrangement?','She always runs on Sundays.','She is running in the marathon next week.','She was running yesterday.','She ran last year.','B'),
    tf(11,'Present Continuous with a future time marker often describes a pre-arranged plan.','true'),
    tf(12,'"She is running tomorrow" always describes a current ongoing action.','false'),
    tf(13,'"What are you doing this weekend?" can ask about future plans.','true'),
    fb(14,'They ___ (fly, PC future) to Tokyo next week for the tournament — tickets are booked.','are flying'),
    fb(15,'She ___ (compete, PC future) in three events at the championships. ___ he ___ (train, PC future) tomorrow?','is competing, Is, training'),
  ]},

  '50a18535-0687-4ea4-b529-342df93767f9':{pass_threshold:70,questions:[ // May/Might/Could for Future
    mc(1,'Which modal expresses the weakest future possibility?','will','might','should','must','B'),
    mc(2,'Complete: "She ___ break the record — she\'s been training exceptionally well."','will','must','might/could/may','should','C'),
    mc(3,'What is the difference between "may" and "might" for future possibility?','May is past, might is present','May = slightly more certain, might = slightly less certain','No difference','Might is more formal','B'),
    mc(4,'Complete: "They ___ qualify for the semi-finals if they win tonight."','will','must','could/might/may','should','C'),
    mc(5,'Complete: "I\'m not sure — she ___ compete or she ___ pull out due to injury."','will / will','might / might','must / must','should / should','B'),
    mc(6,'"Could" for future possibility is:','a definite prediction','an impossibility','one of several possible options','a certainty','C'),
    mc(7,'Complete: "The match ___ be cancelled due to bad weather." (possible)','will','must','may/might/could','should','C'),
    mc(8,'Complete: "It ___ be a close game — both teams are evenly matched."','will','must','might/could','shall','C'),
    mc(9,'Which expresses the highest certainty about the future?','might','may','could','will','D'),
    mc(10,'Complete: "He ___ set a new personal best today — he\'s in great form."','might','could','may','All of the above are possible','D'),
    tf(11,'"Might", "may", and "could" all express future possibility.','true'),
    tf(12,'"Will" expresses certainty about the future, while "might" expresses possibility.','true'),
    tf(13,'"May" always expresses permission, never possibility.','false'),
    fb(14,'She ___ (might) qualify — it depends on her performance. He ___ (could) break the world record.','might, could'),
    fb(15,'The game ___ (may) be postponed. We ___ (will) know the result by tonight.','may, will'),
  ]},

  'ca69db3b-edfe-4616-9aad-e2879adf7863':{pass_threshold:70,questions:[ // Extreme Sports — Vocabulary
    mc(1,'What is "free solo climbing"?','climbing with ropes and a partner','climbing without ropes or safety equipment','a beginner climbing technique','indoor rock climbing','B'),
    mc(2,'What is "BASE jumping"?','jumping from a base of a mountain','parachuting from Buildings, Antennas, Spans (bridges), and Earth (cliffs)','bungee jumping from a crane','skydiving from a plane','B'),
    mc(3,'What does "adrenaline rush" mean?','a sudden feeling of fear','a sudden surge of energy and excitement','a training technique','a type of injury','B'),
    mc(4,'What is "wingsuit flying"?','flying a glider plane','wearing a suit that enables gliding through the air','BASE jumping with a parachute','skydiving in formation','B'),
    mc(5,'What does "endurance" mean in sport?','explosive speed','strength','the ability to sustain prolonged physical activity','flexibility','C'),
    mc(6,'What is a "PB" (personal best) in sport?','a team record','the athlete\'s highest individual performance to date','an international record','a competition prize','B'),
    mc(7,'What does "to push the limits" mean?','to give up','to exceed previous boundaries of achievement','to stay within safe limits','to train moderately','B'),
    mc(8,'What is "skydiving"?','jumping from cliffs','jumping from aircraft and parachuting to the ground','climbing mountains','BASE jumping','B'),
    mc(9,'What does "stamina" mean?','strength','speed','the ability to sustain effort over a long period','technique','C'),
    mc(10,'What is "whitewater rafting"?','sailing on calm water','navigating a boat through fast-moving turbulent river water','swimming in the ocean','kayaking on a lake','B'),
    tf(11,'"Endurance" refers to the ability to sustain prolonged physical activity.','true'),
    tf(12,'A "PB" is a world record in sport.','false'),
    tf(13,'"Adrenaline rush" describes a surge of excitement and energy.','true'),
    fb(14,'___ (BASE) jumping involves parachuting from Buildings, Antennas, Spans, and Earth. ___ (Wingsuit) flying enables gliding through the air.','BASE, Wingsuit'),
    fb(15,'She broke her ___ (PB) in the 100m. The athlete showed incredible ___ (stamina) throughout the race.','PB, stamina'),
  ]},

  '5b4ac7b3-5c9b-47db-a215-7c53babb00d5':{pass_threshold:70,questions:[ // Olympic Games — Collocations
    mc(1,'Which is the correct collocation?','win a medal','gain a medal','take a medal','get a medal','A'),
    mc(2,'Which is correct?','break a world record','make a world record','do a world record','take a world record','A'),
    mc(3,'Which is correct?','make a performance','put up a performance','give a performance','do a performance','C'),
    mc(4,'Which is correct?','carry the torch','bring the torch','take the torch','hold the torch (both A and D)','D'),
    mc(5,'Which is correct?','host the Olympics','hold the Olympics','organise the Olympics','All of the above','D'),
    mc(6,'Which is correct with "gold"?','win gold','take gold','earn gold','Both A and C','D'),
    mc(7,'Which is correct?','set a record','put a record','make a record','do a record','A'),
    mc(8,'Which is correct?','compete in the Olympics','participate in the Olympics','take part in the Olympics','All of the above','D'),
    mc(9,'Which is correct with "achieve"?','achieve a gold medal','achieve victory','achieve success','All of the above','D'),
    mc(10,'Which is correct?','score a goal','make a goal','do a goal','get a goal','A'),
    tf(11,'"Break a world record" is the correct collocation.','true'),
    tf(12,'"Make a gold medal" is the correct collocation.','false'),
    tf(13,'"Host the Olympics" is a correct collocation.','true'),
    fb(14,'She ___ (win) gold and ___ (break) the world record in the same race.','won, broke'),
    fb(15,'They are proud to ___ (host) the games. He ___ (set) a new national record.','host, set'),
  ]},

  'e8c46f91-6699-4dbe-a745-65354a6da95c':{pass_threshold:80,questions:[ // Module 3 Review
    mc(1,'Future will vs going to: "I\'ve already booked — I ___ (compete)." (plan)','will compete','is going to compete','am going to compete','competed','C'),
    mc(2,'Future Continuous: "At 3 pm tomorrow, she ___ (train)."','will train','trained','will be training','is training','C'),
    mc(3,'Future Perfect: "By the end of the year, she ___ (win) 20 medals."','will win','will be winning','will have won','has won','C'),
    mc(4,'Present Continuous for future: "They ___ (fly) to Paris next week." (arranged)','fly','flew','will fly','are flying','D'),
    mc(5,'"Might" vs "will": "The match ___ be cancelled — it\'s not confirmed."','will','must','might/could/may','should','C'),
    mc(6,'What is "endurance" in sport?','speed','strength','ability to sustain prolonged activity','flexibility','C'),
    mc(7,'What is "BASE jumping"?','jumping from a mountain base','parachuting from buildings, antennas, spans, cliffs','skydiving from planes','bungee jumping','B'),
    mc(8,'Correct collocation: ___ a world record','make','break','do','take','B'),
    mc(9,'Correct collocation: ___ gold (medal)','make','do','win','take','C'),
    mc(10,'Future Continuous for polite inquiry: "___ you ___ (use) the court at 4?"','Will / use','Will / be using','Do / use','Are / using','B'),
    mc(11,'Future Perfect: "By 2028, she ___ (compete) in 4 Olympics."','will compete','will be competing','will have competed','competes','C'),
    mc(12,'What does "push the limits" mean?','give up','exceed previous boundaries','stay safe','train moderately','B'),
    mc(13,'Going to vs will: "Look at the score — our team ___ (going to) win!"','will win','is going to win','wins','won','B'),
    mc(14,'What is a "PB" in sport?','a world record','a team record','an athlete\'s best individual performance','a competition prize','C'),
    mc(15,'Correct collocation: ___ the Olympics (be the country that organises it)','win','host','do','make','B'),
    tf(16,'"Will" always expresses a pre-planned intention.','false'),
    tf(17,'Future Perfect shows an action completed before a future point.','true'),
    tf(18,'"Stamina" refers to the ability to sustain effort over a long period.','true'),
    fb(19,'She ___ (going to) retire after the Games. By then, she ___ (win, FP) 6 gold medals.','is going to, will have won'),
    fb(20,'At this time next year, he ___ (train, FC) professionally. He ___ (break, FP) the record by then.','will be training, will have broken'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'2fb65e39-732f-43d2-82c2-d5c6ce5019b0',n:1,title:'Real World English'},
    {id:'f86621f4-1212-424d-8a00-5010cdfb4c05',n:2,title:'Love & Relationships'},
    {id:'7eaf369d-eedc-4fa2-bc4a-38434041ff42',n:3,title:'Sport & Fitness'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 B1 Intermediate — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 1–3 B1 Intermediate`)
}
main().catch(e=>{console.error(e);process.exit(1)})
