/**
 * B1 Intermediate — Modules 7, 8 (Conditionals I, Reported Speech).
 * Run: npx ts-node --project tsconfig.scripts.json scripts/seed-quizzes-b1-mod7-8.ts
 */
import * as fs from 'fs'; import * as path from 'path'; import { createClient } from '@supabase/supabase-js'
function loadEnv(){const f=path.join(process.cwd(),'.env.local');if(!fs.existsSync(f))return;fs.readFileSync(f,'utf-8').split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('#'))return;const i=t.indexOf('=');if(i<0)return;const key=t.slice(0,i).trim();const val=t.slice(i+1).trim().replace(/^['"]|['"]$/g,'');if(key&&!(key in process.env))process.env[key]=val})}
loadEnv()
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type MC={id:number;type:'multiple_choice';question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:'A'|'B'|'C'|'D'}
type TF={id:number;type:'true_false';question:string;correct_answer:'true'|'false'}
type FB={id:number;type:'fill_blank';question:string;correct_answer:string}
type Q=MC|TF|FB
const mc=(id:number,q:string,a:string,b:string,c:string,d:string,ans:'A'|'B'|'C'|'D'):MC=>({id,type:'multiple_choice',question:q,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:ans})
const tf=(id:number,q:string,ans:'true'|'false'):TF=>({id,type:'true_false',question:q,correct_answer:ans})
const fb=(id:number,q:string,ans:string):FB=>({id,type:'fill_blank',question:q,correct_answer:ans})

const QUIZZES:Record<string,{pass_threshold:number;questions:Q[]}>={

  // MODULE 7: Conditionals I
  '1951e822-aa15-4cad-9afa-ca754a208b0a':{pass_threshold:70,questions:[ // Zero Conditional
    mc(1,'Zero Conditional uses:','past simple in both clauses','present simple in both clauses','present simple + will','past simple + would','B'),
    mc(2,'Complete: "If you ___ (expose) cells to extreme heat, they ___ (die)."','expose / die','expose / will die','exposed / die','exposed / would die','A'),
    mc(3,'Zero Conditional expresses:','unreal situations','general truths, scientific facts, and habits','future predictions','past regrets','B'),
    mc(4,'Complete: "Water ___ (boil) if you ___ (heat) it to 100°C."','boils / heat','will boil / heat','would boil / heated','boiled / heated','A'),
    mc(5,'Complete: "If she ___ (not/receive) enough sleep, her concentration ___ (suffer)."','doesn\'t receive / suffers','don\'t receive / suffer','didn\'t receive / suffered','won\'t receive / will suffer','A'),
    mc(6,'Complete: "When demand ___ (exceed) supply, prices ___ (rise)."','exceeds / rise','exceeded / rise','exceeds / will rise','will exceed / rise','A'),
    mc(7,'Which conjunction can replace "if" in Zero Conditional?','unless','when','although','because','B'),
    mc(8,'Complete: "If you ___ (mix) an acid and a base, you ___ (get) a salt and water."','mix / get','mix / will get','mixed / get','would mix / get','A'),
    mc(9,'Zero Conditional can also be used for:','specific past events','imaginary futures','habitual actions and natural laws','completed actions','C'),
    mc(10,'Complete: "When researchers ___ (replicate) the experiment, they ___ (observe) the same results."','replicate / observe','replicated / observe','will replicate / observe','replicate / will observe','A'),
    tf(11,'Zero Conditional uses present simple in both the if-clause and the main clause.','true'),
    tf(12,'Zero Conditional can describe scientific facts.','true'),
    tf(13,'"If" can be replaced by "when" in Zero Conditional without changing the meaning significantly.','true'),
    fb(14,'If you ___ (freeze) water, it ___ (become) ice. (Zero)','freeze, becomes'),
    fb(15,'When the economy ___ (contract), unemployment ___ (rise). (Zero)','contracts, rises'),
  ]},
  'f2edcd07-6bd6-4a16-aa39-55ac2bc9e951':{pass_threshold:70,questions:[ // First Conditional
    mc(1,'First Conditional uses:','present simple + present simple','past simple + would','present simple + will + base verb','past perfect + would have','C'),
    mc(2,'Complete: "If she ___ (submit) her draft by Friday, the supervisor ___ (provide) feedback."','submits / will provide','submitted / will provide','submits / would provide','submit / provides','A'),
    mc(3,'First Conditional is used for:','general truths','impossible situations','real and possible future situations','past regrets','C'),
    mc(4,'Complete: "Unless she ___ (revise) her methodology, the paper ___ (not/be) accepted."','revises / won\'t be','revised / wouldn\'t be','revises / will be','revise / won\'t be','A'),
    mc(5,'Complete: "If the funding ___ (come) through, we ___ (expand) the research."','comes / will expand','came / would expand','will come / expand','comes / expand','A'),
    mc(6,'"Unless" in First Conditional means:','if','if not','even if','only if','B'),
    mc(7,'Complete: "Should she ___ (apply), she ___ (stand) a good chance." (formal/inverted)','apply / will stand','applies / will stand','apply / would stand','applies / would stand','A'),
    mc(8,'Complete: "___ the data ___ (support) the hypothesis, we will publish." (If + subject + verb)','If the data supports','If the data will support','If the data supported','If the data would support','A'),
    mc(9,'What does "provided that" mean in conditionals?','unless','only if / on the condition that','even if','as long as not','B'),
    mc(10,'Complete: "If the results ___ (be) significant, this ___ (represent) a major breakthrough."','are / will represent','were / would represent','are / represents','will be / represent','A'),
    tf(11,'First Conditional describes real and possible future situations.','true'),
    tf(12,'"Unless" means "if".','false'),
    tf(13,'"Should + subject + verb" is a formal alternative to "if" in First Conditional.','true'),
    fb(14,'If they ___ (secure) funding, they ___ (launch) the study. (1st cond.)','secure, will launch'),
    fb(15,'___ (Unless) she improves her methodology, the paper ___ (reject, passive). (1st cond.)','Unless, will be rejected'),
  ]},
  '740b0303-d581-4afe-9243-89df4c7a1c1c':{pass_threshold:70,questions:[ // Second Conditional
    mc(1,'Second Conditional uses:','present simple + will','past simple + would + base verb','past perfect + would have','present simple + present simple','B'),
    mc(2,'Complete: "If she ___ (have) more data, the analysis ___ (be) more robust."','had / would be','has / would be','had / will be','would have / be','A'),
    mc(3,'Second Conditional describes:','real future possibilities','general truths','unreal or unlikely present/future situations','past facts','C'),
    mc(4,'Complete: "If I ___ (be) in your position, I ___ (approach) the problem differently."','were / would approach','am / would approach','was / will approach','would be / approach','A'),
    mc(5,'Complete: "If the budget ___ (allow), we ___ (conduct) a longitudinal study."','allowed / would conduct','allows / would conduct','allowed / will conduct','would allow / conduct','A'),
    mc(6,'Why use "were" instead of "was" for all persons in Second Conditional?','It is a grammatical error','It is formal subjunctive, though "was" is acceptable informally','Only "was" is correct','It depends on the number','B'),
    mc(7,'Complete: "If she ___ (receive) a grant, she ___ (employ) a research assistant."','received / would employ','receives / would employ','received / will employ','would receive / employ','A'),
    mc(8,'"Were to + infinitive" is:','incorrect','an emphatic or formal alternative to past simple in 2nd conditional','always used in 1st conditional','a past form','B'),
    mc(9,'Complete: "If she ___ (not/face) so many obstacles, she ___ (publish) sooner."','didn\'t face / would publish','doesn\'t face / would publish','didn\'t face / will publish','wouldn\'t face / publish','A'),
    mc(10,'Complete: "What ___ you ___ (do) if the experiment ___ (fail)?"','would / do / failed','will / do / fails','would / do / would fail','do / do / failed','A'),
    tf(11,'Second Conditional uses past simple in the if-clause.','true'),
    tf(12,'"If I would be rich" is correct Second Conditional.','false'),
    tf(13,'"Were to + infinitive" adds emphasis or formality in Second Conditional.','true'),
    fb(14,'If they ___ (have) more participants, the study ___ (more valid). (2nd cond.)','had, would be more valid'),
    fb(15,'What ___ (would) you do if the funding ___ (cut)? (2nd cond.)','would, were cut'),
  ]},
  'cf507864-5482-4b80-b9b2-c6b45665ab95':{pass_threshold:70,questions:[ // Third Conditional
    mc(1,'Third Conditional uses:','past simple + would','past perfect + would have + pp','present perfect + will','present simple + present simple','B'),
    mc(2,'Complete: "If she ___ (conduct) a pilot study, she ___ (identify) the flaw earlier."','had conducted / would have identified','conducted / would have identified','had conducted / would identify','conducted / would identify','A'),
    mc(3,'Third Conditional describes:','real future possibilities','unreal present situations','unreal past situations (what would have happened if something had been different)','general truths','C'),
    mc(4,'Complete: "If the data ___ (be) more reliable, the findings ___ (be) more credible."','had been / would have been','was / would have been','had been / would be','were / would have been','A'),
    mc(5,'Complete: "She ___ (pass) the viva if she ___ (prepare) more thoroughly."','would have passed / had prepared','would pass / had prepared','would have passed / prepared','will have passed / had prepared','A'),
    mc(6,'Complete: "If the committee ___ (approve) the proposal, the project ___ (proceed)."','had approved / would have proceeded','approved / would have proceeded','had approved / would proceed','would have approved / proceeded','A'),
    mc(7,'What does Third Conditional often express?','hope for the future','plans','regret or criticism about the past','a scientific fact','C'),
    mc(8,'Complete: "If I ___ (know) about the conference, I ___ (register)."','had known / would have registered','knew / would have registered','had known / would register','would have known / register','A'),
    mc(9,'Complete: "She ___ (not/make) this error if she ___ (proofread) more carefully."','wouldn\'t have made / had proofread','wouldn\'t make / had proofread','wouldn\'t have made / proofread','wouldn\'t have made / would have proofread','A'),
    mc(10,'Identify the Third Conditional: "If it had rained, the experiment would have been delayed."','correct','incorrect — missing "have" in result','incorrect — wrong tense in if-clause','correct only in informal English','A'),
    tf(11,'Third Conditional refers to unreal past situations.','true'),
    tf(12,'"If she had studied harder, she would pass" is correct Third Conditional.','false'),
    tf(13,'Third Conditional often expresses regret about past actions.','true'),
    fb(14,'If they ___ (replicate) the study, they ___ (discover) the error. (3rd cond.)','had replicated, would have discovered'),
    fb(15,'She ___ (not/make) that mistake if she ___ (read) the instructions. (3rd cond.)','wouldn\'t have made, had read'),
  ]},
  '03b680c2-e98b-426e-a0cc-d23de081bf5a':{pass_threshold:70,questions:[ // Wishes & Regrets
    mc(1,'Complete: "I wish I ___ (have) access to a larger dataset." (present wish)','have','had','will have','would have','B'),
    mc(2,'Complete: "If only she ___ (not/overlook) those outliers." (past regret)','didn\'t overlook','hadn\'t overlooked','doesn\'t overlook','wouldn\'t overlook','B'),
    mc(3,'"I wish" + past simple expresses:','a regret about a past completed action','a wish about the present (unreal situation)','a hope for the future','a certain future event','B'),
    mc(4,'"I wish" + past perfect expresses:','a wish about the present','a regret about a past event','a future hope','a real condition','B'),
    mc(5,'Complete: "She wishes she ___ (choose) a different research methodology."','chose','chooses','had chosen','will choose','C'),
    mc(6,'Complete: "If only the data ___ (be) more consistent — it would strengthen the argument."','is','was/were','has been','will be','B'),
    mc(7,'Complete: "I wish I ___ (can) attend the symposium." (ability wish)','can','could','would','will','B'),
    mc(8,'Which expresses a regret about a past decision?','I wish I knew more about this.','I wish I had chosen a different topic.','I wish I could help.','I wish I were better at this.','B'),
    mc(9,'Complete: "He wishes the study ___ (be) more widely cited."','is','would be','were','has been','C'),
    mc(10,'Complete: "If only we ___ (conduct) a control study — the results would be more convincing."','conduct','had conducted','would conduct','were conducting','B'),
    tf(11,'"I wish I spoke better English" expresses a present wish (I don\'t speak well enough).','true'),
    tf(12,'"I wish I have more time" is correct.','false'),
    tf(13,'"If only" is used for stronger/more emphatic wishes and regrets.','true'),
    fb(14,'I wish I ___ (have, present) a larger sample. If only we ___ (consult, past) more experts.','had, had consulted'),
    fb(15,'She wishes she ___ (choose, past) a different topic. He wishes the results ___ (be, present) clearer.','had chosen, were'),
  ]},
  '379c9c33-7e8c-480c-ba13-1d4f5504e84a':{pass_threshold:70,questions:[ // Mixed Conditionals
    mc(1,'A mixed conditional combines:','Zero and First','Second and Third (or First and Second)','only past forms','only present forms','B'),
    mc(2,'Mixed (past condition + present result): "If she ___ (choose) a different topic, she ___ (be) much further along now."','had chosen / would be','had chosen / would have been','chose / will be','chose / would be','A'),
    mc(3,'Mixed (present condition + past result): "If she ___ (be) more organised, she ___ (submit) on time last week."','were / would have submitted','was / would have submitted','is / would have submitted','were / would submit','A'),
    mc(4,'Which is a Type 3+2 mixed conditional?','If it rained, we would stay in.','If she had applied, she would be working there now.','If it rains, we will stay in.','If she applies, she will get the job.','B'),
    mc(5,'Complete: "If he ___ (not/miss) the deadline, his paper ___ (be) published by now."','hadn\'t missed / would be','hasn\'t missed / would be','didn\'t miss / would be','hadn\'t missed / would have been','A'),
    mc(6,'Which is a Type 2+3 mixed conditional?','If he had studied harder, he would know the answer now.','If he were more careful, he would have avoided the error.','If it rained, we would stay in.','If she submits now, she will pass.','B'),
    mc(7,'Complete: "If this theory ___ (be) correct (which it isn\'t), Newton ___ (never/exist) in isolation."','is / would never have existed','were / would never have existed','had been / would never exist','was / would not exist','B'),
    mc(8,'Mixed conditionals allow us to:','only talk about present situations','combine different time frames in one conditional sentence','avoid if-clauses','use only past tenses','B'),
    mc(9,'Complete: "If she ___ (not/change) her method, the paper ___ (be) stronger now."','hadn\'t changed / would be','didn\'t change / would be','hadn\'t changed / would have been','hasn\'t changed / would be','A'),
    mc(10,'Complete: "If he ___ (be) a better communicator (he isn\'t), he ___ (deliver) the keynote more successfully last week."','were / would have delivered','was / would have delivered','had been / would deliver','were / would deliver','A'),
    tf(11,'Mixed conditionals combine elements from different conditional types.','true'),
    tf(12,'In a 3→2 mixed conditional, the if-clause refers to a past event, and the result clause refers to the present.','true'),
    tf(13,'Mixed conditionals always use the same tense in both clauses.','false'),
    fb(14,'If she ___ (train, PP) harder, she ___ (perform, 2nd cond. result) better now.','had trained, would perform'),
    fb(15,'If he ___ (be, 2nd cond.) more focused, he ___ (not/miss, 3rd cond. result) the deadline last month.','were, wouldn\'t have missed'),
  ]},
  'ed9e9bb7-fc84-442b-af38-46bcabe552db':{pass_threshold:70,questions:[ // Conditional Linkers
    mc(1,'What does "unless" mean in conditionals?','if','if not','even if','only when','B'),
    mc(2,'What does "provided that / providing that" mean?','unless','on the condition that','even if','as a result','B'),
    mc(3,'What does "as long as" mean?','only if','on the condition that (similar to provided that)','unless','even though','B'),
    mc(4,'Complete: "___ the participants give informed consent, the study cannot proceed."','As long as','Unless','Provided that','Even if','B'),
    mc(5,'Complete: "She will publish her findings ___ they are peer-reviewed first."','unless','provided that','even if','as long as (both B and D)','D'),
    mc(6,'What does "even if" mean?','if','regardless of whether (the condition doesn\'t change the result)','only if','if not','B'),
    mc(7,'Complete: "___ she receives negative feedback, she will continue the project."','Unless','Provided that','Even if','As long as','C'),
    mc(8,'Complete: "The grant will be approved ___ all documentation is submitted on time."','unless','even if','as long as / provided that','although','C'),
    mc(9,'What does "supposing (that)" mean?','given that / imagine that','even if','unless','on the condition that','A'),
    mc(10,'Complete: "___ you had unlimited resources, what would you research?"','Unless','Even if','Supposing (that)','Provided that','C'),
    tf(11,'"Unless" = "if not".','true'),
    tf(12,'"Provided that" means "even if".','false'),
    tf(13,'"As long as" introduces a condition that must be met.','true'),
    fb(14,'___ (Unless) she revises the methodology, the paper won\'t be accepted. The project will proceed ___ (as long as) funding is secured.','Unless, as long as'),
    fb(15,'___ (Provided that) all data is collected by June, we will meet the deadline. ___ (Even if) the results are negative, they are still publishable.','Provided that, Even if'),
  ]},
  'cc02252b-4f3a-4514-80e7-362296d997a4':{pass_threshold:80,questions:[ // Module 7 Review
    mc(1,'Zero Conditional: "If you ___ (mix) acids and bases, they ___ (neutralise)."','mix / neutralise','mix / will neutralise','mixed / neutralise','mix / neutralised','A'),
    mc(2,'First Conditional: "If she ___ (submit) early, we ___ (provide) feedback."','submits / will provide','submitted / would provide','submits / provide','submit / will provide','A'),
    mc(3,'Second Conditional: "If the sample ___ (be) larger, the results ___ (more reliable)."','were / would be','was / will be','is / would be','had been / would have been','A'),
    mc(4,'Third Conditional: "If they ___ (use) a control group, findings ___ (stronger)."','had used / would have been','used / would be','had used / would be','used / would have been','A'),
    mc(5,'Mixed (3→2): "If she ___ (not/make) that error, her reputation ___ (better) now."','hadn\'t made / would be','didn\'t make / would be','hadn\'t made / would have been','hasn\'t made / would be','A'),
    mc(6,'"Wish" + past simple: "I wish I ___ (have) more participants." (present)','have','had','will have','would have','B'),
    mc(7,'"Wish" + past perfect: "If only she ___ (choose) a better dataset." (past regret)','chose','chooses','had chosen','will choose','C'),
    mc(8,'"Unless" means:','if','if not','even if','only when','B'),
    mc(9,'"Provided that" means:','unless','on the condition that','even if','as a result','B'),
    mc(10,'Complete: "___ the funding is secured, research will commence."','Unless','Even if','As long as / Provided that','Although','C'),
    mc(11,'First Conditional, formal/inverted: "___ she apply, she would be a strong candidate."','If','Should','Unless','Even if','B'),
    mc(12,'Third Conditional expresses:','general truths','real future plans','unreal past situations / regrets','unreal present situations','C'),
    mc(13,'"Even if" means:','if','if not','regardless of whether','on condition that','C'),
    mc(14,'Second Conditional: Why use "were" for all persons?','grammar error','formal subjunctive use','only "was" is correct','only in writing','B'),
    mc(15,'"Supposing that" means:','unless','imagine that / given that','even if','on condition that','B'),
    tf(16,'Zero Conditional uses present simple in both clauses.','true'),
    tf(17,'Third Conditional uses past simple in the if-clause.','false'),
    tf(18,'"I wish I had studied harder" expresses a past regret.','true'),
    fb(19,'If the study ___ (replicate, 3rd cond.), we ___ (find) a different result.','had been replicated, would have found'),
    fb(20,'___ (Unless) she revises it, it ___ (reject, passive, 1st cond.). If only we ___ (have, wish past) more time.','Unless, will be rejected, had'),
  ]},

  // MODULE 8: Reported Speech
  '06a67789-6fd0-40f2-ae33-589eaeae7de3':{pass_threshold:70,questions:[ // Reported Statements
    mc(1,'Report: "I am conducting fieldwork." She said she ___ conducting fieldwork.','is','was','were','has been','B'),
    mc(2,'Report: "We have collected enough data." They said they ___ collected enough data.','have','had','were','would have','B'),
    mc(3,'Report: "She will present at the conference." He said she ___ present at the conference.','will','would','could','might','B'),
    mc(4,'"Can" becomes ___ in reported speech.','would','could','might','should','B'),
    mc(5,'Report: "The results are inconclusive." The researcher said the results ___ inconclusive.','are','were','would be','had been','B'),
    mc(6,'Report: "I don\'t agree with the methodology." He said he ___ agree with the methodology.','doesn\'t','didn\'t','wouldn\'t','hadn\'t','B'),
    mc(7,'What happens to "this" and "here" in reported speech?','they stay the same','they become "that" and "there"','they are deleted','they become "it" and "somewhere"','B'),
    mc(8,'Report: "We completed the analysis yesterday." They told us they ___ completed the analysis the previous day.','have','had','were','would have','B'),
    mc(9,'"Now" in reported speech becomes:','now','that moment','then / at that time','here','C'),
    mc(10,'Report: "I\'m going to publish this." She said she ___ going to publish it.','is','was','were','would be','B'),
    tf(11,'In reported speech, present tenses usually shift back one tense.','true'),
    tf(12,'"Will" remains as "will" in reported speech.','false'),
    tf(13,'"Yesterday" in direct speech becomes "the previous day/the day before" in reported speech.','true'),
    fb(14,'"I am reviewing the data," she said. → She said she ___ reviewing the data.','was'),
    fb(15,'"We have submitted the paper," they announced. → They announced they ___ submitted the paper.','had'),
  ]},
  '3223df1a-c9d2-47f5-840d-80ee37e1eab8':{pass_threshold:70,questions:[ // Reported Questions
    mc(1,'Report: "Where do you work?" → She asked me where I ___.','work','worked','was working','do work','B'),
    mc(2,'In reported questions, the word order is:','question order (inverted)','normal statement order','depends on the question word','always starts with "that"','B'),
    mc(3,'Report: "Are you coming?" → He asked if I ___ coming.','am','was','were','be','C'),
    mc(4,'What introduces a reported yes/no question?','that','what','if / whether','which','C'),
    mc(5,'Report: "Have you read Chomsky?" → She asked whether I ___ Chomsky.','have read','had read','read','was reading','B'),
    mc(6,'Report: "What time does the seminar start?" → He asked what time the seminar ___.','starts','started','is starting','would start','B'),
    mc(7,'In reported questions, "do/does/did" is:','kept','moved to the end','removed','doubled','C'),
    mc(8,'Report: "Why are you changing your methodology?" → The supervisor asked why I ___ my methodology.','change','am changing','was changing','have changed','C'),
    mc(9,'Complete: She asked me ___ I would like to co-author the paper.','that','what','if/whether','which','C'),
    mc(10,'Report: "Which university did you attend?" → He asked which university she ___ attended.','did','has','had','would have','C'),
    tf(11,'Reported questions use normal statement word order (no inversion).','true'),
    tf(12,'"She asked where did I live" is correct reported speech.','false'),
    tf(13,'"Whether" can replace "if" in reported yes/no questions.','true'),
    fb(14,'"Do you know the researcher?" → She asked if I ___ (know) the researcher.','knew'),
    fb(15,'"Where does the data come from?" → He asked where the data ___ (come) from.','came'),
  ]},
  '860a14f3-0460-400e-9925-a483f80ae678':{pass_threshold:70,questions:[ // Reported Commands
    mc(1,'Reported commands use:','to + infinitive','not + base verb','that + clause','infinitive without to','A'),
    mc(2,'Report: "Submit your work by noon," the professor said. → The professor told us ___ our work by noon.','submit','to submit','submitting','that submit','B'),
    mc(3,'Negative reported command: "Don\'t share the data," she said. → She told us ___ share the data.','not to','not','don\'t','to not (both A and C)','A'),
    mc(4,'Which verb is used for commands in reported speech?','say','tell','ask (for polite requests)','both B and C','D'),
    mc(5,'Report: "Please review the draft carefully," he asked. → He asked me ___ the draft carefully.','review','to review','reviewing','that I review','B'),
    mc(6,'Report: "Don\'t plagiarise," the professor warned. → The professor warned us ___ plagiarise.','don\'t','not','not to','to not','C'),
    mc(7,'Complete: "Leave the room immediately," the examiner ordered. → The examiner ordered them ___ the room immediately.','to leave','leave','leaving','that leave','A'),
    mc(8,'"Tell" vs "say" in reported commands: "She told me to study harder." — Is this correct?','No, it should be "she said me"','No, "tell" needs a direct object (me/us)','Yes, it is correct','No, should use "ask"','C'),
    mc(9,'Report: "Be on time," the manager insisted. → The manager insisted that we ___ on time.','be / were / should be (all possible)','are','were (subjunctive)','will be','C'),
    mc(10,'Complete: "Please don\'t interrupt during the presentation," the speaker requested. → The speaker requested the audience ___ during the presentation.','not interrupt','not to interrupt','don\'t interrupt','to not interrupt (both B and D)','B'),
    tf(11,'Reported commands use the structure: tell/ask + object + to + infinitive.','true'),
    tf(12,'"She said me to study harder" is correct.','false'),
    tf(13,'Negative reported commands use "not to + infinitive".','true'),
    fb(14,'"Submit your thesis by the deadline," she said. → She told us ___ our thesis by the deadline.','to submit'),
    fb(15,'"Don\'t share the password," he warned. → He warned us ___ the password.','not to share'),
  ]},
  '4b212e0d-dd56-4cd9-97d7-3ca7d4875061':{pass_threshold:70,questions:[ // Indirect Questions
    mc(1,'Indirect questions use:','question word order','normal statement word order','inverted subject-verb','the auxiliary "do"','B'),
    mc(2,'"Could you tell me where the conference room is?" — This is:','a direct question','an indirect (polite) question','a reported question','a rhetorical question','B'),
    mc(3,'Complete: "Do you know ___ the registration deadline is?" (indirect)','when is','when','when does','when will','B'),
    mc(4,'Complete: "I wonder ___ they have made a decision yet." (indirect)','whether / if','what','when is','that','A'),
    mc(5,'Complete: "Could you explain ___ you collected the data?" (indirect)','how did','how','how do','how is','B'),
    mc(6,'Indirect questions are typically used to:','demand information forcefully','make questions more polite or formal','ask simple questions','report what others said','B'),
    mc(7,'Complete: "I\'d like to know ___ the results are statistically significant." (indirect)','whether/if','what','how is','that','A'),
    mc(8,'Complete: "Can you tell me ___ the symposium starts?" (indirect)','when does','when','when is','that when','B'),
    mc(9,'Which is the correct indirect question?','Can you tell me where does she work?','Can you tell me where she works?','Do you know where she work?','I wonder where does she work?','B'),
    mc(10,'Complete: "I\'m not sure ___ the supervisor approved the change." (indirect)','whether/if','what','when did','who','A'),
    tf(11,'Indirect questions do not invert the subject and verb.','true'),
    tf(12,'"Could you tell me where is the library?" is correct.','false'),
    tf(13,'Indirect questions are more polite than direct questions.','true'),
    fb(14,'"Where is the lecture hall?" → Could you tell me ___ the lecture hall ___?','where, is'),
    fb(15,'"Has the supervisor approved it?" → I wonder ___ the supervisor ___ (approve) it.','whether / if, has approved'),
  ]},
  '07595b9d-af16-4d33-a892-1df9c0269afe':{pass_threshold:70,questions:[ // Reporting Verbs I
    mc(1,'Which verb reports an announcement?','whisper','deny','announce','refuse','C'),
    mc(2,'Complete: "She ___ that she would attend the conference." (inform)','told','said','informed us','Both B and C — B says, C informs us','C'),
    mc(3,'"Advise" is followed by:','that + clause only','object + to + infinitive','gerund only','noun phrase only','B'),
    mc(4,'Report: "You should apply for the grant," she said. → She advised me ___ for the grant.','apply','to apply','applying','that apply','B'),
    mc(5,'"Ask" in reporting: "She asked us ___ by 9 am." (arrive)','to arrive','arriving','arrive','that we arrived','A'),
    mc(6,'"Tell" requires:','no object','a direct object (tell someone)','only a clause','a gerund','B'),
    mc(7,'Complete: "The professor ___ the students to read the primary sources." (told/asked)','said','told/asked','announced','warned','B'),
    mc(8,'"Say" vs "tell": which requires a personal object?','say','tell','both','neither','B'),
    mc(9,'Complete: "He ___ that the findings were significant." (state formally)','said / stated','told','asked','warned','A'),
    mc(10,'Report: "Don\'t exceed the word limit," the editor warned. → The editor warned us ___ the word limit.','to exceed','not to exceed','exceeding','that exceed','B'),
    tf(11,'"Tell" always requires a direct object (tell someone).','true'),
    tf(12,'"She said me to come early" is correct.','false'),
    tf(13,'"Advise" + object + to-infinitive: "She advised me to apply."','true'),
    fb(14,'He ___ (tell) us to submit early. She ___ (advise) me not to change the topic.','told, advised'),
    fb(15,'The supervisor ___ (say/state) that the results were significant. She ___ (warn) us not to share the data.','said / stated, warned'),
  ]},
  'be8fde5d-9cf3-441b-8b0d-7dd70cd81d8f':{pass_threshold:70,questions:[ // Reporting Verbs II — Claim/Deny/Suggest
    mc(1,'"Claim" + that: "He ___ that the results were fabricated." (reported)','claimed','denied','suggested','admitted','A'),
    mc(2,'"Deny" is followed by:','to + infinitive','that + clause or gerund','object + to-infinitive','for + gerund','B'),
    mc(3,'Report: "I didn\'t plagiarise," she said. → She ___ having plagiarised.','denied','claimed','admitted','suggested','A'),
    mc(4,'"Suggest" + gerund: "He ___ reviewing the data." (recommended)','told','suggested','advised','asked','B'),
    mc(5,'"Admit" + gerund: "She ___ making an error in the calculations."','denied','suggested','admitted','claimed','C'),
    mc(6,'"Threaten" + to-infinitive: "He ___ to withdraw funding unless improvements were made."','promised','suggested','threatened','refused','C'),
    mc(7,'"Refuse" + to-infinitive: "She ___ to sign the agreement."','promised','accepted','refused','suggested','C'),
    mc(8,'"Promise" + to-infinitive: "He ___ to submit by the deadline."','threatened','promised','refused','denied','B'),
    mc(9,'"Insist" + on + gerund: "They ___ on conducting further tests."','suggested','insisted','warned','claimed','B'),
    mc(10,'Report: "I\'ll definitely finish it," he said. → He ___ to finish it.','threatened','insisted','promised','claimed','C'),
    tf(11,'"Deny" is followed by a gerund or "that + clause".','true'),
    tf(12,'"She suggested to review the data" is correct.','false'),
    tf(13,'"Admit + gerund" reports a confession: "She admitted making an error."','true'),
    fb(14,'She ___ (claim) that the data was reliable. He ___ (deny) having manipulated the results.','claimed, denied'),
    fb(15,'They ___ (insist on) replicating the study. She ___ (promise) to submit by Friday.','insisted on, promised'),
  ]},
  'f52cb8fd-552f-408b-a3c8-d6034f6d1bb8':{pass_threshold:70,questions:[ // Reported Speech in News — Media Language
    mc(1,'Which verb is formal and common in academic/news reporting?','say','go','be like','be all','A'),
    mc(2,'Which reporting verb suggests the claim may not be true?','confirm','prove','demonstrate','allege','D'),
    mc(3,'"According to" introduces:','a direct order','information attributed to a specific source','a question','a reported command','B'),
    mc(4,'What does "sources close to X claim that..." suggest?','confirmed fact','anonymous sourcing — unverified information','a direct quote','a command','B'),
    mc(5,'Which is a neutral reporting verb in journalism?','accuse','praise','state/report','condemn','C'),
    mc(6,'Complete: "The minister ___ that no agreement had been reached." (formal, neutral)','went','was like','stated/confirmed','promised me','C'),
    mc(7,'"The study ___ that regular exercise reduces stress." (neutral academic reporting)','goes','shows/indicates/demonstrates','alleges','threatens','B'),
    mc(8,'What does "to attribute a quote to someone" mean?','to disagree with someone','to state who said something','to deny a quote','to invent a quote','B'),
    mc(9,'Which pattern is used in news to suggest uncertainty?','The minister confirmed...','The minister has officially stated...','The minister is reportedly/allegedly...','The minister proved...','C'),
    mc(10,'Complete: "The report ___ a significant increase in academic publishing." (present neutral)','alleges','goes','indicates/shows','claims falsely','C'),
    tf(11,'"Allege" suggests the claim is not confirmed or may be disputed.','true'),
    tf(12,'"According to" always means the information is 100% verified.','false'),
    tf(13,'"State" is a more neutral and formal reporting verb than "say".','true'),
    fb(14,'The study ___ (indicate/show) a correlation. The minister ___ (allege) fraud without evidence.','indicates / shows, alleged'),
    fb(15,'"___ (According to) the report, results improved. The suspect ___ (deny) all charges.','According to, denied'),
  ]},
  '6d34dd03-0f23-47e5-a8a7-04f0607f99e6':{pass_threshold:80,questions:[ // Module 8 Review
    mc(1,'Report (statement): "I am writing a monograph." → She said she ___ a monograph.','is writing','was writing','wrote','had been writing','B'),
    mc(2,'Report (statement): "We have submitted the paper." → They said they ___ the paper.','have submitted','had submitted','submitted','were submitting','B'),
    mc(3,'Report (question): "Where do you publish?" → She asked where I ___.','publish','published','do publish','was publishing','B'),
    mc(4,'Report (yes/no question): "Have you applied?" → He asked if I ___ applied.','have','had','did','was','B'),
    mc(5,'Report (command): "Submit your work." → She told us ___ our work.','submit','to submit','submitting','that submit','B'),
    mc(6,'Indirect question: "Could you tell me ___ the seminar starts?" (indirect)','when does','when','when is','that when','B'),
    mc(7,'Reporting verb — "advise": "She ___ me to revise the methodology."','said','told','advised','asked (both C and D)','C'),
    mc(8,'Reporting verb — "deny": "He ___ having plagiarised."','admitted','denied','claimed','refused','B'),
    mc(9,'Reporting verb — "promise": "She ___ to submit by Friday."','threatened','refused','promised','denied','C'),
    mc(10,'"Allege" in news/academic writing suggests:','confirmed fact','possible but unconfirmed claim','a direct command','established proof','B'),
    mc(11,'"According to" introduces:','a direct order','information from a specific source','a command','a reported question','B'),
    mc(12,'Report: "I won\'t share the data," she said. → She refused ___ the data.','share','to share','sharing','that share','B'),
    mc(13,'In reported speech, "now" becomes:','now','here','then / at that time','there','C'),
    mc(14,'Indirect question word order: Which is correct?','Can you tell me where is the lab?','Can you tell me where the lab is?','Do you know where is the lab?','I wonder where is the lab?','B'),
    mc(15,'"Suggest" + gerund: "She ___ replicating the study."','told','suggested','said','advised','B'),
    tf(16,'"Tell" requires a direct object.','true'),
    tf(17,'In reported questions, the subject-verb order is inverted.','false'),
    tf(18,'"Deny + gerund" is used to report a denial of an action.','true'),
    fb(19,'"Will you attend?" → He asked ___ (whether/if) I would attend. She ___ (claim) the data was accurate.','whether / if, claimed'),
    fb(20,'She ___ (tell) us not to exceed the limit. He ___ (suggest) reviewing the findings.','told, suggested'),
  ]},
}

async function main(){
  const MODULES=[
    {id:'54acee01-078e-4a28-a231-8eb51fc10b8f',n:7,title:'Conditionals I'},
    {id:'aca58153-adeb-4cf0-ba74-51116b71169c',n:8,title:'Reported Speech'},
  ]
  let total=0
  for(const mod of MODULES){
    console.log(`\n🔍 B1 Intermediate — Module ${mod.n}: "${mod.title}"`)
    const{data:lessons,error:le}=await supabase.from('english_lessons').select('id,title,order_index').eq('module_id',mod.id).order('order_index')
    if(le)throw le
    const{data:existing,error:qe}=await supabase.from('english_quizzes').select('lesson_id').in('lesson_id',lessons!.map(l=>l.id))
    if(qe)throw qe
    const ex=new Set((existing??[]).map(q=>q.lesson_id))
    const missing=lessons!.filter(l=>!ex.has(l.id))
    console.log(`📋 Total: ${lessons!.length} | ✅ Have: ${ex.size} | ❌ Missing: ${missing.length}`)
    for(const lesson of missing){
      const d=QUIZZES[lesson.id]
      if(!d){console.log(`⚠️  Skipped: ${lesson.title}`);continue}
      const{error}=await supabase.from('english_quizzes').insert({lesson_id:lesson.id,questions:d.questions,pass_threshold:d.pass_threshold})
      if(error){console.error(`❌ Failed: ${lesson.title}: ${error.message}`);continue}
      console.log(`✅ Вставлен квиз: ${lesson.title} — ${d.questions.length} вопросов`)
      total++
    }
  }
  console.log(`\n✅ Готово: ${total} квизов создано для модулей 7–8 B1 Intermediate`)
}
main().catch(e=>{console.error(e);process.exit(1)})
