-- ============================================================
-- B1 Intermediate / Module 2 (Love & Relationships)
-- Reading Sections — Lessons 1–7
-- Theme: Historical Events / Cultural Change
-- ============================================================

-- ── Lesson 1 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Great Migration: Millions in Motion",
  "text": "Between 1910 and 1970, approximately six million African Americans left the rural American South and moved to cities in the North, Midwest, and West. Historians call this the Great Migration, and it stands as one of the most significant demographic transformations in American history. Life in the South offered little hope for Black Americans. Jim Crow laws enforced racial segregation, restricting access to education, employment, and political participation. The constant threat of racial violence made everyday life dangerous. When World War One created a demand for industrial workers in Northern factories, many African Americans saw an opportunity and moved north. Cities like Chicago, Detroit, New York, and Pittsburgh absorbed hundreds of thousands of new residents. Migrants worked in steel mills, slaughterhouses, and automobile factories, earning wages far higher than anything available in the South. They formed vibrant communities, established churches, newspapers, and cultural organisations, and transformed the social landscape of Northern cities. The Great Migration was not without hardship. Northern cities were not free from racism. Migrants frequently faced discrimination in housing, employment, and daily life. Race riots of 1919 in Chicago and other cities revealed that prejudice existed well beyond the South. Despite these obstacles, the migration created new political power. African American voters in Northern cities gradually became an important force in national elections. The movement also produced a remarkable cultural flowering. The Harlem Renaissance brought African American literature, art, and music to international attention, permanently transforming American culture and laying the foundation for subsequent civil rights movements.",
  "glossary": [
    {"term": "migration", "definition": "the movement of people from one place to another in search of better conditions", "translation": "миграция"},
    {"term": "segregation", "definition": "the enforced separation of racial or social groups", "translation": "сегрегация"},
    {"term": "demographic", "definition": "relating to the statistical characteristics of human populations", "translation": "демографический"},
    {"term": "discrimination", "definition": "unjust treatment of people based on race, gender, or other characteristics", "translation": "дискриминация"},
    {"term": "renaissance", "definition": "a period of renewed cultural and intellectual activity", "translation": "возрождение"},
    {"term": "prejudice", "definition": "an unfair opinion formed without knowledge or experience of the facts", "translation": "предрассудок"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What was the Great Migration according to the passage?", "options": ["A) A movement of European immigrants to North America", "B) The movement of six million African Americans from the South to Northern cities", "C) A migration of farm workers fleeing the Midwest drought", "D) The forced relocation of Native Americans from their lands"], "answer": "B", "explanation": "The passage states that approximately six million African Americans moved from the rural South to cities in the North, Midwest, and West."},
    {"id": 2, "question": "What drew African Americans to Northern cities?", "options": ["A) Government relocation programmes", "B) Better climate and available farmland", "C) Industrial jobs created by World War One demand", "D) The abolition of racial laws in Northern states"], "answer": "C", "explanation": "When World War One created a demand for industrial workers in Northern factories, many African Americans saw an opportunity and moved north."},
    {"id": 3, "question": "Which cities are mentioned as major destinations for migrants?", "options": ["A) Los Angeles, Miami, and Boston", "B) Chicago, Detroit, New York, and Pittsburgh", "C) Houston, Dallas, and New Orleans", "D) Philadelphia, Baltimore, and Washington"], "answer": "B", "explanation": "The passage specifically names Chicago, Detroit, New York, and Pittsburgh as cities that absorbed hundreds of thousands of migrants."},
    {"id": 4, "question": "What does the passage say about racial attitudes in Northern cities?", "options": ["A) Racism did not exist in the North", "B) Northern cities quickly eliminated discrimination", "C) Race riots and discrimination showed racism was not limited to the South", "D) Migrants were welcomed and integrated without conflict"], "answer": "C", "explanation": "Race riots of 1919 in Chicago revealed that prejudice existed well beyond the South."},
    {"id": 5, "question": "What was the cultural result of the Great Migration?", "options": ["A) A decline in African American artistic traditions", "B) The Harlem Renaissance brought African American culture to international attention", "C) Southern traditions completely replaced Northern cultural forms", "D) African Americans assimilated into white culture without maintaining their own identity"], "answer": "B", "explanation": "The Harlem Renaissance brought African American literature, art, and music to international attention, permanently transforming American culture."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The Great Migration lasted approximately sixty years.", "answer": true, "evidence": "Between 1910 and 1970, approximately six million African Americans left the rural American South."},
    {"id": 2, "statement": "Jim Crow laws gave African Americans equal access to education and employment in the South.", "answer": false, "evidence": "Jim Crow laws enforced racial segregation, restricting access to education, employment, and political participation."},
    {"id": 3, "statement": "Northern cities were completely free from racism and discrimination.", "answer": false, "evidence": "Northern cities were not free from racism. Migrants frequently faced discrimination in housing, employment, and daily life."},
    {"id": 4, "statement": "African American voters in Northern cities gradually gained political influence.", "answer": true, "evidence": "African American voters in Northern cities gradually became an important force in national elections."},
    {"id": 5, "statement": "The Harlem Renaissance represented a decline in African American cultural production.", "answer": false, "evidence": "The Harlem Renaissance brought African American literature, art, and music to international attention, permanently transforming American culture."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Jim Crow laws enforced racial [BLANK], restricting access to education, employment, and political participation.", "options": ["A) equality", "B) segregation", "C) harmony", "D) freedom"], "answer": "B", "explanation": "Segregation means the enforced separation of racial groups, which is what Jim Crow laws imposed."},
    {"id": 2, "sentence": "When World War One created a [BLANK] for industrial workers, many African Americans moved north.", "options": ["A) shortage", "B) surplus", "C) demand", "D) requirement"], "answer": "C", "explanation": "Demand means a need for something — the war created a need for factory workers that African Americans could fill."},
    {"id": 3, "sentence": "The movement also produced a remarkable cultural [BLANK] that brought African American art and music to international attention.", "options": ["A) collapse", "B) competition", "C): conflict", "D) flowering"], "answer": "D", "explanation": "Flowering means a period of growth and flourishing — the passage uses this word to describe the cultural output of the period."},
    {"id": 4, "sentence": "Race riots revealed that [BLANK] existed well beyond the South, challenging the idea that the North was free from racism.", "options": ["A) equality", "B) opportunity", "C) prejudice", "D) migration"], "answer": "C", "explanation": "Prejudice — an unfair opinion formed without knowledge — is the exact word used in the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes push factors (escaping oppression) and pull factors (seeking opportunity) that caused the Great Migration. Which do you think was more powerful? Give reasons.", "suggested_answer": "Both factors were essential, but the push factors — racial violence, legal segregation, and the daily threat of oppression — were perhaps more powerful as immediate motivators. The danger was real and life-threatening. Without the urgent need to escape, many might have chosen familiar surroundings over the uncertainty of migration. The pull of industrial jobs provided direction, but the fundamental motivation came from the unbearable conditions left behind."},
    {"id": 2, "question": "The passage shows that African Americans built vibrant communities and a cultural renaissance despite facing discrimination in the North. What does this tell us about how communities respond to adversity?", "suggested_answer": "Communities facing hardship often develop remarkable cultural strength as a form of resistance and self-expression. The Harlem Renaissance demonstrates that creativity can flourish even under difficult conditions. Building institutions, sharing traditions, and finding solidarity are ways displaced communities maintain identity and dignity. This pattern appears repeatedly throughout history in the experiences of many immigrant and minority communities worldwide."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 1
) AND type = 'reading';

-- ── Lesson 2 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Industrial Revolution: A World Transformed",
  "text": "The Industrial Revolution began in Britain in the late eighteenth century and transformed the social and economic structure of the entire world. Before this transformation, most people worked in agriculture in rural communities. The invention of the steam engine changed everything, powering factories, ships, and railways and making mass production possible for the first time. The textile industry was among the first to industrialise. Machines replaced skilled handweavers who had worked in their homes for generations. Factory owners could produce cloth far more quickly and cheaply with machinery, but the human cost was considerable. Workers laboured for twelve to sixteen hours a day in dangerous conditions for very low wages. Cities grew rapidly as people left the countryside in search of work. Manchester, Birmingham, and Leeds transformed from market towns into sprawling industrial centres. Housing was overcrowded, sanitation was poor, and air and water pollution caused widespread illness. Child labour was commonplace, with children as young as six working in mines and textile mills. The abuses of industrialisation gradually prompted social reform. Writers like Charles Dickens exposed the suffering of the poor through fiction. Reformers campaigned for legislation to improve conditions. The Factory Acts limited working hours, banned child labour, and required basic safety measures. Trade unions grew stronger, giving workers collective bargaining power. The Industrial Revolution ultimately raised living standards enormously, but its benefits were distributed very unequally. The extraordinary wealth generated by industry concentrated in the hands of factory owners and investors, while those who did the physical labour lived in poverty for decades before reform brought meaningful improvement.",
  "glossary": [
    {"term": "industrialisation", "definition": "the development of large-scale industry in a society or region", "translation": "индустриализация"},
    {"term": "urbanisation", "definition": "the process by which more people come to live in cities and towns", "translation": "урбанизация"},
    {"term": "mechanisation", "definition": "the introduction of machines to replace human labour", "translation": "механизация"},
    {"term": "textile", "definition": "relating to the manufacture of cloth, fabric, and related products", "translation": "текстиль"},
    {"term": "trade union", "definition": "an organisation of workers that campaigns for better pay and working conditions", "translation": "профсоюз"},
    {"term": "reform", "definition": "the improvement of social, political, or economic conditions through change", "translation": "реформа"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "When and where did the Industrial Revolution begin according to the passage?", "options": ["A) In France in the early nineteenth century", "B) In Britain in the late eighteenth century", "C) In the United States after the Civil War", "D) In Germany following national unification"], "answer": "B", "explanation": "The passage states that the Industrial Revolution began in Britain in the late eighteenth century."},
    {"id": 2, "question": "What invention does the passage describe as transforming manufacturing, transportation, and agriculture?", "options": ["A) The printing press", "B) The internal combustion engine", "C) The steam engine", "D) The mechanical loom"], "answer": "C", "explanation": "The invention of the steam engine powered factories, ships, and railways, making mass production possible."},
    {"id": 3, "question": "What were living conditions like for factory workers in early industrial cities?", "options": ["A) Comfortable and regulated by government legislation", "B) Often desperate, with poor housing, pollution, and low wages", "C) Better than rural life, with access to modern facilities", "D) Variable depending on the type of factory"], "answer": "B", "explanation": "Housing was overcrowded, sanitation was poor, air and water pollution caused illness, and wages were very low."},
    {"id": 4, "question": "What does the passage say about child labour during the Industrial Revolution?", "options": ["A) It was rare and quickly banned", "B) It was limited to children over twelve", "C) It was commonplace, with children as young as six working in mines and mills", "D) It only existed in agricultural work"], "answer": "C", "explanation": "Child labour was commonplace, with children as young as six working in mines and textile mills."},
    {"id": 5, "question": "What eventually improved conditions for industrial workers?", "options": ["A) Employers voluntarily raised wages", "B) Workers returned to rural areas", "C) Factory Acts and trade unions improved conditions through law and collective action", "D) New machinery eliminated the need for dangerous labour"], "answer": "C", "explanation": "The Factory Acts limited working hours and banned child labour, while trade unions gave workers collective bargaining power."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Before the Industrial Revolution, most people in Britain lived in cities and worked in factories.", "answer": false, "evidence": "Before this transformation, most people worked in agriculture in rural communities."},
    {"id": 2, "statement": "The textile industry was among the first sectors to industrialise.", "answer": true, "evidence": "The textile industry was among the first to industrialise, with machines replacing skilled handweavers."},
    {"id": 3, "statement": "All children were legally protected from factory work from the beginning of the Industrial Revolution.", "answer": false, "evidence": "Child labour was commonplace, with children as young as six working in mines and textile mills."},
    {"id": 4, "statement": "The Factory Acts helped limit working hours and improve safety standards.", "answer": true, "evidence": "The Factory Acts limited working hours, banned child labour, and required basic safety measures."},
    {"id": 5, "statement": "The benefits of the Industrial Revolution were distributed equally across all sections of society.", "answer": false, "evidence": "The extraordinary wealth generated by industry concentrated in the hands of factory owners and investors, while those who did the physical labour lived in poverty."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The introduction of machines to replace human labour in factories is known as [BLANK].", "options": ["A) urbanisation", "B) mechanisation", "C) globalisation", "D) industrialisation"], "answer": "B", "explanation": "Mechanisation specifically refers to the introduction of machines to replace human labour."},
    {"id": 2, "sentence": "Cities grew rapidly as people left the countryside for work. This process of more people living in cities is called [BLANK].", "options": ["A) industrialisation", "B) migration", "C) urbanisation", "D) commercialisation"], "answer": "C", "explanation": "Urbanisation is the process by which more people come to live in cities and towns."},
    {"id": 3, "sentence": "Trade unions grew stronger, giving workers a [BLANK] voice and the ability to negotiate with employers.", "options": ["A) political", "B) collective", "C) individual", "D) permanent"], "answer": "B", "explanation": "A collective voice means workers speaking together as a group, which gave them more power against employers."},
    {"id": 4, "sentence": "Reformers campaigned for legislation to improve conditions. Their efforts eventually produced significant social [BLANK].", "options": ["A) conflict", "B) revolution", "C) reform", "D) collapse"], "answer": "C", "explanation": "Reform means the improvement of conditions through change, which is what the campaigners achieved."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes how new technology transformed work during the Industrial Revolution. Do you think AI and automation today will have similar social consequences? Give reasons.", "suggested_answer": "The parallels are significant. Just as the steam engine displaced skilled artisans and created new factory jobs, AI and automation are displacing routine workers while creating new roles in technology and services. In both cases, the transition is painful for workers who lose traditional livelihoods. History suggests that new technology ultimately creates more wealth and new kinds of work, but this does not automatically help those who lose their current employment. The need for retraining programmes and social protection is just as relevant today."},
    {"id": 2, "question": "The passage shows that improving working conditions required both individual activism and collective organisation. Which is more effective in fighting for social justice: individual action or collective action?", "suggested_answer": "Collective action is generally more effective because it amplifies the power of individuals who might otherwise be easily ignored. A single worker complaining about unsafe conditions has little leverage over an employer, but a trade union representing thousands can negotiate, strike, and use political influence. However, individual leadership and courage are essential to starting and sustaining collective movements. The most successful social changes combine visionary individuals with broad-based collective organisation."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 2
) AND type = 'reading';

-- ── Lesson 3 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Fall of the Berlin Wall: One Night That Changed Europe",
  "text": "On the night of 9 November 1989, thousands of East Germans gathered at checkpoints in Berlin, demanding the right to travel freely to the West. The border guards, overwhelmed and without clear orders, opened the gates. What followed was one of the most extraordinary nights in modern European history. People climbed onto the Berlin Wall with hammers and chisels and began dismantling the structure that had divided the city for twenty-eight years. The Berlin Wall had been built in 1961 by the East German government to stop its citizens from fleeing to the West through Berlin. Before its construction, three million people had already left East Germany. The wall stretched more than one hundred and fifty kilometres around West Berlin. Over two hundred and forty people died attempting to cross it during its existence. The events leading to the fall began months earlier. In the summer of 1989, Hungary opened its border with Austria, allowing thousands of East Germans to escape to the West through a different route. Mass demonstrations swept East Germany in October. Hundreds of thousands gathered in Leipzig and East Berlin to demand political reform and freedom of movement. On 9 November, a Communist Party spokesman mistakenly announced at a press conference that new travel regulations would apply immediately. The announcement was broadcast across East Germany. Within hours, enormous crowds assembled at border crossings. The guards, lacking orders to stop them, stood aside. Families separated for decades were reunited that night. Germany was formally reunified within a year. The broader transformation proved irreversible — within two years, the Soviet Union itself had dissolved, and the Cold War had effectively ended.",
  "glossary": [
    {"term": "Cold War", "definition": "the period of political tension between the USA and Soviet Union from 1947 to 1991", "translation": "Холодная война"},
    {"term": "checkpoint", "definition": "a place where people and vehicles are stopped and identity is checked at a border", "translation": "контрольно-пропускной пункт"},
    {"term": "exodus", "definition": "the large-scale departure of many people from a place at the same time", "translation": "массовый исход"},
    {"term": "reunification", "definition": "the process of uniting something that was previously separated or divided", "translation": "воссоединение"},
    {"term": "dissolution", "definition": "the formal ending or breaking up of an organisation or political union", "translation": "распад, роспуск"},
    {"term": "demonstration", "definition": "a public event where people gather to show their support for or opposition to something", "translation": "демонстрация"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "When did the Berlin Wall fall according to the passage?", "options": ["A) 9 November 1961", "B) 9 November 1989", "C) 3 October 1990", "D) 25 December 1991"], "answer": "B", "explanation": "The passage states the events took place on the night of 9 November 1989."},
    {"id": 2, "question": "Why was the Berlin Wall originally built?", "options": ["A) To protect East Germany from Western military attack", "B) To stop East Germans from fleeing to the West", "C) To create a controlled trade corridor between the two halves of Berlin", "D) To divide the city as agreed by the four Allied powers"], "answer": "B", "explanation": "The wall was built to stop citizens from fleeing to the West through Berlin."},
    {"id": 3, "question": "What event in Hungary contributed to the pressure on East Germany in 1989?", "options": ["A) Hungary declared independence from the Soviet Union", "B) Hungary opened its border with Austria, allowing East Germans to escape", "C) Hungary expelled all Soviet troops from its territory", "D) Hungary offered official asylum to East German political refugees"], "answer": "B", "explanation": "Hungary opened its border with Austria, allowing thousands of East Germans to escape to the West through a different route."},
    {"id": 4, "question": "How did the wall fall on 9 November according to the passage?", "options": ["A) Western forces crossed the border and demolished it", "B) The East German government ordered its demolition", "C) A spokesman mistakenly announced new travel rules and overwhelmed guards stepped aside", "D) A popular armed uprising overthrew the border guards"], "answer": "C", "explanation": "A Communist Party spokesman mistakenly announced new travel regulations would apply immediately, and the guards stepped aside when faced with enormous crowds."},
    {"id": 5, "question": "What larger change did the fall of the Berlin Wall lead to?", "options": ["A) The permanent division of Germany into two separate states", "B) German reunification and eventually the dissolution of the Soviet Union", "C) A military conflict between East and West Germany", "D) The creation of a new European political organisation"], "answer": "B", "explanation": "Germany was formally reunified within a year, and within two years the Soviet Union had dissolved."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The Berlin Wall stood for exactly twenty years before it fell.", "answer": false, "evidence": "The wall had divided the city for twenty-eight years."},
    {"id": 2, "statement": "More than two hundred people died attempting to cross the Berlin Wall.", "answer": true, "evidence": "Over two hundred and forty people died attempting to cross it during its existence."},
    {"id": 3, "statement": "The fall of the Berlin Wall was the result of a carefully planned operation.", "answer": false, "evidence": "A Communist Party spokesman mistakenly announced at a press conference that new travel regulations would apply immediately."},
    {"id": 4, "statement": "Hungary played a role in the events leading to the fall of the wall.", "answer": true, "evidence": "In the summer of 1989, Hungary opened its border with Austria, allowing thousands of East Germans to escape to the West."},
    {"id": 5, "statement": "German reunification took several decades to complete after the wall fell.", "answer": false, "evidence": "Germany was formally reunified within a year."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Thousands of East Germans gathered at [BLANK] in Berlin, demanding the right to travel freely to the West.", "options": ["A) protests", "B) checkpoints", "C) borders", "D) stations"], "answer": "B", "explanation": "Checkpoints are the specific controlled crossing points at a border, which is the word used in the passage."},
    {"id": 2, "sentence": "The wall was built to stop the mass [BLANK] of East Germans who were leaving the country in large numbers.", "options": ["A) arrival", "B) immigration", "C) exodus", "D) movement"], "answer": "C", "explanation": "Exodus specifically describes the large-scale departure of many people from a place."},
    {"id": 3, "sentence": "Germany was formally [BLANK] within a year of the wall falling, ending the division that had begun after World War Two.", "options": ["A) liberated", "B) reunified", "C) rebuilt", "D) transformed"], "answer": "B", "explanation": "Reunified means brought back together as one country, which is what happened to Germany."},
    {"id": 4, "sentence": "Within two years, the Soviet Union itself had [BLANK], and the Cold War had effectively ended.", "options": ["A) collapsed", "B) reformed", "C) dissolved", "D) declined"], "answer": "C", "explanation": "Dissolved is the exact word used in the passage to describe the formal ending of the Soviet Union."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage shows that the wall fell partly by accident — a spokesman made a mistake. What does this tell us about how historical change can occur in unexpected ways?", "suggested_answer": "This example shows that major historical events are not always the result of careful planning. Sometimes a single mistake can trigger a chain of events that reshapes history. The crowds were ready to act, the political pressure had been building for years, and the system was fragile — the spokesman's error was the spark that ignited already-present forces. This suggests that while structural conditions create the possibility of change, specific moments and even accidents can determine when and how that change actually happens."},
    {"id": 2, "question": "The Berlin Wall was a physical symbol of political division. In the modern world, what other kinds of barriers — physical or non-physical — divide people? What purpose do they serve?", "suggested_answer": "Physical border barriers continue to exist in many parts of the world, often justified by concerns about migration or security. Digital barriers such as internet censorship and information restrictions are modern equivalents that limit the free flow of ideas. Both types of barrier reflect the same underlying tension: states seeking to control what and who crosses their borders. The lesson from the Berlin Wall is that barriers built on fear and repression are ultimately unsustainable. Addressing the root causes of conflict and inequality tends to be more effective than physical or digital separation."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 3
) AND type = 'reading';

-- ── Lesson 4 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Female Suffrage: The Long Fight for the Vote",
  "text": "The struggle for female voting rights is one of the defining social movements of the modern era. In the nineteenth century, women in most countries had no political rights. They could not vote, stand for election, or hold public office. The movement to change this began in the United States and Britain in the mid-nineteenth century. In the United Kingdom, the suffragette movement gained momentum in the early twentieth century under the leadership of figures such as Emmeline Pankhurst. Activists organised marches, public demonstrations, and hunger strikes. Some used more confrontational tactics including breaking windows and chaining themselves to government buildings. The movement faced fierce opposition. Many politicians and commentators argued that women lacked the capacity for political judgement. Suffragettes who went on hunger strike in prison were force-fed in painful and degrading procedures. The turning point came during World War One. As millions of men went to fight, women stepped into factories, offices, and hospitals, managing essential functions of the national economy. The argument that women were unfit for public life became impossible to sustain. In 1918, British women over thirty gained the right to vote. Full equal suffrage for all adult women in Britain came in 1928. In the United States, the Nineteenth Amendment to the Constitution granted women the vote in 1920. Switzerland did not extend this right to women until 1971, and some countries continue to restrict full political participation for women. The suffrage movement established a precedent for organised political activism and became a model for subsequent civil rights and equality movements around the world.",
  "glossary": [
    {"term": "suffrage", "definition": "the right to vote in political elections", "translation": "избирательное право"},
    {"term": "petition", "definition": "a formal written request signed by many people and submitted to an authority", "translation": "петиция"},
    {"term": "civil disobedience", "definition": "the active refusal to obey certain laws as a form of peaceful political protest", "translation": "гражданское неповиновение"},
    {"term": "amendment", "definition": "a change or addition made to a law or constitution", "translation": "поправка к закону или конституции"},
    {"term": "suffragette", "definition": "a woman who campaigned for the right to vote in the early twentieth century", "translation": "суфражистка"},
    {"term": "precedent", "definition": "an earlier decision or action that serves as an example or guide for later ones", "translation": "прецедент"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What was the situation of women in most countries in the nineteenth century?", "options": ["A) They had full political rights including the vote", "B) They had limited voting rights in some countries", "C) They had no political rights and could not vote or hold office", "D) They could vote in local but not national elections"], "answer": "C", "explanation": "Women in most countries had no political rights — they could not vote, stand for election, or hold public office."},
    {"id": 2, "question": "What tactics did the suffragette movement use in Britain?", "options": ["A) Armed resistance and revolutionary violence", "B) Marches, hunger strikes, and confrontational direct action", "C) Only legal challenges through the court system", "D) Boycotts of consumer products to pressure the government"], "answer": "B", "explanation": "Activists organised marches, hunger strikes, and confrontational tactics including breaking windows and chaining themselves to buildings."},
    {"id": 3, "question": "How did World War One change the argument for female suffrage?", "options": ["A) Women chose to pause their campaign to support the war effort", "B) The government banned suffragette activity during the war", "C) Women proved their indispensable role by taking on essential wartime responsibilities", "D) The war showed that women were unable to manage demanding work"], "answer": "C", "explanation": "Women stepped into factories, offices, and hospitals, making the argument that they were unfit for public life impossible to sustain."},
    {"id": 4, "question": "When did British women first gain the right to vote?", "options": ["A) In 1900 after decades of peaceful campaigning", "B) In 1918, with women over thirty gaining the vote", "C) In 1928, when all adult women received equal voting rights", "D) In 1920, following the Nineteenth Amendment"], "answer": "B", "explanation": "In 1918, British women over thirty gained the right to vote."},
    {"id": 5, "question": "Which country is mentioned as not granting women the vote until 1971?", "options": ["A) France", "B) Saudi Arabia", "C) Switzerland", "D) Australia"], "answer": "C", "explanation": "The passage states that Switzerland did not extend the right to vote to women until 1971."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The movement for female voting rights began in the mid-nineteenth century in the United States and Britain.", "answer": true, "evidence": "The movement to change this began in the United States and Britain in the mid-nineteenth century."},
    {"id": 2, "statement": "All politicians and public figures supported the suffragette cause from the beginning.", "answer": false, "evidence": "The movement faced fierce opposition. Many politicians and commentators argued that women lacked the capacity for political judgement."},
    {"id": 3, "statement": "Suffragettes faced imprisonment and force-feeding when they went on hunger strike.", "answer": true, "evidence": "Suffragettes who went on hunger strike in prison were force-fed in painful and degrading procedures."},
    {"id": 4, "statement": "American women gained the right to vote in the same year as British women over thirty.", "answer": false, "evidence": "In 1918, British women over thirty gained the right to vote. In the United States, the Nineteenth Amendment granted women the vote in 1920."},
    {"id": 5, "statement": "By 1928, all adult women in Britain had equal voting rights.", "answer": true, "evidence": "Full equal suffrage for all adult women in Britain came in 1928."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The Nineteenth Amendment to the United States Constitution granted women the right to vote. An amendment is a [BLANK] made to a law or constitution.", "options": ["A) proposal", "B) debate", "C) change", "D) protest"], "answer": "C", "explanation": "An amendment is a formal change or addition made to a law or constitution."},
    {"id": 2, "sentence": "The suffragette movement gained momentum under the leadership of Emmeline Pankhurst, who organised marches and acts of [BLANK] against government policies.", "options": ["A) civil disobedience", "B) armed resistance", "C) economic protest", "D) legal reform"], "answer": "A", "explanation": "Civil disobedience — active refusal to obey certain laws as protest — is one of the tactics described in the passage."},
    {"id": 3, "sentence": "The suffrage movement established a [BLANK] for organised political activism that later movements for civil rights and equality followed.", "options": ["A) failure", "B) precedent", "C) campaign", "D) tradition"], "answer": "B", "explanation": "A precedent is an earlier example that serves as a guide for later actions, which is how the suffrage movement influenced future movements."},
    {"id": 4, "sentence": "Women stepping into factories and hospitals during World War One proved their [BLANK] to national life, undermining arguments that they were unfit for public roles.", "options": ["A) ambition", "B) independence", "C) contribution", "D) determination"], "answer": "C", "explanation": "Contribution describes the valuable role women played — making it impossible to argue they were unfit for public life."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "Women had to prove their value through wartime service before receiving political rights. Do you think rights should have to be earned, or should they be granted automatically? Explain.", "suggested_answer": "Rights, by definition, should not need to be earned — they exist regardless of individual contribution or behaviour. The fact that women had to demonstrate their value through wartime service before receiving the vote reveals a fundamental injustice. However, the historical reality is that marginalised groups often had to challenge prejudice directly before formal legal change occurred. This reflects a gap between the ideal of universal rights and the political reality of how change is actually achieved in practice."},
    {"id": 2, "question": "The suffragettes used both peaceful protest and more disruptive direct action. When, if ever, is it justified to break the law to fight for rights?", "suggested_answer": "When legal channels are exhausted and a system refuses to extend basic rights, direct action and civil disobedience can be justified as a last resort. Historical examples — from the suffragettes to the civil rights movement — show that non-violent but disruptive tactics can change public opinion and force political action. The moral justification depends on the injustice being challenged and the commitment to avoiding harm to other people. Violent tactics are harder to justify and often undermine the cause by alienating potential supporters."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 4
) AND type = 'reading';

-- ── Lesson 5 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Moon Landing: Humanity Steps Beyond Earth",
  "text": "On 20 July 1969, Neil Armstrong became the first human to walk on the surface of the Moon. As he stepped onto the lunar surface, he spoke words broadcast live to hundreds of millions of people on Earth. The Apollo 11 mission, carried out by NASA, represented the culmination of eight years of intensive scientific and technological development. The mission was the product of the Space Race, a competition between the United States and the Soviet Union for leadership in space exploration. The Soviets achieved significant early milestones: Sputnik, the first artificial satellite, was launched in 1957, and Yuri Gagarin became the first human in space in 1961. These achievements alarmed the United States government and public. President Kennedy responded by committing the country to landing an astronaut on the Moon before the end of the 1960s. NASA received enormous funding and attracted some of the finest scientists and engineers in the country. The Apollo 11 crew consisted of three astronauts: Neil Armstrong and Buzz Aldrin descended to the lunar surface in the landing module, while Michael Collins remained in orbit. Armstrong and Aldrin spent approximately two and a half hours on the surface, collecting rock samples and conducting scientific experiments. They planted an American flag and left a plaque reading that they came in peace for all mankind. The Apollo programme continued until 1972, with twelve astronauts walking on the Moon in total. It remains one of the greatest achievements in human history and a lasting symbol of what science, determination, and international competition can inspire humanity to accomplish.",
  "glossary": [
    {"term": "lunar", "definition": "relating to the Moon", "translation": "лунный"},
    {"term": "satellite", "definition": "an object that orbits a larger body in space, either natural or artificial", "translation": "спутник"},
    {"term": "culmination", "definition": "the highest or final point of something, representing its completion", "translation": "кульминация"},
    {"term": "orbit", "definition": "the curved path followed by an object moving around a larger body in space", "translation": "орбита"},
    {"term": "milestone", "definition": "an important achievement that marks a significant stage in a process", "translation": "важный этап, веха"},
    {"term": "module", "definition": "a separate, self-contained unit that forms part of a larger system or vehicle", "translation": "модуль"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "Who was the first human to walk on the surface of the Moon?", "options": ["A) Yuri Gagarin", "B) Buzz Aldrin", "C) Michael Collins", "D) Neil Armstrong"], "answer": "D", "explanation": "On 20 July 1969, Neil Armstrong became the first human to walk on the surface of the Moon."},
    {"id": 2, "question": "What was the Space Race as described in the passage?", "options": ["A) A scientific project jointly run by the US and Soviet Union", "B) A competition between the United States and the Soviet Union in space exploration", "C) A commercial competition between private aerospace companies", "D) A series of missions to photograph other planets in the solar system"], "answer": "B", "explanation": "The Space Race was a competition between the United States and the Soviet Union for leadership in space exploration."},
    {"id": 3, "question": "What was the first significant Soviet space achievement mentioned in the passage?", "options": ["A) Landing an unmanned probe on the Moon", "B) Sending the first human to orbit Earth", "C) Launching the first artificial satellite, Sputnik, in 1957", "D) Developing the first nuclear-powered rocket"], "answer": "C", "explanation": "Sputnik, the first artificial satellite, was launched in 1957."},
    {"id": 4, "question": "What was Michael Collins doing during the Moon landing?", "options": ["A) He landed on the Moon with Armstrong", "B) He remained in orbit above the Moon in the command module", "C) He stayed on Earth and monitored the mission from Houston", "D) He returned to Earth early due to a technical fault"], "answer": "B", "explanation": "While Armstrong and Aldrin descended to the lunar surface, Michael Collins remained in orbit."},
    {"id": 5, "question": "How many astronauts walked on the Moon during the entire Apollo programme?", "options": ["A) Three", "B) Six", "C) Twelve", "D) Fifteen"], "answer": "C", "explanation": "The Apollo programme continued until 1972, with twelve astronauts walking on the Moon in total."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Neil Armstrong was the first human being to orbit the Earth.", "answer": false, "evidence": "Yuri Gagarin became the first human in space in 1961."},
    {"id": 2, "statement": "Soviet space achievements alarmed the American government and public.", "answer": true, "evidence": "These achievements alarmed the United States government and public."},
    {"id": 3, "statement": "President Kennedy promised to land a man on the Moon before the end of the 1970s.", "answer": false, "evidence": "Kennedy committed the country to landing an astronaut on the Moon before the end of the 1960s."},
    {"id": 4, "statement": "All three Apollo 11 astronauts descended to the surface of the Moon.", "answer": false, "evidence": "While Armstrong and Aldrin descended to the lunar surface, Michael Collins remained in orbit."},
    {"id": 5, "statement": "The Apollo programme ended in 1972.", "answer": true, "evidence": "The Apollo programme continued until 1972, with twelve astronauts walking on the Moon in total."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Armstrong and Aldrin descended to the [BLANK] surface while Collins remained in orbit above the Moon.", "options": ["A) orbital", "B) celestial", "C) lunar", "D) planetary"], "answer": "C", "explanation": "Lunar means relating to the Moon, which is the word used in the passage."},
    {"id": 2, "sentence": "The Apollo 11 mission represented the [BLANK] of eight years of intensive scientific and technological development.", "options": ["A) beginning", "B) failure", "C) culmination", "D) result"], "answer": "C", "explanation": "Culmination means the highest or final point — the mission was the completion of years of effort."},
    {"id": 3, "sentence": "Sputnik and Yuri Gagarin were significant early [BLANK] in the Soviet space programme that alarmed the United States.", "options": ["A) accidents", "B) milestones", "C) experiments", "D) satellites"], "answer": "B", "explanation": "Milestones are important achievements marking significant stages in a process."},
    {"id": 4, "sentence": "Armstrong and Aldrin descended to the lunar surface in the landing [BLANK], while Collins orbited above.", "options": ["A) capsule", "B) rocket", "C) module", "D) shuttle"], "answer": "C", "explanation": "Module is the specific word used in the passage to describe the separate unit that landed on the Moon."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "Kennedy set a public deadline for landing on the Moon. Do you think ambitious public goals and deadlines are effective ways to accelerate scientific progress? Give reasons.", "suggested_answer": "Ambitious public commitments can be very effective in focusing resources, talent, and political will. Setting a clear and public deadline creates accountability and prevents the gradual reduction of priorities under other pressures. The Apollo programme demonstrates that seemingly impossible goals can be achieved when sufficient funding, talent, and political support are concentrated on a single objective. However, this approach works best for defined technical problems rather than open-ended research, and the enormous cost must be weighed against other priorities."},
    {"id": 2, "question": "The passage describes the Moon landing as one of the greatest achievements in human history. What makes an achievement great? Do you agree with this assessment?", "suggested_answer": "The Moon landing deserves its reputation as extraordinary. It was the first time humans left Earth and set foot on another world, combining unprecedented technical complexity with enormous risk and political significance. What makes an achievement great is the scale of the obstacles overcome, the collaboration required, the risks accepted, and the inspiration it provides to future generations. Whether or not it had immediate practical benefits, the symbolic value of the Moon landing — demonstrating what humanity can accomplish through collective effort — makes it genuinely remarkable."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 5
) AND type = 'reading';

-- ── Lesson 6 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "A Decade of Change: Cultural Revolutions of the 1960s",
  "text": "The 1960s produced some of the most profound social and cultural changes of the twentieth century. In Western countries, particularly the United States and Britain, a new generation rejected the conservative values and institutions of the previous era and demanded radical change. The decade saw the emergence of powerful social movements that would reshape society for generations. The civil rights movement in the United States challenged racial segregation and demanded full legal equality for African Americans. The anti-Vietnam War movement mobilised millions of young people against military intervention overseas. The feminist movement challenged traditional gender roles and demanded equal rights and opportunities for women. The environmental movement raised public awareness of pollution and ecological damage. Music became a powerful vehicle for social expression. Artists including Bob Dylan, the Beatles, Janis Joplin, and Jimi Hendrix used their songs to challenge authority, celebrate freedom, and express the frustration and idealism of an entire generation. Rock, folk, and soul music carried messages of protest and hope across the world. In visual art, the Pop Art movement led by Andy Warhol questioned the boundary between high culture and mass culture. Beat writers including Jack Kerouac celebrated individual freedom, non-conformity, and the rejection of materialism. The legacy of the 1960s is complex. The movements achieved significant legal and social change: racial segregation was outlawed, voting rights were extended, and environmental legislation was enacted. However, deep inequalities persisted. The decade established a tradition of political activism and social critique that continues to shape public life and culture across the world today.",
  "glossary": [
    {"term": "counterculture", "definition": "a culture with values and lifestyles that oppose those of the mainstream society", "translation": "контркультура"},
    {"term": "activism", "definition": "the use of campaigning, protest, and direct action to bring about political or social change", "translation": "активизм"},
    {"term": "non-conformity", "definition": "the refusal to follow prevailing social norms and expectations", "translation": "нонконформизм"},
    {"term": "ecological", "definition": "relating to the relationship between living organisms and their natural environment", "translation": "экологический"},
    {"term": "materialism", "definition": "the belief that wealth and physical possessions are the most important things in life", "translation": "материализм"},
    {"term": "legislation", "definition": "laws that have been enacted by a government or legislature", "translation": "законодательство"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does the passage describe as the main theme of the 1960s?", "options": ["A) A decade of economic growth and technological progress", "B) A period of cultural and social stability following World War Two", "C) A decade in which young people challenged established values and demanded radical change", "D) A period of political consensus between conservative and progressive forces"], "answer": "C", "explanation": "A new generation rejected conservative values and institutions and demanded radical change, producing profound social and cultural transformations."},
    {"id": 2, "question": "Which of the following movements is NOT mentioned in the passage as part of the 1960s cultural revolution?", "options": ["A) The civil rights movement demanding racial equality", "B) The feminist movement challenging gender roles", "C) The anti-Vietnam War movement opposing military intervention", "D) A movement to restore traditional family values"], "answer": "D", "explanation": "The passage mentions civil rights, anti-war, feminist, and environmental movements — not a traditional values movement."},
    {"id": 3, "question": "What role did music play in the cultural changes of the 1960s?", "options": ["A) Music became purely commercial and avoided political themes", "B) Music served as a vehicle to challenge authority and express the idealism of a generation", "C) Music became less popular as young people turned to visual art and literature", "D) Government censorship limited the influence of protest music"], "answer": "B", "explanation": "Music was a powerful vehicle for social expression, used to challenge authority and express the frustration and idealism of an entire generation."},
    {"id": 4, "question": "What was the Pop Art movement as described in the passage?", "options": ["A) A musical movement combining popular and classical traditions", "B) A political movement using art to campaign for social change", "C) An art movement questioning the boundary between high culture and mass culture", "D) A government programme bringing art education to working-class communities"], "answer": "C", "explanation": "Pop Art, led by Andy Warhol, questioned the boundary between high culture and mass culture."},
    {"id": 5, "question": "What does the passage say about the legacy of the 1960s?", "options": ["A) The influence was short-lived and had little lasting impact", "B) Deep inequalities persisted and the movements achieved nothing significant", "C) Significant legal changes were achieved but deep inequalities persisted", "D) The impact was limited to the United States and had no global influence"], "answer": "C", "explanation": "The movements achieved significant legal and social change, but deep inequalities persisted. The decade established a lasting tradition of political activism."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The 1960s cultural revolution had only artistic impact and no political dimension.", "answer": false, "evidence": "The civil rights, anti-war, feminist, and environmental movements all had significant political dimensions and achieved legal changes."},
    {"id": 2, "statement": "Bob Dylan and the Beatles are mentioned as artists who challenged authority through music.", "answer": true, "evidence": "Artists including Bob Dylan, the Beatles, Janis Joplin, and Jimi Hendrix used their songs to challenge authority and celebrate freedom."},
    {"id": 3, "statement": "Andy Warhol was a Beat writer known for breaking with conventional narrative forms.", "answer": false, "evidence": "Warhol led the Pop Art movement in visual art. Beat writers such as Jack Kerouac were a separate group."},
    {"id": 4, "statement": "All of the social ambitions of the 1960s movements were fully achieved.", "answer": false, "evidence": "Deep inequalities persisted despite the significant legal and social changes achieved."},
    {"id": 5, "statement": "The 1960s established a tradition of political activism that continues to influence societies today.", "answer": true, "evidence": "The decade established a tradition of political activism and social critique that continues to shape public life and culture across the world today."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "A new generation rejected mainstream values and created movements with alternative lifestyles and beliefs, sometimes called a [BLANK].", "options": ["A) civil revolution", "B) counterculture", "C) reform programme", "D) cultural renaissance"], "answer": "B", "explanation": "Counterculture describes a culture with values and lifestyles that oppose those of the mainstream, which describes the 1960s movements."},
    {"id": 2, "sentence": "Artists used their songs to challenge authority, celebrate freedom, and express the frustration and idealism of an entire [BLANK].", "options": ["A) society", "B) movement", "C) generation", "D) community"], "answer": "C", "explanation": "Generation refers to all the people born and living at approximately the same time, sharing similar experiences and attitudes."},
    {"id": 3, "sentence": "Pop Art questioned the [BLANK] between high culture and mass culture, asking what could be considered fine art.", "options": ["A) difference", "B) boundary", "C) connection", "D) competition"], "answer": "B", "explanation": "Boundary is the exact word used in the passage to describe what Pop Art challenged."},
    {"id": 4, "sentence": "The movements achieved significant legal and social change: racial segregation was outlawed and environmental [BLANK] was enacted.", "options": ["A) policy", "B) reform", "C) legislation", "D) protest"], "answer": "C", "explanation": "Legislation means laws enacted by a government, which is what the movements campaigned for and eventually achieved."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage notes that significant legal changes were achieved in the 1960s but deep inequalities persisted. How do you measure the success of a social movement?", "suggested_answer": "Measuring the success of a social movement requires looking at both immediate legal outcomes and long-term cultural change. The civil rights movement achieved specific legal victories, but racial inequality persists decades later. Perhaps success should be measured not as a final achievement but as a shift in what is considered possible and acceptable. A movement that redefines the public conversation and expands what can be demanded — even if full realisation takes generations — has made a meaningful contribution, even if its work remains unfinished."},
    {"id": 2, "question": "The passage describes music as a powerful vehicle for cultural change. Do you agree that art and music can influence politics and society? Give examples.", "suggested_answer": "Art and music can be powerful agents of cultural change because they communicate emotions and ideas in ways that reach audiences that political speeches cannot. Protest songs give voice to collective feelings of injustice in terms that are accessible and emotionally resonant. However, the relationship between art and political change is complex — art can inspire and shift perspectives, but it rarely causes political change on its own. It works alongside political organisation, journalism, and direct action to shift the cultural environment in which political decisions are made."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 6
) AND type = 'reading';

-- ── Lesson 7 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Globalisation: From Local Traditions to a Connected World",
  "text": "Globalisation describes the accelerating process by which economies, societies, and cultures around the world have become interconnected. Although trade and cultural contact between distant regions have existed for millennia, the speed and scale of globalisation increased dramatically during the twentieth century, particularly after the end of the Cold War in 1991. Several developments drove this acceleration. Container shipping dramatically reduced the cost of transporting goods across oceans. Commercial aviation made international travel accessible to millions. The internet and mobile communication created instant global connectivity for individuals and businesses. Multinational corporations expanded across borders, producing goods in lower-wage countries and selling them in higher-income markets. This produced significant economic growth in parts of Asia, Latin America, and Africa, lifting hundreds of millions of people out of extreme poverty. Critics argue, however, that globalisation has also increased inequality. Workers in developed countries have lost jobs as manufacturing moved to cheaper locations. Workers in developing countries often face poor conditions and low wages despite contributing to global supply chains. Cultural globalisation has had similarly mixed effects. The global spread of English, American films, music, and consumer brands has created shared cultural reference points. However, it has also threatened minority languages and local traditions. Hundreds of languages are now endangered, and communities around the world struggle to preserve cultural practices against the pressure of a dominant global culture. Supporters of globalisation argue that the mixing of cultures produces new hybrid forms of music, art, and cuisine that enrich human experience. The debate about how to manage globalisation fairly and sustainably continues to define international political and economic discourse today.",
  "glossary": [
    {"term": "globalisation", "definition": "the process by which economies, cultures, and societies worldwide become increasingly interconnected", "translation": "глобализация"},
    {"term": "multinational corporation", "definition": "a large company that operates in multiple countries simultaneously", "translation": "транснациональная корпорация"},
    {"term": "homogenisation", "definition": "the process of making things uniform or similar everywhere, reducing diversity", "translation": "гомогенизация"},
    {"term": "supply chain", "definition": "the sequence of processes involved in producing and distributing a product from raw material to consumer", "translation": "цепочка поставок"},
    {"term": "inequality", "definition": "the unequal distribution of wealth, opportunities, or resources among people or countries", "translation": "неравенство"},
    {"term": "hybrid", "definition": "something that combines two or more different elements or cultural influences", "translation": "гибрид"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does globalisation refer to according to the passage?", "options": ["A) The spread of democracy to previously authoritarian countries", "B) The increasing interconnection of economies, cultures, and societies worldwide", "C) The migration of people from developing to developed countries", "D) The economic dominance of a small number of powerful nations"], "answer": "B", "explanation": "Globalisation describes the accelerating process by which economies, societies, and cultures around the world have become interconnected."},
    {"id": 2, "question": "What developments drove the acceleration of globalisation according to the passage?", "options": ["A) Military power and diplomatic agreements between governments", "B) Government subsidies for export industries", "C) Container shipping, commercial aviation, and the internet", "D) The introduction of a single global currency"], "answer": "C", "explanation": "Container shipping, commercial aviation, and the internet and mobile communication all drove the acceleration of globalisation."},
    {"id": 3, "question": "What economic benefit of globalisation does the passage mention?", "options": ["A) It eliminated inequality between all countries", "B) It lifted hundreds of millions out of extreme poverty in Asia, Latin America, and Africa", "C) It guaranteed safe working conditions for all factory workers worldwide", "D) It led to equal wages for workers in all countries"], "answer": "B", "explanation": "Globalisation produced significant economic growth, lifting hundreds of millions of people out of extreme poverty."},
    {"id": 4, "question": "What cultural concern does the passage raise about globalisation?", "options": ["A) Cultural exchange is too slow to have any real effect", "B) The spread of American popular culture threatens minority languages and local traditions", "C) Traditional cultures are becoming more isolated from global influences", "D) Digital technology has prevented meaningful cultural exchange"], "answer": "B", "explanation": "The global spread of American culture has threatened minority languages and local traditions — hundreds of languages are now endangered."},
    {"id": 5, "question": "What do supporters of globalisation argue according to the passage?", "options": ["A) That economic growth justifies any social or cultural cost", "B) That wealthier countries benefit most and should protect their advantages", "C) That the mixing of cultures produces new hybrid forms that enrich human experience", "D) That free trade agreements eliminate the need for government regulation"], "answer": "C", "explanation": "Supporters argue that cultural mixing produces new hybrid forms of music, art, and cuisine that enrich human experience."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The passage argues that globalisation is an entirely new phenomenon that began after the Cold War.", "answer": false, "evidence": "Trade and cultural contact between distant regions have existed for millennia, though the speed and scale increased dramatically in the twentieth century."},
    {"id": 2, "statement": "Container shipping made it cheaper to transport goods across oceans.", "answer": true, "evidence": "Container shipping dramatically reduced the cost of transporting goods across oceans."},
    {"id": 3, "statement": "Workers in developing countries always benefit from safe conditions and fair wages through globalisation.", "answer": false, "evidence": "Workers in developing countries often face poor conditions and low wages despite contributing to global supply chains."},
    {"id": 4, "statement": "The passage presents both positive and negative effects of cultural globalisation.", "answer": true, "evidence": "Cultural globalisation has had similarly mixed effects — creating shared reference points while also threatening minority languages and local traditions."},
    {"id": 5, "statement": "The debate over the costs and benefits of globalisation has been fully resolved.", "answer": false, "evidence": "The debate about how to manage globalisation fairly and sustainably continues to define international political and economic discourse today."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Economies, societies, and cultures around the world have become increasingly [BLANK] through the process of globalisation.", "options": ["A) divided", "B) competitive", "C) interconnected", "D) homogenised"], "answer": "C", "explanation": "Interconnected is the word used in the passage to describe how globalisation links the world together."},
    {"id": 2, "sentence": "Critics argue that globalisation has increased [BLANK] both between countries and within individual countries.", "options": ["A) diversity", "B) inequality", "C) instability", "D) trade"], "answer": "B", "explanation": "Inequality is specifically mentioned as a concern raised by critics of globalisation."},
    {"id": 3, "sentence": "Workers in developing countries often face poor conditions and low wages despite contributing to global [BLANK] that supply products to wealthy markets.", "options": ["A) demand", "B) competition", "C) supply chains", "D) corporations"], "answer": "C", "explanation": "Supply chains are the sequences of production and distribution processes — developing country workers often contribute to these chains with little reward."},
    {"id": 4, "sentence": "Supporters argue that cultural mixing produces new [BLANK] forms of music, art, and cuisine that enrich human experience.", "options": ["A) traditional", "B) commercial", "C) hybrid", "D) popular"], "answer": "C", "explanation": "Hybrid means something combining two or more different influences, which is what cultural mixing produces."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage presents both benefits and criticisms of globalisation. On balance, do you think globalisation has been more positive or more negative for the world? Give reasons.", "suggested_answer": "Globalisation has produced enormous economic gains, lifting hundreds of millions out of poverty and creating global supply chains that deliver affordable goods. However, these gains have been unevenly distributed, and the costs — environmental damage, job losses in manufacturing communities, cultural homogenisation — have fallen disproportionately on the most vulnerable. On balance, globalisation may be positive in its potential, but its actual outcomes depend heavily on whether governments and international institutions regulate it fairly and redistribute its benefits."},
    {"id": 2, "question": "The passage discusses concern that the spread of a dominant global culture leads to cultural homogenisation. How important is it to preserve local cultural diversity? What can be done to protect it?", "suggested_answer": "Cultural diversity is genuinely valuable — it represents the accumulated wisdom and creativity of human communities that have evolved in unique historical contexts. When languages die and local traditions disappear, humanity loses irreplaceable knowledge and ways of understanding the world. To protect local cultures, governments can invest in language education, support local artists and media, and promote indigenous cultural content. The goal should be diversity within interconnection — cultural exchange that strengthens rather than replaces local traditions."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 2 AND l.order_index = 7
) AND type = 'reading';