-- ============================================================
-- B1 Intermediate / Module 1 (Real World English)
-- Reading Sections — Lessons 1–7
-- Theme: Academic Study Skills / University Life
-- ============================================================

-- ── Lesson 1: Managing Your Academic Journey ────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Managing Your Academic Journey: Essential Study Skills",
  "text": "University life presents students with exciting opportunities and significant challenges. Unlike secondary school, higher education requires a high degree of self-direction. Students must manage their own time, set personal goals, and take responsibility for their learning without constant guidance from teachers. This shift can feel overwhelming at first, but it also represents a valuable opportunity to develop lifelong skills. Time management is one of the most critical skills for academic success. Effective students use planners, digital calendars, or scheduling apps to map out deadlines, exam dates, and study sessions well in advance. Research shows that students who plan their week at the beginning of each period consistently achieve better results than those who work reactively, responding only to immediate pressures. Equally important is the ability to take effective notes. During lectures, students should not attempt to write every word. Instead, skilled note-takers identify key concepts, record examples, and note connections between ideas. After class, reviewing and reorganising notes within 24 hours significantly improves long-term retention. This technique, known as active recall, forces the brain to retrieve information, strengthening memory pathways. Another essential element of academic success is seeking help proactively. Many students wait until they are struggling before approaching tutors or academic support services. However, universities offer a wide range of resources including writing centres, library workshops, and peer study groups. Students who engage with these resources early in their studies report greater confidence and higher grades. Finally, maintaining a healthy work-life balance is crucial. Regular breaks, physical exercise, and adequate sleep all contribute to cognitive performance. Academic success is not achieved through endless hours of study, but through consistent, focused effort combined with proper self-care.",
  "glossary": [
    {"term": "self-direction", "definition": "the ability to manage your own learning without external control", "translation": "самостоятельность"},
    {"term": "time management", "definition": "the process of organising and planning how to divide time between activities", "translation": "управление временем"},
    {"term": "active recall", "definition": "a study technique where you actively retrieve information from memory", "translation": "активное воспроизведение"},
    {"term": "retention", "definition": "the ability to remember information over a long period", "translation": "запоминание, удержание"},
    {"term": "proactively", "definition": "acting in anticipation of future problems rather than reacting to them", "translation": "проактивно"},
    {"term": "cognitive performance", "definition": "the mental ability to think, learn, and process information effectively", "translation": "когнитивные способности"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does the passage say is required in higher education that differs from secondary school?", "options": ["A) Constant guidance from teachers", "B) A high degree of self-direction", "C) More group work with classmates", "D) Less focus on personal goals"], "answer": "B", "explanation": "The passage states that higher education requires a high degree of self-direction, unlike secondary school."},
    {"id": 2, "question": "According to the passage, when is the best time to plan your academic week?", "options": ["A) The night before each day", "B) At the end of each week", "C) At the beginning of each period", "D) Only when deadlines approach"], "answer": "C", "explanation": "Students who plan their week at the beginning of each period consistently achieve better results."},
    {"id": 3, "question": "What does the passage recommend when taking notes during lectures?", "options": ["A) Write down every word the lecturer says", "B) Record only key concepts and connections between ideas", "C) Use audio recordings instead of writing", "D) Copy notes from other students later"], "answer": "B", "explanation": "Skilled note-takers identify key concepts, record examples, and note connections between ideas."},
    {"id": 4, "question": "What is active recall as described in the passage?", "options": ["A) Reading notes repeatedly before exams", "B) Recording lectures for later review", "C) Retrieving information from memory to strengthen it", "D) Summarising each chapter in your own words"], "answer": "C", "explanation": "Active recall forces the brain to retrieve information, strengthening memory pathways."},
    {"id": 5, "question": "What do students who engage with university resources early in their studies report?", "options": ["A) More stress due to extra commitments", "B) Greater confidence and higher grades", "C) Less time for social activities", "D) Difficulty balancing work and study"], "answer": "B", "explanation": "Students who engage with these resources early in their studies report greater confidence and higher grades."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Secondary school and university students are expected to manage their time in the same way.", "answer": false, "evidence": "Unlike secondary school, higher education requires a high degree of self-direction."},
    {"id": 2, "statement": "Planning your week in advance leads to better academic results.", "answer": true, "evidence": "Students who plan their week at the beginning of each period consistently achieve better results."},
    {"id": 3, "statement": "Good note-taking means writing down every word during a lecture.", "answer": false, "evidence": "Students should not attempt to write every word; skilled note-takers identify key concepts and connections."},
    {"id": 4, "statement": "Reviewing notes within 24 hours helps improve long-term memory.", "answer": true, "evidence": "Reviewing and reorganising notes within 24 hours significantly improves long-term retention."},
    {"id": 5, "statement": "Students should only use university support services when they are seriously struggling.", "answer": false, "evidence": "Students who engage with these resources early in their studies report greater confidence and higher grades."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "This shift can feel overwhelming at first, but it also represents a valuable [BLANK] to develop lifelong skills.", "options": ["A) problem", "B) opportunity", "C) requirement", "D) disappointment"], "answer": "B", "explanation": "Opportunity fits because the passage frames the challenge positively as a chance to grow."},
    {"id": 2, "sentence": "Effective students map out deadlines and study sessions well in [BLANK].", "options": ["A) advance", "B) time", "C) order", "D) progress"], "answer": "A", "explanation": "In advance is the correct collocation meaning before the events occur."},
    {"id": 3, "sentence": "Reviewing notes within 24 hours significantly improves long-term [BLANK].", "options": ["A) management", "B) recall", "C) retention", "D) revision"], "answer": "C", "explanation": "Retention specifically means the ability to keep information in memory over time."},
    {"id": 4, "sentence": "Students who engage with university resources [BLANK] in their studies report greater confidence.", "options": ["A) late", "B) eagerly", "C) early", "D) slowly"], "answer": "C", "explanation": "The passage specifically recommends early engagement with university resources for the best results."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that academic success depends more on consistent effort than on long hours of study. Do you agree? Give reasons and examples.", "suggested_answer": "This is largely true. Students who study for shorter, focused periods using techniques like active recall often retain more than those who spend many hours passively reading. A student who revises for 30 focused minutes daily is likely to outperform one who studies for 5 hours the night before an exam. Quality, structure, and recovery time all play important roles alongside effort."},
    {"id": 2, "question": "Which of the study strategies mentioned in the passage do you find most useful? Why might different strategies work better for different students?", "suggested_answer": "Different students have different learning styles, schedules, and academic demands. Time management tools may benefit students with many responsibilities, while active recall might suit those who struggle with exam anxiety. Cultural backgrounds and previous educational experiences also influence which strategies feel natural. The most effective approach is likely a personalised combination of several techniques."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 1
)
AND type = 'reading';

-- ── Lesson 2: Research Culture in Contemporary Higher Education ──
UPDATE english_lesson_sections
SET content = $json${
  "title": "Research Culture in Contemporary Higher Education",
  "text": "Research is at the heart of modern university life. Across disciplines from medicine and engineering to history and sociology, academics constantly investigate questions, test theories, and generate new knowledge. For students entering higher education today, understanding research culture is essential not only for academic study but also for professional development in a knowledge-based economy. One significant trend in contemporary research is the shift towards collaboration. Rather than working in isolation, researchers increasingly form interdisciplinary teams that bring together specialists from different fields. A medical study might involve biologists, statisticians, psychologists, and ethicists working together. This collaborative model produces richer findings and reduces the risk of narrow, field-specific blind spots. Technology has dramatically transformed how research is conducted and shared. Open access publishing has made millions of academic articles freely available to anyone with an internet connection, breaking down traditional barriers between elite institutions and smaller universities. Meanwhile, large datasets and computational tools allow researchers to analyse information at a scale that was impossible even twenty years ago. However, the research environment also has pressures and challenges. The principle of publish or perish means that academics face constant pressure to produce and publish new research in order to maintain their careers and attract funding. Critics argue that this pressure sometimes leads to rushed studies, questionable methodology, or even fabricated results. For undergraduate students, engagement with research culture begins in the library and seminar room. Learning to read academic articles critically, understanding how arguments are constructed, evaluating evidence, and recognising bias are all foundational skills. Students who develop a genuinely curious, questioning approach to knowledge not only become better researchers but also more thoughtful and effective citizens in a complex world.",
  "glossary": [
    {"term": "interdisciplinary", "definition": "involving two or more academic subjects or fields of study", "translation": "межпредметный"},
    {"term": "open access", "definition": "a publishing model where research is freely available online to all readers", "translation": "открытый доступ"},
    {"term": "publish or perish", "definition": "the pressure on academics to regularly publish research to maintain their careers", "translation": "принцип публикуй или исчезни"},
    {"term": "methodology", "definition": "the system of methods and principles used in a particular field of study", "translation": "методология"},
    {"term": "fabricated", "definition": "invented or falsified, not based on real data", "translation": "сфабрикованный"},
    {"term": "foundational", "definition": "forming the most important and basic part of something", "translation": "основополагающий"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does the passage say research culture is important for?", "options": ["A) Only for students planning to become professors", "B) Academic study and professional development", "C) Improving university rankings internationally", "D) Getting higher marks on essays"], "answer": "B", "explanation": "The passage states that understanding research culture is essential not only for academic study but also for professional development."},
    {"id": 2, "question": "According to the passage, why do researchers form interdisciplinary teams?", "options": ["A) Because universities require it for funding", "B) To produce richer findings and avoid narrow perspectives", "C) To reduce the overall cost of research projects", "D) Because single researchers cannot receive grants"], "answer": "B", "explanation": "This collaborative model produces richer findings and reduces the risk of narrow, field-specific blind spots."},
    {"id": 3, "question": "What has open access publishing achieved according to the passage?", "options": ["A) Made research more expensive to produce", "B) Reduced the number of academic journals available", "C) Made academic articles freely available to anyone online", "D) Limited access to research from smaller universities"], "answer": "C", "explanation": "Open access publishing has made millions of academic articles freely available to anyone with an internet connection."},
    {"id": 4, "question": "What does the publish or perish principle refer to in the passage?", "options": ["A) The requirement to publish only original research findings", "B) The pressure on academics to produce research for their careers", "C) A policy of removing academics who do not publish enough", "D) The competition between universities for research funding"], "answer": "B", "explanation": "Academics face constant pressure to produce and publish new research in order to maintain their careers and attract funding."},
    {"id": 5, "question": "According to the passage, how does undergraduate engagement with research culture begin?", "options": ["A) By conducting original experiments in laboratories", "B) Through critical reading and evaluating evidence in texts", "C) By publishing essays in academic journals", "D) Through attendance at international research conferences"], "answer": "B", "explanation": "Learning to read academic articles critically, evaluating evidence, and recognising bias are all foundational skills."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "All researchers in modern universities work independently on their own projects.", "answer": false, "evidence": "Researchers increasingly form interdisciplinary teams that bring together specialists from different fields."},
    {"id": 2, "statement": "Open access publishing has helped remove some barriers between different types of universities.", "answer": true, "evidence": "Open access publishing has made articles freely available, breaking down traditional barriers between elite institutions and smaller universities."},
    {"id": 3, "statement": "The publish or perish principle has no negative consequences according to the passage.", "answer": false, "evidence": "Critics argue that this pressure sometimes leads to rushed studies, questionable methodology, or even fabricated results."},
    {"id": 4, "statement": "Technology has had little impact on modern research methods.", "answer": false, "evidence": "Technology has dramatically transformed how research is conducted and shared."},
    {"id": 5, "statement": "Developing a questioning approach to knowledge benefits students beyond their academic studies.", "answer": true, "evidence": "Students who develop a genuinely curious, questioning approach become not only better researchers but also more thoughtful and effective citizens."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Researchers increasingly form [BLANK] teams that bring together specialists from different fields.", "options": ["A) competitive", "B) international", "C) interdisciplinary", "D) professional"], "answer": "C", "explanation": "Interdisciplinary describes teams that combine experts from different academic disciplines."},
    {"id": 2, "sentence": "Open access publishing has made articles freely available, breaking down traditional [BLANK] between institutions.", "options": ["A) barriers", "B) borders", "C) differences", "D) distinctions"], "answer": "A", "explanation": "Barriers collocates with breaking down and refers to restrictions on access."},
    {"id": 3, "sentence": "The principle of [BLANK] means that academics face constant pressure to produce and publish new research.", "options": ["A) peer review", "B) open access", "C) publish or perish", "D) academic freedom"], "answer": "C", "explanation": "Publish or perish is the specific term defined in the passage."},
    {"id": 4, "sentence": "Students who develop a genuinely curious, [BLANK] approach to knowledge become better researchers and more effective citizens.", "options": ["A) passive", "B) competitive", "C) questioning", "D) creative"], "answer": "C", "explanation": "The passage specifically uses the phrase curious, questioning approach."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage mentions that publish or perish pressure can lead to fabricated results. What measures could universities or journals take to prevent research misconduct?", "suggested_answer": "Journals could strengthen peer review processes and require data sharing, making fabrication easier to detect. Universities could evaluate academics on teaching quality and research impact rather than just publication quantity. Funding bodies could offer longer-term grants that reduce pressure to publish frequently. Ultimately, a cultural shift that values quality over quantity would be most effective."},
    {"id": 2, "question": "Do you think open access publishing is entirely positive? What might be some disadvantages of making all research freely available?", "suggested_answer": "While open access democratises knowledge, it also presents challenges. Some open access journals charge publication fees, creating barriers for researchers from lower-income countries. Without subscription income, journals may struggle to fund rigorous peer review. Additionally, freely available research may be misread by non-specialists and used to spread misinformation. A balance between accessibility and quality assurance is therefore needed."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 2
)
AND type = 'reading';

-- ── Lesson 3: Academic Integrity ────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Academic Integrity: The Foundation of Scholarly Practice",
  "text": "Academic integrity refers to the ethical framework that governs how students and researchers conduct their work. It encompasses honesty, fairness, trust, respect, and responsibility in all academic activities. Violations of academic integrity are taken extremely seriously by universities worldwide, and understanding what constitutes acceptable and unacceptable practice is essential for every student. The most well-known form of academic dishonesty is plagiarism. Plagiarism occurs when a student presents the work of another person as their own, whether through copying text directly, paraphrasing without acknowledgement, or submitting work completed by someone else. With the rise of internet content and essay-writing services, detection has become increasingly sophisticated. Most universities now use software such as Turnitin to compare submitted work against millions of online sources and previously submitted papers. However, plagiarism is not always intentional. Students from educational backgrounds where memorising and reproducing authoritative texts is considered a sign of respect may find the Western academic emphasis on original argumentation unfamiliar. This is why universities invest significantly in academic writing support, teaching students how to correctly paraphrase, summarise, and cite sources. A second major category is collusion, which occurs when two or more students work together on an individual assignment without permission. Collusion differs from legitimate collaboration in that it violates the assessment conditions and misrepresents the individual capability of each student. Students should always check assignment guidelines carefully to understand what forms of cooperation are permitted. Self-plagiarism is another increasingly recognised issue, where a student submits the same piece of work for more than one assessment. Even though the student produced the original work, resubmitting it without permission undermines the assessment process and may result in serious academic penalties.",
  "glossary": [
    {"term": "plagiarism", "definition": "presenting the work or ideas of another person as your own without acknowledgement", "translation": "плагиат"},
    {"term": "paraphrasing", "definition": "expressing the ideas of another person using different words", "translation": "перефразирование"},
    {"term": "collusion", "definition": "working together on an individual assignment without permission from the instructor", "translation": "сговор (в академической среде)"},
    {"term": "self-plagiarism", "definition": "submitting previously submitted work for a new assessment without permission", "translation": "самоплагиат"},
    {"term": "acknowledge", "definition": "to give credit to the original source of information or ideas", "translation": "признавать, ссылаться"},
    {"term": "assessment", "definition": "a test, essay, or project used to evaluate what a student has learned", "translation": "оценивание"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "According to the passage, what does academic integrity refer to?", "options": ["A) The process of grading student work fairly", "B) The ethical framework governing academic conduct", "C) A set of rules for formatting academic papers", "D) The policy for dealing with cheating in exams"], "answer": "B", "explanation": "Academic integrity refers to the ethical framework that governs how students and researchers conduct their work."},
    {"id": 2, "question": "Which of the following is described as plagiarism in the passage?", "options": ["A) Collaborating with a classmate on a group essay", "B) Using software to check grammar in your writing", "C) Paraphrasing a source without acknowledging it", "D) Quoting a source and giving the author credit"], "answer": "C", "explanation": "Plagiarism includes paraphrasing without acknowledgement."},
    {"id": 3, "question": "Why might plagiarism sometimes be unintentional according to the passage?", "options": ["A) Students are too busy to cite their sources properly", "B) University plagiarism rules are too complicated to follow", "C) Some educational backgrounds emphasise reproducing texts over original argumentation", "D) Detection software is not always accurate in its results"], "answer": "C", "explanation": "Students from backgrounds where memorising authoritative texts is valued may find the Western emphasis on original argumentation unfamiliar."},
    {"id": 4, "question": "How does collusion differ from legitimate collaboration according to the passage?", "options": ["A) Collusion involves copying from external sources", "B) Collusion only occurs in group assignments", "C) Collusion misrepresents individual capability and violates assessment conditions", "D) Collusion is permitted if students inform their tutor beforehand"], "answer": "C", "explanation": "Collusion violates the assessment conditions and misrepresents the individual capability of each student."},
    {"id": 5, "question": "What is self-plagiarism as defined in the passage?", "options": ["A) Using your own ideas without citing yourself as a source", "B) Submitting the same work for more than one assessment without permission", "C) Repeating your arguments within a single essay", "D) Writing a paper without conducting original research"], "answer": "B", "explanation": "Self-plagiarism is submitting the same piece of work for more than one assessment without permission."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Plagiarism only occurs when a student copies text directly from a source.", "answer": false, "evidence": "Plagiarism occurs through copying text directly, paraphrasing without acknowledgement, or submitting work completed by someone else."},
    {"id": 2, "statement": "Most universities now use software to detect plagiarism.", "answer": true, "evidence": "Most universities now use software such as Turnitin to compare submitted work against millions of online sources."},
    {"id": 3, "statement": "Universities provide no support to help students avoid unintentional plagiarism.", "answer": false, "evidence": "Universities invest significantly in academic writing support, teaching students how to correctly paraphrase, summarise, and cite sources."},
    {"id": 4, "statement": "Collusion always results in immediate expulsion from university.", "answer": false, "evidence": "The passage says collusion may result in serious academic penalties, but does not specify expulsion."},
    {"id": 5, "statement": "Self-plagiarism can occur even when a student produced the original work themselves.", "answer": true, "evidence": "Even though the student produced the original work, resubmitting it without permission undermines the assessment process."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Plagiarism occurs when a student presents the work of another as their own, whether through copying text, [BLANK] without acknowledgement, or submitting work by someone else.", "options": ["A) paraphrasing", "B) summarising", "C) referencing", "D) analysing"], "answer": "A", "explanation": "Paraphrasing without acknowledgement is specifically named as a form of plagiarism in the passage."},
    {"id": 2, "sentence": "Most universities now use software to [BLANK] submitted work against millions of online sources.", "options": ["A) publish", "B) compare", "C) analyse", "D) improve"], "answer": "B", "explanation": "Compare submitted work against sources is the exact phrase used in the passage."},
    {"id": 3, "sentence": "Collusion [BLANK] from legitimate collaboration in that it violates assessment conditions.", "options": ["A) emerges", "B) differs", "C) results", "D) derives"], "answer": "B", "explanation": "Collusion differs from legitimate collaboration is the exact phrase used in the passage."},
    {"id": 4, "sentence": "Even though the student produced the original work, resubmitting it without permission [BLANK] the assessment process.", "options": ["A) supports", "B) improves", "C) undermines", "D) replaces"], "answer": "C", "explanation": "Undermines is the verb used in the passage to describe the effect of self-plagiarism."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage mentions that plagiarism is sometimes unintentional. What responsibility do universities have in preventing it, and what responsibility do students have?", "suggested_answer": "Universities have a responsibility to clearly communicate their academic integrity policies, provide writing support, and teach citation skills from the beginning of a course. Students have a responsibility to familiarise themselves with these policies and seek help when uncertain. A shared approach is most effective: universities should not assume students arrive with knowledge of Western academic conventions, while students should not wait until an accusation arises before seeking guidance."},
    {"id": 2, "question": "Some people argue that essay-writing services are a form of academic dishonesty, while others say they are just a form of tutoring. What is your view?", "suggested_answer": "Essay-writing services that produce work for students to submit as their own clearly violate academic integrity, as they allow students to claim credit for work they did not produce. This misrepresents their abilities and devalues the qualifications of honest students. Legitimate tutoring, by contrast, helps students understand material and improve their own work. The key distinction is whether the student ultimately demonstrates their own learning or delegates it entirely to someone else."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 3
)
AND type = 'reading';

-- ── Lesson 4: Digital Libraries and Information Literacy ────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Digital Libraries and Information Literacy",
  "text": "The ability to locate, evaluate, and use information effectively is known as information literacy, and it has become one of the most valuable skills in the digital age. University students have access to an unprecedented volume of academic material through digital libraries, online databases, and open access repositories. However, the sheer quantity of available information can be as challenging as the lack of it. University libraries provide access to specialist databases such as JSTOR, Web of Science, and Scopus, which index millions of peer-reviewed journal articles across every academic discipline. Unlike general internet searches, these databases allow users to filter results by date, publication type, author, and subject area. Understanding how to construct effective database searches using Boolean operators — the logical connectors AND, OR, and NOT — allows students to retrieve precisely relevant results rather than thousands of loosely related articles. Evaluating source credibility is equally important. Not every published text is reliable, and students must develop the habit of asking critical questions about any source they encounter. Who wrote it? What are their qualifications? Where was it published and was it peer-reviewed? When was it written and is the information still current? Does the author have any financial or ideological interests that might bias their conclusions? Citation management tools such as Zotero and Mendeley help students organise their research and automatically generate bibliographies in multiple citation styles including APA, MLA, and Harvard. Using these tools saves time and reduces the risk of formatting errors in reference lists. Ultimately, information literacy is not a passive skill learned once and forgotten. It requires continuous updating as new databases emerge, citation standards evolve, and the boundaries between reliable and unreliable information become increasingly difficult to navigate.",
  "glossary": [
    {"term": "information literacy", "definition": "the ability to find, evaluate, and use information effectively and responsibly", "translation": "информационная грамотность"},
    {"term": "peer-reviewed", "definition": "evaluated by other experts in the same field before being published", "translation": "рецензируемый"},
    {"term": "Boolean operators", "definition": "logical terms (AND, OR, NOT) used to combine or exclude search terms in databases", "translation": "булевы операторы"},
    {"term": "credibility", "definition": "the quality of being trusted and believed to be accurate and reliable", "translation": "достоверность"},
    {"term": "citation management", "definition": "the practice of organising and formatting references using specialist software", "translation": "управление цитированием"},
    {"term": "repository", "definition": "a central online location where academic works are stored and made accessible", "translation": "репозиторий"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is information literacy as described in the passage?", "options": ["A) The ability to use computers and digital devices", "B) The skill of locating, evaluating, and using information effectively", "C) Knowledge of different academic citation styles", "D) The ability to read academic texts at high speed"], "answer": "B", "explanation": "The ability to locate, evaluate, and use information effectively is the definition given in the passage."},
    {"id": 2, "question": "According to the passage, what is an advantage of specialist databases over general internet searches?", "options": ["A) They are free to use for all members of the public", "B) They contain more recently published information", "C) They allow filtering by date, publication type, and subject area", "D) They are easier to understand for students with no prior training"], "answer": "C", "explanation": "Specialist databases allow users to filter results by date, publication type, author, and subject area."},
    {"id": 3, "question": "What are Boolean operators used for in database searches?", "options": ["A) To translate academic articles into different languages", "B) To access databases that require a university password", "C) To connect or exclude search terms for more precise results", "D) To automatically generate citations for sources found"], "answer": "C", "explanation": "Boolean operators allow students to retrieve precisely relevant results rather than thousands of loosely related articles."},
    {"id": 4, "question": "Which of the following questions is NOT mentioned in the passage as part of evaluating a source?", "options": ["A) Is the source peer-reviewed?", "B) Does the author have any potential biases?", "C) How many times has the source been cited by others?", "D) When was the information written?"], "answer": "C", "explanation": "The passage asks about authorship, qualifications, publication venue, currency, and bias — but not citation counts."},
    {"id": 5, "question": "What do citation management tools such as Zotero help students do?", "options": ["A) Find academic articles more quickly through smart searching", "B) Organise research and generate bibliographies automatically", "C) Check their writing for plagiarism before submission", "D) Submit assignments through university online portals"], "answer": "B", "explanation": "Citation management tools help students organise their research and automatically generate bibliographies in multiple citation styles."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Having access to a large quantity of information always makes research easier.", "answer": false, "evidence": "The sheer quantity of available information can be as challenging as the lack of it."},
    {"id": 2, "statement": "Specialist databases only cover one academic discipline each.", "answer": false, "evidence": "These databases index millions of peer-reviewed journal articles across every academic discipline."},
    {"id": 3, "statement": "Using Boolean operators helps students find more relevant search results.", "answer": true, "evidence": "Boolean operators allow students to retrieve precisely relevant results rather than thousands of loosely related articles."},
    {"id": 4, "statement": "All published academic texts can be trusted as reliable sources.", "answer": false, "evidence": "Not every published text is reliable, and students must develop the habit of asking critical questions."},
    {"id": 5, "statement": "Information literacy is a skill that requires continuous updating over time.", "answer": true, "evidence": "It requires continuous updating as new databases emerge, citation standards evolve, and the boundaries between reliable and unreliable information shift."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "University libraries provide access to databases which index millions of [BLANK] journal articles.", "options": ["A) popular", "B) peer-reviewed", "C) digital", "D) international"], "answer": "B", "explanation": "Peer-reviewed journal articles is the exact phrase used in the passage."},
    {"id": 2, "sentence": "Understanding how to use Boolean [BLANK] allows students to retrieve precisely relevant results.", "options": ["A) filters", "B) databases", "C) operators", "D) methods"], "answer": "C", "explanation": "Boolean operators is the technical term defined and used in the passage."},
    {"id": 3, "sentence": "Students must develop the habit of asking critical questions about any source they [BLANK].", "options": ["A) write", "B) encounter", "C) publish", "D) understand"], "answer": "B", "explanation": "Any source they encounter is the exact phrase from the passage."},
    {"id": 4, "sentence": "Citation management tools help students organise their research and automatically generate [BLANK] in multiple citation styles.", "options": ["A) assignments", "B) summaries", "C) outlines", "D) bibliographies"], "answer": "D", "explanation": "Automatically generate bibliographies in multiple citation styles is stated directly in the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage warns that the boundaries between reliable and unreliable information are increasingly difficult to navigate. What factors make this particularly challenging in the digital age?", "suggested_answer": "The internet allows anyone to publish content without editorial oversight, making it difficult to distinguish expert knowledge from opinion or misinformation. Social media algorithms prioritise engaging content over accurate content, and the volume of available information makes thorough verification time-consuming. Additionally, some unreliable sources deliberately mimic the appearance of legitimate academic publications. Critical thinking and systematic evaluation are therefore more important than ever."},
    {"id": 2, "question": "Do you think schools adequately prepare students for information literacy before university? What could be improved?", "suggested_answer": "Many schools focus on basic research skills such as finding sources online but do not teach students how to critically evaluate them or use specialist databases. Students may arrive at university unfamiliar with concepts like peer review, Boolean searching, or citation management. Schools could improve preparation by incorporating information literacy across multiple subjects, not just library classes, and by giving students regular practice evaluating the credibility of real sources they encounter in daily life."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 4
)
AND type = 'reading';

-- ── Lesson 5: Student Well-being and Academic Performance ───
UPDATE english_lesson_sections
SET content = $json${
  "title": "Student Well-being and Academic Performance",
  "text": "The relationship between student well-being and academic performance has received increasing attention in higher education research over the past two decades. Historically, universities focused almost exclusively on intellectual development, treating mental and emotional health as private matters outside institutional responsibility. Today, however, there is strong evidence that psychological well-being is directly connected to learning, motivation, and academic outcomes. Mental health challenges among university students are widespread. Studies across many countries consistently report that significant proportions of students experience anxiety, depression, or burnout during their studies. Transition to university life, financial pressures, academic demands, and social isolation all contribute to these difficulties. First-year students are particularly vulnerable, as they simultaneously face unfamiliar academic expectations and the challenge of building new social networks away from home. Universities have responded by expanding mental health services, counselling facilities, and well-being programmes. Many institutions now offer online mental health resources, peer support networks, and dedicated well-being advisers. However, demand often exceeds available provision, and there is ongoing debate about whether universities are doing enough. Resilience — the capacity to recover from setbacks and adapt to challenging circumstances — is increasingly recognised as a protective factor for student well-being. Research suggests that students who approach difficulties with a growth mindset, viewing challenges as opportunities for development rather than threats, tend to recover more effectively from academic setbacks. Rather than waiting for a crisis to develop, the most effective approach is proactive. Students are encouraged to establish healthy routines, build supportive social connections, and recognise early warning signs of stress before they escalate. Self-awareness and a willingness to seek help are not signs of weakness but indicators of emotional intelligence and effective self-management.",
  "glossary": [
    {"term": "well-being", "definition": "a state of being comfortable, healthy, and experiencing positive mental and physical health", "translation": "благополучие"},
    {"term": "burnout", "definition": "a state of extreme mental and physical exhaustion caused by prolonged stress", "translation": "эмоциональное выгорание"},
    {"term": "resilience", "definition": "the ability to recover quickly from difficulties and adapt to challenging circumstances", "translation": "устойчивость, резилиентность"},
    {"term": "growth mindset", "definition": "the belief that abilities and intelligence can be developed through effort and learning", "translation": "установка на рост"},
    {"term": "proactive", "definition": "taking action in advance to deal with expected challenges rather than reacting to them later", "translation": "проактивный"},
    {"term": "counselling", "definition": "professional guidance provided to help someone manage personal or psychological difficulties", "translation": "психологическое консультирование"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "How has the view of universities towards student mental health changed according to the passage?", "options": ["A) Universities now focus less on academic performance overall", "B) Universities have moved from ignoring mental health to recognising its importance", "C) Universities have shifted their focus entirely to student well-being", "D) Universities have reduced academic programme funding to support well-being"], "answer": "B", "explanation": "Historically universities ignored mental health, but today there is strong evidence that well-being is connected to academic outcomes."},
    {"id": 2, "question": "Which group of students is described as particularly vulnerable to mental health challenges?", "options": ["A) Final-year students preparing for exams", "B) International students studying abroad", "C) First-year students adjusting to university life", "D) Students who are working part-time alongside their studies"], "answer": "C", "explanation": "First-year students are particularly vulnerable as they simultaneously face unfamiliar academic expectations and new social challenges."},
    {"id": 3, "question": "What is resilience as described in the passage?", "options": ["A) The ability to study for long periods without rest", "B) The capacity to recover from setbacks and adapt to challenges", "C) A mental health programme offered by universities", "D) The willingness to ask for help from academic tutors"], "answer": "B", "explanation": "Resilience is defined as the capacity to recover from setbacks and adapt to challenging circumstances."},
    {"id": 4, "question": "According to the passage, what does a growth mindset involve?", "options": ["A) Studying harder after receiving a poor grade", "B) Viewing challenges as opportunities for development", "C) Avoiding situations that might lead to academic failure", "D) Comparing your academic progress with other students"], "answer": "B", "explanation": "A growth mindset involves viewing challenges as opportunities for development rather than threats."},
    {"id": 5, "question": "What does the passage say about seeking help for mental health difficulties?", "options": ["A) It should only be done in cases of serious crisis", "B) It is a sign of weakness that students should try to overcome", "C) It is a sign of emotional intelligence and effective self-management", "D) It is less effective than managing stress completely independently"], "answer": "C", "explanation": "A willingness to seek help is described as an indicator of emotional intelligence and effective self-management."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Mental health challenges among university students are rare and limited to a small minority.", "answer": false, "evidence": "Significant proportions of students experience anxiety, depression, or burnout during their studies."},
    {"id": 2, "statement": "First-year students face both academic and social challenges at the same time.", "answer": true, "evidence": "They simultaneously face unfamiliar academic expectations and the challenge of building new social networks away from home."},
    {"id": 3, "statement": "All universities provide sufficient mental health support to meet student demand.", "answer": false, "evidence": "Demand often exceeds available provision, and there is ongoing debate about whether universities are doing enough."},
    {"id": 4, "statement": "Students with a growth mindset tend to recover more effectively from academic setbacks.", "answer": true, "evidence": "Students who approach difficulties with a growth mindset tend to recover more effectively from academic setbacks."},
    {"id": 5, "statement": "The passage recommends waiting until a mental health crisis occurs before taking any action.", "answer": false, "evidence": "Rather than waiting for a crisis to develop, the most effective approach is proactive."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Studies consistently report that significant proportions of students experience anxiety, depression, or [BLANK] during their studies.", "options": ["A) excitement", "B) success", "C) burnout", "D) confusion"], "answer": "C", "explanation": "Burnout is listed alongside anxiety and depression as a serious mental health challenge in the passage."},
    {"id": 2, "sentence": "The capacity to recover from setbacks and adapt to challenging circumstances is called [BLANK].", "options": ["A) resilience", "B) motivation", "C) independence", "D) confidence"], "answer": "A", "explanation": "Resilience is specifically defined in the passage as the capacity to recover from setbacks and adapt to challenges."},
    {"id": 3, "sentence": "Students who approach difficulties with a growth mindset view challenges as [BLANK] for development.", "options": ["A) requirements", "B) threats", "C) opportunities", "D) obstacles"], "answer": "C", "explanation": "The passage contrasts viewing challenges as opportunities for development rather than threats."},
    {"id": 4, "sentence": "Self-awareness and a willingness to seek help are indicators of emotional [BLANK] and effective self-management.", "options": ["A) stability", "B) intelligence", "C) strength", "D) awareness"], "answer": "B", "explanation": "Emotional intelligence is the exact phrase used in the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that resilience and a growth mindset protect students from mental health difficulties. Are these personal qualities, or can they be taught? Give reasons.", "suggested_answer": "Resilience and growth mindset are not simply fixed personality traits — they can be developed through practice, supportive environments, and deliberate learning. Research in educational psychology suggests that when students learn about neuroplasticity and the value of challenge, their attitudes toward failure change. Schools and universities can cultivate these qualities through feedback practices that praise effort rather than ability, and by normalising struggle as part of the learning process."},
    {"id": 2, "question": "Some people believe that universities are becoming too focused on student well-being at the expense of academic standards. Do you agree or disagree?", "suggested_answer": "The evidence suggests that well-being and academic standards are not in opposition — they are interconnected. Students who are mentally healthy are better able to engage with difficult material and produce high-quality work. Rather than lowering standards, well-being support helps more students reach their academic potential. However, there is a valid concern that some forms of well-being provision may create dependency rather than building the self-regulation skills students need for long-term success."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 5
)
AND type = 'reading';

-- ── Lesson 6: The Art of Critical Thinking ──────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Art of Critical Thinking in Academic Contexts",
  "text": "Critical thinking is widely regarded as one of the most important skills a university student can develop, yet it is also one of the most frequently misunderstood. Many students assume that critical thinking means finding fault or being negative about ideas. In academic contexts, however, critical thinking has a more precise meaning: it is the disciplined process of actively and skilfully conceptualising, applying, analysing, synthesising, and evaluating information gathered from observation, experience, reasoning, and communication. At its core, critical thinking involves interrogating assumptions. Every argument, whether in a textbook, a research article, or a news report, rests on certain assumptions about how the world works. A critical thinker asks what these assumptions are, whether they are justified, and whether the conclusions follow logically from the evidence provided. This is quite different from simply accepting information because it comes from an authoritative source. Developing strong argumentation skills is a key component of academic critical thinking. An academic argument is not the same as a quarrel. Rather, it is a structured set of claims supported by evidence and reasoning. Effective academic writers present a clear thesis, support it with relevant evidence, address counterarguments, and draw conclusions that are proportionate to the evidence available. They do not overstate their findings or claim certainty where only probability exists. One important distinction in the literature on critical thinking concerns the difference between domain-specific and transferable skills. Some critical thinking skills — such as evaluating statistical evidence or interpreting legal texts — require specialist knowledge. Others, such as identifying logical fallacies, detecting bias, and constructing well-reasoned arguments, are more broadly transferable. Universities aim to develop both types, equipping students to think rigorously in their own field and beyond.",
  "glossary": [
    {"term": "critical thinking", "definition": "the disciplined process of analysing, synthesising, and evaluating information to form a reasoned judgement", "translation": "критическое мышление"},
    {"term": "assumption", "definition": "something accepted as true without proof or examination", "translation": "допущение, предположение"},
    {"term": "argumentation", "definition": "the process of constructing and presenting a structured, evidence-based argument", "translation": "аргументация"},
    {"term": "thesis", "definition": "the main claim or central argument of a piece of academic writing", "translation": "тезис"},
    {"term": "logical fallacy", "definition": "an error in reasoning that makes an argument logically invalid", "translation": "логическая ошибка"},
    {"term": "transferable", "definition": "able to be applied usefully in different contexts or subject areas", "translation": "применимый в разных контекстах"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "How does the passage define critical thinking in academic contexts?", "options": ["A) Finding errors and problems in the work of other people", "B) The disciplined process of analysing, evaluating, and synthesising information", "C) The ability to memorise and recall large amounts of information", "D) A negative or sceptical approach to reading and evaluating texts"], "answer": "B", "explanation": "Critical thinking is the disciplined process of conceptualising, applying, analysing, synthesising, and evaluating information."},
    {"id": 2, "question": "What does interrogating assumptions mean according to the passage?", "options": ["A) Asking whether a source is published in a reputable journal", "B) Questioning whether the foundations of an argument are justified", "C) Memorising the main assumptions of an academic theory", "D) Rejecting any argument that relies on unprovable assumptions"], "answer": "B", "explanation": "A critical thinker asks what the assumptions are, whether they are justified, and whether conclusions follow logically."},
    {"id": 3, "question": "According to the passage, what is an academic argument?", "options": ["A) A disagreement between two scholars in a public debate", "B) A structured set of claims supported by evidence and reasoning", "C) A summary of different perspectives on a topic", "D) A personal opinion supported by selected examples"], "answer": "B", "explanation": "An academic argument is a structured set of claims supported by evidence and reasoning."},
    {"id": 4, "question": "What mistake do ineffective academic writers make, according to the passage?", "options": ["A) Using too many quotations from academic sources", "B) Addressing counterarguments unnecessarily in their essays", "C) Overstating findings or claiming certainty where only probability exists", "D) Including too much evidence for their main claims"], "answer": "C", "explanation": "The passage states that effective writers do not overstate findings, implying that weak writers make this mistake."},
    {"id": 5, "question": "What is the difference between domain-specific and transferable critical thinking skills?", "options": ["A) Domain-specific skills are more valuable in professional contexts", "B) Transferable skills require specialist knowledge while domain-specific ones do not", "C) Domain-specific skills require specialist knowledge while transferable skills apply more broadly", "D) Transferable skills are only taught at the postgraduate level"], "answer": "C", "explanation": "Domain-specific skills require specialist knowledge, while transferable skills like detecting bias apply more broadly."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "In everyday language and in academic contexts, critical thinking means exactly the same thing.", "answer": false, "evidence": "Many students assume critical thinking means finding fault; in academic contexts it has a more precise, different meaning."},
    {"id": 2, "statement": "A critical thinker accepts information more readily when it comes from an authoritative source.", "answer": false, "evidence": "This is quite different from simply accepting information because it comes from an authoritative source."},
    {"id": 3, "statement": "An effective academic argument addresses counterarguments as well as the main claim.", "answer": true, "evidence": "Effective academic writers present a clear thesis, support it with relevant evidence, and address counterarguments."},
    {"id": 4, "statement": "All critical thinking skills require specialist domain knowledge to apply.", "answer": false, "evidence": "Some skills require specialist knowledge; others, such as identifying logical fallacies and detecting bias, are more broadly transferable."},
    {"id": 5, "statement": "Universities aim to develop both domain-specific and transferable thinking skills.", "answer": true, "evidence": "Universities aim to develop both types, equipping students to think rigorously in their own field and beyond."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Critical thinking involves interrogating [BLANK] — asking whether the foundations of an argument are justified.", "options": ["A) sources", "B) assumptions", "C) evidence", "D) conclusions"], "answer": "B", "explanation": "Interrogating assumptions is the specific phrase used in the passage."},
    {"id": 2, "sentence": "Effective academic writers present a clear [BLANK], support it with relevant evidence, and address counterarguments.", "options": ["A) summary", "B) overview", "C) thesis", "D) paragraph"], "answer": "C", "explanation": "Present a clear thesis is the exact phrase used in the passage."},
    {"id": 3, "sentence": "Skills such as identifying logical [BLANK], detecting bias, and constructing well-reasoned arguments are broadly transferable.", "options": ["A) errors", "B) fallacies", "C) problems", "D) arguments"], "answer": "B", "explanation": "Identifying logical fallacies is the exact phrase used in the passage."},
    {"id": 4, "sentence": "Effective writers do not [BLANK] their findings or claim certainty where only probability exists.", "options": ["A) publish", "B) support", "C) overstate", "D) evaluate"], "answer": "C", "explanation": "They do not overstate their findings is directly stated in the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage suggests that critical thinking is frequently misunderstood by students. Why might this be, and what is the consequence for their academic work?", "suggested_answer": "Critical thinking is often misunderstood because the term is used loosely in everyday speech to mean scepticism or negativity. Students who believe it means criticising everything may produce essays that only describe problems without proposing reasoned solutions. Without a clear understanding of what critical thinking involves — systematic analysis, logical argumentation, and evidence evaluation — students are unlikely to develop the skills that university education aims to cultivate."},
    {"id": 2, "question": "The passage distinguishes between transferable and domain-specific thinking skills. Which do you think employers value more, and why?", "suggested_answer": "Most employers value a combination of both, but research suggests that transferable skills such as structured reasoning, logical argumentation, and bias detection are highly prized across industries. Domain-specific knowledge dates quickly as industries evolve, while the ability to think critically, adapt to new information, and communicate evidence-based conclusions remains consistently valuable. Many graduate employers explicitly state that they value candidates who can think independently over those with specialised knowledge alone."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 6
)
AND type = 'reading';

-- ── Lesson 7: Understanding Academic Assessment and Feedback ─
UPDATE english_lesson_sections
SET content = $json${
  "title": "Understanding Academic Assessment and Feedback",
  "text": "Assessment is a central feature of academic life, but its purpose is more complex than simply assigning grades. Universities use a variety of assessment formats — including essays, examinations, presentations, projects, and portfolios — to evaluate different types of knowledge, skills, and competencies. Understanding how assessments work and how to use them strategically can significantly enhance student performance. Academic assessment generally falls into two broad categories. Formative assessment is designed to support learning in progress. It provides feedback that helps students identify strengths and weaknesses before a final grade is awarded. Examples include practice essays, in-class quizzes, and draft submissions with tutor comments. The purpose of formative assessment is developmental: it shows students what they need to do to improve. Summative assessment, by contrast, is designed to evaluate learning at the end of a period of study. Examinations, final essays, and end-of-year projects are all examples of summative assessment. These typically carry significant weight in the final grade awarded to each student, and their primary purpose is to certify that a defined level of knowledge or skill has been achieved. Feedback literacy — the ability to understand, interpret, and act on feedback — is an increasingly important skill for students. Research shows that many students receive feedback but fail to engage with it meaningfully, often because they do not understand the marking criteria or because they experience negative emotions in response to critical comments. Students who develop feedback literacy treat feedback as actionable information rather than a judgement of their personal worth. Peer assessment, in which students evaluate the work submitted by their peers using agreed criteria, is another increasingly common feature of university education. When conducted rigorously, peer assessment develops critical thinking, deepens understanding of marking standards, and builds collaborative skills.",
  "glossary": [
    {"term": "formative assessment", "definition": "assessment designed to provide feedback and support the ongoing learning process", "translation": "формативное оценивание"},
    {"term": "summative assessment", "definition": "assessment that evaluates learning at the end of a study period and contributes to a final grade", "translation": "суммативное оценивание"},
    {"term": "feedback literacy", "definition": "the ability to understand, interpret, and act on feedback received from teachers or peers", "translation": "грамотность в работе с обратной связью"},
    {"term": "marking criteria", "definition": "the standards and descriptions used to evaluate and grade student work", "translation": "критерии оценивания"},
    {"term": "peer assessment", "definition": "a process where students evaluate the work of their fellow students using agreed criteria", "translation": "взаимооценивание"},
    {"term": "portfolio", "definition": "a collection of work samples used to demonstrate skills, progress, and achievements", "translation": "портфолио"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does the passage say is the primary purpose of formative assessment?", "options": ["A) To certify that a student has reached a required level", "B) To contribute the largest portion of the final grade", "C) To help students identify strengths and weaknesses before final grading", "D) To compare student performance across different universities"], "answer": "C", "explanation": "Formative assessment provides feedback that helps students identify strengths and weaknesses before a final grade is awarded."},
    {"id": 2, "question": "According to the passage, which of the following is an example of summative assessment?", "options": ["A) A practice essay with tutor feedback", "B) An in-class quiz during the semester", "C) A draft submission with comments from a tutor", "D) A final end-of-year examination"], "answer": "D", "explanation": "Examinations, final essays, and end-of-year projects are all examples of summative assessment."},
    {"id": 3, "question": "What is feedback literacy as described in the passage?", "options": ["A) The ability to write clear and constructive feedback for others", "B) The skill of understanding, interpreting, and acting on feedback received", "C) A course offered by universities to improve academic writing skills", "D) The process of assigning grades based on a marking rubric"], "answer": "B", "explanation": "Feedback literacy is defined as the ability to understand, interpret, and act on feedback."},
    {"id": 4, "question": "Why do many students fail to engage meaningfully with feedback according to the passage?", "options": ["A) They prefer to learn independently without any guidance", "B) Feedback is written in overly technical academic language", "C) They do not understand the marking criteria or react emotionally to criticism", "D) Tutors rarely provide detailed or constructive feedback on work"], "answer": "C", "explanation": "Students fail to engage because they do not understand the marking criteria or experience negative emotions in response to critical comments."},
    {"id": 5, "question": "What does the passage say peer assessment develops in students?", "options": ["A) Competitive attitudes towards academic performance", "B) Critical thinking, deeper understanding, and collaborative skills", "C) The ability to write more clearly under time pressure", "D) Independence from tutor guidance in their studies"], "answer": "B", "explanation": "Peer assessment develops critical thinking, deepens understanding of marking standards, and builds collaborative skills."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Universities use only one type of assessment format to evaluate student performance.", "answer": false, "evidence": "Universities use a variety of assessment formats — including essays, examinations, presentations, projects, and portfolios."},
    {"id": 2, "statement": "Formative assessment is designed to evaluate learning at the end of a study period.", "answer": false, "evidence": "Formative assessment is designed to support learning in progress, not to evaluate at the end."},
    {"id": 3, "statement": "Students who develop feedback literacy treat feedback as actionable information.", "answer": true, "evidence": "Students who develop feedback literacy treat feedback as actionable information rather than a judgement of their personal worth."},
    {"id": 4, "statement": "Peer assessment has no educational value for the students who provide the feedback.", "answer": false, "evidence": "Peer assessment develops critical thinking, deepens understanding of marking standards, and builds collaborative skills."},
    {"id": 5, "statement": "Summative assessments typically have a significant impact on the final grade awarded.", "answer": true, "evidence": "These typically carry significant weight in the final grade awarded to each student."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Formative assessment provides feedback that helps students identify strengths and [BLANK] before a final grade is awarded.", "options": ["A) grades", "B) weaknesses", "C) improvements", "D) errors"], "answer": "B", "explanation": "Identify strengths and weaknesses is the exact phrase used in the passage."},
    {"id": 2, "sentence": "The purpose of formative assessment is [BLANK]: it shows students what they need to do to improve.", "options": ["A) evaluative", "B) competitive", "C) developmental", "D) administrative"], "answer": "C", "explanation": "The purpose of formative assessment is developmental is stated directly in the passage."},
    {"id": 3, "sentence": "Students who develop feedback [BLANK] treat feedback as actionable information rather than a personal judgement.", "options": ["A) skills", "B) literacy", "C) awareness", "D) management"], "answer": "B", "explanation": "Feedback literacy is the specific term introduced and defined in the passage."},
    {"id": 4, "sentence": "Peer assessment deepens understanding of marking [BLANK] and builds collaborative skills.", "options": ["A) criteria", "B) systems", "C) standards", "D) grades"], "answer": "C", "explanation": "Deepens understanding of marking standards is the exact phrase from the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage suggests that many students do not engage meaningfully with feedback. What strategies could tutors and universities use to improve this?", "suggested_answer": "Universities could make feedback more actionable by structuring comments around specific marking criteria and suggesting concrete next steps. Tutors could use dialogue-based feedback sessions where students ask questions and discuss how to improve, rather than simply receiving written comments. Universities might also teach feedback literacy explicitly as part of orientation programmes, helping students understand that feedback reflects the quality of work rather than their intelligence or personal worth."},
    {"id": 2, "question": "Do you think peer assessment is a fair method of evaluation? What are its advantages and limitations?", "suggested_answer": "Peer assessment offers genuine advantages: it develops critical thinking, familiarises students with assessment criteria, and builds collaborative communication skills. However, its fairness as a formal evaluation method is debatable. Students may lack the expertise to assess complex work accurately, may be influenced by personal relationships, or may apply criteria inconsistently. For this reason, peer assessment works best as a learning activity rather than a high-stakes evaluation tool. When supported by clear criteria and tutor moderation, it can be both educationally valuable and reasonably reliable."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate'
    AND c.category = 'General English'
    AND m.order_index = 1
    AND l.order_index = 7
)
AND type = 'reading';