-- ============================================================
-- B1 Intermediate / Module 3 (Sport & Fitness)
-- Reading Sections — Lessons 1–7
-- Theme: Climate & Environment
-- ============================================================

-- ── Lesson 1 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Climate Change: Causes, Evidence, and Consequences",
  "text": "Climate change refers to long-term shifts in global temperatures and weather patterns. While natural factors have always influenced climate, scientific evidence shows that since the mid-twentieth century, human activities have become the dominant driver of change. The burning of fossil fuels — coal, oil, and natural gas — releases carbon dioxide and other greenhouse gases into the atmosphere. These gases trap heat from the sun, causing the average temperature of Earth to rise. This phenomenon is known as the greenhouse effect. The evidence for climate change is overwhelming. Global average temperatures have risen by approximately 1.1 degrees Celsius since the pre-industrial era. Arctic sea ice is melting at record rates. Sea levels are rising as glaciers and ice sheets lose mass. Extreme weather events including heatwaves, hurricanes, floods, and droughts are becoming more frequent and severe. Coral reefs, which support twenty-five percent of all marine life, are experiencing widespread bleaching as ocean temperatures rise. The consequences of continued warming are serious. Scientists project that if emissions are not significantly reduced, temperatures could rise by three to four degrees Celsius by the end of the century. This would displace hundreds of millions of people, threaten food security, and trigger the collapse of entire ecosystems. Vulnerable countries in low-lying coastal areas and the tropics face the greatest risks, despite contributing least to global emissions. Addressing climate change requires both mitigation — reducing emissions — and adaptation — adjusting to changes that are already unavoidable. International cooperation through agreements such as the Paris Agreement is essential, but current national commitments fall short of what scientists say is necessary.",
  "glossary": [
    {"term": "greenhouse effect", "definition": "the warming of Earth caused by gases in the atmosphere trapping heat from the sun", "translation": "парниковый эффект"},
    {"term": "fossil fuels", "definition": "natural fuels such as coal, oil, and gas formed from ancient organic matter", "translation": "ископаемое топливо"},
    {"term": "emissions", "definition": "the release of gases, especially carbon dioxide, into the atmosphere", "translation": "выбросы"},
    {"term": "mitigation", "definition": "the action of reducing the severity or impact of something negative", "translation": "смягчение последствий"},
    {"term": "adaptation", "definition": "the process of adjusting to new conditions or changing circumstances", "translation": "адаптация"},
    {"term": "bleaching", "definition": "the whitening and potential death of coral caused by heat-stressed expulsion of algae", "translation": "обесцвечивание (коралловых рифов)"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What has been the dominant driver of climate change since the mid-twentieth century according to the passage?", "options": ["A) Natural volcanic eruptions", "B) Changes in solar radiation", "C) Human activities, especially burning fossil fuels", "D) Natural shifts in ocean currents"], "answer": "C", "explanation": "Scientific evidence shows that since the mid-twentieth century, human activities have become the dominant driver of climate change."},
    {"id": 2, "question": "How much have global average temperatures risen since the pre-industrial era?", "options": ["A) 0.5 degrees Celsius", "B) 1.1 degrees Celsius", "C) 2.0 degrees Celsius", "D) 3.4 degrees Celsius"], "answer": "B", "explanation": "Global average temperatures have risen by approximately 1.1 degrees Celsius since the pre-industrial era."},
    {"id": 3, "question": "What percentage of marine life do coral reefs support according to the passage?", "options": ["A) Ten percent", "B) Fifteen percent", "C) Twenty percent", "D) Twenty-five percent"], "answer": "D", "explanation": "Coral reefs support twenty-five percent of all marine life."},
    {"id": 4, "question": "Which countries face the greatest risks from climate change according to the passage?", "options": ["A) The largest industrial nations that produce the most emissions", "B) Countries in low-lying coastal areas and the tropics that contribute least to emissions", "C) Landlocked countries in cold northern regions", "D) Countries that have signed the Paris Agreement"], "answer": "B", "explanation": "Vulnerable countries in low-lying coastal areas and the tropics face the greatest risks despite contributing least to global emissions."},
    {"id": 5, "question": "What does the passage say about current national commitments under international climate agreements?", "options": ["A) They are sufficient to prevent dangerous warming", "B) They exceed what scientists say is necessary", "C) They fall short of what scientists say is necessary", "D) They are not being implemented by most countries"], "answer": "C", "explanation": "Current national commitments fall short of what scientists say is necessary to prevent dangerous levels of warming."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Natural factors have always influenced climate, but human activities are now the dominant driver of change.", "answer": true, "evidence": "While natural factors have always influenced climate, scientific evidence shows that human activities have become the dominant driver."},
    {"id": 2, "statement": "Arctic sea ice is growing as global temperatures rise.", "answer": false, "evidence": "Arctic sea ice is melting at record rates."},
    {"id": 3, "statement": "Extreme weather events are becoming less frequent as a result of climate change.", "answer": false, "evidence": "Extreme weather events including heatwaves, hurricanes, floods, and droughts are becoming more frequent and severe."},
    {"id": 4, "statement": "Addressing climate change requires both reducing emissions and adjusting to changes already underway.", "answer": true, "evidence": "Addressing climate change requires both mitigation — reducing emissions — and adaptation — adjusting to changes that are already unavoidable."},
    {"id": 5, "statement": "If emissions are not reduced, temperatures could rise by three to four degrees by the end of the century.", "answer": true, "evidence": "Scientists project that if emissions are not significantly reduced, temperatures could rise by three to four degrees Celsius by the end of the century."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The burning of fossil fuels releases gases that trap heat in the atmosphere, causing warming. This process is called the [BLANK].", "options": ["A) carbon cycle", "B) greenhouse effect", "C) thermal expansion", "D) ozone depletion"], "answer": "B", "explanation": "The greenhouse effect is the warming caused by gases in the atmosphere trapping heat from the sun."},
    {"id": 2, "sentence": "The release of carbon dioxide and other gases into the atmosphere from burning fuel is called [BLANK].", "options": ["A) pollution", "B) radiation", "C) emissions", "D) combustion"], "answer": "C", "explanation": "Emissions refers specifically to the release of greenhouse gases into the atmosphere."},
    {"id": 3, "sentence": "Addressing climate change requires both [BLANK] — reducing emissions — and adaptation to changes already occurring.", "options": ["A) regulation", "B) mitigation", "C) conservation", "D) intervention"], "answer": "B", "explanation": "Mitigation means reducing the severity of the problem — in this context, cutting emissions to slow warming."},
    {"id": 4, "sentence": "Countries in low-lying coastal areas face the greatest climate risks despite contributing [BLANK] to global emissions.", "options": ["A) most", "B) equally", "C) least", "D) significantly"], "answer": "C", "explanation": "The passage specifically states that vulnerable countries contribute least to global emissions yet face the greatest risks."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage notes that vulnerable countries face the greatest climate risks despite contributing least to emissions. Is this fair? What moral obligations do high-emission countries have?", "suggested_answer": "This situation is deeply unjust. Countries that industrialised early built their wealth through processes that released the majority of historical emissions, yet the consequences fall most severely on developing nations that had little part in causing the problem. High-emission countries have a clear moral obligation to provide financial and technological support to help vulnerable nations adapt. Beyond fairness, there is also a practical argument: climate instability generates migration and conflict that affects all countries, so helping vulnerable nations is ultimately in the interest of all."},
    {"id": 2, "question": "The passage argues that both mitigation and adaptation are necessary responses to climate change. Which do you think is more urgent, and why?", "suggested_answer": "Both are urgent, but mitigation must take priority because it addresses the root cause. Without significant reductions in emissions, adaptation becomes increasingly inadequate — there are limits to how much sea walls can be raised or crop varieties adjusted before conditions become unsurvivable. However, adaptation is already critical for communities facing impacts today. The most effective approach combines rapid mitigation to limit future warming with targeted adaptation support for those who are already experiencing severe consequences."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 1
) AND type = 'reading';

-- ── Lesson 2 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Renewable Energy: Powering a Sustainable Future",
  "text": "The transition from fossil fuels to renewable energy is one of the most significant technological and economic challenges of the twenty-first century. Renewable energy sources — including solar, wind, hydropower, and geothermal energy — generate electricity without burning fossil fuels and without producing greenhouse gas emissions. In recent years, the cost of renewable energy has fallen dramatically. Solar panels, which cost roughly one hundred times more per unit of electricity in 1980 than they do today, have become one of the cheapest sources of new electricity generation in history. Wind energy has followed a similar trajectory. As costs have fallen, investment in renewable energy has grown rapidly. In 2022, global investment in clean energy exceeded one trillion dollars for the first time. More than a third of all electricity generated globally now comes from renewable sources. Governments around the world are setting targets to achieve net-zero emissions by 2050, requiring massive increases in renewable capacity. Despite this progress, significant challenges remain. Renewable energy sources are intermittent — solar panels produce no electricity at night and wind turbines stop when the wind is calm. Storing energy in batteries or other systems to cover these gaps remains expensive and technologically challenging. The electricity grids of most countries were designed for large centralised power stations and must be redesigned to accommodate distributed renewable generation. The mining of minerals such as lithium, cobalt, and rare earth elements for batteries and turbines raises its own environmental and social concerns. The transition to renewable energy will require not only technological innovation but also significant changes in policy, infrastructure, and international cooperation.",
  "glossary": [
    {"term": "renewable energy", "definition": "energy from sources that are naturally replenished, such as sunlight, wind, and water", "translation": "возобновляемая энергия"},
    {"term": "intermittent", "definition": "stopping and starting at irregular intervals; not continuous", "translation": "прерывистый, непостоянный"},
    {"term": "net-zero", "definition": "a state where the amount of greenhouse gas emitted equals the amount removed from the atmosphere", "translation": "углеродная нейтральность"},
    {"term": "trajectory", "definition": "the path or course followed by something developing over time", "translation": "траектория"},
    {"term": "infrastructure", "definition": "the basic physical systems of a country, such as roads, power grids, and water supplies", "translation": "инфраструктура"},
    {"term": "geothermal", "definition": "relating to heat produced within the Earth and used as an energy source", "translation": "геотермальный"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What advantage do renewable energy sources have over fossil fuels according to the passage?", "options": ["A) They are always available regardless of weather conditions", "B) They generate electricity without producing greenhouse gas emissions", "C) They are less expensive to install than any other energy source", "D) They require no maintenance once installed"], "answer": "B", "explanation": "Renewable energy sources generate electricity without burning fossil fuels and without producing greenhouse gas emissions."},
    {"id": 2, "question": "How much has the cost of solar panels changed since 1980?", "options": ["A) They have become twice as expensive", "B) They have remained roughly the same cost", "C) They now cost approximately one hundred times less than in 1980", "D) They have become ten times cheaper than in 1980"], "answer": "C", "explanation": "Solar panels cost roughly one hundred times more per unit of electricity in 1980 than they do today."},
    {"id": 3, "question": "What was achieved globally in clean energy investment for the first time in 2022?", "options": ["A) Investment reached one hundred billion dollars", "B) Investment exceeded one trillion dollars", "C) More than half of all electricity came from renewables", "D) All new power stations built were renewable"], "answer": "B", "explanation": "In 2022, global investment in clean energy exceeded one trillion dollars for the first time."},
    {"id": 4, "question": "What is the main challenge of intermittent renewable energy sources?", "options": ["A) They produce too much electricity and overload the grid", "B) They are too expensive to build in developing countries", "C) They do not generate electricity at all times, requiring energy storage solutions", "D) They require extremely large areas of land to generate significant power"], "answer": "C", "explanation": "Renewable sources are intermittent — solar panels produce no electricity at night and wind turbines stop when wind is calm — creating a need for energy storage."},
    {"id": 5, "question": "What environmental concern does the passage raise about the renewable energy transition?", "options": ["A) Renewable energy farms destroy natural habitats on a massive scale", "B) The mining of minerals for batteries and turbines raises environmental and social concerns", "C) Renewable energy actually produces more emissions than fossil fuels over its lifetime", "D) Solar panels and wind turbines create dangerous levels of noise and light pollution"], "answer": "B", "explanation": "The mining of minerals such as lithium, cobalt, and rare earth elements for batteries and turbines raises environmental and social concerns."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The cost of solar energy has remained stable over recent decades.", "answer": false, "evidence": "Solar panels cost roughly one hundred times more per unit of electricity in 1980 than they do today."},
    {"id": 2, "statement": "More than a third of all electricity generated globally now comes from renewable sources.", "answer": true, "evidence": "More than a third of all electricity generated globally now comes from renewable sources."},
    {"id": 3, "statement": "Renewable energy can be stored easily and cheaply in current battery technology.", "answer": false, "evidence": "Storing energy in batteries or other systems to cover gaps remains expensive and technologically challenging."},
    {"id": 4, "statement": "Most existing electricity grids were designed to work with distributed renewable energy sources.", "answer": false, "evidence": "The electricity grids of most countries were designed for large centralised power stations and must be redesigned."},
    {"id": 5, "statement": "Achieving net-zero emissions by 2050 will require massive increases in renewable energy capacity.", "answer": true, "evidence": "Governments around the world are setting targets to achieve net-zero emissions by 2050, requiring massive increases in renewable capacity."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Solar and wind energy are [BLANK] — they stop producing electricity when the sun sets or the wind calms, creating a need for storage.", "options": ["A) reliable", "B) abundant", "C) intermittent", "D) efficient"], "answer": "C", "explanation": "Intermittent means stopping and starting at irregular intervals, which describes how solar and wind energy production varies."},
    {"id": 2, "sentence": "Governments are setting targets to achieve [BLANK] emissions by 2050, balancing the greenhouse gases emitted with those removed.", "options": ["A) reduced", "B) net-zero", "C) minimal", "D) carbon-free"], "answer": "B", "explanation": "Net-zero is the specific term for a state where emissions produced equal emissions removed from the atmosphere."},
    {"id": 3, "sentence": "The cost of solar energy has followed a similar [BLANK] to wind energy, falling rapidly as technology and production have improved.", "options": ["A) pattern", "B) trajectory", "C) trend", "D) decline"], "answer": "B", "explanation": "Trajectory describes the path or course of development over time, which is the word used in the passage."},
    {"id": 4, "sentence": "The electricity grid and other basic physical systems of a country are collectively known as [BLANK].", "options": ["A) technology", "B) utilities", "C) infrastructure", "D) services"], "answer": "C", "explanation": "Infrastructure refers to the basic physical systems of a country, including power grids and transport networks."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage notes that the renewable energy transition requires significant changes in policy, infrastructure, and international cooperation. Which of these do you think is the biggest barrier, and why?", "suggested_answer": "Political will and international cooperation may be the greatest barriers, because the technical solutions largely already exist. Solar and wind energy are now cheap and proven technologies. The challenge is that transitioning away from fossil fuels threatens established economic interests in coal, oil, and gas industries that have significant political influence in many countries. Internationally, poorer countries need financial support to transition without sacrificing development. Without strong political commitment and fair global cooperation, the technical potential of renewable energy will not be realised fast enough."},
    {"id": 2, "question": "The passage raises concerns about the mining of minerals for renewable energy technology. Does this mean renewable energy is not truly sustainable? How should we weigh these concerns?", "suggested_answer": "The environmental costs of mineral mining are real and must be addressed, but they should be weighed against the far greater long-term damage from continued fossil fuel use. Climate change threatens ecosystems on a planetary scale, while mining impacts, though serious, are more localised and potentially manageable through better regulation. The goal should be to make the transition as clean as possible — reducing mining impacts through recycling, more efficient use of materials, and better environmental standards — while not allowing these concerns to delay the transition away from fossil fuels."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 2
) AND type = 'reading';

-- ── Lesson 3 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Deforestation: When Forests Disappear",
  "text": "Forests cover approximately thirty percent of the land surface of Earth and play a vital role in regulating the global climate, supporting biodiversity, and sustaining the livelihoods of hundreds of millions of people. Yet every year, millions of hectares of forest are cleared for agriculture, logging, mining, and urban development. Tropical forests, including the Amazon rainforest in South America and the Congo Basin in Africa, are experiencing the most severe losses. Deforestation contributes to climate change in two distinct ways. First, trees absorb carbon dioxide from the atmosphere as they grow, acting as carbon sinks. When forests are cut down or burned, this stored carbon is released back into the atmosphere, contributing to greenhouse gas emissions. Second, forests regulate local and regional rainfall patterns. Their destruction disrupts water cycles, contributing to droughts and floods in affected regions. Biodiversity loss is another catastrophic consequence. Tropical forests contain more than half of all land species on Earth. When their habitat is destroyed, many species face extinction before they have even been recorded by science. The Amazon alone loses thousands of species every year due to deforestation. The economic drivers of deforestation are powerful. In many developing countries, clearing forest land for cattle ranching, soy cultivation, or palm oil production generates income and employment that governments and communities rely on. Addressing deforestation therefore requires offering alternative economic pathways, compensating communities for preserving forests, and enforcing existing environmental laws. International mechanisms such as REDD+ — Reducing Emissions from Deforestation and Forest Degradation — aim to pay developing countries for protecting their forests, but implementation has been slow and results mixed.",
  "glossary": [
    {"term": "deforestation", "definition": "the large-scale clearing or removal of forests for other land uses", "translation": "вырубка лесов"},
    {"term": "biodiversity", "definition": "the variety of plant and animal life in a particular habitat or on Earth as a whole", "translation": "биоразнообразие"},
    {"term": "carbon sink", "definition": "a natural system such as a forest or ocean that absorbs and stores carbon dioxide", "translation": "поглотитель углерода"},
    {"term": "habitat", "definition": "the natural environment in which a species lives and grows", "translation": "среда обитания"},
    {"term": "extinction", "definition": "the complete disappearance of a species from the Earth", "translation": "вымирание"},
    {"term": "degradation", "definition": "the process of something declining in quality or condition", "translation": "деградация"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What percentage of Earth's land surface is covered by forests according to the passage?", "options": ["A) Ten percent", "B) Twenty percent", "C) Thirty percent", "D) Forty percent"], "answer": "C", "explanation": "Forests cover approximately thirty percent of the land surface of Earth."},
    {"id": 2, "question": "How does deforestation contribute to climate change?", "options": ["A) Only by releasing stored carbon when trees are burned or cut down", "B) By releasing stored carbon and disrupting rainfall patterns", "C) Only by disrupting water cycles and regional weather patterns", "D) By reducing oxygen levels in the atmosphere"], "answer": "B", "explanation": "Deforestation contributes by releasing stored carbon from trees and by disrupting water cycles and rainfall patterns."},
    {"id": 3, "question": "What proportion of all land species do tropical forests contain according to the passage?", "options": ["A) One quarter", "B) One third", "C) More than half", "D) More than three quarters"], "answer": "C", "explanation": "Tropical forests contain more than half of all land species on Earth."},
    {"id": 4, "question": "What are the main economic drivers of deforestation mentioned in the passage?", "options": ["A) Urban expansion and road construction", "B) Cattle ranching, soy cultivation, and palm oil production", "C) Mining and oil extraction", "D) Tourism development and infrastructure projects"], "answer": "B", "explanation": "Clearing forest for cattle ranching, soy cultivation, or palm oil production generates income and employment that communities rely on."},
    {"id": 5, "question": "What is the purpose of the REDD+ mechanism mentioned in the passage?", "options": ["A) To fine countries that exceed emission targets", "B) To pay developing countries for protecting their forests", "C) To fund reforestation projects in developed countries", "D) To monitor deforestation rates using satellite technology"], "answer": "B", "explanation": "REDD+ aims to pay developing countries for protecting their forests, though implementation has been slow."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Forests play no significant role in regulating the global climate.", "answer": false, "evidence": "Forests play a vital role in regulating the global climate, supporting biodiversity, and sustaining livelihoods."},
    {"id": 2, "statement": "When forests are cut down, the carbon stored in trees is released back into the atmosphere.", "answer": true, "evidence": "When forests are cut down or burned, stored carbon is released back into the atmosphere, contributing to greenhouse gas emissions."},
    {"id": 3, "statement": "Many species in tropical forests have already been fully documented by science before their habitats were destroyed.", "answer": false, "evidence": "Many species face extinction before they have even been recorded by science."},
    {"id": 4, "statement": "The economic drivers of deforestation are relatively weak and easy to counteract.", "answer": false, "evidence": "The economic drivers of deforestation are powerful. Clearing forest generates income and employment that governments and communities rely on."},
    {"id": 5, "statement": "The REDD+ mechanism has produced rapid and clearly successful results in reducing deforestation.", "answer": false, "evidence": "Implementation has been slow and results mixed."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Trees absorb carbon dioxide as they grow, acting as natural [BLANK] that remove greenhouse gases from the atmosphere.", "options": ["A) filters", "B) carbon sinks", "C) reserves", "D) buffers"], "answer": "B", "explanation": "Carbon sinks are natural systems that absorb and store carbon dioxide, which is the role trees play."},
    {"id": 2, "sentence": "Tropical forests contain more than half of all land species on Earth. When their [BLANK] is destroyed, many face extinction.", "options": ["A) ecosystem", "B) territory", "C) habitat", "D) region"], "answer": "C", "explanation": "Habitat is the natural environment in which a species lives — its destruction threatens the species that depend on it."},
    {"id": 3, "sentence": "The complete disappearance of a species from Earth due to habitat loss is called [BLANK].", "options": ["A) migration", "B): extinction", "C) depletion", "D) reduction"], "answer": "B", "explanation": "Extinction is the complete disappearance of a species, which is what the passage warns could happen to many tropical species."},
    {"id": 4, "sentence": "Forests cover approximately thirty percent of Earth's land surface, but large areas are being cleared every year through [BLANK].", "options": ["A) erosion", "B) pollution", "C) deforestation", "D) degradation"], "answer": "C", "explanation": "Deforestation is the large-scale clearing or removal of forests, which is the central topic of the passage."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes a conflict between economic development and environmental protection. How can developing countries be supported to preserve forests without sacrificing economic growth?", "suggested_answer": "The tension between development and forest protection can be reduced through several approaches. Payment schemes like REDD+ can compensate communities and governments for the economic value of standing forests. Sustainable forest management can generate income from timber and non-timber products without clear-cutting. Ecotourism can provide livelihoods that depend on intact ecosystems. Wealthy countries, which benefited economically from their own past deforestation, have a moral obligation to fund these alternatives. The key is ensuring that conservation is economically competitive with destruction, which requires both international financial support and effective local governance."},
    {"id": 2, "question": "The passage mentions that many species face extinction before they have even been scientifically recorded. Why does the loss of undiscovered species matter? Should we value all life equally?", "suggested_answer": "The loss of undiscovered species is significant for multiple reasons. Many species have potential medical, agricultural, or ecological value that we have not yet identified — we cannot know what we are losing until it is gone. Ecologically, every species plays a role in its ecosystem, and its loss can have cascading effects on other species and on ecosystem stability. From an ethical perspective, many argue that species have intrinsic value regardless of their usefulness to humans. Whether or not we value all life equally, the irreversibility of extinction makes caution the rational choice."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 3
) AND type = 'reading';

-- ── Lesson 4 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Ocean Pollution: Threats to the Marine World",
  "text": "The oceans cover more than seventy percent of Earth's surface and produce more than half of the oxygen we breathe. They regulate the global climate, absorb carbon dioxide, and support food systems that billions of people depend on. Yet human activity is placing marine ecosystems under unprecedented pressure. Plastic pollution is among the most visible threats to ocean health. Each year, approximately eight million tonnes of plastic enter the ocean, breaking down into tiny particles called microplastics that are now found in the deepest ocean trenches, in the tissues of marine animals, and even in human blood. Marine animals frequently mistake plastic debris for food, leading to internal injuries, malnutrition, and death. Seabirds, sea turtles, and whales are particularly vulnerable. Chemical pollution presents a less visible but equally serious threat. Agricultural runoff containing fertilisers causes rapid growth of algae in coastal waters, a process called eutrophication. When the algae die and decompose, oxygen is consumed, creating vast dead zones where most marine life cannot survive. More than five hundred such zones have been identified worldwide. Ocean acidification is another consequence of rising carbon dioxide levels. As the ocean absorbs more carbon dioxide from the atmosphere, its chemistry changes, becoming more acidic. This affects shell-forming organisms such as oysters, clams, and corals, which struggle to build their protective structures in acidic conditions. Addressing ocean pollution requires action at multiple levels: international agreements to reduce plastic production, better waste management systems, stricter controls on agricultural chemicals, and rapid reduction of carbon emissions to slow acidification. Without coordinated global action, the damage to marine ecosystems will become irreversible within decades.",
  "glossary": [
    {"term": "microplastics", "definition": "tiny pieces of plastic less than five millimetres in size found throughout the environment", "translation": "микропластик"},
    {"term": "eutrophication", "definition": "the excessive enrichment of water with nutrients causing dense algae growth and oxygen depletion", "translation": "эвтрофикация"},
    {"term": "acidification", "definition": "the process by which a substance becomes more acidic, reducing its pH value", "translation": "закисление, подкисление"},
    {"term": "ecosystem", "definition": "a community of living organisms interacting with each other and their environment", "translation": "экосистема"},
    {"term": "runoff", "definition": "water that flows over land surface carrying chemicals and sediment into water bodies", "translation": "сток"},
    {"term": "decompose", "definition": "to break down into smaller components through biological or chemical processes", "translation": "разлагаться"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What proportion of the oxygen we breathe do the oceans produce according to the passage?", "options": ["A) More than a quarter", "B) More than a third", "C) More than half", "D) More than two thirds"], "answer": "C", "explanation": "The oceans produce more than half of the oxygen we breathe."},
    {"id": 2, "question": "How much plastic enters the ocean each year according to the passage?", "options": ["A) One million tonnes", "B) Four million tonnes", "C) Eight million tonnes", "D) Twelve million tonnes"], "answer": "C", "explanation": "Each year, approximately eight million tonnes of plastic enter the ocean."},
    {"id": 3, "question": "What is eutrophication as described in the passage?", "options": ["A) The warming of oceans due to climate change", "B) The accumulation of plastic in marine ecosystems", "C) The rapid growth of algae caused by fertiliser runoff, depleting oxygen", "D) The process by which ocean water becomes more acidic"], "answer": "C", "explanation": "Eutrophication is the rapid growth of algae caused by agricultural runoff containing fertilisers. When the algae die, oxygen is consumed."},
    {"id": 4, "question": "How does ocean acidification affect marine life according to the passage?", "options": ["A) It raises water temperature and kills tropical fish", "B) It makes the water unsuitable for large marine mammals", "C) It affects shell-forming organisms that struggle to build structures in acidic conditions", "D) It reduces the amount of light penetrating deep water"], "answer": "C", "explanation": "Acidification affects shell-forming organisms such as oysters, clams, and corals which struggle to build protective structures in more acidic conditions."},
    {"id": 5, "question": "How many oxygen-depleted dead zones have been identified worldwide?", "options": ["A) More than one hundred", "B) More than two hundred", "C) More than three hundred", "D) More than five hundred"], "answer": "D", "explanation": "More than five hundred dead zones have been identified worldwide."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Microplastics have been found only on the ocean surface and in coastal areas.", "answer": false, "evidence": "Microplastics are now found in the deepest ocean trenches, in the tissues of marine animals, and even in human blood."},
    {"id": 2, "statement": "Marine animals sometimes mistake plastic debris for food, which can cause them harm.", "answer": true, "evidence": "Marine animals frequently mistake plastic debris for food, leading to internal injuries, malnutrition, and death."},
    {"id": 3, "statement": "Dead zones in the ocean are areas where marine life thrives due to high nutrient levels.", "answer": false, "evidence": "When algae die and decompose, oxygen is consumed, creating vast dead zones where most marine life cannot survive."},
    {"id": 4, "statement": "Ocean acidification is caused by the ocean absorbing more carbon dioxide from the atmosphere.", "answer": true, "evidence": "As the ocean absorbs more carbon dioxide from the atmosphere, its chemistry changes, becoming more acidic."},
    {"id": 5, "statement": "The passage suggests that damage to marine ecosystems can be easily reversed if action is taken.", "answer": false, "evidence": "Without coordinated global action, the damage to marine ecosystems will become irreversible within decades."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Plastic breaks down into tiny pieces called [BLANK] that are now found even in the deepest ocean trenches and in human blood.", "options": ["A) nanoparticles", "B) microplastics", "C) sediment", "D) fragments"], "answer": "B", "explanation": "Microplastics are the specific term for tiny plastic particles less than five millimetres in size."},
    {"id": 2, "sentence": "Agricultural [BLANK] containing fertilisers flows into coastal waters and causes rapid algae growth that depletes oxygen.", "options": ["A) waste", "B) pollution", "C) runoff", "D) chemicals"], "answer": "C", "explanation": "Runoff is water that flows over land carrying chemicals — in this case, fertilisers from agriculture."},
    {"id": 3, "sentence": "When algae [BLANK] after dying, they consume oxygen and create dead zones where marine life cannot survive.", "options": ["A) multiply", "B) decompose", "C) sink", "D) accumulate"], "answer": "B", "explanation": "Decompose means to break down through biological processes, which is what happens to algae when they die."},
    {"id": 4, "sentence": "The rising acidity of the ocean — known as ocean [BLANK] — makes it harder for corals and shellfish to form their protective structures.", "options": ["A) warming", "B) pollution", "C) acidification", "D) degradation"], "answer": "C", "explanation": "Acidification is the process by which the ocean becomes more acidic due to absorbing carbon dioxide."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes multiple threats to ocean health from different sources. If you could address only one, which would you prioritise and why?", "suggested_answer": "Carbon dioxide emissions causing ocean acidification would be the most critical to address because it is both global in scale and the root cause of multiple other environmental problems including climate change. Unlike plastic pollution, which is highly visible and generates public concern, acidification is invisible and affects the basic chemistry of the ocean on a planetary scale. Addressing emissions would also slow climate-related warming of the oceans. However, plastic pollution deserves urgent attention too because it is already present in deep sea trenches and human tissue, and the scale of harm to individual animals is immediate and observable."},
    {"id": 2, "question": "The passage notes that microplastics have been found in human blood. Does this change how you think about plastic pollution? Should individuals or governments be primarily responsible for reducing plastic waste?", "suggested_answer": "Finding microplastics in human blood makes the issue directly personal — it is no longer only a problem for marine animals in distant oceans. This may make people more motivated to change behaviour. However, individual action alone is insufficient when the majority of plastic waste comes from industrial production and packaging decisions made by companies. Government regulation — banning unnecessary single-use plastics, requiring producers to take responsibility for waste, and investing in recycling infrastructure — is essential. Individual choices matter but systemic change driven by policy is more effective and equitable."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 4
) AND type = 'reading';

-- ── Lesson 5 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Biodiversity Loss: The Sixth Mass Extinction",
  "text": "Earth is currently experiencing what scientists describe as the sixth mass extinction event in the history of life on the planet. The previous five were caused by natural events such as asteroid impacts and volcanic eruptions. This one is caused entirely by human activity. Species are disappearing at a rate estimated to be one thousand times higher than the natural background rate. It is conservatively estimated that around one million species currently face extinction, many within decades. The primary causes of biodiversity loss are habitat destruction, overexploitation, climate change, pollution, and invasive species. Habitat destruction — primarily through deforestation, wetland drainage, and conversion of land for agriculture — is the single greatest threat, eliminating the environments that species need to survive and reproduce. Biodiversity matters for many reasons. Ecosystems provide services that humanity depends on, including clean air and water, pollination of crops, regulation of disease, and decomposition of waste. These services have been estimated to be worth tens of trillions of dollars annually, yet they are provided for free by functioning ecosystems. The loss of biodiversity erodes the resilience of these systems. When a key species disappears, entire food webs can collapse. Pollinators such as bees are particularly important — approximately eighty percent of all food crops depend on pollination by insects and other animals. The decline of bee populations in recent decades due to pesticides, habitat loss, and disease poses a direct threat to global food security. Conservation efforts include the creation of protected areas, captive breeding programmes, restoration of degraded habitats, and international agreements such as the Convention on Biological Diversity. However, current protected areas cover only around seventeen percent of land and ten percent of the ocean.",
  "glossary": [
    {"term": "mass extinction", "definition": "a widespread and rapid decrease in the diversity and abundance of life on Earth", "translation": "массовое вымирание"},
    {"term": "overexploitation", "definition": "the excessive use of a natural resource to the point where it cannot recover", "translation": "сверхэксплуатация"},
    {"term": "invasive species", "definition": "non-native organisms introduced to an ecosystem that cause harm to native species", "translation": "инвазивные виды"},
    {"term": "pollination", "definition": "the transfer of pollen between plants enabling fertilisation and seed production", "translation": "опыление"},
    {"term": "food web", "definition": "the interconnected network of feeding relationships between species in an ecosystem", "translation": "пищевая сеть"},
    {"term": "resilience", "definition": "the ability of an ecosystem to recover from disturbance and maintain its function", "translation": "устойчивость экосистемы"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What distinguishes the current mass extinction from the previous five?", "options": ["A) It is happening more slowly than previous extinctions", "B) It is caused entirely by human activity rather than natural events", "C) It affects only terrestrial species, not marine life", "D) It is taking place only in tropical regions"], "answer": "B", "explanation": "The previous five mass extinctions were caused by natural events. This one is caused entirely by human activity."},
    {"id": 2, "question": "What is described as the single greatest threat to biodiversity?", "options": ["A) Climate change and rising temperatures", "B) Pollution from industrial and agricultural sources", "C) Habitat destruction through deforestation and land conversion", "D) Overexploitation of wildlife through hunting and fishing"], "answer": "C", "explanation": "Habitat destruction — primarily through deforestation, wetland drainage, and land conversion for agriculture — is the single greatest threat."},
    {"id": 3, "question": "What percentage of all food crops depend on pollination by insects and animals?", "options": ["A) Approximately fifty percent", "B) Approximately sixty percent", "C) Approximately seventy percent", "D) Approximately eighty percent"], "answer": "D", "explanation": "Approximately eighty percent of all food crops depend on pollination by insects and other animals."},
    {"id": 4, "question": "What ecosystem services does the passage describe biodiversity as providing?", "options": ["A) Clean air and water, pollination, disease regulation, and waste decomposition", "B) Timber, medicinal plants, tourism, and agricultural land", "C) Carbon storage, rainfall regulation, soil fertility, and flood protection", "D) All of the above are mentioned in the passage"], "answer": "A", "explanation": "The passage lists clean air and water, pollination of crops, regulation of disease, and decomposition of waste as ecosystem services."},
    {"id": 5, "question": "What percentage of land is currently covered by protected areas?", "options": ["A) Around five percent", "B) Around ten percent", "C) Around seventeen percent", "D) Around twenty-five percent"], "answer": "C", "explanation": "Current protected areas cover only around seventeen percent of land."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The current rate of species extinction is similar to the natural background rate.", "answer": false, "evidence": "Species are disappearing at a rate estimated to be one thousand times higher than the natural background rate."},
    {"id": 2, "statement": "Ecosystem services such as pollination and water purification have enormous economic value.", "answer": true, "evidence": "These services have been estimated to be worth tens of trillions of dollars annually."},
    {"id": 3, "statement": "The loss of a key species can cause entire food webs to collapse.", "answer": true, "evidence": "When a key species disappears, entire food webs can collapse."},
    {"id": 4, "statement": "Bee populations are growing due to successful conservation programmes.", "answer": false, "evidence": "The decline of bee populations in recent decades due to pesticides, habitat loss, and disease poses a direct threat to global food security."},
    {"id": 5, "statement": "Current protected areas cover more than half of the world's land surface.", "answer": false, "evidence": "Current protected areas cover only around seventeen percent of land and ten percent of the ocean."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Earth is experiencing its sixth [BLANK] event, with species disappearing one thousand times faster than the natural background rate.", "options": ["A) climate crisis", "B) mass extinction", "C) ecological collapse", "D) biodiversity shift"], "answer": "B", "explanation": "Mass extinction refers to a widespread and rapid decrease in the diversity and abundance of life on Earth."},
    {"id": 2, "sentence": "Non-native organisms introduced to an ecosystem that harm native species are called [BLANK].", "options": ["A) competitor species", "B) exotic organisms", "C) invasive species", "D) migrant species"], "answer": "C", "explanation": "Invasive species is the specific term for non-native organisms introduced to an ecosystem that cause harm."},
    {"id": 3, "sentence": "Approximately eighty percent of food crops depend on [BLANK] by insects and animals to reproduce and produce fruit.", "options": ["A) fertilisation", "B) pollination", "C) reproduction", "D) germination"], "answer": "B", "explanation": "Pollination is the transfer of pollen between plants enabling fertilisation and seed production."},
    {"id": 4, "sentence": "Biodiversity increases the [BLANK] of ecosystems, helping them recover from disturbances and continue providing services.", "options": ["A) productivity", "B) diversity", "C) resilience", "D) stability"], "answer": "C", "explanation": "Resilience is the ability of an ecosystem to recover from disturbance and maintain its function."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that biodiversity has enormous economic value through ecosystem services. Is this the most compelling reason to conserve biodiversity, or are there other equally important arguments?", "suggested_answer": "Framing biodiversity conservation in economic terms can be effective in political and business contexts where decision-makers respond to cost-benefit analysis. However, reducing nature to its monetary value has limitations. Many argue that species have intrinsic value — a right to exist regardless of their usefulness to humans. Ethical arguments for conservation based on our responsibility as stewards of the planet can be more motivating than economic calculations, which can always be challenged with different numbers. The strongest case for biodiversity conservation combines economic, ecological, aesthetic, and ethical arguments."},
    {"id": 2, "question": "The passage notes that current protected areas cover only seventeen percent of land. Scientists recommend protecting at least thirty percent. What are the main barriers to expanding protected areas?", "suggested_answer": "The main barriers are economic and political. Designating land as protected means restricting farming, logging, mining, and development — activities that generate income for local communities and tax revenue for governments. In many developing countries, people living near biodiversity hotspots are also among the poorest, and conservation must compete with immediate survival needs. Political resistance from agricultural and extractive industries is also powerful. Solutions include compensating communities for protection, developing sustainable economic alternatives, and building genuine local support for conservation rather than imposing it from outside."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 5
) AND type = 'reading';

-- ── Lesson 6 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Carbon Footprint: Individual Action and Collective Responsibility",
  "text": "A carbon footprint is the total amount of greenhouse gases — primarily carbon dioxide and methane — produced directly or indirectly by a person, organisation, or activity. Measuring carbon footprints has become a widely used tool for understanding the environmental impact of different lifestyles and consumption choices. The concept was popularised in part by oil company marketing campaigns in the early 2000s, which shifted public focus towards individual responsibility and away from corporate and systemic causes of emissions. Today, the debate about individual versus systemic action on climate change is actively contested. On one hand, individual choices genuinely matter. Food systems are responsible for around a third of global greenhouse gas emissions. Switching to a predominantly plant-based diet, reducing air travel, driving less, and choosing energy-efficient homes can significantly reduce personal emissions. Research suggests that the highest-income individuals have carbon footprints many times larger than those of people on average incomes, suggesting that targeted changes by the wealthy could have significant impact. On the other hand, critics argue that emphasising personal responsibility distracts from the systemic changes needed. Most people have limited options: they drive because there is no public transport, they eat cheap food because healthy alternatives are unaffordable, they fly because no train connection exists. Without policy changes that make low-carbon options available and affordable, individual behaviour change can only go so far. The most effective approach combines strong government policy — carbon taxes, clean energy investment, sustainable agriculture — with cultural shifts that make low-carbon choices normal and desirable. Individual action and systemic change are not alternatives but complements.",
  "glossary": [
    {"term": "carbon footprint", "definition": "the total greenhouse gas emissions caused directly or indirectly by a person or organisation", "translation": "углеродный след"},
    {"term": "methane", "definition": "a powerful greenhouse gas produced by livestock, landfills, and fossil fuel extraction", "translation": "метан"},
    {"term": "systemic", "definition": "relating to the underlying system or structure rather than individual elements", "translation": "системный"},
    {"term": "consumption", "definition": "the use of goods, services, and resources", "translation": "потребление"},
    {"term": "carbon tax", "definition": "a charge on the carbon content of fuels designed to reduce greenhouse gas emissions", "translation": "углеродный налог"},
    {"term": "predominantly", "definition": "mainly; for the most part", "translation": "преимущественно"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is a carbon footprint as defined in the passage?", "options": ["A) The area of land needed to absorb an individual's carbon emissions", "B) The total greenhouse gases produced directly or indirectly by a person or activity", "C) The amount of carbon dioxide released by burning fossil fuels", "D) A measurement of deforestation caused by consumer choices"], "answer": "B", "explanation": "A carbon footprint is the total amount of greenhouse gases produced directly or indirectly by a person, organisation, or activity."},
    {"id": 2, "question": "Who popularised the concept of carbon footprints, and why does this matter according to the passage?", "options": ["A) Environmental scientists, to help people make better choices", "B) Oil companies, partly to shift focus towards individual responsibility", "C) Governments, to encourage citizens to reduce emissions", "D) Non-governmental organisations, to raise awareness of climate change"], "answer": "B", "explanation": "The concept was popularised in part by oil company marketing campaigns that shifted focus towards individual responsibility and away from systemic causes."},
    {"id": 3, "question": "What proportion of global greenhouse gas emissions come from food systems?", "options": ["A) Around ten percent", "B) Around a fifth", "C) Around a third", "D) Around half"], "answer": "C", "explanation": "Food systems are responsible for around a third of global greenhouse gas emissions."},
    {"id": 4, "question": "What is the main argument made by critics who emphasise systemic change over individual action?", "options": ["A) Individual choices have no measurable impact on emissions", "B) Most people lack the options needed to make genuinely low-carbon choices without policy support", "C) Only the wealthiest individuals can afford to reduce their carbon footprint", "D) Government policy is always more effective than market-based solutions"], "answer": "B", "explanation": "Critics argue that most people have limited options — they drive, eat cheap food, and fly because lower-carbon alternatives are not available or affordable."},
    {"id": 5, "question": "What does the passage say about the relationship between individual action and systemic change?", "options": ["A) Individual action is more important than systemic change", "B) Systemic change is more important and individual action is irrelevant", "C) Individual action and systemic change are alternatives to be chosen between", "D) Individual action and systemic change are complements, not alternatives"], "answer": "D", "explanation": "The passage concludes that individual action and systemic change are not alternatives but complements."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "A carbon footprint measures only the direct emissions produced by a person through activities like driving.", "answer": false, "evidence": "A carbon footprint includes the total greenhouse gases produced directly OR indirectly by a person, organisation, or activity."},
    {"id": 2, "statement": "Oil companies played a role in making carbon footprints a popular concept.", "answer": true, "evidence": "The concept was popularised in part by oil company marketing campaigns in the early 2000s."},
    {"id": 3, "statement": "High-income individuals tend to have smaller carbon footprints than people on average incomes.", "answer": false, "evidence": "Research suggests that the highest-income individuals have carbon footprints many times larger than those of people on average incomes."},
    {"id": 4, "statement": "The passage argues that individual behaviour change is sufficient on its own to address climate change.", "answer": false, "evidence": "Without policy changes that make low-carbon options available and affordable, individual behaviour change can only go so far."},
    {"id": 5, "statement": "Strong government policy and cultural shifts towards low-carbon choices are described as part of the most effective approach.", "answer": true, "evidence": "The most effective approach combines strong government policy with cultural shifts that make low-carbon choices normal and desirable."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The total greenhouse gases produced by a person's activities — their [BLANK] — can be measured and compared across different lifestyles.", "options": ["A) ecological impact", "B) carbon footprint", "C) energy consumption", "D) climate contribution"], "answer": "B", "explanation": "Carbon footprint is the specific term for the total greenhouse gas emissions caused by a person or activity."},
    {"id": 2, "sentence": "Switching to a [BLANK] plant-based diet — eating mostly plants but not necessarily exclusively — can significantly reduce emissions from food.", "options": ["A) completely", "B) primarily", "C) predominantly", "D) partially"], "answer": "C", "explanation": "Predominantly means mainly or for the most part, which is the word used in the passage."},
    {"id": 3, "sentence": "Critics argue that the focus on individual responsibility distracts from the [BLANK] changes needed — changes to the underlying policies and structures.", "options": ["A) political", "B) economic", "C) systemic", "D) cultural"], "answer": "C", "explanation": "Systemic means relating to the underlying system or structure, which is what critics argue needs to change."},
    {"id": 4, "sentence": "A [BLANK] — a charge on the carbon content of fuels — is one policy tool governments can use to incentivise lower emissions.", "options": ["A) carbon tax", "B) green levy", "C) fuel surcharge", "D) climate fee"], "answer": "A", "explanation": "Carbon tax is the specific policy instrument defined in the passage as a charge on the carbon content of fuels."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage reveals that oil companies helped popularise the concept of the carbon footprint to shift blame to individuals. How does knowing this change your view of individual responsibility for climate change?", "suggested_answer": "Knowing that the carbon footprint concept was partly a corporate marketing strategy does not eliminate individual responsibility, but it does help reframe it. It shows that emphasis on personal behaviour change can be a distraction from the much larger question of who controls energy systems, agricultural practices, and industrial processes. Individuals can and should make better choices, but the structural decisions made by corporations and governments have far greater impact. Critical awareness of how responsibility is framed helps us direct our energy towards systemic change while still making the personal changes within our control."},
    {"id": 2, "question": "The passage argues that low-carbon choices are often not available or affordable for most people. Is this a reason to focus only on policy, or should individuals still try to reduce their own footprint?", "suggested_answer": "Individual action and policy change are not in competition — both are needed. Individuals who can afford to choose lower-carbon lifestyles should do so, both for direct impact and because consumer behaviour can drive market changes. However, it would be wrong to judge or burden those who lack the resources or options to make different choices. The role of policy is precisely to make better choices available and affordable to everyone, not only the privileged. Demanding policy change is itself a form of individual action that may have more systemic impact than any single lifestyle choice."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 6
) AND type = 'reading';

-- ── Lesson 7 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Youth Climate Activism: A Generation Demands Change",
  "text": "In August 2018, a fifteen-year-old Swedish student named Greta Thunberg began a school strike outside the Swedish parliament, demanding stronger government action on climate change. Within months, her solitary protest had inspired a global movement. By March 2019, more than one and a half million students in over one hundred countries had joined strikes under the banner of Fridays for Future. The movement drew attention to what many young people see as a fundamental injustice: they will live through the worst consequences of climate change caused primarily by earlier generations. Youth climate activism did not begin with Thunberg, but she gave it unprecedented global visibility. Young activists have used social media effectively to organise protests, share information, and reach audiences that traditional political organisations cannot. The visual and emotional power of young people demanding action has proven difficult for politicians to ignore, even if substantive policy responses have often been slow to follow. Critics of youth climate activism argue that young people lack the technical expertise and life experience necessary to develop effective policy solutions. Others suggest that some aspects of the movement have become counterproductive, focusing on individual guilt and emotional appeals rather than practical solutions. However, supporters argue that the political system has failed to respond adequately to decades of scientific warnings, and that urgent emotional appeals are precisely what is needed to break through political inertia. Research on social movements suggests that disruptive protest can shift public opinion and create the political conditions in which policy change becomes possible. Youth climate activism represents a continuation of a long tradition of young people challenging established power structures to demand a more just future.",
  "glossary": [
    {"term": "activism", "definition": "the use of direct and public action to achieve political or social goals", "translation": "активизм"},
    {"term": "strike", "definition": "a period of organised refusal to work or attend school as a form of protest", "translation": "забастовка"},
    {"term": "inertia", "definition": "a tendency to do nothing or to remain unchanged despite the need for action", "translation": "инерция"},
    {"term": "substantive", "definition": "having real importance, significance, or practical effect", "translation": "существенный, конкретный"},
    {"term": "injustice", "definition": "a situation where people are treated unfairly or do not receive what they deserve", "translation": "несправедливость"},
    {"term": "disruptive", "definition": "causing interruption or disturbance to the normal course of events", "translation": "разрушительный, нарушающий порядок"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "How did the Fridays for Future movement begin?", "options": ["A) Through a viral social media campaign launched by a group of activists", "B) With Greta Thunberg striking alone outside the Swedish parliament in 2018", "C) As an organised international event planned by environmental organisations", "D) With a student petition signed by millions across Europe"], "answer": "B", "explanation": "In August 2018, fifteen-year-old Greta Thunberg began a school strike outside the Swedish parliament, inspiring a global movement."},
    {"id": 2, "question": "How many students had joined climate strikes by March 2019?", "options": ["A) Around five hundred thousand", "B) Around one million", "C) More than one and a half million", "D) More than three million"], "answer": "C", "explanation": "By March 2019, more than one and a half million students in over one hundred countries had joined strikes."},
    {"id": 3, "question": "What fundamental injustice does the passage describe young climate activists as highlighting?", "options": ["A) That young people pay higher taxes than older generations", "B) That young people will live through the worst consequences of climate change caused by earlier generations", "C) That young people are excluded from formal political decision-making processes", "D) That environmental education is inadequate in schools worldwide"], "answer": "B", "explanation": "Many young people see it as a fundamental injustice that they will live through the worst consequences of climate change caused primarily by earlier generations."},
    {"id": 4, "question": "What advantage of social media does the passage mention in relation to youth activism?", "options": ["A) It allows young people to vote on policy decisions directly", "B) It makes protests more professional and better organised", "C) It enables young people to organise, share information, and reach audiences traditional politics cannot", "D) It provides funding for activist organisations through online donations"], "answer": "C", "explanation": "Young activists have used social media to organise protests, share information, and reach audiences that traditional political organisations cannot."},
    {"id": 5, "question": "What does research on social movements suggest about disruptive protest?", "options": ["A) It usually backfires by alienating the public and reducing support", "B) It can shift public opinion and create conditions in which policy change becomes possible", "C) It is only effective when supported by established political parties", "D) It works best when focused on economic arguments rather than emotional appeals"], "answer": "B", "explanation": "Research suggests that disruptive protest can shift public opinion and create the political conditions in which policy change becomes possible."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Youth climate activism began with Greta Thunberg and had no history before 2018.", "answer": false, "evidence": "Youth climate activism did not begin with Thunberg, but she gave it unprecedented global visibility."},
    {"id": 2, "statement": "Politicians found the visual power of youth climate protests difficult to ignore.", "answer": true, "evidence": "The visual and emotional power of young people demanding action has proven difficult for politicians to ignore."},
    {"id": 3, "statement": "All commentators agree that youth climate activism is effective and should be supported.", "answer": false, "evidence": "Critics argue that young people lack technical expertise, and others suggest some aspects have become counterproductive."},
    {"id": 4, "statement": "Supporters of youth activism argue that emotional appeals are appropriate given the political system has ignored scientific warnings.", "answer": true, "evidence": "Supporters argue that the political system has failed to respond adequately to decades of scientific warnings, and that urgent emotional appeals are precisely what is needed."},
    {"id": 5, "statement": "The passage presents youth climate activism as a completely new phenomenon with no connection to historical movements.", "answer": false, "evidence": "Youth climate activism represents a continuation of a long tradition of young people challenging established power structures."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Greta Thunberg began a school [BLANK] outside the Swedish parliament, refusing to attend school until the government acted on climate change.", "options": ["A) protest", "B) march", "C) strike", "D) boycott"], "answer": "C", "explanation": "Strike is the specific word used in the passage — it refers to organised refusal to work or attend school as protest."},
    {"id": 2, "sentence": "Supporters argue that urgent emotional appeals are needed to break through political [BLANK] — the tendency to do nothing despite the need for action.", "options": ["A) resistance", "B) inertia", "C) opposition", "D) indifference"], "answer": "B", "explanation": "Inertia describes a tendency to remain unchanged despite the need for action, which is the word used in the passage."},
    {"id": 3, "sentence": "Substantive policy responses to climate activism have often been slow, despite the [BLANK] importance of the actions demanded.", "options": ["A) emotional", "B) symbolic", "C) substantive", "D) political"], "answer": "C", "explanation": "Substantive means having real importance and practical effect — it describes the significance of the policy responses needed."},
    {"id": 4, "sentence": "Research suggests that [BLANK] protest — causing interruption to normal events — can shift public opinion and create conditions for policy change.", "options": ["A) violent", "B) organised", "C) disruptive", "D) peaceful"], "answer": "C", "explanation": "Disruptive is the specific word used in the passage — it describes protest that causes interruption to the normal course of events."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes a debate between critics who say young activists lack expertise and supporters who say emotional appeals are necessary. Which side do you find more persuasive, and why?", "suggested_answer": "The critics have a point that effective climate policy requires technical knowledge and political experience. However, youth activists are not claiming to design policy in detail — they are demanding that policymakers act on the scientific evidence that already exists. The argument that young people lack expertise is often used to dismiss inconvenient voices rather than to engage with their legitimate demands. History shows that social movements composed of people without formal expertise have been essential drivers of social change, from the civil rights movement to the suffragettes. Expertise and urgency both have a role to play."},
    {"id": 2, "question": "The passage notes that the Fridays for Future movement drew attention to an intergenerational injustice. How should societies handle situations where the costs of decisions fall on future generations who cannot currently vote?", "suggested_answer": "Intergenerational injustice is a genuine democratic problem. Young people and future generations will bear the costs of decisions made today, yet they have limited or no political voice. Some solutions include lowering the voting age, requiring governments to consider long-term impacts in all policy decisions, or creating official bodies representing future interests. Ultimately, the challenge is to build political systems that can look beyond election cycles and consider outcomes decades into the future. Youth activism is one way of giving a voice to future generations — through protest, young people draw attention to long-term consequences that short-term political incentives tend to ignore."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 3 AND l.order_index = 7
) AND type = 'reading';