-- ============================================================
-- B1 Intermediate / Module 4 (Money & Shopping)
-- Reading Sections — Lessons 1–7
-- Theme: Economics / Consumer Society
-- ============================================================

-- ── Lesson 1 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The History of Money: From Barter to Bitcoin",
  "text": "Money is one of the most transformative inventions in human history, yet it began simply as a solution to the inconvenience of barter. In early societies, people exchanged goods directly — a farmer might trade grain for a tool or an animal. This system had obvious limitations: both parties had to want exactly what the other had to offer, a problem economists call the double coincidence of wants. Commodity money — using valuable objects such as shells, salt, or grain as a medium of exchange — solved this problem. Eventually, metals such as gold and silver became the dominant commodity money because they were durable, portable, divisible, and relatively scarce. The minting of standardised coins by governments, beginning around 600 BCE in Lydia (modern Turkey), made trade far more efficient. Paper money emerged in China during the Tang Dynasty (618-907 CE) and reached Europe by the seventeenth century. Initially, paper money was a certificate that could be exchanged for a fixed quantity of gold or silver — a system known as the gold standard. This link was gradually severed over the twentieth century, and modern fiat currencies derive their value from government authority and public trust rather than any physical commodity. The invention of credit — borrowing money to spend now and repay later — dramatically expanded economic activity but also introduced new risks. Digital payments, online banking, and cryptocurrencies such as Bitcoin represent the latest phase in the evolution of money, enabling transactions across the world in seconds. As society becomes increasingly cashless, questions about financial inclusion — ensuring all members of society can participate in the digital economy — are becoming increasingly urgent.",
  "glossary": [
    {"term": "barter", "definition": "the direct exchange of goods or services without using money", "translation": "бартер"},
    {"term": "commodity money", "definition": "objects with intrinsic value used as a medium of exchange", "translation": "товарные деньги"},
    {"term": "fiat currency", "definition": "money that has value because a government declares it to be legal tender, not because it represents a commodity", "translation": "фиатная валюта"},
    {"term": "gold standard", "definition": "a monetary system where currency value is directly linked to a fixed amount of gold", "translation": "золотой стандарт"},
    {"term": "cryptocurrency", "definition": "a digital currency using cryptography for secure transactions without a central authority", "translation": "криптовалюта"},
    {"term": "financial inclusion", "definition": "ensuring that all people have access to useful and affordable financial products and services", "translation": "финансовая доступность"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What problem with barter does the passage describe as the double coincidence of wants?", "options": ["A) The difficulty of agreeing on a fair price for goods", "B) The need for both parties to want exactly what the other has to offer", "C) The problem of transporting heavy goods over long distances", "D) The requirement that both parties speak the same language"], "answer": "B", "explanation": "The double coincidence of wants is the problem where both parties must want exactly what the other has to offer."},
    {"id": 2, "question": "Why did gold and silver become the dominant commodity money?", "options": ["A) Because they were the most beautiful materials available", "B) Because governments declared them to be official currencies", "C) Because they were durable, portable, divisible, and relatively scarce", "D) Because they were found everywhere in large quantities"], "answer": "C", "explanation": "Metals became dominant because they were durable, portable, divisible, and relatively scarce."},
    {"id": 3, "question": "What was the gold standard?", "options": ["A) A system where gold coins were the only accepted payment", "B) A monetary system where currency value was linked to a fixed amount of gold", "C) A quality standard for gold used in jewellery and coins", "D) An international agreement to use gold as a universal currency"], "answer": "B", "explanation": "The gold standard was a system where paper money was a certificate that could be exchanged for a fixed quantity of gold or silver."},
    {"id": 4, "question": "What do modern fiat currencies derive their value from?", "options": ["A) The gold reserves held by central banks", "B) The productivity of the national economy", "C) Government authority and public trust", "D) The silver and gold content of the currency"], "answer": "C", "explanation": "Modern fiat currencies derive their value from government authority and public trust rather than any physical commodity."},
    {"id": 5, "question": "What concern about digital payments and a cashless society does the passage raise?", "options": ["A) That digital payments are too slow to support global trade", "B) That cryptocurrencies will replace all traditional currencies", "C) That financial inclusion — ensuring all can participate — becomes more urgent", "D) That governments will lose the ability to control the money supply"], "answer": "C", "explanation": "As society becomes increasingly cashless, questions about financial inclusion and ensuring all members can participate are becoming more urgent."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Barter is a more efficient system than money because it does not require trust in a government.", "answer": false, "evidence": "Barter had obvious limitations — both parties had to want exactly what the other had, a problem called the double coincidence of wants."},
    {"id": 2, "statement": "Standardised coins were first minted around 600 BCE in what is now Turkey.", "answer": true, "evidence": "The minting of standardised coins by governments, beginning around 600 BCE in Lydia (modern Turkey), made trade far more efficient."},
    {"id": 3, "statement": "Paper money was first used in Europe during the Middle Ages.", "answer": false, "evidence": "Paper money emerged in China during the Tang Dynasty (618-907 CE) and reached Europe by the seventeenth century."},
    {"id": 4, "statement": "The link between paper money and gold was maintained throughout the twentieth century.", "answer": false, "evidence": "This link was gradually severed over the twentieth century."},
    {"id": 5, "statement": "The invention of credit expanded economic activity but also introduced new risks.", "answer": true, "evidence": "The invention of credit dramatically expanded economic activity but also introduced new risks."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "In early societies, people exchanged goods directly without money — a system called [BLANK].", "options": ["A) barter", "B) trade", "C) commerce", "D) exchange"], "answer": "A", "explanation": "Barter is the specific term for the direct exchange of goods or services without using money."},
    {"id": 2, "sentence": "Paper money was initially a certificate exchangeable for a fixed quantity of gold — a system known as the [BLANK].", "options": ["A) silver standard", "B) commodity system", "C) gold standard", "D) fiat system"], "answer": "C", "explanation": "The gold standard is the monetary system where currency value was directly linked to a fixed amount of gold."},
    {"id": 3, "sentence": "Modern currencies like the US dollar are [BLANK] currencies — they have value because governments declare them legal tender, not because of any commodity backing.", "options": ["A) digital", "B) fiat", "C) credit", "D) commodity"], "answer": "B", "explanation": "Fiat currency derives its value from government authority and public trust, not from a physical commodity."},
    {"id": 4, "sentence": "Digital currencies using cryptography for secure transactions without central authority are called [BLANK].", "options": ["A) digital money", "B) e-currency", "C) cryptocurrencies", "D) virtual coins"], "answer": "C", "explanation": "Cryptocurrency is the specific term for digital currencies like Bitcoin that use cryptography and operate without a central authority."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes how money has evolved from physical commodities to digital currencies. What qualities should good money have? Does cryptocurrency meet these criteria?", "suggested_answer": "Good money should be durable, portable, divisible, scarce, and widely accepted as a medium of exchange. Cryptocurrencies like Bitcoin meet some of these criteria — they are divisible and portable — but their value is extremely volatile, which undermines their usefulness as a stable medium of exchange or store of value. They also require internet access and technical knowledge, limiting their use. Traditional currencies backed by stable governments and central banks tend to perform the functions of money more reliably for most people, though the technology underlying cryptocurrencies may eventually be applied in more stable forms."},
    {"id": 2, "question": "The passage raises the concern of financial inclusion as societies go cashless. Who is most at risk of being excluded, and what can be done to protect them?", "suggested_answer": "Those most at risk of exclusion from a cashless economy include elderly people who are less comfortable with digital technology, people living in poverty without smartphones or bank accounts, those in rural areas with poor internet connectivity, and undocumented migrants who cannot access formal banking. Solutions include maintaining cash as a legal option for payment, creating simple and free digital payment systems accessible by basic mobile phones, expanding banking access through post offices and community organisations, and providing digital literacy education to groups at risk of exclusion."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 1
) AND type = 'reading';

-- ── Lesson 2 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Rise of Consumerism: Buying More, Living Better?",
  "text": "Consumerism describes an economic and social system in which the acquisition of goods and services plays a central role in life and identity. While people have always bought and sold things, consumer culture as we know it today emerged in the twentieth century, driven by industrialisation, rising incomes, credit availability, and sophisticated advertising. The United States led this transformation. After World War Two, rising wages and the availability of consumer credit allowed millions of American families to buy homes, cars, televisions, and appliances for the first time. Manufacturers discovered that they could increase profits not simply by making better products but by making products that quickly became unfashionable or obsolete — a practice known as planned obsolescence. Advertising became a major industry dedicated to creating desire for things people had not previously known they needed. Consumer culture spread globally through the second half of the twentieth century, particularly accelerating after the end of the Cold War as previously restricted markets opened. Today, global consumption has reached levels that many economists and environmentalists consider unsustainable. The extraction of raw materials, the energy required for manufacturing and transportation, and the disposal of waste all place enormous pressure on natural systems. The fashion industry alone produces around ten percent of global carbon emissions. Critics of consumerism argue that beyond a certain level of comfort, additional consumption does not increase happiness or life satisfaction. Research in psychology consistently finds that experiences, social connections, and purpose contribute more to wellbeing than material possessions. Sustainable consumption — buying fewer, better-quality goods that last longer — is increasingly promoted as both an environmental and personal health imperative.",
  "glossary": [
    {"term": "consumerism", "definition": "a social and economic order encouraging the purchase of goods and services in ever-greater amounts", "translation": "консьюмеризм, потребительство"},
    {"term": "planned obsolescence", "definition": "the deliberate design of products to become outdated or unusable within a short period", "translation": "запланированное устаревание"},
    {"term": "acquisition", "definition": "the act of obtaining or buying something", "translation": "приобретение"},
    {"term": "obsolete", "definition": "no longer used or needed because something newer or better has replaced it", "translation": "устаревший"},
    {"term": "sustainable consumption", "definition": "using goods and services in a way that meets current needs without compromising future generations", "translation": "устойчивое потребление"},
    {"term": "wellbeing", "definition": "the state of being comfortable, healthy, and happy", "translation": "благополучие"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is consumerism as described in the passage?", "options": ["A) A system that prioritises saving money over spending it", "B) An economic and social system where acquiring goods is central to life and identity", "C) A government policy of subsidising consumer products", "D) The practice of buying only essential goods and services"], "answer": "B", "explanation": "Consumerism describes an economic and social system in which the acquisition of goods and services plays a central role in life and identity."},
    {"id": 2, "question": "What is planned obsolescence?", "options": ["A) A government programme to update public infrastructure", "B) The natural ageing and breakdown of products over time", "C) The deliberate design of products to become outdated quickly", "D) A marketing strategy to promote new products through advertising"], "answer": "C", "explanation": "Planned obsolescence is the practice of making products that quickly become unfashionable or obsolete to drive repeat purchases."},
    {"id": 3, "question": "What did manufacturers discover about increasing profits?", "options": ["A) Making better products always generates more profit", "B) Reducing prices attracts more customers than improving quality", "C) Making products that quickly become obsolete increases repeat purchases", "D) Advertising is less effective than word-of-mouth recommendation"], "answer": "C", "explanation": "Manufacturers discovered they could increase profits by making products that quickly became unfashionable or obsolete."},
    {"id": 4, "question": "What does research in psychology find about material possessions and happiness?", "options": ["A) More possessions consistently lead to greater happiness", "B) Experiences, connections, and purpose contribute more to wellbeing than possessions", "C) The relationship between possessions and happiness is the same across all cultures", "D) Only luxury goods contribute significantly to life satisfaction"], "answer": "B", "explanation": "Research consistently finds that experiences, social connections, and purpose contribute more to wellbeing than material possessions."},
    {"id": 5, "question": "What percentage of global carbon emissions does the fashion industry produce?", "options": ["A) Around two percent", "B) Around five percent", "C) Around ten percent", "D) Around fifteen percent"], "answer": "C", "explanation": "The fashion industry alone produces around ten percent of global carbon emissions."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Consumer culture as we know it today has existed throughout all of human history.", "answer": false, "evidence": "Consumer culture as we know it today emerged in the twentieth century, driven by industrialisation, rising incomes, and advertising."},
    {"id": 2, "statement": "After World War Two, rising wages and consumer credit allowed American families to buy homes and appliances for the first time.", "answer": true, "evidence": "Rising wages and the availability of consumer credit allowed millions of American families to buy homes, cars, televisions, and appliances for the first time."},
    {"id": 3, "statement": "Global consumption has reached levels considered sustainable by most economists and environmentalists.", "answer": false, "evidence": "Today, global consumption has reached levels that many economists and environmentalists consider unsustainable."},
    {"id": 4, "statement": "Advertising was developed specifically to create desire for things people had not previously needed.", "answer": true, "evidence": "Advertising became a major industry dedicated to creating desire for things people had not previously known they needed."},
    {"id": 5, "statement": "Research consistently shows that buying more possessions is the most reliable path to happiness.", "answer": false, "evidence": "Research consistently finds that experiences, social connections, and purpose contribute more to wellbeing than material possessions."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The economic and social system where the [BLANK] of goods is central to identity and daily life is called consumerism.", "options": ["A) production", "B) acquisition", "C) distribution", "D) regulation"], "answer": "B", "explanation": "Acquisition — the act of obtaining or buying something — is the word used in the passage's definition of consumerism."},
    {"id": 2, "sentence": "Manufacturers designed products to become quickly [BLANK] — no longer useful or fashionable — so customers would buy replacements sooner.", "options": ["A) expensive", "B) recyclable", "C) obsolete", "D) defective"], "answer": "C", "explanation": "Obsolete means no longer used or needed because something newer has replaced it."},
    {"id": 3, "sentence": "The practice of designing products to break or go out of fashion quickly is called planned [BLANK].", "options": ["A) consumption", "B) production", "C) obsolescence", "D) replacement"], "answer": "C", "explanation": "Planned obsolescence is the deliberate design of products to become outdated or unusable quickly."},
    {"id": 4, "sentence": "Buying fewer, better-quality goods that last longer is promoted as [BLANK] consumption — meeting needs without harming future generations.", "options": ["A) minimal", "B) responsible", "C) sustainable", "D) ethical"], "answer": "C", "explanation": "Sustainable consumption means using goods in a way that meets current needs without compromising future generations."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes planned obsolescence as a deliberate business strategy. Is this ethical? Should it be regulated or banned?", "suggested_answer": "Planned obsolescence raises genuine ethical concerns. Designing products to fail prematurely wastes resources, contributes to pollution, and financially exploits consumers by forcing unnecessary repeat purchases. It is particularly harmful in the context of the current environmental crisis, where extending the lifespan of products is essential for reducing waste and emissions. Regulating it — by requiring minimum product lifespans, mandating repairability, or banning software designed to degrade older devices — seems justified. Right-to-repair laws, which require manufacturers to provide spare parts and instructions, are one practical step already being taken in several countries."},
    {"id": 2, "question": "The passage suggests that beyond a certain level of comfort, consumption does not increase happiness. Why do people continue buying more if it does not make them happier?", "suggested_answer": "Several psychological mechanisms explain this gap between expectation and reality. Advertising is highly effective at creating aspirational desire, making us believe that the next purchase will finally satisfy us. Social comparison — comparing ourselves to neighbours, peers, or media images — drives consumption as a form of status signalling. Habit and routine make familiar consumption patterns feel normal and necessary. There is also genuine pleasure in the act of purchasing itself, which fades quickly once the item is owned — a phenomenon psychologists call hedonic adaptation. Understanding these mechanisms does not automatically change behaviour, but it can help people make more intentional choices."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 2
) AND type = 'reading';

-- ── Lesson 3 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Psychology of Advertising: How Brands Shape Decisions",
  "text": "Advertising is a multi-trillion dollar global industry whose purpose is to influence consumer behaviour. Modern advertising has moved far beyond simply informing people about products. It draws on psychology, neuroscience, data analysis, and behavioural economics to shape perceptions, create emotional associations, and influence decisions in ways that consumers often do not consciously recognise. One of the most powerful techniques is emotional branding. Rather than describing what a product does, advertisers create a lifestyle, feeling, or identity that the product represents. A sports drink does not just quench thirst — it represents athletic achievement and a healthy, active life. A luxury car is not simply transport — it signals success, taste, and social status. By associating products with aspirational identities, advertisers make purchasing feel like a step towards becoming the person you want to be. Social proof is another key psychological mechanism. People tend to follow the behaviour of others, particularly in uncertain situations. Advertisers exploit this through testimonials, celebrity endorsements, and statistics about how many millions of people use their product. The fear of missing out — sometimes called FOMO — is a related technique, creating urgency by suggesting that a deal is limited or that others are already benefiting. Digital advertising has made these techniques far more precise. Through data collected from social media, search engines, and online behaviour, advertisers can target individuals with messages specifically designed for their particular psychology, interests, and vulnerabilities. Critics argue that this level of personalised targeting, particularly directed at children and vulnerable individuals, raises serious ethical concerns about manipulation and consent. Media literacy — the ability to critically analyse and evaluate advertising messages — is increasingly regarded as an essential life skill.",
  "glossary": [
    {"term": "emotional branding", "definition": "a strategy of creating emotional associations between a product and a desired identity or feeling", "translation": "эмоциональный брендинг"},
    {"term": "social proof", "definition": "the tendency to follow the behaviour of others, used in advertising through testimonials and endorsements", "translation": "социальное доказательство"},
    {"term": "testimonial", "definition": "a statement by a customer or celebrity recommending a product", "translation": "отзыв, рекомендация"},
    {"term": "FOMO", "definition": "fear of missing out — anxiety that others are having rewarding experiences that you are not", "translation": "страх упустить что-то"},
    {"term": "media literacy", "definition": "the ability to critically analyse and evaluate media messages and advertising", "translation": "медиаграмотность"},
    {"term": "targeting", "definition": "the practice of directing advertising at specific individuals based on their characteristics and behaviour", "translation": "таргетирование"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is the purpose of emotional branding according to the passage?", "options": ["A) To describe the features and price of a product accurately", "B) To associate products with aspirational identities and feelings", "C) To compare a product favourably with its competitors", "D) To explain how a product is manufactured and tested"], "answer": "B", "explanation": "Emotional branding creates a lifestyle, feeling, or identity that the product represents, making purchasing feel like a step towards becoming who you want to be."},
    {"id": 2, "question": "What is social proof and how is it used in advertising?", "options": ["A) Evidence from scientific studies that a product is effective", "B) The tendency to follow others' behaviour, exploited through testimonials and endorsements", "C) A legal requirement to provide honest reviews of products", "D) A technique of comparing prices to show value"], "answer": "B", "explanation": "Social proof is the tendency to follow the behaviour of others, which advertisers exploit through testimonials, celebrity endorsements, and popularity statistics."},
    {"id": 3, "question": "What is FOMO as described in the passage?", "options": ["A) A technique for collecting consumer data through social media", "B) The fear of missing out, used to create urgency in advertising", "C) A psychological term for addiction to online shopping", "D) A form of targeted advertising based on personal data"], "answer": "B", "explanation": "FOMO — fear of missing out — is used to create urgency by suggesting that a deal is limited or others are already benefiting."},
    {"id": 4, "question": "How has digital advertising changed the use of psychological techniques?", "options": ["A) It has made advertising less personal and more generic", "B) It has reduced the effectiveness of emotional branding", "C) It allows precise targeting based on individual psychology, interests, and vulnerabilities", "D) It has made advertising less expensive and more ethical"], "answer": "C", "explanation": "Through data collected online, advertisers can target individuals with messages specifically designed for their particular psychology and vulnerabilities."},
    {"id": 5, "question": "What does the passage describe as an essential life skill?", "options": ["A) The ability to distinguish between good and bad advertising", "B) The ability to resist all forms of consumer marketing", "C) Media literacy — the ability to critically analyse advertising messages", "D) Understanding the legal regulations governing advertising"], "answer": "C", "explanation": "Media literacy — the ability to critically analyse and evaluate advertising messages — is increasingly regarded as an essential life skill."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Modern advertising focuses primarily on providing factual information about product features.", "answer": false, "evidence": "Modern advertising has moved far beyond simply informing people about products — it creates emotional associations and influences decisions."},
    {"id": 2, "statement": "A luxury car advertisement is described in the passage as representing success and social status.", "answer": true, "evidence": "A luxury car is not simply transport — it signals success, taste, and social status."},
    {"id": 3, "statement": "Digital advertising targets all consumers with the same general message.", "answer": false, "evidence": "Advertisers can target individuals with messages specifically designed for their particular psychology, interests, and vulnerabilities."},
    {"id": 4, "statement": "Celebrity endorsements and testimonials are examples of social proof.", "answer": true, "evidence": "Advertisers exploit social proof through testimonials, celebrity endorsements, and statistics about how many millions use their product."},
    {"id": 5, "statement": "The passage argues that targeted advertising directed at children and vulnerable people raises no ethical concerns.", "answer": false, "evidence": "Critics argue that personalised targeting, particularly directed at children and vulnerable individuals, raises serious ethical concerns about manipulation and consent."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Rather than describing a product, advertisers use [BLANK] to create emotional associations — making a sports drink represent athletic achievement.", "options": ["A) celebrity marketing", "B) emotional branding", "C) product placement", "D) targeted advertising"], "answer": "B", "explanation": "Emotional branding is the strategy of associating products with desired identities, feelings, and lifestyles."},
    {"id": 2, "sentence": "Advertisers use customer reviews, celebrity [BLANK], and popularity statistics to show that many people already trust and use their product.", "options": ["A) endorsements", "B) recommendations", "C) testimonials", "D) profiles"], "answer": "C", "explanation": "Testimonials are statements by customers or celebrities recommending a product, which is the specific word used in the passage."},
    {"id": 3, "sentence": "The anxiety that others are having rewarding experiences that you are missing — known as [BLANK] — is exploited to create urgency in advertising.", "options": ["A) peer pressure", "B) FOMO", "C) social anxiety", "D) consumer anxiety"], "answer": "B", "explanation": "FOMO stands for fear of missing out and is used by advertisers to make consumers act quickly."},
    {"id": 4, "sentence": "The ability to critically analyse and evaluate advertising messages is called [BLANK] and is increasingly considered an essential skill.", "options": ["A) consumer rights", "B) critical thinking", "C) media literacy", "D) digital awareness"], "answer": "C", "explanation": "Media literacy is the specific term used in the passage for the ability to analyse and evaluate media messages and advertising."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage raises concerns about targeted advertising directed at children. Should advertising to children be regulated more strictly or banned entirely? Give reasons.", "suggested_answer": "There are strong arguments for stricter regulation. Children have developing critical thinking skills and are particularly susceptible to emotional and aspirational appeals in advertising. They are also less able to recognise when they are being manipulated. Several countries have restricted advertising to children, particularly for junk food and toys. A complete ban would be difficult to enforce in the digital age, but clear restrictions on targeting children with personalised advertising based on data collection, combined with mandatory media literacy education, would be a more proportionate and practical approach than a complete prohibition."},
    {"id": 2, "question": "The passage argues that consumers are often influenced by advertising without consciously recognising it. Does this knowledge change how you think about your own purchasing decisions? What can individuals do to become more aware consumers?", "suggested_answer": "Awareness of advertising psychology can help people make more intentional choices, but it does not make us immune to its effects. Even people who know about social proof or emotional branding are still influenced by them, because these mechanisms operate partly at a subconscious level. Practical steps towards more aware consumption include waiting before purchasing to reduce impulse buying, questioning what emotional need a product is supposed to meet, and distinguishing between wants created by advertising and genuine needs. Developing media literacy — actively analysing rather than passively absorbing advertising — is the most effective long-term defence."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 3
) AND type = 'reading';

-- ── Lesson 4 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Online Shopping Revolution",
  "text": "The rise of e-commerce — buying and selling goods and services through the internet — has fundamentally transformed retail globally. In 1995, Amazon launched as an online bookstore. By 2023, it had become one of the most valuable companies in the world, selling almost everything imaginable, and online retail accounts for more than twenty percent of all retail sales in many developed countries. The convenience of online shopping is undeniable. Consumers can browse millions of products, read reviews, compare prices, and make purchases at any hour from any location with internet access. Delivery services have become faster — same-day or next-day delivery is now standard in many urban areas. Subscription services offer regular delivery of food, household products, and entertainment, reducing the need for planned shopping trips. However, the online retail revolution has had significant consequences for traditional high-street shops and city centres. Many large retailers, including long-established department stores and clothing chains, have closed hundreds of branches or gone out of business entirely as customer traffic moved online. City centres that once thrived on retail have been forced to reinvent themselves, converting empty shop spaces into residential units, entertainment venues, and community facilities. The environmental impact of e-commerce is complex. While physical retail requires energy-consuming buildings, online delivery creates its own emissions through the transportation of individual packages. The growth of packaging waste and the emissions from delivery vehicles represent significant challenges. Returns — which online shoppers make far more frequently than in-store shoppers — generate additional transportation emissions and waste. Meanwhile, gig economy workers who drive for delivery companies often face insecure employment, low pay, and minimal legal protections, raising serious questions about who bears the social costs of retail convenience.",
  "glossary": [
    {"term": "e-commerce", "definition": "the buying and selling of goods and services over the internet", "translation": "электронная коммерция"},
    {"term": "retail", "definition": "the sale of goods directly to consumers, typically in small quantities", "translation": "розничная торговля"},
    {"term": "subscription service", "definition": "a service providing regular delivery of products or access to content in exchange for periodic payment", "translation": "подписка"},
    {"term": "high street", "definition": "the main shopping street in a town or city; used to refer to traditional retail shops", "translation": "главная торговая улица"},
    {"term": "gig economy", "definition": "a labour market characterised by short-term contracts and freelance work rather than permanent employment", "translation": "гиг-экономика"},
    {"term": "returns", "definition": "goods sent back to the seller by the customer after purchase", "translation": "возврат товара"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What was Amazon when it launched in 1995?", "options": ["A) A cloud computing company", "B) A digital payment platform", "C) An online bookstore", "D) A streaming entertainment service"], "answer": "C", "explanation": "Amazon launched in 1995 as an online bookstore before expanding into selling almost everything."},
    {"id": 2, "question": "What proportion of all retail sales does online shopping account for in many developed countries?", "options": ["A) Around five percent", "B) Around ten percent", "C) Around fifteen percent", "D) More than twenty percent"], "answer": "D", "explanation": "Online retail accounts for more than twenty percent of all retail sales in many developed countries."},
    {"id": 3, "question": "What has happened to many traditional high-street retailers as online shopping has grown?", "options": ["A) They have expanded by adding online sales channels", "B) They have reduced prices to compete with online retailers", "C) Many have closed branches or gone out of business entirely", "D) They have focused on luxury goods not available online"], "answer": "C", "explanation": "Many large retailers have closed hundreds of branches or gone out of business entirely as customer traffic moved online."},
    {"id": 4, "question": "What does the passage say about online returns compared to in-store returns?", "options": ["A) Online returns are less common than in-store returns", "B) Online shoppers make returns far more frequently than in-store shoppers", "C) Returns have no significant environmental impact", "D) Retailers have solved the returns problem through improved sizing technology"], "answer": "B", "explanation": "Online shoppers make returns far more frequently than in-store shoppers, generating additional transportation emissions and waste."},
    {"id": 5, "question": "What concern does the passage raise about gig economy delivery workers?", "options": ["A) They earn too much compared to traditional retail workers", "B) There are not enough of them to meet demand", "C) They often face insecure employment, low pay, and minimal legal protections", "D) They contribute significantly to traffic congestion in cities"], "answer": "C", "explanation": "Gig economy delivery workers often face insecure employment, low pay, and minimal legal protections."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Amazon was originally founded as a company selling a wide range of consumer products.", "answer": false, "evidence": "Amazon launched as an online bookstore in 1995 before expanding."},
    {"id": 2, "statement": "Online shopping allows consumers to browse and purchase at any time from any location with internet access.", "answer": true, "evidence": "Consumers can make purchases at any hour from any location with internet access."},
    {"id": 3, "statement": "City centres affected by the decline of retail have made no effort to adapt their empty shop spaces.", "answer": false, "evidence": "City centres have been forced to reinvent themselves, converting empty shop spaces into residential units, entertainment venues, and community facilities."},
    {"id": 4, "statement": "E-commerce has no environmental impact because it eliminates the need for large retail buildings.", "answer": false, "evidence": "The growth of packaging waste and the emissions from delivery vehicles represent significant challenges."},
    {"id": 5, "statement": "Returns from online shopping generate additional environmental costs through transportation and waste.", "answer": true, "evidence": "Returns generate additional transportation emissions and waste."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The buying and selling of goods over the internet — known as [BLANK] — has transformed retail globally since the 1990s.", "options": ["A) digital commerce", "B) e-commerce", "C) online retail", "D) internet trading"], "answer": "B", "explanation": "E-commerce is the specific term for buying and selling goods and services through the internet."},
    {"id": 2, "sentence": "Many long-established department stores have closed as [BLANK] sales have declined dramatically due to online competition.", "options": ["A) luxury", "B) high-street", "C) traditional", "D) physical"], "answer": "B", "explanation": "High street refers to traditional retail shops in town centres, which have declined as online shopping has grown."},
    {"id": 3, "sentence": "Companies offering regular delivery of household products in exchange for periodic payment use a [BLANK] model.", "options": ["A) subscription service", "B) delivery programme", "C) loyalty scheme", "D) membership plan"], "answer": "A", "explanation": "Subscription service describes the model of regular delivery in exchange for periodic payment."},
    {"id": 4, "sentence": "Delivery drivers working for short-term contracts without employment security are part of what is called the [BLANK].", "options": ["A) informal economy", "B) service industry", "C) gig economy", "D) digital workforce"], "answer": "C", "explanation": "The gig economy refers to work characterised by short-term contracts and freelance arrangements rather than permanent employment."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes both the convenience of online shopping and its negative consequences. On balance, is the rise of e-commerce good or bad for society? Give reasons.", "suggested_answer": "E-commerce brings genuine benefits: greater choice, lower prices, and convenience that saves time and improves access for people in rural areas or with limited mobility. However, the social costs are significant — the decline of high streets creates dead city centres that were previously social and community spaces, gig economy workers are exploited, and environmental costs of packaging and delivery are substantial. Whether the balance is positive depends partly on whether these costs are properly regulated and distributed. Currently, the convenience benefits flow mainly to consumers, while social and environmental costs are borne by workers and communities who receive little compensation."},
    {"id": 2, "question": "The passage raises concerns about gig economy workers who deliver online purchases. Should they be classified as employees rather than independent contractors? What are the arguments on both sides?", "suggested_answer": "Classifying delivery workers as employees would entitle them to minimum wage, sick pay, holiday pay, and legal protections. The argument for this classification is strong — many gig workers have limited freedom to work for competitors, follow strict company algorithms, and depend on a single platform for their income. The argument against is that employee status would raise costs for platforms, potentially reducing job opportunities, and that some workers genuinely value the flexibility of independent contracting. The most equitable solution may be an intermediate category — guaranteeing basic protections like minimum pay and accident insurance without requiring the full employment relationship."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 4
) AND type = 'reading';

-- ── Lesson 5 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Fair Trade and Ethical Consumption",
  "text": "The fair trade movement emerged in the 1960s and 1970s as a response to concerns about the exploitation of producers in developing countries by global supply chains. Conventional commodity trade — particularly in products like coffee, cocoa, bananas, and cotton — has historically generated enormous profits for large corporations and retailers in wealthy countries while leaving farmers and workers in producing countries with minimal income, often below the cost of production. Fair trade organisations such as Fairtrade International certify products that meet standards for fair minimum prices, safe working conditions, environmental protection, and community investment. Consumers who buy certified fair trade products pay a small premium, a portion of which goes directly to producer cooperatives to invest in schools, healthcare, and infrastructure. The fair trade market has grown significantly. Fair trade certified products are now available in supermarkets worldwide, and major retailers have made fair trade commitments for key products like coffee and cocoa. However, critics have raised questions about the effectiveness of fair trade certification. Some research suggests that the benefits reach only a small proportion of workers in supply chains and that farmers in fair trade cooperatives do not always receive significantly higher incomes than non-certified farmers. Others argue that the system is primarily a marketing tool that allows consumers in wealthy countries to feel good about their purchases without requiring fundamental changes to trade structures. More radical approaches to ethical consumption argue that individual purchasing decisions, however well-intentioned, cannot substitute for systemic changes such as reforming international trade rules, ending agricultural subsidies that disadvantage developing country farmers, and ensuring that corporations operating globally are held accountable for the conditions in their entire supply chain.",
  "glossary": [
    {"term": "fair trade", "definition": "a trading partnership aiming to achieve greater equity for producers in developing countries", "translation": "справедливая торговля"},
    {"term": "cooperative", "definition": "a business or organisation owned and run jointly by its members for their mutual benefit", "translation": "кооператив"},
    {"term": "premium", "definition": "an additional amount paid above the standard price, often to ensure higher quality or ethical standards", "translation": "надбавка, премия"},
    {"term": "certification", "definition": "the process of officially confirming that something meets required standards", "translation": "сертификация"},
    {"term": "subsidy", "definition": "money paid by a government to support an industry or reduce costs for producers or consumers", "translation": "субсидия"},
    {"term": "accountability", "definition": "the fact of being responsible for actions and required to explain them", "translation": "подотчётность, ответственность"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "Why did the fair trade movement emerge according to the passage?", "options": ["A) To promote environmentally friendly farming practices worldwide", "B) As a response to concerns about the exploitation of producers in developing countries", "C) To create new markets for luxury products from poor countries", "D) To reduce the cost of imported goods for consumers in wealthy countries"], "answer": "B", "explanation": "The fair trade movement emerged as a response to concerns about the exploitation of producers in developing countries by global supply chains."},
    {"id": 2, "question": "What do fair trade certification standards require?", "options": ["A) Products must be made exclusively in developing countries", "B) Companies must donate ten percent of profits to charity", "C) Fair minimum prices, safe working conditions, environmental protection, and community investment", "D) Products must be produced using only organic farming methods"], "answer": "C", "explanation": "Fair trade standards cover fair minimum prices, safe working conditions, environmental protection, and community investment."},
    {"id": 3, "question": "How is the fair trade premium used according to the passage?", "options": ["A) It goes directly to individual farmers as higher wages", "B) It funds research into more productive farming techniques", "C) A portion goes to producer cooperatives to invest in schools, healthcare, and infrastructure", "D) It is used to cover the cost of certification and inspection"], "answer": "C", "explanation": "A portion of the premium goes directly to producer cooperatives to invest in schools, healthcare, and infrastructure."},
    {"id": 4, "question": "What criticism of fair trade certification does the passage mention?", "options": ["A) It raises consumer prices so much that demand falls significantly", "B) It only covers luxury products rather than essential goods", "C) Benefits may reach only a small proportion of supply chain workers and may primarily serve as a marketing tool", "D) Certification is controlled by large corporations that undermine its standards"], "answer": "C", "explanation": "Critics argue that benefits reach only a small proportion of workers and that fair trade is primarily a marketing tool allowing consumers to feel good without fundamental change."},
    {"id": 5, "question": "What does the passage describe as a more radical approach to ethical consumption?", "options": ["A) Refusing to buy any products made in developing countries", "B) Requiring all companies to obtain fair trade certification", "C) Systemic changes to international trade rules and corporate accountability", "D) Creating consumer cooperatives that buy directly from farmers"], "answer": "C", "explanation": "More radical approaches argue for systemic changes such as reforming trade rules and ensuring corporations are accountable for their entire supply chain."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Conventional coffee and cocoa trade has historically provided high incomes to farmers in producing countries.", "answer": false, "evidence": "Conventional commodity trade has historically left farmers and workers in producing countries with minimal income, often below the cost of production."},
    {"id": 2, "statement": "Fair trade certified products are now available in supermarkets worldwide.", "answer": true, "evidence": "Fair trade certified products are now available in supermarkets worldwide."},
    {"id": 3, "statement": "All research confirms that fair trade farmers receive significantly higher incomes than non-certified farmers.", "answer": false, "evidence": "Some research suggests that farmers in fair trade cooperatives do not always receive significantly higher incomes than non-certified farmers."},
    {"id": 4, "statement": "The passage suggests that individual purchasing decisions alone are sufficient to transform international trade structures.", "answer": false, "evidence": "Individual purchasing decisions, however well-intentioned, cannot substitute for systemic changes such as reforming international trade rules."},
    {"id": 5, "statement": "Agricultural subsidies in wealthy countries can disadvantage developing country farmers.", "answer": true, "evidence": "More radical approaches argue for ending agricultural subsidies that disadvantage developing country farmers."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Farmers in fair trade [BLANK] — organisations owned and run jointly by their members — can invest the premium in community projects.", "options": ["A) partnerships", "B) associations", "C) cooperatives", "D) companies"], "answer": "C", "explanation": "Cooperatives are businesses or organisations owned and run jointly by their members for mutual benefit."},
    {"id": 2, "sentence": "Consumers pay a small [BLANK] above the standard price for fair trade products, part of which supports producer communities.", "options": ["A) fee", "B) premium", "C) charge", "D) surcharge"], "answer": "B", "explanation": "Premium is the additional amount paid above the standard price for fair trade products."},
    {"id": 3, "sentence": "The process of officially confirming that a product meets fair trade standards is called [BLANK].", "options": ["A) verification", "B) auditing", "C) inspection", "D) certification"], "answer": "D", "explanation": "Certification is the process of officially confirming that something meets required standards."},
    {"id": 4, "sentence": "Governments pay [BLANK] to support domestic farmers, which can make it harder for developing country farmers to compete on world markets.", "options": ["A) grants", "B) subsidies", "C) benefits", "D) allowances"], "answer": "B", "explanation": "Subsidies are money paid by a government to support an industry or reduce costs — agricultural subsidies in wealthy countries can disadvantage developing country producers."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes fair trade as potentially a marketing tool rather than a fundamental solution. Is it better to support an imperfect system like fair trade or to wait for systemic change? Give your view.", "suggested_answer": "Supporting fair trade, even imperfectly, generates immediate improvements for some producers and builds consumer awareness of supply chain issues. Waiting for systemic change while doing nothing benefits no one. However, the risk is that buying fair trade satisfies the conscience without creating pressure for more significant reform. The most effective approach is to support fair trade as a partial measure while also advocating for stronger international trade rules, corporate accountability, and an end to subsidies that harm developing country producers. Individual action and systemic change are not alternatives — they complement each other."},
    {"id": 2, "question": "Should corporations operating globally be held legally accountable for conditions throughout their entire supply chain? What are the arguments for and against?", "suggested_answer": "The argument for holding corporations accountable throughout their supply chain is compelling. When a company profits from cheap labour in unsafe conditions by subcontracting to third parties, it is effectively benefiting from exploitation while avoiding responsibility for it. Supply chain accountability laws, such as those requiring human rights due diligence, make this responsibility explicit. The argument against is the practical difficulty of monitoring complex global supply chains and the potential that strict standards could push companies to source from fewer, more easily monitored suppliers, reducing opportunities for smaller producers. The goal should be meaningful accountability, not simply compliance theatre that adds bureaucracy without improving conditions."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 5
) AND type = 'reading';

-- ── Lesson 6 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Sharing Economy: Ownership vs Access",
  "text": "The sharing economy refers to a model of economic activity in which individuals share access to goods and services, typically facilitated by digital platforms. Companies such as Airbnb, which allows homeowners to rent out their properties to travellers, and Uber, which connects drivers with passengers, are among the most prominent examples. The sharing economy has grown enormously since the late 2000s, with total revenues in key sectors estimated in the hundreds of billions of dollars globally. Proponents argue that the sharing economy makes more efficient use of existing resources. Privately owned cars, for example, are stationary for approximately ninety-five percent of their lifespan. Sharing platforms allow these underutilised assets to generate economic value for their owners while providing convenient services for others. Property rental platforms allow homeowners to earn income from spare rooms or holiday properties. The environmental argument for sharing is that fewer goods need to be manufactured if more people share access to them. Critics, however, raise significant concerns. Short-term property rentals through platforms like Airbnb have been linked to rising housing costs in many cities, as landlords convert long-term rental properties to more profitable short-term lets. This reduces housing supply for permanent residents and contributes to affordability crises in popular cities. Ride-hailing services have been associated with increased urban congestion and adverse effects on traditional taxi industries. The gig workers who power these platforms often lack the employment protections and benefits that traditional employees receive. Increasingly, cities and governments are regulating sharing economy platforms, imposing limits on short-term rentals, requiring licensing of drivers, and demanding that platforms contribute to social security systems for their workers. The debate about the sharing economy reflects broader questions about how digital platforms should be governed in the public interest.",
  "glossary": [
    {"term": "sharing economy", "definition": "an economic model where goods and services are shared between individuals via digital platforms", "translation": "экономика совместного потребления"},
    {"term": "platform", "definition": "a digital service that connects buyers and sellers or providers and users", "translation": "платформа"},
    {"term": "underutilised", "definition": "not used to its full potential or capacity", "translation": "недостаточно используемый"},
    {"term": "short-term rental", "definition": "renting a property for a brief period, typically through online platforms like Airbnb", "translation": "краткосрочная аренда"},
    {"term": "congestion", "definition": "a situation where roads are so full of vehicles that movement is slowed or blocked", "translation": "пробки, заторы"},
    {"term": "gig workers", "definition": "people employed on short-term contracts or as independent contractors through digital platforms", "translation": "работники гиг-экономики"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is the sharing economy as described in the passage?", "options": ["A) A government programme to provide free services to low-income households", "B) An economic model where individuals share access to goods via digital platforms", "C) A cooperative system where businesses share profits with their employees", "D) An environmental initiative to reduce consumption by sharing ownership of goods"], "answer": "B", "explanation": "The sharing economy refers to a model of economic activity in which individuals share access to goods and services, facilitated by digital platforms."},
    {"id": 2, "question": "What percentage of their lifespan are privately owned cars stationary according to the passage?", "options": ["A) Around fifty percent", "B) Around seventy percent", "C) Around eighty percent", "D) Approximately ninety-five percent"], "answer": "D", "explanation": "Privately owned cars are stationary for approximately ninety-five percent of their lifespan."},
    {"id": 3, "question": "What problem has Airbnb been linked to in many cities?", "options": ["A) Reduced tourism and lower hotel occupancy rates", "B) Rising housing costs as landlords convert long-term rentals to short-term lets", "C) Increased noise and disturbance in residential neighbourhoods", "D) A decline in hotel standards due to reduced competition"], "answer": "B", "explanation": "Short-term property rentals have been linked to rising housing costs as landlords convert long-term rentals to more profitable short-term lets."},
    {"id": 4, "question": "What concerns about gig workers does the passage raise?", "options": ["A) They earn too much compared to traditional employees", "B) They lack the employment protections and benefits that traditional employees receive", "C) They create unfair competition for traditional taxi and hotel industries", "D) They pay too little tax on their income from platforms"], "answer": "B", "explanation": "Gig workers often lack the employment protections and benefits that traditional employees receive."},
    {"id": 5, "question": "How are governments responding to the growth of sharing economy platforms?", "options": ["A) By banning them entirely in most countries", "B) By providing tax incentives to encourage their growth", "C) By regulating them through licensing, rental limits, and social security contributions", "D) By creating government-owned alternatives to compete with private platforms"], "answer": "C", "explanation": "Cities and governments are imposing limits on short-term rentals, requiring licensing, and demanding social security contributions."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The sharing economy became significant in the 2000s, driven by digital platforms connecting users and providers.", "answer": true, "evidence": "The sharing economy has grown enormously since the late 2000s."},
    {"id": 2, "statement": "Sharing economy platforms make more efficient use of existing resources that would otherwise sit idle.", "answer": true, "evidence": "Sharing platforms allow underutilised assets to generate economic value while providing convenient services for others."},
    {"id": 3, "statement": "Short-term rental platforms have reduced housing costs in most cities by increasing the supply of accommodation.", "answer": false, "evidence": "Short-term property rentals have been linked to rising housing costs in many cities, reducing housing supply for permanent residents."},
    {"id": 4, "statement": "Ride-hailing services have reduced congestion in cities by replacing private car journeys.", "answer": false, "evidence": "Ride-hailing services have been associated with increased urban congestion."},
    {"id": 5, "statement": "The debate about the sharing economy reflects broader questions about how digital platforms should be governed in the public interest.", "answer": true, "evidence": "The debate about the sharing economy reflects broader questions about how digital platforms should be governed in the public interest."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Airbnb and Uber are digital [BLANK] that connect homeowners and drivers with travellers and passengers.", "options": ["A) marketplaces", "B) networks", "C) platforms", "D) systems"], "answer": "C", "explanation": "Platform is the specific term used in the passage for the digital services that connect providers and users."},
    {"id": 2, "sentence": "Cars sit unused for ninety-five percent of their life — they are highly [BLANK] assets that sharing platforms can activate.", "options": ["A) inefficient", "B) underutilised", "C) wasted", "D) idle"], "answer": "B", "explanation": "Underutilised means not used to full potential or capacity, which describes privately owned cars."},
    {"id": 3, "sentence": "Landlords converting homes from long-term housing to [BLANK] rental on platforms like Airbnb has reduced housing supply for residents.", "options": ["A) temporary", "B) commercial", "C) short-term", "D) flexible"], "answer": "C", "explanation": "Short-term rental is the specific term for renting property for brief periods through online platforms."},
    {"id": 4, "sentence": "The increase in ride-hailing vehicles in city centres has contributed to traffic [BLANK], slowing movement and reducing air quality.", "options": ["A) pollution", "B) density", "C) congestion", "D) overload"], "answer": "C", "explanation": "Congestion describes the situation where roads are so full of vehicles that movement is slowed."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The sharing economy claims to make more efficient use of existing resources. Does this environmental argument hold up when you consider all its effects? Explain.", "suggested_answer": "The environmental efficiency argument has some merit — sharing a car or a property does reduce the need for additional manufacturing. However, the broader effects are more complex. Ride-hailing services have increased the total distance driven in cities rather than replacing private car journeys, increasing emissions overall. Short-term rentals increase tourism, which generates transport emissions. The environmental case for the sharing economy depends heavily on the specific use case and whether sharing genuinely displaces ownership or simply adds new consumption on top of existing patterns. The most environmentally beneficial sharing involves genuinely replacing ownership rather than expanding access to activities people would not otherwise do."},
    {"id": 2, "question": "Should cities have the right to restrict sharing economy platforms like Airbnb to protect housing supply for residents? What are the key principles at stake?", "suggested_answer": "Cities have a legitimate interest in maintaining housing affordability for their residents, which is a fundamental social good. When commercial short-term rental platforms remove homes from the long-term market and price out local residents, the social harm is real and measurable. Restricting platforms in this way does limit individual economic freedom, but property rights in cities have always been constrained by planning regulations, zoning laws, and tenancy protections because housing is a social necessity, not merely a commodity. The key principle is that the right to profit from property does not override the community's interest in accessible housing — and regulating the means by which that profit is extracted is a normal exercise of public authority."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 6
) AND type = 'reading';

-- ── Lesson 7 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Financial Literacy: Managing Money in the Modern World",
  "text": "Financial literacy refers to the ability to understand and effectively manage personal finances, including budgeting, saving, borrowing, investing, and planning for the future. Despite its fundamental importance to individual well-being, financial education remains limited or absent in the school curricula of many countries. Research consistently shows that poor financial literacy is associated with higher levels of personal debt, inadequate retirement savings, and susceptibility to financial fraud. Budgeting is the foundation of sound financial management. A budget is a plan that tracks income and expenditure, helping individuals avoid spending more than they earn. The 50/30/20 rule — allocating fifty percent of income to needs, thirty percent to wants, and twenty percent to savings and debt repayment — is a widely recommended framework. However, applying such rules requires a stable income and a level of financial cushion that many people, particularly those in low-income situations, do not have. Understanding credit and debt is another essential component of financial literacy. Credit cards, loans, and mortgages can be valuable tools when used wisely, but their costs are often obscured by complex terms and conditions. Annual Percentage Rate (APR) is the most important figure to understand when comparing borrowing options — it represents the true yearly cost of credit including fees and interest. High-cost credit products such as payday loans can trap borrowers in cycles of debt. Investing — putting money to work in assets such as shares, bonds, or property to generate returns over time — is the primary mechanism by which individuals can build long-term wealth. Compound interest — earning returns on your previous returns — means that starting to invest early, even with small amounts, has a dramatically larger long-term impact than starting late with larger sums. Financial literacy education that begins in schools can help reduce inequality by giving all young people the knowledge to make informed financial decisions.",
  "glossary": [
    {"term": "financial literacy", "definition": "the ability to understand and manage personal finances effectively", "translation": "финансовая грамотность"},
    {"term": "budget", "definition": "a plan for income and expenditure over a given period", "translation": "бюджет"},
    {"term": "APR", "definition": "Annual Percentage Rate — the yearly cost of credit including interest and fees", "translation": "годовая процентная ставка"},
    {"term": "compound interest", "definition": "interest calculated on both the initial amount and the accumulated interest from previous periods", "translation": "сложные проценты"},
    {"term": "investment", "definition": "the act of putting money into assets with the expectation of generating future returns", "translation": "инвестиция"},
    {"term": "mortgage", "definition": "a loan secured against property, typically used to purchase a home", "translation": "ипотека"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What does financial literacy include according to the passage?", "options": ["A) Only knowledge of how to save and invest money", "B) Understanding and managing budgeting, saving, borrowing, investing, and planning", "C) The ability to calculate tax and complete financial reporting", "D) Knowledge of stock markets and investment strategies"], "answer": "B", "explanation": "Financial literacy includes the ability to understand and effectively manage personal finances: budgeting, saving, borrowing, investing, and planning."},
    {"id": 2, "question": "According to the passage, what does poor financial literacy lead to?", "options": ["A) Reduced consumer spending and slower economic growth", "B) Higher taxes and reduced government revenue", "C) Higher personal debt, inadequate retirement savings, and susceptibility to fraud", "D) Lower levels of entrepreneurship and economic innovation"], "answer": "C", "explanation": "Poor financial literacy is associated with higher levels of personal debt, inadequate retirement savings, and susceptibility to financial fraud."},
    {"id": 3, "question": "What does the 50/30/20 rule recommend?", "options": ["A) Spending half your income, saving thirty percent, and investing twenty percent", "B) Allocating fifty percent to needs, thirty percent to wants, and twenty percent to savings and debt", "C) Spending fifty percent less than you earn and saving thirty percent for retirement", "D) Investing twenty percent in stocks, thirty percent in bonds, and fifty percent in property"], "answer": "B", "explanation": "The 50/30/20 rule allocates fifty percent to needs, thirty percent to wants, and twenty percent to savings and debt repayment."},
    {"id": 4, "question": "What is APR and why is it important?", "options": ["A) A government measure of average household income", "B) The annual percentage of income paid in taxes", "C) The true yearly cost of credit including fees and interest", "D) A credit score system used by banks to assess borrowers"], "answer": "C", "explanation": "APR represents the true yearly cost of credit including fees and interest — the most important figure when comparing borrowing options."},
    {"id": 5, "question": "What advantage of starting to invest early does the passage describe?", "options": ["A) Early investors receive preferential tax treatment from governments", "B) Compound interest means small early investments have a larger long-term impact than larger late investments", "C) Early investors can access better investment products with higher guaranteed returns", "D) Starting early allows investors to spread risk over more markets and asset types"], "answer": "B", "explanation": "Compound interest means that starting to invest early, even with small amounts, has a dramatically larger long-term impact than starting late with larger sums."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Financial education is well-established in the school curricula of most countries.", "answer": false, "evidence": "Financial education remains limited or absent in the school curricula of many countries."},
    {"id": 2, "statement": "A budget is a plan that helps individuals track income and avoid spending more than they earn.", "answer": true, "evidence": "A budget is a plan that tracks income and expenditure, helping individuals avoid spending more than they earn."},
    {"id": 3, "statement": "The 50/30/20 rule is equally practical for all income levels.", "answer": false, "evidence": "Applying such rules requires a stable income and a level of financial cushion that many people, particularly those in low-income situations, do not have."},
    {"id": 4, "statement": "Payday loans are recommended in the passage as an affordable form of credit.", "answer": false, "evidence": "High-cost credit products such as payday loans can trap borrowers in cycles of debt."},
    {"id": 5, "statement": "Compound interest means earning returns on both the initial investment and previously accumulated returns.", "answer": true, "evidence": "Compound interest — earning returns on your previous returns — means that starting to invest early has a dramatically larger long-term impact."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "A [BLANK] is a plan for income and expenditure that helps you avoid spending more than you earn.", "options": ["A) savings plan", "B) financial plan", "C) budget", "D) forecast"], "answer": "C", "explanation": "A budget is the specific term for a plan tracking income and expenditure to manage personal finances."},
    {"id": 2, "sentence": "When comparing loans and credit cards, the most important figure is the [BLANK], which shows the true yearly cost including all fees and interest.", "options": ["A) interest rate", "B) APR", "C) credit score", "D) monthly payment"], "answer": "B", "explanation": "APR — Annual Percentage Rate — represents the true yearly cost of credit including fees and interest."},
    {"id": 3, "sentence": "Starting to invest early takes advantage of [BLANK] — earning returns on both the original investment and all previously earned returns.", "options": ["A) investment growth", "B) compounding returns", "C) compound interest", "D) accumulated savings"], "answer": "C", "explanation": "Compound interest is the specific term for earning returns on both the initial amount and previously accumulated interest."},
    {"id": 4, "sentence": "A [BLANK] is a loan secured against property, allowing people to buy homes by borrowing against the value of the building.", "options": ["A) credit line", "B) personal loan", "C) mortgage", "D) bond"], "answer": "C", "explanation": "A mortgage is a loan secured against property, typically used to purchase a home."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that financial literacy education in schools can help reduce inequality. Do you agree? Are there structural barriers to financial well-being that education alone cannot address?", "suggested_answer": "Financial literacy education is valuable and can improve individual decision-making. However, many financial problems are structural rather than educational — poverty, low wages, insecure employment, and the lack of affordable housing are not solved by knowing about compound interest or APR. Blaming financial difficulties on poor literacy can shift responsibility from systemic causes to individuals. Education should be combined with structural policies: minimum wage legislation, housing support, consumer protection from predatory lending, and accessible public pension systems. Financial literacy is most effective as a complement to these protections, not as a substitute for them."},
    {"id": 2, "question": "The passage describes compound interest as one of the most powerful forces in personal finance. Why do so many people fail to take advantage of it, and what barriers prevent early investment?", "suggested_answer": "Most people who fail to invest early do so because immediate needs consume available income. Rent, food, childcare, and debt repayments leave little surplus for long-term investment. The psychological concept of present bias — the tendency to prioritise immediate rewards over future benefits — also plays a role. For lower-income households, the priority is financial stability today, not wealth accumulation decades from now. Removing these barriers requires not just financial education but also policies that reduce immediate financial pressure: higher wages, affordable housing, universal childcare, and automatic enrollment in pension schemes with employer contributions."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l
  JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
    AND m.order_index = 4 AND l.order_index = 7
) AND type = 'reading';