-- ============================================================
-- B1 Intermediate / Module 5 (Law & Society)
-- Reading Sections — Lessons 1–7
-- Theme: Crime / Justice / Human Rights
-- ============================================================

-- ── Lesson 1 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Evolution of Criminal Justice: From Retribution to Rehabilitation",
  "text": "The concept of criminal justice has changed dramatically over thousands of years. In ancient legal codes such as the Code of Hammurabi (Babylon, around 1754 BCE), punishments were based on the principle of proportional retribution: if someone harmed another, they should suffer an equivalent harm. This eye-for-an-eye principle established the idea that punishment should match the crime, a concept still central to modern justice. Ancient Roman law introduced important principles that continue to influence legal systems worldwide, including the presumption of innocence, the right to face accusers, and the requirement for evidence before conviction. Medieval European justice relied heavily on religious authority, with trials by ordeal — placing suspects in situations of physical danger to determine guilt through divine intervention — and public punishment designed to deter potential offenders through fear. The Enlightenment of the seventeenth and eighteenth centuries fundamentally changed thinking about crime and punishment. Philosophers such as Cesare Beccaria argued that punishment should serve deterrence and rehabilitation rather than vengeance, and should be no more severe than necessary to prevent the crime from being repeated. These ideas shaped modern legal systems that emphasise proportionality, due process, and the rights of the accused. Contemporary justice systems vary in their emphasis. Some prioritise retribution — giving offenders the punishment they deserve. Others emphasise deterrence — preventing future crime through the threat of punishment. Rehabilitation — reforming offenders to reintegrate them productively into society — is a third approach gaining increasing support. Evidence increasingly shows that rehabilitation programmes reduce reoffending more effectively than punishment alone.",
  "glossary": [
    {"term": "retribution", "definition": "punishment given in return for wrongdoing; paying back harm with harm", "translation": "возмездие"},
    {"term": "presumption of innocence", "definition": "the principle that a person is considered innocent until proven guilty in court", "translation": "презумпция невиновности"},
    {"term": "deterrence", "definition": "the use of punishment or threat of punishment to discourage future criminal behaviour", "translation": "сдерживание, предупреждение преступлений"},
    {"term": "rehabilitation", "definition": "the process of reforming an offender to help them return productively to society", "translation": "реабилитация"},
    {"term": "proportionality", "definition": "the principle that punishment should be proportionate to the severity of the crime committed", "translation": "соразмерность"},
    {"term": "due process", "definition": "the legal requirement that authorities respect all legal rights of a person before punishment", "translation": "надлежащая правовая процедура"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What was the eye-for-an-eye principle in the Code of Hammurabi?", "options": ["A) Punishment should be more severe than the crime", "B) Punishment should match the harm caused", "C) Offenders should be helped to reform", "D) Only religious courts can determine punishment"], "answer": "B", "explanation": "The Code of Hammurabi was based on proportional retribution — punishment should match the harm caused."},
    {"id": 2, "question": "Which legal tradition introduced the presumption of innocence according to the passage?", "options": ["A) Babylonian law under Hammurabi", "B) Medieval European religious courts", "C) Ancient Roman law", "D) Enlightenment philosophy of the 1700s"], "answer": "C", "explanation": "Ancient Roman law introduced the presumption of innocence, the right to face accusers, and the requirement for evidence."},
    {"id": 3, "question": "What was a trial by ordeal?", "options": ["A) A long formal legal process in Roman courts", "B) Placing suspects in physical danger to determine guilt through divine intervention", "C) A system of compensation paid by offenders to victims", "D) Public shaming designed to humiliate offenders"], "answer": "B", "explanation": "Trials by ordeal involved placing suspects in physical danger to determine guilt through divine intervention in medieval Europe."},
    {"id": 4, "question": "What did Enlightenment thinkers like Beccaria argue about punishment?", "options": ["A) Punishment should instil maximum fear in potential offenders", "B) Religion should determine appropriate punishments", "C) Punishment should serve deterrence and rehabilitation rather than vengeance", "D) Only the state has the right to administer severe physical punishment"], "answer": "C", "explanation": "Beccaria argued that punishment should serve deterrence and rehabilitation rather than vengeance."},
    {"id": 5, "question": "What does evidence increasingly show about rehabilitation programmes?", "options": ["A) They are more expensive than imprisonment without reducing reoffending", "B) They reduce reoffending more effectively than punishment alone", "C) They are effective only for minor offenders", "D) They work only when combined with strict imprisonment"], "answer": "B", "explanation": "Evidence increasingly shows that rehabilitation programmes reduce reoffending more effectively than punishment alone."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The Code of Hammurabi originated in ancient Rome.", "answer": false, "evidence": "The Code of Hammurabi was from Babylon, around 1754 BCE."},
    {"id": 2, "statement": "Ancient Roman law included the presumption of innocence as a legal principle.", "answer": true, "evidence": "Ancient Roman law introduced the presumption of innocence and the right to face accusers."},
    {"id": 3, "statement": "Medieval European justice was based primarily on scientific evidence and rational inquiry.", "answer": false, "evidence": "Medieval European justice relied heavily on religious authority, with trials by ordeal."},
    {"id": 4, "statement": "Beccaria argued for harsher and more public forms of punishment.", "answer": false, "evidence": "Beccaria argued that punishment should serve deterrence and rehabilitation rather than vengeance."},
    {"id": 5, "statement": "Rehabilitation aims to reform offenders and reintegrate them into society.", "answer": true, "evidence": "Rehabilitation means reforming offenders to reintegrate them productively into society."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The principle that punishment should match the severity of the crime is called [BLANK].", "options": ["A) retribution", "B) rehabilitation", "C) proportionality", "D) due process"], "answer": "C", "explanation": "Proportionality is the principle that punishment should be proportionate to the severity of the crime."},
    {"id": 2, "sentence": "Ancient Roman law established the [BLANK] — the principle that a person is considered innocent until proven guilty.", "options": ["A) right to appeal", "B) presumption of innocence", "C) rule of law", "D) right to silence"], "answer": "B", "explanation": "Presumption of innocence is the legal principle that a person is considered innocent until proven guilty."},
    {"id": 3, "sentence": "Beccaria argued punishment should serve [BLANK] — preventing future crime through the threat of consequences.", "options": ["A) retribution", "B) rehabilitation", "C) deterrence", "D) compensation"], "answer": "C", "explanation": "Deterrence is the use of punishment or its threat to discourage future criminal behaviour."},
    {"id": 4, "sentence": "The process of reforming offenders to help them return productively to society is called [BLANK].", "options": ["A) deterrence", "B) retribution", "C) supervision", "D) rehabilitation"], "answer": "D", "explanation": "Rehabilitation is the process of reforming an offender and reintegrating them into society."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes how views on punishment have evolved. Which purpose of punishment — retribution, deterrence, or rehabilitation — do you think is most important today? Give reasons.", "suggested_answer": "The most defensible approach combines all three. Retribution meets a human need for justice and proportionality — serious wrongs must be taken seriously. Deterrence works best for rational actors calculating costs and benefits. Rehabilitation offers the most practical benefit to society by reducing reoffending, which protects future victims. Evidence consistently shows that treatment, education, and skills training in prison reduce reoffending more than punishment alone. The most effective systems combine proportionate punishment with genuine rehabilitation."},
    {"id": 2, "question": "The passage shows that ideas about justice have changed dramatically over history. What does this tell us about the nature of justice itself?", "suggested_answer": "The dramatic changes in how societies have understood justice — from divine trials to rehabilitation — suggest that justice is not a fixed universal standard but a human construction that reflects the values and knowledge of each era. What seems obviously just to one generation may seem barbaric to the next. This does not mean justice is purely subjective — some principles, like the presumption of innocence, have proven durable across cultures. It does suggest we should approach current practices with humility, recognising that future generations may judge aspects of our justice systems as harshly as we judge past practices."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 1) AND type = 'reading';

-- ── Lesson 2 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Universal Declaration of Human Rights",
  "text": "On 10 December 1948, the United Nations General Assembly adopted the Universal Declaration of Human Rights. Drafted in the aftermath of the atrocities of World War Two, the Declaration represented the collective determination of humanity to ensure that such horrors would never be repeated. It established, for the first time in history, a common standard of fundamental rights and freedoms that all human beings are entitled to, regardless of nationality, race, religion, sex, or any other status. The Declaration comprises thirty articles covering civil, political, economic, social, and cultural rights. Civil and political rights include the right to life, freedom from torture, the right to a fair trial, freedom of expression, and the right to participate in government. Economic and social rights include the right to education, adequate housing, healthcare, and a standard of living sufficient for health and well-being. The Declaration was a significant moral and political achievement. However, its provisions are not legally binding in international law — it is a declaration of principles rather than a treaty. Countries that have incorporated its principles into domestic law or signed subsequent binding treaties are legally obligated to uphold them. In practice, enforcement remains a major challenge. Many states violate the rights they have formally committed to uphold, and international mechanisms for accountability are often weak. Nevertheless, the Declaration has had profound influence. It has inspired dozens of subsequent international human rights treaties, shaped the constitutions of newly independent states, and provided a common language for human rights activism worldwide. It remains one of the most significant documents in the history of international relations.",
  "glossary": [
    {"term": "declaration", "definition": "a formal public statement of intentions, principles, or beliefs", "translation": "декларация"},
    {"term": "ratification", "definition": "the formal confirmation of a treaty or agreement by a government", "translation": "ратификация"},
    {"term": "legally binding", "definition": "creating legal obligations that must be followed under law", "translation": "юридически обязательный"},
    {"term": "treaty", "definition": "a formally concluded agreement between countries that is legally binding", "translation": "договор, соглашение"},
    {"term": "enforcement", "definition": "the process of ensuring that laws or rules are obeyed", "translation": "правоприменение"},
    {"term": "accountability", "definition": "the fact of being responsible for your actions and required to explain them to others", "translation": "подотчётность, ответственность"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "When was the Universal Declaration of Human Rights adopted?", "options": ["A) 10 December 1945", "B) 10 December 1948", "C) 24 October 1945", "D) 1 January 1950"], "answer": "B", "explanation": "The Universal Declaration of Human Rights was adopted on 10 December 1948."},
    {"id": 2, "question": "What prompted the creation of the Declaration according to the passage?", "options": ["A) The end of colonialism and the independence of new nations", "B) The atrocities of World War Two and the determination to prevent their repetition", "C) A request from developing nations for international recognition of their rights", "D) The formation of the United Nations Security Council"], "answer": "B", "explanation": "The Declaration was drafted in the aftermath of World War Two atrocities, representing the determination to ensure such horrors would never be repeated."},
    {"id": 3, "question": "What is the legal status of the Universal Declaration?", "options": ["A) It is fully legally binding on all UN member states", "B) It is legally binding only for the five permanent Security Council members", "C) It is a declaration of principles, not a legally binding treaty", "D) It has no legal status but is enforced through economic sanctions"], "answer": "C", "explanation": "The Declaration is a declaration of principles rather than a legally binding treaty."},
    {"id": 4, "question": "What economic and social rights does the passage mention?", "options": ["A) The right to vote, freedom of speech, and freedom of the press", "B) The right to education, housing, healthcare, and an adequate standard of living", "C) The right to own property, conduct business, and move freely", "D) The right to work, form trade unions, and receive minimum wages"], "answer": "B", "explanation": "Economic and social rights include the right to education, adequate housing, healthcare, and a standard of living sufficient for health."},
    {"id": 5, "question": "What challenge does the passage identify in relation to the Declaration?", "options": ["A) Most countries have refused to incorporate it into their constitutions", "B) Enforcement remains difficult as many states violate rights they committed to uphold", "C) The Declaration has become outdated and needs to be comprehensively revised", "D) Too many rights are included, making it impossible to prioritise essential ones"], "answer": "B", "explanation": "Many states violate rights they have formally committed to uphold, and international mechanisms for accountability are often weak."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The Universal Declaration of Human Rights was adopted in the immediate aftermath of World War Two.", "answer": true, "evidence": "Drafted in the aftermath of the atrocities of World War Two, adopted on 10 December 1948."},
    {"id": 2, "statement": "The Declaration is legally binding on all countries under international law.", "answer": false, "evidence": "Its provisions are not legally binding in international law — it is a declaration of principles rather than a treaty."},
    {"id": 3, "statement": "The Declaration covers only civil and political rights, not economic or social rights.", "answer": false, "evidence": "The Declaration comprises thirty articles covering civil, political, economic, social, and cultural rights."},
    {"id": 4, "statement": "All countries that signed the Declaration fully comply with its provisions.", "answer": false, "evidence": "Many states violate the rights they have formally committed to uphold, and international accountability mechanisms are often weak."},
    {"id": 5, "statement": "The Declaration has influenced the constitutions of newly independent states.", "answer": true, "evidence": "The Declaration has inspired dozens of subsequent treaties, shaped constitutions of newly independent states, and provided a common language for human rights activism."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The Universal Declaration is a [BLANK] of principles rather than a legally binding international treaty.", "options": ["A) charter", "B) declaration", "C) convention", "D) resolution"], "answer": "B", "explanation": "Declaration is the specific term for a formal public statement of principles that is not automatically legally binding."},
    {"id": 2, "sentence": "Countries that have signed subsequent [BLANK] based on the Declaration are legally obligated to uphold the rights they contain.", "options": ["A) agreements", "B) charters", "C) treaties", "D) declarations"], "answer": "C", "explanation": "Treaties are formally concluded international agreements that are legally binding, unlike declarations."},
    {"id": 3, "sentence": "[BLANK] of human rights remains a major challenge — many states violate rights they formally committed to uphold.", "options": ["A) Declaration", "B) Enforcement", "C) Recognition", "D) Ratification"], "answer": "B", "explanation": "Enforcement is the process of ensuring that laws and rules are obeyed, which the passage identifies as a major challenge."},
    {"id": 4, "sentence": "International mechanisms for [BLANK] — requiring states to explain and answer for rights violations — are often weak.", "options": ["A) enforcement", "B) ratification", "C) accountability", "D) compliance"], "answer": "C", "explanation": "Accountability means being responsible for your actions and required to explain them, which is what weak international mechanisms fail to ensure."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage notes that the Declaration is not legally binding. Does this undermine its value? Can a document without legal enforcement still be meaningful?", "suggested_answer": "A non-binding declaration can still be tremendously valuable. The UDHR has shaped national constitutions, inspired binding treaties, and provided a common framework for civil society and activists to challenge abusive governments. Its moral authority comes not from legal enforcement but from the breadth of its acceptance — nearly all countries have endorsed its principles. Legal obligations are only as strong as their enforcement mechanisms, and even binding treaties are frequently violated. The Declaration works through persuasion, publicity, and the creation of shared standards that governments must at least publicly endorse, which creates accountability even without formal legal sanctions."},
    {"id": 2, "question": "The Declaration establishes both civil rights and economic and social rights. Some argue that economic rights such as housing and healthcare are aspirational goals rather than genuine rights. Do you agree?", "suggested_answer": "Dismissing economic and social rights as merely aspirational reflects a limited view of what rights are. If a person lacks food, housing, or healthcare, their civil and political rights have little practical value. Rights are most meaningful when they protect the basic conditions for a dignified human life. The difficulty of immediately fulfilling economic rights in all contexts does not mean they are not genuine rights — it means they require sustained effort and resources to realise. Treating them as secondary to civil rights has historically allowed wealthy nations to avoid accountability for poverty and inequality within and across borders."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 2) AND type = 'reading';

-- ── Lesson 3 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Cybercrime: Threats in the Digital Age",
  "text": "Cybercrime — criminal activity conducted through computer networks and the internet — has become one of the fastest-growing categories of crime globally. From financial fraud and identity theft to ransomware attacks on hospitals and disruption of critical infrastructure, the scale and sophistication of cybercrime represent a serious threat to individuals, businesses, and governments worldwide. Financial cybercrime affects hundreds of millions of people each year. Phishing — deceptive emails or messages designed to trick people into revealing passwords or financial information — is among the most common attacks. Once criminals gain access to banking credentials or personal information, they can drain accounts, take out fraudulent loans, or sell the stolen information to other criminal networks. Identity theft, in which criminals use the personal information of another individual to commit fraud, can take victims years to resolve and may damage credit ratings, employment prospects, and personal well-being. Ransomware attacks involve criminals encrypting important data and demanding payment for its release. Several high-profile attacks have disrupted hospitals, delaying medical procedures and endangering lives, and have cost businesses and public institutions hundreds of millions of dollars in ransom payments and recovery costs. The global nature of cybercrime creates significant challenges for law enforcement. Criminals frequently operate from countries with limited cybercrime legislation or inadequate international cooperation agreements. Attributing attacks to specific individuals or groups is technically difficult and time-consuming. International cooperation through organisations such as Interpol is improving, but remains insufficient given the speed at which cybercriminal techniques evolve. Prevention through strong passwords, regular software updates, two-factor authentication, and critical awareness of phishing attempts remains the most effective defence for individuals and organisations.",
  "glossary": [
    {"term": "cybercrime", "definition": "criminal activity carried out by means of computers or the internet", "translation": "киберпреступление"},
    {"term": "phishing", "definition": "a fraudulent attempt to obtain sensitive information by disguising as a trustworthy source", "translation": "фишинг"},
    {"term": "ransomware", "definition": "malicious software that encrypts data and demands payment for its release", "translation": "программа-вымогатель"},
    {"term": "identity theft", "definition": "the fraudulent use of another person's personal information to commit crimes", "translation": "кража личных данных"},
    {"term": "two-factor authentication", "definition": "a security process requiring two separate forms of identification to access an account", "translation": "двухфакторная аутентификация"},
    {"term": "encryption", "definition": "the process of encoding information so that only authorised users can access it", "translation": "шифрование"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is phishing as described in the passage?", "options": ["A) A type of ransomware that encrypts hospital data", "B) Deceptive messages designed to trick people into revealing sensitive information", "C) The theft of physical documents containing personal information", "D) A technique for accessing computer systems through security vulnerabilities"], "answer": "B", "explanation": "Phishing involves deceptive emails or messages designed to trick people into revealing passwords or financial information."},
    {"id": 2, "question": "What do ransomware attacks involve?", "options": ["A) Stealing personal data and selling it on the dark web", "B) Creating fake websites to collect payment card details", "C) Encrypting important data and demanding payment for its release", "D) Sending millions of spam emails to overload computer systems"], "answer": "C", "explanation": "Ransomware involves criminals encrypting important data and demanding payment for its release."},
    {"id": 3, "question": "What harm can identity theft cause to victims according to the passage?", "options": ["A) Only financial losses that can be quickly recovered", "B) Damage to credit ratings, employment prospects, and personal well-being", "C) Primarily emotional distress with no lasting practical consequences", "D) Loss of social media accounts and digital identity"], "answer": "B", "explanation": "Identity theft can take years to resolve and may damage credit ratings, employment prospects, and personal well-being."},
    {"id": 4, "question": "Why is international cybercrime law enforcement challenging?", "options": ["A) There are no international laws covering cybercrime", "B) Most cybercriminals operate anonymously from their home countries", "C) Criminals operate from countries with limited legislation and attribution is technically difficult", "D) Cybercrime is not considered serious enough to warrant international cooperation"], "answer": "C", "explanation": "Criminals operate from countries with limited legislation, and attributing attacks to specific individuals is technically difficult."},
    {"id": 5, "question": "What does the passage recommend as the most effective defence against cybercrime?", "options": ["A) Avoiding use of the internet for financial transactions", "B) Government monitoring of all internet communications", "C) Strong passwords, software updates, two-factor authentication, and awareness of phishing", "D) Only using offline systems for sensitive personal and financial data"], "answer": "C", "explanation": "Prevention through strong passwords, updates, two-factor authentication, and phishing awareness is the most effective defence."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Cybercrime is one of the fastest-growing categories of crime globally.", "answer": true, "evidence": "Cybercrime has become one of the fastest-growing categories of crime globally."},
    {"id": 2, "statement": "Phishing attacks always involve direct hacking of computer systems.", "answer": false, "evidence": "Phishing involves deceptive emails or messages designed to trick people into revealing information — it relies on deception, not technical hacking."},
    {"id": 3, "statement": "Ransomware attacks have only targeted private businesses and have not affected public services.", "answer": false, "evidence": "Attacks have disrupted hospitals, delayed medical procedures, and cost public institutions hundreds of millions of dollars."},
    {"id": 4, "statement": "International cooperation against cybercrime is currently sufficient to keep pace with evolving criminal techniques.", "answer": false, "evidence": "International cooperation remains insufficient given the speed at which cybercriminal techniques evolve."},
    {"id": 5, "statement": "Using two-factor authentication is recommended as part of cybercrime prevention.", "answer": true, "evidence": "Prevention through two-factor authentication and critical awareness of phishing attempts remains the most effective defence."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Criminals sending deceptive emails to trick people into revealing their passwords are using a technique called [BLANK].", "options": ["A) hacking", "B) phishing", "C) spoofing", "D) ransomware"], "answer": "B", "explanation": "Phishing is the specific term for fraudulent attempts to obtain sensitive information by appearing trustworthy."},
    {"id": 2, "sentence": "In a [BLANK] attack, criminals encrypt important data and demand payment before restoring access.", "options": ["A) phishing", "B) malware", "C) ransomware", "D) spyware"], "answer": "C", "explanation": "Ransomware is malicious software that encrypts data and demands payment for its release."},
    {"id": 3, "sentence": "The fraudulent use of another person's personal details to commit fraud is called [BLANK].", "options": ["A) data theft", "B) identity theft", "C) personal fraud", "D) account takeover"], "answer": "B", "explanation": "Identity theft is the fraudulent use of another person's personal information to commit crimes."},
    {"id": 4, "sentence": "Requiring users to confirm their identity through two separate verification steps — called [BLANK] — makes accounts much harder to access fraudulently.", "options": ["A) password protection", "B) two-step login", "C) two-factor authentication", "D) secure access"], "answer": "C", "explanation": "Two-factor authentication is the security process requiring two separate forms of identification to access an account."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage shows that ransomware attacks on hospitals can endanger lives. Should attacking healthcare infrastructure be treated as a special category of serious crime with higher penalties?", "suggested_answer": "Attacks on critical healthcare infrastructure that endanger lives represent an extreme form of harm and should be treated with corresponding seriousness. The fact that hospital ransomware attacks have delayed cancer treatments and emergency care — potentially contributing to deaths — puts them in a different category from financial cybercrime. Higher penalties are one response, but deterrence through punishment alone is limited for sophisticated criminal groups operating internationally. More effective measures include mandatory baseline cybersecurity standards for critical infrastructure, international agreements that remove safe havens for cybercriminals, and dedicated law enforcement resources."},
    {"id": 2, "question": "The passage places some responsibility on individuals to protect themselves through security practices. Is this fair, or should organisations and governments bear more responsibility for cybersecurity?", "suggested_answer": "Placing primary responsibility on individuals is unfair given the sophistication of attacks. Most people lack the technical knowledge to defend against state-sponsored hackers or professional criminal organisations. Organisations that collect personal data have a duty of care to protect it with robust security measures, and governments should regulate minimum standards. Individual responsibility has a role — basic hygiene like strong passwords and two-factor authentication does help — but it should be the last line of defence, not the first. Systemic solutions requiring organisations and platforms to build security in from the start are more effective than expecting every user to be a cybersecurity expert."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 3) AND type = 'reading';

-- ── Lesson 4 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Restorative Justice: Repairing the Harm",
  "text": "Criminal justice systems worldwide debate the merits of two distinct philosophical approaches to wrongdoing: retributive justice and restorative justice. Retributive justice, which has dominated Western legal systems for centuries, holds that crime deserves punishment proportionate to its severity. The offender has violated the law and the community has a right to punish them accordingly. Prison sentences, fines, and community service are the primary tools of the retributive system. Restorative justice takes a fundamentally different approach. Rather than focusing on what punishment an offender deserves, it asks what harm has been done, who has been affected, and what can be done to repair it. The process typically involves facilitated meetings between offenders, victims, and affected community members. Offenders take direct responsibility for their actions and often agree to compensate or make amends to those they have harmed. Victims have an opportunity to express the impact of the crime and to participate in determining what a just outcome looks like. Research on restorative justice programmes has produced generally positive findings. Victims who participate report higher satisfaction with the justice process and greater emotional recovery than those who go through conventional court proceedings alone. Reoffending rates among offenders who complete restorative programmes are often significantly lower than among those who receive only conventional sentences. These benefits are particularly pronounced for lower-level and first-time offences. However, restorative justice has limitations. It is not appropriate for all crimes or all offenders. In cases of serious violence, some victims may not wish to meet those who harmed them. There is also a risk that the process prioritises reconciliation over appropriate accountability, potentially leaving serious offenders without sufficient consequences.",
  "glossary": [
    {"term": "restorative justice", "definition": "an approach to justice focused on repairing harm through cooperation between offenders, victims, and community", "translation": "восстановительное правосудие"},
    {"term": "retributive justice", "definition": "an approach to justice based on giving offenders punishment proportionate to their crime", "translation": "карательное правосудие"},
    {"term": "facilitated", "definition": "made easier or more structured through the guidance of a trained mediator", "translation": "направляемый, с участием посредника"},
    {"term": "reoffending", "definition": "committing another crime after having already been punished for a previous one", "translation": "рецидив преступления"},
    {"term": "reconciliation", "definition": "the restoration of friendly relations between people who were in conflict", "translation": "примирение"},
    {"term": "amends", "definition": "actions taken to compensate for wrongdoing or harm caused to another", "translation": "возмещение ущерба, исправление"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "What is the central focus of retributive justice?", "options": ["A) Repairing harm and restoring relationships", "B) Giving offenders punishment proportionate to their crime", "C) Preventing future crime through rehabilitation", "D) Involving victims in determining outcomes"], "answer": "B", "explanation": "Retributive justice holds that crime deserves punishment proportionate to its severity."},
    {"id": 2, "question": "What does restorative justice ask instead of what punishment an offender deserves?", "options": ["A) How can the offender be most effectively deterred from reoffending", "B) What community service would most benefit the public", "C) What harm has been done, who was affected, and how can it be repaired", "D) What sentence would be most publicly acceptable"], "answer": "C", "explanation": "Restorative justice asks what harm has been done, who has been affected, and what can be done to repair it."},
    {"id": 3, "question": "What does research show about victims who participate in restorative justice programmes?", "options": ["A) They are more likely to experience trauma from meeting the offender", "B) They report higher satisfaction and greater emotional recovery than through courts alone", "C) They receive higher financial compensation than through the court system", "D) They are less likely to support prosecution of future offenders"], "answer": "B", "explanation": "Victims who participate report higher satisfaction with the justice process and greater emotional recovery."},
    {"id": 4, "question": "For which type of offences are the benefits of restorative justice most pronounced?", "options": ["A) Serious violent crimes and organised crime", "B) International crimes and terrorism", "C) Lower-level and first-time offences", "D) Economic crimes and corporate fraud"], "answer": "C", "explanation": "The benefits are particularly pronounced for lower-level and first-time offences."},
    {"id": 5, "question": "What limitation of restorative justice does the passage mention?", "options": ["A) It is more expensive than conventional court proceedings", "B) It requires victims to forgive offenders", "C) It may prioritise reconciliation over appropriate accountability for serious offenders", "D) It has not been studied and lacks evidence of effectiveness"], "answer": "C", "explanation": "There is a risk that the process prioritises reconciliation over appropriate accountability, potentially leaving serious offenders without sufficient consequences."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Retributive justice focuses primarily on repairing harm to victims.", "answer": false, "evidence": "Retributive justice holds that crime deserves punishment — the focus is on giving offenders consequences, not on repairing harm."},
    {"id": 2, "statement": "Restorative justice typically involves facilitated meetings between offenders, victims, and community members.", "answer": true, "evidence": "The process typically involves facilitated meetings between offenders, victims, and affected community members."},
    {"id": 3, "statement": "Reoffending rates are consistently higher among offenders who complete restorative programmes.", "answer": false, "evidence": "Reoffending rates among offenders who complete restorative programmes are often significantly lower than among those who receive only conventional sentences."},
    {"id": 4, "statement": "Restorative justice is equally appropriate for all types of crimes.", "answer": false, "evidence": "It is not appropriate for all crimes or all offenders. In cases of serious violence, some victims may not wish to meet those who harmed them."},
    {"id": 5, "statement": "Victims in restorative justice processes can participate in determining outcomes.", "answer": true, "evidence": "Victims have an opportunity to express the impact of the crime and to participate in determining what a just outcome looks like."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Rather than focusing on punishment, [BLANK] justice asks what harm was done and how it can be repaired.", "options": ["A) retributive", "B) restorative", "C) rehabilitative", "D) preventive"], "answer": "B", "explanation": "Restorative justice is the approach focused on repairing harm rather than administering punishment."},
    {"id": 2, "sentence": "Offenders in restorative programmes often agree to make [BLANK] — taking actions to compensate those they have harmed.", "options": ["A) apologies", "B) payments", "C) amends", "D) promises"], "answer": "C", "explanation": "Amends are actions taken to compensate for wrongdoing or harm caused to another."},
    {"id": 3, "sentence": "[BLANK] — committing further crimes after being punished — is significantly lower among offenders who complete restorative programmes.", "options": ["A) Recidivism", "B) Reoffending", "C) Relapse", "D) Repetition"], "answer": "B", "explanation": "Reoffending is the specific term used in the passage for committing another crime after previous punishment."},
    {"id": 4, "sentence": "The process is guided by a trained mediator — making it [BLANK] — to ensure both parties are heard fairly.", "options": ["A) structured", "B) supervised", "C) facilitated", "D) managed"], "answer": "C", "explanation": "Facilitated means made easier or more structured through the guidance of a trained mediator."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage shows that restorative justice produces better outcomes for many offenders and victims. Why do you think retributive justice remains dominant despite this evidence?", "suggested_answer": "Retributive justice remains dominant partly because it aligns with powerful emotional instincts. When a crime is committed, the natural response is anger and a desire for the wrongdoer to suffer proportionately. Politicians respond to these instincts because voters are motivated by emotion as much as evidence. There is also a legitimate concern that restorative justice, if applied without proper safeguards, could allow serious offenders to avoid meaningful consequences through staged apologies. Changing dominant approaches to justice requires sustained public education about what actually reduces crime, combined with political courage to prioritise evidence over populist sentiment."},
    {"id": 2, "question": "The passage suggests that restorative justice is more appropriate for minor than serious offences. Do you agree? Are there cases where it might be valuable even after serious crimes?", "suggested_answer": "The caution around serious offences is understandable — not all victims want contact with those who harmed them, and serious crimes may require consequences that signal social disapproval proportionate to the harm. However, there are documented cases where restorative processes have helped victims of serious crimes — including violence — to find closure and understanding that the conventional justice system could not provide. The key is that participation must be entirely voluntary, professionally supported, and offered as a supplement to rather than replacement for appropriate legal consequences. Some survivors have found meeting those who harmed them transformative in ways that no court verdict could achieve."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 4) AND type = 'reading';

-- ── Lesson 5 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Human Trafficking: The Crime of Modern Slavery",
  "text": "Human trafficking — the recruitment, transportation, or receipt of people through coercion, deception, or force for the purpose of exploitation — is a serious crime and a violation of fundamental human rights. It is often described as a form of modern slavery. Estimates suggest that approximately forty to fifty million people are affected by some form of modern slavery worldwide, though the hidden nature of the crime makes precise measurement impossible. Human trafficking takes several forms. Sex trafficking, in which victims are forced or coerced into sexual exploitation, is among the most commonly reported. Labour trafficking involves victims being forced to work in agriculture, construction, domestic service, or factories under conditions of debt bondage or direct coercion. Organ trafficking — the illegal recruitment of individuals to donate organs for transplant — is a less common but serious form. Trafficking affects people on all continents, though it disproportionately affects women and girls, migrants, people living in poverty, and those displaced by conflict. Traffickers typically use deceptive recruitment — advertising false job offers for legitimate work abroad — combined with debt bondage, confiscation of identity documents, and threats of violence to control victims once they are in vulnerable situations. Addressing trafficking requires a coordinated response involving law enforcement, social services, immigration agencies, and civil society organisations. Prevention efforts focus on education, particularly for vulnerable groups, helping people recognise deceptive recruitment offers. Support for survivors includes legal assistance, housing, healthcare, and psychological counselling. International cooperation and improved information sharing between countries are essential for identifying trafficking networks and prosecuting those responsible.",
  "glossary": [
    {"term": "human trafficking", "definition": "the exploitation of people through coercion or deception for labour, sex, or other purposes", "translation": "торговля людьми"},
    {"term": "coercion", "definition": "the practice of persuading someone to do something using threats or force", "translation": "принуждение"},
    {"term": "debt bondage", "definition": "a form of forced labour where a person works to pay off a debt that keeps increasing", "translation": "долговая кабала"},
    {"term": "exploitation", "definition": "the action of treating someone unfairly in order to benefit from their work or situation", "translation": "эксплуатация"},
    {"term": "displacement", "definition": "the forced movement of people from their home area due to conflict, disaster, or persecution", "translation": "вынужденное перемещение"},
    {"term": "survivor", "definition": "a person who has experienced and overcome a traumatic event such as trafficking or abuse", "translation": "выживший, пострадавший"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "How is human trafficking described in the passage?", "options": ["A) As an immigration issue caused by weak border controls", "B) As a form of modern slavery and a violation of fundamental human rights", "C) As a problem limited to developing countries", "D) As primarily an issue of voluntary migration gone wrong"], "answer": "B", "explanation": "Human trafficking is described as a serious crime, a violation of fundamental human rights, and a form of modern slavery."},
    {"id": 2, "question": "What is debt bondage as described in the passage?", "options": ["A) A legitimate form of employment contract in certain industries", "B) A legal debt owed by migrants to recruitment agencies", "C) A form of forced labour where victims work to pay off a debt that keeps increasing", "D) A financial penalty imposed on traffickers by courts"], "answer": "C", "explanation": "Debt bondage is when victims are forced to work to pay off a debt that keeps increasing, maintaining their exploitation."},
    {"id": 3, "question": "Who is most vulnerable to trafficking according to the passage?", "options": ["A) Well-educated professionals seeking work abroad", "B) Citizens of wealthy countries travelling for tourism", "C) Women and girls, migrants, people in poverty, and those displaced by conflict", "D) Young men seeking employment in construction industries"], "answer": "C", "explanation": "Trafficking disproportionately affects women and girls, migrants, people living in poverty, and those displaced by conflict."},
    {"id": 4, "question": "What initial method do traffickers typically use to recruit victims?", "options": ["A) Direct violent abduction from public places", "B) False job offers advertising legitimate work abroad", "C) Online recruitment through legitimate employment websites", "D) Pressure through family members already working abroad"], "answer": "B", "explanation": "Traffickers typically use deceptive recruitment by advertising false job offers for legitimate work abroad."},
    {"id": 5, "question": "What support does the passage say survivors of trafficking need?", "options": ["A) Only legal assistance to prosecute traffickers", "B) Financial compensation from their traffickers", "C) Legal assistance, housing, healthcare, and psychological counselling", "D) Immediate return to their country of origin"], "answer": "C", "explanation": "Support for survivors includes legal assistance, housing, healthcare, and psychological counselling."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Human trafficking only involves the movement of people across international borders.", "answer": false, "evidence": "Human trafficking involves the recruitment, transportation, or receipt of people through coercion — it can occur within a single country."},
    {"id": 2, "statement": "Labour trafficking involves forcing victims to work under conditions of debt bondage or coercion.", "answer": true, "evidence": "Labour trafficking involves victims being forced to work under conditions of debt bondage or direct coercion."},
    {"id": 3, "statement": "Human trafficking is easy to measure accurately because victims regularly report it to authorities.", "answer": false, "evidence": "The hidden nature of the crime makes precise measurement impossible."},
    {"id": 4, "statement": "Traffickers typically use threats and confiscation of documents to control victims once recruited.", "answer": true, "evidence": "Traffickers use debt bondage, confiscation of identity documents, and threats of violence to control victims."},
    {"id": 5, "statement": "Addressing trafficking requires only law enforcement action, without involving social services or civil society.", "answer": false, "evidence": "Addressing trafficking requires a coordinated response involving law enforcement, social services, immigration agencies, and civil society organisations."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Traffickers use [BLANK] — threats and force — to control victims and prevent them from escaping their situation.", "options": ["A) persuasion", "B) coercion", "C) deception", "D) manipulation"], "answer": "B", "explanation": "Coercion is the practice of persuading someone to do something using threats or force."},
    {"id": 2, "sentence": "Victims in [BLANK] are forced to work to pay off debts that are deliberately kept artificially high to prevent them ever being free.", "options": ["A) servitude", "B) forced labour", "C) debt bondage", "D) captivity"], "answer": "C", "explanation": "Debt bondage is the specific term for a form of forced labour where a debt keeps increasing to maintain exploitation."},
    {"id": 3, "sentence": "Trafficking disproportionately affects those displaced by conflict — people forced from their homes by [BLANK] or disaster.", "options": ["A) migration", "B) displacement", "C) persecution", "D) relocation"], "answer": "B", "explanation": "Displacement refers to the forced movement of people from their home area due to conflict, disaster, or persecution."},
    {"id": 4, "sentence": "Support services must be available to [BLANK] — those who have experienced trafficking — to help them rebuild their lives.", "options": ["A) victims", "B): refugees", "C) migrants", "D) survivors"], "answer": "D", "explanation": "Survivors is the specific term used in the passage for people who have experienced and overcome trafficking."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage describes human trafficking as modern slavery. Do you think the term slavery is appropriate? What does using this term achieve?", "suggested_answer": "Using the term slavery is both appropriate and strategic. The conditions described — coercion, captivity, deprivation of freedom and identity documents, forced labour — share the defining characteristics of historical slavery even if the legal framework is different. The term is morally powerful and helps communicate the severity of the crime to audiences who might otherwise dismiss it as simply irregular migration. It also creates a connection to historical anti-slavery movements, lending moral clarity and urgency. The risk is that the comparison might seem to diminish historical slavery, but most scholars and advocates argue that recognising modern slavery as a continuation of historical oppression strengthens rather than weakens both causes."},
    {"id": 2, "question": "The passage emphasises education and awareness as key prevention tools. Why might awareness not be enough, and what structural changes are needed to address trafficking?", "suggested_answer": "Awareness is important but insufficient because trafficking is driven by structural factors — poverty, gender inequality, armed conflict, and lack of legal migration pathways — that education alone cannot address. People accept dangerous migration and employment offers not because they lack awareness but because their alternatives are even worse. Structural responses include creating legal pathways for labour migration so people are not forced to use illegal routes, strengthening social protection for women and vulnerable groups, regulating labour recruitment agencies, and addressing poverty in source communities. Awareness campaigns work best as part of a broader strategy that removes the conditions that make people vulnerable to exploitation."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 5) AND type = 'reading';

-- ── Lesson 6 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "The Death Penalty: An Unresolved Debate",
  "text": "The death penalty — the execution of a person as punishment for a crime — remains one of the most contested issues in criminal justice. More than one hundred countries have abolished it in law or practice, but approximately fifty continue to carry out executions. The United States, China, Iran, Saudi Arabia, and Egypt are among those that retain and actively use it. Advocates argue that the death penalty serves as the ultimate deterrent against the most serious crimes, provides permanent protection to society by eliminating the most dangerous offenders, and represents the proportionate response to crimes such as premeditated murder. Some also invoke the principle of justice: that those who deliberately take a life should face the most serious consequence available. Opponents raise compelling practical and moral arguments against capital punishment. The risk of executing an innocent person is among the most serious objections. Since 1973 in the United States alone, more than one hundred and ninety people on death row have been exonerated — cleared of guilt — after new evidence emerged. Research has consistently failed to demonstrate that the death penalty deters crime more effectively than long prison sentences. The process of capital punishment is also significantly more expensive than life imprisonment when the costs of mandatory legal appeals are included. On moral grounds, many argue that the state has no legitimate right to kill its citizens regardless of the crime committed. International human rights organisations, including the United Nations, have called for a universal moratorium on executions, arguing that the right to life is fundamental and should not be conditional on behaviour.",
  "glossary": [
    {"term": "capital punishment", "definition": "the legally authorised killing of someone as punishment for a crime", "translation": "смертная казнь"},
    {"term": "deterrent", "definition": "a thing that discourages or prevents people from doing something", "translation": "сдерживающий фактор"},
    {"term": "exonerated", "definition": "officially declared free from blame or criminal responsibility", "translation": "оправданный, снятый с подозрения"},
    {"term": "moratorium", "definition": "a temporary prohibition of an activity", "translation": "мораторий"},
    {"term": "abolition", "definition": "the formal ending of a practice or institution", "translation": "отмена, упразднение"},
    {"term": "premeditated", "definition": "planned or considered before it is done; deliberate", "translation": "преднамеренный"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "How many countries have abolished the death penalty in law or practice according to the passage?", "options": ["A) Around twenty-five countries", "B) Around fifty countries", "C) More than one hundred countries", "D) All but fifteen countries"], "answer": "C", "explanation": "More than one hundred countries have abolished the death penalty in law or practice."},
    {"id": 2, "question": "What argument do advocates of the death penalty make?", "options": ["A) It is cheaper than life imprisonment", "B) It serves as the ultimate deterrent and provides permanent protection to society", "C) It reduces prison overcrowding and improves conditions for other inmates", "D) It is supported by scientific evidence of reduced crime rates"], "answer": "B", "explanation": "Advocates argue the death penalty serves as the ultimate deterrent and permanently protects society by eliminating dangerous offenders."},
    {"id": 3, "question": "What does the passage say about research on the death penalty as a deterrent?", "options": ["A) Research consistently shows it reduces murder rates", "B) Research has consistently failed to show it deters crime more than long prison sentences", "C) Research is inconclusive and more studies are needed", "D) Research shows it deters crime in some countries but not others"], "answer": "B", "explanation": "Research has consistently failed to demonstrate that the death penalty deters crime more effectively than long prison sentences."},
    {"id": 4, "question": "How many people on death row in the US have been exonerated since 1973?", "options": ["A) More than fifty", "B) More than one hundred", "C) More than one hundred and ninety", "D) More than two hundred and fifty"], "answer": "C", "explanation": "Since 1973 in the United States alone, more than one hundred and ninety people on death row have been exonerated."},
    {"id": 5, "question": "What has the United Nations called for regarding the death penalty?", "options": ["A) A complete and permanent abolition worldwide", "B) A universal moratorium on executions", "C) Restriction to only the most extreme terrorist crimes", "D) Transfer of all execution decisions to international courts"], "answer": "B", "explanation": "The United Nations has called for a universal moratorium on executions, arguing the right to life is fundamental."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "The majority of countries in the world have abolished the death penalty.", "answer": true, "evidence": "More than one hundred countries have abolished it in law or practice, while approximately fifty continue executions."},
    {"id": 2, "statement": "Capital punishment is consistently cheaper than life imprisonment.", "answer": false, "evidence": "Capital punishment is significantly more expensive than life imprisonment when mandatory legal appeal costs are included."},
    {"id": 3, "statement": "No person executed under the death penalty has later been found to be innocent.", "answer": false, "evidence": "More than one hundred and ninety people on death row have been exonerated after new evidence emerged."},
    {"id": 4, "statement": "Research supports the claim that the death penalty reduces crime more effectively than long prison sentences.", "answer": false, "evidence": "Research has consistently failed to demonstrate that the death penalty deters crime more effectively than long prison sentences."},
    {"id": 5, "statement": "Opponents of the death penalty argue that the right to life should not be conditional on behaviour.", "answer": true, "evidence": "Many argue that the right to life is fundamental and should not be conditional on behaviour."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "The execution of a person as legal punishment for a crime is called [BLANK].", "options": ["A) capital punishment", "B) life imprisonment", "C) criminal execution", "D) judicial killing"], "answer": "A", "explanation": "Capital punishment is the legally authorised killing of someone as punishment for a crime."},
    {"id": 2, "sentence": "Advocates argue the death penalty acts as a [BLANK] — a factor that discourages potential murderers from committing the crime.", "options": ["A) punishment", "B) consequence", "C) deterrent", "D) sanction"], "answer": "C", "explanation": "A deterrent is something that discourages or prevents people from doing something."},
    {"id": 3, "sentence": "Over one hundred and ninety people on death row in the US have been [BLANK] — officially cleared of guilt — after new evidence proved their innocence.", "options": ["A) acquitted", "B) released", "C) pardoned", "D) exonerated"], "answer": "D", "explanation": "Exonerated means officially declared free from blame or criminal responsibility, which is the word used in the passage."},
    {"id": 4, "sentence": "The United Nations has called for a [BLANK] on executions — a temporary prohibition — while debates about abolition continue.", "options": ["A) moratorium", "B) ban", "C) suspension", "D) pause"], "answer": "A", "explanation": "A moratorium is a temporary prohibition of an activity, which is what the UN has called for on executions."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that more than 190 innocent people have been exonerated from death row. Is the risk of executing innocent people sufficient reason alone to abolish the death penalty?", "suggested_answer": "For many, the risk of killing an innocent person is sufficient reason to abolish the death penalty entirely. No justice system is infallible, and the consequences of an error in capital cases are irreversible — unlike imprisonment, execution cannot be undone when new evidence emerges. If even a small number of innocent people are executed, the entire system of capital punishment loses its moral legitimacy. Some advocates of the death penalty respond that improved forensic evidence, including DNA testing, reduces this risk, but no justice system can guarantee zero errors. The irrevocability of death makes it categorically different from other punishments."},
    {"id": 2, "question": "Some countries retain the death penalty claiming it reflects their culture and values. Should international human rights standards override national decisions about punishment?", "suggested_answer": "This question touches on the tension between universal human rights and national sovereignty. The argument for international standards is that certain rights — including the right to life — are so fundamental that they cannot be legitimately waived by any government for any citizen. Rights exist to protect individuals from their governments, not to reflect cultural preferences. The counterargument is that imposing standards developed primarily in Western democratic contexts on other societies reflects a form of cultural imperialism. The resolution may lie in persuasion rather than imposition: international pressure, diplomatic engagement, and demonstrating the practical inadequacy of capital punishment can change minds more sustainably than top-down mandates."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 6) AND type = 'reading';

-- ── Lesson 7 ────────────────────────────────────────────────
UPDATE english_lesson_sections
SET content = $json${
  "title": "Youth Crime and Rehabilitation: Investing in Young Lives",
  "text": "Youth crime — offending by young people, typically those under eighteen — presents distinct challenges for criminal justice systems. Young people who commit crimes are still developing cognitively, emotionally, and socially, which affects their capacity for moral judgement and impulse control. Most jurisdictions therefore treat young offenders differently from adults, with separate youth justice systems, courts, and custodial facilities. The causes of youth crime are complex. Research consistently identifies key risk factors: poverty and economic disadvantage, family instability and neglect, poor educational engagement, association with delinquent peers, mental health difficulties, and exposure to violence or abuse. Membership in gangs significantly increases the risk of serious offending and victimisation. Protective factors — circumstances that reduce the likelihood of offending — include strong family support, positive engagement with school, access to community resources, and stable housing. Debates about how to respond to youth crime centre on two contrasting philosophies. The punitive approach holds that young offenders should face serious consequences including custody to deter themselves and others. The rehabilitative approach argues that punishment alone is ineffective for young people whose development is incomplete and whose trajectory can be redirected. Evidence strongly supports the rehabilitative approach. Early intervention programmes addressing risk factors before offending occurs, community-based alternatives to custody, mentoring, and education and employment support all show stronger results in preventing reoffending than incarceration alone. Countries with the lowest youth crime rates tend to combine strong social support systems with rehabilitative rather than punitive justice. Investing in young people early — in education, mental health support, and stable communities — consistently proves more cost-effective than managing the consequences of crime.",
  "glossary": [
    {"term": "delinquent", "definition": "a young person who regularly behaves in a criminal or antisocial way", "translation": "малолетний правонарушитель"},
    {"term": "custodial", "definition": "relating to imprisonment or being kept in custody", "translation": "связанный с лишением свободы"},
    {"term": "risk factors", "definition": "characteristics or circumstances that increase the likelihood of a negative outcome", "translation": "факторы риска"},
    {"term": "protective factors", "definition": "characteristics or circumstances that reduce the likelihood of a negative outcome", "translation": "защитные факторы"},
    {"term": "rehabilitation", "definition": "the process of helping someone change behaviour and reintegrate into society", "translation": "реабилитация"},
    {"term": "incarceration", "definition": "the state of being imprisoned or confined", "translation": "лишение свободы, заключение"}
  ],
  "comprehension_questions": [
    {"id": 1, "question": "Why do most justice systems treat young offenders differently from adults?", "options": ["A) Because the crimes committed by young people are always less serious", "B) Because young people are still developing cognitively, emotionally, and socially", "C) Because there are not enough adult prisons to accommodate young offenders", "D) Because public opinion consistently demands more lenient treatment for young people"], "answer": "B", "explanation": "Young people are still developing cognitively, emotionally, and socially, affecting their capacity for moral judgement and impulse control."},
    {"id": 2, "question": "Which of the following is described as a risk factor for youth offending?", "options": ["A) Participation in team sports and community activities", "B) Strong engagement with education and learning", "C) Association with delinquent peers and exposure to violence", "D) Access to mental health support and stable housing"], "answer": "C", "explanation": "Association with delinquent peers and exposure to violence are identified as risk factors for youth offending."},
    {"id": 3, "question": "What is the difference between the punitive and rehabilitative approaches to youth justice?", "options": ["A) The punitive approach focuses on prevention while the rehabilitative approach focuses on punishment", "B) The punitive approach uses custody to deter while rehabilitation redirects development", "C) The punitive approach is used for adults while rehabilitation is for young offenders", "D) The punitive approach is evidence-based while rehabilitation is theoretical"], "answer": "B", "explanation": "The punitive approach uses custody to deter, while rehabilitation argues punishment alone is ineffective for young people whose development can be redirected."},
    {"id": 4, "question": "What does evidence show about rehabilitation compared to incarceration for young offenders?", "options": ["A) Incarceration consistently produces better outcomes than rehabilitation", "B) Both approaches produce similar results in reducing reoffending", "C) Rehabilitation and early intervention show stronger results in preventing reoffending", "D) Evidence is inconclusive because youth justice systems vary too widely"], "answer": "C", "explanation": "Early intervention, community-based alternatives, and rehabilitation show stronger results in preventing reoffending than incarceration alone."},
    {"id": 5, "question": "What does the passage say about countries with the lowest youth crime rates?", "options": ["A) They use the strictest punitive measures including long sentences for young people", "B) They combine strong social support with rehabilitative rather than punitive justice", "C) They focus exclusively on prevention programmes in schools", "D) They have no separate youth justice system — young people are tried as adults"], "answer": "B", "explanation": "Countries with the lowest youth crime rates combine strong social support systems with rehabilitative rather than punitive justice."}
  ],
  "true_false_questions": [
    {"id": 1, "statement": "Most jurisdictions treat young offenders in exactly the same way as adult criminals.", "answer": false, "evidence": "Most jurisdictions treat young offenders differently from adults, with separate youth justice systems, courts, and custodial facilities."},
    {"id": 2, "statement": "Gang membership significantly increases the risk of serious offending and victimisation.", "answer": true, "evidence": "Membership in gangs significantly increases the risk of serious offending and victimisation."},
    {"id": 3, "statement": "Strong family support and positive school engagement are described as risk factors for youth crime.", "answer": false, "evidence": "Strong family support and positive engagement with school are protective factors that reduce the likelihood of offending."},
    {"id": 4, "statement": "Early intervention addressing risk factors before offending occurs is more effective than incarceration after the fact.", "answer": true, "evidence": "Early intervention programmes addressing risk factors before offending occurs show stronger results in preventing reoffending than incarceration alone."},
    {"id": 5, "statement": "Investing in education and mental health support for young people is less cost-effective than managing crime after it occurs.", "answer": false, "evidence": "Investing in young people early consistently proves more cost-effective than managing the consequences of crime."}
  ],
  "vocabulary_in_context": [
    {"id": 1, "sentence": "Young offenders are typically held in separate [BLANK] facilities rather than adult prisons.", "options": ["A) community", "B) custodial", "C) rehabilitative", "D) secure"], "answer": "B", "explanation": "Custodial means relating to imprisonment or being kept in custody."},
    {"id": 2, "sentence": "Poverty, family instability, and association with delinquent peers are all [BLANK] — circumstances that increase the likelihood of youth offending.", "options": ["A) causes", "B) triggers", "C) risk factors", "D) predictors"], "answer": "C", "explanation": "Risk factors are characteristics or circumstances that increase the likelihood of a negative outcome."},
    {"id": 3, "sentence": "Stable housing, school engagement, and strong family support are [BLANK] — circumstances that reduce the likelihood of offending.", "options": ["A) protective factors", "B) safety nets", "C) support systems", "D) positive influences"], "answer": "A", "explanation": "Protective factors are characteristics that reduce the likelihood of a negative outcome — the opposite of risk factors."},
    {"id": 4, "sentence": "Research shows community-based alternatives to [BLANK] — imprisonment — are more effective at preventing reoffending among young people.", "options": ["A) supervision", "B) detention", "C) incarceration", "D) custody"], "answer": "C", "explanation": "Incarceration is the state of being imprisoned or confined, which is what community-based alternatives aim to replace."}
  ],
  "critical_thinking": [
    {"id": 1, "question": "The passage argues that investing in early intervention is more cost-effective than managing crime later. Why do you think governments often prioritise punishment over prevention?", "suggested_answer": "Governments often prioritise punishment over prevention because punitive responses are more politically visible and emotionally satisfying in the short term. When a crime occurs, the public demand action — arrests, convictions, and sentences that signal seriousness. Prevention programmes take years to show results and operate quietly in the background. Politicians are rewarded electorally for being tough on crime rather than for funding invisible preventive programmes. There is also a temporal mismatch: the costs of prevention are immediate while the benefits — crimes not committed years later — are diffuse and hard to attribute. Better public education about what evidence shows actually works can gradually shift these incentives."},
    {"id": 2, "question": "The passage describes youth crime as a symptom of wider social problems including poverty and family instability. Does this mean young offenders bear less personal responsibility for their actions?", "suggested_answer": "Understanding the structural causes of youth crime does not eliminate personal responsibility, but it contextualises it. Young people who grow up in poverty, violence, and instability face genuine disadvantages in developing the self-regulation and decision-making capacity needed to avoid harmful choices. This context matters morally and practically — it tells us that harsh punishment alone is unlikely to be effective and that addressing root causes is essential. However, recognising context is different from excusing behaviour. Young people who harm others must still be held accountable in age-appropriate ways, and justice for victims remains important. The goal is a system that does both: holds young people responsible and simultaneously addresses the conditions that made offending likely."}
  ]
}$json$::jsonb
WHERE lesson_id = (
  SELECT l.id FROM english_lessons l JOIN english_modules m ON l.module_id = m.id
  JOIN english_courses c ON m.course_id = c.id
  WHERE c.title = 'B1 Intermediate' AND c.category = 'General English'
  AND m.order_index = 5 AND l.order_index = 7) AND type = 'reading';